### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by anchitgupt** [ContinuumIO/anaconda-issues#4793] opened 2017-08-30 16:53 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 22:22:42.721 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 22:22:42.936 NotebookApp] Serving notebooks from local directory: /home/anchit
[I 22:22:42.937 NotebookApp] 0 active kernels 
[I 22:22:42.937 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=8278e4ffc1cee232eeb1efdce0238fbe4c61505f6619d834
[I 22:22:42.937 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:22:42.940 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=8278e4ffc1cee232eeb1efdce0238fbe4c61505f6619d834
[9357:9393:0830/222247.822695:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[I 22:22:47.833 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 22:22:48.169 NotebookApp] 404 GET /robots.txt (127.0.0.1) 24.45ms referer=None

```
## System information
```
python: 3.6.1
language: en_IN
os: Linux;4.4.0-92-generic;#115~14.04.1-Ubuntu SMP Thu Aug 10 15:06:53 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-08-30 16:55
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-30 16:55 UTC
