### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by UditAnchalia** [ContinuumIO/anaconda-issues#6954] opened 2017-10-28 16:44 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 22:12:54.805 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 22:12:55.173 NotebookApp] [nb_anacondacloud] enabled
[I 22:12:55.179 NotebookApp] [nb_conda] enabled
[I 22:12:55.391 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 22:12:55.391 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 22:12:55.436 NotebookApp] Serving notebooks from local directory: /home/uditanchalia
[I 22:12:55.436 NotebookApp] 0 active kernels 
[I 22:12:55.437 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=e7234fbd842033ebdeb962a9e33c07a28302262fd9cb422b
[I 22:12:55.437 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:12:55.444 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=e7234fbd842033ebdeb962a9e33c07a28302262fd9cb422b
[I 22:12:56.474 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[19154:19194:1028/221256.547667:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

```
## System information
```
python: 3.5.3
pyqt: 5.6.0
qt: 5.6.2
conda: 4.3.27
platform: linux-64
os: Linux;4.4.0-96-generic;#119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017;x86_64;x86_64
version: 1.6.2
language: en_US
```

**Comment by goanpeca** [comment] 2017-10-29 04:39
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-29 04:39 UTC
Labels: pkg:navigator, reso:duplicate
