### ISSUE TITLE
anaconda navigator 5.0.1 for Mac crashes when starting with OS X Yosemite

### ISSUE THREAD

**Issue by schultz101** [ContinuumIO/anaconda-issues#6993] opened 2017-10-30 11:56 UTC
Dear all
This morning after having updated something in my operating system (now running Mac OS X Yosemite 10.10.5), Anaconda 3 5.0.1 Navigator crashes at lunch with the following error message:

```
Traceback (most recent call last):
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 313, in catch_zombie
yield
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 295, in wrapper
return fun(self, *args, **kwargs)
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
return cext.proc_cmdline(self.pid)
File "/Users/mauriziobetto/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
self.gen.throw(type, value, traceback)
File "/Users/mauriziobetto/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 326, in catch_zombie
raise AccessDenied(proc.pid, proc._name)
psutil.AccessDenied: psutil.AccessDenied (pid=638)
```

Any idea about what went wrong and how to fix it?
Any help is much appreciated.

Cheers

**Comment by goanpeca** [comment] 2017-10-30 13:06
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-30 13:06 UTC

**Comment by schultz101** [comment] 2017-10-30 13:30
thank you :-) I really appreciate your help.

**Comment by hanskwan** [comment] 2017-12-09 08:27
Cheers!!! It works for me, after updating. I thought I had a much bigger issue before coz I install two anaconda(Wanted the updated version)
