### ISSUE TITLE
Two local locations for environments

### ISSUE THREAD

**Issue by FMeines** [ContinuumIO/anaconda-issues#1598] opened 2017-04-12 10:22 UTC
I have recently install anaconda and I have encountered two local folders for the environments. One is located in program files folder and the other one is in user folder. My OS is windows 7 64b. So, I have two root environments too. And when I use conda through command line switches between both. When I return to root environment using conda, it goes to root in program files. Even when I was in an enviroment of user folder. This behavior is normal?

Sorry, but i posted this issue here and in the anaconda issues channel because I don't know which one is related to. Please, you can close that are not related.

**Comment by nehaljwani** [comment] 2017-05-17 05:39
Closing as duplicate of https://github.com/conda/conda/issues/5040

**Closed by nehaljwani** 2017-05-17 05:39 UTC
Labels: reso:duplicate
