### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rsmkung** [ContinuumIO/anaconda-issues#8517] opened 2018-02-11 06:37 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=7176)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Sheng-Miao\Anaconda\envs\py36\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Sheng-Miao\Anaconda\envs\py36\lib\site-packages\psutil\_pswindows.py", line 705, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sheng-Miao\Anaconda\envs\py36\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Sheng-Miao\Anaconda\envs\py36\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Sheng-Miao\Anaconda\envs\py36\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Sheng-Miao\Anaconda\envs\py36\lib\site-packages\psutil\__init__.py", line 666, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Sheng-Miao\Anaconda\envs\py36\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=7176)

```
## System information
```
python: 3.6.4
language: en_US
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family

**Comment by goanpeca** [comment] 2018-02-11 06:41
Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1984 for more information on how to fix this.**

Or you can run on the Terminal or Anaconda prompt:

```
ancaonda-navigator --reset
```

**Closed by goanpeca** 2018-02-11 06:41 UTC
Labels: pkg:navigator, reso:duplicate
