### ISSUE TITLE
Wont launch after download

### ISSUE THREAD

**Issue by kamal23t** [ContinuumIO/anaconda-issues#8947] opened 2018-03-20 18:14 UTC
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/mhcuser/Library/Application Support/binstar/config.yaml", line 1, column 1

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by ewilansky** [comment] 2018-03-20 19:11
Try this: 
conda install anaconda-client=1.6.11

I ran into the same problem and found this previously posted issue: https://github.com/ContinuumIO/anaconda-issues/issues/8568

**Comment by goanpeca** [comment] 2018-03-20 20:55
@ewilansky is right!

Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.11
```

**Closed by goanpeca** 2018-03-20 20:55 UTC
