### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by GeeHLee** [ContinuumIO/anaconda-issues#9069] opened 2018-04-02 11:13 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
## Traceback
```
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "D:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```
## System information
```
python: 3.6.1
language: fr_FR
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by sweemeng** [comment] 2018-04-02 11:15
On same OS and the command `conda help` raise the following exception

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\cli\main.py", line 103, in _main
    from ..base.context import context
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\sweem\.condarc", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\cli\main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 579, in print_unexpected_error_message
    from .base.context import context
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\sweem\.condarc", position 0
```

**Comment by goanpeca** [comment] 2018-04-02 11:16
Closing as duplicate of #1837

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1837 for more information on how to fix this.**

**Closed by goanpeca** 2018-04-02 11:16 UTC
Labels: pkg:navigator, reso:duplicate
