### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by MasiCal354** [ContinuumIO/anaconda-issues#4985] opened 2017-09-04 01:24 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: /home/masical354/anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area '/home/masical354/anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="/home/masical354/anaconda3"

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.10.0-33-generic;#37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-09-04 01:26
**See Issue #1845 for more information on how to fix this.**

---

Closing as duplicate of #1845


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-09-04 01:26 UTC
Labels: pkg:navigator
