### ISSUE TITLE
Completely shield anaconda from system qt libs?

### ISSUE THREAD

**Issue by bk322** [ContinuumIO/anaconda-issues#63] opened 2014-01-20 11:05 UTC
The problem
===========

I hit into a confilict of anaconda (1.8) Qt libs version 4.8.5:

```bash
$ find $ANACONDA/lib -name '*.4.8.5'
/home/boris/cmp/soft/sft/anaconda/lib/libQtTest.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtCLucene.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtCore.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtOpenGL.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtSql.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtHelp.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtMultimedia.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtScript.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtNetwork.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtScriptTools.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtXml.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtDesigner.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtDesignerComponents.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtSvg.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtXmlPatterns.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtGui.so.4.8.5
/home/boris/cmp/soft/sft/anaconda/lib/libQtDeclarative.so.4.8.5
```

with system (Kubuntu alpha) Qt libs:

```bash
$ find /usr/lib -name "*so.4.8.6"
/usr/lib/i386-linux-gnu/libQtDeclarative.so.4.8.6
/usr/lib/i386-linux-gnu/libQtXml.so.4.8.6
/usr/lib/i386-linux-gnu/libQtCLucene.so.4.8.6
/usr/lib/i386-linux-gnu/libQtNetwork.so.4.8.6
/usr/lib/i386-linux-gnu/libQtXmlPatterns.so.4.8.6
/usr/lib/i386-linux-gnu/libQtScript.so.4.8.6
/usr/lib/i386-linux-gnu/libQtCore.so.4.8.6
/usr/lib/i386-linux-gnu/libQtOpenGL.so.4.8.6
/usr/lib/i386-linux-gnu/libQtDBus.so.4.8.6
/usr/lib/i386-linux-gnu/libQtSql.so.4.8.6
/usr/lib/i386-linux-gnu/libQtGui.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQt3Support.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtScriptTools.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtDeclarative.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtXml.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtSvg.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtTest.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtDesigner.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtCLucene.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtNetwork.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtXmlPatterns.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtHelp.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtDesignerComponents.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtScript.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtCore.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtDBus.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtSql.so.4.8.6
/usr/lib/x86_64-linux-gnu/libQtGui.so.4.8.6
```
So I can't use default matplotlib backend:

```python
#!/usr/bin/env python

import sys

# to ensure the script runs in anaconda do:
# $ export ANACONDA=/path/to/anaconda
import os
try:
    os.environ["ANACONDA"]
    sys.path.insert(1, os.environ["ANACONDA"] + "/lib/python2.7/site-packages")
except KeyError:
    pass

# test matplotlib:
from matplotlib import pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(range(5), range(5), "ro")
fig.savefig("test.svg")
```
gives:

```
Cannot mix incompatible Qt library (version 0x40806) with this library (version 0x40805)
Aborted
```
My question is: how do I prevent anaconda from loading system qt libs?

I tried
=======

i tried the workaround proposed [here](https://github.com/conda/conda-recipes/issues/22)

I made a `qt.conf` in `$ANACONDA/bin`:

```
[Paths]
Prefix = '.'
```

and issued

```bash
$ QT_PLUGIN_PATH=''
```

It didn't help.

I also tried to nullify `LD_LIBRARY_PATH` from the shell as well as from the script:

```python
os.environ["LD_LIBRARY_PATH"] = ""
```

Nothing works.

The workaround
==============

In this exact problem -- a problem of using matplotlib -- a quick workaroud is to use another backend:

```python
import matplotlib
matplotlib.use("svg")
```

A possible solution
===================

I think the ideal solution is to do something like a *css reset* to qt environment variables before running anaconda's python. I'd do this but I don't know which environment variables are responsible for where qt looks for libraries. I've no experience of qt.

Another possible solution is to have a way to force qt version in anaconda.

**Comment by astrofrog** [comment] 2015-02-12 17:25
This appears to still be happening - is there a proper fix for this?

**Comment by keflavich** [comment] 2015-02-13 15:18
I'm also experiencing this issue.  Should I try a different backend?

**Comment by ccordoba12** [comment] 2015-02-14 22:28
Yes, there is a fix for this. I'm working on it right now for the next Anaconda release.

The problem is Oxygen (the default KDE window decoration system) requires dbus to run, and the current Anaconda build doesn't come with QtDbus.

So when an Anacoda application is ran inside KDE, it resorts to grab QtDbus from the system. That's what generates this problem.

In fact, this is a duplicate of issue #32, so I'm closing it.

**Closed by ccordoba12** 2015-02-14 22:28 UTC
Labels: duplicate

**Comment by evanthebouncy** [comment] 2018-05-20 06:51
Yes, there is a fix for this. I'm working on it right now for the next Anaconda release.

still broken after 3 years BabyRage

**Comment by msarahan** [comment] 2018-05-20 14:15
@evanthebouncy what is the fix you would propose?  We'd be happy to include it if it works.

**Comment by evanthebouncy** [comment] 2018-06-12 21:04
I was quoting ccordobas comment from 3 years ago haha
