### ISSUE TITLE
 cmake fails at startup on OS X 10.6 with "dyld: Symbol not found: _kSecImportExportPassphrase"

### ISSUE THREAD

**Issue by benmwebb** [ContinuumIO/anaconda-issues#412] opened 2015-08-18 22:25 UTC
(See also conda/conda-recipes#368; I'm guessing that was the wrong place to report this issue.)

On an OS X 10.6 machine, cmake (3.2.3) doesn't work:

    $ conda install cmake
    [...]
    $ cmake
    dyld: Symbol not found: _kSecImportExportPassphrase
      Referenced from: /tmp/conda.3093/bin/cmake
      Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
     in /tmp/conda.3093/bin/cmake
    Trace/BPT trap

Looks like the cmake package just needs to be rebuilt on a 10.6 (or older?) Mac. I rebuilt it myself on a 10.6 machine, and it works fine for me: https://anaconda.org/salilab/cmake-mac

I see from the [conda docs](http://conda.pydata.org/docs/building/environment-vars.html) that MACOSX_DEPLOYMENT_TARGET is set to 10.6, so I guess 10.6 is your intended floor (the Anaconda quickstart guide doesn't specify a minimum version of OS X). My guess is the machine you built cmake on is a fairly new Mac with a recent XCode, and since Apple only provides SDKs for 10.10 and 10.9 nowadays, the deployment target is ignored?

**Comment by ccordoba12** [comment] 2015-08-19 00:35
I don't think we're going to rebuild cmake on 10.6, sorry. You're the first person to ask for it.

**Comment by benmwebb** [comment] 2015-08-19 23:24
No need to apologise to me, since I built my own cmake package anyway. I just thought you'd like to know that your package is broken.

**Comment by ccordoba12** [comment] 2015-08-20 00:00
Broken in *10.6*, but as I said, you're the first person to notice it.

**Comment by ccordoba12** [comment] 2015-08-20 00:17
Closing as duplicate of #413.

**Closed by ccordoba12** 2015-08-20 00:17 UTC
