### ISSUE TITLE
Anacpmda startup error

### ISSUE THREAD

**Issue by eharperink** [ContinuumIO/anaconda-issues#3549] opened 2017-07-25 13:36 UTC
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-11-14 23:05
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-14 23:05 UTC
