### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by dhakaddhandera** [ContinuumIO/anaconda-issues#4584] opened 2017-08-24 07:18 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda3"

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;x86;x86 Family 6 Model 42 Stepping 7, GenuineIntel
version: 1.6.2
platform: win-32
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-08-24 07:19
**See Issue #1845 for more information on how to fix this.**

---

Closing as duplicate of #1845


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Comment by dhakaddhandera** [comment] 2017-08-24 07:19
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda3"

**Closed by goanpeca** 2017-08-24 07:19 UTC
Labels: pkg:navigator

**Comment by dhakaddhandera** [comment] 2017-08-24 07:21
anaconda prompt is taking cammand conda update conda what to  do

**Comment by goanpeca** [comment] 2017-08-24 11:52
@dhakaddhandera you install for all users, so every time you want to install on root you wont be able to unless you start navigator with Admin privileges.

Please install for current user only.
