### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Techgitgood** [ContinuumIO/anaconda-issues#4354] opened 2017-08-17 16:53 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=516)
## Traceback
```
Traceback (most recent call last):
  File "/Users/jfigueroa/miniconda3/envs/py3k/lib/python3.6/site-packages/psutil/_psosx.py", line 293, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/jfigueroa/miniconda3/envs/py3k/lib/python3.6/site-packages/psutil/_psosx.py", line 356, in cmdline
    return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jfigueroa/miniconda3/envs/py3k/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/jfigueroa/miniconda3/envs/py3k/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/jfigueroa/miniconda3/envs/py3k/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/jfigueroa/miniconda3/envs/py3k/lib/python3.6/site-packages/psutil/__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "/Users/jfigueroa/miniconda3/envs/py3k/lib/python3.6/site-packages/psutil/_psosx.py", line 306, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=516)

```
## System information
```
python: 3.6.1
language: en
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.24
```

**Comment by goanpeca** [comment] 2017-08-17 16:53
**See Issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-17 16:53 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by Techgitgood** [comment] 2017-08-17 17:55
Temporary Workaround Found: 
Behavior reported:
    The traceback occurred the day after an "authentication.add' was performed ; 
           "<username> replaced the token Anaconda Navigator to the account <username> "
    After a complete reboot.
    When a GUI icon dbl-click launch was made of Anaconda Navigator (app).
           Located within miniconda3/envs/py3k/Anaconda-Navigator

Workaround:
Run as sudo the traceback executable  Using OSX (10.11.6) Terminal (2.6.1) to 
       $ sudo miniconda3/envs/py3k/bin/anaconda-navigator
          Navigator GUI opened. But I noted an "...initializing" message during splash screen.

Behavior after workaround:
Workaround test; 
       the Navigator GUI was closed.
       then another launch was attempted, but not from the sudo CLI, 
                this time from the Anaconda Navigator (app).
       the Anaconda Navigator (app) opened as it did the day prior,
             superficial test of tabs; Home , Environments, Learning appeared functional.
