### ISSUE TITLE
Spyder freezes when trying to assign np.array to variable

### ISSUE THREAD

**Issue by dmenin** [ContinuumIO/anaconda-issues#708] opened 2016-03-16 17:03 UTC
Hi, I'm experiencing the following problem, can someone advise if a bug or maybe something wrong on my environment?
Thanks

```
import numpy as np
l = []
foo = ['AAAA', 16, 0, 1, 0, 0, 0]
foo1 = ['BBBB', 8,  0, 0, 0, 0, 0]
l.append(foo)
l.append(foo1)
#calling np.array on the list works fine:
np.array(l)
```
Output:

```
array([['AAAA', '16', '0', '1', '0', '0', '0'],
       ['BBBB', '8', '0', '0', '0', '0', '0']], 
      dtype='|S4')
```

if I try to assign the result to a variable, Spider freezes:
`test = np.array(l)`

*Doesn't happen if I run the same code on Jupyter 

Version:

```
import sys
sys.version
Out[2]: '2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.1500 64 bit (AMD64)]'
```

**Comment by ccordoba12** [comment] 2016-03-16 17:15
The problem (I think) are string elements in the array. I'm working on fixing it for Spyder 2.3.9.

For now I'm going to close this issue as a duplicate of issue spyder-ide/spyder#2983.

**Closed by ccordoba12** 2016-03-16 17:15 UTC

**Comment by dmenin** [comment] 2016-03-16 17:17
thanks you for your prompt response. It does seem like the same issue.
Any known work around?

**Comment by ccordoba12** [comment] 2016-03-16 17:19
Not that I know of, sorry. But 2.3.9 should be ready next week :-)
