### ISSUE TITLE
Spyder copy/paste omits last character

### ISSUE THREAD

**Issue by c-mori** [ContinuumIO/anaconda-issues#452] opened 2015-09-23 21:35 UTC
Copying and pasting within Spyder leaves off the last character of the buffer.

Copy: "Hello world"
Paste: "Hello worl"

Thanks

**Comment by ccordoba12** [comment] 2015-09-24 03:02
Closing as duplicate of spyder-ide/spyder#2710.

**Closed by ccordoba12** 2015-09-24 03:02 UTC
