### ISSUE TITLE
An unexpected error occurred on Navigator start-up. AccessDenied: psutil.AccessDenied (pid=439)

### ISSUE THREAD

**Issue by nazarih** [ContinuumIO/anaconda-issues#5570] opened 2017-09-16 00:55 UTC
Traceback (most recent call last):
File "/Users/hamid/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/hamid/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/hamid/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/hamid/anaconda/lib/python2.7/site-packages/psutil/__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "/Users/hamid/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 306, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=439)

**Comment by goanpeca** [comment] 2017-09-16 03:24
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-16 03:24 UTC

**Comment by nazarih** [comment] 2017-09-16 20:30
I tried this, but I still got the same error. Navigator failed to launch on MacOS Sierra.

**Comment by aanand1008** [comment] 2017-12-12 17:37
I am also getting same error as below:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=9724)



I have run below commands in order to solve this issue in vain:
$ conda update anaconda-navigator
$ conda update navigator-updater
$ conda update --prefix C:\ProgramData\Anaconda3 anaconda

Kindly help me to solve this issue. Nothing worked for me

**Comment by taymourniazi** [comment] 2018-01-19 10:23
An unexpected error occurred on Navigator start-up
psutil.AccessDenied
So I used several commands like
-	Conda update anaconda-navigator
-	Conda update navigator-updater
-	Conda update --prefix C:\Users\asd\Anaconda2 anaconda
It all doesn’t fix the issue only the following work fine
-	Anaconda-navigator --reset
