### ISSUE TITLE
Unable to open Anaconda Navigator in Windows10

### ISSUE THREAD

**Issue by muthu492** [ContinuumIO/anaconda-issues#4437] opened 2017-08-20 05:57 UTC
i have installed the following file 'Anaconda-4.4.0-Windows-x86_64' in Windows10. When I try to open 'Anaconda Navigator', it is not opening but throwing the below error in IE. I tried with both 32 bit and 64 bit versions.

*****Error when I try to open Anaconda Navigator*****

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\Muthu Rengan\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-08-20 05:57
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-20 05:57 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by muthu492** [comment] 2017-08-21 12:19
Thanks Goanpeca,

I am using the latest version of anaconda Navigator. 
Anaconda command prompt is also not working. 
System details: 
Os: windows 10 64 bit

Please help me to fix this issue. Thanks..

**Comment by goanpeca** [comment] 2017-08-21 16:29
>Anaconda command prompt is also not working.

What do you mean?

**Comment by muthu492** [comment] 2017-08-22 04:54
when I try to open Anaconda prompt the following message is displayed.
failed to create process.
failed to create process.
failed to create process.

C:\Users\Muthu Rengan>

**Comment by goanpeca** [comment] 2017-08-22 13:43
@muthu492 the problem is most likely related to the spaces in your path. Please remove anaconda and then reinstall it in a path without spaces.

**Comment by muthu492** [comment] 2017-08-22 18:14
Thanks Goanpeca. It is now working :)

**Comment by Piyupranav** [comment] 2018-05-27 14:19
'C:\Users\piyup\Anaconda3\Scripts\activate.bat' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\piyup>
When I start the anaconda prompt this is what is displayed. And I am not able to locate anything in start menu after installing anaconda v5.1 and python v3.6.
