### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Kumapapa2012** [ContinuumIO/anaconda-issues#3255] opened 2017-07-17 01:40 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 09:40:42.481 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 09:40:42.516 NotebookApp] Serving notebooks from local directory: /home/kmori
[I 09:40:42.516 NotebookApp] 0 active kernels 
[I 09:40:42.516 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=1f505cf0ac0b7ae20fdbeb1eb2e37b815f09a350e673629c
[I 09:40:42.516 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:40:42.518 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=1f505cf0ac0b7ae20fdbeb1eb2e37b815f09a350e673629c
[29913:29950:0717/094043.105926:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[I 09:40:43.149 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1

```
## System information
```
python: 3.6.1
language: ja_JP
os: Linux;4.4.0-83-generic;#106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-11-14 22:44
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-14 22:44 UTC
