### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by AIFatima** [ContinuumIO/anaconda-issues#9167] opened 2018-04-13 13:15 UTC
The following errors occured:

None:
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/pro/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/pro/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004EF5978>, 'Connection to repo.continuum.io timed out. (connect timeout=9.15)'))",),)

{'python': '3.5.2', 'version': '1.2.1', 'qt': '4.8.7', 'platform': 'win-64', 'pyqt': '4.11.4', 'conda': '4.3.30', 'os': 'Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'language': 'zh_CN'}

**Comment by goanpeca** [comment] 2018-04-13 13:18
Closing as duplicate of #1932

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1932 for more information on how to fix this.**

**Closed by goanpeca** 2018-04-13 13:18 UTC
Labels: pkg:navigator, reso:duplicate
