### ISSUE TITLE
Navigator won't start (Had Microsoft update yesterday)

### ISSUE THREAD

**Issue by PrinterMark** [ContinuumIO/anaconda-issues#8558] opened 2018-02-15 01:37 UTC
### Actual Behavior

Web page:file: ///C:/Users/Mark/AppData/Local/Temp/tmp34dfqleu.html
Opens with error message:
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
byte indices must be integers or slices, not str
Traceback
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1270, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._conda_api = CondaAPI()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1663, in CondaAPI
    CONDA_API = _CondaAPI()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 346, in __init__
    self.set_conda_prefix()
  File "E:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

### Expected Behavior

...in place of the directory window where I can select my pynb code

### Steps to Reproduce

just restart Navigator

##### Anaconda or Miniconda version:
anaconda-client-1.6.5-py36hd36550c_0\Scripts

##### Operating System:
Windows 10

##### `conda info`

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 743, in __call__
        return func(*args, **kwargs)
      File "E:\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "E:\Anaconda3\lib\site-packages\conda\base\context.py", line 225, in __init__
        argparse_args=argparse_args)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "E:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "E:\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
        Reader.__init__(self, stream)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
        self.determine_encoding()
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
        self.update(1)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
        self.check_printable(data)
      File "E:\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Mark\.condarc", position 0

`$ E:\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.

```

##### `conda list --show-channel-urls`

```
environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=E:\Anaconda3
                 HOMEPATH=\Users\Mark
                     PATH=E:\Anaconda3\Library\bin;e:\Users\Mark\Anaconda3;e:\Users\Mark\Anaconda3\Scripts;c:
                          \users\mark\appdata\local\enthought\canopy\user\scripts;C:\Users\Mark\
                          AppData\Local\Enthought\Canopy\User;C:\Users\Mark\AppData\Local\Enthou
                          ght\Canopy\User\Scripts;C:\Users\Mark\AppData\Local\Microsoft\WindowsA
                          pps;E:\graphviz-feedstock-master;
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
               PYTHONPATH=E:\Python33\mglearn
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Mark\.condarc
 populated config files :
          conda version : 4.4.7
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : E:\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : E:\Anaconda3\pkgs
                          C:\Users\Mark\AppData\Local\conda\conda\pkgs
       envs directories : E:\Anaconda3\envs
                          C:\Users\Mark\AppData\Local\conda\conda\envs
                          C:\Users\Mark\.conda\envs
               platform : win-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

**Comment by goanpeca** [comment] 2018-02-15 01:47
Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #1837 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-02-15 01:47 UTC
