### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by htpybk** [ContinuumIO/anaconda-issues#3526] opened 2017-07-25 01:27 UTC
Hi. May I ask what should I do to fix following error?

I installed Anaconda2 to my Macbook and have this error after I shut down my Mac and reopen it on next day.

## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=559)
## Traceback
```
Traceback (most recent call last):
  File "/Users/peteryung/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/peteryung/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/peteryung/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/peteryung/anaconda/lib/python2.7/site-packages/psutil/__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "/Users/peteryung/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 306, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=559)

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-07-25 01:27
**See Issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-25 01:27 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by htpybk** [comment] 2017-07-25 01:46
Wow...what a quick response! Problem is fixed. Many thanks!
