### ISSUE TITLE
getting this error while updating any package

### ISSUE THREAD

**Issue by rimiprasad** [ContinuumIO/anaconda-issues#4816] opened 2017-08-31 04:49 UTC
(C:\ProgramData\Anaconda3) C:\Users\riprasad>conda update anaconda-navigator
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/<anaconda_dot
_org_username>/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_ser
ver_certificate', 'certificate verify failed')],)",),),)

**Comment by goanpeca** [comment] 2017-08-31 04:49
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-31 04:49 UTC
Labels: pkg:navigator, reso:duplicate
