### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hendricksonsarahl** [ContinuumIO/anaconda-issues#1939] opened 2017-06-04 19:27 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=972)
## Traceback
```
Traceback (most recent call last):
  File "/Users/sarah/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 293, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/sarah/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 356, in cmdline
    return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sarah/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/sarah/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/sarah/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/sarah/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "/Users/sarah/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 306, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=972)

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.5.0;Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by nehaljwani** [comment] 2017-06-04 19:28
Related #1867

**Comment by goanpeca** [comment] 2017-06-08 21:04
Closing as duplicate of #1984

**Closed by goanpeca** 2017-06-08 21:04 UTC
Labels: pkg:navigator, reso:duplicate
