### ISSUE TITLE
Anaconda navigator does not remember "yes, and don't ask me again" on the "help improve anaconda" popup window

### ISSUE THREAD

**Issue by jeremymatt** [ContinuumIO/anaconda-issues#9761] opened 2018-07-14 20:04 UTC
As requested:
https://groups.google.com/a/continuum.io/forum/?fromgroups#!topic/anaconda/AZ53DreeDpY

### Actual Behavior

Each time I open Anaconda Navigator, I see a popup window asking me if I want to help improve Anaconda Navigator.  This shows up despite clicking "Ok, and don't ask me again".  I've tried both with and without "Yes, I'd like to help improve Anaconda" checked and have tried clicking the plain "ok" button as well.  The message keeps coming back no matter what I do.

![anaconda](https://user-images.githubusercontent.com/32210294/42728008-19eeedd4-876e-11e8-941c-c4a36dd9fd63.png)

### Expected Behavior

When I click "OK, and don't ask me again", I expect that the program will remember my choice and not ask me again

### Steps to Reproduce

1. Close Anaconda Navigator
2. Open Anaconda Navigator

##### `conda info`

from Windows 10:
```

(base) C:\Users\jmatt>conda info

     active environment : base
    active env location : C:\Users\jmatt\Anaconda3
            shell level : 1
       user config file : C:\Users\jmatt\.condarc
 populated config files : C:\Users\jmatt\.condarc
          conda version : 4.5.5
    conda-build version : 3.10.9
         python version : 3.6.6.final.0
       base environment : C:\Users\jmatt\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\jmatt\Anaconda3\pkgs
                          C:\Users\jmatt\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jmatt\Anaconda3\envs
                          C:\Users\jmatt\AppData\Local\conda\conda\envs
                          C:\Users\jmatt\.conda\envs
               platform : win-64
             user-agent : conda/4.5.5 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

From Windows 10:
```
(base) C:\Users\jmatt>conda list --show-channel-urls
# packages in environment at C:\Users\jmatt\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0    defaults
alabaster                 0.7.11                   py36_0    defaults
anaconda                  custom           py36h363777c_0    defaults
anaconda-client           1.6.14                   py36_0    defaults
anaconda-navigator        1.8.7                    py36_0    defaults
anaconda-project          0.8.2            py36hfad2e28_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.5                    py36_0    defaults
astropy                   3.0.3            py36hfa6e2cd_2    defaults
atomicwrites              1.1.5                    py36_0    defaults
attrs                     18.1.0                   py36_0    defaults
babel                     2.6.0                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0              py36h81696a8_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2    defaults
beautifulsoup4            4.6.0            py36hd4cc5e8_1    defaults
bitarray                  0.8.2            py36hfa6e2cd_0    defaults
bkcharts                  0.2              py36h7e685f7_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3           py36h8a29ca5_0    defaults
bleach                    2.1.3                    py36_0    defaults
blosc                     1.14.3               he51fdeb_0    defaults
bokeh                     0.13.0                   py36_0    defaults
boto                      2.48.0           py36h1a776d2_1    defaults
bottleneck                1.2.1            py36hd119dfa_0    defaults
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.4.16                py36_0    defaults
cffi                      1.11.5           py36h945400d_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
click                     6.7              py36hec8c647_0    defaults
cloudpickle               0.5.3                    py36_0    defaults
clyent                    1.2.2            py36hb10d595_1    defaults
colorama                  0.3.9            py36h029ae33_0    defaults
comtypes                  1.1.4                    py36_0    defaults
conda                     4.5.5                    py36_0    defaults
conda-build               3.10.9                   py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h065de53_0    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
contextlib2               0.5.5            py36he5d52c0_0    defaults
cryptography              2.2.2            py36hfa6e2cd_0    defaults
curl                      7.60.0               h7602738_0    defaults
cycler                    0.10.0           py36h009560c_0    defaults
cython                    0.28.3           py36hfa6e2cd_0    defaults
cytoolz                   0.9.0.1          py36hfa6e2cd_0    defaults
dask                      0.18.1                   py36_0    defaults
dask-core                 0.18.1                   py36_0    defaults
datashape                 0.5.4            py36h5770b85_0    defaults
decorator                 4.3.0                    py36_0    defaults
distributed               1.22.0                   py36_0    defaults
docutils                  0.14             py36h6012d8f_0    defaults
entrypoints               0.2.3            py36hfd66bb0_2    defaults
et_xmlfile                1.0.1            py36h3d2d736_0    defaults
fastcache                 1.0.2            py36hfa6e2cd_2    defaults
filelock                  3.0.4                    py36_0    defaults
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.6                    py36_0    defaults
freetype                  2.8                  h51f8f2c_1    defaults
geographiclib             1.49                       py_0    conda-forge
geopy                     1.14.0                     py_0    conda-forge
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.3.4            py36hfa6e2cd_0    defaults
glob2                     0.6              py36hdf76b57_0    defaults
greenlet                  0.4.13           py36hfa6e2cd_0    defaults
h5py                      2.8.0            py36h3bdd7fb_0    defaults
hdf5                      1.10.2               hac2f561_1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1            py36h047fa9f_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.7                      py36_0    defaults
imageio                   2.3.0                    py36_0    defaults
imagesize                 1.0.0                    py36_0    defaults
intel-openmp              2018.0.3                      0    defaults
ipykernel                 4.8.2                    py36_0    defaults
ipython                   6.4.0                    py36_0    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
ipywidgets                7.2.1                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              0.24             py36hb6c5a24_1    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.12.0                   py36_1    defaults
jinja2                    2.10             py36h292fed1_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter                   1.0.0                    py36_4    defaults
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           5.2.0            py36h6d89b47_1    defaults
jupyter_core              4.4.0            py36h56e9d50_0    defaults
jupyterlab                0.32.1                   py36_0    defaults
jupyterlab_launcher       0.10.5                   py36_0    defaults
kiwisolver                1.0.1            py36h12c3424_0    defaults
krb5                      1.16.1               h038dc86_6    defaults
lazy-object-proxy         1.3.1            py36hd1c21d2_0    defaults
libcurl                   7.60.0               hc4dcbb0_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.34               h79bbb47_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libssh2                   1.8.0                hd619d38_4    defaults
libtiff                   4.0.9                hb8ad9f9_1    defaults
libxml2                   2.9.8                hadb2253_1    defaults
libxslt                   1.1.32               hf6f1972_0    defaults
llvmlite                  0.23.2           py36he51fdeb_0    defaults
locket                    0.2.0            py36hfed976d_1    defaults
lxml                      4.2.2            py36hef2cd61_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.0              py36h0e26971_1    defaults
matplotlib                2.2.2            py36h153e9ff_1    defaults
mccabe                    0.6.1            py36hb41005a_1    defaults
menuinst                  1.4.14           py36hfa6e2cd_0    defaults
mistune                   0.8.3            py36hfa6e2cd_1    defaults
mkl                       2018.0.3                      1    defaults
mkl-service               1.1.2            py36h57e144c_4    defaults
mkl_fft                   1.0.1            py36h452e1ab_0    defaults
mkl_random                1.0.1            py36h9258bd6_0    defaults
more-itertools            4.2.0                    py36_0    defaults
mpmath                    1.0.0            py36hacc8adf_2    defaults
msgpack-python            0.5.6            py36he980bc4_0    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.5.0                    py36_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.3.1            py36h8dc0fde_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
networkx                  2.1                      py36_0    defaults
nltk                      3.3.0                    py36_0    defaults
nose                      1.3.7            py36h1c3779e_2    defaults
notebook                  5.5.0                    py36_0    defaults
numba                     0.38.1           py36h830ac7b_0    defaults
numexpr                   2.6.5            py36hcd2f87e_0    defaults
numpy                     1.14.5           py36h9fa60d3_1    defaults
numpy-base                1.14.5           py36h5c71026_1    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36h7560279_0    defaults
olefile                   0.45.1                   py36_0    defaults
openpyxl                  2.5.4                    py36_0    defaults
openssl                   1.0.2o               h8ea7d77_0    defaults
packaging                 17.1                     py36_0    defaults
pandas                    0.23.1           py36h830ac7b_0    defaults
pandoc                    2.2.1                h1a437c5_0    defaults
pandocfilters             1.4.2            py36h3ef6317_1    defaults
parso                     0.2.1                    py36_0    defaults
partd                     0.3.8            py36hc8e763b_0    defaults
path.py                   11.0.1                   py36_0    defaults
pathlib2                  2.3.2                    py36_0    defaults
patsy                     0.5.0                    py36_0    defaults
pep8                      1.7.1                    py36_0    defaults
pickleshare               0.7.4            py36h9de030f_0    defaults
pillow                    5.1.0            py36h0738816_0    defaults
pip                       10.0.1                   py36_0    defaults
pkginfo                   1.4.2                    py36_1    defaults
pluggy                    0.6.0            py36hc7daf1e_0    defaults
ply                       3.11                     py36_0    defaults
prompt_toolkit            1.0.15           py36h60b8f86_0    defaults
psutil                    5.4.6            py36hfa6e2cd_0    defaults
py                        1.5.3                    py36_0    defaults
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pycrypto                  2.6.1            py36hfa6e2cd_9    defaults
pycurl                    7.43.0.2         py36h74b6da3_0    defaults
pyflakes                  2.0.0                    py36_0    defaults
pygments                  2.2.0            py36hb010967_0    defaults
pylint                    1.9.2                    py36_0    defaults
pyodbc                    4.0.23           py36h6538335_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.2.0            py36h785a196_1    defaults
pyqt                      5.9.2            py36h1aa27d4_0    defaults
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.4.4            py36he6f6034_0    defaults
pytest                    3.6.2                    py36_0    defaults
pytest-arraydiff          0.2                      py36_0    defaults
pytest-astropy            0.4.0                    py36_0    defaults
pytest-doctestplus        0.1.3                    py36_0    defaults
pytest-openfiles          0.3.0                    py36_0    defaults
pytest-remotedata         0.3.0                    py36_0    defaults
python                    3.6.6                hea74fb7_0    defaults
python-dateutil           2.7.3                    py36_0    defaults
pytz                      2018.4                   py36_0    defaults
pywavelets                0.5.2            py36hc649158_0    defaults
pywin32                   223              py36hfa6e2cd_1    defaults
pywinpty                  0.5.4                    py36_0    defaults
pyyaml                    3.12             py36h1d1928f_1    defaults
pyzmq                     17.0.0           py36hfa6e2cd_1    defaults
qt                        5.9.6            vc14h62aca36_0    defaults
qtawesome                 0.4.4            py36h5aa48f6_0    defaults
qtconsole                 4.3.1            py36h99a29a9_0    defaults
qtpy                      1.4.2                    py36_0    defaults
requests                  2.19.1                   py36_0    defaults
rope                      0.10.7           py36had63a69_0    defaults
ruamel_yaml               0.15.37          py36hfa6e2cd_2    defaults
scikit-image              0.14.0           py36h6538335_1    defaults
scikit-learn              0.19.1           py36h53aea1b_0    defaults
scipy                     1.1.0            py36h672f292_0    defaults
seaborn                   0.8.1            py36h9b69545_0    defaults
send2trash                1.5.0                    py36_0    defaults
setuptools                39.2.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
sip                       4.19.8           py36h6538335_0    defaults
six                       1.11.0           py36h4db2310_1    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           1.2.1            py36h763602f_0    defaults
sortedcollections         1.0.1                    py36_0    defaults
sortedcontainers          2.0.4                    py36_0    defaults
sphinx                    1.7.5                    py36_0    defaults
sphinxcontrib             1.0              py36hbbac3d2_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.2.8                    py36_0    defaults
sqlalchemy                1.2.8            py36hfa6e2cd_0    defaults
sqlite                    3.24.0               h7602738_0    defaults
statsmodels               0.9.0            py36h452e1ab_0    defaults
sympy                     1.1.1            py36h96708e0_0    defaults
tblib                     1.3.2            py36h30f5020_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h2698cfe_0    defaults
tk                        8.6.7                hcb92d03_3    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.0.2                    py36_0    defaults
traitlets                 4.3.2            py36h096827d_0    defaults
typing                    3.6.4                    py36_0    defaults
unicodecsv                0.14.1           py36h6450c06_0    defaults
urllib3                   1.23                     py36_0    defaults
vc                        14                   h0510ff6_3    defaults
vs2015_runtime            14.0.25123                    3    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.31.1                   py36_0    defaults
widgetsnbextension        3.2.1                    py36_0    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
win_unicode_console       0.5              py36hcdbd4b5_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py36he5f5981_0    defaults
xlrd                      1.1.0            py36h1cb58dc_1    defaults
xlsxwriter                1.0.5                    py36_0    defaults
xlwings                   0.11.8                   py36_0    defaults
xlwt                      1.3.0            py36h1a4751e_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.2.5                hc6251cf_0    defaults
zict                      0.1.3            py36h2d8e73e_0    defaults
zlib                      1.2.11               h8395fce_2    defaults

(base) C:\Users\jmatt>
```

**Comment by nehaljwani** [comment] 2018-07-15 14:30
@jeremymatt Did you ever open anaconda-navigator as an admin user?

**Comment by jeremymatt** [comment] 2018-07-16 03:37
Just did now on my personal machine (win 10), and the prompt did not come back - thanks for the suggestion.  Not really a solution for my work computer as I don't have admin rights, but at least we know why it wasn't remembering.

**Comment by laurenkj** [comment] 2019-04-23 17:16
I am also having this issue and it is now annoying because I use Anaconda a lot and every single time this prompt comes up.

**Comment by p-d-moore** [comment] 2019-07-07 22:22
> @solarjoe the issue is not that you need admin privileges to have this working. The issue is that if Navigator was opened at some point with admin rights, then the configuration might have been overridden and now admin privileges are going to be needed moving forward.

I am in the same situation as @solarjoe -> company pc without admin privileges.  Not having admin privileges and having installed Anaconda myself, it has never been opened with Admin privileges.  Nonetheless, ticking "Don't show again" doesn't make the welcome box disappear.

**Comment by QtRoS** [comment] 2019-10-29 06:12
Tired of this just like @laurenkj and @p-d-moore 
Please, do something. It is very annoying :\

**Comment by SonteruID** [comment] 2020-01-14 09:22
Same Issue with me and we are in 2020 now :-)

**Comment by forrestwaters** [comment] 2020-01-14 16:56
Please try the troubleshooting steps recommended here and let us know if this doesn't work for you: https://docs.anaconda.com/anaconda/navigator/troubleshooting/#navigator-ignores-the-ok-and-don-t-show-again-option-on-the-help-anaconda-improve-pop-up
`.anaconda/navigator/anaconda-navigator.ini` can be found in your users home directory.

**Comment by msarahan** [comment] 2020-01-14 17:31
As far as I can tell, any issues here originate because the `%USERPROFILE%\.anaconda\navigator\anaconda-navigator.ini` file can't be created or read.  That's a permissions problem on the user's side.  If anyone has evidence to the contrary, we'd like to see it, but in the meantime, we recommend making certain that Navigator can read and write to the `%USERPROFILE%\.anaconda\navigator folder.

**Comment by msarahan** [comment] 2020-01-14 17:38
On second thought, we are writing to the user's home folder, which makes sense on a local machine, but might not make sense for situations where a user's profile is remote.  We will investigate better places to put the configuration, but we'd still appreciate some more details on situations where the problem occurs.  How is your profile set up?

**Comment by solarjoe** [comment] 2020-01-15 13:14
Strange, I had this problem until yesterday. I did not know about the `anaconda-navigator.ini`. When I checked the setting this morning it already was `show_startup = False`. Now the pop-up is gone. Heisenberg-style. Looked - gone. No clue why.

I clicked "Upgrade now" earlier this morning, but I did not work due to missing administrative privileges (still 1.9.6). But could this be related?

**Comment by SonteruID** [comment] 2020-01-20 15:00
Mike,

I opened the Anaconda3 Navigator this time explicitly with Admin rights : it opened without showing the caption at all, which is good.

I reopened later the usual way without explicitly selecting the admin option, .. and it still did not show the window .. so seems to be ok now.

 

I have installed the program under Windows 10 straightforward, BUT I let it install the Anaconda3 folder on a separate drive i.e. not in the normal c-drive/program… folder. The user data are nevertheless saved under user\sonte …. on the main drive.

 

Thanks

Sonteru

 

Von: Mike Sarahan <notifications@github.com> 
Gesendet: Dienstag, 14. Januar 2020 18:38
An: ContinuumIO/anaconda-issues <anaconda-issues@noreply.github.com>
Cc: Sonteru <Sonteru@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [ContinuumIO/anaconda-issues] Anaconda navigator does not remember "yes, and don't ask me again" on the "help improve anaconda" popup window (#9761)

 

On second thought, we are writing to the user's home folder, which makes sense on a local machine, but might not make sense for situations where a user's profile is remote. We will investigate better places to put the configuration, but we'd still appreciate some more details on situations where the problem occurs. How is your profile set up?

**Comment by yorkad** [comment] 2020-03-10 16:50
I run navigator locally on a few Windows 10 x64 machines and always had this issue.

Today I upgraded navigator from 1.9.7 to 1.9.12 and the issue seems to be fixed on the first try.  Hope that helps.

**Comment by bkvaal** [comment] 2020-03-31 20:20
The popup froze on my screen, but after editing the ini file seems OK

**Comment by DoctorMG** [comment] 2020-05-05 10:10
I have it again. And again and again. 
(Windows 10 Prof., Anaconda 1.9.12)
I started this as admin. And it came back again. 
I edited this .rc-file. It was gone for a short while.
For some upgrade reason (updateing spyder IDE and some packages) I had to start Anaconda again as admin. I am not sure if this was exactly the point in time. But it seems it used that opportunity to change the .rc-entry or something else. 
At least it is back. :-((

Honestly: if this window worked well ("help improve ...") - I guess in terms with user experience - it should detect anyhow that the first slap in the face of the user is itself ignoring the user enty. At the moment just this helper is the reason why I write the first time here something at github. 
Who needs such a helper that creates it's own major problem? In my opinion it is a confession of a unsolved weakness everytime I see it (... every startup!). Reminds me on the old Clippy from Microsoft, that wanted to communicate smartness - but became the symbol for stupidity and mockery since it never worked smart and every user could see this every day.

Don't get me wrong: there is nothing against a crash/bug/user experience trouble etc. detection and the agreeement of the user to it. There is a fat PhD work with dozens of Usability Patterns/Anti Patterns I wrote as a researcher that can be applied for detecting and improving flaws and bottlenecks. ... I have to like it, if somebody want to apply this :-)

But as long as such a simple thing ('no means no!', just one boolean thing!) seems to be unmanageable this should be removed from a released version.

**Comment by jpmartineau** [comment] 2020-05-23 18:32
This is really annoying. If it can't be fixed, remove the window altogether. It doesn't reflect well on Anaconda as it's the first thing we see when we startup.

**Comment by SonteruID** [comment] 2020-05-23 21:29
Indeed, I have it too again. 

Actually, I take it as a training tool to improve my patience .. target is to feel no increase of adrenalin level when seeing it 😊

Good news .. I am close.

Regards

Sonteru.

 

Von: Jean-Pierre Martineau <notifications@github.com> 
Gesendet: Samstag, 23. Mai 2020 20:33
An: ContinuumIO/anaconda-issues <anaconda-issues@noreply.github.com>
Cc: Sonteru <Sonteru@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [ContinuumIO/anaconda-issues] Anaconda navigator does not remember "yes, and don't ask me again" on the "help improve anaconda" popup window (#9761)

 

This is really annoying. If it can't be fixed, remove the window altogether. It doesn't reflect well on Anaconda as it's the first thing we see when we startup.

**Comment by Eraseri** [comment] 2020-07-08 07:30
I have it too. Very annoying -.-   ...looking forward to solution.

**Comment by DoctorMG** [comment] 2020-07-09 08:35
Observations for improvement: as written above this box seems to comeback like a zombie although it was switched of on several ways (clicking, execute as admin, changing config files).

I didn't dig too deep, but what I found:
[Windows 10]
1. It seems to interact with the rights. Sometime starting as admin resolves it for a short while. I don't find a rule to tell - but after several times starting it as user it is back.
2. Maybe it deals with re-installation. Since some advice was to change some config file entry, I looked for such files. In my user file area I have one folder with the name .Anaconda. But below the subfolder Navigator I find the similar structure like .Anaconda and all the subfolders and files a second time. Now I am not sure if this is correct (belonging to some backup-to-defaults strategy) or result of some conflicting installations (... failure). At least it seemed like Anaconda switches between the two anaconda-navigator.ini files. As long as one of the files has a "True" as value for "show_startup = " it seems to take it. If this is the case some hint for removal of the wrong orphans would be helpful. 

I hope this can help with the analysis. I know that these "sometimes we have it" bugs are really inconvenient for programmers. Always you think you really have it, another one reports some exception where it greets again.

**Comment by Alexdamo** [comment] 2020-10-19 13:01
The following solution worked for me. Start the Navigator from the start menu "as administrator". When the request window pops up, check the box and press "Don't show again". Close the program, then start again as administrator. The pop-up window shouldn't appear. After that start the program as a normal user, it won't pop up any more.

**Comment by DoctorMG** [comment] 2020-10-20 08:04
Alexdamo, thanks for this proposal. As you can see on my post I tried this hack several times in the past, either ;-)
Unfortunately it comes back for any reason. I cannot recognize any logic with this behavior. It comes and goes - but mainly it is there after every daily boot. 
Since it seems to be that hard to tame I prefered to remove it.

**Comment by innocentius** [comment] 2020-11-15 09:53
This issue has been open for more than two years already. Anaconda developers, if you think this issue is unimportant, let me tell you that it is not. You have one of the most security & privacy-conscious userbase in the whole world, and this worsens your image quite a bit. At least try to fix it if you don't want to be recognized the same as some Chinese spamwares or those promotional emails.

**Comment by csoja** [comment] 2020-11-16 19:31
This should be fixed in Anaconda Navigator 1.10.0 that was recently released.  You'll need to update it on the command line - either in a terminal or from the Anaconda Prompt depending what platform you are running on.  Please upgrade and let us know if you are still seeing the issue.

**Comment by innocentius** [comment] 2020-11-17 02:35
Seems fixed after the update. Let's see if others still experience this bug.

**Comment by SonteruID** [comment] 2020-11-19 10:41
For me : I could not update to 1.10.0 despite I was offered to update and I clicked YES … several trials. I also tried on the prompt, but was unsure what is right syntax : e.g. conda install anaconda=1.10.0 did not work, as well as same with … navigator .. .

> But good news:  the  "yes, and don't ask me again" window does not pop up any more 😊

Regards

Sonteru

 

Von: csoja <notifications@github.com> 
Gesendet: Montag, 16. November 2020 20:32
An: ContinuumIO/anaconda-issues <anaconda-issues@noreply.github.com>
Cc: Sonteru <Sonteru@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [ContinuumIO/anaconda-issues] Anaconda navigator does not remember "yes, and don't ask me again" on the "help improve anaconda" popup window (#9761)

 

This should be fixed in Anaconda Navigator 1.10.0 that was recently released. You'll need to update it on the command line - either in a terminal or from the Anaconda Prompt depending what platform you are running on. Please upgrade and let us know if you are still seeing the issue.

**Comment by csoja** [comment] 2020-11-19 15:24
the correct syntax is _conda update anaconda-navigator_

**Comment by SonteruID** [comment] 2020-11-20 10:15
Indeed, 

 

.. the hyphen proved to be hyper relevant 😊.

 

Now I have updated successfully the navigator and I am getting NO reminder window.

 

Thanks

Sonteru

 

Von: csoja <notifications@github.com> 
Gesendet: Donnerstag, 19. November 2020 16:25
An: ContinuumIO/anaconda-issues <anaconda-issues@noreply.github.com>
Cc: Sonteru <Sonteru@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [ContinuumIO/anaconda-issues] Anaconda navigator does not remember "yes, and don't ask me again" on the "help improve anaconda" popup window (#9761)

 

the correct syntax is conda update anaconda-navigator

**Comment by csoja** [comment] 2020-11-20 16:31
Closing this issue as two users have confirmed they no longer are seeing the popup window with version 1.10.0 of Navigator.

**Closed by csoja** 2020-11-20 16:31 UTC
Labels: pkg-navigator, type-bug
