### ISSUE TITLE
Navigator fails - first try

### ISSUE THREAD

**Issue by justauserofpython** [ContinuumIO/anaconda-issues#2212] opened 2017-06-12 19:59 UTC
I wanted to try out navigator but it failed. 
I just removed my old anaconda since I updated to macos 10.12.5 and reinstalled anaconda3 (python v 3.6.1).

$alias navigator='/Users/jimj/anaconda3/bin/anaconda-navigator'
~ 2879 $navigator
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Users/jimj/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

0:86: execution error: "file:/var/folders/d_/ls51m_5w8xn1jw00r6bly4280000gq/T/tmpumtpu73b.html" doesn’t understand the “open location” message. (-1708)
69:77: execution error: Can’t get application "chrome". (-1728)
~ 2879 $

**Comment by goanpeca** [comment] 2017-06-12 20:01
Closing as duplicate of #1837

**Closed by goanpeca** 2017-06-12 20:01 UTC
