### ISSUE TITLE
Can't launch Anaconda navigator

### ISSUE THREAD

**Issue by patex1987** [ContinuumIO/anaconda-issues#7192] opened 2017-11-08 12:54 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=2936)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\gpatassy\AppData\Local\Continuum\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\gpatassy\AppData\Local\Continuum\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Prístup je odmietnutý

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gpatassy\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\gpatassy\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\gpatassy\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\gpatassy\AppData\Local\Continuum\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\gpatassy\AppData\Local\Continuum\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2936)

```
## System information

platform : win-64
conda version : 4.3.25
conda-env version : 4.3.25
python version : 3.6.1.final.0
requests version : 2.14.2
user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.1 Windows/7 Windows/6.1.7601

**Comment by goanpeca** [comment] 2017-11-08 13:40
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-08 13:40 UTC

**Comment by nguyentuanancdt** [comment] 2018-09-14 05:37
I updated anaconda navigator but I can't launch anaconda navigator now.Pls help me

**Comment by patex1987** [comment] 2018-09-14 05:57
Have you tried `$ anaconda-navigator --reset` from ticket #1984
