### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by abhijitdey** [ContinuumIO/anaconda-issues#7336] opened 2017-11-15 19:31 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <http://hltv1003.hydc.sbc.com:8080/conda/anaconda/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPConnectionPool(host='hltv1003.hydc.sbc.com', port=8080): Max retries exceeded with url: /conda/anaconda/win-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000400DDD8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))",),)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-11-15 19:35
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-15 19:35 UTC
Labels: pkg:navigator, reso:duplicate
