### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by 1357997531** [ContinuumIO/anaconda-issues#10934] opened 2019-05-21 07:59 UTC
### Actual Behavior

cannot open but pop out one window and ask me put a comment here.

### Expected Behavior

the anaconda founten 

### Steps to Reproduce

when i want to open the porgram 

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:
Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "**", line 150, in start_app
    window = run_app(splash)
  File "**", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "**", line 168, in __init__
    self.api = AnacondaAPI()
  *  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

</details>

**Comment by csoja** [comment] 2019-06-07 20:16
Thank you for submitting an error report, but there isn't enough information here to determine the cause of your problem.  You need to include not just the error, but the versions of the software installed, what OS, etc.  You will need to run the conda commands in the Anaconda Prompt.  I will close this for now - but can reopen if sufficient information is provided.

**Closed by csoja** 2019-06-07 20:16 UTC
