### ISSUE TITLE
Cannot Install/neither update

### ISSUE THREAD

**Issue by jrobertofg** [ContinuumIO/anaconda-issues#3393] opened 2017-07-20 21:31 UTC
This was the first error->

CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2><br>Elapsed: None<br><br>An HTTP error occurred when trying to retrieve this URL.<br>HTTP errors are often intermittent, and a simple retry will get you on your way.<br>SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)<br>

++++++++
This was the first error->The solution that someon gave to me was update by getting into the Anaconda Prompt and write "conda update anaconda-navigator" when I do that i obtain the following:
++++++

(............>conda update anaconda-navigator
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

(...................>conda update anaconda-navigator
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

**Comment by goanpeca** [comment] 2017-07-20 21:32
Closing as duplicate of #1932

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-20 21:32 UTC
Labels: pkg:navigator, reso:duplicate
