### ISSUE TITLE
sqlite not compiled with load extension capability

### ISSUE THREAD

**Issue by jonwoodring** [ContinuumIO/anaconda-issues#1287] opened 2016-12-08 20:13 UTC
This was done with Anaconda Python 3.5, sqlite 3.13.0, tested on an Arch Linux via miniconda.

The connection object should have `enable_load_extension(enabled)` and `load_extension(path)` if it allows extension loading.

According to https://docs.python.org/3/library/sqlite3.html#f1 
> [1]	(1, 2) The sqlite3 module is not built with loadable extension support by default, because some platforms (notably Mac OS X) have SQLite libraries which are compiled without this feature. To get loadable extension support, you must pass –enable-loadable-sqlite-extensions to configure.

It seems that the conda version was not turned on either.

```python
import sqlite3
conn = sqlite3.Connection(':memory:')
cursor = conn.cursor()
cursor.execute("select load_extension('/home/woodring/gio/genericio/frontend/GenericIOSQLite.so')")
```

```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-23-d608204c129b> in <module>()
      2 conn = sqlite3.Connection(':memory:')
      3 cursor = conn.cursor()
----> 4 cursor.execute("select load_extension('/home/woodring/gio/genericio/frontend/GenericIOSQLite.so')")

OperationalError: not authorized
```

```python
dir(conn)
```

```
['DataError',
 'DatabaseError',
 'Error',
 'IntegrityError',
 'InterfaceError',
 'InternalError',
 'NotSupportedError',
 'OperationalError',
 'ProgrammingError',
 'Warning',
 '__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'close',
 'commit',
 'create_aggregate',
 'create_collation',
 'create_function',
 'cursor',
 'execute',
 'executemany',
 'executescript',
 'in_transaction',
 'interrupt',
 'isolation_level',
 'iterdump',
 'rollback',
 'row_factory',
 'set_authorizer',
 'set_progress_handler',
 'set_trace_callback',
 'text_factory',
 'total_changes']
```

**Comment by timothyrenner** [comment] 2017-02-02 00:11
Seeing the same issue on macOS with standard Anaconda distribution.

**Comment by clayadavis** [comment] 2017-04-29 17:00
I can confirm

- this issue exists with Anaconda's Python 3.6
- this issue does not exist with the Python3 shipped in Ubuntu 16.10.

**Comment by jpeacock29** [comment] 2017-12-15 17:59
This issue persists with OSX 10.10.5, Sqlite3 2.6.0 and Sqlite 3.13.0. It has been fixed (at least for the given configuration) in the [conda-forge Python feedstock](https://github.com/conda-forge/python-feedstock) in [PR 107](https://github.com/conda-forge/python-feedstock/pull/107).

For users encountering issue, you can install the conda-forge Python build in a new environment by first configuring conda-forge (this should work with anaconda as well, but untested):

     conda config --add channels conda-forge 

Now install python

    conda install python

Lastly, remove the conda-forge configuration:

    conda config --remove channels conda-forge

**Comment by mingwandroid** [comment] 2017-12-15 18:15
@jpeacock29, this is fixed in the official `Anaconda Distribution` and has been since the release of 5.0.0 at the end of September: https://github.com/AnacondaRecipes/python-feedstock/blob/master/recipe/build.sh#L166

All of our packages are now built from forks of `conda-forge` now so generally speaking we have reasonable feature parity.

FWIW our Python is a lot faster and more secure than `conda-forge`'s. I'm hoping to make PRs when they adopt `conda-build 3` and our new compilers but that's not happened yet.

**Closed** 2017-12-15 18:17 UTC
Labels: os:linux, tag:package-request

**Comment by jpeacock29** [comment] 2017-12-15 18:31
Thanks, @mingwandroid, didn't realize this had been fixed there! Upgraded and works now.
