### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#1038] opened 2016-09-05 13:24 UTC
Anaconda Navigator Update error:

Extra data: line 2 column 1 (char 82)

{'version': '1.2.2', 'language': 'en_GB', 'conda': '4.1.11', 'qt': '4.8.7', 'python': '3.5.2', 'platform': 'win-64', 'pyqt': '4.11.4', 'os': 'Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel'}

**Comment by goanpeca** [comment] 2016-09-05 15:20
Hi @joesoap99 thabnks for reporting, this has been fixed in the new version of navigator comming soon.

Closing as it is a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/969

**Closed by goanpeca** 2016-09-05 15:20 UTC
