### ISSUE TITLE
Error after conda install scikit-learn

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1645] opened 2017-04-27 23:21 UTC
_From @GeoffNN on April 27, 2017 0:29_

After creating a new conda environment, with `conda create -n name python=3.5`, doing `conda install scikit-learn` and then importing sklearn results in the following error:
`"ImportError: libopenblasp-r0-39a31c03.2.18.so: cannot open shared object file: No such file or directory"`

_Copied from original issue: conda/conda#5156_

**Comment by kalefranz** [comment] 2017-04-27 23:21
Can you please provide `conda info` and `conda list --show-channel-urls`?  Also, did you remember to `source activate name` after your `conda create`?

**Comment by kalefranz** [comment] 2017-04-27 23:21
_From @GeoffNN on April 27, 2017 20:37_

I did `source activate name`. The installation worked with `pip` but not with `conda`. Here are the outputs you asked for (after the installation with pip on the env).

Here's the output of `conda info`: 
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : /home/geoff/anaconda3  (writable)
    default environment : /home/geoff/anaconda3/envs/umkl
       envs directories : /home/geoff/anaconda3/envs
                          /home/geoff/.conda/envs
          package cache : /home/geoff/anaconda3/pkgs
                          /home/geoff/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.2 Linux/4.4.0-75-generic debian/jessie/sid glibc/2.19
                UID:GID : 1000:1000

And of `conda list --show-channel-urls`:
```
# packages in environment at /home/geoff/anaconda3/envs/umkl:
#
bleach                    2.0.0                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.0.11                    <pip>
entrypoints               0.2.2                     <pip>
html5lib                  0.999999999               <pip>
ipykernel                 4.6.1                     <pip>
ipython                   6.0.0                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                6.0.0                     <pip>
jedi                      0.10.2                    <pip>
Jinja2                    2.9.6                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.0.1                     <pip>
jupyter-console           5.1.0                     <pip>
jupyter-core              4.3.0                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.0.0                     <pip>
mistune                   0.7.4                     <pip>
nbconvert                 5.1.1                     <pip>
nbformat                  4.3.0                     <pip>
notebook                  5.0.0                     <pip>
numpy                     1.12.1                    <pip>
openssl                   1.0.2k                        1    defaults
pandas                    0.19.2                    <pip>
pandocfilters             1.4.1                     <pip>
pexpect                   4.2.1                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py35_1    defaults
prompt-toolkit            1.0.14                    <pip>
ptyprocess                0.5.1                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    3.5.3                         1    defaults
python-dateutil           2.6.0                     <pip>
pytz                      2017.2                    <pip>
pyzmq                     16.0.2                    <pip>
qtconsole                 4.3.0                     <pip>
readline                  6.2                           2    defaults
scikit-learn              0.18.1                    <pip>
scipy                     0.19.0                    <pip>
seaborn                   0.7.1                     <pip>
setuptools                27.2.0                   py35_0    defaults
simplegeneric             0.8.1                     <pip>
six                       1.10.0                    <pip>
sklearn                   0.0                       <pip>
sqlite                    3.13.0                        0    defaults
terminado                 0.6                       <pip>
testpath                  0.3                       <pip>
tk                        8.5.18                        0    defaults
tornado                   4.5.1                     <pip>
traitlets                 4.3.2                     <pip>
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        2.0.0                     <pip>
xz                        5.2.2                         1    defaults
zlib                      1.2.8                         3    defaults
```

**Comment by JoshuaC3** [comment] 2017-11-21 23:06
It seems this is happening to me for a lot of packages that I can installing with the miniconda dist `conda install package_x`. When I try to import the model it fails. When I install it with `pip install package_x` it installs and then is importable.

What might be going on here?

**Comment by msarahan** [comment] 2017-11-21 23:59
You have a ton of packages installed with pip.  Wheels bundle their own dependencies, and these dependencies are often incompatible with conda equivalents.  For example, Anaconda packages use MKL rather than openblas.  That may be part of the cause here.  For @GeoffNN, it seems like a mix of conda-forge and defaults packages that may be at fault, rather than @JoshuaC3's issue with pip.  There have been widespread reports of this sort, but we haven't seen a good reproducible test case yet.  We will fix it when we can identify the root cause.

At this point, you're better off creating a new installation or new env and installing the libraries you want using conda, NOT pip.  It is always best to try installing with conda first, and only fall back to pip as a last resort.  Note that many packages not yet available on the default channel are available from conda-forge:

``conda search -c conda-forge (package you want)``
``conda install -c conda-forge (package you want)``

**Comment by JoshuaC3** [comment] 2017-11-22 07:12
Thanks for the info. I have now removed miniconda and installed Anaconda. `conda install` now seems to be working, or at least the packages that weren't working with conda have been installed with the anaconda distribution; sklearn, scipy.

One issue that has still remained is some of the kernel paths for the Jupyter Notebook have been looking in the old miniconda path. This was eventually fixed with a kernel reinstall. I will link when back on my computer.

**Comment by msarahan** [comment] 2017-11-22 16:23
Great, thanks for that link.  That was an issue I've seen elsewhere but didn't know how to address.

Anaconda is miniconda, plus a bunch of packages on top that have been tested to work together.  You'd be fine starting with miniconda and using ``conda install`` too.  Mostly the people who really like Anaconda are the ones who don't have reliable internet connections, or the people who prefer to think of it as a big monolithic bunch of software (like Matlab).  The latter isn't an accurate concept, but it's OK.

Long-term, I would strongly advise you to prefer miniconda, and create environments for your projects, each with only the few necessary dependencies you need.  Using environments is much cleaner than installing everything into the root environment.  Anaconda sort of promotes the mindset using the root env for everything, since it's all already there.

**Closed** 2017-11-22 16:23 UTC
Labels: source:community, type:question

**Comment by JoshuaC3** [comment] 2017-11-22 16:49
Yes, what you say makes sense and in fact this is exactly why I tried to use miniconda. For some reason the Anaconda out-of-the-box installs worked (i.e. imported nicely) but my miniconda `conda install` didn't. Hence my roll. Of course this could be user error but I do not see where I could have gone wrong with this. Thanks for your help!
