### ISSUE TITLE
Navigator Error launching Spyder

### ISSUE THREAD

**Issue by sformanjawbone** [ContinuumIO/anaconda-issues#3637] opened 2017-07-27 21:44 UTC
I launched Spyder from the Anaconda Navigator and this error came up in a dialog.  The Spyder application started and seems to be running fine.  I'm reporting it in case it is useful, and because you made it easy to do so from the dialog (nice touch!)

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.22
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-07-27 21:45
**See Issue #1778 for more information on how to fix this.**

---

Closing as duplicate of #1778


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-27 21:45 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by sformanjawbone** [comment] 2017-07-27 21:55
That  fixed it.  Thank you.  Apologies for the noise. :-)
