### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hitiler** [ContinuumIO/anaconda-issues#10740] opened 2019-03-17 03:03 UTC
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\jupyterlab_server\server.py", line 14, in <module>
    from notebook.base.handlers import (
  File "D:\Anaconda\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "D:\Anaconda\lib\site-packages\notebook\nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\Scripts\jupyter-lab-script.py", line 6, in <module>
    from jupyterlab.labapp import main
  File "D:\Anaconda\lib\site-packages\jupyterlab\labapp.py", line 12, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "D:\Anaconda\lib\site-packages\jupyterlab_server\__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "D:\Anaconda\lib\site-packages\jupyterlab_server\app.py", line 9, in <module>
    from .server import ServerApp
  File "D:\Anaconda\lib\site-packages\jupyterlab_server\server.py", line 26, in <module>
    from jupyter_server.base.handlers import (                          # noqa
ModuleNotFoundError: No module named 'jupyter_server'

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.6.8
```

**Comment by goanpeca** [comment] 2019-03-17 23:42
Closing as duplicate of #8216

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8216 for more information on how to fix this issue.**

Or try running

```
conda upgrade jupyter_core
```

**Closed by goanpeca** 2019-03-17 23:42 UTC
Labels: pkg-navigator, reso-duplicate
