### ISSUE TITLE
anaconda navigator issue

### ISSUE THREAD

**Issue by MuhammadAhmad-BlockchainDeveloper** [ContinuumIO/anaconda-issues#12943] opened 2022-05-25 10:32 UTC
when i click on "Anaconda Navigator Issue" to run it, then i am getting following error in browser
Main Error
('Forbidden: Request forbidden -- authorization will not help ([GET] https://192.168.99.254:8090/ips/block/webcat?cat=49&pl=0&url=aHR0cHM6Ly9hcGkuYW5hY29uZGEub3Jn -> 403)', 403)
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1116, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 645, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 100, in __init__
    self.reload_client()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 314, in reload_client
    client.user()
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Forbidden: Request forbidden -- authorization will not help ([GET] https://192.168.99.254:8090/ips/block/webcat?cat=49&pl=0&url=aHR0cHM6Ly9hcGkuYW5hY29uZGEub3Jn -> 403)', 403)

Please respond on this

**Comment by tarikasd** [comment] 2022-08-01 08:40
Hello, I have the same problem. Did you find a solution?

**Comment by vshevchenko-anaconda** [comment] 2022-09-09 12:03
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/12415

**Closed** 2022-09-09 12:05 UTC
Labels: type-bug, reso-duplicate, pkg-navigator
