### ISSUE TITLE
Navigator Error: what is this? How do I fix it?

### ISSUE THREAD

**Issue by diegocaseonit** [ContinuumIO/anaconda-issues#2675] opened 2017-06-28 09:03 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
python: 3.5.2
language: en
platform: osx-64
version: 1.6.2
conda: 4.3.21
pyqt: 5.6.0
qt: 5.6.2
os: Darwin;16.1.0;Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64;x86_64;i386
```

**Comment by goanpeca** [comment] 2017-06-28 13:37
Closing as duplicate of #1778

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-28 13:37 UTC
Labels: pkg:navigator, reso:duplicate
