### ISSUE TITLE
2016 era numpy and scipy no longer installable together

### ISSUE THREAD

**Issue by richafrank** [ContinuumIO/anaconda-issues#10378] opened 2018-11-29 16:39 UTC
numpy 1.11.3 can no longer be installed with other packages from that era (e.g. scipy 0.17.1) because a new package of numpy 1.11.3 was [uploaded `Wed Nov 21 08:54:36 2018`](https://anaconda.org/anaconda/numpy/files/modal/info/5bf51d4c7557f4134a1fad77) depending on `mkl >=2018`, but scipy 0.17.1 still depends on [`mkl 11.3.3`](https://anaconda.org/anaconda/scipy/files/modal/info/5bb33a9ec5eaa87780873658).

Our builds that pin all these older 2016 dependencies fail now. Is there a recommended way to pin to a specific numpy package version that isn't being re-released?

### Actual Behavior

```cmd
>conda create -n testenv python=2.7 numpy=1.11.3 scipy=0.17.1
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.11.3*
  - scipy 0.17.1* -> mkl 11.3.3
  - scipy 0.17.1* -> numpy 1.10*
Use "conda info <package>" to see the dependencies for each package.
```

```cmd
>conda info numpy=1.11.3

numpy 1.11.3 py27hfef472a_4
---------------------------
file name   : numpy-1.11.3-py27hfef472a_4.tar.bz2
name        : numpy
version     : 1.11.3
build string: py27hfef472a_4
build number: 4
channel     : defaults
size        : 3.2 MB
arch        : None
license     : BSD 3-Clause
md5         : dd6295aa527cea56ba55b6c42f0f1fcb
noarch      : None
platform    : None
subdir      : win-64
timestamp   : 1519835534310
url         : https://repo.continuum.io/pkgs/main/win-64/numpy-1.11.3-py27hfef472a_4.tar.bz2
dependencies:
    icc_rt >=13.1.6
    python >=2.7,<2.8.0a0
    vc 9.*
    mkl >=2018,<2019.0a0
    blas * mkl
```

```cmd

scipy 0.17.1 np111py27_1
------------------------
file name   : scipy-0.17.1-np111py27_1.tar.bz2
name        : scipy
version     : 0.17.1
build string: np111py27_1
build number: 1
channel     : defaults
size        : 11.5 MB
arch        : x86_64
date        : 2016-06-13
license     : BSD
md5         : 1dfd0991a113a4c9578d5b830aa3230d
noarch      : None
platform    : win32
url         : https://repo.continuum.io/pkgs/free/win-64/scipy-0.17.1-np111py27_1.tar.bz2
dependencies:
    blas * mkl
    mkl 11.3.3
    numpy 1.11*
    python 2.7*
    vs2008_runtime
```

### Expected Behavior
This successful example is from a [Nov 8, 2018 build](https://ci.appveyor.com/project/quantopian/zipline/branch/master/job/u7iyauk4rlxsy7g8?fullLog=true), which isn't a minimal example, but illustrates that this combination of libs used to work:

env vars:
```
    PYTHON_ARCH: "64"
    PANDAS_VERSION: "0.18.1"
    NUMPY_VERSION: "1.11.3"
    SCIPY_VERSION: "0.17.1"
```

```cmd
ECHO %PYTHON_VERSION% %PYTHON_ARCH% %PYTHON%
2.7 64 
ECHO %NUMPY_VERSION%
1.11.3

conda create -n testenv --yes -q --use-local pip python=%PYTHON_VERSION% numpy=%NUMPY_VERSION% pandas=%PANDAS_VERSION% scipy=%SCIPY_VERSION% ta-lib=%TALIB_VERSION% bcolz=%BCOLZ_VERSION% numexpr=%NUMEXPR_VERSION% pytables=%PYTABLES_VERSION% h5py=%H5PY_VERSION% -c quantopian -c https://conda.anaconda.org/quantopian/label/ci

Package plan for installation in environment C:\Python27_64\envs\testenv:
The following NEW packages will be INSTALLED:
    bcolz:           0.12.1-np111py27_0      quantopian
    blas:            1.0-mkl                           
    blosc:           1.14.4-h95ae18b_0                 
    bzip2:           1.0.6-h0c8e037_5                  
    certifi:         2018.10.15-py27_0                 
    h5py:            2.7.1-py27h5f1a774_2              
    hdf5:            1.10.2-h530792d_2                 
    icc_rt:          2017.0.4-h97af966_0               
    lzo:             2.10-h0bb7fe3_2                   
    mkl:             11.3.3-1                          
    numexpr:         2.6.1-np111py27_1                 
    numpy:           1.11.3-py27hfef472a_4             
    pandas:          0.18.1-np111py27_0                
    pip:             18.1-py27_0                       
    pytables:        3.4.3-py27hdd5b532_1              
    python:          2.7.15-h2880e7c_3                 
    python-dateutil: 2.7.5-py27_0                      
    pytz:            2018.7-py27_0                     
    scipy:           0.17.1-np111py27_1                
    setuptools:      40.5.0-py27_0                     
    six:             1.11.0-py27_1                     
    snappy:          1.1.7-he46498f_3                  
    ta-lib:          0.4.9-np111py27_0       quantopian
    vc:              9-h7299396_1                      
    vs2008_runtime:  9.00.30729.1-hfaea7d5_1           
    wheel:           0.32.2-py27_0                     
    wincertstore:    0.2-py27hf04cefb_0                
    zlib:            1.2.11-hbc2faf4_2       
```

Note that this includes
```
    mkl:             11.3.3-1                  
    numpy:           1.11.3-py27hfef472a_4
    python:          2.7.15-h2880e7c_3       
    scipy:           0.17.1-np111py27_1
```           

### Steps to Reproduce

```
conda create -n testenv python=2.7 numpy=1.11.3 scipy=0.17.1
```

##### `conda info`
```
Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\Administrator\Miniconda3  (writable)
    default environment : C:\Users\Administrator\Miniconda3\envs\testenv
       envs directories : C:\Users\Administrator\Miniconda3\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : C:\Users\Administrator\Miniconda3\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.14393
          administrator : True
```

##### `conda list --show-channel-urls`
```
# packages in environment at C:\Users\Administrator\Miniconda3:
#
asn1crypto                0.22.0           py36h8e79faa_1    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
cachecontrol              0.12.3           py36hfe50d7b_0    defaults
certifi                   2017.7.27.1      py36h043bc9e_0    defaults
cffi                      1.10.0           py36hae3d1b5_1    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
colorama                  0.3.9            py36h029ae33_0    defaults
conda                     4.3.27           py36hcbae3bd_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
cryptography              2.0.3            py36h123decb_1    defaults
distlib                   0.2.5            py36h51371be_0    defaults
html5lib                  0.999999999      py36ha09b1f3_0    defaults
idna                      2.6              py36h148d497_1    defaults
lockfile                  0.12.2           py36h0468280_0    defaults
menuinst                  1.4.10           py36h42196fb_0    defaults
msgpack-python            0.4.8            py36h58b1e9d_0    defaults
openssl                   1.0.2l           vc14hcac20b0_2  [vc14]  defaults
packaging                 16.8             py36ha0986f6_1    defaults
pip                       9.0.1            py36hadba87b_3    defaults
progress                  1.3              py36hbeca8d3_0    defaults
pycosat                   0.6.2            py36hf17546d_1    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pyopenssl                 17.2.0           py36h15ca2fc_0    defaults
pyparsing                 2.2.0            py36h785a196_1    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
python                    3.6.3                h9e2ca53_1    defaults
pywin32                   221              py36h9c10281_0    defaults
requests                  2.18.4           py36h4371aae_1    defaults
ruamel_yaml               0.11.14          py36h9b16331_2    defaults
setuptools                36.5.0           py36h65f9e6e_0    defaults
six                       1.10.0           py36h2c0fdd8_1    defaults
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h2379b0c_2    defaults
vs2015_runtime            14.0.25123           hd4c4e62_1    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
wheel                     0.29.0           py36h6ce6cde_1    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
yaml                      0.1.7            vc14hb31d195_1  [vc14]  defaults

```

**Comment by soapy1** [comment] 2018-11-30 16:43
@richafrank this should be resolved now! Going to close this out but  please reopen if the problem is not fixed for you

**Closed by soapy1** 2018-11-30 16:43 UTC

**Comment by soapy1** [comment] 2018-11-30 17:35
Heya @richafrank, we haven't been re-releasing old numpy packages, this was a result of a hotfix that was applied. You can checkout out the repo here if you are interested in what happens with that https://github.com/AnacondaRecipes/repodata-hotfixes. The MKL hotfixing that was affecting this happens around here: https://github.com/AnacondaRecipes/repodata-hotfixes/blob/master/main.py#L305

**Comment by richafrank** [comment] 2018-12-03 21:38
Interesting - thanks @soapy1 ! Glad to know about this hotfixing going on.
