### ISSUE TITLE
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

### ISSUE THREAD

**Issue by Arnav382** [ContinuumIO/anaconda-issues#12973] opened 2022-06-21 06:45 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

### Conda info

```shell
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)
```

### Conda config

```shell
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)
```

**Comment by mjoyce88** [comment] 2022-06-21 06:56
also have same issue Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)
Traceback
Traceback (most recent call last):
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1116, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 645, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 100, in __init__
    self.reload_client()
  File "C:\Users\andy3\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 314, in reload_client
    client.user()
  File "C:\Users\andy3\anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\Users\andy3\anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Comment by Poulami2515** [comment] 2022-06-21 06:58
Same issue :

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)
Traceback
Traceback (most recent call last):
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client.user()
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\Users\POULAMI PAUL\anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Comment by henriquez07** [comment] 2022-06-21 06:59
Same issue here

Main Error
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Comment by zabdellaoui** [comment] 2022-06-21 06:59
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)
Traceback
Traceback (most recent call last):
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\Users\zakaa\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client.user()
  File "C:\Users\zakaa\anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\Users\zakaa\anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Comment by thimomulder** [comment] 2022-06-21 07:00
Same issue here:

**Navigator Error**
An unexpected error occurred on Navigator start-up

**Report**
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

**Main Error**
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Traceback**
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1168, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 683, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 145, in __init__
    self.reload_client()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 360, in reload_client
    client.user()
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Comment by rezkiaa** [comment] 2022-06-21 07:00
Same issue here, how to solve the problem? 

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)
Traceback
Traceback (most recent call last):
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 94, in __init__
    self.reload_client()
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 325, in reload_client
    client.user()
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/binstar_client/__init__.py", line 242, in user
    self._check_response(res)
  File "/home/eg10/anaconda3/lib/python3.9/site-packages/binstar_client/__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Comment by natha7** [comment] 2022-06-21 07:03
Same problem here.


Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

Traceback
Traceback (most recent call last):
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 228, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1116, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 645, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 100, in __init__
    self.reload_client()
  File "C:\Users\Conda\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 314, in reload_client
    client.user()
  File "C:\Users\Conda\anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\Users\Conda\anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Comment by Domlin123** [comment] 2022-06-21 07:05
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)
Traceback
Traceback (most recent call last):
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\Users\yinxi\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client.user()
  File "C:\Users\yinxi\anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\Users\yinxi\anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal Server Error: Server got itself in trouble ([GET] https://api.anaconda.org/user -> 500)', 500)

**Comment by thimomulder** [comment] 2022-06-21 08:29
I solved the issue, I checked in the program and features section of the control panel for the Anaconda install. I uninstalled every version of it and reinstalled Conda. This worked for me.

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 09:26
This issue was caused by an incident on anaconda.org side. The navigator team has planned stability improvements to prevent such issues. For now, I'm closing this ticket. Thank you all for commenting. Feel free to open another issue in case of any problems.

**Closed by vshevchenko-anaconda** 2023-07-07 09:26 UTC
Labels: type-bug, pkg-navigator, anaconda-sync
