### ISSUE TITLE
Anaconda Python 3.8.3 in Mac running multiprocessing code 5 times

### ISSUE THREAD

**Issue by magusverma** [ContinuumIO/anaconda-issues#12085] opened 2020-10-10 10:49 UTC
I was trying to parallelise a code. But it was running slow. On a very basic analysis using following code I found that for some reason with my anaconda python installation the file is loaded 5 times.

```
import time
from multiprocessing import Pool, freeze_support

def dummy():
  time.sleep(1)

print("in test_outside")

if __name__ == '__main__':
    freeze_support()
    start = time.time()
    for parallel_request_count in [1]:
        pool = Pool()
        r = [pool.apply_async(dummy, []) for i in range(parallel_request_count)] 
        answers = [x.get(timeout=10) for x in r]
        print("Total Time taken to process %d request in Parallel:" % parallel_request_count,time.time()-start)

```

### Running with anaconda 3.8.3
```
(base) 38f9d3654b47:vcost vermagus$ python --version
Python 3.8.3
(base) 38f9d3654b47:vcost vermagus$ python test_outside.py 
in test_outside
in test_outside
in test_outside
in test_outside
in test_outside
Total Time taken to process 1 request in Parallel: 1.297395944595337
(base) 38f9d3654b47:vcost vermagus$ which python
/Users/vermagus/opt/anaconda3/bin/python
```

### Running with default python 2.7 in mac
```
(base) 38f9d3654b47:vcost vermagus$ /usr/bin/python test_outside.py 
in test_outside
('Total Time taken to process 1 request in Parallel:', 1.3117179870605469)
```

**Comment by mingwandroid** [comment] 2020-10-10 12:01
Please fill in the information asked for in the issue template.

Please show the output from just running `python` on its own.

I cannot reproduce this. In my output I see:

```
1
Total Time taken to process 1 request in Parallel: 1.1670572757720947
```

Closing until the needed info is provided.

**Closed by mingwandroid** 2020-10-10 12:01 UTC

**Comment by mingwandroid** [comment] 2020-10-10 12:03
Ah oops I left a line out.

You need to use Pool(processes=1). Please read the python documentation: https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.pool

That python 2.7 on your macOS system does this differently is not surprising.
