### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by SiddharthDas123** [ContinuumIO/anaconda-issues#7818] opened 2017-12-17 19:17 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Traceback (most recent call last):
  File "/Users/sid/Desktop/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3099, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/sid/Desktop/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3011, in run_spyder
    main.post_visible_setup()
  File "/Users/sid/Desktop/anaconda/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1269, in post_visible_setup
    self.historylog.add_history(get_conf_path('history.py'))
  File "/Users/sid/Desktop/anaconda/lib/python3.6/site-packages/spyder/plugins/history.py", line 232, in add_history
    text, _ = encoding.read(filename)
  File "/Users/sid/Desktop/anaconda/lib/python3.6/site-packages/spyder/utils/encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sid/.spyder-py3/history.py'

```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.2.0;Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment] 2017-12-17 19:19
**See Issue #1778 for more information on how to fix this.**

---

Closing as duplicate of #1778


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-12-17 19:19 UTC
Labels: pkg:navigator, reso:duplicate
