### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by manoharlax** [ContinuumIO/anaconda-issues#3543] opened 2017-07-25 10:22 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=8520)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Manu\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Manu\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Manu\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Manu\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Manu\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=8520)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_IN
python: 2.7.13
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-07-25 10:22
**See Issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-25 10:22 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by manoharlax** [comment] 2017-07-25 10:39
Hey I just did it but its showing the same error again

**Comment by manoharlax** [comment] 2017-07-25 10:40
You want me to post the error again ?

**Comment by manoharlax** [comment] 2017-07-25 10:43
Traceback (most recent call last):
File "c:\Users\Manu\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "c:\Users\Manu\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "c:\Users\Manu\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "c:\Users\Manu\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "c:\Users\Manu\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=8520)

**Comment by manoharlax** [comment] 2017-07-25 10:48
Ok I did it but I had to rest the anaconda navigator 
by this command:  anaconda-navigator --reset
Then it worked! Thank You!
