### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by canthonyscott** [ContinuumIO/anaconda-issues#7294] opened 2017-11-13 19:29 UTC
I seem to be unable to install R-studio through anaconda. I have successfully done this before. This occurs when clicking Install under R-studio in the Home tab of Anaconda Navigator.

## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Dependencies missing in current win-64 channels: 
  - rstudio ==1.1.383 -> fonts-anaconda
  - rstudio ==1.1.383 -> icu >=58.2,<59.0a0

Close matches found; did you mean one of these?

    fonts-anaconda: anaconda

(and similarly for the other packages)
```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-11-13 19:30
**See Issue #6970 for more information on how to fix this.**

---

Closing as duplicate of #6970


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-13 19:30 UTC
Labels: pkg:navigator, reso:duplicate
