### ISSUE TITLE
Failed to create ( add )  Anaconda menus (to the system PATH)

### ISSUE THREAD

**Issue by IkiAlex** [ContinuumIO/anaconda-issues#732] opened 2016-04-01 12:15 UTC
Hey there! 
If somebody can help me i'd be very thankful, cause i cant solve this by myself. As i see there is pretty odd issue, and i cant find a solution cause nothing works for me. 
I have very new virtual pc ( win xp 64 ) and i'm trying to install anaconda/ miniconda. No matter. So i got 2 errors i *_have *_to ignore :  
Failed to create Anaconda menus
Failed to add Anaconda to the system PATH

Ofcourse , if i just ignore this - nothing works. Cant launch even conda : 
Failed to create process
Just cant understand why it doesn't work for me. I've installed anaconda on 4 different pc ( all win xp 64 ) And sometime it works, sometime doesn't

Regards, ALex! 

[<a target="_blank" href="http://itmages.ru/image/view/4081138/a31454fc"><img src="http://storage6.static.itmages.ru/i/16/0401/s_1459512715_4619779_a31454fcf5.png" /></a>](url)
[<a target="_blank" href="http://itmages.ru/image/view/4081144/b72cf8ba"><img src="http://storage1.static.itmages.ru/i/16/0401/s_1459512759_9917065_b72cf8ba5a.png" /></a>](url)

**Comment by msarahan** [comment] 2016-04-01 12:53
There may be up to three things at play here:

- if you have other versions of python installed and on PATH, the installer may erroneously try to use them to make menus, and will probably fail.
- there was a race condition in the installer scripts that led to deletion of scripts before they finished installing. This fix has not yet been released in a miniconda installer.
- our python 2 installers don't properly support non-ASCII characters right now. Python 3 installers should, but more recent ones do not support Windows XP.

I hope this helps you narrow it down.  If you can isolate it, please let us know.

**Comment by IkiAlex** [comment] 2016-04-01 14:31
ty for fast reply. 
1. I thought about it. That's why i've installed "clean" ver of win xp as virtual machine
2.I also tried to install anaconda instead miniconda and received the same error. I only work with mini right now,cause it's faster to test (30 vs 300 Mb)
3. I have to use python2. I can't see any non-ASCII chars in any path. Maybe there is some kind of trick i should use to avoid this error with changing some registry key.

**Comment by msarahan** [comment] 2016-04-01 14:33
what locale is the system set to?  Do you have any way of sharing the VM with us so we can study this more closely?  Our main issue in studying this problem has been inability to reproduce it.

**Comment by IkiAlex** [comment] 2016-04-04 10:00
sry fo long no-respond .This is exactly what i'm using right now: 
https://yadi.sk/d/nnHEzl0WBCumY

**Comment by IkiAlex** [comment] 2016-04-06 09:53
Well.... I have nothing to say. Now it works on my vm (2 d ago didnt, now does! ) I did nothing. 
And still i cant install it to my work pc ( where i need this ) 
I just dont know whats going on ...

**Comment by msarahan** [comment] 2016-04-06 12:53
It sounds like our race condition is still alive and well.  I will try to investigate.

Even when that part of the installer fails, you should be able to use the installed python, though.  Open a prompt in the folder where you installed it, and run python from there.  Does it work? If not, any error would be helpful to understand why the installer might be failing.  If it works and you just want to run with it, you can manually modify PATH and install shortcuts.  Let me know if the installed python works, and I'll point you to directions.

**Comment by IkiAlex** [comment] 2016-04-08 11:02
Ty for your time,I appreciate You still trying to help. Sry for long no-respond sometimes. 
Well, quote : ".. If it works"
I wish...it would be to easy.   But it doesn't 
"Could not execute specified program" , when i'm trying to run  c:\Miniconda2\python.exe 
"the application was not running because it is incorrectly configured. Re-installing the application may fix this problem" if i 'm trying to execute python.exe at folder (by double clicking) . 
"Failed to create process" when i'm trying to run ..\conda.exe

**Comment by IkiAlex** [comment] 2016-04-08 11:30
Well . Seems like i've found the solution. Unfortunately I can't test it now , cause I haven't access for all machines right now , but it works at local pc ( same as others) 
The solution was to easy. i only had to install (vcredist_x64.exe ,  Microsoft Visual C++ 2008 Redistributable Setup ) I'll reply next week does it rly fixes the problem, but guess so

**Comment by g4u55i4n** [comment] 2016-05-25 17:52
Hi Mike, thank you and sorry for that - sounds like incompetence to me

**Comment by SeppDeDepp** [comment] 2016-09-09 12:48
I had the same problem.
Solution: Execute the "addpath", "mkdirs", and "mkmenus" for the cmd with admin rights.

![bsp](https://cloud.githubusercontent.com/assets/9266221/18387265/e8ebe42e-769b-11e6-9201-95a813047e19.PNG)

Without admin permission this error shows up

![prob](https://cloud.githubusercontent.com/assets/9266221/18387250/d0d50348-769b-11e6-9d33-2df518e5b008.PNG)
("Zugriff verweigert" means permission denied)

Here my install log [log.txt](https://github.com/ContinuumIO/anaconda-issues/files/463963/log.txt)

**Comment by jcmorris-mts** [comment] 2016-09-17 07:30
Just to make SeppDeDepp's answer a bit more convenient...

1. Save the code below as a batch file in <ANACONDA_HOME> where your python is located.
2. Run it as an admin.  Works a treat!

Assuming <ANACONDA_HOME> = "C:\Anaconda3"

```
REM Fix.bat
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" addpath
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" mkdirs
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" mkmenus
```

**Comment by eunseoplee90** [comment] 2016-09-22 12:38
Hi~

I am trying to install minianaconda, but I cant.
When installing, I had the same problem, and following above method.
Until 'addpath' and 'mkdirs' are worked well, but at entering mkmenus, I have some problem like this.
![image](https://cloud.githubusercontent.com/assets/9734295/18748332/c4601ab4-810c-11e6-98a8-e5493ae46a66.png)
![image](https://cloud.githubusercontent.com/assets/9734295/18748347/ce6ee47c-810c-11e6-8134-28992d408e22.png)

(I run 'cmd' as admin.)

Please help me :(

**Comment by prithvikg** [comment] 2016-09-24 21:21
Did some research and found out it was because my path variable was too long. Windows apparently has a limit of 1024 for path length. so i cleared some variables and reinstalled and it seemed to work fine

**Comment by luishang** [comment] 2016-09-26 00:59
Same problem here. 'addpath' and 'mkdirs' worked well, but mkmenus, didn't. I'm also running in cmd as an administrator and the length of my path is shot: c:\Anaconda

**Comment by BillDineen** [comment] 2016-11-09 15:37
I have a new laptop with win 10 64 and have the exact same issue on first installation attempt. Any suggestions?

**Comment by eunseoplee90** [comment] 2016-11-10 08:47
Hi~ 

I have solved this problem.

In my case, English is not my native language, so when I install windows 10 in my computer, I type my name as Korean.

This cause the problem like this. 

Thus, I change my name into one as English, It works well.

**Comment by caioproiete** [comment] 2016-11-22 21:35
I've just had the same issue on a Windows 10 machine (Anaconda2-4.2.0-Windows-x86_64.exe). No special characters in my name or path, no blank spaces either, my user is admin on the machine, and UAC is turned off.

Running `addpath`, `mkdirs`, and `mkmenus` from an elevated prompt didn't work either.

**The only way I could make it work, as running the installer as Administrator, and installing it for All Users**.

**Comment by rTfact** [comment] 2016-12-01 13:46
Had the same problem on Windows 8.1 Enterprise.
Tried the fix-script, but it didn't fix things.
My path is not very long: approx 163 chars. Std. ascii username.
Anaconda3 4.2.0 (64-bit).
Installing for All as Admin worked.

**Comment by MarkusFK** [comment] 2016-12-03 10:30
I tried the same that @caioproite sugested on my Win 10 (64 bit system) with (Anaconda2-4.2.0-Windows-x86_64.exe), run it as admin installing for all users. And it didn't work. Got following message:
![anaconda error_4](https://cloud.githubusercontent.com/assets/24353213/20858712/e4438f60-b94b-11e6-806b-f01436aac306.PNG)

Can anybody help me? thanks.

**Comment by TheBeege** [comment] 2016-12-15 09:22
So if this is such an easily fixed problem, why isn't the Windows installer fixed? 

Is there a repo for it? I'd be disappointed if there's not a PR already, but I'll create one if there isn't.

**Comment by TheBeege** [comment] 2016-12-15 09:25
@MarkusFK - I'm _guessing_ you should be able to change line 172 in knownfolders.py to use path.decode('utf8') rather than whatever codec it's attempting to use. Why it's not designed to select the correct codec is beyond me.

**Comment by msarahan** [comment] 2017-01-09 19:24
@TheBeege the code for this is menuinst.  Specifically, https://github.com/ContinuumIO/menuinst/blob/master/menuinst/knownfolders.py#L168

It is trying to detect the right codec, but I might be totally wrong in how I do it.  PRs welcome on menuinst.

We have also reworked the installers for the coming Anaconda 4.3 release to disallow unicode paths when installing a Python2 distribution, and to warn people about these paths with Python 3.  Accented characters unfortunately just break a lot of Python 2 software, and we can't fix the entire ecosystem.

**Comment by vaibhavgupta2205** [comment] 2017-01-09 20:57
Hi @msarahan,

I tried installing both the versions i.e 2.7 as well as 3.5 for 64 bit Windows OS. Got the following three issues in order as mentioned :-
- Failed to create Anaconda menus
- Failed to create Anaconda directories
- Failed to add Anaconda to the system PATH
Can you please help me out here by letting me know what steps exactly to follow as I am completely new to this,

**Comment by Jang-neudern** [comment] 2017-01-11 08:06
Finally installed.

1. I'm a Korean and using non-ASCII user name. (in Korean, not English)
  -> creating new account for my window10, user name is in English.
2. IntelliJ, blueJ, JDK were installed.
 I still do not understand relation, but they can affect path modification or something somehow (that's what I've searched)
-> uninstall and delete paths (you can google how to)
3. I'm not sure path variable was too long or short enough. -> just make new account name in one alphabet 'j'.
4. vaccine : did not turn off
   anti-malware program : did turn off.
   (I still do not know causality, I just did -_- ;;)
5. selected user only install

Thank you all!

**Comment by Jang-neudern** [comment] 2017-01-11 08:33
I tested several times more, 

My problem was just other pre-installed programs or their paths, I think.

without a new account, without a vaccine turned off, without some kinds of modifying the length of path variable, installed.

**Comment by rmundkowsky** [comment] 2017-02-04 18:46
Had this problem with Miniconda (latest I think 4.3.0) and Anaconda 4.3.0 on Windows 8.1 (64 bit, default USA English). The failure happens near end of install of these apps, so do not try to install Anaconda, because it just takes longer to fail.  Making your path short, installing as Admin, installing Visual Studio redist executables, and using 32 bit rather than 64 bit version does NOT help. The following does work:

0) ****** UNINSTALL ALL PYTHON INSTALLATIONS, OTHERWISE THEY WILL GET MESSED UP AND YOU CANNOT CLEANLY UNINSTALL THEM WITHOUT WINDOWS RESTORE, or at least I think these two problems were related *****
1) Install Miniconda
2) As Admin open CMD and change to directory where Miniconda is installed
3) pythonw.exe -E -s "Lib\_nsis.py" addpath
4) pythonw.exe -E -s "Lib\_nsis.py" mkdirs
5) pythonw.exe -E -s "Lib\_nsis.py" mkmenus
6) exit that CMD
7) I then ran Anaconda prompt from start menu, but you likely can use CMD
note) if you run "conda list", you will see no packages installed, but good news is conda will install pacakges, so:
8) conda install numpy
note) this will install conda! lol
9) conda install anaconda

Now, I am not sure if environment is totally fixed, because if you run the following it fails, but likely a different bug:
modules('help')
But if you run some tests like following it seems to work
import numpy
numpy.test('full')

So Anaconda developers, please fix this, or make install easier (e.g. just unzip a bunch of files, we really do not need links in menus and etc, just python and packages).

**Comment by sayingu** [comment] 2017-02-07 01:36
I had a same problem at this line

> Creating Anaconda menus...  
> Execute: "C:\Users\sayin\Anaconda3\pythonw.exe" -E -s "C:\Users\sayin\Anaconda3\Lib\_nsis.py" mkmenus  

I deleted user variable Path `C:\Program Files (x86)\Google\google_appengine\` and it's worked.

And I guess [Miniconda](https://conda.io/miniconda.html) don't have this issue.
Because I have installed no errors same settings at my home.

**Comment by 11leven** [comment] 2017-03-02 19:25
For win10 , Abort the installation when you see "Failed to create ( add ) Anaconda menus "

Restart the installation by right clicking the installation file and 'Run as Admin'. 
Allow it to access by all users of the system.

**Comment by rmundkowsky** [comment] 2017-03-02 19:43
Tried that on Windows 8.1 and that does not work.

Robert

**Comment by yangwe1** [comment] 2017-03-22 07:39
I had the same problem, and finally solved it by reinstalling anaconda in root directory like C:\.Maybe there are some troubles related to privileges.

**Comment by yvi1** [comment] 2017-04-01 01:58
Encountered the same installation error with Anaconda3-4.3.1-Windows-x86_64 and Windows 10. Used @jcmorris-mts fix above.

**Comment by rmundkowsky** [comment] 2017-04-03 14:50
I wonder if might also be related to having multiple c++ redistributable packages installed.

**Comment by yvi1** [comment] 2017-04-03 18:16
After I removed all python distributions from my computer and cleared all PATHs related to python in sysdm.cpl, the installation worked fine with the following options.

1. did NOT have to run it "as administrator"
2. installed it "for myself only"

**Comment by sis6789** [comment] 2017-04-04 13:12
1. Start CMD with admin. 
2. Start anaconda installer within CMD window as command.

That is all!

**Comment by rmundkowsky** [comment] 2017-04-04 13:42
Actually that is not all that is needed!  Read the thread and other internet posts.

**Comment by piilupart88** [comment] 2017-04-25 10:21
![anaconda menu](https://cloud.githubusercontent.com/assets/19267402/25380392/cab11224-29b8-11e7-8dde-10c65d43a8b6.png)

Same here. I have Windows 10, admin rights and no odd characters. 
My installer refused to create Anaconda menus, and add Anaconda to PATH.

Like @Jang-neudern I had previosly installed some other IDEs and set up paths for Java.

My solution: delete preiously set up Java paths and voila!
![inkedjavahome_li](https://cloud.githubusercontent.com/assets/19267402/25380721/e835d0c2-29b9-11e7-8846-614ec1df0458.jpg)
![inkedjavajdk_li](https://cloud.githubusercontent.com/assets/19267402/25380730/f0281c2c-29b9-11e7-841a-7eabdb7676b8.jpg)

**Comment by xdnh** [comment] 2017-04-25 16:02
I changed my environment variable and deleted JAVA&jdk...
And it works!

**Comment by goanpeca** [comment] 2017-04-25 22:31
@electronwill might be worth documenting this somewhere?

**Closed** 2017-04-25 22:31 UTC

**Comment by electronwill** [comment] 2017-04-25 23:11
Yes, it would be good to add an item to https://docs.continuum.io/anaconda/troubleshooting about the errors "Failed to create Anaconda menus" and "Failed to add Anaconda to the system PATH". I'll draft a PR so we can discuss it.

**Comment by mingwandroid** [comment] 2017-04-25 23:19
I can't think why the `JAVA_HOME` env. var would have any bearing on this .. I need to look into that.

**Comment by goanpeca** [comment] 2017-04-26 00:09
>I can't think why the JAVA_HOME env. var would have any bearing on this .. I need to look into that.

Me neither :-|

**Comment by christakahashi** [comment] 2017-04-26 21:37
I'm having the same issue.  win 10, x64, US english local.  no space or non-ascii chars. short paths. 
opening an admin command prompt and retyping the failed installer commands seems to work (i say seems because they run without errors).  

```
C:\WINDOWS\system32>"C:\Users\chris\Anaconda2\pythonw.exe" -E -s "C:\Users\chris\Anaconda2\Lib\_nsis.py" mkmenus

C:\WINDOWS\system32>"C:\Users\chris\Anaconda2\pythonw.exe" -E -s "C:\Users\chris\Anaconda2\Lib\_nsis.py" mkdirs

C:\WINDOWS\system32>"C:\Users\chris\Anaconda2\pythonw.exe" -E -s "C:\Users\chris\Anaconda2\Lib\_nsis.py" addpath

C:\WINDOWS\system32>"C:\Users\chris\Anaconda2\pythonw.exe" -E -s "C:\Users\chris\Anaconda2\pkgs\.cio-config.py" "C:\Users\chris\Downloads\Anaconda2-4.2.0-Windows-x86_64.exe"
```

Then attempting to open navigator gives me some issue about not finding qt.  

In the anaconda prompt i was able to run

```
conda install qt
```
which allows navigator to open.  hopefully that's all i need to do to get it running.

**Comment by MayankArya19** [comment] 2017-06-09 18:17
i am getting only one error and that says anaconda menus cant be in installed

**Comment by AndrewKemendo** [comment] 2017-06-22 18:30
I'm on a Surface Book 64bit Win10 and used the above solution from April 25th:  https://github.com/ContinuumIO/anaconda-issues/issues/732#issuecomment-296987211 and it worked.

Deleted the Oracle java path in environment variables

**Comment by kswgit** [comment] 2017-06-25 03:25
I got a same problem, and I deleted my 'erlang' environment variable and it work.

**Comment by solenovex** [comment] 2017-07-04 01:49
I don't have java or jdk path in my environment, but still got the same problem...

**Comment by solenovex** [comment] 2017-07-04 01:58
I don't have java or jdk path in my environment, but I still got the same problem when installing.     
Then I ignore the errors, I manually execute the command:     
"C:\Users\solen\Anaconda3\pythonw.exe" -E -s "C:\Users\solen\Anaconda3\Lib\_nsis.py" mkmenus"    
and the command execution was successful, menus were created in the start menu, but when I open ipython or jupyter notebook, there is an error: "This application failed to start because it couldn't find or load the Qt platformplugin "windows" in ""."

**Comment by poleguy** [comment] 2017-07-05 18:22
I had the same problem on Win 7. I looked in the install details and ran the command listed there directly from the cmd.exe shell manually and it worked:
"C:\Anaconda3\pythonw.exe" -E -s "C:\Anaconda3\Lib\_nsis.py" addpath 3.6.1 Anaconda3 4.4.0 64-bit

**Comment by Kernalcorn82** [comment] 2017-07-14 20:24
Well! Seeing as this thread is still being looked at nowadays, I was having the whole no menus, path and such at the end of the installation. I uninstalled and reinstalled like a lunatic for a few days and thanks to this thread decided to run the installation in admin mode. By installing for all users it worked like a charm. 
I was using windows 10, 64-bit OS, and anaconda3 4.4.0

Keep fighting the good fight brothers and sisters, you can solve this problem!

**Comment by tpjoe** [comment] 2017-07-16 08:29
Had the same issue, just solved this problem by deleting the variables in PATH so that the total PATH characters (space and semi colon included) from both "USER" and "SYSTEM" combined is below 1000. I also deleted all variables that have parentheses. Then install with admin.

**Comment by cjalvarado** [comment] 2017-07-31 21:34
Whew!  I'm running the same set up most describe (Windows 10 64-bit anaconda3 4.4.0) and getting the same error(s).  After days of "uninstalling and reinstalling like a lunatic" (as @Kernalcorn82 describes) earlier this year, nothing (running as admin, stalling for Just me, installing for everyone, all of the fixes with the post-install scripts, etc) worked and I had given up.  But today I finally went back to this thread and saw the new information about Java and the path, and lo and behold removing the Java entries, as well as those with parentheses, from my path and the system path worked!  I also removed my CLASSPATH, for the record, even though I doubt that was it (but who knows...).  Both installing for all and installing for just me (running as admin just in case) worked.  So relieved to have a solution!

**Comment by javaSunson** [comment] 2017-08-07 03:05
when I delete all of the path ,install stil error

**Comment by niejijing** [comment] 2017-09-02 09:43
if u encounter this problem, UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4
please get into this path, usually, C:\ProgramData\Anaconda2\Lib, edit _nsis.py， add two lines under 'import sys' as:
reload(sys)
sys.setdefaultencoding( "utf-8" )
then in dir C:\ProgramData\Anaconda2, enter the cmd:
python .\Libs\_nsis.py mkmenus

**Comment by TutCanada** [comment] 2017-09-06 18:59
I had this same problem in Windows 10, while installing from the executable Anaconda3-4.4.0-Windows-x86_64.exe. After trying several options, including the commands suggested above by christakahashi, the one that worked for me was to turn OFF virus checking in Windows Defender.

**Comment by 8gentile** [comment] 2017-10-23 21:50
use cmd not powershell. problem solved

**Comment by cvredenburgh** [comment] 2017-11-04 21:54
OK, working in Win 10 on Dell XPS turning off the Win Defender and installing as Administrator for all users after uninstalling other versions of python worked.

**Comment by edogaafx** [comment] 2017-11-05 13:32
As for me, I got python 3.5 already and a lot of other developer tools on my dekstop pc.
Running Anaconda3.5.0.1 installer **as Administrator** and choosing install path **without spaces** solved the problem.

**Comment by slipnickeldatamunch** [comment] 2017-11-14 16:24
The fix for me was to adjust one of the two java path statements.  When you look at it in Windows 10 GUI, all look the same but when you see it in text, the /bin entry is in quotes.  Removing those quotes allowed it to complete without removing the java path statements.

**Comment by rmundkowsky** [comment] 2017-11-14 16:29
I am guessing that the installer like had a problem based on multiple visual c++ binaries being installed.  I currently only have one and the install worked fine. Back when I had the problem, I had multiple visual c++ binaries installed. This is totally a guess to the root cause of the problem.  But I do thing other settings help (e.g. keep path to Conda short, no spaces in the path, install as admin).

**Comment by larssonbajra** [comment] 2017-11-15 04:07
![anaconda](https://user-images.githubusercontent.com/25429466/32818336-ed534e26-ca05-11e7-887f-432c38217d3c.PNG)

This is the error im facing.. Please help

**Comment by goanpeca** [comment] 2017-11-15 14:25
@larssonbajra please open a new issue

**Comment by jtcours** [comment] 2017-11-30 06:42
Hello all. I may have a handle on part of the problem. I'm hoping it sparks some ideas for others.

We're installing _without_ admin privileges--local user only--on a Win 7 Enterprise 64 bit machine. 

We first ran into the failure to create menus. I worked around it by opening a command prompt and running the commands below, following the lead of some of the previous posters.  If you try this step, please note that I had to run them using python.exe, not pythonw.exe, and that I ran them from the installation directory:

```
C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3>python.exe -E -s "C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3\Lib\_nsis.py" addpath
C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3>python.exe -E -s "C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3\Lib\_nsis.py" mkdirs
C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3>python.exe -E -s "C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3\Lib\_nsis.py" mkmenus
```
That got us menu entries and a working Jupyter notebook.

The next problem was when we tried to launch Spyder. It gave the same popup others have been getting about a missing Qt plugin: `This application failed to start because it could not find or load the Qt platform plugin "windows" in "".`

The first issue was that the path to spyder-script.py in the menu shortcut for Spyder was too long, and Windows truncated it at 260 characters. Here's what was in the shortcut's target. Notice there's no trailing close quote:
`C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3\pythonw.exe C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3\cwp.py C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3 "C:/Users/mnagamin/AppData/Local/Continuum/Anaconda3/pythonw.exe" "C:/Users/mnagamin
`

I'm not sure whether Windows keeps the full path buried somewhere, but just in case I created copy of cwp.py called cwp2.py and modified it to expand the "@" symbol to a full path: 
```
# ADJUSTMENT:	
# If the caller included the "@" symbol in the args, replace it with
# the value of prefix to let callers use a shorter path.
args = [arg.replace('@', prefix) for arg in args]

subprocess.call(args, env=env)

```
That let me shorten the target in the menu entry to this:
`C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3\pythonw.exe C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3\cwp2.py C:\Users\mnagamin\AppData\Local\Continuum\Anaconda3 "@/pythonw.exe" "@/Scripts/spyder-script.py"`

Unfortunately, pythonw is still generating the error about the missing Qt plugin. The empty string in the popup suggests it's getting an incomplete search path, but I'm not sure where its path information comes from.

**Comment by mohansriramakrishna** [comment] 2017-12-09 04:38
I am having same problem, I think why this happen to me is because of I was deleted Anaconda3 folder instead of uninstalling it. So, when I am trying to reinstall it , It's saying failed to add menus. I have to clean the previous paths and other stuff. I don't know how to this please help me to overcome this.

**Comment by prihu** [comment] 2017-12-18 11:36
https://docs.anaconda.com/anaconda/user-guide/troubleshooting#windows-error-failed-to-create-anaconda-menus-or-failed-to-add-anaconda-to-the-system-path. Following this with All users did the trick for me

**Comment by mohansriramakrishna** [comment] 2018-01-02 06:54
Here is the solution I have found.
1. Locate to the Anaconda3 directory where it is installed.
2. And then go to the lib directory.
 Open cmd type below commands.
  >>>cd C:\Anaconda3\Lib (Assume installed directory C:\)
3. Run _nsis.py . Follow below steps to addpath, mkdirs, mkmenus
 >>>C:\python.exe _nsis.py addpath
 >>>C:\python.exe _nsis.py mkdirs
 >>>C:\python.exe _nsis.py mkmenus
That's it. Hope it'll helps you to solve this problem.

**Comment by VincentRouvreau** [comment] 2018-01-24 10:03
Thank you @piilupart88 I had an old Java path installation in my Path environment variable. I removed it, and **it works** !!

**Comment by ImmortalSon** [comment] 2018-02-21 09:47
After trying almost all suggestions in this thread (removing java entries from PATH, running the installer as normal user / admin, installing only for myself / everyone, installing Miniconda and running conda install anaconda, running the scripts after install, uninstalling and reinstalling a dozen times) - nothing worked. The menu items in start menu stubbornly remained missing, and the anaconda prompt gave the infamous activate.bat error.

There was one suggestion that I could not try: temporarily disabling the anti-virus (Webroot SecureAnywhere), as it is a company machine (Surface Pro 4) and corporate policy doesn't allow even opening the Webroot interface, let alone disable it temporarily. Upon a hunch, I decided to try and install Anaconda in Windows SAFE MODE, and it worked!

Here's what I did:
1. Uninstalled old non-working Anaconda, cleaned up PATH, restated machine. I had JRE installed (not JDK), but I didn't uninstall it, as I need it for other programs. Also, there were several VC++ runtimes installed, I left them all alone.
2. As given in https://www.itecs.ncsu.edu/helpdesk/kb/installing-programs-in-safe-mode/ I enabled services for installing programs in safe mode.
3. Entered Safe Mode via shift-restart  and chose WITHOUT networking, since I had downloaded the full Anaconda 5.1.0 x64 installer, and wasn't going to install vscode - I wanted the fewest services running. Crucially, Webroot SecureAnywhere wasn't running.
4. Installed Anaconda for all users into the default C:\ProgramData\anaconda3 folder, and accepted the default options on PATH (unchecked) and registering python (checked).
5. Skipped installing  vscode.
6. Rebooted normally. Lo and behold, Anaconda installed properly with all menu entries! I started Navigator for the first time, and launched Spyder with out any issues. Whew!

And created a GitHub account to post this update, in case there is any one else tearing their hair trying to install Anaconda...

**Comment by alexeiz** [comment] 2018-03-10 07:58
How come this is closed?  The issue is still here.  I hit it when trying to install miniconda via scoop.  Scoop runs the installer in silent mode, so the problem becomes even harder to identify.

Anyway, the issue has to do with either Windows PATH being too long, or PATH containing non-existent directories, or the whole environment variables block is too large.  I was able to resolve this issue by reducing PATH to bare essentials temporarily in a command prompt:

```
set Path=C:\Windows\System32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0
```

And when I ran the installer from that command prompt, it finally worked.

**Comment by jetilton** [comment] 2018-04-02 18:02
I had the same issue went through a lot of the above.  Deleted anything anaconda/conda related and deleted my Path variable for my user.  Everything installed as expected.

**Comment by mars0925** [comment] 2018-04-04 03:00
delete all Environmental variables PATH and install again. it work for me

**Comment by yhling** [comment] 2018-04-04 13:43
Trying to install Anaconda 64-bit on a Windows 7 work machine, with only user privileges.

The only thing that worked for me is installing it under C:\. Installation completed successfully.

**Comment by ldfreight** [comment] 2018-05-22 08:10
issue is still there. I am installing for all users  with an admin account, on default path C:\ProgramData\Anaconda3

**Comment by akhilachitluri** [comment] 2018-09-29 06:37
I am trying to install Anaconda2 version 5.2.0 32-bit in windows .I am getting this error. 
![error](https://user-images.githubusercontent.com/25925825/46242005-3b502980-c3e0-11e8-94e6-d482158ac9a6.PNG)

**Comment by bbakk14** [comment] 2018-10-31 01:53
Also getting this error and have been banging my head against the wall trying all of the suggested solutions in this thread. Any further help would be really appreciated!

![capture](https://user-images.githubusercontent.com/35664241/47761246-0ad50700-dc8e-11e8-8f27-42eef7e08fc9.JPG)

**Comment by nehaljwani** [comment] 2018-11-03 07:18
@bbakk14 Open command prompt. Type: `set COMSPEC`. What do you see in the output? If it points to a file, please double check whether it exists.

**Comment by bbakk14** [comment] 2018-11-12 02:49
@nehaljwani It just says  `ComSpec=C:\Anaconda3;` when I type `set COMSPEC` in CMD.

**Comment by nehaljwani** [comment] 2018-11-23 04:30
Usually, in a Windows installation, the value of the `ComSpec` variable is `C:\Windows\system32\cmd.exe`, I am surprised that it points to `C:\Anaconda3` for you 🤔

**Comment by medengineer** [comment] 2019-06-18 23:15
Hoping it helps someone, I kept getting the 'failed to make menus' error on Win10. Removing Java from environment path did the trick.

**Comment by diegormsouza** [comment] 2019-10-23 19:21
Hi all,

It happened to me and I solved doing this:

1-) Delete all variables from PATH (make a backup, to be able to put them back again later).
2-) Deleted JAVA SDK and JAVA related variables
3-) Downloaded an old version of Miniconda (early 2019): https://repo.continuum.io/miniconda/

Then it installed well. After that, put the PATH variables back.

**Comment by anderl80** [comment] 2019-11-20 11:41
Whaaaat? Cannot be true!! Anaconda starts to do weird things on my environment...

**Comment by vxfranky** [comment] 2019-12-25 08:54
Another solution: install Microsoft Visual C++ Redistributable. Visit https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by piyushshahu** [comment] 2020-01-27 15:57
If you are using windows 7 and if this problem persists after formatting. Just update to service pack 1 (KB976932) then install another update of KB2999226. This helps in my case to solve the "create menus" problem.

**Comment by HridoyHazard** [comment] 2022-06-23 06:40
i'm having the same issue now. tried 64bit and 32bit both but there were no problem while installing but after the installation i don't have anaconda-navigator in start menu or anywhere. i have this folder in installation directory.and if i open the conda.exe file it just automatically close after open. plz help
![image](https://user-images.githubusercontent.com/71395891/175232062-ebf81bc2-7214-4158-a022-18b3859210ac.png)
