### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by shintkb** [ContinuumIO/anaconda-issues#3642] opened 2017-07-28 06:55 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-32/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-32/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 405 Method Not Allowed',)))",),)

```
## System information
```
python: 3.6.1
language: ja_JP
os: Windows;7;6.1.7601;x86;x86 Family 6 Model 58 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-32
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment] 2017-07-28 06:56
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-28 06:56 UTC
Labels: pkg:navigator, reso:duplicate
