### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by twwendyyu** [ContinuumIO/anaconda-issues#7530] opened 2017-11-28 04:58 UTC
# **Main Error**
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=3188)

# **Traceback**
```
File "C:\Users\USER\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\USER\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\USER\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\USER\Anaconda2\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\USER\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=3188)
```

# **System Information**
```
             platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\Users\USER\Anaconda2  (writable)
    default environment : C:\Users\USER\Anaconda2
       envs directories : C:\Users\USER\Anaconda2\envs
                          C:\Users\USER\AppData\Local\conda\conda\envs
                          C:\Users\USER\.conda\envs
          package cache : C:\Users\USER\Anaconda2\pkgs
                          C:\Users\USER\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\USER\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : False

```

**Comment by goanpeca** [comment] 2017-11-28 04:58
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-28 04:58 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by goanpeca** [comment] 2017-11-28 05:02
**See Issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
