### ISSUE TITLE
Python Has Stopped Working

### ISSUE THREAD

**Issue by tech-team-user-2** [ContinuumIO/anaconda-issues#1538] opened 2017-03-20 08:16 UTC
I am Newbie In Python. Few Years Before I Installed Python 3.5.0 With IDLE. After Sometime, a malware infected  my PC and IDLE Didn't Start and I removed the malware, even after that it didn't start but the Code Window Runs Perfect but when I run The Python Shell it says Python has Stopped Working.Please Somebody Comment And Help Me Solve This Issue.For More Details About My PC:--
OS : - Windows 7 Ultimate SP1 (32-Bit)
RAM : - 2 GB
CPU : - 1.66Ghz (Dual-Core Processor)
GPU : - 256.00 MB
For More Information About My PC Visit This Link : --
https://www.cnet.com/au/products/dell-inspiron-6400/review/

**Comment by goanpeca** [comment] 2017-03-21 17:38
@tech-team-user-2 are you using the anaconda distribution at all?

**Comment by markgross** [comment] 2017-03-25 15:17
I get the same problem.  Using Windows 10, anaconda version 4.3.1-64bit.

To reproduce run python or ipyton in power shell, start help(), then modules.

the system will report python has stopped working.

See screen cap of event....

![image](https://cloud.githubusercontent.com/assets/62436/24323487/7711c778-1133-11e7-920c-25914e7adb72.png)

**Comment by goanpeca** [comment] 2017-03-25 21:31
@ilanschnell @mingwandroid ?

**Comment by Abhishek2997** [comment] 2017-05-19 08:06
I also had the same problem. On opening Ananconda Navigator, it showed Initializing... and then 'Pyhton has stopped working'.
Solution:
Instead of Anaconda Navigator, Open Anaconda Prompt and in the command window type 'spyder'. Wait a few seconds and spyder will get launched

**Comment by tech-team-user-2** [comment] 2017-05-20 04:42
No I am not using Anaconda Sorry For The Delay. I don't use any modules from outside.

**Comment by tech-team-user-2** [comment] 2017-05-20 04:45
No guys i am not using any module i am not using anaconda. I am not using modules @markgross @Abhishek2997 @goanpeca

**Comment by tech-team-user-2** [comment] 2017-05-20 04:47
Well Thanks for your comments please try help me solve this probem. Regards, tech-team-user-2.

**Comment by ccordoba12** [comment] 2017-05-20 13:13
Well, if you're not using Anaconda, this is not the right place to ask for help, sorry.

Closing as *won't fix*.

**Closed by ccordoba12** 2017-05-20 13:13 UTC
Labels: reso:wontfix

**Comment by Zizanno** [comment] 2017-07-07 08:51
I get the same error when trying to run Anaconda Navigator or spyder: Python has Stopped working

**Comment by CGN38** [comment] 2017-07-17 13:13
Is there a work around for this.  It pretty much makes Anaconda Navigator useless at the moment.  

I'm running windows 10.  Any time you try to save or open a file in Orange3, Spyder, glueviz, ... you will get the "Python has stopped working."  Basically any time the windows file manager opens.  I have a few ideas I'm going to try, but I was hoping somebody has already solved this.

**Comment by Aroniez** [comment] 2017-07-26 21:12
Same issue on windows 7-64 bit. Cant run Anaconda Navigator or Anaconda Prompt

**Comment by sarmadsalman** [comment] 2018-01-27 16:32
I'm suffering from the same problem on Windows 7-64 bit. Cant run Anaconda Navigator and Anaconda Prompt and pycharm and IDLE's

**Comment by heemansh** [comment] 2018-02-25 03:32
message prompts saying that the python stopped while  opening file manager in anaconda

**Comment by BhekiMabheka** [comment] 2018-04-19 08:02
I am using Anaconda, getting the same error

**Comment by LikhinNelliyotan** [comment] 2018-09-01 07:14
I have same Problem and solved
Please Follow following Steps
1.conda install -c anaconda qt 
2. conda update qt pyqt
start again

**Comment by akbism** [comment] 2019-02-22 17:41
> I have same Problem and solved
> Please Follow following Steps
> 1.conda install -c anaconda qt
> 2. conda update qt pyqt
> start again

Bang on target. It worked after I tried this and that!!!

**Comment by vikramnist** [comment] 2019-05-19 13:38
I have tried all the methods its not working . When i launch jupyter notebook error is coming as python has stopped working.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	3.7.3150.1013
  Application Timestamp:	5c9bf5b3
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7600.16385
  Fault Module Timestamp:	4a5bdfe0
  Exception Code:	40000015
  Exception Offset:	000000000000aa7d
  OS Version:	6.1.7600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	688b
  Additional Information 2:	688b37186dc3dae3bf899ff7bea759df
  Additional Information 3:	e6b2
  Additional Information 4:	e6b23b0fa05554c67a37157288f7e4ae

can anybody help me out with this issue.

**Comment by sunnygulati** [comment] 2019-06-26 20:00
> I have tried all the methods its not working . When i launch jupyter notebook error is coming as python has stopped working.
> 
> Problem signature:
> Problem Event Name:	APPCRASH
> Application Name:	python.exe
> Application Version:	3.7.3150.1013
> Application Timestamp:	5c9bf5b3
> Fault Module Name:	KERNELBASE.dll
> Fault Module Version:	6.1.7600.16385
> Fault Module Timestamp:	4a5bdfe0
> Exception Code:	40000015
> Exception Offset:	000000000000aa7d
> OS Version:	6.1.7600.2.0.0.256.48
> Locale ID:	1033
> Additional Information 1:	688b
> Additional Information 2:	688b37186dc3dae3bf899ff7bea759df
> Additional Information 3:	e6b2
> Additional Information 4:	e6b23b0fa05554c67a37157288f7e4ae
> 
> can anybody help me out with this issue.

I am getting the same error while running Python on Jupyter Notebook.
 I am using Windows 7 64 Bit.
Someone please reply.

**Comment by Aroniez** [comment] 2019-06-26 20:03
Have you tried the steps mentioned above?

1.conda install -c anaconda qt
2. conda update qt pyqt

**Comment by sunnygulati** [comment] 2019-06-26 20:08
Yes, I was installed the below through anaconda command prompt
> conda install -c anaconda qt
but whem I ran the below I got an error
> conda update qt pyqt

Please advise

**Comment by vikramnist** [comment] 2019-06-28 04:01
Remove the antivitus and install anaconda again. Hope it helps. It worked
for me

**Comment by prashantshukla003** [comment] 2019-07-22 04:22
> 
> 
> Yes, I was installed the below through anaconda command prompt
> 
> > conda install -c anaconda qt
> > but whem I ran the below I got an error
> > conda update qt pyqt
> 
> Please advise

I had the same issue. Tried all that has been said above. Then I thought to go and download latest python version and I am using Windows 7 Operating System.
And when I did that, I got the message while installing the version that
"Please upgrade your system to install python"
The problem was:
**I was not having Windows Service Pack 1 for Win 7.**

So basically, this might be your problem as well. 
Just go to the Microsoft site and download the Service Pack applicable to your OS version and install it. It will ask to restart your PC a several times.
After that, just go on Anaconda Prompt and run Jupyter Notebook. It will work fine.
This will definitely solve your problem.

**Comment by vikramnist** [comment] 2019-12-01 13:03
Hey,

I just signed the petition "Indian Judiciary: Hang the criminal(s) of
Priyanka Reddy Rape/Murder case before the 2019 year end" and wanted to see
if you could help by adding your name.

Our goal is to reach 300,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/QFDRBFr7Hz

Thanks!
Vikram

**Comment by kapil3** [comment] 2020-03-15 06:11
Run Spyder as administrator can solve your problem.

**Comment by jhorous** [comment] 2022-01-03 13:24
Thanks a lot prashantshukla003!
