### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by SaiGonguyen** [ContinuumIO/anaconda-issues#2003] opened 2017-06-06 17:05 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000009B9E13D780>, 'Connection to repo.continuum.io timed out. (connect timeout=9.15)'))",),)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-06-21 16:01
Closing as duplicate of #1932

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-21 16:01 UTC
Labels: pkg:navigator, reso:duplicate
