### ISSUE TITLE
Corrupt package tarball

### ISSUE THREAD

**Issue by kenahoo** [ContinuumIO/anaconda-issues#11132] opened 2019-07-22 18:17 UTC
NB: I followed the instructions I see in the error message, but let me know if this is the wrong place to report the error.

### Actual Behavior

Trying to install packages in an environment, results in "ERROR: Encountered corrupt package tarball" error.  

The same command in different environments succeeds reliably, but fails reliably in this environment.

```
% /opt/miniconda/bin/conda install -n r-3.6 r-devtools r-testthat
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/miniconda/envs/r-3.6

  added / updated specs:
    - r-devtools
    - r-testthat


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    r-askpass-1.0              |    r36h14c3975_0          26 KB
    r-assertthat-0.2.1         |    r36h6115d3f_0          74 KB
    r-backports-1.1.4          |    r36h96ca727_0          63 KB
    r-callr-3.2.0              |    r36h6115d3f_0         270 KB
    r-cli-1.1.0                |    r36h6115d3f_0         189 KB
    r-clipr-0.6.0              |    r36h6115d3f_0          66 KB
    r-clisymbols-1.2.0         |    r36h6115d3f_0          25 KB
    r-crayon-1.3.4             |    r36h6115d3f_0         757 KB
    r-curl-3.3                 |    r36h96ca727_0         382 KB
    r-desc-1.2.0               |    r36h6115d3f_0         305 KB
    r-devtools-2.0.2           |    r36h6115d3f_0         402 KB
    r-digest-0.6.18            |    r36h96ca727_0         146 KB
    r-fansi-0.4.0              |    r36h96ca727_0         182 KB
    r-fs-1.2.7                 |    r36h29659fb_0         171 KB
    r-gh-1.0.1                 |    r36h6115d3f_0          58 KB
    r-git2r-0.25.2             |    r36h96ca727_0         832 KB
    r-glue-1.3.1               |    r36h96ca727_0         159 KB
    r-httr-1.4.0               |    r36h6115d3f_0         513 KB
    r-ini-0.3.1                |    r36h6115d3f_0          31 KB
    r-jsonlite-1.6             |    r36h96ca727_0         620 KB
    r-magrittr-1.5             |    r36h6115d3f_4         173 KB
    r-memoise-1.1.0            |    r36h6115d3f_0          45 KB
    r-mime-0.6                 |    r36h96ca727_0          50 KB
    r-openssl-1.3              |    r36h96ca727_0         609 KB
    r-pillar-1.3.1             |    r36h6115d3f_0         180 KB
    r-pkgbuild-1.0.3           |    r36h6115d3f_0         156 KB
    r-pkgconfig-2.0.2          |    r36h6115d3f_0          25 KB
    r-pkgload-1.0.2            |    r36h29659fb_0         157 KB
    r-praise-1.0.0             |    r36h6115d3f_4          23 KB
    r-prettyunits-1.0.2        |    r36h6115d3f_0          38 KB
    r-processx-3.3.0           |    r36h96ca727_0         180 KB
    r-ps-1.3.0                 |    r36h96ca727_0         208 KB
    r-purrr-0.3.2              |    r36h96ca727_0         380 KB
    r-r6-2.4.0                 |    r36h6115d3f_0          68 KB
    r-rcmdcheck-1.3.2          |    r36h6115d3f_0         1.4 MB
    r-rcpp-1.0.1               |    r36h29659fb_0         3.2 MB
    r-remotes-2.0.4            |    r36h6115d3f_0         333 KB
    r-rlang-0.3.4              |    r36h96ca727_0         992 KB
    r-rprojroot-1.3_2          |    r36h6115d3f_0          98 KB
    r-rstudioapi-0.10          |    r36h6115d3f_0         240 KB
    r-sessioninfo-1.1.1        |    r36h6115d3f_0          59 KB
    r-sys-3.2                  |    r36h96ca727_0          45 KB
    r-testthat-2.1.1           |    r36h29659fb_0         1.0 MB
    r-tibble-2.1.1             |    r36h96ca727_0         303 KB
    r-usethis-1.5.0            |    r36h6115d3f_0         720 KB
    r-utf8-1.1.4               |    r36h96ca727_0         138 KB
    r-whisker-0.3_2            |    r36h6115d3f_4          82 KB
    r-withr-2.1.2              |    r36h6115d3f_0         181 KB
    r-xopen-1.0.0              |    r36h6115d3f_0          30 KB
    r-yaml-2.2.0               |    r36h96ca727_0         105 KB
    ------------------------------------------------------------
                                           Total:        16.3 MB

The following NEW packages will be INSTALLED:

  r-askpass          pkgs/main/linux-64::r-askpass-1.0-r36h14c3975_0
  r-assertthat       pkgs/r/noarch::r-assertthat-0.2.1-r36h6115d3f_0
  r-backports        pkgs/main/linux-64::r-backports-1.1.4-r36h96ca727_0
  r-callr            pkgs/r/noarch::r-callr-3.2.0-r36h6115d3f_0
  r-cli              pkgs/r/noarch::r-cli-1.1.0-r36h6115d3f_0
  r-clipr            pkgs/r/noarch::r-clipr-0.6.0-r36h6115d3f_0
  r-clisymbols       pkgs/r/noarch::r-clisymbols-1.2.0-r36h6115d3f_0
  r-crayon           pkgs/r/noarch::r-crayon-1.3.4-r36h6115d3f_0
  r-curl             pkgs/main/linux-64::r-curl-3.3-r36h96ca727_0
  r-desc             pkgs/r/noarch::r-desc-1.2.0-r36h6115d3f_0
  r-devtools         pkgs/r/noarch::r-devtools-2.0.2-r36h6115d3f_0
  r-digest           pkgs/main/linux-64::r-digest-0.6.18-r36h96ca727_0
  r-fansi            pkgs/main/linux-64::r-fansi-0.4.0-r36h96ca727_0
  r-fs               pkgs/main/linux-64::r-fs-1.2.7-r36h29659fb_0
  r-gh               pkgs/r/noarch::r-gh-1.0.1-r36h6115d3f_0
  r-git2r            pkgs/main/linux-64::r-git2r-0.25.2-r36h96ca727_0
  r-glue             pkgs/main/linux-64::r-glue-1.3.1-r36h96ca727_0
  r-httr             pkgs/r/noarch::r-httr-1.4.0-r36h6115d3f_0
  r-ini              pkgs/r/noarch::r-ini-0.3.1-r36h6115d3f_0
  r-jsonlite         pkgs/main/linux-64::r-jsonlite-1.6-r36h96ca727_0
  r-magrittr         pkgs/r/noarch::r-magrittr-1.5-r36h6115d3f_4
  r-memoise          pkgs/r/noarch::r-memoise-1.1.0-r36h6115d3f_0
  r-mime             pkgs/main/linux-64::r-mime-0.6-r36h96ca727_0
  r-openssl          pkgs/main/linux-64::r-openssl-1.3-r36h96ca727_0
  r-pillar           pkgs/r/noarch::r-pillar-1.3.1-r36h6115d3f_0
  r-pkgbuild         pkgs/r/noarch::r-pkgbuild-1.0.3-r36h6115d3f_0
  r-pkgconfig        pkgs/r/noarch::r-pkgconfig-2.0.2-r36h6115d3f_0
  r-pkgload          pkgs/main/linux-64::r-pkgload-1.0.2-r36h29659fb_0
  r-praise           pkgs/r/noarch::r-praise-1.0.0-r36h6115d3f_4
  r-prettyunits      pkgs/r/noarch::r-prettyunits-1.0.2-r36h6115d3f_0
  r-processx         pkgs/main/linux-64::r-processx-3.3.0-r36h96ca727_0
  r-ps               pkgs/main/linux-64::r-ps-1.3.0-r36h96ca727_0
  r-purrr            pkgs/main/linux-64::r-purrr-0.3.2-r36h96ca727_0
  r-r6               pkgs/r/noarch::r-r6-2.4.0-r36h6115d3f_0
  r-rcmdcheck        pkgs/r/noarch::r-rcmdcheck-1.3.2-r36h6115d3f_0
  r-rcpp             pkgs/main/linux-64::r-rcpp-1.0.1-r36h29659fb_0
  r-remotes          pkgs/r/noarch::r-remotes-2.0.4-r36h6115d3f_0
  r-rlang            pkgs/main/linux-64::r-rlang-0.3.4-r36h96ca727_0
  r-rprojroot        pkgs/r/noarch::r-rprojroot-1.3_2-r36h6115d3f_0
  r-rstudioapi       pkgs/r/noarch::r-rstudioapi-0.10-r36h6115d3f_0
  r-sessioninfo      pkgs/r/noarch::r-sessioninfo-1.1.1-r36h6115d3f_0
  r-sys              pkgs/main/linux-64::r-sys-3.2-r36h96ca727_0
  r-testthat         pkgs/main/linux-64::r-testthat-2.1.1-r36h29659fb_0
  r-tibble           pkgs/main/linux-64::r-tibble-2.1.1-r36h96ca727_0
  r-usethis          pkgs/r/noarch::r-usethis-1.5.0-r36h6115d3f_0
  r-utf8             pkgs/main/linux-64::r-utf8-1.1.4-r36h96ca727_0
  r-whisker          pkgs/r/noarch::r-whisker-0.3_2-r36h6115d3f_4
  r-withr            pkgs/r/noarch::r-withr-2.1.2-r36h6115d3f_0
  r-xopen            pkgs/r/noarch::r-xopen-1.0.0-r36h6115d3f_0
  r-yaml             pkgs/main/linux-64::r-yaml-2.2.0-r36h96ca727_0


Proceed ([y]/n)? 

Downloading and Extracting Packages
r-memoise-1.1.0      | 45 KB     | ########## | 100% 
r-crayon-1.3.4       | 757 KB    | ########## | 100% 
r-rstudioapi-0.10    | 240 KB    | ########## | 100% 
r-devtools-2.0.2     | 402 KB    | ########## | 100% 
r-digest-0.6.18      | 146 KB    | ########## | 100% 
r-r6-2.4.0           | 68 KB     | ########## | 100% 
r-rprojroot-1.3_2    | 98 KB     | ########## | 100% 
r-mime-0.6           | 50 KB     | ########## | 100% 
r-magrittr-1.5       | 173 KB    | ########## | 100% 
r-fs-1.2.7           | 171 KB    |            |   0% ERROR: Encountered corrupt package tarball at /opt/miniconda/pkgs/r-fs-1.2.7-r36h29659fb_0.conda. Conda has left it in place.  Please report this to the maintainers of your package.  For the defaults channel, please report to https://github.com/continuumio/anaconda-issues
r-fs-1.2.7           | 171 KB    | ########## | 100% 

CondaSystemExit: Exiting 1
```

### Expected Behavior

Package should be downloaded and installed successfully.

### Steps to Reproduce

The `r-3.6` environment where I'm attempting to install these packages is defined by `/opt/miniconda/bin/conda create -n r-3.6 r=3.6.0`.

This is all happening inside a Docker environment that I'm building using a Dockerfile, I can share that Dockerfile if you want.

##### Anaconda or Miniconda version:

```
# /opt/miniconda/bin/conda --version
conda 4.7.10
```

##### `conda info`

<details>

```
     active environment : base
    active env location : /opt/miniconda
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /opt/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/miniconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.21.0 CPython/3.7.3 Linux/4.9.125-linuxkit centos/7.6.1810 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at /opt/miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
asn1crypto                0.24.0                   py37_0    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2019.5.15                     0    defaults
certifi                   2019.6.16                py37_0    defaults
cffi                      1.12.2           py37h2e261b9_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.7.10                   py37_0    defaults
conda-package-handling    1.3.11                   py37_0    defaults
cryptography              2.6.1            py37h1ba5d50_0    defaults
idna                      2.8                      py37_0    defaults
libarchive                3.3.3                h5d8350f_5    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
lz4-c                     1.8.1.2              h14c3975_0    defaults
lzo                       2.10                 h49e0be7_2    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
pip                       19.0.3                   py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.3                h0371630_0    defaults
python-libarchive-c       2.8                     py37_11    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
setuptools                41.0.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.27.2               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.32.1                     py_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wheel                     0.33.1                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults
```

</details>

**Comment by kenahoo** [comment] 2019-07-22 18:19
I do have the `r-fs-1.2.7-r36h29659fb_0.conda` file if that would be helpful to look at.  It's 171K in size.  Contents are:

```
% unzip -l r-fs-1.2.7-r36h29659fb_0.conda 
Archive:  r-fs-1.2.7-r36h29659fb_0.conda
  Length      Date    Time    Name
---------  ---------- -----   ----
     3509  06-14-2019 08:49   info-r-fs-1.2.7-r36h29659fb_0.tar.zst
   171204  06-14-2019 08:49   pkg-r-fs-1.2.7-r36h29659fb_0.tar.zst
       31  06-14-2019 08:49   metadata.json
---------                     -------
   174744                     3 files
```

**Comment by msarahan** [comment] 2019-07-22 18:24
It looks like you may have gotten an interrupted download.  The file size should be about 450KB for the .conda file, or 500KB for the .tar.bz2.  From https://repo.continuum.io/pkgs/r/linux-64/current_repodata.json:

```
    "r-fs-1.2.7-r36h29659fb_0.conda": {
      "build": "r36h29659fb_0",
      "build_number": 0,
      "depends": [
        "libgcc-ng >=7.3.0",
        "libstdcxx-ng >=7.3.0",
        "r-base >=3.6,<3.7.0a0",
        "r-rcpp",
        "_r-mutex 1.* anacondar_1"
      ],
      "legacy_bz2_md5": "3153dc14bfe04f44866e6c79c849a19f",
      "license": "GPL-3",
      "license_family": "GPL3",
      "md5": "2b0f982218a12e64d10023e35b20c061",
      "name": "r-fs",
      "sha256": "b7f4d67d370e578da90d4b73c56e4c123cf4e691c914febc14a567e05cf379c5",
      "size": 457463,
      "subdir": "linux-64",
      "timestamp": 1558439278352,
      "version": "1.2.7"
    },
```

**Comment by kenahoo** [comment] 2019-07-22 18:49
In the first table of output above, it says this:

```
The following packages will be downloaded:

package                    |            build
...
r-fs-1.2.7                 |    r36h29659fb_0         171 KB
```

Does that mean some metadata somewhere is wrong?

**Comment by msarahan** [comment] 2019-07-22 18:54
That's fun and interesting...  I can reproduce it here, too.  We'll look into it.  You can download that 500 kB file and install it with just the file path:

``conda install -n r-3.6 <path to manually downloaded .tar.bz2>``

After that, try your install again.  Hopefully this gets you past the block here.

**Comment by kenahoo** [comment] 2019-07-22 18:58
Thanks, will do!

**Comment by msarahan** [comment] 2019-07-22 20:09
The problem is that we have stale metadata in the "main" channel that is taking precedence over the R channel.  We are cleaning up that metadata, and things should be back to normal quickly.

**Comment by msarahan** [comment] 2019-07-22 20:37
Confirmed that the cleaned up index no longer has this issue.  Closing.  Thanks for raising this @kenahoo

**Closed by msarahan** 2019-07-22 20:37 UTC

**Comment by kenahoo** [comment] 2019-07-22 21:19
Great, confirmed that I'm getting the right download now too.
