### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by romanceholic** [ContinuumIO/anaconda-issues#5228] opened 2017-09-08 18:25 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /anaconda-fusion/win-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001F52572BA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))",),)

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-09-08 18:27
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-08 18:27 UTC
Labels: pkg:navigator, reso:duplicate
