### ISSUE TITLE
Change in behavior launching ipython notebooks from anacona environment

### ISSUE THREAD

**Issue by jhamman** [ContinuumIO/anaconda-issues#461] opened 2015-10-07 16:44 UTC
Previously, I have been able to run ipython notebooks from Anaconda environments using this workflow:

```Bash
conda create -n test python=3.4 ipython-notebook
source activate test
ipython notebook
```
and then in a new notebook
```Python
import sys
print(sys.executable)
```
would yield
```
/Users/jhamman/anaconda/envs/test/bin/python
```
Recently, this behavior has changed (I've seen it on Mac OS and Linux for Python 2.7 and 3.4).  Now I get the root anaconda python executable:
```
/Users/jhamman/anaconda/bin/python
```

Consequently, I'm not able to import/use packages in my environments from ipython notebooks.  If I start an ipython session in the terminal, this problem does NOT exist. So this may just be an issue with the notebook kernels. 

Has anyone else seen this behavior?

**Comment by jasongrout** [comment] 2015-10-07 17:24
This is almost certainly an ipython issue to solve, though perhaps the solution will also involve some work in conda.  I think we should carry on the discussion at https://github.com/ipython/ipython/issues/8880

**Comment by ccordoba12** [comment] 2015-10-07 19:57
Closing here because this is an IPython regression.

**Closed by ccordoba12** 2015-10-07 19:57 UTC
