### ISSUE TITLE
Error when starting anaconda-navigator from environment

### ISSUE THREAD

**Issue by mbunse** [ContinuumIO/anaconda-issues#3500] opened 2017-07-24 08:51 UTC
I do not have admin rights for my windows PC. Since I got the message "This application failed to start because it could not find or load Qt platform plugin "windows" in "". Reinstalling the application may fix the problem" i followed some advise and tried
```
$ conda install qt
```
This gave me an CondaIOError with the advice to run 
```
$ conda create -n my_root --clone="C:\ProgramData\Anaconda3"
```
which is what I did.
Then I activated the my_root environment and started anaconda-navigator:
```
$ activate my_root
$ anaconda-navigator
```
This resulted in the following error message

**Navigator Error**
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker

**Main Error**
```
byte indices must be integers or slices, not str`
```
**Traceback**

Traceback (most recent call last):
```
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```

**Comment by goanpeca** [comment] 2017-07-24 08:51
Closing as duplicate of #1837

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-24 08:51 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by mbunse** [comment] 2017-07-24 10:25
Unfortunately, that did not resolve my issue:
```
(my_root) C:\Users\301512>conda update anaconda-navigator
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\301512\AppData\Local\conda
\conda\envs\my_root:

The following packages will be UPDATED:

    anaconda-navigator: 1.6.2-py36_0 --> 1.6.3-py36_0

Proceed ([y]/n)?

anaconda-navig 100% |###############################| Time: 0:00:00  54.58 MB/s
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\Users\301512\AppData\Local\conda\conda\envs\my_root', env_name: 'my_
root', mode: 'user', used_mode: 'user'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\Users\301512\AppData\Local\conda\conda\envs\my_root', env_name: 'my_
root', mode: 'user', used_mode: 'user'

(my_root) C:\Users\301512>anaconda-navigator
An unexpected error occurred on Navigator start-up<br>byte indices must be integ
ers or slices, not str
Traceback (most recent call last):
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```
