### ISSUE TITLE
Conda HTTP Error when Updating Navigator

### ISSUE THREAD

**Issue by jlw4192** [ContinuumIO/anaconda-issues#3182] opened 2017-07-14 15:49 UTC
In response to my earlier issue, I can't even update my anaconda navigator from the terminal without an http error. I can't install packages either. 

`conda update anaconda-navigator Produces this error:
`Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-
64/repodata.json.bz2>
Elapsed: None
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

SSLError(SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')"
,),),)

**Comment by goanpeca** [comment] 2017-07-14 15:49
Closing as duplicate of #1932

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-14 15:49 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by kleinash** [comment] 2019-03-11 15:45
This doesn't solve the problem of being able to upgrade or change the environments listed in the navigator. I upgrade the navigator but am unable to use it.
