### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tomaszkubacki** [ContinuumIO/anaconda-issues#4784] opened 2017-08-30 13:31 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 15:31:20.946 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 15:31:21.534 NotebookApp] Serving notebooks from local directory: /home/tomek
[I 15:31:21.534 NotebookApp] 0 active kernels 
[I 15:31:21.534 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=1fdbcc6228880c0bd5a0815eea8eacafc2bd2e2d7aa28b56
[I 15:31:21.535 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:31:21.536 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=1fdbcc6228880c0bd5a0815eea8eacafc2bd2e2d7aa28b56
[25783:25818:0830/153122.292057:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[I 15:31:22.314 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 15:31:22.764 NotebookApp] /home/tomek/.steampid doesn't exist
[W 15:31:22.767 NotebookApp] /home/tomek/.steampath doesn't exist

```
## System information
```
python: 3.6.1
language: pl_PL
os: Linux;4.10.0-33-generic;#37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-08-30 13:48
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-30 13:48 UTC
Labels: pkg:navigator, reso:duplicate
