### ISSUE TITLE
Spyder ipython console crash

### ISSUE THREAD

**Issue by JeremyEnns** [ContinuumIO/anaconda-issues#6557] opened 2017-10-10 20:18 UTC
## Description
Spyder ipython console crash

**What steps will reproduce the problem?**

1. conda create -n py27 python=2.7 spyder
2. launch spyder in the new environment

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

```python-traceback
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1273, in close_client
    self.create_new_client()
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 991, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1018, in connect_client_to_kernel
    stderr_file)
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1420, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_client/manager.py", line 257, in start_kernel
    **kw)
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_client/manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/jenns/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment] 2017-10-10 20:38
@mingwandroid, I think this problem can be solved in the Spyder side. But there's another one in Python 3.5 that @JeremyEnns forgot to mention:

```python-traceback
(SpyderIDE) 0471-jenns:~ jenns$ spyder
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Traceback (most recent call last):
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3093, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2995, in run_spyder
    main.setup()
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 847, in setup
    from spyder.plugins.editor import Editor
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/site-packages/spyder/plugins/editor.py", line 41, in <module>
    from spyder.utils.introspection.manager import IntrospectionManager
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/site-packages/spyder/utils/introspection/manager.py", line 21, in <module>
    from spyder.utils.introspection.plugin_client import PluginClient
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in <module>
    import zmq
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/site-packages/zmq/backend/__init__.py", line 21, in <module>
    if platform.python_implementation() == 'PyPy':
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/platform.py", line 1235, in python_implementation
    return _sys_version()[0]
  File "/Users/jenns/anaconda3/envs/SpyderIDE/lib/python3.5/platform.py", line 1193, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.4 |Anaconda, Inc.| (default, Sep 20 2017, 06:08:04) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```

and it seems like an error in patching `sys.version`, so it's related to Anaconda only.

**Comment by ccordoba12** [comment] 2017-10-11 16:36
@mingwandroid, users are also reporting hard crashes in macOS 10.12.6 and 10.13 with Python 3.6. To solve them, I think we should update Qt to 5.6.3, which was released three weeks ago.

**Comment by ccordoba12** [comment] 2017-10-13 01:01
@JeremyEnns, I addressed the problem you reported in PR spyder-ide/spyder#5457. It'll be part of Spyder **3.2.4**.

**Comment by mingwandroid** [comment] 2017-10-13 17:36
Hi @ccordoba12, I believe the crashes are due to us not rebuilding `python.app` after having rebuilt `python` for macOS. I have uploaded new `python.app` builds now and they work for me. Please help test.

**Comment by ccordoba12** [comment] 2017-10-14 20:23
@mingwandroid, what about the crash in Python 3.5?

**Comment by mingwandroid** [comment] 2017-10-14 21:24
Should also be fixed now. Did you try?

**Comment by ccordoba12** [comment] 2017-10-14 21:34
Sorry, I haven't. Should it fixed by rebuilding `python.app` too?

**Comment by mingwandroid** [comment] 2017-10-14 21:40
I'm only hoping the python.app fix fixes this too but I am not convinced!

**Comment by ccordoba12** [comment] 2017-10-18 01:28
@JeremyEnns, could you test if the new `python.app` fixes the error in Python 3.5? Thanks!

**Comment by mingwandroid** [comment] 2017-10-18 01:30
BTW, I had a good go at updating to Qt 5.6.3, and it *seems* (I have not compared carefully yet) that a lot of stuff has changed. WebEngine for example disables builds on macOS < 10.10.

**Comment by mingwandroid** [comment] 2017-10-20 15:30
I cannot reproduce `ValueError: failed to parse CPython sys.version: '3.5.4 |Anaconda, Inc.| (default, Sep 20 2017, 06:08:04) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'`

For me, an env with python 3.5 and spyder worked fine and then, within spyder the following also worked fine (I am not sure about what the return value should contain exactly, but it didn't hit any assertions):

```
import platform
print(platform._sys_version())
```

giving:

```
('CPython', '3.5.4', '', '', 'default', 'Oct  5 2017 02:58:14', 'GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)')
```

**Comment by csoja** [comment] 2019-06-07 15:29
I believe this is resolved now.

**Closed by csoja** 2019-06-07 15:29 UTC
