### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by myjz** [ContinuumIO/anaconda-issues#7398] opened 2017-11-20 14:15 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /anaconda/pkgs/free/win-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000022AEB5E3080>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))",),)

```
## System information
```
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
python: 3.5.3
platform: win-64
version: 1.6.2
pyqt: 5.6.0
qt: 5.6.2
conda: 4.3.27
language: zh_CN
```

**Comment by goanpeca** [comment] 2017-11-20 14:18
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-20 14:18 UTC
Labels: pkg:navigator, reso:duplicate
