### ISSUE TITLE
When launching after install I get this following error (on MacOS)

### ISSUE THREAD

**Issue by KirthiRaman** [ContinuumIO/anaconda-issues#326] opened 2015-05-04 16:27 UTC
Sorry, the application encountered a fatal error. Please report the following to us at
https://github.com/ContinuumIO/anaconda-issues

SyntaxError: Unexpected token <

**Comment by KirthiRaman** [comment] 2015-05-04 16:37
Hello anyone out there?

**Comment by ccordoba12** [comment] 2015-05-04 23:10
This is duplicate of issue #327.

**Closed by ccordoba12** 2015-05-04 23:10 UTC
Labels: duplicate
