### ISSUE TITLE
Navigator start-up error

### ISSUE THREAD

**Issue by puneetmidha** [ContinuumIO/anaconda-issues#9269] opened 2018-04-29 14:26 UTC
### Actual Behavior

Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/puneetmidha/Library/Application Support/binstar/config.yaml", line 1, column 1

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment] 2018-04-30 14:39
Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.14
```

**Closed by goanpeca** 2018-04-30 14:39 UTC
Labels: pkg:navigator
