### ISSUE TITLE
Navigator: This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".

### ISSUE THREAD

**Issue by Haffi112** [ContinuumIO/anaconda-issues#1182] opened 2016-10-22 13:27 UTC
When I try to run anaconda-navigator I get the following message:

This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

I have no clue how to fix this and googling hasn't helped at all. This is my first install of Anaconda.

**Comment by goanpeca** [comment] 2016-10-24 19:13
Hi @Haffi112 what version of anaconda did you install?

What operating system are you using?

Could you open the command prompt and type

`conda info` and paste the result here

and then type

`conda list` and paste the result here

Thanks

**Comment by binary-bard** [comment] 2016-10-28 14:48
I've same issue. Here are the details:
userx@linuxPC:~$ anaconda-navigator
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted
userx@linuxPC:~$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /opt/anaconda2  (read only)
    default environment : /opt/anaconda2
       envs directories : /home/userx/.conda/envs
                          /opt/anaconda2/envs
          package cache : /home/userx/.conda/envs/.pkgs
                          /opt/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

userx@linuxPC:~$ conda list
# packages in environment at /opt/anaconda2:
#
_license                  1.1                      py27_1
_nb_ext_conf              0.3.0                    py27_0
accelerate                2.3.0               np111py27_3
accelerate_cudalib        2.0                           0
alabaster                 0.7.9                    py27_0
anaconda                  custom                   py27_0
anaconda-clean            1.0.0                    py27_0
anaconda-client           1.5.1                    py27_0
anaconda-navigator        1.3.1                    py27_0
argcomplete               1.0.0                    py27_1
astroid                   1.4.7                    py27_0
astropy                   1.2.1               np111py27_0
babel                     2.3.4                    py27_0
backports                 1.0                      py27_0
backports_abc             0.4                      py27_0
beautifulsoup4            4.5.1                    py27_0
bitarray                  0.8.1                    py27_0
blaze                     0.10.1                   py27_0
bokeh                     0.12.2                   py27_0
boto                      2.42.0                   py27_0
bottleneck                1.1.0               np111py27_0
cairo                     1.12.18                       6
cdecimal                  2.3                      py27_2
cffi                      1.7.0                    py27_0
chest                     0.2.3                    py27_0
click                     6.6                      py27_0
cloudpickle               0.2.1                    py27_0
clyent                    1.2.2                    py27_0
colorama                  0.3.7                    py27_0
conda                     4.2.11                   py27_0
conda-build               2.0.2                    py27_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py27_0
configparser              3.5.0                    py27_0
contextlib2               0.5.3                    py27_0
cryptography              1.5                      py27_0
cudatoolkit               7.5                           0
curl                      7.49.0                        1
cycler                    0.10.0                   py27_0
cython                    0.24.1                   py27_0
cytoolz                   0.8.0                    py27_0
dask                      0.11.0                   py27_0
datashape                 0.5.2                    py27_0
dbus                      1.10.10                       0
decorator                 4.0.10                   py27_0
dill                      0.2.5                    py27_0
docutils                  0.12                     py27_2
dynd-python               0.7.2                    py27_0
entrypoints               0.2.2                    py27_0
enum34                    1.1.6                    py27_0
et_xmlfile                1.0.1                    py27_0
expat                     2.1.0                         0
fastcache                 1.0.2                    py27_1
filelock                  2.0.6                    py27_0
flask                     0.11.1                   py27_0
flask-cors                2.1.2                    py27_0
fontconfig                2.11.1                        6
freetype                  2.5.5                         1
funcsigs                  1.0.2                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.0.5                    py27_0
get_terminal_size         1.0.0                    py27_0
gevent                    1.1.2                    py27_0
git                       2.9.3                         0
glib                      2.43.0                        1
greenlet                  0.4.10                   py27_0
grin                      1.2.1                    py27_3
gst-plugins-base          1.8.0                         0
gstreamer                 1.8.0                         0
h5py                      2.6.0               np111py27_2
harfbuzz                  0.9.39                        1
hdf5                      1.8.17                        1
heapdict                  1.0.0                    py27_1
icu                       54.1                          0
idna                      2.1                      py27_0
imagesize                 0.7.1                    py27_0
ipaddress                 1.0.16                   py27_0
ipykernel                 4.5.0                    py27_0
ipython                   5.1.0                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                5.2.2                    py27_0
itsdangerous              0.24                     py27_0
jbig                      2.1                           0
jdcal                     1.2                      py27_1
jedi                      0.9.0                    py27_1
jinja2                    2.8                      py27_1
jpeg                      8d                            2
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.4.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.2.0                    py27_0
Keras                     1.1.0                     <pip>
lazy-object-proxy         1.2.1                    py27_0
libdynd                   0.7.2                         0
libffi                    3.2.1                         0
libgcc                    4.8.5                         2
libgfortran               3.0.0                         1
libpng                    1.6.22                        0
libsodium                 1.0.10                        0
libtiff                   4.0.6                         2
libxcb                    1.12                          0
libxml2                   2.9.2                         0
libxslt                   1.1.28                        0
llvmlite                  0.11.0                   py27_0
locket                    0.2.0                    py27_1
lxml                      3.6.4                    py27_0
markupsafe                0.23                     py27_2
matplotlib                1.5.3               np111py27_0
mistune                   0.7.3                    py27_0
mkl                       11.3.3                        0
mkl-service               1.1.2                    py27_2
mpmath                    0.19                     py27_1
multipledispatch          0.4.8                    py27_0
nb_anacondacloud          1.2.0                    py27_0
nb_conda                  2.0.0                    py27_0
nb_conda_kernels          2.0.0                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.1.0                    py27_0
nbpresent                 3.0.2                    py27_0
networkx                  1.11                     py27_0
nltk                      3.2.1                    py27_0
nose                      1.3.7                    py27_1
nose-parameterized        0.5.0                    py27_0
notebook                  4.2.3                    py27_0
numba                     0.26.0              np111py27_0
numexpr                   2.6.1               np111py27_0
numpy                     1.11.1                   py27_0
odo                       0.5.0                    py27_1
openpyxl                  2.3.2                    py27_0
openssl                   1.0.2j                        0
pandas                    0.18.1              np111py27_0
partd                     0.3.6                    py27_0
patchelf                  0.9                           0
path.py                   8.2.1                    py27_0
pathlib2                  2.1.0                    py27_0
patsy                     0.4.1                    py27_0
pep8                      1.7.0                    py27_0
pexpect                   4.0.1                    py27_0
pickleshare               0.7.4                    py27_0
pillow                    3.3.1                    py27_0
pip                       8.1.2                    py27_0
pixman                    0.32.6                        0
pkginfo                   1.3.2                    py27_0
ply                       3.9                      py27_0
prompt_toolkit            1.0.3                    py27_0
psutil                    4.3.1                    py27_0
ptyprocess                0.5.1                    py27_0
py                        1.4.31                   py27_0
pyasn1                    0.1.9                    py27_0
pycairo                   1.10.0                   py27_0
pycosat                   0.6.1                    py27_1
pycparser                 2.14                     py27_1
pycrypto                  2.6.1                    py27_4
pycurl                    7.43.0                   py27_0
pyflakes                  1.3.0                    py27_0
pygments                  2.1.3                    py27_0
pylint                    1.5.4                    py27_1
pyopenssl                 16.0.0                   py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_0
pyserial                  2.7                      py27_0
pytables                  3.2.3.1             np111py27_0
pytest                    2.9.2                    py27_0
python                    2.7.12                        1
python-dateutil           2.5.3                    py27_0
pytz                      2016.6.1                 py27_0
pyyaml                    3.12                     py27_0
pyzmq                     15.4.0                   py27_0
qt                        5.6.0                         0
qtawesome                 0.3.3                    py27_0
qtconsole                 4.2.1                    py27_1
qtpy                      1.1.2                    py27_0
readline                  6.2                           2
redis                     3.2.0                         0
redis-py                  2.10.5                   py27_0
requests                  2.11.1                   py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.14                  py27_0
scikit-image              0.12.3              np111py27_1
scikit-learn              0.17.1              np111py27_2
scipy                     0.18.1              np111py27_0
setuptools                27.2.0                   py27_0
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
snakeviz                  0.4.1                    py27_0
snowballstemmer           1.2.1                    py27_0
sockjs-tornado            1.0.3                    py27_0
sphinx                    1.4.6                    py27_0
spyder                    3.0.0                    py27_0
sqlalchemy                1.0.13                   py27_0
sqlite                    3.13.0                        0
ssl_match_hostname        3.4.0.2                  py27_1
statsmodels               0.6.1               np111py27_1
sympy                     1.0                      py27_0
terminado                 0.6                      py27_0
theano                    0.8.2                    py27_0
tk                        8.5.18                        0
toolz                     0.8.0                    py27_0
tornado                   4.4.1                    py27_0
traitlets                 4.3.0                    py27_0
unicodecsv                0.14.1                   py27_0
wcwidth                   0.1.7                    py27_0
werkzeug                  0.11.11                  py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        1.2.6                    py27_0
wrapt                     1.10.6                   py27_0
xlrd                      1.0.0                    py27_0
xlsxwriter                0.9.3                    py27_0
xlwt                      1.1.2                    py27_0
xz                        5.2.2                         0
yaml                      0.1.6                         0
zeromq                    4.1.4                         0
zlib                      1.2.8                         3

**Comment by goanpeca** [comment] 2016-10-28 14:53
@ccordoba12 thoughts?

**Comment by binary-bard** [comment] 2016-10-28 15:27
Actually I found a work-around for now reading this: http://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without (answer from TranslucentCloud)

I added a link under bin directory to ../plugins/platforms where the library exists and it is working for me now. Maybe there is a better solution but I tried changing qt.conf and it didn't help.

**Comment by karoliina** [comment] 2016-10-31 18:23
I get this error when trying to run `%pylab` or `import matplotlib.pyplot` in iPython. I'm on a fresh Anaconda 4.2.9 install on Arch Linux. Would really appreciate a workaround or a solution of any kind - I've been looking into the workaround from StackOverflow, with no success yet.

I'm thinking the issue has something to do with the fact that I currently have version 5.7 of [qt5-base](https://www.archlinux.org/packages/extra/x86_64/qt5-base/) installed, while Anaconda's qt and pyqt are on version 5.6.0.

`conda info`:
```
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/karo/anaconda3  (writable)
    default environment : /home/karo/anaconda3
       envs directories : /home/karo/anaconda3/envs
          package cache : /home/karo/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False
```

`conda list`:
```
# packages in environment at /home/karo/anaconda3:
#
_license                  1.1                      py35_1  
_nb_ext_conf              0.3.0                    py35_0  
alabaster                 0.7.9                    py35_0  
anaconda                  4.2.0               np111py35_0  
anaconda-clean            1.0.0                    py35_0  
anaconda-client           1.5.1                    py35_0  
anaconda-navigator        1.3.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astroid                   1.4.7                    py35_0  
astropy                   1.2.1               np111py35_0  
babel                     2.3.4                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.5.1                    py35_0  
bitarray                  0.8.1                    py35_0  
blaze                     0.10.1                   py35_0  
bokeh                     0.12.2                   py35_0  
boto                      2.42.0                   py35_0  
bottleneck                1.1.0               np111py35_0  
cairo                     1.12.18                       6  
cffi                      1.7.0                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.6                      py35_0  
cloudpickle               0.2.1                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.7                    py35_0  
conda                     4.2.9                    py35_0  
conda-build               2.0.2                    py35_0  
configobj                 5.0.6                    py35_0  
contextlib2               0.5.3                    py35_0  
cryptography              1.5                      py35_0  
curl                      7.49.0                        1  
cycler                    0.10.0                   py35_0  
cython                    0.24.1                   py35_0  
cytoolz                   0.8.0                    py35_0  
dask                      0.11.0                   py35_0  
datashape                 0.5.2                    py35_0  
dbus                      1.10.10                       0  
decorator                 4.0.10                   py35_0  
dill                      0.2.5                    py35_0  
docutils                  0.12                     py35_2  
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2                    py35_0  
et_xmlfile                1.0.1                    py35_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py35_1  
filelock                  2.0.6                    py35_0  
flask                     0.11.1                   py35_0  
flask-cors                2.1.2                    py35_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
get_terminal_size         1.0.0                    py35_0  
gevent                    1.1.2                    py35_0  
glib                      2.43.0                        1  
greenlet                  0.4.10                   py35_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np111py35_2  
harfbuzz                  0.9.39                        1  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py35_1  
icu                       54.1                          0  
idna                      2.1                      py35_0  
imagesize                 0.7.1                    py35_0  
ipykernel                 4.5.0                    py35_0  
ipython                   5.1.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                5.2.2                    py35_0  
itsdangerous              0.24                     py35_0  
jbig                      2.1                           0  
jdcal                     1.2                      py35_1  
jedi                      0.9.0                    py35_1  
jinja2                    2.8                      py35_1  
jpeg                      8d                            2  
jsonschema                2.5.1                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            4.4.0                    py35_0  
jupyter_console           5.0.0                    py35_0  
jupyter_core              4.2.0                    py35_0  
lazy-object-proxy         1.2.1                    py35_0  
libdynd                   0.7.2                         0  
libffi                    3.2.1                         0  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxcb                    1.12                          0  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.13.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.6.4                    py35_0  
markupsafe                0.23                     py35_2  
matplotlib                1.5.3               np111py35_0  
mistune                   0.7.3                    py35_0  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py35_2  
mpmath                    0.19                     py35_1  
multipledispatch          0.4.8                    py35_0  
nb_anacondacloud          1.2.0                    py35_0  
nb_conda                  2.0.0                    py35_0  
nb_conda_kernels          2.0.0                    py35_0  
nbconvert                 4.2.0                    py35_0  
nbformat                  4.1.0                    py35_0  
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.1                    py35_0  
nose                      1.3.7                    py35_1  
notebook                  4.2.3                    py35_0  
numba                     0.28.1              np111py35_0  
numexpr                   2.6.1               np111py35_0  
numpy                     1.11.1                   py35_0  
odo                       0.5.0                    py35_1  
openpyxl                  2.3.2                    py35_0  
openssl                   1.0.2j                        0  
pandas                    0.18.1              np111py35_0  
partd                     0.3.6                    py35_0  
patchelf                  0.9                           0  
path.py                   8.2.1                    py35_0  
pathlib2                  2.1.0                    py35_0  
patsy                     0.4.1                    py35_0  
pep8                      1.7.0                    py35_0  
pexpect                   4.0.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    3.3.1                    py35_0  
pip                       8.1.2                    py35_0  
pixman                    0.32.6                        0  
pkginfo                   1.3.2                    py35_0  
ply                       3.9                      py35_0  
prompt_toolkit            1.0.3                    py35_0  
psutil                    4.3.1                    py35_0  
ptyprocess                0.5.1                    py35_0  
py                        1.4.31                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_1  
pycparser                 2.14                     py35_1  
pycrypto                  2.6.1                    py35_4  
pycurl                    7.43.0                   py35_0  
pyflakes                  1.3.0                    py35_0  
pygments                  2.1.3                    py35_0  
pylint                    1.5.4                    py35_1  
pyopenssl                 16.0.0                   py35_0  
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_0  
pytables                  3.2.3.1             np111py35_0  
pytest                    2.9.2                    py35_0  
python                    3.5.2                         0  
python-dateutil           2.5.3                    py35_0  
pytz                      2016.6.1                 py35_0  
pyyaml                    3.12                     py35_0  
pyzmq                     15.4.0                   py35_0  
qt                        5.6.0                         0  
qtawesome                 0.3.3                    py35_0  
qtconsole                 4.2.1                    py35_1  
qtpy                      1.1.2                    py35_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py35_0  
requests                  2.11.1                   py35_0  
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.14                  py35_0  
scikit-image              0.12.3              np111py35_1  
scikit-learn              0.17.1              np111py35_2  
scipy                     0.18.1              np111py35_0  
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.4.6                    py35_0  
spyder                    3.0.0                    py35_0  
sqlalchemy                1.0.13                   py35_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py35_1  
sympy                     1.0                      py35_0  
terminado                 0.6                      py35_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py35_0  
tornado                   4.4.1                    py35_0  
traitlets                 4.3.0                    py35_0  
unicodecsv                0.14.1                   py35_0  
wcwidth                   0.1.7                    py35_0  
werkzeug                  0.11.11                  py35_0  
wheel                     0.29.0                   py35_0  
widgetsnbextension        1.2.6                    py35_0  
wrapt                     1.10.6                   py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.3                    py35_0  
xlwt                      1.1.2                    py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3  
```

**Comment by ccordoba12** [comment] 2016-10-31 20:20
Most likely this problem is caused by the lack of `libselinux`, as it was reported in spyder-ide/spyder#3383.

The solution is to install that package. For Arch Linux, please follow the instructions in this comment: https://github.com/spyder-ide/spyder/issues/3383#issuecomment-251132105

**Comment by karoliina** [comment] 2016-10-31 21:46
Unfortunately installing the `libselinux` package from AUR didn't solve the problem for me.

**Comment by binary-bard** [comment] 2016-11-02 03:57
I don't think the installation of Qt5.7 should matter since Anaconda will set the path to the installed version of Qt5.6 first. Plugin path I mentioned needs to be set for the Qt version installed within Anaconda  (Qt5.6 in your case). I had a Qt4 version installed outside of Anaconda.

**Comment by wjagers** [comment] 2016-11-18 13:22
Check whether `bin/qt.conf` in your Anaconda install directory is accessible for the account you're running as, especially when not installing in your home directory.

I just ran into the same error after an install in /opt. After some troubleshooting I noticed the permissions for `qt.conf` (750) wouldn't allow it to be read. Resolving that fixed the startup.

Posting this just in case it would apply to anyone else.

**Comment by binary-bard** [comment] 2016-11-21 06:32
I had the same permissions. I just tried to change them but it didn't help fix the issue.

userx@linuxPC:~$ anaconda-navigator
userx@linuxPC:~$ sudo chmod 755 /opt/anaconda2/bin/qt.conf
userx@linuxPC:~$ sudo rm /opt/anaconda2/bin/platforms
userx@linuxPC:~$ anaconda-navigator
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted

**Comment by goanpeca** [comment] 2016-12-27 18:41
Is there any update on this issue @ccordoba12 ?

**Comment by rgr-myrg** [comment] 2017-01-10 17:09
@wjagers Permissions problem on /opt/anaconda3/bin/qt.conf for me as well. chmod solved it.

Thanks a lot.

**Comment by goanpeca** [comment] 2017-01-10 17:15
@Haffi112,

Does doing

>Permissions problem on /opt/anaconda3/bin/qt.conf for me as well. chmod solved it.

Fixes this for you?

**Comment by atabakd** [comment] 2017-01-14 17:30
changing permission did not work for me!

**Comment by Haffi112** [comment] 2017-01-16 19:01
This solution did not work for me either.

**Comment by Haffi112** [comment] 2017-01-16 19:36
After googling for a while I stumbled upon the following solution:

    export QT_PLUGIN_PATH=<qt base path>/plugins

For me this was

    export QT_PLUGIN_PATH="/usr/lib/x86_64-linux-gnu/qt5/plugins"

**Comment by atabakd** [comment] 2017-01-17 11:51
The plugin path solved it for me too.

**Comment by goanpeca** [comment] 2017-01-17 11:58
@mingwandroid @ccordoba12

**Comment by ccordoba12** [comment] 2017-01-17 13:33
@Haffi112, that's not the right solution because it's using your system Qt plugins, which are compiled under different conditions than the Qt package provided by Anaconda. So although that makes things work for you, it could also lead to bizarre and undebugable crashes (specially for Spyder, which uses a much wider range of Qt widgets than Navigator).

Please try with

    export QT_PLUGIN_PATH=<anaconda installation dir>/plugins

and let us know if that works for you.

**Comment by Haffi112** [comment] 2017-01-17 17:46
This does not work for me :(

I tried doing (on the file in folder plugins/PyQt5)

    ldd libpyqt5qmlplugin.so 

and my output is (in case this provides any useful information)

	linux-vdso.so.1 =>  (0x00007fff12d2a000)
	libpython2.7.so.1.0 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/libpython2.7.so.1.0 (0x00007f163aeeb000)
	libQt5Gui.so.5 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/libQt5Gui.so.5 (0x00007f163a698000)
	libQt5Qml.so.5 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/libQt5Qml.so.5 (0x00007f163a032000)
	libQt5Network.so.5 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/libQt5Network.so.5 (0x00007f1639cad000)
	libQt5Core.so.5 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/libQt5Core.so.5 (0x00007f1639544000)
	libGL.so.1 => /usr/lib/nvidia-370/libGL.so.1 (0x00007f163928a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f163906d000)
	libstdc++.so.6 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/libstdc++.so.6 (0x00007f1638d56000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1638a4d000)
	libgcc_s.so.1 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/libgcc_s.so.1 (0x00007f1638837000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f163846d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1638269000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f1638066000)
	libpng16.so.16 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/./libpng16.so.16 (0x00007f1637e24000)
	libz.so.1 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/./libz.so.1 (0x00007f1637c0e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1637a05000)
	libicui18n.so.54 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/./libicui18n.so.54 (0x00007f16375a1000)
	libicuuc.so.54 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/./libicuuc.so.54 (0x00007f1637202000)
	libicudata.so.54 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/./libicudata.so.54 (0x00007f16357d8000)
	libgthread-2.0.so.0 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/./libgthread-2.0.so.0 (0x00007f16355d7000)
	libglib-2.0.so.0 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/./libglib-2.0.so.0 (0x00007f1635298000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f9eadd6000)
	libGLX.so.0 => /usr/lib/nvidia-370/libGLX.so.0 (0x00007f1635068000)
	libGLdispatch.so.0 => /usr/lib/nvidia-370/libGLdispatch.so.0 (0x00007f1634d7f000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f1634a44000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f1634832000)
	libxcb.so.1 => /home/hafsteinn/anaconda/plugins/PyQt5/./../../lib/libxcb.so.1 (0x00007f163460c000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f1634408000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f1634202000)

**Comment by egranstedt** [comment] 2017-01-27 21:41
I'm having the same issue with a fresh install of anaconda for python3 on linux (Ubuntu 16.04).

Relevant conda-info:
```
               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
```

Note that I have libselinux:
```
/lib/i386-linux-gnu/libselinux.so.1
/lib/x86_64-linux-gnu/libselinux.so.1
```

Also qt.conf is readable.

I was not able to resolve by setting:
`QT_PLUGIN_PATH=<anaconda installation dir>/plugins`

Setting it to the system-level QT plugins directory allows anaconda-navigator to run, but as @ccordoba12 indicates, this is not a true solution.

**Comment by goanpeca** [comment] 2017-02-01 14:46
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

---


This should be fixed by the latest version, please reopen if this is not the case.

**Closed by goanpeca** 2017-02-01 14:46 UTC
Labels: pending:feedback, tag:navigator

**Comment by jlgabriel** [comment] 2017-02-02 03:37
Hi, the same happened to me with the new Anaconda 4.3 Windows 64bit installer, when I installed in the default suggested path (under C:\Users\...).

After I uninstalled it and re-installed it in a folder in root (C:\Anaconda), the error disappeared and now I can use Spyder and others.

I hope it helps! best regards, Juan

**Comment by mingwandroid** [comment] 2017-02-02 08:32
@jlgabriel, what was the exact path under `C:\Users`?

**Comment by jlgabriel** [comment] 2017-02-02 10:40
Hi, I initially selected the option to install Anaconda just for my user and the path was: 

C:\Users\juanl\Anaconda3

After installing it in C:\Anaconda (and for all users? I don't remember...) this problem was solved.

**Comment by jdhao** [comment] 2017-02-12 13:35
For me, the root cause is that `/usr/lib64` was added to LD_LIBRARY_PATH in the system /etc/profile. As a result, when importing matplotlib, it is looking for xcb package in /usr/lib64 instead of under the directory where Anaconda is installed. Hence an error.  The solution is to remove `/usr/lib64` from system LD_LIBRARY_PATH, or you can explicitly add the libxcb path under the Anaconda directory to LD_LIBRARY_PATH in your own .bash_profile. That should resolve this issue. For more info, see https://github.com/ContinuumIO/anaconda-issues/issues/1249

**Comment by mingwandroid** [comment] 2017-02-12 15:31
@jdhao, is this on centos7? Do you know if a default installation of your OS does this? I really hope not!

**Comment by jdhao** [comment] 2017-02-12 16:02
@mingwandroid, yes, it is on CentOS 7. The `/usr/lib64` dir was added by the server manager, not by default.

**Comment by mingwandroid** [comment] 2017-02-12 16:06
Is the 'server manager' a person or a program/package?

**Comment by jdhao** [comment] 2017-02-12 16:09
@mingwandroid, it is a person.

**Comment by mingwandroid** [comment] 2017-02-12 16:43
OK I'll send a link later when I am in front of a computer making the case that LD_LIBRARY_PATH should not be used except by users in very specific situations.

If you google "LD_LIBRARY_PATH considered harmful" you should be able to find it.

**Comment by ccordoba12** [comment] 2017-02-13 00:00
As Wes McKinney said: "*Hell is other's people LD_LIBRARY_PATH*" ;-)

**Comment by mingwandroid** [comment] 2017-02-13 00:09
Indeed. https://gms.tf/ld_library_path-considered-harmful.html

**Comment by mingwugmail** [comment] 2017-05-10 18:12
http://stackoverflow.com/questions/33051790/anaconda-python-could-not-find-or-load-the-qt-platform-plugin-xcb

The issue stemmed from anaconda having Qt version 5.6 installed, while my system Qt libraries were at version 5.5.

A quick hack is to make sure Anaconda libraries precede your system libraries by setting LD_LIBRARY_PATH:

export LD_LIBRARY_PATH=$HOME/anaconda2/lib:$LD_LIBRARY_PATH
Unfortunately, this will break other programs that use Qt 5.5, so you can only use it in situations that are 100% anaconda python,

**Comment by joddlehod** [comment] 2017-05-23 17:30
@mingwugmail Thanks!  After trying everything else on this thread, yours is the only solution that worked for me.

I originally had anaconda python working fine, but then after installing openfoam I could no longer load matplotlib.pyplot.  After exporting LD_LIBRARY_PATH=$HOME/anaconda3/lib:$LD_LIBRARY_PATH I can now use matplotlib.pyplot, but not openfoam.  Suggestions on how I can make both coexist peacefully?  I am trying to automate openfoam using python.

**Comment by mingwugmail** [comment] 2017-05-26 23:43
don't set LD_LIBRARY_PATH system wide.

for your 2 task commands, set it separately:

$ LD_LIBRARY_PATH=$HOME/anaconda2/lib:$LD_LIBRARY_PATH  cmd_that_call_matplotlib
$ LD_LIBRARY_PATH=(make_it_sure_Qt_5.5_is_there_first) cmd_that_call_openfoam

**Comment by imkane** [comment] 2017-09-13 23:33
I'm having this same issue and can't see a valid solution mentioned :(

**Comment by gitliubao** [comment] 2025-01-24 05:33
使用 example.pyx   和 setup.py 实现 python 调用 C 和 C++ 代码的示例代码
