### ISSUE TITLE
Navigator Error on macOS High Sierra 10.13.3

### ISSUE THREAD

**Issue by mlbch** [ContinuumIO/anaconda-issues#8769] opened 2018-03-05 16:14 UTC
### Actual Behavior
```
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/marcbuchner/Library/Application Support/binstar/config.yaml", line 1, column 1
Traceback
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/Applications/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/Applications/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/Applications/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Applications/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Applications/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/Applications/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/Applications/anaconda3/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/Applications/anaconda3/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/marcbuchner/Library/Application Support/binstar/config.yaml", line 1, column 1
```
##### Anaconda or Miniconda version:
Anaconda3 5.1.0

##### Operating System:
macOS High Sierra 10.13.3

##### `conda info`

```
Current conda install:

               platform : osx-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : /Users/marcbuchner/anaconda  (writable)
    default environment : /Users/marcbuchner/anaconda
       envs directories : /Users/marcbuchner/anaconda/envs
                          /Users/marcbuchner/.conda/envs
          package cache : /Users/marcbuchner/anaconda/pkgs
                          /Users/marcbuchner/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/marcbuchner/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.34 requests/2.13.0 CPython/3.5.2 Darwin/17.4.0 OSX/10.13.3    
                UID:GID : 501:20

```

##### `conda list --show-channel-urls`

```
# packages in environment at /Users/marcbuchner/anaconda:
#
_nb_ext_conf              0.2.0                    py35_0    defaults
alabaster                 0.7.8                    py35_0    defaults
anaconda                  custom                   py35_0    defaults
anaconda-client           1.4.0                    py35_0    defaults
anaconda-navigator        1.2.1                    py35_0    defaults
appnope                   0.1.0                    py35_0    defaults
appscript                 1.0.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astropy                   1.2.1               np111py35_0    defaults
babel                     2.3.3                    py35_0    defaults
backports                 1.0                      py35_0    defaults
beautifulsoup4            4.4.1                    py35_0    defaults
bitarray                  0.8.1                    py35_0    defaults
blaze                     0.10.1                   py35_0    defaults
bokeh                     0.12.0                   py35_0    defaults
boto                      2.40.0                   py35_0    defaults
bottleneck                1.1.0               np111py35_0    defaults
cffi                      1.6.0                    py35_0    defaults
chest                     0.2.3                    py35_0    defaults
click                     6.6                      py35_0    defaults
cloudpickle               0.2.1                    py35_0    defaults
clyent                    1.2.2                    py35_0    defaults
colorama                  0.3.7                    py35_0    defaults
conda                     4.3.34                   py35_0    conda-forge
conda-build               1.21.3                   py35_0    defaults
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py35_0    defaults
contextlib2               0.5.3                    py35_0    defaults
cryptography              1.4                      py35_0    defaults
curl                      7.49.0                        0    defaults
cycler                    0.10.0                   py35_0    defaults
cython                    0.24                     py35_0    defaults
cytoolz                   0.8.0                    py35_0    defaults
dask                      0.10.0                   py35_0    defaults
datashape                 0.5.2                    py35_0    defaults
decorator                 4.0.10                   py35_0    defaults
dill                      0.2.5                    py35_0    defaults
docutils                  0.12                     py35_2    defaults
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.2                    py35_0    defaults
et_xmlfile                1.0.1                    py35_0    defaults
fastcache                 1.0.2                    py35_1    defaults
flask                     0.11.1                   py35_0    defaults
flask-cors                2.1.2                    py35_0    defaults
freetype                  2.5.5                         1    defaults
get_terminal_size         1.0.0                    py35_0    defaults
gevent                    1.1.1                    py35_0    defaults
greenlet                  0.4.10                   py35_0    defaults
h5py                      2.6.0               np111py35_1    defaults
hdf5                      1.8.16                        0    defaults
heapdict                  1.0.0                    py35_1    defaults
idna                      2.1                      py35_0    defaults
imagesize                 0.7.1                    py35_0    defaults
ipykernel                 4.3.1                    py35_0    defaults
ipython                   4.2.0                    py35_1    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                4.1.1                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py35_1    defaults
jedi                      0.9.0                    py35_1    defaults
jinja2                    2.8                      py35_1    defaults
jpeg                      8d                            1    defaults
jsonschema                2.5.1                    py35_0    defaults
jupyter                   1.0.0                    py35_3    defaults
jupyter_client            4.3.0                    py35_0    defaults
jupyter_console           4.1.1                    py35_0    defaults
jupyter_core              4.1.0                    py35_0    defaults
libdynd                   0.7.2                         0    defaults
libpng                    1.6.22                        0    defaults
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
llvmlite                  0.11.0                   py35_0    defaults
locket                    0.2.0                    py35_1    defaults
lxml                      3.6.0                    py35_0    defaults
markupsafe                0.23                     py35_2    defaults
matplotlib                1.5.1               np111py35_0    defaults
mistune                   0.7.2                    py35_1    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py35_2    defaults
mpmath                    0.19                     py35_1    defaults
multipledispatch          0.4.8                    py35_0    defaults
nb_anacondacloud          1.1.0                    py35_0    defaults
nb_conda                  1.1.0                    py35_0    defaults
nb_conda_kernels          1.0.3                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbformat                  4.0.1                    py35_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
networkx                  1.11                     py35_0    defaults
nltk                      3.2.1                    py35_0    defaults
nose                      1.3.7                    py35_1    defaults
notebook                  4.2.1                    py35_0    defaults
numba                     0.26.0              np111py35_0    defaults
numexpr                   2.6.0               np111py35_0    defaults
numpy                     1.11.1                   py35_0    defaults
odo                       0.5.0                    py35_1    defaults
openpyxl                  2.3.2                    py35_0    defaults
openssl                   1.0.2h                        1    defaults
pandas                    0.18.1              np111py35_0    defaults
partd                     0.3.4                    py35_0    defaults
path.py                   8.2.1                    py35_0    defaults
pathlib2                  2.1.0                    py35_0    defaults
patsy                     0.4.1                    py35_0    defaults
pep8                      1.7.0                    py35_0    defaults
pexpect                   4.0.1                    py35_0    defaults
pickleshare               0.7.2                    py35_0    defaults
pillow                    3.2.0                    py35_1    defaults
pip                       8.1.2                    py35_0    defaults
ply                       3.8                      py35_0    defaults
psutil                    4.3.0                    py35_0    defaults
ptyprocess                0.5.1                    py35_0    defaults
py                        1.4.31                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.14                     py35_1    defaults
pycrypto                  2.6.1                    py35_4    defaults
pycurl                    7.43.0                   py35_0    defaults
pyflakes                  1.2.3                    py35_0    defaults
pygments                  2.1.3                    py35_0    defaults
pyopenssl                 16.2.0                   py35_0    conda-forge
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      4.11.4                   py35_3    defaults
pytables                  3.2.2               np111py35_4    defaults
pytest                    2.9.2                    py35_0    defaults
python                    3.5.2                         0    defaults
python-dateutil           2.5.3                    py35_0    defaults
python.app                1.2                      py35_4    defaults
pytz                      2016.4                   py35_0    defaults
pyyaml                    3.11                     py35_4    defaults
pyzmq                     15.2.0                   py35_1    defaults
qt                        4.8.7                         3    defaults
qtconsole                 4.2.1                    py35_0    defaults
qtpy                      1.0.2                    py35_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py35_0    defaults
requests                  2.13.0                   py35_0    conda-forge
rope                      0.9.4                    py35_1    defaults
ruamel_yaml               0.15.35                  py35_0    conda-forge
scikit-image              0.12.3              np111py35_1    defaults
scikit-learn              0.17.1              np111py35_2    defaults
scipy                     0.17.1              np111py35_1    defaults
setuptools                23.0.0                   py35_0    defaults
simplegeneric             0.8.1                    py35_1    defaults
singledispatch            3.4.0.3                  py35_0    defaults
sip                       4.16.9                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.4.1                    py35_0    defaults
sphinx_rtd_theme          0.1.9                    py35_0    defaults
spyder                    2.3.9                    py35_0    defaults
sqlalchemy                1.0.13                   py35_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.6.1               np111py35_1    defaults
sympy                     1.0                      py35_0    defaults
terminado                 0.6                      py35_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py35_0    defaults
tornado                   4.3                      py35_1    defaults
traitlets                 4.2.1                    py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
werkzeug                  0.11.10                  py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.2                    py35_0    defaults
xlwings                   0.7.2                    py35_0    defaults
xlwt                      1.1.2                    py35_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         3    defaults
```

**Comment by goanpeca** [comment] 2018-03-05 16:19
Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.11
```

**Closed by goanpeca** 2018-03-05 16:19 UTC
