### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by LLiswatching** [ContinuumIO/anaconda-issues#3931] opened 2017-08-05 05:38 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=1284)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\sshss\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\sshss\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sshss\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\sshss\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\sshss\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\sshss\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\sshss\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=1284)

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0

**Comment by goanpeca** [comment] 2017-08-05 05:38
**See Issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-05 05:38 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by LLiswatching** [comment] 2017-08-05 05:52
Thanks very much!
            On 08/05/2017 13:56, Gonzalo Peña-Castellanos wrote: See Issue #1984 for more information on how to fix this.

Closing as duplicate of #1984

Please remember to update to the latest version of Navigator to include
the latest fixes.
Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:
$ conda update anaconda-navigator


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ContinuumIO/anaconda-issues","title":"ContinuumIO/anaconda-issues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ContinuumIO/anaconda-issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@goanpeca in #3931: **See Issue #1984 for more information on how to fix this.**\n\n---\n\nClosing as duplicate of #1984\n\n\n---\n\nPlease remember to update to the latest version of Navigator to include\nthe latest fixes.\n\nOpen a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)\nand type:\n\n```\n$ conda update anaconda-navigator\n```\n"}],"action":{"name":"View Issue","url":"https://github.com/ContinuumIO/anaconda-issues/issues/3931#issuecomment-320414168"}}}
