### ISSUE TITLE
Anaconda: Navigator Error

### ISSUE THREAD

**Issue by kkaoru1981** [ContinuumIO/anaconda-issues#7972] opened 2018-01-01 12:16 UTC
I installed Anaconda 5.0.1 on Windows 10.
Starting up Anaconda Navigator, an error below occured.

I tried conda update anaconda-navigator on cmd.
But it resulted in same error again with the latest version.

Does anyone have a solution?

======================================================

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

list indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 161, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1269, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Users\kitamura\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: list indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2018-01-02 16:43
Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See issue #1837 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-01-02 16:43 UTC
