### ISSUE TITLE
libhdf5 import error

### ISSUE THREAD

**Issue by jhamman** [ContinuumIO/anaconda-issues#399] opened 2015-08-04 16:28 UTC
I'm getting this error trying to import the `netCDF4` package:
```
(rasm)$ ipython
Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

```python
In [1]: import netCDF4
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f731da2de255> in <module>()
----> 1 import netCDF4

/home/jhamman/anaconda/envs/rasm/lib/python3.4/site-packages/netCDF4/__init__.py in <module>()
      1 # init for netCDF4 package
      2 # Docstring comes from extension module _netCDF4
----> 3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
      5 from ._netCDF4 import __doc__

ImportError: libhdf5_hl.so.9: cannot open shared object file: No such file or directory
```
Details about my install are below:

```
(rasm)$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.15.1
  conda-build version : 1.13.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /usr/local/anaconda  (read only)
  default environment : /home/jhamman/anaconda/envs/rasm
     envs directories : /home/jhamman/anaconda/envs
                        /usr/local/anaconda/envs
        package cache : /home/jhamman/anaconda/envs/.pkgs
                        /usr/local/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

```
(rasm)$ ipython
Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

```python
In [1]: import netCDF4
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f731da2de255> in <module>()
----> 1 import netCDF4

/home/jhamman/anaconda/envs/rasm/lib/python3.4/site-packages/netCDF4/__init__.py in <module>()
      1 # init for netCDF4 package
      2 # Docstring comes from extension module _netCDF4
----> 3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
      5 from ._netCDF4 import __doc__

ImportError: libhdf5_hl.so.9: cannot open shared object file: No such file or directory

(rasm)$ conda list
# packages in environment at /home/jhamman/anaconda/envs/rasm:
#
basemap                   1.0.7                np19py34_0  
binstar                   0.11.0                   py34_0  
bottleneck                1.0.0                np19py34_0  
certifi                   14.05.14                 py34_0  
chest                     0.2.3                    py34_0  
clyent                    0.3.4                    py34_0  
curl                      7.38.0                        0  
cyordereddict             0.2.2                     <pip>
cython                    0.22                     py34_0  
dask                      0.6.1                np19py34_0  
dill                      0.2.3                    py34_0  
fontconfig                2.11.1                        4  
freetype                  2.5.2                         2  
gdal                      1.11.2               np19py34_2  
geos                      3.3.3                         0  
h5netcdf                  0.2.1                     <pip>
h5py                      2.5.0                np19py34_3  
hdf4                      4.2.11                        0  
hdf5                      1.8.15.1                      1  
heapdict                  1.0.0                    py34_0  
ipython                   3.2.1                    py34_0  
ipython-notebook          3.2.1                    py34_0  
jinja2                    2.8                      py34_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py34_0  
libgdal                   1.11.2                        0  
libnetcdf                 4.3.2                         1  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
locket                    0.2.0                    py34_0  
markupsafe                0.23                     py34_0  
matplotlib                1.4.3                np19py34_2  
mistune                   0.7                      py34_0  
netcdf4                   1.1.8                np19py34_0  
nose                      1.3.7                    py34_0  
numpy                     1.9.2                    py34_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py34_0  
partd                     0.3.2                np19py34_0  
patsy                     0.3.0                np19py34_0  
pillow                    2.8.1                    py34_2  
pip                       7.1.0                    py34_0  
proj4                     4.8.0                         0  
psutil                    2.2.1                    py34_0  
ptyprocess                0.4                      py34_0  
pygments                  2.0.2                    py34_0  
pyhdf                     0.9                  np19py34_0  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.11.3                   py34_1  
python                    3.4.3                         1  
python-dateutil           2.4.2                    py34_0  
python-hdf4               0.9                  np19py34_0  
pytz                      2015.4                   py34_0  
pyyaml                    3.11                     py34_1  
pyzmq                     14.7.0                   py34_0  
qt                        4.8.6                         3  
readline                  6.2                           2  
requests                  2.7.0                    py34_0  
scipy                     0.16.0               np19py34_0  
seaborn                   0.6.0                np19py34_0  
setuptools                18.0.1                   py34_0  
sip                       4.16.5                   py34_0  
six                       1.9.0                    py34_0  
sqlite                    3.8.4.1                       1  
statsmodels               0.6.1                np19py34_0  
system                    5.8                           2  
terminado                 0.5                      py34_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py34_0  
tornado                   4.2.1                    py34_0  
tzwhere                   1.0                       <pip>
xlrd                      0.9.3                    py34_0  
xray                      0.5.2                np19py34_0  
xz                        5.0.5                         0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by heistermann** [comment] 2015-08-17 14:34
I have a similar problem in a Wakari environment (np18py27-1.9). Trying to

`>>> import netCDF4`

gives:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f731da2de255> in <module>()
----> 1 import netCDF4

ImportError: libhdf5_hl.so.7: cannot open shared object file: No such file or directory
```

**Comment by Tony-RJ** [comment] 2015-08-19 16:41
Similar problem, when trying to use netCDF4 whithin ipython
=======================================================0
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) 
IPython 3.2.0 -- An enhanced Interactive Python.
________________________________________________________________________________
In [2]: import netCDF4
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f731da2de255> in <module>()
----> 1 import netCDF4

~/anaconda/lib/python2.7/site-packages/netCDF4/__init__.py in <module>()
      1 # init for netCDF4. package
      2 # Docstring comes from extension module _netCDF4.
----> 3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
      5 from ._netCDF4 import __doc__, __pdoc__

ImportError: ~/anaconda/lib/python2.7/site-packages/netCDF4/../../.././libk5crypto.so.3: symbol k5_set_error, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference

In [3]: 
                
____________________________________________________________________

**Comment by mias50** [comment] 2015-09-16 21:56
I have the exact  same problem. has any one contacted Continum Analytics?

miniconda3 64 bit:

"# ipython
Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python."


Relevant packages and libraries in miniconda3 environment:
cython                    0.23.2                   py34_0
h5py                      2.5.0                np19py34_3  
hdf5                      1.8.15.1                      1
libnetcdf                 4.3.3.1                       1 
krb5                      1.13.2                        0 
netcdf4                   1.1.9                np19py34_0

Running on  puppy linix quirky build April 7.03:
http://bkhome.org/news/?viewDetailed=00187

error:

--
ImportError                               Traceback (most recent call last)
<ipython-input-1-f731da2de255> in <module>()
----> 1 import netCDF4

/root/miniconda3/lib/python3.4/site-packages/netCDF4/__init__.py in <module>()
      1 # init for netCDF4. package
      2 # Docstring comes from extension module _netCDF4.
----> 3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
      5 from ._netCDF4 import __doc__, __pdoc__

ImportError: libkeyutils.so.1: cannot open shared object file: No such file or directory



Anybody come across a solution?

**Comment by mias50** [comment] 2015-09-16 22:03
Also I changed my path variable to look into many directories (over kill here):

# echo $PATH
/root/miniconda3/bin:/usr:/usr/lib:/root/miniconda3/lib:/root/miniconda3/pkgs:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/X11R7/bin:/root/my-applications/bin:/usr/games
#

**Comment by groutr** [comment] 2015-09-17 16:18
I can investigate this either today or tomorrow.  Thanks for submitting the issue.

**Comment by groutr** [comment] 2015-09-17 20:01
I cannot reproduce this issue.  Using netCDF4 1.1.9
```
# packages in environment at .../miniconda/envs/n3test:
#
curl                      7.43.0                        1
decorator                 4.0.2                    py34_0
hdf5                      1.8.15.1                      1
ipython                   4.0.0                    py34_0
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py34_0
krb5                      1.13.2                        0
libgfortran               1.0                           0
libnetcdf                 4.3.3.1                       1
netcdf4                   1.1.9                np19py34_0
numpy                     1.9.2                    py34_1
openblas                  0.2.14                        1
openssl                   1.0.1k                        1
path.py                   7.6.1                    py34_0
pexpect                   3.3                      py34_0
pickleshare               0.5                      py34_0
pip                       7.1.2                    py34_0
python                    3.4.3                         1
readline                  6.2                           2
setuptools                18.1                     py34_0
simplegeneric             0.8.1                    py34_0
sqlite                    3.8.4.1                       1
system                    5.8                           2
tk                        8.5.18                        0
traitlets                 4.0.0                    py34_0
wheel                     0.24.0                   py34_0
xz                        5.0.5                         0
zlib                      1.2.8                         0
```

**Comment by jhamman** [comment] 2015-09-18 15:40
For the record, wiping my environment and starting over fixed my original issue here.  So it may be related to the order in which the packages are installed or linked.  Since I was eventually able to get this to work, I'm not surprised you're having trouble reproducing the problem.

**Comment by groutr** [comment] 2015-09-24 16:29
We'll close this for now.  If it happens again, please let us know.

**Closed by groutr** 2015-09-24 16:29 UTC
Labels: needs info
