### ISSUE TITLE
Anaconda Navigator error "byte indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by psvnmahesh** [ContinuumIO/anaconda-issues#7409] opened 2017-11-21 05:10 UTC
After installation of Anaconda, I can only see the error by opening Anaconda Navigator as "byte indices must be integers or slices, not str".

Could anyone please help me on this.

**Comment by goanpeca** [comment] 2017-11-21 05:12
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-21 05:12 UTC

**Comment by goanpeca** [comment] 2017-11-21 05:14
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```
