### ISSUE TITLE
Spyder: cannot connect to IPython kernel

### ISSUE THREAD

**Issue by sshaky2** [ContinuumIO/anaconda-issues#341] opened 2015-05-28 06:52 UTC
I am new to python. I installed the most recent version of anaconda 64 bit. When I start spyder it says connecting to ipython kernel and it could not connect.

**Comment by ccordoba12** [comment] 2015-05-28 13:54
A couple of questions:

1. Which platform are you working on? Windows, Linux or Mac?
2. What Python version are you using?
3. What is your Spyder version?

**Comment by sshaky2** [comment] 2015-05-28 15:18
I am using win 8.1, python 2.7. I am using spyder which comes with anaconda package.

**Comment by ccordoba12** [comment] 2015-05-28 16:56
Ok, please run in a terminal (i.e. cmd.exe)

    conda update pyzmq

and try again. That should fix your problem :-)

**Comment by ccordoba12** [comment] 2015-06-04 07:18
@sshaky2, any updates?

**Comment by sshaky2** [comment] 2015-06-04 12:51
Hi Carlos,

Sorry haven't worked on it lately. I have been travelling for last few
days. So I haven't got time to work on it. Will let you know once I try as
you said.

Thank you

**Comment by ccordoba12** [comment] 2015-06-05 00:14
Ok, thanks for the update :-)

**Comment by plasmon80** [comment] 2015-11-10 16:28
Hi, I have been desperately searching for a solution for the same problem.

I have Windows 7 and have installed, uninstalled and reinstalled Anaconda2-2.4.0-Windows-x86_64; Spyder (Python 2.7) multiple times, but it always says 'connecting to kernel' when I open it and it never connects.  

I tried 'conda update pyzmq' and it says 'All requested packages already installed'. 

I previously had Pyscripter and PyCharm, but unistalled them.

It is still not connecting to kernel, it keeps freezing, could you please help?

**Comment by ccordoba12** [comment] 2015-11-10 20:30
It could also be a problem with your firewall and/or antivirus.

Please try to deactivate them and see if that fixes the issue for you.

**Comment by plasmon80** [comment] 2015-11-10 20:33
Thanks for the response, the firewall is not activated, the computer is on my company network. Spyder used to work on the same computer, then it just kept giving the 'connecting to kernel' warning everytime I opened it.

**Comment by ccordoba12** [comment] 2015-11-11 13:55
Then that's probably caused by the move to IPython/Jupyter 4.0. What 
happens if you reinstall Anaconda 2.3?

**Comment by plasmon80** [comment] 2015-11-12 08:43
Thanks, I will try to uninstall version 2.4 and install version 2.3.

**Comment by matthiaskoenig** [comment] 2015-11-18 14:44
I have the same issue on Ubuntu 14.04 LTS
Connecting to kernel is just rotating, but never connecting.
* Spyder 2.3.7
* Python 2.7.6
* IPython 4.0.0
I do not use anaconda, but installed the dependencies via pip.

**Comment by beew** [comment] 2015-11-29 00:34
I have experienced the same issue on Ubuntu 15.10 64 bit.
Updated to 2.3.8 fixed it.

**Comment by ccordoba12** [comment] 2015-11-29 15:44
Yes, the problem was generated by the update to Matplotlib 1.5, but only 
on Python 2 and Linux.

New conda packages for 2.3.8 will be available in a couple of days :-)

**Comment by sherlockzoom** [comment] 2016-04-11 02:11
I sovled this problem on Ubuntu 15.10 64 bit by reset my spdyer.

`$ spyder --reset`

**Comment by kjoth** [comment] 2017-01-26 13:29
I installed in Win 10 64 bit. But the spyder keeps informing that "Connecting to Kernel" for ipyhton. Any solution tothis?

**Comment by goanpeca** [comment] 2017-05-17 04:51
@ccordoba12 ?

**Comment by ccordoba12** [comment] 2017-05-17 16:03
This was an error in Spyder 2.3. It should be fixed now in Spyder 3.1.4, so please update to that version.

**Closed by ccordoba12** 2017-05-17 16:03 UTC
Labels: pending:feedback, pkg:spyder

**Comment by javierrenton** [comment] 2018-05-03 16:15
I confirm that the solution given some posts above does work for Python 2.7, Spyder 3.2.8 in Windows 10, 64-bit version:

 conda update pyzmq

**Comment by mrwu0814** [comment] 2018-06-11 02:07
I had the same problem,
and I tried the "conda update pyzmq" @ccordoba12  said,
And it saved my day! It works fine now. Thank you.

**Comment by sergiosd** [comment] 2018-06-23 07:44
Same problem, Spyder  3.2.8
"conda update pyzmq" didn't work (package already installed)
... but @sherlockzoom solution did it:
"spyder --reset" in Windows 8.1

The only "strange" thing I did was to change the default working directory from "current directory" to a specific directory I selected in preferences menu ( I can't tell exact words of menu in English since I work in a Spanish version), resetting spyder looks like that was the solution...

**Comment by jamessong** [comment] 2018-11-20 04:05
so surprised the problem still exists even with the newest anaconda ... junk product i have to say

**Comment by BiswajeetPramanik** [comment] 2019-02-16 17:53
how to connect to a ipython kernel which i have made in an conda environment(for tensorflow-gpu)

**Comment by ccordoba12** [comment] 2019-02-17 11:59
@BiswajeetPramanik, please read our guide:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
