### ISSUE TITLE
Navigator Error when launching Jupyterlab

### ISSUE THREAD

**Issue by iburnaga** [ContinuumIO/anaconda-issues#10155] opened 2018-10-05 00:47 UTC
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\iburn\Anaconda3\Scripts\jupyter-lab-script.py", line 6, in <module>
    from jupyterlab.labapp import main
  File "C:\Users\iburn\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "C:\Users\iburn\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\iburn\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.6.6
language: en_US
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.8
```

**Comment by goanpeca** [comment] 2018-10-08 18:05
Closing as duplicate of #8216

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

**Closed by goanpeca** 2018-10-08 18:05 UTC

**Comment by omolaid** [comment] 2019-04-30 08:48
Good day, can somone help me? I tried launching jupyterlab and I'm getting this error:



Application jupyterlab launch may have produced errors


Traceback (most recent call last):
File "/Applications/anaconda3/bin/jupyter-lab", line 7, in 
from jupyterlab.labapp import main
File "/Applications/anaconda3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 7, in 
from notebook.notebookapp import NotebookApp, aliases, flags
File "/Applications/anaconda3/lib/python3.6/site-packages/notebook/__init__.py", line 25, in 
from .nbextensions import install_nbextension
File "/Applications/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 28, in 
from ipython_genutils.py3compat import string_types, cast_unicode_py2
File "/Applications/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 145, in 
import platform
File "/Applications/anaconda3/lib/python3.6/platform.py", line 116, in 
import sys, os, re, subprocess
File "/Applications/anaconda3/lib/python3.6/subprocess.py", line 136, in 
import _posixsubprocess
ImportError: dlopen(/Applications/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
Referenced from: /Applications/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
Expected in: flat namespace
in /Applications/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so



Any idea how to go about it?
