### ISSUE TITLE
Jupyter fails on launch from Anaconda Navigator from Windows 7 Enterprise

### ISSUE THREAD

**Issue by MichaelTuchman** [ContinuumIO/anaconda-issues#1027] opened 2016-08-30 19:37 UTC
I am following the tutorial "biopy" and tried to launch my environment via Jupyter notebook, but all I get is a blank browser window opened to http://localhost:8890/tree.

Something was not set up correctly.

**Comment by kerrywatson1** [comment] 2016-09-08 18:26
QA team tested and reported that they could not reproduce this issue. Report below. Closing.
=====
The testing has been completed for this tutorial on Windows7 (32/64-bit) for Anaconda2 and Anaconda3. We were unable to reproduce the issue mentioned in this ticket: https://github.com/ContinuumIO/anaconda-issues/issues/1027 

Jupyter launches successfully from any port i.e.
http://localhost:8888/tree
http://localhost:8889/tree
http://localhost:8890/tree

**Closed by kerrywatson1** 2016-09-08 18:26 UTC
Labels: Navigator

**Comment by kerrywatson1** [comment] 2016-09-08 18:27
@csoja

**Comment by MichaelTuchman** [comment] 2016-09-08 18:34
You closed this ticket without any speculation on what might be the difference between a successful launch and an unsuccessful launch.   I'm not insane or lying, so something is still not happening as it is supposed to.   What I hear you saying is that I'm **supposed to see** http;//localhost:8888/tree in my browser bar.   That is indeed occurring.  But the remainder of the screen is blank, pointing perhaps to a configuration issue.

**Comment by kerrywatson1** [comment] 2016-09-08 18:40
Michael, I'm sorry, it just means our QA team could not reproduce your
issue.You may need to reboot or reinstall. Have you tried our email group
https://groups.google.com/a/continuum.io/forum/#!forum/anaconda? I'm sorry
I couldn't be more helpful to you.

_______________________________

Kerry Watson
Documentation manager

[image: Continuum Analytics] <http://continuum.io>

**Comment by MichaelTuchman** [comment] 2016-09-08 20:17
OK, I sort of figured it out.  My default browser was locked by my administrator and I don't think Javascript is running on that browser.  However, when I open a Chrome browser (which I can modify) with the server still running and point it to **localhost:8888/tree**,  I _can_ see the **Jupyter** interface. 

So, the TL;DR: is "it is running correctly  but I couldn't see it".

Perhaps knowing this might help you respond to related issues.

**Comment by Larz60p** [comment] 2018-05-01 01:41
I am running windows 7 (professional version).
I also get an error while starting Jupyter Notebook from Anaconda Navigator, except Jupyter still lanuches:

Here is the content of the error message:
----------------------------------------------------------------------------------------

[I 21:38:10.616 NotebookApp] The port 8888 is already in use, trying another port.
[I 21:38:10.616 NotebookApp] The port 8889 is already in use, trying another port.
[I 21:38:10.617 NotebookApp] The port 8890 is already in use, trying another port.
[W 21:38:10.635 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
Traceback (most recent call last):
File "C:\Anaconda3_5.1.0\lib\site-packages\notebook\notebookapp.py", line 1451, in init_server_extensions
mod = importlib.import_module(modulename)
File "C:\Anaconda3_5.1.0\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 21:38:10.657 NotebookApp] JupyterLab beta preview extension loaded from C:\Anaconda3_5.1.0\lib\site-packages\jupyterlab
[I 21:38:10.657 NotebookApp] JupyterLab application directory is C:\Anaconda3_5.1.0\share\jupyter\lab
[I 21:38:11.719 NotebookApp] Serving notebooks from local directory: C:\Users\...
[I 21:38:11.719 NotebookApp] 0 active kernels
[I 21:38:11.719 NotebookApp] The Jupyter Notebook is running at:
[I 21:38:11.719 NotebookApp] http://localhost:8891/?token=...
[I 21:38:11.719 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:38:11.720 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8891/?token= ...
[I 21:38:11.871 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 21:38:12.249 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20180430213810 (::1) 9.00ms referer=http://localhost:8891/tree
