### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by venkatjilla** [ContinuumIO/anaconda-issues#1863] opened 2017-06-02 05:36 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>string indices must be integers, not str
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\PADMA\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4

**Comment by nehaljwani** [comment] 2017-06-03 12:13
Closing as duplicate of #1837

**Comment by goanpeca** [comment] 2017-06-03 17:12
@venkatjilla it seems conda is not set correctly on path.

**Comment by goanpeca** [comment] 2017-07-11 23:55
Closing as duplicate of #1837 

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-11 23:55 UTC
Labels: os:windows, pkg:navigator
