### ISSUE TITLE
Unable to install anaonda

### ISSUE THREAD

**Issue by nevadarain** [ContinuumIO/anaconda-issues#3967] opened 2017-08-06 19:03 UTC
I cant install anaconda because my filepath in home directory has a space and i cant rename folder.  When i do install it , and i double click icon i get an error message.  When i run the acaconda command prompt i also get an error message.  Ive submitted issues about this problem 2 times already but nobody on this forum is helping me.  Whats the point of this forum? is there any other method for technical support i can use?

**Comment by akshaybabloo** [comment] 2017-08-08 00:50
Could you link all the issue links here?

**Comment by nevadarain** [comment] 2017-08-08 01:06
@akshaybabloo 

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

string indices must be integers, not str

Traceback

Traceback (most recent call last):
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
window = run_app(splash)
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
window = MainWindow(splash=splash)
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in init
self.api = AnacondaAPI()
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in init
self._conda_api = CondaAPI()
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
CONDA_API = _CondaAPI()
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in init
self.set_conda_prefix()
File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

Your help will be much appreciated. Thank you

**Comment by akshaybabloo** [comment] 2017-08-08 01:16
See #1281

**Comment by msarahan** [comment] 2017-08-08 12:41
Closing as duplicate of #1281.  Thanks @akshaybabloo

**Closed by msarahan** 2017-08-08 12:41 UTC
