### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Andelous** [ContinuumIO/anaconda-issues#4142] opened 2017-08-11 19:58 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\Users\angel\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\Users\angel\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\Users\angel\Anaconda3"

```
## System information
```
python: 3.6.1
language: es_MX
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: None
conda: None
```

**Comment by Andelous** [comment] 2017-08-11 20:00
I've tried changing the folder permissions, and running Anaconda Navigator as administrator. Anaconda is installed just for me, in order to avoid permission issues that come with the installation for everyone, but it doesn't seem to work.

**Comment by Andelous** [comment] 2017-08-11 20:04
The application I was trying to install is Spyder 3.2.0.

**Comment by goanpeca** [comment] 2017-08-13 13:07
**See issue #1845 for more information on how to fix this issue.**

---

Closing as duplicate of #1845

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-13 13:07 UTC
Labels: pkg:navigator
