### ISSUE TITLE
update failure

### ISSUE THREAD

**Issue by xweipbcsf** [ContinuumIO/anaconda-issues#6480] opened 2017-10-07 16:25 UTC
Traceback (most recent call last):
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
    linked_dists = install_linked(prefix)
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
    return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
    load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
    linked_data_[prefix][dist] = rec = IndexRecord(**rec)
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
    instance = super(EntityType, cls).__call__(*args, **kwargs)
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
    setattr(self, key, kwargs[key])
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
    instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
  File "/Users/xingkong/anaconda/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
    raise ValidationError(getattr(self, 'name', 'undefined name'), val)
conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506044346.682 for timestamp

**Comment by DrChrisLevy** [comment] 2017-10-07 23:55
I am having a similar issue:

**Comment by wa1618i** [comment] 2017-10-08 06:49
Same issue here when trying to install:
conda install -c anaconda atlas=3.8.4 
This atlas anaconda installation doesn't occur previously

**Comment by nehaljwani** [comment] 2017-10-08 07:24
Closing as duplicate of https://github.com/conda/conda/issues/6096

**Closed by nehaljwani** 2017-10-08 07:24 UTC
