### ISSUE TITLE
Anaconda Navigator Error upon attempting to open Anaconda Navigator in Windows 

### ISSUE THREAD

**Issue by mohans1411** [ContinuumIO/anaconda-issues#13069] opened 2022-10-11 09:44 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

Anaconda Navigator Error upon attempting to open Anaconda Navigator in Windows 

### Conda info

```shell
Anaconda Navigator Error upon attempting to open Anaconda Navigator in Windows
```

### Conda config

```shell
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 217, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 76, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "E:\Anaconda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Admin\.continuum\anaconda-client\config.yaml", position 0
2022-10-11 15:13:34,919 - ERROR exceptions.handle_exception:89
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Admin\.continuum\anaconda-client\config.yaml", position 0
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 217, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 76, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "E:\Anaconda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Admin\.continuum\anaconda-client\config.yaml", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 87, in handle_exception
    display_qt_error_box(error, traceback)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 19, in display_qt_error_box
    msg_box = MessageBoxError(
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 530, in __init__
    super().__init__(
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 338, in __init__
    self.tracker = GATracker() if analytics else None
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\analytics.py", line 253, in GATracker
    GA_TRACKER = _GATracker()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\analytics.py", line 89, in __init__
    self.api = AnacondaAPI()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1176, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 683, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 145, in __init__
    self.reload_client()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 356, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "E:\Anaconda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Admin\.continuum\anaconda-client\config.yaml", position 0
```

### Conda list

```shell
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 217, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 76, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "E:\Anaconda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Admin\.continuum\anaconda-client\config.yaml", position 0
2022-10-11 15:13:34,919 - ERROR exceptions.handle_exception:89
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Admin\.continuum\anaconda-client\config.yaml", position 0
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 217, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 76, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "E:\Anaconda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Admin\.continuum\anaconda-client\config.yaml", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 87, in handle_exception
    display_qt_error_box(error, traceback)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 19, in display_qt_error_box
    msg_box = MessageBoxError(
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 530, in __init__
    super().__init__(
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 338, in __init__
    self.tracker = GATracker() if analytics else None
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\analytics.py", line 253, in GATracker
    GA_TRACKER = _GATracker()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\analytics.py", line 89, in __init__
    self.api = AnacondaAPI()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1176, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 683, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 145, in __init__
    self.reload_client()
  File "E:\Anaconda\lib\site-packages\anaconda_navigator\api\client_api.py", line 356, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 242, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "E:\Anaconda\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "E:\Anaconda\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "E:\Anaconda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "E:\Anaconda\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Admin\.continuum\anaconda-client\config.yaml", position 0
```

### Additional Context

Anaconda Navigator Error upon attempting to open Anaconda Navigator in Windows

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 09:39
Duplicate of #12762

**Closed by vshevchenko-anaconda** 2023-07-07 09:39 UTC
Labels: type-bug, pkg-navigator
