### ISSUE TITLE
Anaconda doesn't open in windows 10 upgrade to latest as of today

### ISSUE THREAD

**Issue by abhih** [ContinuumIO/anaconda-issues#7379] opened 2017-11-18 19:35 UTC
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

byte indices must be integers or slices, not str
Traceback

Traceback (most recent call last):
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 116, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 259, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\abhis\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 129, in start_app
    "There is an instance of "
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 450, in __init__
    type_=self.INFORMATION_BOX,
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
    self.tracker = GATracker()
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 289, in GATracker
    GA_TRACKER = _GATracker()
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 100, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1258, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Users\abhis\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-11-19 04:26
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-19 04:26 UTC
