### ISSUE TITLE
An unexpected error occurred on Navigator start-up psutil.AccessDenied(pid=6312) 

### ISSUE THREAD

**Issue by christinab12** [ContinuumIO/anaconda-issues#7679] opened 2017-12-07 12:34 UTC
Hi,

When trying to launch Anaconda Navigator I get the error bellow. I have tried updating with: 
$ conda update anaconda-navigator
$ conda update navigator-update
but it doesn't resolve the issue.

I have also uninstalled and re-installed and still get the same error. I was using the Navigator without any problem up until yesterday.

Traceback (most recent call last):
File "C:\Users\christina\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\christina\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\christina\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\christina\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\christina\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\christina\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\christina\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=6312)

**Comment by goanpeca** [comment] 2017-12-07 16:12
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Comment by christinab12** [comment] 2017-12-08 17:05
All requested packages are already installed and there is still the same issue.

**Comment by goanpeca** [comment] 2017-12-08 18:50
Hi @christinab12 did you take a look at

`See issue #1984 for more information on how to fix this` ?

**Closed** 2017-12-08 18:50 UTC

**Comment by christinab12** [comment] 2017-12-09 13:17
Ok I tried reset and it works now. Thanks!

**Comment by goanpeca** [comment] 2017-12-09 14:39
No prob :-)
