### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ASodha** [ContinuumIO/anaconda-issues#9498] opened 2018-06-01 12:04 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.5.0;Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.4
```

**Comment by goanpeca** [comment] 2018-06-01 12:07
Closing as duplicate of #1778

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1778 for more information on how to fix this.**

**Closed by goanpeca** 2018-06-01 12:07 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by ASodha** [comment] 2018-06-01 12:38
cheers bud, 
although now I have 2 navigators under my applications folder. I can't seem to uninstall the old one, how can I do this?

**Comment by goanpeca** [comment] 2018-06-01 13:07
What are the locations of these 2 navigator apps?

When using Spotlight Search

Do you see difference in the locations?

<img width="682" alt="screen shot 2018-06-01 at 08 07 03" src="https://user-images.githubusercontent.com/3627835/40842234-d393b6fc-6572-11e8-9aaa-0051a271e185.png">

**Comment by ASodha** [comment] 2018-06-01 13:14
There is only one under my applications folder.
But 2 on my launchpad, and i cannot seem to remove one.
