### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by amitlevy21** [ContinuumIO/anaconda-issues#3707] opened 2017-07-29 22:24 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/amit/Programs/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3069, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/amit/Programs/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2971, in run_spyder
    main.setup()
  File "/home/amit/Programs/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 820, in setup
    from spyder.plugins.help import Help
  File "/home/amit/Programs/anaconda3/lib/python3.6/site-packages/spyder/plugins/help.py", line 32, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "/home/amit/Programs/anaconda3/lib/python3.6/site-packages/spyder/utils/help/sphinxify.py", line 29, in <module>
    from docutils.utils import SystemMessage as SystemMessage
  File "/home/amit/Programs/anaconda3/lib/python3.6/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/home/amit/Programs/anaconda3/lib/python3.6/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/home/amit/Programs/anaconda3/lib/python3.6/site-packages/docutils/utils/error_reporting.py", line 60, in <module>
    codecs.lookup(locale_encoding or '') # None -> ''
NameError: name 'locale_encoding' is not defined

```
## System information
```
python: 3.6.1
language: en
os: Linux;4.10.0-28-generic;#32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.23
```

**Comment by gavenkoa** [comment] 2017-10-08 18:11
Like here: https://github.com/spyder-ide/spyder/issues/5155 - add `LC_ALL=C`

**Comment by goanpeca** [comment] 2017-10-09 17:42
Closin as duplicate of https://github.com/spyder-ide/spyder/issues/5155

**Closed by goanpeca** 2017-10-09 17:42 UTC
Labels: pkg:navigator, pkg:spyder, reso:duplicate
