### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Jerriychen** [ContinuumIO/anaconda-issues#3844] opened 2017-08-03 00:53 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x105b7f410>: Failed to establish a new connection: [Errno 65] No route to host',))",),)

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.22
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.1.0;Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-08-03 00:54
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-03 00:54 UTC
Labels: pkg:navigator, reso:duplicate
