### ISSUE TITLE
Spyder: "The ordinal 242 could not be located in the dynamic link library libiomp5md.dll"

### ISSUE THREAD

**Issue by josephernest** [ContinuumIO/anaconda-issues#11547] opened 2020-01-09 11:02 UTC
Hello,
I just installed `Anaconda3-2019.10-Windows-x86_64.exe` on a Windows 7 x64 PC. 
When running Spyder, I get:
 
![image](https://user-images.githubusercontent.com/6168083/72062304-d4eed200-32d7-11ea-8693-c5b6a4e13285.png)

Is it a well-known issue? What is the solution for this issue?

**Comment by msarahan** [comment] 2020-01-09 14:25
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/10672

**Closed by msarahan** 2020-01-09 14:25 UTC

**Comment by josephernest** [comment] 2020-01-09 15:25
@msarahan I have looked at https://github.com/ContinuumIO/anaconda-issues/issues/10672 but there is no easy fix for this issue.

For a course I'm starting to teach next week, I planned to ask students to install this Anaconda version on their laptop... But with this kind of difficult-to-debug error, it seems probably not a good idea.

Would you recommend to install a standard python package from python.org in the meantime until this problem is fixed, to avoid lots of debugging @msarahan ?

Thanks in advance

PS: asking students to install VMware + linux + Anaconda inside is not an option. 

PS2: Not sure this one here is a duplicate of #10672 because the latter is `The ordinal 242 could not be located in the dynamic link library mkl_intel_thread.dll` and in my case it's `libiomp5md.dll`.

**Comment by csoja** [comment] 2020-01-09 16:10
Did you try https://github.com/ContinuumIO/anaconda-issues/issues/10672#issuecomment-466716217 ? 

From the Anaconda Prompt, please try conda update python

then if that doesn't work, try:

set CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1

More details here: https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

It is a case of you having conflicting software installed and the wrong version of the dll is being picked up.

**Comment by josephernest** [comment] 2020-01-09 16:20
> set CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1
Thank you for your comment @csoja.

I tried this but it still does not work:

![image](https://user-images.githubusercontent.com/6168083/72084733-52c8d280-3304-11ea-9f67-2c131da83cc4.png)

> It is a case of you having conflicting software installed and the wrong version of the dll is being picked up.

IMHO this should not be a problem, we all have lots of programs installed, and all of them either use the C:\Windows\System32\* files, or local .dll files in the program folder, or use statically linked libs.

Possible solution: **Shouldn't Anaconda pack the right .dll in the Anaconda installation folder?** So that this has the priority, and then it wouldn't matter if similar files (but different version) are found in C:\Windows\System32\.
I think that's how many programs ensure that there are no .dll problems.

**Comment by josephernest** [comment] 2020-01-10 11:56
PS: I tried with 2019-10, 2019-07, 2019-03, and it's the same.

**Comment by msarahan** [comment] 2020-01-13 14:17
Anaconda is made up of hundreds of individual packages.  That's before
users start installing any of the many available additional packages.  The
Windows DLL search paths are detailed in the FAQ that @csoja listed.  You
are correct that if every .dll lived alongside the python.exe file, there
would be fewer issues.  However, Python on Windows has an especially poor
standard file layout, where python.exe sits at the root of an
installation.  If all DLLs were installed there, the probability of name
conflicts would be high, and it would also be a terrible mess.  Static
linking is an option, but then every package using a given library would
need to be rebuilt whenever that given library was updated.

We all have lots of programs installed, but I'm not aware of any program
that is dynamically composed of as many parts as Anaconda.  The cost of
flexibility is this increased complexity and fragility, and if you research
this issue, you'll see that we have poured several man-months of effort
into this, dating back to at least 2016.  The lack of an RPATH-like
mechanism and the conflation of executable and shared library search PATH
on Windows are serious weaknesses on Windows.

You seem to be blaming Anaconda primarily for this not working.  You should
also consider investigating why the rogue libiomp5.dll file is present in
your system32 folder.  That is the fundamental malpractice here, and it's
likely that whatever has installed that is actually an easier place to
change, by shifting their behavior to putting libiomp5.dll alongside the
consumer application, which presumably is a much less complicated
collection of parts.

**Comment by josephernest** [comment] 2020-01-13 17:12
Thank you for your answer @msarahan. 
Of course, I could easily investigate why it does not work *on this precise computer*, and how libiomp5.dll could be moved or removed, etc.  
But I was planning to use Anaconda in a teaching situation, for which it's not possible to spend a few minutes on each student's computer to debug why some DLLs are interfering with Anaconda.
That's why I was suggesting to find a better solution, less sensitive to potential incompatible DLLs, etc.

(And by the way, on the same computer, installing the same Python version from python.org + pip install numpy etc. did not give this error, so I was curious what caused the problem here for this Anaconda package.)
