### ISSUE TITLE
Navigator Error after pc shut down

### ISSUE THREAD

**Issue by NinjaAtWork** [ContinuumIO/anaconda-issues#12593] opened 2021-09-01 16:50 UTC
this happened when i removed an `env `and accidentally pc got shut down due to electricity cut ,after turn on i was unable to launch the navigator, take one hour to uninstall conda for a fresh install, so much terrible
```

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

'NoneType' object has no attribute 'split'

Traceback

Traceback (most recent call last):
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 166, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1534, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 81, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1571, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 342, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Ninja\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 500, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 10:12
Duplicate of #11780

**Closed by vshevchenko-anaconda** 2023-07-07 10:12 UTC
