### ISSUE TITLE
Navigator Error on starting Anaconda-Navigator

### ISSUE THREAD

**Issue by anugrah-saxena** [ContinuumIO/anaconda-issues#3349] opened 2017-07-19 20:41 UTC
Main Error

byte indices must be integers or slices, not str
Traceback

Traceback (most recent call last):
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\USER_NAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-07-19 20:41
Closing as duplicate of #1837

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-19 20:41 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by anugrah-saxena** [comment] 2017-07-19 21:15
@goanpeca that wouldn't work for my windows machine. It says conda not found. I think there is a different command for Win. So, I am just uninstalling and reinstalling again.
I will let you know if there is other problem. Thanks.

**Comment by anugrah-saxena** [comment] 2017-07-19 21:28
Thanks. It is working now!
