### ISSUE TITLE
navigator error 7960

### ISSUE THREAD

**Issue by wiserguy1964** [ContinuumIO/anaconda-issues#7916] opened 2017-12-25 17:41 UTC
Traceback (most recent call last):
File "C:\Users\VASILIOS\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\VASILIOS\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\VASILIOS\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\VASILIOS\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\VASILIOS\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\VASILIOS\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\VASILIOS\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=7960)

**Comment by goanpeca** [comment] 2017-12-26 11:59
Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See issue #1984 for more information on how to fix this.**

**Closed by goanpeca** 2017-12-26 11:59 UTC
