### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by cherry30036** [ContinuumIO/anaconda-issues#8102] opened 2018-01-11 18:04 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 23:32:46.051 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 23:32:46.068 NotebookApp] Serving notebooks from local directory: /home/cherry
[I 23:32:46.068 NotebookApp] 0 active kernels 
[I 23:32:46.068 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=be40bbc1ce7d6595c6f8e3b409c8ab54890ccb236af1ba02
[I 23:32:46.068 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:32:46.069 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=be40bbc1ce7d6595c6f8e3b409c8ab54890ccb236af1ba02
[I 23:32:47.724 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[12106:12145:0111/233247.868831:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_IN
python: 2.7.13
os: Linux;4.10.0-43-generic;#47~16.04.1-Ubuntu SMP Wed Dec 13 19:23:27 UTC 2017;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2018-01-11 18:05
Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #2098 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-01-11 18:05 UTC
Labels: pkg:navigator, reso:duplicate
