### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by i-amgeek** [ContinuumIO/anaconda-issues#6953] opened 2017-10-28 16:43 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 22:12:50.098 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 22:12:51.110 NotebookApp] Serving notebooks from local directory: /home/anonymous
[I 22:12:51.110 NotebookApp] 0 active kernels 
[I 22:12:51.110 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=202f6c681326d3b0da4c8ad520fc527addbe57069631f177
[I 22:12:51.110 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:12:51.111 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=202f6c681326d3b0da4c8ad520fc527addbe57069631f177
[21125:21160:1028/221251.612749:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[I 22:12:51.639 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 22:12:52.482 NotebookApp] /home/anonymous/.#c.c doesn't exist

```
## System information
```
python: 3.6.1
language: en_IN
os: Linux;4.4.0-53-generic;#74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-10-29 04:39
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-29 04:39 UTC
Labels: pkg:navigator, reso:duplicate
