### ISSUE TITLE
Anaconda picking up wrong version of xlwings

### ISSUE THREAD

**Issue by cwreid18** [ContinuumIO/anaconda-issues#1503] opened 2017-03-06 15:12 UTC
When I run `conda install xlwings=0.7.2` in a new environment, the version that gets installed is not 0.7.2 but 0.10.0 (judging from the xlwings.bas file in Lib/site_packages/xlwings). This also happens when running `conda install anaconda=4.1.1`. My root environment is python 3.5 and anaconda 4.1.1 (which contains xlwings 0.7.2), but this issue also occurs with a root environment of python 3.6 and anaconda 4.3.0. In every case, conda thinks it has installed xlwings 0.7.2 (as indicated by the output of `conda list`), but this is not the case.

**Comment by nehaljwani** [comment] 2017-05-17 19:59
How are you determining that the version of `xlwings` installed is `0.10.0` and not `0.7.2`?

```cmd
(1503py27) C:\Users\nwani>conda list xlwings
# packages in environment at C:\Users\nwani\AppData\Local\Continuum\Miniconda2\envs\1503py27:
#
xlwings                   0.7.2                    py27_0

(1503py27) C:\Users\nwani>type %CONDA_PREFIX%\Lib\site-packages\xlwings\xlwings.bas | findstr/n ^^|findstr "^[1-2]:"
1:Attribute VB_Name = "xlwings"
2:' xlwings.org, version: 0.7.2

(1503py27) C:\Users\nwani>python -c "import xlwings; print xlwings.__version__"
0.7.2
```

```cmd
(1503py35) C:\Users\nwani>conda list xlwings
# packages in environment at C:\Users\nwani\AppData\Local\Continuum\Miniconda2\envs\1503py35:
#
xlwings                   0.7.2                    py35_0

(1503py35) C:\Users\nwani>type %CONDA_PREFIX%\Lib\site-packages\xlwings\xlwings.bas | findstr/n ^^|findstr "^[1-2]:"
1:Attribute VB_Name = "xlwings"
2:' xlwings.org, version: 0.7.2

(1503py35) C:\Users\nwani>python -c "import xlwings; print(xlwings.__version__)"
0.7.2
```

Closing as unable to reproduce. Please re-open if you find otherwise.

**Closed by nehaljwani** 2017-05-17 19:59 UTC
Labels: os:windows, reso:invalid
