### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mdirac** [ContinuumIO/anaconda-issues#6661] opened 2017-10-15 09:54 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb957428a50>: Failed to establish a new connection: [Errno 111] Connection refused',)))",),)

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Linux;3.13.0-133-generic;#182-Ubuntu SMP Tue Sep 19 15:49:21 UTC 2017;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-10-15 09:56
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-15 09:56 UTC
Labels: pkg:navigator, reso:duplicate
