### ISSUE TITLE
Anaconda Navigator won't open after update

### ISSUE THREAD

**Issue by pranavdogra7** [ContinuumIO/anaconda-issues#8954] opened 2018-03-21 05:06 UTC
Traceback (most recent call last):
  File "/Users/binga/anaconda3/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 129, in main
    from anaconda_navigator.app.start import start_app
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 33, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 32, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 33, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 24, in <module>
    from anaconda_navigator.api.conda_api import CondaAPI
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 33, in <module>
    from anaconda_navigator.utils.findpip import PIP_LIST_SCRIPT
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/findpip.py", line 22, in <module>
    import pip
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/Users/binga/anaconda3/lib/python3.6/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'

******conda info
platform : osx-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/binga/anaconda3  (writable)
    default environment : /Users/binga/anaconda3
       envs directories : /Users/binga/anaconda3/envs
                          /Users/binga/.conda/envs
          package cache : /Users/binga/anaconda3/pkgs
                          /Users/binga/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/binga/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.34 requests/2.18.4 CPython/3.6.3 Darwin/17.2.0 OSX/10.13.1    
                UID:GID : 501:20

**Comment by nehaljwani** [comment] 2018-03-21 06:43
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/8911

**Closed by nehaljwani** 2018-03-21 06:43 UTC
