### ISSUE TITLE
psutil.AccessDenied: psutil.AccessDenied (pid=6320)

### ISSUE THREAD

**Issue by joejoejoe60507** [ContinuumIO/anaconda-issues#6006] opened 2017-09-24 01:04 UTC
Traceback (most recent call last):
File "C:\Users\ASUS\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\ASUS\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] 存取被拒。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\ASUS\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\ASUS\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\ASUS\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\ASUS\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "C:\Users\ASUS\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=6320)

**Comment by goanpeca** [comment] 2017-09-24 20:24
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-24 20:24 UTC

**Comment by mdc713** [comment] 2017-11-08 16:39
This fix _is not_ working. I have the exact issue described above, and when I run the two conda update commands, I see this:

```
(C:\Users\macolli\AppData\Local\Continuum\anaconda3) C:\WINDOWS\system32>conda update anaconda
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\macolli\AppData\Local\Continuum\anaconda3:
#
anaconda                  5.0.1            py36h8316230_2

(C:\Users\macolli\AppData\Local\Continuum\anaconda3) C:\WINDOWS\system32>conda update anaconda-navigator
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\macolli\AppData\Local\Continuum\anaconda3:
#
anaconda-navigator        1.6.9            py36hc720852_0

(C:\Users\macolli\AppData\Local\Continuum\anaconda3) C:\WINDOWS\system32>conda update navigator-updater
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\macolli\AppData\Local\Continuum\anaconda3:
#
navigator-updater         0.1.0            py36h8a7b86b_0
```

**Comment by goanpeca** [comment] 2017-11-08 16:42
Please read `See issue #1984 for more information on how to fix this.`

**Comment by ashleshsortee** [comment] 2018-01-30 16:58
For me updating anaconda navigator and then restarting laptop worked.

**Comment by ashleshsortee** [comment] 2018-01-30 16:59
For me updating anaconda navigator and restarting laptop worked.

**Comment by SheikhNoor** [comment] 2023-11-15 12:37
Traceback (most recent call last):
      File "C:\Users\NOAH\anaconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\NOAH\anaconda3\Lib\site-packages\conda\cli\main.py", line 54, in main_subshell
        parser = generate_parser(add_help=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\NOAH\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 127, in generate_parser
        configure_parser_plugins(sub_parsers)
      File "C:\Users\NOAH\anaconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 354, in configure_parser_plugins
        else set(find_commands()).difference(plugin_subcommands)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\NOAH\anaconda3\Lib\site-packages\conda\cli\find_commands.py", line 71, in find_commands
        for entry in os.scandir(dir_path):
                     ^^^^^^^^^^^^^^^^^^^^
    OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:\\Program Files (x86)\\GnuWin32\\bin'

`$ C:\Users\NOAH\anaconda3\Scripts\conda-script.py --version`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\NOAH\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\NOAH\anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\NOAH\anaconda3
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\NOAH
               LD_PRELOAD=<not set>
                     PATH=C:\Program Files\Microsoft\jdk-11.0.16.101-
                          hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:
                          \Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\
                          ;C:\MinGW\bin;C:\Program Files\Git\cmd;"C:\Program Files
                          (x86)\GnuWin32\bin;C:\Program Files (x86)\Embarcadero\Dev-Cpp\TDM-GCC-
                          64\bin";C:\Users\NOAH\AppData\Local\Programs\Python\Python312\Scripts;
                          C:\Users\NOAH\AppData\Local\Microsoft\WindowsApps;C:\Users\NOAH\AppDat
                          a\Local\Programs\Microsoft VS Code\bin;C:\Users\NOAH\anaconda3\Library
                          \bin\;C:\Users\NOAH\anaconda3\Scripts\;C:\Users\NOAH\anaconda3\condabi
                          n\;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\NOAH\.condarc
 populated config files : C:\Users\NOAH\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\NOAH\anaconda3  (writable)
      conda av data dir : C:\Users\NOAH\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\NOAH\anaconda3\pkgs
                          C:\Users\NOAH\.conda\pkgs
                          C:\Users\NOAH\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\NOAH\anaconda3\envs
                          C:\Users\NOAH\.conda\envs
                          C:\Users\NOAH\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
\
