### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by koyo-jakanees** [ContinuumIO/anaconda-issues#2900] opened 2017-07-06 10:32 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: /home/koyo/anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area '/home/koyo/anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="/home/koyo/anaconda3"

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.4.0-83-generic;#106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-07-06 14:57
Closing as duplicate of #1845

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-06 14:57 UTC
Labels: pkg:navigator

**Comment by koyo-jakanees** [comment] 2017-07-07 08:43
i get the same error messege when installing OSMnx via conda even as a super user, what did i miss during installation
@goanpeca
