### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by peteashton** [ContinuumIO/anaconda-issues#1866] opened 2017-06-02 08:20 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
pyqt: 5.6.0
version: 1.6.2
python: 3.5.3
platform: osx-64
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Mon Apr 17 17:15:27 PDT 2017; root:xnu-3789.60.24~21/RELEASE_X86_64;x86_64;i386
conda: 4.3.21
qt: 5.6.2
language: en
```

**Comment by nehaljwani** [comment] 2017-06-03 08:51
Closing as duplicate of #1778

**Closed by nehaljwani** 2017-06-03 08:51 UTC
