### ISSUE TITLE
Failed to create menus

### ISSUE THREAD

**Issue by fusionkram** [ContinuumIO/anaconda-issues#8464] opened 2018-02-07 19:05 UTC
I am trying to install Anaconda on a Win10 machine (64 bit). It gets mostly through the install but near the end, it give a "failed to create menus" error. The dialog window gives me 3 choices (retry, ignore, cancel). Using retry just gives back the error window. I chose "ignore" to continue. I saw previous posts of this problem but they don't help. One of the big differences is that when I look in the Anaconda3 folder, the pythonw.exe file is not in there. It only has the "Lib" and "pkgs" folders, ".nonadmin" and "Uninstall-Anaconda3.exe". I noticed in the script, it is trying to execute a "pythonw.exe" command, which is why it's failing. I ran the install with "debugview" on. 

I saw in those earlier posts that it says it is better to install as "just for me" and as non-admin. I did install as "just for me", but I am installing as admin. For some reason, my computer won't let me create an non-admin account.

The debugview log is:
00000001	0.00000000	[6884] InitSideBySide failed create an activation context. Error: 1814	
00000002	2.68831134	[11536] InitSideBySide failed create an activation context. Error: 1814	
00000003	356.14364624	[13064] ERROR FindDefaultInterface:CM_Get_Device_Interface_List_Size failed:0x00000000, InterfaceListSize = 1  	
00000004	356.14376831	[13064] ERROR SensorOpenByType:Failed to open sensor error:0x0000007E 	
00000005	356.14450073	[13064] ERROR FindDefaultInterface:CM_Get_Device_Interface_List_Size failed:0x00000000, InterfaceListSize = 1  	
00000006	356.14450073	[13064] ERROR SensorOpenByType:Failed to open sensor error:0x00000490 	
00000007	824.54394531	[4248] InitSideBySide failed create an activation context. Error: 1814

**Comment by mingwandroid** [comment] 2018-02-07 19:08
You have not ran into a failure to create menu entries, you've run into a race condition in the installer logic that will be fixed in the next release.

As a workaround you should be able to use Miniconda. From a `cmd.exe` prompt, run the following:

```
cd %UserProfile%
powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe', 'mc3.exe') }"
start /wait "" mc3.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=0 /S /D=%UserProfile%\anaconda3
%UserProfile%\anaconda3\Scripts\activate.bat
conda install -y anaconda=5.0.1 conda-build _ipyw_jlab_nb_ext_conf
```

**Comment by fusionkram** [comment] 2018-02-08 03:24
Thanks for the quick response. The instructions, as given did not work. After executing the "start" statement, there was no activate.bat in the Anaconda3 folder. It did create a Miniconda3 folder with the "mc3.exe" program. I ran that program. It then created the activate.bat. I ran the batch file and then executed the "conda install" statement. It all ran to completion. I now have a "python.exe" file in Miniconda3 that brings up a command-line python interpreter. I guess I can't get a environment in Miniconda? When is the next release of Anaconda come out?

**Comment by mingwandroid** [comment] 2018-02-08 08:35
This line:

> powershell -command "& { (New-Object Net.WebClient).DownloadFile('https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe', 'mc3.exe') }"

.. creates mc3.exe, not the `start` line. That installs Miniconda3 into `%UserProfile%\Anaconda3`.

The line after that activates your Miniconda3 installation and the one after that turns this Miniconda3 into Anaconda3 5.0.1.

These instructions have worked successfully for many people. You need to paste the exact output from the `cmd.exe` prompt if I am to be able to help you here.

The next release is due out soon, a week or so hopefully.

**Comment by fusionkram** [comment] 2018-02-08 14:52
Success!! I re-ran the commands as provided. I don't know why it didn't work the first time but it worked when I tried it again. Thank you, mingwandroid, for all your help!

**Closed** 2018-02-08 14:53 UTC

**Comment by smiddy** [comment] 2018-03-06 15:54
When will  the race condition be fixed? I used the anaconda installer version 5.1 and the problem is still present.

**Comment by inhwanlee** [comment] 2018-03-18 17:51
I had exactly same problem and I solved this issue by removing Java related variable in system PATH.
I had %JAVA_HOME%\bin in path and after removed this path, the installation just worked without any problem.

**Comment by king07828** [comment] 2018-04-29 13:36
April 29 and this is still a problem.

How to get to a prior version of the installer that works?

**Comment by vmartinlac** [comment] 2018-05-24 07:43
I too run into the same message "Failed to create menus" when installing either Miniconda on Windows 7. I was not able to install anaconda correctly even following the above instructions.
