### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sugarKun** [ContinuumIO/anaconda-issues#8166] opened 2018-01-17 00:12 UTC
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Packages missing in current channels:
            
  - rstudio ==1.1.383 -> fonts-anaconda
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> libgfortran >=3.0.1
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> ncurses 6.0.*
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-ddalpha
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-dimred >=0.1.0 -> r-drr -> r-cvst
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-gower
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-rcpproll
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-withr >=2.0.0
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-dbi >=0.7
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-glmnet >=2.0_13
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-haven >=1.1.0
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-httr >=1.3.1
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-modelr >=0.1.1
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-quantmod >=0.4_11
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-recommended >=3.4.2
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-shiny >=1.0.5 -> r-httpuv >=1.3.5
  - rstudio ==1.1.383 -> r-mongolite >=0.8
  - rstudio ==1.1.383 -> r-odbc >=1.1.1
  - rstudio ==1.1.383 -> r-profvis >=0.3.2
  - rstudio ==1.1.383 -> r-rjdbc >=0.2_5
  - rstudio ==1.1.383 -> r-rsconnect >=0.8.5

We have searched for the packages in the following channels:
            
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
            
```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment] 2018-01-18 16:50
Closing as duplicate of #6970

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #6970 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-01-18 16:50 UTC
