### ISSUE TITLE
ANACONDA NAVIGATION START UP ACCESS DENIED....

### ISSUE THREAD

**Issue by cmorris2945** [ContinuumIO/anaconda-issues#4402] opened 2017-08-19 06:43 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=10180)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Christopher\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Christopher\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Christopher\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Christopher\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Christopher\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Christopher\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Christopher\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=10180)

```
## System information
```
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
qt: 5.6.2
python: 3.5.3
language: en_US
pyqt: 5.6.0
version: 1.6.2
conda: 4.3.24
platfor

**Comment by goanpeca** [comment] 2017-08-19 06:43
**See Issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-19 06:43 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by mohitmonu23** [comment] 2018-01-16 07:44
when i run anaconda navigator it shows me like this error
Traceback (most recent call last):
File "C:\Users\asus\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\asus\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\asus\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\asus\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\asus\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\asus\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\asus\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=7360)

**Comment by csoja** [comment] 2018-01-16 14:46
@mohitmonu23 from an Anaconda Prompt Window, please execute _anaconda-navigator --reset_

**Comment by mohitmonu23** [comment] 2018-01-16 14:58
@csoja 
Thank you

**Comment by robbertliu** [comment] 2019-01-29 07:13
@csoja 
Thank you, [rose]

**Comment by santosh2702** [comment] 2020-04-16 04:43
Thank you [@csoja]
