### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by lTesseraktl** [ContinuumIO/anaconda-issues#2706] opened 2017-06-29 07:21 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda3"

```
## System information
```
python: 3.6.1
language: ru_RU
os: Windows;10;10.0.15063;AMD64;AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-06-29 13:34
Closing as duplicate of #1845

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-29 13:34 UTC
Labels: pkg:navigator

**Comment by Brockmerkwan** [comment] 2017-07-06 04:42
I have tried this and I am still getting  an error I am using Ubuntu Linux with zsh shell

**Comment by Brockmerkwan** [comment] 2017-07-06 07:37
never mind I fixed it with chmod -R +x
