### ISSUE TITLE
Issue with conda environments

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#487] opened 2015-10-21 10:00 UTC
Since yesterday, I'm seeing this kind of failure on AppVeyor (Windows continuous integration)

```
[00:07:12] #
[00:07:12] # To activate this environment, use:
[00:07:12] # > activate test
[00:07:12] #
[00:07:12] activate test
[00:07:12] Activating environment ""C:\conda\Scripts\..\envs"\test"...
[00:07:12] python --version
[00:07:12] Python 2.7.10 :: Continuum Analytics, Inc.
[00:07:12] conda install -q --yes numpy scipy cython astropy pyqt matplotlib h5py pygments pyzmq scikit-image pandas sphinx xlrd pillow pytest mock coverage ipython ipykernel qtconsole traitlets
[00:07:12] Fetching package metadata: 
[00:07:12] .
[00:07:13] .
[00:07:13] .
[00:07:13] .
[00:07:13] 
[00:07:14] Error: environment does not exist: C:\projects\glue\"C:\conda\envs"\test
[00:07:14] #
[00:07:14] # Use 'conda create' to create an environment before installing packages
[00:07:14] # into it.
[00:07:14] #
[00:07:14] Command exited with code 1
```

I also saw a similar error on Travis, but it seems to be random. Any ideas what could be causing this?

**Comment by ccordoba12** [comment] 2015-10-21 13:11
It seems an error in the activation script. What is your conda version?

**Comment by msarahan** [comment] 2015-10-21 13:24
That's a problem that slipped into conda-env.  My fault.  Conda-env 2.4.3 will exhibit this problem.  I will fix this as soon as possible.

**Comment by embray** [comment] 2015-10-21 16:42
Thanks @msarahan :+1:

**Comment by msarahan** [comment] 2015-10-21 20:17
conda-env 2.4.3 has been removed from our repositories for Windows.  This should be an OK release for Linux/OS X, now that Ilan has fixed the packaging issue on those platforms.  This release should be considered dysfunctional on Windows.  We will issue a new release shortly.  For those interested: https://github.com/conda/conda-env/pull/188

**Comment by ukoethe** [comment] 2015-10-22 08:35
The problem is caused by some extraneous quote characters that slipped into `activate.bat`. I propose a fix in https://github.com/conda/conda-env/pull/187, but as far as I understand, the conda folks are working on a more principled solution.

**Comment by msarahan** [comment] 2015-10-22 12:29
See https://github.com/conda/conda/pull/1727 and https://github.com/conda/conda-env/pull/189

These will be merged today.  We will tag new conda and conda-env versions very soon.

We have removed packages for conda-env 2.4.3 from the repository, so we hope that people will not have further issue going forward.  The simplest way to undo damage that the conda-env update may have caused is to:

1. Manually hack activate.bat to apply https://github.com/conda/conda-env/pull/187 - your installation may be broken otherwise.
2. Downgrade to conda-env 2.4.2.

    conda install -f conda-env

should do the trick.

**Closed** 2017-05-09 08:03 UTC
