### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by alybel** [ContinuumIO/anaconda-issues#6999] opened 2017-10-30 16:38 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[I 00:37:00.385 NotebookApp] Serving notebooks from local directory: /var/folders/zt/j9pl6d717d5ctx2_qg9vqrpw0000gn/T/spyder-alexanderbeck/notebooks
[I 00:37:00.385 NotebookApp] 0 active kernels 
[I 00:37:00.385 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=4eff8dad86a33430f7a91a6a2a4d882af9bf8809f548cdda
[I 00:37:00.385 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:37:00.385 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=4eff8dad86a33430f7a91a6a2a4d882af9bf8809f548cdda
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
python: 3.6.3
language: en
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment] 2017-10-30 16:40
**See Issue #1778 for more information on how to fix this.**

---

Closing as duplicate of #1778


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-30 16:40 UTC
Labels: pkg:navigator, reso:duplicate
