### ISSUE TITLE
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode' in "C:\Users\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

### ISSUE THREAD

**Issue by westsnownice** [ContinuumIO/anaconda-issues#8735] opened 2018-03-03 10:27 UTC
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment] 2018-03-04 00:54
Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.11
```

**Closed by goanpeca** 2018-03-04 00:54 UTC
