### ISSUE TITLE
Anaconda keeps crashing and will not open. 

### ISSUE THREAD

**Issue by iamnoob246** [ContinuumIO/anaconda-issues#4654] opened 2017-08-27 00:32 UTC
Every time I open anaconda it crashes, can anyone help? I got this text : 
Traceback (most recent call last):
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
window = run_app(splash)
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
window = MainWindow(splash=splash)
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
self.api = AnacondaAPI()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
self._conda_api = CondaAPI()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
CONDA_API = _CondaAPI()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
self.set_conda_prefix()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-08-27 00:32
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-27 00:32 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by iamnoob246** [comment] 2017-08-27 01:13
I tried that but still is not working.

**Comment by iamnoob246** [comment] 2017-08-27 01:18
this is what im getting Traceback (most recent call last):
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
window = run_app(splash)
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
window = MainWindow(splash=splash)
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
self.api = AnacondaAPI()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1214, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
self._conda_api = CondaAPI()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
CONDA_API = _CondaAPI()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
self.set_conda_prefix()
File "/Users/mavericksofhate/anaconda/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 494, in set_conda_prefix
self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-08-28 13:18
@iamnoob246 what happens if you open a terminal, then do `source activate root` and then `anaconda-navigator` ?

**Comment by iamnoob246** [comment] 2017-08-28 16:46
Got it to work!

**Comment by iamnoob246** [comment] 2017-08-28 16:47
Thanks for the help!
