### ISSUE TITLE
Issues with netCDF mismatch

### ISSUE THREAD

**Issue by josephhardinee** [ContinuumIO/anaconda-issues#1588] opened 2017-04-06 18:27 UTC
netCDF appears to be broken on a new installation (in a conda environment) of anaconda with python 3.6

`conda create -p $HOME/py36 anaconda`
`source activate /global/homes/j/jhardin/py36`
`conda install netCDF4`

Then in ipython
`from netCDF4 import Dataset`
yields
ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory

If you conda remove netCDF4 and install via pip it works.

This seems to be an issue in both 2.7 and 3.6 (The only two versions I tested).

**Comment by jjhelmus** [comment] 2017-04-06 21:14
I believe this is the same issue as #1360.  I can reproduce this issue and installing hdf4 version 4.2.12 using `conda install hdf4=4.2.12` seems to fix the netCDF4 import.

**Comment by josephhardinee** [comment] 2017-04-06 21:55
I can verify this does fix it on my system and it does look like 1360.

**Comment by rabernat** [comment] 2017-05-08 20:11
Really important to get these netcdf issues fixed. These errors are tripping up new python geoscience users, causing them deep frustration with python / anaconda as a whole.

**Comment by nehaljwani** [comment] 2017-05-17 05:42
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1360

**Closed by nehaljwani** 2017-05-17 05:42 UTC
Labels: reso:duplicate, type:bug
