### ISSUE TITLE
Re: Anaconda Initialization Errors

### ISSUE THREAD

**Issue by Lemniscatus** [ContinuumIO/anaconda-issues#3019] opened 2017-07-10 13:19 UTC
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 124, in start_app
"There is an instance of "
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 450, in __init__
type_=self.INFORMATION_BOX,
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
self.tracker = GATracker()
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\utils\analytics.py", line 284, in GATracker
GA_TRACKER = _GATracker()
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\utils\analytics.py", line 95, in __init__
self.api = AnacondaAPI()
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
self._conda_api = CondaAPI()
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
CONDA_API = _CondaAPI()
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
self.set_conda_prefix()
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**Comment by goanpeca** [comment] 2017-07-10 15:30
Closing as duplicate of #1837

Please update to the latest version of Navigator.

Open a terminal and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-10 15:30 UTC
