### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by changjurhee** [ContinuumIO/anaconda-issues#4657] opened 2017-08-27 03:11 UTC
Windows7 (x64)
Anaconda3
 

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda  issue tracker  

Main Error

list indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: list indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-08-28 13:32
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-28 13:32 UTC

**Comment by changjurhee** [comment] 2017-08-30 09:51
My windows system has firewall so that I could not use properly conda prompt command. 
Do I have to reinstall ?

**Comment by changjurhee** [comment] 2017-08-30 11:10
- uninstall
- reinstall 4.4.0 x64
- conda update anaconda-navigator

```
C:\Users\Administrator>conda --version
[0x61017D80] ANOMALY: meaningless REX prefix used
[0x61018520] ANOMALY: meaningless REX prefix used
conda 4.3.21

C:\Users\Administrator>conda update anaconda-navigator
[0x61017D80] ANOMALY: meaningless REX prefix used
[0x61018520] ANOMALY: meaningless REX prefix used
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\ProgramData\Anaconda3:

The following packages will be UPDATED:

    anaconda:           4.4.0-np112py36_0 --> custom-py36_0
    anaconda-navigator: 1.6.2-py36_0      --> 1.6.4-py36_0
    conda:              4.3.21-py36_0     --> 4.3.25-py36_0

Proceed ([y]/n)?

anaconda-custo 100% |###############################| Time: 0:00:00 882.38 kB/s
anaconda-navig 100% |###############################| Time: 0:00:00   8.10 MB/s
conda-4.3.25-p 100% |###############################| Time: 0:00:00   8.64 MB/s
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: '
system'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: '
system'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: '
system'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'None', used_mode: '
system'

C:\Users\Administrator>

```
unfortunately, still got navigator error. 


Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda  issue tracker  


Main Error

list indices must be integers or slices, not str


Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: list indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-08-30 13:03
It seems to be related to the fact you installed for all users. I suggest you uninstall and reinstall for the current user as the installation advices

**Comment by changjurhee** [comment] 2017-08-31 05:17
As you guess, I did it. However, it seems still same error. 


Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda  issue tracker  


Main Error

list indices must be integers or slices, not str


Traceback

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\Administrator\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: list indices must be integers or slices, not str

**Comment by changjurhee** [comment] 2017-08-31 05:22
Should I install lower version than latest ?

**Comment by goanpeca** [comment] 2017-08-31 14:28
@changjurhee what ahppens if you start navigator by opening the `Anaconda Prompt` and typing:

`anaconda-navigator`

?
