### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by harishj011** [ContinuumIO/anaconda-issues#1941] opened 2017-06-04 19:47 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>[Errno 13] Permission denied: '/home/harish/.anaconda/navigator/navigator.lock'
## Traceback
```
Traceback (most recent call last):
  File "/home/harish/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/harish/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 111, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "/home/harish/anaconda3/lib/python3.6/site-packages/anaconda_navigator/external/filelock.py", line 242, in acquire
    self._acquire()
  File "/home/harish/anaconda3/lib/python3.6/site-packages/anaconda_navigator/external/filelock.py", line 386, in _acquire
    fd = os.open(self._lock_file, open_mode)
PermissionError: [Errno 13] Permission denied: '/home/harish/.anaconda/navigator/navigator.lock'

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.8.0-53-generic;#56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```
I am not able to launch anaconda Navigator in Ubuntu ,,,,, I removed the software 3 times and then installed 3 times. Then also i am getting the same error. Can anybody know this error and if you guys give some guidance that will be a great help.

**Comment by nehaljwani** [comment] 2017-06-04 19:49
Related #1867 #1939

**Comment by goanpeca** [comment] 2017-07-11 23:50
Closing as duplicate of #1984 

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-11 23:50 UTC
Labels: pkg:navigator
