### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by muhammadsaheer** [ContinuumIO/anaconda-issues#3483] opened 2017-07-23 16:05 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: /home/saheer/anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area '/home/saheer/anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="/home/saheer/anaconda3"

```
## System information
```
python: 3.6.1
language: en_IN
os: Linux;4.4.0-21-generic;#37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-07-23 16:05
Closing as duplicate of #1845

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-23 16:05 UTC
Labels: pkg:navigator
