### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Andelous** [ContinuumIO/anaconda-issues#4310] opened 2017-08-16 08:48 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/angel/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/angel/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/angel/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/angel/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/angel/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.9.40-1-MANJARO;#1 SMP PREEMPT Fri Jul 28 09:24:52 UTC 2017;x86_64;
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-08-16 14:11
@ccordoba12 I think I have seen this already>

**Comment by Andelous** [comment] 2017-08-16 16:21
The only things I did were: 

- Install Anaconda on Manjaro XFCE Edition (17.0.2) in the same way this tutorial says:
https://docs.continuum.io/anaconda/install/linux

- Run anaconda-navigator from the terminal.

- Click on the launch button under the Spyder logo...

And the error keeps popping out. There is also this line in the terminal, right after I press enter:

```
[angel@XPS-L502X ~]$ anaconda-navigator
libpng warning: iCCP: known incorrect sRGB profile
```

I hope I can get some help. Sorry if my english isn't that good, I ain't a native speaker.
Greetings from Mexico.

**Comment by goanpeca** [comment] 2017-08-16 16:41
@Andelous thanks for the additional information. You can safely ignore 

`libpng warning: iCCP: known incorrect sRGB profile`

**Comment by Andelous** [comment] 2017-08-17 17:11
Hey, I just installed Spyder using pacman package manager, and it ran like a charm.

And more specifically, this version.
https://www.archlinux.org/packages/community/any/spyder3/

To make it work with Anaconda, I added to the PYTHONPATH the folder which contains all of the Anaconda Libraries.

I also changed the default Python interpreter to the one inside the Anaconda folder.

I hope this gives some more clues.

**Comment by goanpeca** [comment] 2017-11-14 20:46
## See issue #3374 for more information on how to fix this issue.**

---

Closing as duplicate of #3374

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-14 20:46 UTC
Labels: pkg:navigator, pkg:spyder, reso:duplicate
