### ISSUE TITLE
Navigator Error An unexpected error occurred on Navigator start-up  5/5/2022 5:54 pm Arizona Time

### ISSUE THREAD

**Issue by naeemahaz** [ContinuumIO/anaconda-issues#12919] opened 2022-05-06 00:54 UTC
Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Naeemah\.continuum\anaconda-client\config.yaml", position 0

It was working this morning.  Come on

**Comment by naeemahaz** [comment] 2022-05-06 07:17
I uninstalled Anaconda and reinstalled it.  It still doesn't work. What's up?

**Comment by csoja** [comment] 2022-05-23 16:17
Sounds like your anaconda-client configuration file got corrupted.  Those configuration files aren't automatically removed when you uninstall and reinstall Anaconda.  If you rename C:\Users\Naeemah.continuum\anaconda-client\config.yaml to C:\Users\Naeemah.continuum\anaconda-client\config.old and restart Navigator, I expect it will fix it.

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 09:39
Duplicate of #12762

**Closed by vshevchenko-anaconda** 2023-07-07 09:39 UTC
Labels: pkg-navigator
