### ISSUE TITLE
`mkl` installed despite specifying `nomkl`

### ISSUE THREAD

**Issue by desilinguist** [ContinuumIO/anaconda-issues#1370] opened 2017-01-18 20:08 UTC
When creating a conda environment using a file, the `defaults` channel keeps wanting to install `mkl-2017.0.1` even though my file explicitly specifies `nomkl`. The file looks like:

```
python>=3.4.3,
numpy=1.11.2
scipy=0.18.1
nomkl
```

Below is the output when I run `conda create -n foo --file packages.txt` with this file. Note however, that if I specify `-c conda-forge`, things work as expected and only `openblas` is installed.

```
Fetching package metadata .........
Solving package specifications: ..........
Warning: 2 possible package resolutions (only showing differing packages):
  - mkl-2017.0.1-0.tar.bz2, numpy-1.11.2-py35_nomkl_0.tar.bz2, openblas-0.2.14-4.tar.bz2, scipy-0.18.1-np111py35_1.tar.bz2
  - mkl-11.3.3-0.tar.bz2, numpy-1.11.2-py35_0.tar.bz2, openblas-0.2.19-0.tar.bz2, scipy-0.18.1-np111py35_nomkl_1.tar.bz2

Package plan for installation in environment /tmp/xxx:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-2017.0.1               |                0       128.2 MB
    python-3.5.0rc4            |                0        25.2 MB
    numpy-1.11.2               |     py35_nomkl_0         6.1 MB
    setuptools-27.2.0          |           py35_0         526 KB
    wheel-0.29.0               |           py35_0          82 KB
    pip-9.0.1                  |           py35_1         1.7 MB
    scipy-0.18.1               |      np111py35_1        31.2 MB
    ------------------------------------------------------------
                                           Total:       193.1 MB

The following NEW packages will be INSTALLED:

    libgfortran: 3.0.0-1            
    mkl:         2017.0.1-0         
    nomkl:       1.0-0              
    numpy:       1.11.2-py35_nomkl_0 [nomkl]
    openblas:    0.2.14-4           
    openssl:     1.0.1k-1           
    pip:         9.0.1-py35_1       
    python:      3.5.0rc4-0          (copy)
    readline:    6.2-2              
    scipy:       0.18.1-np111py35_1 
    setuptools:  27.2.0-py35_0      
    sqlite:      3.13.0-0           
    tk:          8.5.18-0           
    wheel:       0.29.0-py35_0       (copy)
    xz:          5.0.5-1            
    zlib:        1.2.8-3            
```

**Comment by nehaljwani** [comment] 2017-05-18 03:59
Not able to reproduce this with conda 4.3.18 and only defaults channel in .condarc

```bash
(1503) ➜  ~ conda --version
conda 4.3.18
(1503) ➜  ~ cat <<EOF > /tmp/pkgs.txt
python>=3.4.3
numpy=1.11.2
scipy=0.18.1
nomkl
EOF
(1503) ➜  ~ conda create -n 1370 --file /tmp/pkgs.txt
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /Users/nwani/m3/envs/1370:

The following NEW packages will be INSTALLED:

    nomkl:      1.0-0
    numpy:      1.11.2-py36_nomkl_0      [nomkl]
    openssl:    1.0.2k-2
    pip:        9.0.1-py36_1
    python:     3.6.1-2
    readline:   6.2-2
    scipy:      0.18.1-np111py36_nomkl_1 [nomkl]
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1
    zlib:       1.2.8-3

Proceed ([y]/n)?
```

@desilinguist Please share the output for `conda info`

**Comment by nehaljwani** [comment] 2017-06-03 09:17
Closing as this is not reproducible with the latest version of conda.

**Closed by nehaljwani** 2017-06-03 09:17 UTC
Labels: pending:feedback
