### ISSUE TITLE
Anaconda Navigator Won't Download

### ISSUE THREAD

**Issue by yagevlevi** [ContinuumIO/anaconda-issues#11360] opened 2019-10-10 17:57 UTC
### Actual Behavior

Anaconda Navigator won't download on my MacBook Pro after downloading macOS Catalina

### Expected Behavior

It should download

##### Operating System: macOS Catalina
<img width="682" alt="Screen Shot 2019-10-07 at 8 59 22 PM" src="https://user-images.githubusercontent.com/56408687/66593896-e94ef180-eb65-11e9-8fa7-60a6051f65ba.png">

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by forrestwaters** [comment] 2019-10-10 18:04
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/10998
We recommend using the sh installer for now.

**Closed by forrestwaters** 2019-10-10 18:04 UTC

**Comment by yagevlevi** [comment] 2019-10-10 18:05
> Duplicate of #10998
> We recommend using the sh installer for now.

What is the sh installer and where can I find it?

**Comment by forrestwaters** [comment] 2019-10-10 18:23
https://docs.anaconda.com/anaconda/install/mac-os/#using-the-command-line-install

**Comment by csoja** [comment] 2019-10-10 19:02
https://repo.anaconda.com/archive/Anaconda3-2019.07-MacOSX-x86_64.sh
