### ISSUE TITLE
psutil.AccessDenied (pid = 514)

### ISSUE THREAD

**Issue by ceefryingpan** [ContinuumIO/anaconda-issues#3511] opened 2017-07-24 14:05 UTC
Traceback (most recent call last):
File "/Users/charlespan/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/charlespan/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/charlespan/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/charlespan/anaconda/lib/python2.7/site-packages/psutil/__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "/Users/charlespan/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 306, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=514)

**Comment by goanpeca** [comment] 2017-07-24 17:37
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-24 17:37 UTC
