### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by prati2710** [ContinuumIO/anaconda-issues#2007] opened 2017-06-06 18:40 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=4656)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Pratishtha\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Pratishtha\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Pratishtha\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Pratishtha\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Pratishtha\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=4656)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_IN
python: 2.7.13
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-06-08 21:03
Closing as duplicate of #1984

**Closed by goanpeca** 2017-06-08 21:03 UTC
Labels: pkg:navigator, reso:duplicate
