### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by richardkershner** [ContinuumIO/anaconda-issues#10143] opened 2018-10-03 16:18 UTC
## Main error
The following errors occurred:
## Traceback
```
PackagesNotFoundError: The following packages are not available from current channels:

  - rstudio==1.1.423

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```
## System information
```
python: 3.6.4
language: en_US
os: Windows;10;10.0.17134;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.4
```

**Comment by goanpeca** [comment] 2018-10-03 23:08
Closing as duplicate of #6970

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #6970 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-10-03 23:08 UTC
