### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rouenlee29** [ContinuumIO/anaconda-issues#9221] opened 2018-04-23 00:50 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=637)
## Traceback
```
Traceback (most recent call last):
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 348, in catch_zombie
    yield
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 412, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 666, in cmdline
    return self._proc.cmdline()
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 330, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 412, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/Users/rouenlee/anaconda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rouenlee/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 361, in catch_zombie
    raise AccessDenied(proc.pid, proc._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=637)

```
## System information
```
python: 3.6.4
language: en
os: Darwin;16.5.0;Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.9.4
pyqt: 5.9.2
conda: 4.5.1
```

**Comment by goanpeca** [comment] 2018-04-23 00:51
Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #1984 for more information on how to fix this.**

Or you can run on the Terminal or Anaconda prompt:

```
anaconda-navigator --reset
```

**Closed by goanpeca** 2018-04-23 00:51 UTC
Labels: pkg:navigator, reso:duplicate
