### ISSUE TITLE
Anaconda Navigator could not open

### ISSUE THREAD

**Issue by babaknasr** [ContinuumIO/anaconda-issues#4381] opened 2017-08-18 15:44 UTC
I have two Anaconda3 environments. Anaconda navigator corresponding to root environment does open. However Navigator corresponded to second environment  (py35) could not open. Here are the error message bellow:

Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Users\babak\Anaconda3\envs\py35\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-08-18 15:44
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-18 15:44 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by babaknasr** [comment] 2017-08-18 15:48
It is already the latest version (anaconda-navigator 1.6.4), but the problem exists.
