### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by cgbeas** [ContinuumIO/anaconda-issues#9669] opened 2018-06-26 01:43 UTC
Right before this happened my machine crashed while I was working on a Jupyter Notebook which I had opened through the Anaconda Navigator.

## Main error
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
## Traceback
```
Traceback (most recent call last):
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Users/carlosbeas/anaconda/envs/conda3p5/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```
## System information
```
pyqt: 4.11.4
platform: osx-64
conda: 4.5.4
language: en
os: Darwin;17.6.0;Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
python: 3.5.5
qt: 5.6.2
```

**Comment by goanpeca** [comment] 2018-06-26 01:47
Closing as duplicate of #1837

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1837 for more information on how to fix this.**

**Closed by goanpeca** 2018-06-26 01:47 UTC
Labels: pkg:navigator, reso:duplicate
