### ISSUE TITLE
R kernel in Jupyter keeps dying

### ISSUE THREAD

**Issue by dthboyd** [ContinuumIO/anaconda-issues#1617] opened 2017-04-21 08:59 UTC

**Comment by dthboyd** [comment] 2017-04-21 09:00
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
          package cache : //anaconda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-canary/osx-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/davidboyd/.condarc
           offline mode : False

**Comment by dthboyd** [comment] 2017-04-21 09:01
conda list --show-channel-urls
# packages in environment at //anaconda:
#
_license                  1.1                      py35_1    defaults
_nb_ext_conf              0.3.0                    py35_0    defaults
alabaster                 0.7.9                    py35_0    defaults
anaconda                  custom                   py35_0    defaults
anaconda-clean            1.0.0                    py35_0    defaults
anaconda-client           1.5.1                    py35_0    defaults
anaconda-fusion           1.0.2                    py35_0    anaconda-fusion
anaconda-navigator        1.3.1                    py35_0    defaults
anyqt                     0.0.8                    py35_1    conda-forge
aplus                     0.11.0                   py35_0    conda-forge
appnope                   0.1.0                    py35_0    defaults
appscript                 1.0.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astroid                   1.4.7                    py35_0    defaults
astropy                   1.3.2               np111py35_0    conda-forge
babel                     2.3.4                    py35_0    defaults
backports                 1.0                      py35_0    defaults
beautifulsoup4            4.5.1                    py35_0    defaults
bitarray                  0.8.1                    py35_0    defaults
blaze                     0.10.1                   py35_0    defaults
bokeh                     0.12.2                   py35_0    defaults
boto                      2.42.0                   py35_0    defaults
bottleneck                1.1.0               np111py35_0    defaults
cachetools                2.0.0                    py35_0    conda-forge
cairo                     1.14.8                        0    defaults
cffi                      1.7.0                    py35_0    defaults
chardet                   2.3.0                    py35_0    conda-forge
chest                     0.2.3                    py35_0    defaults
click                     6.6                      py35_0    defaults
cloudpickle               0.2.1                    py35_0    defaults
clyent                    1.2.2                    py35_0    defaults
colorama                  0.3.7                    py35_0    defaults
conda                     4.2.13                   py35_0    conda-forge
conda-build               2.0.2                    py35_0    defaults
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py35_0    defaults
contextlib2               0.5.3                    py35_0    defaults
cryptography              1.5                      py35_0    defaults
curl                      7.49.0                        1    defaults
cycler                    0.10.0                   py35_0    defaults
cython                    0.24.1                   py35_0    defaults
cytoolz                   0.8.0                    py35_0    defaults
dask                      0.11.0                   py35_0    defaults
datashape                 0.5.2                    py35_0    defaults
decorator                 4.0.10                   py35_0    defaults
dill                      0.2.5                    py35_0    defaults
docutils                  0.12                     py35_2    defaults
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.2                    py35_0    defaults
et_xmlfile                1.0.1                    py35_0    defaults
fastcache                 1.0.2                    py35_1    defaults
filelock                  2.0.6                    py35_0    defaults
flask                     0.11.1                   py35_0    defaults
flask-cors                2.1.2                    py35_0    defaults
fontconfig                2.12.1                        3    defaults
freetype                  2.5.5                         1    defaults
future                    0.16.0                   py35_0    conda-forge
futures                   3.0.3                    py35_0    defaults
get_terminal_size         1.0.0                    py35_0    defaults
gettext                   0.19.7                        1    conda-forge
gevent                    1.1.2                    py35_0    defaults
glib                      2.50.2                        1    defaults
glue-core                 0.10.2                   py35_1    conda-forge
glue-vispy-viewers        0.7.2                    py35_1    conda-forge
glueviz                   0.10.2                        0    conda-forge
greenlet                  0.4.10                   py35_0    defaults
gsl                       2.2.1                         1    conda-forge
h5py                      2.6.0               np111py35_2    defaults
harfbuzz                  0.9.39                        2    defaults
hdf5                      1.8.17                        1    defaults
healpy                    1.9.1               np111py35_0    conda-forge
heapdict                  1.0.0                    py35_1    defaults
icu                       54.1                          0    defaults
idna                      2.1                      py35_0    defaults
imagesize                 0.7.1                    py35_0    defaults
ipykernel                 4.5.0                    py35_0    defaults
ipython                   5.1.0                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                5.2.2                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py35_1    defaults
jedi                      0.9.0                    py35_1    defaults
jinja2                    2.8                      py35_1    defaults
joblib                    0.11                     py35_0    conda-forge
jpeg                      8d                            2    defaults
jsonschema                2.5.1                    py35_0    defaults
jupyter                   1.0.0                    py35_3    defaults
jupyter_client            4.4.0                    py35_0    defaults
jupyter_console           5.0.0                    py35_0    defaults
jupyter_core              4.2.0                    py35_0    defaults
kapteyn                   2.3                 np111py35_0    conda-forge
keyring                   9.0                      py35_0    conda-forge
keyrings.alt              1.2                      py35_0    conda-forge
lazy-object-proxy         1.2.1                    py35_0    defaults
libdynd                   0.7.2                         0    defaults
libffi                    3.2.1                         3    conda-forge
libgcc                    4.8.5                         1    defaults
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        2    defaults
llvmlite                  0.13.0                   py35_0    defaults
locket                    0.2.0                    py35_1    defaults
lxml                      3.6.4                    py35_0    defaults
markupsafe                0.23                     py35_2    defaults
matplotlib                1.5.3               np111py35_0    defaults
mistune                   0.7.3                    py35_1    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py35_2    defaults
mpld3                     0.3                       <pip>
mpmath                    0.19                     py35_1    defaults
multipledispatch          0.4.8                    py35_0    defaults
nb_anacondacloud          1.2.0                    py35_0    defaults
nb_conda                  2.0.0                    py35_0    defaults
nb_conda_kernels          2.0.0                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbformat                  4.1.0                    py35_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py35_0    defaults
nltk                      3.2.1                    py35_0    defaults
nose                      1.3.7                    py35_1    defaults
notebook                  4.2.3                    py35_0    defaults
numba                     0.28.1              np111py35_0    defaults
numexpr                   2.6.1               np111py35_0    defaults
numpy                     1.11.1                   py35_0    defaults
odo                       0.5.0                    py35_1    defaults
openpyxl                  2.3.2                    py35_0    defaults
openssl                   1.0.2j                        0    defaults
orange3                   3.4.1               np111py35_0    conda-forge
pandas                    0.18.1              np111py35_0    defaults
pandoc                    1.19.2                        0    conda-forge
pango                     1.40.3                        1    defaults
partd                     0.3.6                    py35_0    defaults
path.py                   8.2.1                    py35_0    defaults
pathlib2                  2.1.0                    py35_0    defaults
patsy                     0.4.1                    py35_0    defaults
pcre                      8.39                          0    conda-forge
pep8                      1.7.0                    py35_0    defaults
pexpect                   4.0.1                    py35_0    defaults
pickleshare               0.7.4                    py35_0    defaults
pillow                    3.3.1                    py35_0    defaults
pip                       8.1.2                    py35_0    defaults
pip                       9.0.1                     <pip>
pixiedust                 1.0.2                     <pip>
pixman                    0.34.0                        0    conda-forge
pkginfo                   1.3.2                    py35_0    defaults
plotly                    2.0.5                    py35_0    conda-forge
ply                       3.9                      py35_0    defaults
progressbar2              3.10.1                   py35_1    conda-forge
prompt_toolkit            1.0.3                    py35_0    defaults
psutil                    4.3.1                    py35_0    defaults
ptyprocess                0.5.1                    py35_0    defaults
py                        1.4.31                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.14                     py35_1    defaults
pycrypto                  2.6.1                    py35_4    defaults
pycurl                    7.43.0                   py35_0    defaults
pyflakes                  1.3.0                    py35_0    defaults
pygments                  2.1.3                    py35_0    defaults
pylint                    1.5.4                    py35_1    defaults
pyopengl                  3.1.0                    py35_0    conda-forge
pyopenssl                 16.2.0                   py35_0    defaults
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      5.6.0                    py35_0    defaults
pyqtgraph                 0.10.0                   py35_2    conda-forge
pytables                  3.2.3.1             np111py35_0    defaults
pytest                    2.9.2                    py35_0    defaults
pytest-runner             2.11.1                   py35_0    conda-forge
python                    3.5.2                         0    defaults
python-dateutil           2.5.3                    py35_0    defaults
python-utils              2.0.0                    py35_0    conda-forge
python.app                1.2                      py35_4    defaults
pytz                      2016.6.1                 py35_0    defaults
pyyaml                    3.12                     py35_0    defaults
pyzmq                     15.4.0                   py35_0    defaults
qt                        5.6.0                         0    defaults
qtawesome                 0.3.3                    py35_0    defaults
qtconsole                 4.2.1                    py35_1    defaults
qtpy                      1.1.2                    py35_0    defaults
r                         3.3.2                  r3.3.2_0    conda-forge
r-assertthat              0.1                    r3.3.2_4    r
r-backports               1.0.4                  r3.3.2_0    r
r-base                    3.3.2                         1    conda-forge
r-base64enc               0.1_3                  r3.3.2_0    r
r-bh                      1.62.0_1               r3.3.2_0    r
r-bitops                  1.0_6                  r3.3.2_2    r
r-boot                    1.3_18                 r3.3.2_0    conda-forge
r-broom                   0.4.1                  r3.3.2_0    r
r-car                     2.1_4                  r3.3.2_0    r
r-caret                   6.0_73                 r3.3.2_0    r
r-catools                 1.17.1                 r3.3.2_2    r
r-class                   7.3_14                 r3.3.2_0    conda-forge
r-cluster                 2.0.6                  r3.3.2_0    conda-forge
r-codetools               0.2_15                 r3.3.2_0    conda-forge
r-colorspace              1.3_1                  r3.3.2_0    r
r-crayon                  1.3.2                  r3.3.2_0    r
r-curl                    2.3                    r3.3.2_0    r
r-data.table              1.10.0                 r3.3.2_0    r
r-dbi                     0.5_1                  r3.3.2_0    r
r-dichromat               2.0_0                  r3.3.2_2    r
r-digest                  0.6.10                 r3.3.2_0    r
r-dplyr                   0.5.0                  r3.3.2_0    r
r-essentials              1.5.2                  r3.3.2_0    r
r-evaluate                0.10                   r3.3.2_0    r
r-forcats                 0.1.1                  r3.3.2_0    r
r-foreach                 1.4.3                  r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    conda-forge
r-formatr                 1.4                    r3.3.2_0    r
r-ggplot2                 2.2.0                  r3.3.2_0    r
r-gistr                   0.3.6                  r3.3.2_0    r
r-glmnet                  2.0_5                  r3.3.2_0    r
r-gtable                  0.2.0                  r3.3.2_0    r
r-haven                   1.0.0                  r3.3.2_0    r
r-hexbin                  1.27.1                 r3.3.2_0    r
r-highr                   0.6                    r3.3.2_0    r
r-hms                     0.3                    r3.3.2_0    r
r-htmltools               0.3.5                  r3.3.2_0    r
r-htmlwidgets             0.8                    r3.3.2_0    r
r-httpuv                  1.3.3                  r3.3.2_0    r
r-httr                    1.2.1                  r3.3.2_0    r
r-irdisplay               0.4.4                  r3.3.2_0    r
r-irkernel                0.7.1                  r3.3.2_0    r
r-iterators               1.0.8                  r3.3.2_0    r
r-jsonlite                1.1                    r3.3.2_0    r
r-kernsmooth              2.23_15                r3.3.2_0    conda-forge
r-knitr                   1.15.1                 r3.3.2_0    r
r-labeling                0.3                    r3.3.2_2    r
r-lattice                 0.20_34                r3.3.2_0    conda-forge
r-lazyeval                0.2.0                  r3.3.2_0    r
r-lme4                    1.1_12                 r3.3.2_0    r
r-lubridate               1.6.0                  r3.3.2_0    r
r-magrittr                1.5                    r3.3.2_2    r
r-maps                    3.1.1                  r3.3.2_0    r
r-markdown                0.7.7                  r3.3.2_2    r
r-mass                    7.3_45                 r3.3.2_0    conda-forge
r-matrix                  1.2_7.1                r3.3.2_0    conda-forge
r-matrixmodels            0.4_1                  r3.3.2_0    r
r-mgcv                    1.8_17                 r3.3.2_0    conda-forge
r-mime                    0.5                    r3.3.2_0    r
r-minqa                   1.2.4                  r3.3.2_2    r
r-mnormt                  1.5_5                  r3.3.2_0    r
r-modelmetrics            1.1.0                  r3.3.2_0    r
r-modelr                  0.1.0                  r3.3.2_0    r
r-munsell                 0.4.3                  r3.3.2_0    r
r-nlme                    3.1_131                r3.3.2_0    conda-forge
r-nloptr                  1.0.4                  r3.3.2_2    r
r-nnet                    7.3_12                 r3.3.2_0    conda-forge
r-openssl                 0.9.5                  r3.3.2_0    r
r-pbdzmq                  0.2_4                  r3.3.2_0    r
r-pbkrtest                0.4_6                  r3.3.2_0    r
r-plyr                    1.8.4                  r3.3.2_0    r
r-pryr                    0.1.2                  r3.3.2_0    r
r-psych                   1.6.9                  r3.3.2_0    r
r-purrr                   0.2.2                  r3.3.2_0    r
r-quantmod                0.4_7                  r3.3.2_0    r
r-quantreg                5.29                   r3.3.2_0    r
r-r6                      2.2.0                  r3.3.2_0    r
r-randomforest            4.6_12                 r3.3.2_0    r
r-rbokeh                  0.5.0                  r3.3.2_0    r
r-rcolorbrewer            1.1_2                  r3.3.2_3    r
r-rcpp                    0.12.8                 r3.3.2_0    r
r-rcppeigen               0.3.2.9.0              r3.3.2_0    r
r-readr                   1.0.0                  r3.3.2_0    r
r-readxl                  0.1.1                  r3.3.2_0    r
r-recommended             3.3.2                  r3.3.2_0    conda-forge
r-repr                    0.10                   r3.3.2_0    r
r-reshape2                1.4.2                  r3.3.2_0    r
r-rmarkdown               1.3                    r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    conda-forge
r-rprojroot               1.1                    r3.3.2_0    r
r-rvest                   0.3.2                  r3.3.2_0    r
r-scales                  0.4.1                  r3.3.2_0    r
r-selectr                 0.3_0                  r3.3.2_0    r
r-shiny                   0.14.2                 r3.3.2_0    r
r-sourcetools             0.1.5                  r3.3.2_0    r
r-sparsem                 1.74                   r3.3.2_0    r
r-spatial                 7.3_11                 r3.3.2_0    conda-forge
r-stringi                 1.1.2                  r3.3.2_0    r
r-stringr                 1.1.0                  r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    conda-forge
r-tibble                  1.2                    r3.3.2_0    r
r-tidyr                   0.6.0                  r3.3.2_0    r
r-tidyverse               1.0.0                  r3.3.2_0    r
r-ttr                     0.23_1                 r3.3.2_0    r
r-uuid                    0.1_2                  r3.3.2_0    r
r-xml2                    1.0.0                  r3.3.2_0    r
r-xtable                  1.8_2                  r3.3.2_0    r
r-xts                     0.9_7                  r3.3.2_2    r
r-yaml                    2.1.14                 r3.3.2_0    r
r-zoo                     1.7_13                 r3.3.2_0    r
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py35_0    defaults
requests                  2.13.0                   py35_0    defaults
rope                      0.9.4                    py35_1    defaults
ruamel_yaml               0.11.14                  py35_0    defaults
scikit-image              0.12.3              np111py35_1    defaults
scikit-learn              0.18.1              np111py35_0    defaults
scipy                     0.18.1              np111py35_0    defaults
seaborn                   0.7.1                    py35_0    conda-forge
setuptools                27.2.0                   py35_0    defaults
simplegeneric             0.8.1                    py35_1    defaults
singledispatch            3.4.0.3                  py35_0    defaults
sip                       4.18                     py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.4.6                    py35_0    defaults
spyder                    3.0.0                    py35_0    defaults
sqlalchemy                1.0.13                   py35_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.6.1               np111py35_1    defaults
swampy                    2.1.7                     <pip>
sympy                     1.0                      py35_0    defaults
terminado                 0.6                      py35_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py35_0    defaults
tornado                   4.4.1                    py35_0    defaults
traitlets                 4.3.0                    py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
vaex                      1.0.0b6                  py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    defaults
werkzeug                  0.11.11                  py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        1.2.6                    py35_0    defaults
wrapt                     1.10.6                   py35_0    defaults
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.3                    py35_0    defaults
xlwings                   0.10.0                   py35_0    defaults
xlwt                      1.1.2                    py35_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         3    defaults

**Comment by mingwandroid** [comment] 2017-04-21 09:11
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1614, please read https://github.com/ContinuumIO/anaconda-issues/issues/1614#issuecomment-295977083

**Closed by mingwandroid** 2017-04-21 09:11 UTC
