### ISSUE TITLE
Error happen on my mac app.

### ISSUE THREAD

**Issue by xrstuart** [ContinuumIO/anaconda-issues#714] opened 2016-03-20 08:19 UTC
SyntaxError: Unexpected token <

Please help me to solve this out. Thank you.

**Comment by nehaljwani** [comment] 2017-05-19 20:09
@xrstuart Where do you see this error? Would it be possible for you to share a screenshot?

**Comment by nehaljwani** [comment] 2017-05-21 06:35
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/350

**Closed by nehaljwani** 2017-05-21 06:35 UTC
Labels: pending:feedback, reso:duplicate
