### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by A-Fisk** [ContinuumIO/anaconda-issues#9371] opened 2018-05-12 18:44 UTC
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "//anaconda/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "//anaconda/lib/python3.5/site-packages/jupyterlab/labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "//anaconda/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "//anaconda/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
os: Darwin;17.5.0;Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64;x86_64;i386
platform: osx-64
language: en
qt: 5.6.2
pyqt: 5.6.0
version: 1.6.2
python: 3.5.5
conda: 4.5.2
```

**Comment by goanpeca** [comment] 2018-05-14 13:50
Closing as duplicate of #8216

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8216 for more information on how to fix this issue.**

Or try running

```
conda upgrade jupyter_core
```

**Closed by goanpeca** 2018-05-14 13:50 UTC
