### ISSUE TITLE
unlable to open anaconda navigator

### ISSUE THREAD

**Issue by pjnani12** [ContinuumIO/anaconda-issues#7053] opened 2017-11-01 19:38 UTC
![screenshot 29](https://user-images.githubusercontent.com/32244363/32293804-50f8414e-bf6a-11e7-91e3-37726cca7808.png)

**Comment by goanpeca** [comment] 2017-11-01 19:52
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

Also make sure you install Anaconda for the `current user` and not `All users` and also ensure only ascii characters are used.

**Closed by goanpeca** 2017-11-01 19:52 UTC
