### ISSUE TITLE
Navigator Error in startup

### ISSUE THREAD

**Issue by hlastro** [ContinuumIO/anaconda-issues#8998] opened 2018-03-25 14:32 UTC
### Actual Behavior

An unexpected error occurred on Navigator start-up

### Expected Behavior

Start up navigator

### Steps to Reproduce       

Click on Navigator symbol

 Click on  Navigator or try executing via terminal

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/hl/Library/Application Support/binstar/config.yaml", line 1, column 1
```

**Comment by goanpeca** [comment] 2018-03-26 16:30
Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.11
```

**Closed by goanpeca** 2018-03-26 16:30 UTC

**Comment by hlastro** [comment] 2018-03-27 02:52
Thank you so much!  That worked perfectly.
