### ISSUE TITLE
Navigator Error (crash)

### ISSUE THREAD

**Issue by moonbase3** [ContinuumIO/anaconda-issues#5408] opened 2017-09-12 17:36 UTC
I have been using Anaconda with Jetbrains Pycharm and it automatically updates all the modules so that may have caused the problem. It repeats. i tried installing it again but to no avail.

[Navigator Error.html.txt](https://github.com/ContinuumIO/anaconda-issues/files/1296854/Navigator.Error.html.txt)

**Comment by goanpeca** [comment] 2017-09-12 21:21
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-12 21:21 UTC
