### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by teejayvee** [ContinuumIO/anaconda-issues#8414] opened 2018-02-02 22:35 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://conda.anaconda.org/gurobi/osx-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPConnectionPool(host='conda.anaconda.org', port=80): Max retries exceeded with url: /gurobi/osx-64/repodata.json (Caused by ProtocolError('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known')))",),)

```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.4.0;Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment] 2018-02-02 22:39
Closing as duplicate of #1932

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1932 for more information on how to fix this.**

**Closed by goanpeca** 2018-02-02 22:39 UTC
Labels: pkg:navigator, reso:duplicate
