### ISSUE TITLE
Anaconda3:5.0.0  unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory

### ISSUE THREAD

**Issue by virtualluke** [ContinuumIO/anaconda-issues#6232] opened 2017-09-29 03:05 UTC
I just installed Anaconda3, 5.0.0. on my system (x86_64 centos 7.3).  I went to install python-snappy and get the below error.  I have tried a few other packages and some install/build correctly and others have this same error as below.  (the system is not connected to the internet so it takes a little work to move files over to install, FYI).  This same install had no issues with Anaconda 4.4.0 on this system. I added the Anaconda3 bin path to the beginning of my PATH also (in case that is relevant).

thanks,
Luke

$ /home/user/anaconda3/bin/pip install /tmp/python-snappy-0.5.1.tar.gz
Processing /tmp/python-snappy-0.5.1.tar.gz
Building wheels for collected packages: python-snappy
  Running setup.py bdist_wheel for python-snappy ... error
  Complete output from command /home/user/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-eoc1f5ey-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpky39290upip-wheel- --python-tag cp36:
  WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
  running bdist_wheel
  running build
  running build_py
  package init file '__init__.py' not found (or not a regular file)
  creating build
  creating build/lib.linux-x86_64-3.6
  copying setup.py -> build/lib.linux-x86_64-3.6
  copying snappy.py -> build/lib.linux-x86_64-3.6
  copying snappy_cffi.py -> build/lib.linux-x86_64-3.6
  copying test_snappy.py -> build/lib.linux-x86_64-3.6
  copying test_snappy_cffi.py -> build/lib.linux-x86_64-3.6
  running build_ext
  building '_snappy' extension
  creating build/temp.linux-x86_64-3.6
  x86_64-conda_cos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -I/home/user/anaconda3/include/python3.6m -c snappymodule.cc -o build/temp.linux-x86_64-3.6/snappymodule.o
  unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1

**Comment by jskksj** [comment] 2017-09-29 03:25
Anaconda2-5.0.0-Linux-x86_64 gives me the same error:
    error: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
when running 'pip install kivy' in Linux Mint.

Anaconda2-4.4.0-Linux-x86_64 installs kivy without error.

It seems to be related to this discussion: https://stackoverflow.com/questions/46450912/unable-to-execute-x86-64-conda-cos6-linux-gnu-gcc-no-such-file-or-directory

**Comment by msarahan** [comment] 2017-09-29 05:06
Duplicate of https://github.com/conda/conda/issues/6030 - closing to consolidate discussion there.

**Closed by msarahan** 2017-09-29 05:06 UTC

**Comment by msarahan** [comment] 2017-09-30 16:08
Both of these builds now fail for other reasons - due to missing dependencies.  Snappy looks like:

```
  gcc -pthread -B /opt/conda/bin -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python2.7 -c snappymodule.cc -o build/temp.linux-x86_64-2.7/snappymodule.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  snappymodule.cc:31:22: fatal error: snappy-c.h: No such file or directory
   #include <snappy-c.h>
                        ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
```

while kivy looks like:

```
    WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

    Package sdl2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `sdl2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'sdl2' found
    Package SDL2_ttf was not found in the pkg-config search path.
    Perhaps you should add the directory containing `SDL2_ttf.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'SDL2_ttf' found
    Package SDL2_image was not found in the pkg-config search path.
    Perhaps you should add the directory containing `SDL2_image.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'SDL2_image' found
    Package SDL2_mixer was not found in the pkg-config search path.
    Perhaps you should add the directory containing `SDL2_mixer.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'SDL2_mixer' found    WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

    Package sdl2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `sdl2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'sdl2' found
    Package SDL2_ttf was not found in the pkg-config search path.
    Perhaps you should add the directory containing `SDL2_ttf.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'SDL2_ttf' found
    Package SDL2_image was not found in the pkg-config search path.
    Perhaps you should add the directory containing `SDL2_image.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'SDL2_image' found
    Package SDL2_mixer was not found in the pkg-config search path.
    Perhaps you should add the directory containing `SDL2_mixer.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'SDL2_mixer' found
```

Providing dependencies is outside the scope of this issue.  I really highly recommend using conda packages for snappy: ``conda install snappy``

Kivy is more complicated.  If you install sdl2-devel or something like that on linux-mint, it should build for you.  Unfortunately, it does not look like anyone has current conda packages for kivy.  Conda-forge does have sdl2 packages, so you may be able to submit a conda-forge recipe for kivy to improve the situation.

**Comment by kmsravindra** [comment] 2018-05-09 06:26
I got this error on Ubuntu on paperspace. I could solve it using the command - 
conda install gxx_linux-64

Hope it will be useful for someone

**Comment by hamidkarimi** [comment] 2018-12-27 21:52
> I got this error on Ubuntu on paperspace. I could solve it using the command -
> conda install gxx_linux-64
> 
> Hope it will be useful for someone

It worked for me. Thank you so much

**Comment by sajastu** [comment] 2020-04-09 15:42
Same issue here. Could anyone work around this? Even `conda install gxx_linux-64` not worked me, which seems to be the mostly-accepted one for people...

**Comment by gocoee** [comment] 2020-06-12 03:20
sudo ln -sf /usr/bin/gcc /usr/bin/x86_64-conda_cos6-linux-gnu-gcc

**Comment by kxgong** [comment] 2023-12-10 05:06
> I got this error on Ubuntu on paperspace. I could solve it using the command - conda install gxx_linux-64
> 
> Hope it will be useful for someone

This solved my problem. Thank you!
