### ISSUE TITLE
repo.continuum.io flaky

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/anaconda-issues#11397] opened 2019-10-24 16:40 UTC
Recently we have been seeing quite a number of failed downloads from `repo.continuum.io`, especially on Travis CI.
```
2019-10-24 16:27:59 URL:https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh [70489432/70489432] -> "miniconda.sh" [1]

PREFIX=/home/travis/miniconda

Unpacking payload ...

  0%|          | 0/35 [00:00<?, ?it/s]

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

**Comment by forrestwaters** [comment] 2019-10-24 18:27
Looks like this may be the same issue described in https://github.com/conda/conda/issues/9345 .

**Comment by msarahan** [comment] 2019-10-24 18:29
Yes, closing as duplicate of https://github.com/conda/conda/issues/9345

We are working on addressing the issue and will upload new installers soon.  Closing to consolidate discussion at the conda issue.

**Closed by msarahan** 2019-10-24 18:29 UTC
