### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Jorge-Alberto** [ContinuumIO/anaconda-issues#2053] opened 2017-06-07 19:54 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda3"

```
## System information
```
python: 3.6.1
language: es_MX
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-06-08 21:19
Closing as duplicate of #1845

**Closed by goanpeca** 2017-06-08 21:19 UTC
Labels: pkg:navigator
