### ISSUE TITLE
CondaHttpError when trying to update Navigator

### ISSUE THREAD

**Issue by masumshaikh** [ContinuumIO/anaconda-issues#3321] opened 2017-07-19 09:20 UTC
## Description of error
CondaHttpError when trying to update Navigator via console. (Note that I do not have an "Update Navigator" button in top right of the Navigator. Trying to attempt the following:

conda update anaconda-navigator

## Output from console:
```
c:\Anaconda3\Scripts>conda update anaconda-navigator
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005524F28>, 'Connection to repo.continuum.io timed out
. (connect timeout=9.15)'))",),)
```

**Comment by goanpeca** [comment] 2017-07-19 09:20
Closing as duplicate of #1932

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Comment by masumshaikh** [comment] 2017-07-19 09:21
Related to: https://github.com/ContinuumIO/anaconda-issues/issues/3319

**Closed by goanpeca** 2017-07-19 09:20 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by masumshaikh** [comment] 2017-07-19 09:23
I was told to execute "conda update anaconda-navigator" as a solution to #3319, but this proposed solution suffers from the same problem.

**Comment by masumshaikh** [comment] 2017-07-19 09:23
@goanpeca would you mind checking if this really is a duplicate? Thanks.

**Comment by masumshaikh** [comment] 2017-07-20 09:31
For anyone else who comes across this page, turned out to be because I was behind a corporate proxy. Oops. Solution was to use CNTLM.
