### ISSUE TITLE
Ruby config references non-existent /tmp/build

### ISSUE THREAD

**Issue by vbraun** [ContinuumIO/anaconda-issues#10547] opened 2019-01-25 09:23 UTC
### Actual Behavior

Building native ruby extensions fails with (in the mkmf.log):
~~~~
sh: /home/conda/feedstock_root/build_artifacts/ruby_1537084490905/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc: No such file or directory
~~~~
Note: I don't have a /home/conda directory

### Expected Behavior

Building native extensions should work. The ruby configuration in `/path/to/conda/lib/ruby/2.4.0/x86_64-linux/rbconfig.rb` shouldn't contain things like
~~~~
tools/lib/ruby/2.4.0/x86_64-linux/rbconfig.rb:  CONFIG["CXX"] = "/home/conda/feedstock_root/build_artifacts/ruby_1537084490905/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++"
tools/lib/ruby/2.4.0/x86_64-linux/rbconfig.rb:  CONFIG["CC"] = "/home/conda/feedstock_root/build_artifacts/ruby_1537084490905/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc"
~~~~

### Steps to Reproduce

Install conda + ruby, then run 
~~~
/path/to/conda/bin/gem install ffi
~~~

##### Anaconda or Miniconda version:

conda 4.5.12

##### Operating System:

Fedora 29 x86_64

##### `conda info`
```
$ /home/vbraun/Talque-2/tools/bootstrap/miniconda/bin/conda info

     active environment : None
       user config file : /home/vbraun/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.6.0.final.0
       base environment : /home/vbraun/Talque-2/tools/bootstrap/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/vbraun/Talque-2/tools/bootstrap/miniconda/pkgs
                          /home/vbraun/.conda/pkgs
       envs directories : /home/vbraun/Talque-2/tools/bootstrap/miniconda/envs
                          /home/vbraun/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.12.4 CPython/3.6.0 Linux/4.19.13-300.fc29.x86_64 fedora/29 glibc/2.28
                UID:GID : 1000:1000
             netrc file : /home/vbraun/.netrc
           offline mode : False
```

##### `conda list --show-channel-urls`
```
$ /home/vbraun/Talque-2/tools/bootstrap/miniconda/bin/conda list --show-channel-urls
# packages in environment at /home/vbraun/Talque-2/tools/bootstrap/miniconda:
#
# Name                    Version                   Build  Channel
cffi                      1.9.1                    py36_0    defaults
conda                     4.5.12                py36_1000    conda-forge
conda-env                 2.6.0                         1    conda-forge
cryptography              1.7.1                    py36_0    defaults
idna                      2.2                      py36_0    defaults
libffi                    3.2.1                         1    defaults
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
nodejs                    10.12.0              hfc679d8_0    conda-forge
openssl                   1.0.2k                        1    defaults
pip                       9.0.1                    py36_1    defaults
pyasn1                    0.1.9                    py36_0    defaults
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.17                     py36_0    defaults
pyopenssl                 16.2.0                   py36_0    defaults
python                    3.6.0                         0    defaults
readline                  6.2                           2    defaults
requests                  2.12.4                   py36_0    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
setuptools                27.2.0                   py36_0    defaults
six                       1.10.0                   py36_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py36_0    defaults
xz                        5.2.2                         1    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         3    defaults
```

**Comment by vbraun** [comment] 2019-01-25 10:21
This seems to be a conda-forge issue, I've raised https://github.com/conda-forge/ruby-feedstock/issues/14

However, the same issue exists with the anaconda ruby package except that the offending path is /tmp/build and not /home/conda/feedstock_root
~~~
sh: /tmp/build/80754af9/ruby_1540331260710/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc: No such file or directory
~~~

**Comment by nehaljwani** [comment] 2019-02-14 05:07
@mingwandroid How would you suggest to fix this? A side (probably related) question: Should compilers be a dependency for the ruby package?

**Comment by nehaljwani** [comment] 2019-02-14 05:25
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/9863

**Closed by nehaljwani** 2019-02-14 05:25 UTC
