### ISSUE TITLE
gdal 2.0.0 broken on windows

### ISSUE THREAD

**Issue by jorisvandenbossche** [ContinuumIO/anaconda-issues#400] opened 2015-08-05 15:10 UTC
Related to #295

But if I do a fresh install of `gdal` on Windows in a new env, it fails to import with 

```
>>> import gdal
ImportError: DLL load failed: The application has failed to start because its si
de-by-side configuration is incorrect. Please see the application event log or u
se the command-line sxstrace.exe tool for more detail.
```

Full log:

```
C:\Users\vdbosscj>conda create -n test-gdal python gdal
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda\envs\test-gdal:

The following NEW packages will be INSTALLED:

    curl:       7.43.0-1
    gdal:       2.0.0-np19py27_0
    hdf5:       1.8.15.1-2
    krb5:       1.13.2-0
    libgdal:    2.0.0-0
    libnetcdf:  4.3.3.1-2
    numpy:      1.9.2-py27_0
    pip:        7.1.0-py27_0
    python:     2.7.10-0
    setuptools: 18.0.1-py27_0
    zlib:       1.2.8-0

Proceed ([y]/n)?

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate test-gdal
#

C:\Users\vdbosscj>activate test-gdal
Activating environment "test-gdal"...

[test-gdal] C:\Users\vdbosscj>python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 16:44:52) [MSC
v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\envs\test-gdal\lib\site-packages\gdal.py", line 2, in <modul
e>
    from osgeo.gdal import deprecation_warn
  File "C:\Anaconda\envs\test-gdal\lib\site-packages\osgeo\__init__.py", line 25
, in <module>
    _gdal = swig_import_helper()
  File "C:\Anaconda\envs\test-gdal\lib\site-packages\osgeo\__init__.py", line 21
, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The application has failed to start because its si
de-by-side configuration is incorrect. Please see the application event log or u
se the command-line sxstrace.exe tool for more detail.
>>>
```

**Comment by jorisvandenbossche** [comment] 2015-08-05 15:13
Downgrading to 1.11.2 fixes it. So it seems that the error from #295 which was fixed for the 1.x series, is again present in 2.0.0

```
[test-gdal] C:\Users\vdbosscj>conda install gdal=1.11.2
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda\envs\test-gdal:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgdal-1.11.2             |                2         4.8 MB
    gdal-1.11.2                |       np19py27_4         339 KB
    ------------------------------------------------------------
                                           Total:         5.1 MB

The following packages will be DOWNGRADED:

    gdal:    2.0.0-np19py27_0 --> 1.11.2-np19py27_4
    libgdal: 2.0.0-0          --> 1.11.2-2

Proceed ([y]/n)?

Fetching packages ...
libgdal-1.11.2 100% |###############################| Time: 0:00:02   2.30 MB/s
gdal-1.11.2-np 100% |###############################| Time: 0:00:00 466.43 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

[test-gdal] C:\Users\vdbosscj>python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 16:44:52) [MSC
v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import gdal
>>>
```

**Comment by jedfrechette** [comment] 2015-08-06 17:04
The binaries (e.g. gdalinfo) that ship with gdal 2.0 are also broken, failing to start with error 0xc0150002. Running Dependency Walker on gdalinfo indicates that it can't find MSVCR90.DLL. 

Downgrading to 1.11.2 also fixes this issue.

**Comment by groutr** [comment] 2015-08-06 18:16
MSVCR90.dll is part of the Microsoft Visual C++ 2008 redistributable package.
https://www.microsoft.com/en-us/download/details.aspx?id=2092

**Comment by jedfrechette** [comment] 2015-08-06 18:37
Oops, I mistyped in my original comment. It isn't 90.dll that is missing it is 90d.dll, i.e. it looks like a debug build got published.--Jed Frechette                                                                                                                                                                                                                From: Ryan GroutSent: Thursday, August 6, 2015 12:16To: ContinuumIO/anaconda-issuesReply To: ContinuumIO/anaconda-issuesCc: jedfrechetteSubject: Re: [anaconda-issues] gdal 2.0.0 broken on windows (#400)MSVCR90.dll is part of the Microsoft Visual C++ 2008 redistributable package.
https://www.microsoft.com/en-us/download/details.aspx?id=2092

—Reply to this email directly or view it on GitHub.

**Comment by phme** [comment] 2015-09-26 21:33
Same issue here, is there a workaround? Downgrading is not an option for me, I need gdal >= 1.8.

**Comment by omad** [comment] 2015-11-01 23:39
Same issue here, downgrading to 1.11.2 got things working again.

**Comment by jdmcbr** [comment] 2015-11-17 16:59
I also see this issue in Python 2.7 or 3.4, and have, like others, had to downgrad to gdal 1.11.2 to get things working.

**Comment by jhamman** [comment] 2016-03-10 22:12
I don't think this issue is unique to windows.  I'm also getting it on OSX.

**Comment by h4k1m0u** [comment] 2016-05-30 16:59
Downgraded to `gdal 1.11.1` as well, due to the same problem encoutered with `Python 2.7.11`, `Conda 4.0.7` on `Window 8 (64 bits)`.

**Comment by nehaljwani** [comment] 2017-05-21 12:31
Looks like this was fixed? I am not able to reproduce this.

```cmd
(400t) nwani@winbuilder C:\Users\nwani>conda list
# packages in environment at C:\Users\nwani\Anaconda2\envs\400t:
#
curl                      7.43.0                        1
gdal                      2.0.0                np19py27_0
hdf5                      1.8.15.1                      2
krb5                      1.13.2                        0
libgdal                   2.0.0                         0
libnetcdf                 4.3.3.1                       2
numpy                     1.9.2                    py27_0
pip                       7.1.0                    py27_0
python                    2.7.10                        0
setuptools                18.0.1                   py27_0
zlib                      1.2.8                         0

(400t) nwani@winbuilder C:\Users\nwani>python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import gdal
>>> exit()
```

**Comment by nehaljwani** [comment] 2017-05-21 12:32
Closing as it seems the problem has been fixed. Please re-open if you feel otherwise.

**Closed by nehaljwani** 2017-05-21 12:32 UTC
Labels: os:windows
