### ISSUE TITLE
Launching Conda Navigator: charmap codec error

### ISSUE THREAD

**Issue by israasalah90** [ContinuumIO/anaconda-issues#13190] opened 2023-05-07 16:05 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

Can't launch Conda Navigator on Windows. 
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Error:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'charmap' codec can't decode byte 0x81 in position 69: character maps to 
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\ProgramData\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 215, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "C:\ProgramData\anaconda3\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 76, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "C:\ProgramData\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 311, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\ProgramData\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 300, in load_file_configs
    raw_data = collections.OrderedDict(
  File "C:\ProgramData\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 300, in 
    raw_data = collections.OrderedDict(
  File "C:\ProgramData\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 272, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\ProgramData\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 245, in load_config
    data = yaml_load(file) or data
  File "C:\ProgramData\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 15, in yaml_load
    return safe_load(stream)
  File "C:\ProgramData\anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\ProgramData\anaconda3\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\ProgramData\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\ProgramData\anaconda3\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\ProgramData\anaconda3\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\ProgramData\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 69: character maps to 

### Conda info

```shell
(base) C:\Users\xx>conda info

     active environment : base
    active env location : C:\ProgramData\anaconda3
            shell level : 1
       user config file : C:\Users\xx\.condarc
 populated config files : C:\Users\xx\.condarc
          conda version : 23.3.1
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\ProgramData\anaconda3  (read only)
      conda av data dir : C:\ProgramData\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\anaconda3\pkgs
                          C:\Users\xx\.conda\pkgs
                          C:\Users\xx\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\xx\.conda\envs
                          C:\ProgramData\anaconda3\envs
                          C:\Users\xx\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.10.9 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> C:\Users\xx\.condarc <==
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at C:\ProgramData\anaconda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.11.1          py310haa95532_0    defaults
anaconda-navigator        2.4.0           py310haa95532_0    defaults
anaconda-project          0.11.1          py310haa95532_0    defaults
anyio                     3.5.0           py310haa95532_0    defaults
argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
argon2-cffi-bindings      21.2.0          py310h2bbff1b_0    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
attrs                     22.1.0          py310haa95532_0    defaults
babel                     2.11.0          py310haa95532_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.12.2          py310haa95532_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.1.0              pyhd3eb1b0_0    defaults
boltons                   23.0.0          py310haa95532_0    defaults
bottleneck                1.3.5           py310h9128911_0    defaults
brotlipy                  0.7.0           py310h2bbff1b_1002    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.01.10           haa95532_0    defaults
certifi                   2022.12.7       py310haa95532_0    defaults
cffi                      1.15.1          py310h2bbff1b_3    defaults
chardet                   4.0.0           py310haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4           py310haa95532_0    defaults
clyent                    1.2.2           py310haa95532_1    defaults
colorama                  0.4.6           py310haa95532_0    defaults
comm                      0.1.2           py310haa95532_0    defaults
conda                     23.3.1          py310haa95532_0    defaults
conda-build               3.23.3          py310haa95532_0    defaults
conda-content-trust       0.1.3           py310haa95532_0    defaults
conda-pack                0.6.0              pyhd3eb1b0_0    defaults
conda-package-handling    2.0.2           py310haa95532_0    defaults
conda-package-streaming   0.7.0           py310haa95532_0    defaults
conda-repo-cli            1.0.41          py310haa95532_0    defaults
conda-token               0.4.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              39.0.1          py310h21b164f_0    defaults
debugpy                   1.5.1           py310hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
entrypoints               0.4             py310haa95532_0    defaults
et_xmlfile                1.1.0           py310haa95532_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
filelock                  3.9.0           py310haa95532_0    defaults
freetype                  2.12.1               ha860e81_0    defaults
future                    0.18.3          py310haa95532_0    defaults
giflib                    5.2.1                h8cc25b3_3    defaults
glib                      2.69.1               h5dc1a3c_2    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
gst-plugins-base          1.18.5               h9e645db_0    defaults
gstreamer                 1.18.5               hd78058f_0    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      3.4             py310haa95532_0    defaults
intel-openmp              2023.1.0         h59b6b97_46319    defaults
ipykernel                 6.19.2          py310h9909e9c_0    defaults
ipython                   8.12.0          py310haa95532_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                8.0.4           py310haa95532_0    defaults
jedi                      0.18.1          py310haa95532_1    defaults
jinja2                    3.1.2           py310haa95532_0    defaults
jpeg                      9e                   h2bbff1b_1    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
jsonschema                4.17.3          py310haa95532_0    defaults
jupyter                   1.0.0           py310haa95532_8    defaults
jupyter_client            8.1.0           py310haa95532_0    defaults
jupyter_console           6.6.3           py310haa95532_0    defaults
jupyter_core              5.3.0           py310haa95532_0    defaults
jupyter_server            1.23.4          py310haa95532_0    defaults
jupyterlab                3.5.3           py310haa95532_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.22.0          py310haa95532_0    defaults
jupyterlab_widgets        3.0.5           py310haa95532_0    defaults
krb5                      1.19.4               h5b6d351_0    defaults
lerc                      3.0                  hd77b12b_0    defaults
libarchive                3.6.2                h2033e3e_1    defaults
libclang                  14.0.6          default_hb5a9fac_1    defaults
libclang13                14.0.6          default_h8e68704_1    defaults
libdeflate                1.17                 h2bbff1b_0    defaults
libffi                    3.4.2                hd77b12b_6    defaults
libiconv                  1.16                 h2bbff1b_2    defaults
liblief                   0.12.3               hd77b12b_0    defaults
libogg                    1.3.5                h2bbff1b_1    defaults
libpng                    1.6.39               h8cc25b3_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libtiff                   4.5.0                h6c2663c_2    defaults
libvorbis                 1.3.7                he774522_0    defaults
libwebp                   1.2.4                hbc33d0d_1    defaults
libwebp-base              1.2.4                h2bbff1b_1    defaults
libxml2                   2.10.3               h0ad7f3c_0    defaults
libxslt                   1.1.37               h2bbff1b_0    defaults
lxml                      4.9.2           py310h2bbff1b_0    defaults
lz4-c                     1.9.4                h2bbff1b_0    defaults
m2-msys2-runtime          2.5.0.17080.65c939c               3    defaults
m2-patch                  2.7.5                         2    defaults
markupsafe                2.1.1           py310h2bbff1b_0    defaults
matplotlib-inline         0.1.6           py310haa95532_0    defaults
menuinst                  1.4.19          py310h59b6b97_0    defaults
mistune                   0.8.4           py310h2bbff1b_1000    defaults
mkl                       2023.1.0         h8bd8f75_46356    defaults
mkl-service               2.4.0           py310h2bbff1b_1    defaults
mkl_fft                   1.3.6           py310h4ed8f06_1    defaults
mkl_random                1.2.2           py310h4ed8f06_1    defaults
msys2-conda-epoch         20160418                      1    defaults
navigator-updater         0.3.0           py310haa95532_0    defaults
nbclassic                 0.5.5           py310haa95532_0    defaults
nbclient                  0.5.13          py310haa95532_0    defaults
nbconvert                 6.5.4           py310haa95532_0    defaults
nbformat                  5.7.0           py310haa95532_0    defaults
nest-asyncio              1.5.6           py310haa95532_0    defaults
notebook                  6.5.4           py310haa95532_0    defaults
notebook-shim             0.2.2           py310haa95532_0    defaults
numexpr                   2.8.4           py310h2cd9be0_1    defaults
numpy                     1.24.3          py310h055cbcc_1    defaults
numpy-base                1.24.3          py310h65a83cf_1    defaults
openpyxl                  3.0.10          py310h2bbff1b_0    defaults
openssl                   1.1.1t               h2bbff1b_0    defaults
packaging                 23.0            py310haa95532_0    defaults
pandas                    1.5.3           py310h4ed8f06_0    defaults
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pathlib                   1.0.1              pyhd3eb1b0_1    defaults
pcre                      8.45                 hd77b12b_0    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.4.0           py310hd77b12b_0    defaults
pip                       22.3.1          py310haa95532_0    defaults
pkginfo                   1.9.6           py310haa95532_0    defaults
platformdirs              2.5.2           py310haa95532_0    defaults
pluggy                    1.0.0           py310haa95532_1    defaults
ply                       3.11            py310haa95532_0    defaults
powershell_shortcut       0.0.1                         3    defaults
prometheus_client         0.14.1          py310haa95532_0    defaults
prompt-toolkit            3.0.36          py310haa95532_0    defaults
prompt_toolkit            3.0.36               hd3eb1b0_0    defaults
psutil                    5.9.0           py310h2bbff1b_0    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
py-lief                   0.12.3          py310hd77b12b_0    defaults
pycosat                   0.6.4           py310h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyjwt                     2.4.0           py310haa95532_0    defaults
pyopenssl                 23.0.0          py310haa95532_0    defaults
pyqt                      5.15.7          py310hd77b12b_0    defaults
pyqt5-sip                 12.11.0         py310hd77b12b_0    defaults
pyrsistent                0.18.0          py310h2bbff1b_0    defaults
pysocks                   1.7.1           py310haa95532_0    defaults
python                    3.10.9               h966fe2a_1    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2          py310haa95532_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2022.7          py310haa95532_0    defaults
pywin32                   305             py310h2bbff1b_0    defaults
pywinpty                  2.0.10          py310h5da7b33_0    defaults
pyyaml                    6.0             py310h2bbff1b_1    defaults
pyzmq                     25.0.2          py310hd77b12b_0    defaults
qt-main                   5.15.2               he8e5bd7_8    defaults
qt-webengine              5.15.9               hb9a9bb5_5    defaults
qtconsole                 5.4.2           py310haa95532_0    defaults
qtpy                      2.2.0           py310haa95532_0    defaults
qtwebkit                  5.212                h2bbfb41_5    defaults
requests                  2.29.0          py310haa95532_0    defaults
ruamel.yaml               0.17.21         py310h2bbff1b_0    defaults
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1    defaults
ruamel_yaml               0.17.21         py310h2bbff1b_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                65.6.3          py310haa95532_0    defaults
sip                       6.6.2           py310hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sniffio                   1.2.0           py310haa95532_1    defaults
soupsieve                 2.4             py310haa95532_0    defaults
sqlite                    3.41.2               h2bbff1b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
tbb                       2021.8.0             h59b6b97_0    defaults
terminado                 0.17.1          py310haa95532_0    defaults
tinycss2                  1.2.1           py310haa95532_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1           py310haa95532_0    defaults
toolz                     0.12.0          py310haa95532_0    defaults
tornado                   6.2             py310h2bbff1b_0    defaults
tqdm                      4.65.0          py310h9909e9c_0    defaults
traitlets                 5.7.1           py310haa95532_0    defaults
typing-extensions         4.5.0           py310haa95532_0    defaults
typing_extensions         4.5.0           py310haa95532_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
ujson                     5.4.0           py310hd77b12b_0    defaults
urllib3                   1.26.15         py310haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1           py310haa95532_1    defaults
websocket-client          0.58.0          py310haa95532_4    defaults
wheel                     0.38.4          py310haa95532_0    defaults
widgetsnbextension        4.0.5           py310haa95532_0    defaults
win_inet_pton             1.1.0           py310haa95532_0    defaults
wincertstore              0.2             py310haa95532_2    defaults
winpty                    0.4.3                         4    defaults
xz                        5.4.2                h8cc25b3_0    defaults
yaml                      0.2.5                he774522_0    defaults
zeromq                    4.3.4                hd77b12b_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
zstandard                 0.19.0          py310h2bbff1b_0    defaults
zstd                      1.5.5                hd43e919_0    defaults
```

**Comment by vshevchenko-anaconda** [comment] 2023-07-06 14:37
Duplicate of #13159

**Closed by vshevchenko-anaconda** 2023-07-06 14:37 UTC
Labels: type-bug, pkg-navigator
