### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by pjgoodall** [ContinuumIO/anaconda-issues#2668] opened 2017-06-28 06:22 UTC
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

byte indices must be integers or slices, not str
Traceback

Traceback (most recent call last):
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/peter/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-06-28 17:27
Closing as duplicate of #1837

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-28 17:27 UTC

**Comment by pjgoodall** [comment] 2017-06-29 01:04
All packages were up-to-date. Anaconda was installed fresh yesterday.
Just tried suggestion - same error.

Cheers...

**Comment by LBsh** [comment] 2017-08-31 16:41
I have tried uninstall and reinstall the whole package but nothing works. Running as administrator does not help.

**Comment by rodrigoporcionato** [comment] 2017-09-01 18:54
hi, check if exist a site package in Python. Normaly in this path : C:\Users\youruser\AppData\Roaming\Python and delete the folder. This it work with me.

**Comment by pjgoodall** [comment] 2017-09-11 00:52
I'm on Ubuntu 16.04 LTS

Sorry I forgot to mention my platform...

**Comment by klapi85** [comment] 2017-09-19 07:49
I got the same problem with Ubuntu 14.04 and Anaconda 4.4.0 with Python 3.6 installer (64-Bit).

**Comment by klapi85** [comment] 2017-09-19 08:32
I've noticed there is a problem while using the "fish" terminal. Bash goes ok.

**Comment by goanpeca** [comment] 2017-09-19 11:54
We only have official support for bash, although it may or may not work on other shells.

**Comment by taymourniazi** [comment] 2018-01-19 10:22
An unexpected error occurred on Navigator start-up
psutil.AccessDenied
So I used several commands like
-	Conda update anaconda-navigator
-	Conda update navigator-updater
-	Conda update --prefix C:\Users\asd\Anaconda2 anaconda
It all doesn’t fix the issue only the following work fine
-	Anaconda-navigator --reset

**Comment by mohammadraasel** [comment] 2018-03-10 21:45
on teminal type:
conda update -n base conda

**Comment by carmamir** [comment] 2018-03-11 19:14
@mohammadraasel 

Already guys confirmed that this is not a solution !

Doesn't work at all. Fresh install, Windows.

**Comment by csoja** [comment] 2018-03-19 16:25
@carmamir  You tried _anaconda-navigator --reset_  from an Anaconda Prompt window?

**Comment by ranand985** [comment] 2018-03-21 13:27
@csoja  Thanks a lot. The command you suggested worked on my system (Mac).

**Comment by anushreddy** [comment] 2018-04-17 17:26
@csoja Worked like a charm. Thanks

**Comment by freyesBci** [comment] 2018-05-13 23:16
@csoja After searching everywhere this solved everything! Thanks

**Comment by DennisScuba** [comment] 2018-05-24 14:20
I tried all mentioned possibilities and couldn't fix it, has someone another idea?

**Comment by ESSIENEKPO** [comment] 2018-06-29 14:16
I type Anaconda-navigator --reset on Anaconda command prompt on windows 8.1 and it reset Anaconda Navigator. After reset, it prompted for update to version 1.8.4 which I did. It prompted again for another update to version 1.8.7 and I followed the screen, after that Anaconda Navigator loaded and works fine. Note, it will prompt you to close Anaconda navigator as the update progresses. Thanks for this forum.

**Comment by goanpeca** [comment] 2018-06-29 15:02
@ESSIENEKPO open the command prompt and install from there.

`conda install anaconda-navigator=1.8.7`

**Comment by mshofuan** [comment] 2019-04-23 08:20
I try 
conda update anaconda-navigator 

Then,  it works

Thank u all
