### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by LeonardManhanga** [ContinuumIO/anaconda-issues#1967] opened 2017-06-05 17:09 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),),)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-06-21 16:01
Closing as duplicate of #1932

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-21 16:01 UTC
Labels: pkg:navigator, reso:duplicate
