### ISSUE TITLE
update spyder fails to create links

### ISSUE THREAD

**Issue by chanansh** [ContinuumIO/anaconda-issues#257] opened 2015-02-02 08:47 UTC
I have updates spyder using `conda update` but it fails to update shortcuts. 
Moreover I don't have an icon to spyder.
Plus, if I close spyder, it crashes instead of closing normally.

```

[      COMPLETE      ] |#################################################| 100%
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
menuinst Exception:Traceback (most recent call last):####################| 100%
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 309, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 42, in instal
l
    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 133, in create
    u'' + icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\
Programs\Anaconda (64-bit)\Spyder.lnk' - error 0x80070005
[      COMPLETE      ] |#################################################| 100%

```

**Comment by ccordoba12** [comment] 2015-02-02 20:35
You can't do any `conda` command while Spyder is open. That's (most) probably the cause of this error. To fix it, please do

    conda install -f foo

where foo are all the packages involved in your update.

**Comment by jdmcbr** [comment] 2015-08-21 03:49
While this is certainly not a huge issue, I wanted to chime in and say I'm seeing the same error with Spyder closed.

```
C:\Anaconda>conda update -f spyder
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following packages will be UPDATED:

    spyder: 2.3.5.2-py27_0 --> 2.3.5.2-py27_0

Proceed ([y]/n)? y

[      COMPLETE      ]|##################################################| 100%
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
menuinst Exception:Traceback (most recent call last):                    |   0%
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 316, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Anaconda\lib\site-packages\menuinst\__init__.py", line 42, in install

    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda\lib\site-packages\menuinst\win32.py", line 133, in create
    u'' + icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\
Programs\Anaconda (64-bit)\Spyder.lnk' - error 0x80070005
[      COMPLETE      ]|##################################################| 100% 
```

And, the conda info:

```
C:\Anaconda>conda info
Current conda install:

             platform : win-64
        conda version : 3.16.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
```

**Comment by ccordoba12** [comment] 2015-08-21 13:33
I'll take a look at this one.

**Comment by H0R5E** [comment] 2015-11-17 10:58
Issue #91 is a dupe.

**Comment by ccordoba12** [comment] 2015-11-18 14:06
Closing as a duplicate of issue #91.

**Closed by ccordoba12** 2015-11-18 14:06 UTC
Labels: duplicate
