### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by amiaty** [ContinuumIO/anaconda-issues#2410] opened 2017-06-19 23:48 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=2640)
## Traceback
```
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=2640)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.22
qt: 5.6.2
language: fa_IR
python: 2.7.13
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-06-20 00:15
Closing as duplicate of #1984

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-20 00:15 UTC
Labels: pkg:navigator, reso:duplicate
