### ISSUE TITLE
Fatal Error with Anaconda Launcher, 32-bit Windows XP, 64-bit Windows XP, 64-bit Windows 7

### ISSUE THREAD

**Issue by TMKAIG1** [ContinuumIO/anaconda-issues#216] opened 2014-11-26 20:43 UTC
Hi!  Sorry about the repeat message on this issue, but I had to delete my first GitHub account and create a new one, because I must have mis-entered my eddress when I originally set up my account, and it seems that the one thing you can't edit in your GitHub account is the eddress!  Anyway, I have had the chance to install Anaconda on two more machines, a Windows XP 64-bit desktop and a Windows XP 32-bit laptop.  Same launcher fatal error message each time.  Can anybody get launcher to work?  I appreciate any assistance!  Thanks!!

**Comment by joknows** [comment] 2015-01-21 17:28
Has anyone found a resolution? I'm having the same issue - C:\Anaconda and C:\Anaconda\Scripts are both in my path

**Comment by tswicegood** [comment] 2015-01-21 19:12
@joknows we haven't tracked this down, but we're in the process of a big update to Anaconda Launcher.  The Windows testing on this new version is extensive, so my hope is that it will solve your problems.  Once we have a development build, I'll post how to install it from here.

**Comment by joknows** [comment] 2015-01-22 03:55
@tswicegood Great, thanks!

**Comment by dferguso** [comment] 2015-04-03 14:07
Has this issue been resolved?  I was getting the same error when I attempted to start the Launcher while my PC was off-line.  Tried again after connected to the network and it started with no error.  Could this be a issue with needing some external network access?  I hope not as I need to use Conda off-line.

**Comment by tbshirey** [comment] 2015-04-06 15:29
Interesting that you mention this. I am getting the same error today trying to launch Anaconda 2.2.0 on my Mac at work. The Launcher opened fine at home all weekend while connected to wifi, but now trying at work while offline it will not open. Interestingly, I can open the Spyder app directly by calling spyder from the command line terminal.

**Comment by tswicegood** [comment] 2015-04-06 16:06
Unfortunately, the currently released version of Anaconda Launcher doesn't work offline.

**Comment by tbshirey** [comment] 2015-04-07 02:06
Thanks for the reply tswicegood.  That's what I suspected, but wanted to make sure. It's not a big issue, for me at least, as I can still call everything I need from the command line while offline.

**Comment by mannion9** [comment] 2015-06-09 15:28
I have had this same issue on a mac and I fixed it but I do not know why it works.

All I did was go into terminal and go to my anaconda directory and ran the python.app which opened a python shell. After quitting this I tried opening Launcher again and it worked just fine. 

Hope this helps someone. I have know idea what opening the python.app does but it worked.

**Comment by mrkr188** [comment] 2015-07-12 06:33
I have windows 7 32 bit version of python 2.7 anaconda installed. I am facing the similar issue as well.

**Comment by giumas** [comment] 2015-09-08 00:40
I can confirm the issue on Win7 64bit with both python 2.7 and 3.4

**Comment by goanpeca** [comment] 2015-10-06 13:33
Hi, we are working on a new launcher which should address the issues presented by the previous version.

If you would like to try it please go to a terminal, remove the previous launcher, install the new version and launch it by typing:

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

Let us know if the issues persist, or any other comments and suggestions

Cheers

**Comment by giumas** [comment] 2015-10-06 13:37
![capture](https://cloud.githubusercontent.com/assets/2849257/10310034/d68402ec-6c0d-11e5-928c-3085a5c648b7.PNG)

It works!

**Comment by goanpeca** [comment] 2015-10-06 13:50
@glumas great to hear, we are still polishing/implementing some of the features so that it is complete for release but wanted to get some feedback on users with issues.

Please let us know, 

Cheers :+1:

**Comment by yavigol** [comment] 2015-10-19 19:22
I recently updated spyder (via launcher) on my windows 7 (32-bit) machine.  As a result I can launch spyder neither from the launcher, nor running spyder.exe.  the system generates the following message:
'The version of this file is not compatible with the version of Windows you're running.  Check your computer's system information to see wehther you need an x86 (32-bit) or x64(64-bit) version of the program, and then contact the software publisher'
To avoid the issue, I reinstalled anaconda and do not update spyder through the launcher anymore.  The solution works OK so far, but it is far from being ideal.  Could you please let me know if there any way to resolve this issue?

**Comment by goanpeca** [comment] 2015-10-19 19:25
@yavigol can you provide some info on the Launcher version you were using?

**Comment by yavigol** [comment] 2015-10-19 19:33
Anaconda Launcher Info
Version: 1.0.0 (node-webkit 0.10.1)
Conda Version: 3.14.1
Root Prefix: C:\Users\Iaro\Anaconda
Default Prefix: C:\Users\Iaro\Anaconda
Python Version: 2.7.10.final.0
Platform: win-32

**Comment by goanpeca** [comment] 2015-10-19 19:36
There is a new version of the launcher (still under development) you can try it by doing.

```bash
conda remove launcher
conda install -c https://conda.anaconda.org/goanpeca/channel/dev launcher=2.0.0rc1
launcher
```

**Comment by yavigol** [comment] 2015-10-19 19:41
I tried the new launcher a little bit earlier today (found the link in one of your recent messages).  It did not help unfortunately.

**Comment by yavigol** [comment] 2015-10-19 19:44
I also noticed that spyder update results in removal of spyder related icons from Anaconda folder in the Start menu

**Comment by goanpeca** [comment] 2015-10-19 21:03
Thanks for the reporting, will get to fixing the issues, cheers

**Comment by yavigol** [comment] 2015-10-20 11:01
By the way, I got the same issue on another laptop (also windows 7 32bit), owned by my friend.  Looks like this is a systematic issue

**Comment by goanpeca** [comment] 2015-10-20 14:42
@ccordoba12 is this related to the conda recipe?

**Comment by ccordoba12** [comment] 2015-10-20 19:09
@goanpeca, what exactly?

**Comment by goanpeca** [comment] 2015-10-20 20:02
The spyder icons/shortcuts not being created correctly in windows

**Comment by ccordoba12** [comment] 2015-10-20 20:07
Yes, it could be. Truth is I don't understand too well how that works on Windows :-)

**Comment by goanpeca** [comment] 2015-10-20 20:10
I sent a msg in gitter some time ago about this.... basically the conda recipe for spyder is broken (shortcuts) for some versions now....

> ```bash
Linking packages ...
menuinst Exception:Traceback (most recent call last):##########          |  81%
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 309, in mk_menus
    return
  File "C:\Miniconda\lib\site-packages\menuinst\__init__.py", line 40, in instal
l
    m.create()
  File "C:\Miniconda\lib\site-packages\menuinst\win32.py", line 45, in create
    os.mkdir(self.path)
WindowsError: [Error 5] Access is denied: u'C:\\ProgramData\\Microsoft\\Windows\
\Start Menu\\Programs\\Anaconda (32-bit)'
menuinst Exception:Traceback (most recent call last):##################  |  96%
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 309, in mk_menus
    return
  File "C:\Miniconda\lib\site-packages\menuinst\__init__.py", line 40, in instal
l
    m.create()
  File "C:\Miniconda\lib\site-packages\menuinst\win32.py", line 45, in create
    os.mkdir(self.path)
WindowsError: [Error 5] Access is denied: u'C:\\ProgramData\\Microsoft\\Windows\
\Start Menu\\Programs\\Anaconda (32-bit)'
[      COMPLETE      ]|##################################################| 100%


```

**Comment by ccordoba12** [comment] 2015-10-22 16:47
This was fixed in our internal repo, and new packages will be delivered shortly.

**Comment by goanpeca** [comment] 2015-10-22 19:42
:+1:

**Comment by DenverDaveH** [comment] 2016-01-12 22:38
I am on Windows 7 64 bit. I opened a cmd prompt as Admin. I then cd'd to the dir with Anaconda2-2.4.1-Windows-x86_64.exe. I ran it from inside the Admin prompt. I am logged in with my admin account. I get an error about creating menu items. Here is my conda info:
c:\Anaconda2\Scripts>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.8.1
     root environment : c:\Anaconda2  (writable)
  default environment : c:\Anaconda2
     envs directories : c:\Anaconda2\envs
        package cache : c:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
I saw on the Continuum site that this was fixed. But not for me. 
It appears this is not resolved. Or is it and I missed a step?
Please advise.

**Comment by msarahan** [comment] 2016-01-12 22:46
The installer by itself contains an old version of the menuinst package that exhibits problems with a file deletion race condition.  We can't fix old installers.  We are scheduled to have a new release in February.  Until then, let me ask some questions:

Does setup complete in spite of the error?  If so, you can update menuinst and install shortcuts using the following commands:

    conda update menuinst
    conda install -f console_shortcut ipython ipython-notebook ipython-qtconsole launcher spyder

If setup does not complete in spite of the error, you can install with an older installer (2.4.0 or earlier), then update:

    conda update --all

**Comment by DenverDaveH** [comment] 2016-01-13 17:32
Hi Mike,
Thanks for the quick reply.
To answer your install question, aside from the menu shortcuts, the install goes on without any errors. 

I think ran the commands as you said. They worked just fine. I have the Anaconda group of shortcuts in the programs list. 

Thanks for the info. I look forward to this being fixed in Feb. 
Dave

**Comment by goanpeca** [comment] 2017-05-17 03:56
Launcher is deprecated and has been replaced by Anaconda Navigator. To learn more about it please check the [documentation](https://docs.continuum.io/anaconda/navigator/)

To install please open the Anaconda Prompt/Terminal and type

```
$ conda install anaconda-navigator
```

**Closed by goanpeca** 2017-05-17 03:56 UTC
Labels: os:windows, tag:launcher, type:bug

**Comment by yavigol** [comment] 2017-05-17 04:37
Hi all,

I just installed anaconda 2x and updated it right away with "conda update
--all".  As a result Spyder and other apps installed do not open.  I
uninstalled anaconda 2x and installed anaconda 3x.  The same story.  Before
updating Spyder opened w/o problems.  After the update - does not open at
all.  Could you please advise what to do?  Should I install the
installation package and run no updates in the future?

Thanks,
Jaro

**Comment by thomas236** [comment] 2017-05-25 14:36
Please install an archive version of Anaconda (version 2.2 or earlier ) to solve. 
Please refer to
https://docs.continuum.io/anaconda/faq#id21

It works for me
