### ISSUE TITLE
Upgrading miniconda breaks pip

### ISSUE THREAD

**Issue by tdaff** [ContinuumIO/anaconda-issues#6317] opened 2017-10-02 10:02 UTC
When running on Appveyor, starting with miniconda 4.2.12 and upgrading conda and pip leaves pip in a broken state:

```
pip --help
Traceback (most recent call last):
  File "C:\Miniconda35-x64\Scripts\pip-script.py", line 6, in <module>
    from pip import main
  File "C:\Miniconda35-x64\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Miniconda35-x64\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Miniconda35-x64\lib\site-packages\pip\download.py", line 41, in <module>
    from pip._vendor.requests.adapters import BaseAdapter, HTTPAdapter
ImportError: No module named 'pip._vendor.requests.adapters'
```

Reproducible on 3.5 and 3.6 outside of Appveyor but works fine on 2.7:

See:
https://ci.appveyor.com/project/tdaff/conda-pip-fail/build/1.0.1

Build script is in:
https://bitbucket.org/tdaff/conda_pip_fail/overview

**Comment by msarahan** [comment] 2017-10-02 21:08
I've seen this with old miniconda (4.3.11) updated to current. I have not seen this with 4.3.21 or 4.3.27. the issue is that a requests folder is left in the lib/site-packages/pip/_vendor folder, presumably due to a bad old pip package that didn't list all it's files correctly. Removing that folder makes pip work for me. I have asked the appveyor team to update their miniconda installations.

If you have information to add here, please do. My advice right now is to install new miniconda from installers rather than upgrading old installs.

**Comment by msarahan** [comment] 2017-10-02 21:11
The appveyor team pointed me to this issue:
https://github.com/appveyor/ci/issues/1780

**Comment by csoja** [comment] 2018-01-08 20:49
This should be fixed and not a problem now.  Please let us know if that is not the case.

**Closed by csoja** 2018-01-08 20:49 UTC

**Comment by HuskyCougar** [comment] 2022-10-24 00:43
Not specifically a pip issue but, install miniconda stomped my paths.

$ perl /mnt/c/data/PHOTO/photo_renamer.pl
Can't locate Image/ExifTool.pm in @INC (you may need to install the Image::ExifTool module) (@INC contains: /mnt/c/TOOLS/WSL_miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /mnt/c/TOOLS/WSL_miniconda3/lib/site_perl/5.26.2 /mnt/c/TOOLS/WSL_miniconda3/lib/5.26.2/x86_64-linux-thread-multi /mnt/c/TOOLS/WSL_miniconda3/lib/5.26.2 .) at /mnt/c/data/PHOTO/photo_renamer.pl line 26.
BEGIN failed--compilation aborted at /mnt/c/data/PHOTO/photo_renamer.pl line 26.
