### ISSUE TITLE
conda command failure

### ISSUE THREAD

**Issue by midhubalan** [ContinuumIO/anaconda-issues#6171] opened 2017-09-27 13:01 UTC
I created a new environment for tensorflow following instructions from this  [repo](https://github.com/the-deep-learners/TensorFlow-LiveLessons/tree/master/installation ) 
When restarted my computer and launched anaconda command prompt
I received following message and conda command was not recognized:
usage: conda [-h]
             {keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
             ...
conda: error: invalid choice: '..checkenv' (choose from 'keygen', 'sign', 'unsign', 'verify', 'unpack', 'install', 'install-scripts', 'convert', 'version', 'help')
I tried launching anaconda using navigator

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\XXXX\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

I am using Windows 64 bit system

**Comment by goanpeca** [comment] 2017-09-27 13:05
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-27 13:05 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by midhubalan** [comment] 2017-09-27 13:07
Conda command just does not work to do a conda update

**Comment by Braveheart53** [comment] 2017-09-27 14:14
Multiple of these same issues have been posted and closed by the same person. With the fully updated conda suggested as well as 

`./conda update --all`

I have not included anconda in my path as to not interfer with the system version of python, but I have used aliases to run as required. Just to list the full return again with fully update anaconda3 at 1013 EST on 2017-09-27:

` 
./anaconda-navigator
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "/home/wwallace/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

Segmentation fault (core dumped)
`

**Comment by msarahan** [comment] 2017-09-27 14:15
You have somehow picked up a conda version that is out of sync with the activate scripts.  To remedy this, I think you might need to do a fresh install of anaconda or miniconda from the .exe installers.

**Comment by midhubalan** [comment] 2017-09-27 14:19
@goanpeca conda command is not recognized i get the following message when i start the conda prompt.
usage: conda [-h]
{keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
...
conda: error: invalid choice: '..checkenv' (choose from 'keygen', 'sign', 'unsign', 'verify', 'unpack', 'install', 'install-scripts', 'convert', 'version', 'help')
I tried launching anaconda using navigator

**Comment by eng-tsmith** [comment] 2017-10-06 08:23
I am having the same problem:
No conda command is working., e.g. `activate root` --> ` conda: error: invalid choice: '..checkenv'`

**Comment by Mistty** [comment] 2017-10-23 07:22
after I interupted a anaconda prompt...when restart
usage: conda [-h]
             {keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
             ...
conda: error: invalid choice: '..checkenv' (choose from 'keygen', 'sign', 'unsign', 'verify', 'unpack', 'install', 'install-scripts', 'convert', 'version', 'help')

and then nothing could save it for now....

**Comment by JerryKurata** [comment] 2017-10-24 20:01
Brand new installation of Anaconda3 on Windows 10 system.  When the system is restarted I get the following:

C:\Users\jerry\Anaconda3>conda update
usage: conda [-h]
             {keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
             ...
conda: error: invalid choice: 'update' (choose from 'keygen', 'sign', 'unsign', 'verify', 'unpack', 'install', 'install-scripts', 'convert', 'version', 'help')
 

Directly running conda.exe outputs the following, **NOTICE, No Update option**:

C:\Users\jerry\Anaconda3>conda.exe
usage: conda [-h]
             {keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
             ...

positional arguments:
  {keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
                        commands
    keygen              Generate signing key
    sign                Sign wheel
    unsign              Remove RECORD.jws from a wheel by truncating the zip
                        file. RECORD.jws must be at the end of the archive.
                        The zip file must be an ordinary archive, with the
                        compressed files and the directory in the same order,
                        and without any non-zip content after the truncation
                        point.
    verify              Verify a wheel. The signature will be verified for
                        internal consistency ONLY and printed. Wheel's own
                        unpack/install commands verify the manifest against
                        the signature and file contents.
    unpack              Unpack wheel
    install             Install wheels
    install-scripts     Install console_scripts
    convert             Convert egg or wininst to wheel
    version             Print version and exit
    help                Show this help

optional arguments:
  -h, --help            show this help message and exit

Please let me know what I am doing wrong

**Comment by yiran-THU** [comment] 2017-10-26 07:29
@goanpeca 

```
conda update anaconda-navigator
conda update navigator-updater
```
This command doesn't work ,my OS is win10(64),python3.5

**Comment by JerryKurata** [comment] 2017-10-26 15:18
I did some more investigation.  In my case, the problem was with Google TensorFlow.  Their PIP based installation replace conda.exe with an older/broke version.   Since I need TensorFlow more than environments I have to, unfortunately, abandon environments until this is fixed.  But, since Google says that Conda is community supported, not sure if they will do anything.

**Comment by jjhelmus** [comment] 2017-10-26 19:10
@JerryKurata Can you provide some more details on how conda is breaking when you pip install tensorflow?  I followed the instructions for [installing tensorflow on Windows with Anaconda](https://www.tensorflow.org/install/install_windows) and had no issue running conda afterwords.  

It should be safe to not include the `--ignore-installed` and `--upgrade` arguments from the install command but I would be interested in learning more about what was causing the breakage.

**Comment by JerryKurata** [comment] 2017-10-26 19:29
@jjhelmus Sure.  Here is what I did. 

- Downloaded and ran anaconda 5.0.1 for windows installed.  Selected 64-bit graphical installer.  Took defaults.
- added c:\user\jerry\Anaconda3 and c:\user\jerry\Anacona3\scripts to my path so I could use the conda command from command line
- created environment with the command "conda create -n tf-test python=3.6 numpy scipy matplotlib spyder"
- checked date last updated for c:\user\jerry\Anaconda3\script\conda.exe.  Date showed time of installation.
- Activate environment with "activate tf-test"
- Per instruction on https://www.tensorflow.org/install/install_windows ran the command "pip install --ignore-installed --upgrade tensorflow-gpu"
- checked date last updated for c:\user\jerry\Anaconda3\script\conda.exe.  **Date showed time before date of installation.**
- But, conda command works
- Reboot system
- create new terminal session
- activate tf-test - ERROR
- Try conda command - ERROR -
"usage: conda [-h]
{keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
...
conda: error: invalid choice: 'update' (choose from 'keygen', 'sign', 'unsign', 'verify', 'unpack', 'install', 'install-scripts', 'convert', 'version', 'help')"

**Comment by awt135** [comment] 2017-11-12 11:15
usage: conda [-h]
             {keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
             ...
conda: error: invalid choice: '..checkenv' (choose from 'keygen', 'sign', 'unsign', 'verify', 'unpack', 'install', 'install-scripts', 'convert', 'version', 'help')


i installed the TensorFlow on windows normally ，the same of upstairs，but  when i reboot the windows ， the result is same wrong.

**Comment by JerryKurata** [comment] 2017-11-12 15:30
A little more information on working around this.  I made a copy of my Anaconda3\scripts folder **before** installing tensorflow-gpu.  Then installed tensorflow-gpu.  After installing tensorflow-gpu, the conda.exe was replaced with the incorrect version.  But I could replace it with the correct version of conda.exe from my copy and get it going.

**Comment by jwangjie** [comment] 2017-11-14 04:08
I solved my problem following this: https://stackoverflow.com/a/46493533/8936445 

In short, after activating the created environment, instead of "pip install --ignore-installed --upgrade tensorflow-gpu", use "pip install tensorflow-gpu".

**Comment by vncntprvst** [comment] 2017-12-12 20:47
Another way of fixing this issue, if one has a restore point available, is to go to the scripts folder (e.g. _C:\ProgramData\Anaconda2\Scripts_ ) , right-click on _conda.exe_ and select "Restore previous version".

**Comment by akhilgeothom** [comment] 2019-02-13 16:50
If this message coming up every time you start the terminal (linux) is what is annoying you and led you here,
 then just edit the .bashrc file by removing all lines related to conda init.
