### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by annesoj** [ContinuumIO/anaconda-issues#2375] opened 2017-06-18 17:56 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=612)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Anne-Sophie\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Anne-Sophie\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Accès refusé

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anne-Sophie\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Anne-Sophie\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Anne-Sophie\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Anne-Sophie\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Anne-Sophie\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=612)

```
## System information
```
python: 3.6.1
language: fr_FR
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.

**Comment by annesoj** [comment] 2017-06-18 17:59
Hi everyone,

Please help, I cannot connect to anaconda anymore and I have no ideas why.
I cut navigator while one program was still running, it might com from that....

I get the error I posted and then I have to button "report the error" (what I did" and "ok" which close mi anaconda. I don't know how to go on again....

**Comment by goanpeca** [comment] 2017-06-19 01:52
Closing as duplicate of #1984

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-19 01:52 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by annesoj** [comment] 2017-06-19 05:23
Thank you very much.
Actully I rebut my computer and everything was working....

My be an update have been done.

However I will try tu update anyway with "$ conda update anaconda-navigator". 

Thank you again,
Anne-Sophie

**Comment by annesoj** [comment] 2017-06-19 11:39
Hi Goanpeca,

I tried to update anaconda as you said, using a terminal and I got this error:

`PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\Anne-Sophie\Miniconda3
  package name: anaconda-navigator`


Do you know what it meant?
Actully since I have installed Miniconda, anytime I install a librairy it get installed in miniconda and I have to copy/paste in Anaconda.

I used miniconda because I didn't try to install xgboost using anaconda....
