### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by daydreamer77r** [ContinuumIO/anaconda-issues#8272] opened 2018-01-24 22:40 UTC
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/Users/Robin/anaconda/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/Users/Robin/anaconda/lib/python3.5/site-packages/jupyterlab/labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "/Users/Robin/anaconda/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/Robin/anaconda/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
platform: osx-64
language: en
pyqt: 5.6.0
version: 1.6.2
conda: 4.4.7
os: Darwin;17.3.0;Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64;x86_64;i386
qt: 5.6.0
python: 3.5.2
```

**Comment by goanpeca** [comment] 2018-01-25 16:22
Closing as duplicate of #8216

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8216 for more information on how to fix this issue.**

Or try running

```
conda upgrade jupyter_core
```

**Closed by goanpeca** 2018-01-25 16:22 UTC
Labels: pkg:navigator, reso:duplicate
