### ISSUE TITLE
Cannot install packages with either pip or conda

### ISSUE THREAD

**Issue by udayr23** [ContinuumIO/anaconda-issues#10576] opened 2019-02-02 03:45 UTC
Here is what is happening when I try using pip to install something:

pip install pymsgbox
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pymsgbox
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pymsgbox/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pymsgbox/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pymsgbox/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pymsgbox/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pymsgbox/
  Could not fetch URL https://pypi.org/simple/pymsgbox/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pymsgbox/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  Could not find a version that satisfies the requirement pymsgbox (from versions: )
No matching distribution found for pymsgbox
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

here is what happened when I try the same thing with Conda:

conda install pymsgbox
Solving environment: failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/r/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

Here is my system information: 
Windows 10, 64bit
Dell Inspiron 13 7000
Python 3.7.1
conda 4.5.12

Any idea what may be causing this? I just need a way to install files. I am a beginner to this stuff so please explain things as clearly as possible.

**Comment by msarahan** [comment] 2019-02-02 04:36
duplicate of https://github.com/conda/conda/issues/8046 - you may find a workaround there.  conda 4.6.2 included a fix that may address the root cause of the issue, but it probably doesn't fix already-broken environments.

If those suggestions are too much for you, I recommend uninstalling anaconda, then reinstalling it, followed by immediately updating conda to 4.6.2 before doing anything else.  From there, hopefully you are OK.

**Closed by msarahan** 2019-02-02 04:36 UTC

**Comment by ccoollavie** [comment] 2019-05-10 12:55
Hi, 
Problem solved here ?
https://github.com/conda/conda/issues/8273
Copy these files from the ./Library/bin to ./DLL/ : 
libcrypto-1_1-x64.*
libssl-1_1-x64.*

**Comment by yibo-liang** [comment] 2019-05-14 13:35
> Hi,
> Problem solved here ?
> [conda/conda#8273](https://github.com/conda/conda/issues/8273)
> Copy these files from the ./Library/bin to ./DLL/ :
> libcrypto-1_1-x64.*
> libssl-1_1-x64.*

Finally something that worked for me. Best regards.

**Comment by v3nd3774** [comment] 2019-06-05 14:08
Just had this issue and solved with adding following line in `~/.zshrc`:

```
export PATH=$CONDA_HOME/Library/bin:$PATH
```

Just have to ensure `$CONDA_HOME` points to the parent folder of `Library`.

**Comment by EandrewJones** [comment] 2019-06-21 01:47
> Hi,
> Problem solved here ?
> [conda/conda#8273](https://github.com/conda/conda/issues/8273)
> Copy these files from the ./Library/bin to ./DLL/ :
> libcrypto-1_1-x64.*
> libssl-1_1-x64.*

Another +1 on this fix for Windows 10.

**Comment by rishisinha** [comment] 2019-06-26 11:30
> Hi,
> Problem solved here ?
> [conda/conda#8273](https://github.com/conda/conda/issues/8273)
> Copy these files from the ./Library/bin to ./DLL/ :
> libcrypto-1_1-x64.*
> libssl-1_1-x64.*

Thanks this worked :)

**Comment by weiwei2** [comment] 2019-08-25 11:27
this also works for me on windows 10. i was using anaconda indirectly from vs code

**Comment by mingwandroid** [comment] 2019-08-25 21:37
None of this is recommended. You are better off setting and env. var of
CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1 permanently. This applies for users
of code (though I believe it activates conda correctly now so this is not
necessary) and for people who have broken their systems by installing 3rd
party applications that put non-system DLLs into C:\Windows\System32 (i.e.
those people who have been copying SSL dlls around).
