### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Parth-Patel12** [ContinuumIO/anaconda-issues#9017] opened 2018-03-27 10:43 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 16:12:28.002 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 16:12:30.249 NotebookApp] Serving notebooks from local directory: /home/karma
[I 16:12:30.250 NotebookApp] 0 active kernels 
[I 16:12:30.250 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=9ad332f0a197826601aabec7d707a18c265e6e29231c2fbb
[I 16:12:30.250 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:12:30.250 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=9ad332f0a197826601aabec7d707a18c265e6e29231c2fbb
[I 16:12:30.754 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[3458:3497:0327/161230.775112:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.

```
## System information
```
python: 3.6.1
language: en_IN
os: Linux;4.13.0-37-generic;#42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.11
```

**Comment by goanpeca** [comment] 2018-03-27 14:03
Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #2098 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-03-27 14:03 UTC
Labels: pkg:navigator, reso:duplicate
