### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by menkefh** [ContinuumIO/anaconda-issues#7169] opened 2017-11-07 18:35 UTC
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Packages missing in current channels:
            
  - rstudio ==1.1.383 -> fonts-anaconda
  - rstudio ==1.1.383 -> icu >=58.2,<59.0a0

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
            
```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by menkefh** [comment] 2017-11-07 18:37
I see [This issue](https://github.com/ContinuumIO/anaconda-issues/issues/7112) and will attempt the suggested solution.

**Comment by goanpeca** [comment] 2017-11-14 22:22
**See issue #6970 for more information on how to fix this issue.**

---

Closing as duplicate of #6970

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-14 22:22 UTC
