### ISSUE TITLE
Notebook Error: ImportError: DLL load failed

### ISSUE THREAD

**Issue by Pattingerr** [ContinuumIO/anaconda-issues#10422] opened 2018-12-13 16:32 UTC
### Main error

Application notebook launch may have produced errors.

### Traceback
```

Traceback (most recent call last):
  File "C:\Users\Patri\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\Patri\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\Patri\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Patri\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Patri\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Patri\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Patri\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Patri\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

```

### Expected Behavior

Launching Notebook

##### `conda info`

```
     active environment : None
       user config file : C:\Users\Patri\.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.17.4
         python version : 3.7.1.final.0
       base environment : C:\Users\Patri\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Patri\Anaconda3\pkgs
                          C:\Users\Patri\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Patri\Anaconda3\envs
                          C:\Users\Patri\AppData\Local\conda\conda\envs
                          C:\Users\Patri\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.20.1 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

```

**Comment by spex66** [comment] 2018-12-18 10:57
Same here, identical `conda info` just English errors.
So why have you closed it @Pattingerr ?

My repo steps:
Miniconda installed with `chocolatey.org` > `choco install miniconda3`

Switched then to 
```
conda config --add channels conda-forge
conda update --all
conda install jupyter notebook
```

```
$ conda info

     active environment : None
       user config file : C:\Users\spex6\.condarc
 populated config files : C:\Users\spex6\.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\tools\miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\tools\miniconda3\pkgs
                          C:\Users\spex6\AppData\Local\conda\conda\pkgs
       envs directories : C:\tools\miniconda3\envs
                          C:\Users\spex6\AppData\Local\conda\conda\envs
                          C:\Users\spex6\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

running `ipython` 
```
In [4]: from zmq import backend
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-9875ebe2007f> in <module>
----> 1 from zmq import backend

C:\tools\miniconda3\lib\site-packages\zmq\__init__.py in <module>
     45 # zmq top-level imports
     46
---> 47 from zmq import backend
     48 from zmq.backend import *
     49 from zmq import sugar

C:\tools\miniconda3\lib\site-packages\zmq\backend\__init__.py in <module>
     38             # raise the *first* error, not the fallback
     39             from zmq.utils.sixcerpt import reraise
---> 40             reraise(*exc_info)
     41
     42 globals().update(_ns)

C:\tools\miniconda3\lib\site-packages\zmq\utils\sixcerpt.py in reraise(tp, value, tb)
     32         if value.__traceback__ is not tb:
     33             raise value.with_traceback(tb)
---> 34         raise value
     35
     36 else:

C:\tools\miniconda3\lib\site-packages\zmq\backend\__init__.py in <module>
     25
     26     try:
---> 27         _ns = select_backend(first)
     28     except Exception:
     29         exc_info = sys.exc_info()

C:\tools\miniconda3\lib\site-packages\zmq\backend\select.py in select_backend(name)
     25     """Select the pyzmq backend"""
     26     try:
---> 27         mod = __import__(name, fromlist=public_api)
     28     except ImportError:
     29         raise

C:\tools\miniconda3\lib\site-packages\zmq\backend\cython\__init__.py in <module>
      4 # Distributed under the terms of the Lesser GNU Public License (LGPL).
      5
----> 6 from . import (constants, error, message, context,
      7                       socket, utils, _poll, _version, _device )
      8

ImportError: DLL load failed: The specified module could not be found.
```

**Comment by Pattingerr** [comment] 2018-12-18 11:05
@spex66 i reopened it. I closed it because if im using the Anaconda Prompt, everything works. I used GitBash for Windows, thats where the error occured. You also using Anaconda Prompt?

**Comment by spex66** [comment] 2018-12-18 11:11
Just was able to fix it!

In my case I wasn't aware that I have to add THREE miniconda related paths to PATH env-variable

```
C:\tools\miniconda3
C:\tools\miniconda3\Scripts
C:\tools\miniconda3\Library\bin
```
Found the last one pointing to `Library\bin` on stackoverflow, which I've missed previously.
After that the problem is gone.

Hope it works for you too

**Comment by spex66** [comment] 2018-12-18 11:17
and no I was using simple CMD shell (ConEmu) not "anaconda shell", which is why I had to extend the PATH manually. The Anaconda Shell is doing this for you.

**Comment by mingwandroid** [comment] 2018-12-18 15:35
We do not support using our software outside of proper activation (anaconda prompt, navigator, manually running the activation scripts *).

*

cmd.exe: `<ROOT_OF_ANACONDA>\Scripts\activate.bat`
MSYS2 (or Git for Windows): `source <ROOT_OF_ANACONDA>/Scripts/activate`

MSYS2 is  better supported than Git for Windows but likely either will work fine.

Closing as out of scope.

**Closed by mingwandroid** 2018-12-18 15:35 UTC

**Comment by avinaashdhumal** [comment] 2020-03-25 16:49
pip uninstall pyzmq
pip install pyzmq
It works for me I hope it will work for you

**Comment by prusswan** [comment] 2022-11-09 08:34
> pip uninstall pyzmq pip install pyzmq It works for me I hope it will work for you

This worked for me. conda offered `23.2.0` (which led to the error) but pip installed `24.0.1`
