### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by louisdv75** [ContinuumIO/anaconda-issues#2116] opened 2017-06-09 15:43 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=457)
## Traceback
```
Traceback (most recent call last):
  File "/Users/louisdevitry/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/louisdevitry/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/louisdevitry/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/louisdevitry/anaconda/lib/python2.7/site-packages/psutil/__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "/Users/louisdevitry/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 306, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=457)

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.0.0;Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-06-09 17:31
Closing as duplicate of #1984

**Closed by goanpeca** 2017-06-09 17:31 UTC
Labels: pkg:navigator, reso:duplicate
