### ISSUE TITLE
serious numpy numerical error/inconsistency on macOS

### ISSUE THREAD

**Issue by cod3licious** [ContinuumIO/anaconda-issues#9460] opened 2018-05-26 23:48 UTC
I get very very strange numerical inconsistencies like these:
<img width="789" alt="screen shot 2018-05-27 at 0 29 08" src="https://user-images.githubusercontent.com/1093567/40580834-df8b364e-6147-11e8-9b4d-4f6aa0300643.png">
I could reproduce this in ipython and jupyter notebook but only on macOS, not on Linux. Here is a gist with [code to reproduce the error](https://gist.github.com/cod3licious/d2926e0bdc1355f0a921ac083d2799eb) (Note that you need to download and unzip a file first and then appropriately copy your value of `vec_x` to `a`.) The error also happens for `np.dot` and possibly other functions.

My system specs:
macOS 10.13.4 (17E202) 
Python 3.6.4 :: Anaconda custom (64-bit)
jupyter-notebook 5.4.0
ipython 6.2.1
numpy 1.14.2
gensim 3.4.0

This is a cross post from this [numpy issue](https://github.com/numpy/numpy/issues/11166) and this [jupyter notebook issue](https://github.com/jupyter/notebook/issues/3641) (as I really don't know who's the culprit in the end).

**Edit:** I first had Python 2.7 installed with anaconda and then created a new environment with `conda create -n python36 python=3.6 anaconda`. In this new environment, I have conda version 4.5.4 and when I tried to run `anaconda --version` (and `anaconda --help` and just `anaconda`), instead of the version number I got an error like this:
```
(python36) ~ % anaconda --help
Traceback (most recent call last):
  File "/Users/franzi/anaconda/envs/python36/bin/anaconda", line 11, in <module>
    sys.exit(main())
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/scripts/cli.py", line 160, in main
    description=__doc__, version=version)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/scripts/cli.py", line 127, in binstar_main
    add_subparser_modules(parser, sub_command_module, 'conda_server.subcommand')
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/clyent/__init__.py", line 134, in add_subparser_modules
    command_module.add_parser(subparsers)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 378, in add_parser
    parser.set_defaults(auto_register=bool(get_config().get('auto_register', True)))
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/utils/config.py", line 223, in <genexpr>
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/Users/franzi/anaconda/envs/python36/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/franzi/Library/Application Support/binstar/config.yaml", line 1, column 1
```
Besides this, I get:
```
(python36) ~ % conda list anaconda
# packages in environment at /Users/franzi/anaconda/envs/python36:
#
# Name                    Version                   Build  Channel
anaconda                  custom           py36ha4fed55_0  
anaconda-client           1.6.9                    py36_0  
anaconda-project          0.8.2            py36h9ee5d53_0
```
and I really don't know where this "custom" version comes from as I just followed they guidelines on the anaconda website on how to manage multiple python versions...

**Edit 2:** When I execute the code in the plain and basic python command line interpreter (the one that was installed with anaconda when I created the python 3.6 environment), this error does not happen. Not quite sure what this means exactly but it's probably not exactly a numpy issue then.

**Comment by cod3licious** [comment] 2018-05-27 15:34
Ok, here is a much simpler piece of code to reproduce the error:
```python
#import IPython
#import PyQt5.QtWidgets
import numpy as np
a = np.ones([2])
print(a.dtype)                   # float64
print(np.linalg.norm(a))         # 1.4142135623730951
b = np.array(a, dtype=np.float32)
print(np.linalg.norm(b))         # 0.0
```
In IPython or jupyter-notebook this gives the wrong results and in plain python the wrong results can be reproduced by importing either `IPython` or `PyQt5.QtWidgets` _before_ numpy. 
This seems to be closely related to this issue: https://github.com/ContinuumIO/anaconda-issues/issues/1461

**Comment by cod3licious** [comment] 2018-05-27 19:50
in case it helps, these are my numpy configurations:
<img width="585" alt="screen shot 2018-05-27 at 21 33 59" src="https://user-images.githubusercontent.com/1093567/40589890-e5d7e9c6-61f5-11e8-88fc-9e77232461a6.png">

**Comment by msarahan** [comment] 2018-05-29 14:48
duplicate of https://github.com/numpy/numpy/issues/9758; closing.

**Closed by msarahan** 2018-05-29 14:48 UTC

**Comment by cod3licious** [comment] 2018-05-29 22:05
umm...are you actually going to do anything about this? the other issue that you referenced was reported more than half a year ago and nothing seems to have changed since then. getting grossly inaccurate results for something as basic as a dot product seems to me like a very serious issue that someone should really try to fix. i mean, can i just not use anaconda to install python on mac anymore?!

**Comment by msarahan** [comment] 2018-05-29 23:49
We can't.  This is a detail of how OSX loads libraries.  If you load a GUI library first, Accelerate populates the namespace.  MKL comes along later and says "great, let me just call that function."  Boom, dumb stuff happens.  If you read the thread I linked, you'll see that Intel has developed a fix, and it'll be in the next MKL update release.

https://github.com/numpy/numpy/issues/9758#issuecomment-370809277

**Comment by cod3licious** [comment] 2018-05-30 07:40
ok, thanks - i really hope that update will be out soon!

**Comment by paulthebaker** [comment] 2018-07-30 18:39
@msarahan says in this [thread](https://github.com/numpy/numpy/issues/9758) that the "most recent mkl build" has a fix for this.  Can someone confirm the minimum version number or the specific build number that contains the fix?

**Comment by mingwandroid** [comment] 2018-07-30 18:43
`conda update mkl` will get you this information.

**Comment by a-jacobo** [comment] 2018-10-08 13:48
I'm still having this issue with the last versions of Numpy (1.15.2) and MKL (2019.0, build 118) both using Python 2.7 and 3.6. If I import just numpy it works fine but if I import iPython first and then numpy I get:

`RuntimeError: The current Numpy installation ('/Users/ajacobo/anaconda2/envs/opencv3/lib/python2.7/site-packages/numpy/__init__.pyc') fails to pass simple sanity checks. This can be caused for example by incorrect BLAS library being linked in.`

**Comment by msarahan** [comment] 2018-10-08 13:51
Should be MKL 2018 update 3 or higher.

@a-jacobo where does your opencv come from?  If it is built against openblas, that might be the problem.

**Comment by a-jacobo** [comment] 2018-10-08 14:36
Oh, I ran it in the opencv environment because I happened to be working with it at the time, but I get the same error in the base environment of my freshly installed anaconda installation macOs High Sierra. Here is the full output from my base environment:

`Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import IPython
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajacobo/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 227, in <module>
    _sanity_check()
  File "/Users/ajacobo/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 225, in _sanity_check
    raise RuntimeError(msg.format(__file__))
RuntimeError: The current Numpy installation ('/Users/ajacobo/anaconda2/lib/python2.7/site-packages/numpy/__init__.pyc') fails to pass simple sanity checks. This can be caused for example by incorrect BLAS library being linked in.`

And the MKL is the one that comes installed by default, which is version 2019.

**Comment by msarahan** [comment] 2018-10-08 14:53
There's definitely something wrong - perhaps incorrect blas libraries getting preferentially loaded by your system somehow.  That's really beyond our ability to troubleshoot or support, unfortunately.  You may find DTrace helpful for figuring out what is happening: https://8thlight.com/blog/colin-jones/2015/11/06/dtrace-even-better-than-strace-for-osx.html

**Comment by a-jacobo** [comment] 2018-10-08 15:03
I see, thanks... This also seems beyond my ability to troubleshoot. This problem means that in a fresh anaconda installation I can't import numpy in a Jupyter Notebook, I wonder if other people are having the same issue.

**Comment by a-jacobo** [comment] 2019-03-15 15:27
The problem can be solved by following the steps described here: 

https://github.com/numpy/numpy/issues/11481#issuecomment-429153833
