### ISSUE TITLE
Navigator Error with 403 status code while Startup

### ISSUE THREAD

**Issue by skybird2022** [ContinuumIO/anaconda-issues#13002] opened 2022-07-25 14:26 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

Hi Conda Technical Support Team,

1. Escalate Navigator Error with 403 status code in following error messages while Startup "Anaconda Navigator"  for your investigation.

2. I tried to execute following commands in "Anaconda Prompt", it's not workable. 
(1) conda update anaconda-navigator
(2) anaconda-navigator --reset
(3) conda update anaconda-client
(4) conda update -f anaconda-client
(5) conda update conda
(6) conda update --all

3. I also searched all related solutions from website, e.g  naname from ..condarc to .old,   from config.yaml to config.old, it's not workable too. 

4. I visited url : https://api.anaconda.org/user, there is a error message return as "Authorization header was not given", it looks like a api error. 

Please look into this bug report and provide your professional guideline/solution. Thanks !

// Quote //

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)
Traceback
Traceback (most recent call last):
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 133, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 248, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\Administrator\AppData\Roaming\.anaconda\navigator\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 143, in start_app
    msgbox = MessageBoxInformation(
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 521, in __init__
    super().__init__(*args, type_=self.INFORMATION_BOX, title=title, text=text, parent=parent, **kwargs)
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 338, in __init__
    self.tracker = GATracker() if analytics else None
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 253, in GATracker
    GA_TRACKER = _GATracker()
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 89, in __init__
    self.api = AnacondaAPI()
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1168, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 683, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 145, in __init__
    self.reload_client()
  File "G:\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 360, in reload_client
    client.user()
  File "G:\anaconda3\lib\site-packages\binstar_client\__init__.py", line 241, in user
    self._check_response(res)
  File "G:\anaconda3\lib\site-packages\binstar_client\__init__.py", line 226, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403) 

// Unquote//

### Conda info

```shell
active environment : base
    active env location : G:\anaconda3
            shell level : 1
       user config file : C:\Users\Administrator\.condarc
 populated config files : C:\Users\Administrator\.condarc
          conda version : 4.13.0
    conda-build version : 3.21.9
         python version : 3.8.13.final.0
       virtual packages : __cuda=9.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : G:\anaconda3  (writable)
      conda av data dir : G:\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : G:\anaconda3\pkgs
                          C:\Users\Administrator\.conda\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
       envs directories : G:\anaconda3\envs
                          C:\Users\Administrator\.conda\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.8.13 Windows/7
Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> C:\Users\Administrator\.condarc <==
ssl_verify: True
channels:
  - defaults
```

### Conda list

```shell
icu                       58.2                 ha925a31_3    defaults
idna                      2.6                      pypi_0    pypi
imagecodecs               2021.3.31        py38h5da4933_0    defaults
imageio                   2.9.0              pyhd3eb1b0_0    defaults
imagesize                 1.4.1            py38haa95532_0    defaults
importlib-metadata        4.11.3           py38haa95532_0    defaults
importlib_metadata        4.11.3               hd3eb1b0_0    defaults
importlib_resources       5.2.0              pyhd3eb1b0_1    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
intel-openmp              2021.4.0          haa95532_3556    defaults
intervaltree              3.1.0              pyhd3eb1b0_0    defaults
ipykernel                 6.9.1            py38haa95532_0    defaults
ipython                   8.4.0            py38haa95532_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.5              pyhd3eb1b0_1    defaults
isort                     5.9.3              pyhd3eb1b0_0    defaults
itsdangerous              1.1.0              pyhd3eb1b0_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.17.2           py38haa95532_1    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
joblib                    1.0.1              pyhd3eb1b0_0    defaults
jpeg                      9e                   h2bbff1b_0    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonschema                4.4.0            py38haa95532_0    defaults
jupyter                   1.0.0                    py38_7    defaults
jupyter-packaging         0.7.12             pyhd3eb1b0_0    defaults
jupyter_client            7.2.2            py38haa95532_0    defaults
jupyter_console           6.4.0              pyhd3eb1b0_0    defaults
jupyter_core              4.10.0           py38haa95532_0    defaults
jupyter_server            1.17.1           py38haa95532_0    defaults
jupyterlab                3.3.2              pyhd3eb1b0_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.10.3             pyhd3eb1b0_1    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
keyring                   23.4.0           py38haa95532_0    defaults
kiwisolver                1.4.2            py38hd77b12b_0    defaults
krb5                      1.18.2               hc04afaa_0    defaults
lazy-object-proxy         1.6.0            py38h2bbff1b_0    defaults
lcms2                     2.12                 h83e58a3_0    defaults
lerc                      2.2.1                hd77b12b_0    defaults
libaec                    1.0.4                h33f27b4_1    defaults
libarchive                3.4.2                h5e25573_0    defaults
libcurl                   7.71.1               h2a8f88b_1    defaults
libdeflate                1.7                  h2bbff1b_5    defaults
libiconv                  1.16                 h2bbff1b_2    defaults
liblief                   0.11.5               hd77b12b_1    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libspatialindex           1.9.3                h6c2663c_0    defaults
libssh2                   1.9.0                h7a1dbc1_1    defaults
libtiff                   4.2.0                hd0e1b90_0    defaults
libwebp                   1.2.2                h2bbff1b_0    defaults
libxml2                   2.9.14               h0ad7f3c_0    defaults
libxslt                   1.1.34               he774522_0    defaults
libzopfli                 1.0.3                ha925a31_0    defaults
llvmlite                  0.36.0           py38h34b8924_4    defaults
locket                    1.0.0            py38haa95532_0    defaults
lxml                      4.6.3            py38h9b66d53_0    defaults
lz4-c                     1.9.3                h2bbff1b_1    defaults
lzo                       2.10                 he774522_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                2.0.1            py38h2bbff1b_0    defaults
matplotlib                3.5.1            py38haa95532_1    defaults
matplotlib-base           3.5.1            py38hd77b12b_1    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mccabe                    0.6.1                    py38_1    defaults
menuinst                  1.4.18           py38h59b6b97_0    defaults
mistune                   0.8.4           py38he774522_1000    defaults
mkl                       2021.4.0           haa95532_640    defaults
mkl-service               2.4.0            py38h2bbff1b_0    defaults
mkl_fft                   1.3.1            py38h277e83a_0    defaults
mkl_random                1.2.2            py38hf11a4ad_0    defaults
mlxtend                   0.19.0                   pypi_0    pypi
mock                      4.0.3              pyhd3eb1b0_0    defaults
more-itertools            8.12.0             pyhd3eb1b0_0    defaults
mouseinfo                 0.1.3                    pypi_0    pypi
mpmath                    1.2.1            py38haa95532_0    defaults
msgpack-python            1.0.3            py38h59b6b97_0    defaults
mss                       6.1.0                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py38_0    defaults
munkres                   1.1.4                      py_0    defaults
mypy_extensions           0.4.3            py38haa95532_1    defaults
navigator-updater         0.2.1                    py38_1    defaults
nbclassic                 0.3.5              pyhd3eb1b0_0    defaults
nbclient                  0.5.13           py38haa95532_0    defaults
nbconvert                 6.4.4            py38haa95532_0    defaults
nbformat                  5.3.0            py38haa95532_0    defaults
nest-asyncio              1.5.5            py38haa95532_0    defaults
networkx                  2.8.4            py38haa95532_0    defaults
nltk                      3.6.1              pyhd3eb1b0_0    defaults
nose                      1.3.7           pyhd3eb1b0_1006    defaults
notebook                  6.4.11           py38haa95532_0    defaults
numba                     0.53.1           py38hf11a4ad_0    defaults
numexpr                   2.8.3            py38hb80d3ca_0    defaults
numpy                     1.22.3           py38h7a0a035_0    defaults
numpy-base                1.22.3           py38hca35cd5_0    defaults
numpydoc                  1.4.0            py38haa95532_0    defaults
olefile                   0.46                       py_0    defaults
opencv-contrib-python     4.5.5.64                 pypi_0    pypi
opencv-python             4.5.4.58                 pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0    defaults
openpyxl                  3.0.7              pyhd3eb1b0_0    defaults
openssl                   1.1.1q               h2bbff1b_0    defaults
outcome                   1.1.0                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.4.3            py38hd77b12b_0    defaults
pandoc                    2.12                 haa95532_0    defaults
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
paramiko                  2.8.1              pyhd3eb1b0_0    defaults
parsel                    1.6.0                    pypi_0    pypi
parso                     0.7.0                      py_0    defaults
partd                     1.2.0              pyhd3eb1b0_1    defaults
path                      15.1.2           py38haa95532_0    defaults
path.py                   12.5.0                        0    defaults
pathlib2                  2.3.5            py38haa95532_2    defaults
pathspec                  0.7.0                      py_0    defaults
patsy                     0.5.1                    py38_0    defaults
pefile                    2021.9.3                 pypi_0    pypi
pep8                      1.7.1                    py38_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.2.0            py38hdc2b20a_1    defaults
pip                       22.1.2           py38haa95532_0    defaults
pkginfo                   1.8.2              pyhd3eb1b0_0    defaults
platformdirs              2.4.0              pyhd3eb1b0_0    defaults
pluggy                    1.0.0            py38haa95532_1    defaults
ply                       3.11                     py38_0    defaults
powershell_shortcut       0.0.1                         3    defaults
prettytable               2.4.0                    pypi_0    pypi
prometheus_client         0.13.1             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.17             pyhca03da5_0    defaults
prompt_toolkit            3.0.17               hd3eb1b0_0    defaults
psutil                    5.9.0            py38h2bbff1b_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
py                        1.11.0             pyhd3eb1b0_0    defaults
py-lief                   0.11.5           py38hd77b12b_1    defaults
pyautogui                 0.9.53                   pypi_0    pypi
pycodestyle               2.6.0              pyhd3eb1b0_0    defaults
pycosat                   0.6.3            py38h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pycurl                    7.43.0.6         py38h7a1dbc1_0    defaults
pydocstyle                6.1.1              pyhd3eb1b0_0    defaults
pydub                     0.25.1                   pypi_0    pypi
pyecharts                 1.1.0                    pypi_0    pypi
pyerfa                    2.0.0            py38h2bbff1b_0    defaults
pyflakes                  2.2.0              pyhd3eb1b0_0    defaults
pygetwindow               0.0.9                    pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyinstaller               4.5.1                    pypi_0    pypi
pyinstaller-hooks-contrib 2021.3                   pypi_0    pypi
pyjwt                     2.4.0            py38haa95532_0    defaults
pylint                    2.12.2           py38haa95532_1    defaults
pyls-black                0.4.6                hd3eb1b0_0    defaults
pyls-spyder               0.3.2              pyhd3eb1b0_0    defaults
pymsgbox                  1.0.9                    pypi_0    pypi
pymysql                   1.0.2                    pypi_0    pypi
pynacl                    1.4.0            py38h62dcd97_1    defaults
pyodbc                    4.0.30           py38ha925a31_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyperclip                 1.8.2                    pypi_0    pypi
pypng                     0.0.21                   pypi_0    pypi
pyqrcode                  1.2.1                    pypi_0    pypi
pyqt                      5.9.2            py38hd77b12b_6    defaults
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyreadline                2.1                      py38_1    defaults
pyrect                    0.1.4                    pypi_0    pypi
pyrsistent                0.18.0           py38h196d8e1_0    defaults
pyscreeze                 0.1.28                   pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0    defaults
pytables                  3.6.1            py38ha5be198_0    defaults
pytesseract               0.3.8                    pypi_0    pypi
pytest                    6.2.3            py38haa95532_2    defaults
python                    3.8.13               h6244533_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-docx               0.8.11                   pypi_0    pypi
python-fastjsonschema     2.15.1             pyhd3eb1b0_0    defaults
python-jsonrpc-server     0.4.0                      py_0    defaults
python-language-server    0.36.2             pyhd3eb1b0_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytweening                1.0.4                    pypi_0    pypi
pytz                      2022.1           py38haa95532_0    defaults
pywavelets                1.3.0            py38h2bbff1b_0    defaults
pywin32                   302              py38h2bbff1b_2    defaults
pywin32-ctypes            0.2.0                 py38_1000    defaults
pywinauto                 0.6.3                    pypi_0    pypi
pywinpty                  2.0.2            py38h5da7b33_0    defaults
pyyaml                    5.3                      pypi_0    pypi
pyzmq                     23.2.0           py38hd77b12b_0    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 1.0.3              pyhd3eb1b0_0    defaults
qtconsole                 5.3.1            py38haa95532_0    defaults
qtpy                      2.0.1              pyhd3eb1b0_0    defaults
regex                     2022.7.9         py38h2bbff1b_0    defaults
requests                  2.27.1                   pypi_0    pypi
retry                     0.9.2                    pypi_0    pypi
rope                      0.22.0             pyhd3eb1b0_0    defaults
rtree                     0.9.7            py38h2eaa2aa_1    defaults
ruamel_yaml               0.15.100         py38h2bbff1b_0    defaults
scikit-image              0.18.1           py38hf11a4ad_0    defaults
scipy                     1.7.3            py38h0a974cb_0    defaults
selenium                  4.1.0                    pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                61.2.0           py38haa95532_0    defaults
simplegeneric             0.8.1                    py38_2    defaults
simplejson                3.17.6                   pypi_0    pypi
singledispatch            3.6.1           pyhd3eb1b0_1001    defaults
sip                       4.19.13          py38hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
snappy                    1.1.9                h6c2663c_0    defaults
sniffio                   1.2.0            py38haa95532_1    defaults
snowballstemmer           2.2.0              pyhd3eb1b0_0    defaults
sortedcollections         2.1.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
spark-parser              1.8.9                    pypi_0    pypi
sphinx                    5.0.2            py38haa95532_0    defaults
sphinxcontrib             1.0                      py38_1    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaults
sphinxcontrib-websupport  1.2.4                      py_0    defaults
spyder                    4.2.5            py38haa95532_0    defaults
spyder-kernels            1.10.2           py38haa95532_0    defaults
sqlalchemy                1.4.7            py38h2bbff1b_0    defaults
sqlite                    3.38.5               h2bbff1b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
sympy                     1.8              py38haa95532_0    defaults
tbb                       2020.3               h74a9793_0    defaults
tblib                     1.7.0              pyhd3eb1b0_0    defaults
tencentcloud-sdk-python   3.0.569                  pypi_0    pypi
terminado                 0.13.1           py38haa95532_0    defaults
testpath                  0.6.0            py38haa95532_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tifffile                  2020.10.1        py38h8c2d366_2    defaults
tinyaes                   1.0.1                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.11.2             pyhd3eb1b0_0    defaults
tornado                   6.1              py38h2bbff1b_0    defaults
tqdm                      4.64.0           py38haa95532_0    defaults
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
trio                      0.19.0                   pypi_0    pypi
trio-websocket            0.9.2                    pypi_0    pypi
typed-ast                 1.4.3            py38h2bbff1b_1    defaults
typing-extensions         4.1.1                hd3eb1b0_0    defaults
typing_extensions         4.1.1              pyh06a4308_0    defaults
ujson                     5.4.0            py38hd77b12b_0    defaults
uncompyle6                3.7.4                    pypi_0    pypi
unicodecsv                0.14.1                   py38_0    defaults
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
w3lib                     1.22.0                   pypi_0    pypi
watchdog                  1.0.2            py38haa95532_1    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py38_1    defaults
websocket-client          0.58.0           py38haa95532_4    defaults
werkzeug                  1.0.1              pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.2            py38haa95532_0    defaults
win_inet_pton             1.1.0            py38haa95532_0    defaults
win_unicode_console       0.5                      py38_0    defaults
wincertstore              0.2              py38haa95532_2    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.13.3           py38h2bbff1b_2    defaults
wsproto                   1.0.0                    pypi_0    pypi
xdis                      5.0.13                   pypi_0    pypi
xlrd                      2.0.1              pyhd3eb1b0_0    defaults
xlsxwriter                1.3.8              pyhd3eb1b0_0    defaults
xlwings                   0.23.0           py38haa95532_0    defaults
xlwt                      1.3.0                    py38_0    defaults
xmltodict                 0.12.0                     py_0    defaults
xz                        5.2.5                h8cc25b3_1    defaults
yaml                      0.2.5                he774522_0    defaults
yapf                      0.31.0             pyhd3eb1b0_0    defaults
zeromq                    4.3.4                hd77b12b_0    defaults
zfp                       0.5.5                hd77b12b_6    defaults
zict                      2.1.0            py38haa95532_0    defaults
zipp                      3.8.0            py38haa95532_0    defaults
zlib                      1.2.12               h8cc25b3_2    defaults
zope                      1.0                      py38_1    defaults
zope.event                4.5.0                    py38_0    defaults
zope.interface            5.3.0            py38h2bbff1b_0    defaults
zstd                      1.4.9                h19a0ad4_0    defaults
```

### Additional Context

No, thanks

**Comment by vshevchenko-anaconda** [comment] 2022-09-09 12:02
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/12415

**Closed by vshevchenko-anaconda** 2022-09-09 12:02 UTC
Labels: type-bug, reso-duplicate, pkg-navigator
