### ISSUE TITLE
Another Anaconda-Navigator Start up Error

### ISSUE THREAD

**Issue by marmot2019** [ContinuumIO/anaconda-issues#3696] opened 2017-07-29 17:42 UTC
I just installed Anaconda 4.4 on my computer (Ubuntu 16.04 LTS) and everything seems OK when I start up from the terminal (i.e. type 'anaconda-navigator').  I wanted to make a "menu" entry for gnome 3 and I think I got it right using the following in my applications directory (i.e. Anaconda-Navigator.desktop)

[Desktop Entry]
Type=Application
Name=Anaconda Navigator
Exec=/home/marmot/anaconda3/bin/anaconda-navigator
Icon=/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/static/images/anaconda-logo.svg
Terminale=false
Catagories=Development;Science

This shows up on my menu, but when I go to use it, I get the following error message:

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

byte indices must be integers or slices, not str
Traceback

Traceback (most recent call last):
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/marmot/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-07-29 17:42
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-29 17:42 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by marmot2019** [comment] 2017-07-29 18:10
Thanks for your prompt reply, but I still get the same problem even after updating anaconda-navigator. J
