### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jphair2** [ContinuumIO/anaconda-issues#11474] opened 2019-11-24 13:22 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;19.0.0;Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by csoja** [comment] 2019-12-02 19:41
Duplicate of #1778
Please see that issue for the solution.

**Closed by csoja** 2019-12-02 19:41 UTC
