### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by pedrojunqueira** [ContinuumIO/anaconda-issues#10790] opened 2019-04-03 10:16 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
python: 3.6.2
language: en
os: Darwin;18.5.0;Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.24
```

**Comment by csoja** [comment] 2019-04-25 16:56
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1778
Please see that issue for the solution.

**Closed by csoja** 2019-04-25 16:56 UTC
