### ISSUE TITLE
Failed to create Anaconda Menus

### ISSUE THREAD

**Issue by danfp35** [ContinuumIO/anaconda-issues#2395] opened 2017-06-19 11:03 UTC
Hi, 

I've been working with anaconda 4.4.0 (python 2.7) for several months. However, one day my anti-virus (kaspersky) found that  something in spyder folder was potentially dangerous and deleted it. After that it didn't work anymore.  I tried to uninstall and reinstall. Nevertheless,  at the end of the re-installation, appeared two warning issues: First, ''Failed to create Anaconda Menus" and ''Failed to initialize Anaconda Dirctories''. After that, it seems that the installation has ended correctly. But, there are no apps (so I cannot use spyder). 

I think the problem comes because  Ananconda uninstaller  does leave something in my computer which interferes with the new installation, I have tried evertything I've thought, but problem persists. 
Any help would be terrific! I'm desperate!

Thanks

![2017-06-19 1](https://user-images.githubusercontent.com/29165821/27282293-9d5ee5e6-54ef-11e7-900c-4b7781ba696a.png)
![2017-06-19](https://user-images.githubusercontent.com/29165821/27282294-9d61658c-54ef-11e7-9d49-ea32f7d13c30.png)

**Comment by y2kbugger** [comment] 2017-06-22 20:06
This is a duplicate of 732

**Comment by TutCanada** [comment] 2017-09-06 19:05
I had this same problem on an initial installation in Windows 10, while installing from the executable Anaconda3-4.4.0-Windows-x86_64.exe.   After trying several of the proposed solutions in these pages, the one that worked for me was to do a clean install with the Virus Checker in Windows Defender turned OFF.
I installed for current user only (no administrator priviledges). Before that, I uninstalled (from Control Panel > uninstall > Python 3.6.0 (Anaconda3 4.3.1 64-bit)), then check that my Anaconda3 directory was empty.  The installer completed without complaining, and I can start Spyder from the Windows start button.

**Comment by AshutoshPhatak** [comment] 2017-10-09 13:36
duplicate of #732 but would still answer because a lot many people are still facing the issue. I tried to fix the issue in isolation, wrt the solution provided in this(and other) thread. 
1. Copy the existing contents from PATH variable and keep it blank, Just enter <;> so as to save it.
2. Retry the installation(latest 5.0.0) and select "All users option"
3. After successful installation, put in the variables taken out from PATH.[had been using a lot of those for selenium, java etc]

**Comment by jhndrx** [comment] 2017-10-17 03:13
**Potential Workaround**
I encountered this issue on several work computers but not my 2 home computers. I kept getting a popup with a 0xc0000022 error when the installer was running pythonw.exe from the temp folder. It appears this error occurs when files are corrupted or do not have proper permissions. It might explain why some are able to get past the error with admin rights (but not everyone?). Here's a link regarding it. I admit that I didn't thoroughly research this error. Just a precursory look. [https://neosmart.net/wiki/0xc0000022/#About_the_82200xc00000228221_error](url)

I noticed that it kept occurring at the same point in the Anaconda install. Line 56741 on the right shows the rest of the highlighted line on the Anaconda install to the left. 
![pythonw](https://user-images.githubusercontent.com/20349377/31644212-a2c52c9c-b2ba-11e7-90ec-e833de1e5064.PNG)
After it failed, I did not click to continue (since it removes the temp files) and tried running the specified pythonw.exe in the temp folder and it kept giving me the 0xc000022 error. So, I finished out the Anaconda install, ignoring errors and saved a copy of the details as shown in the image. The Anaconda install folder was very bare, only a couple folders and definitely did not have the pythonw.exe file that was trying to be used in lines 56745-56749. So I simply installed python 3.6.3 somewhere not in my Anaconda install folder (just me, not modifying path) and I reran the command on line 56741 using the pythonw.exe included in the separate python install in place of the temporary folder one. Give it a couple of minutes and then run the 3 lines 56745-56748 (Anaconda install location of C:\Anaconda3). and it works fine. Probably best to reboot afterwards but doesn't appear necessary. This included the "add to path" selection from the install.

@msarahan I noticed from #732 that you were looking into this issue. Perhaps this will aide in determining the error. I would definitely look at the code that puts the pythonw.exe in the temporary folder as it might be corrupting it or doing incorrect permissions.

Extra information about previous possible workarounds. I did not have any Java stuff in my environment variables at home or at work. My home computers have less than 1024 characters in the path variable. Work computers have over 1024. I don't know if this affects the install at all but I will mention it for completeness.

**Closed** 2017-10-17 11:47 UTC

**Comment by Es-Sakhi** [comment] 2018-04-29 15:44
After spending more than 2 days on this finally comes to an end. I considered as the most challenging task in 2018 so far. Here is the remedy: (some of this step my not be necessary, however this is the last process I followed in order to get it to work)  
1.	Delete the variables form path all of them (remember to save them somewhere because you well have to put them back.
2.	Download and install Redistributable Package (link below)
https://www.microsoft.com/en-us/download/confirmation.aspx?id=14632
3.	search your computer for any related previously installed python or anaconda and delete them
4.	reboot you PC
5.	go to https://www.anaconda.com/download/#windows download and install Anaconda.
6.	Put back all the variable were in the path previously 
7.	Add the path to the newly installed anaconda
8.	Done

**Comment by msarahan** [comment] 2018-05-08 13:48
@jhndrx thanks for the insight.  Do you have any anti-virus running?  We've seen that anti-virus can trigger this issue by delaying the files actually being present, which may explain your observations.  It seems like we probably need a way to account for that, and build in delays rather than fall over.

@Es-Sakhi @AshutoshPhatak what were your PATH settings before you cleared them?  We're having a hard time reproducing this.  We've tried with long paths and with quotes in the path, but so far we haven't had any luck getting the problem to reliably show up.

**Comment by Sleekery** [comment] 2018-06-21 19:00
I'm getting the same menu error. I've already deleted my paths and tried deleting all folders with anything conda, anaconda, or python related. My only remaining paths are for variables TEMP and TMP.

I'm trying to install Anaconda 5.2.0 on Windows 10. I originally uninstalled Anaconda to reinstall it because I the program suddenly wouldn't work despite not having any updates overnight.

**Comment by vxfranky** [comment] 2019-12-25 08:52
Another solution: install Microsoft Visual C++ Redistributable. Visit https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Abhishekrkd** [comment] 2021-03-08 11:30
i tried every possible method to install and launch anaconda most of the times it wont install showing cannot create menus error and if somehow it gets installed (old version) it wont launch
