### ISSUE TITLE
Error on initial Navigator launch

### ISSUE THREAD

**Issue by cherylt3ll** [ContinuumIO/anaconda-issues#8983] opened 2018-03-22 21:58 UTC
Followed Anaconda install instructions...clicked Navigator to launch from Start menu

Message Received:

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Desdemona\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

Traceback

Traceback (most recent call last):
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 187, in load_config
    data = yaml_load(fd)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\constructor.py", line 125, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\yaml\constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "C:\Users\Desdemona\AppData\Local\ContinuumIO\binstar\config.yaml", line 1, column 1

**Comment by cherylt3ll** [comment] 2018-03-22 23:45
UPDATE: 

Uninstalled Anaconda via Control Panel, restarted computer per instructions. Re-downloaded Anaconda. Re-installed. On this attempt, launched Navigator to receive this message:

Main Error

psutil.AccessDenied (pid=1880)

Traceback

Traceback (most recent call last):
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 705, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\psutil\__init__.py", line 666, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Desdemona\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=1880)


Advisement? TIA

**Comment by goanpeca** [comment] 2018-03-23 00:34
Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #1984 for more information on how to fix this.**

Or you can run on the Terminal or Anaconda prompt:

```
anaconda-navigator --reset
```

**Closed by goanpeca** 2018-03-23 00:34 UTC
