### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by lastrye** [ContinuumIO/anaconda-issues#2219] opened 2017-06-12 22:53 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=7384)
## Traceback
```
Traceback (most recent call last):
  File "D:\PROGRAMING\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\PROGRAMING\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "D:\PROGRAMING\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "D:\PROGRAMING\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "D:\PROGRAMING\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=7384)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.2.13
qt: 5.6.2
language: zh_CN
python: 2.7.13
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-06-12 23:37
Closing as duplicate of #1984

**Closed by goanpeca** 2017-06-12 23:37 UTC
Labels: pkg:navigator, reso:duplicate
