### ISSUE TITLE
Navigator Launch issue: Could not find a suitable TLS CA certificate bundle, invalid path: True

### ISSUE THREAD

**Issue by athenalai** [ContinuumIO/anaconda-issues#12511] opened 2021-07-07 06:17 UTC
### Actual Behavior

An unexpected error occurred on Navigator start-up

### Expected Behavior

Anaconda Navigator stat-up

### Steps to Reproduce

Install anaconda, try to launch app via navigator

### Anaconda or Miniconda version:

Anaconda3-2021.05-MacOSX-x86_64.pkg

### Operating System:

Mac OS 10.15.7

### Main Error

Could not find a suitable TLS CA certificate bundle, invalid path: True

### Traceback(most recent call last):

  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 95, in __init__
    self.reload_client()
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/client_api.py", line 326, in reload_client
    client.user()
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/binstar_client/__init__.py", line 244, in user
    res = self.session.get(url, verify=self.session.verify)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 227, in cert_verify
    raise IOError("Could not find a suitable TLS CA certificate bundle, "
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: True

**Comment by LtDan33** [comment] 2021-08-28 14:50
Thanks for the heads up! This looks like a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/12451. Going to close this out. Can you thumbs up that existing instead? Thanks!

**Closed by LtDan33** 2021-08-28 14:50 UTC

**Comment by guernine24** [comment] 2021-12-31 01:14
same problem
Could not find a suitable TLS CA certificate bundle, invalid path: True
what is the solution?
