### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jneupane12** [ContinuumIO/anaconda-issues#4198] opened 2017-08-13 14:07 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 19:52:33.188 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 19:52:35.519 NotebookApp] Serving notebooks from local directory: /home/jinsei
[I 19:52:35.519 NotebookApp] 0 active kernels 
[I 19:52:35.519 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=ccaed4796f1841ad56104b18eee262e2ed5b3ec8b831a4fe
[I 19:52:35.519 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:52:35.520 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=ccaed4796f1841ad56104b18eee262e2ed5b3ec8b831a4fe
[3192:3229:0813/195236.822104:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[I 19:52:36.874 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;3.13.0-128-generic;#177-Ubuntu SMP Tue Aug 8 11:40:23 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-11-14 20:45
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-14 20:45 UTC
Labels: pkg:navigator, reso:duplicate
