### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by aparnarajath** [ContinuumIO/anaconda-issues#1972] opened 2017-06-05 19:38 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=5944)
## Traceback
```
Traceback (most recent call last):
  File "E:\python\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "E:\python\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "E:\python\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "E:\python\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "E:\python\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "E:\python\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=5944)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-06-08 21:04
Closing as duplicate of #1984

**Closed by goanpeca** 2017-06-08 21:04 UTC
Labels: pkg:navigator, reso:duplicate
