### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by huoyushi** [ContinuumIO/anaconda-issues#7036] opened 2017-11-01 08:22 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

```
## System information
```
python: 3.6.1
language: zh_CN
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-11-01 08:26
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-01 08:26 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by huoyushi** [comment] 2017-11-01 08:58
Thanks a lot first ,I use an proxy cause this problem . when i stop the proxy or disable the SSL verification it works well.
