### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by smartgamer** [ContinuumIO/anaconda-issues#8200] opened 2018-01-19 14:16 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 09:15:55.033 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
[I 09:15:55.658 NotebookApp] The port 8888 is already in use, trying another port.
[I 09:15:55.658 NotebookApp] The port 8889 is already in use, trying another port.
[I 09:15:55.784 NotebookApp] [nb_anacondacloud] enabled
[I 09:15:55.788 NotebookApp] [nb_conda] enabled
[I 09:15:55.870 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 09:15:55.870 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 09:15:55.874 NotebookApp] Serving notebooks from local directory: /home/upsman
[I 09:15:55.874 NotebookApp] 0 active kernels 
[I 09:15:55.874 NotebookApp] The Jupyter Notebook is running at: http://localhost:8890/?token=6e9fcda66a85bb2a0331d2089f1abff21d683771c841f90b
[I 09:15:55.874 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:15:55.875 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=6e9fcda66a85bb2a0331d2089f1abff21d683771c841f90b
[I 09:15:56.321 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[7203:7242:0119/091556.383008:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.

```
## System information
```
language: en_US
python: 3.5.3
platform: linux-64
os: Linux;4.4.0-109-generic;#132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018;x86_64;x86_64
conda: 4.3.30
qt: 5.6.2
pyqt: 5.6.0
version: 1.6.2
```

**Comment by goanpeca** [comment] 2018-01-19 16:05
Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #2098 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-01-19 16:05 UTC
Labels: pkg:navigator, reso:duplicate
