### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ChrisFoufoulides** [ContinuumIO/anaconda-issues#9049] opened 2018-03-31 14:49 UTC
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\foufo\Anaconda3\Scripts\jupyter-lab-script.py", line 3, in <module>
    import jupyterlab.labapp
  File "C:\Users\foufo\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "C:\Users\foufo\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\foufo\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.0
```

**Comment by goanpeca** [comment] 2018-04-01 01:54
Closing as duplicate of #8216

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8216 for more information on how to fix this issue.**

Or try running

```
conda upgrade jupyter_core
```

**Closed by goanpeca** 2018-04-01 01:54 UTC
Labels: pkg:navigator, reso:duplicate
