### ISSUE TITLE
navigator error

### ISSUE THREAD

**Issue by shivangvsingh5** [ContinuumIO/anaconda-issues#9147] opened 2018-04-11 21:39 UTC
getting navigator error after installing anaconda for mac os X ...below are the errors-
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'

**Comment by goanpeca** [comment] 2018-04-12 14:18
Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.11
```

**Closed by goanpeca** 2018-04-12 14:18 UTC
