### ISSUE TITLE
Main Error

### ISSUE THREAD

**Issue by IamRajeev** [ContinuumIO/anaconda-issues#3031] opened 2017-07-10 15:32 UTC
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=328)
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 293, in wrapper
    return fun(self, *args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 356, in cmdline
    return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 306, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=328)

**Comment by goanpeca** [comment] 2017-07-10 15:33
Closing as duplicate of #1984

Please update to the latest version of Navigator.

on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-10 15:33 UTC

**Comment by IamRajeev** [comment] 2017-07-10 15:36
Hi,
Still showing error.

**Comment by goanpeca** [comment] 2017-07-10 15:39
Did you look at #1984 ?
