### ISSUE TITLE
Anaconda-navigator Failure in Fedora 26

### ISSUE THREAD

**Issue by Braveheart53** [ContinuumIO/anaconda-issues#6172] opened 2017-09-27 14:28 UTC
Multiple of these same issues have been posted and closed by the same person, see #1837 yet to my knowledgge no viable solution has been found. 

With the fully updated through conda as suggested as well as 

<pre><code>
./conda update --all
./conda update anaconda-navigator
./conda update navigator-updater
</code></pre>

I have not included anconda in my path as to not interfer with the system version of python, but I have used aliases to run as required. Just to list the full return again with fully update anaconda3 at 1013 EST on 2017-09-27 on a fully up-to-date Fedora 26 x64 KDE spin system with a version downloaded yesterday:

<pre><code>
./anaconda-navigator 

An unexpected error occurred on Navigator start-up byte indices must be integers or slices, not str
Traceback (most recent call last): 
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "/home/xxxx/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

Segmentation fault (core dumped)'
</code></pre>

Running as regular user, running conda for update works either as an alias or within the local bin directory. Do you suggest installing as root or super users and putting in an area such as /opt and giving 777 or 775 permissions? Current permissions are 775 with local user as and user group as owner (seen in code above as xxxx) and it is located within the home directory of the user.

**Comment by goanpeca** [comment] 2017-09-27 14:30
> Do you suggest installing as root or super users and putting in an area such as /opt and giving 777 or 775 permissions? 

No, we advice current user. Anaconda does not require sudo or admin to run/install.

**Comment by goanpeca** [comment] 2017-09-27 14:33
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-27 14:33 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by Braveheart53** [comment] 2017-09-27 14:35
As stated in the post, #1837 gives no viable solution. I have followed exactly as it has said and do not find it fixes the issue. Please stop closing these issues until a true solution is found. There have been many reposts of this issue due to this problem.

**Comment by goanpeca** [comment] 2017-09-27 14:39
@Braveheart53 we just released Anaconda Distribution 5.0 which includes major improvements in different aspects. I recommend you install this, for the current user only (on whatever OS you are using) 

https://www.anaconda.com/download/

**Comment by Braveheart53** [comment] 2017-09-27 14:47
I will say activating the root environment by
`source activate root`
does allow me to run the navigator, but I don't view this a good solution.

I will try 5.0 and comment on it as well. Any tips on installing the new and removing the previous version?

**Comment by goanpeca** [comment] 2017-09-27 14:50
@Braveheart53 the thing is that if an environment is not properly activated, some packages under some circumstances cannot run (navigator in this case). And sometimes just adding the anaconda pefix to the PATH does not seem to cut it on some Linux Distros. The new Navigator actually checks this and will tell you to properly activate the environment by doing

`source activate root` which is what really ensure not only the PATH is set correctly, but othe activate scripts from other packages.

Please test 5.0.0 and let us know how it goes :-)

Cheers, and sorry for the inconveniences.

**Comment by Braveheart53** [comment] 2017-09-27 14:55
No problem, it is stated in the new install section [here](https://docs.anaconda.com/anaconda/faq#distribution-faq-linux-path) that is must be in the path. But I have had problems with this OS and mini-conda on a raspberry doing this. So will it run well if I just activate the environment and not add it to the path so that python in the system will be used otherwise? 

Essentially, I create an alias such as anaPython to use anaconda and keep it separate of the system python. I would be great if anaconda could interface directly with the system python in a separate environment to control that as well and ensure it is at the correct version etc.

It seems to me that in a linux distribution, adding this to the path can be an issue, at least adding before other python paths (/usr/bin for example).

**Comment by Braveheart53** [comment] 2017-09-27 14:59
Install the new version as suggested with the following command:
`./Anaconda3-5.0* -u`

Returned this:

<pre><code>
PREFIX=/home/xxxx/anaconda3
installing: python-3.6.2-h02fb82a_12 ...
Python 3.6.2 :: Anaconda custom (64-bit)
installing: ca-certificates-2017.08.26-h1d4fec5_0 ...
installing: conda-env-2.6.0-h36134e3_1 ...
installing: intel-openmp-2018.0.0-h15fc484_7 ...
installing: libgcc-ng-7.2.0-hcbc56d2_1 ...
installing: libgfortran-ng-7.2.0-h6fcbd8e_1 ...
installing: libstdcxx-ng-7.2.0-h24385c6_1 ...
installing: expat-2.2.4-hc00ebd1_1 ...
installing: gmp-6.1.2-hb3b607b_0 ...
installing: graphite2-1.3.10-hc526e54_0 ...
installing: icu-58.2-h211956c_0 ...
installing: jbig-2.1-hdba287a_0 ...
installing: jpeg-9b-habf39ab_1 ...
installing: libffi-3.2.1-h4deb6c0_3 ...
installing: libsodium-1.0.13-h31c71d8_2 ...
installing: libssh2-1.8.0-h8c220ad_2 ...
installing: libtool-2.4.6-hd50d1a6_0 ...
installing: libxcb-1.12-he6ee5dd_2 ...
installing: lzo-2.10-hc0eb8fc_0 ...
installing: mkl-2018.0.0-hb491cac_4 ...
installing: ncurses-6.0-h06874d7_1 ...
installing: openssl-1.0.2l-h9d1a558_3 ...
Error: old string incorrect `SLDIR: "/home/wwallace/anaconda3/ssl"'
Error: post-link failed for: openssl-1.0.2l-h9d1a558_3
</code></pre>

**Comment by Braveheart53** [comment] 2017-09-27 15:07
After completely removing anaconda3 install folder and .anaconda and then running the install command, installation went well.

**Comment by goanpeca** [comment] 2017-09-27 15:11
>So will it run well if I just activate the environment and not add it to the path so that python in the system will be used otherwise?

Yes, it will work just fine without adding it to the path, as long as you always activate it.

>./Anaconda3-5.0* -u

Why not `$ bash Anaconda...` or is that the same :-p ?
