### ISSUE TITLE
Anaconda Navigation app cannot be launched

### ISSUE THREAD

**Issue by AnjuPMS** [ContinuumIO/anaconda-issues#2913] opened 2017-07-06 22:56 UTC
> Main Error

string indices must be integers, not str

Traceback

Traceback (most recent call last):
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Users/amadhusoodhanans/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

>

**Comment by goanpeca** [comment] 2017-07-07 02:55
Closing as duplicate of #1837

Please update to the latest version of Navigator.

Open a terminal and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-07 02:55 UTC
