### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rhlgupta** [ContinuumIO/anaconda-issues#1978] opened 2017-06-05 22:17 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda2
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda2'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda2"

```
## System information
```
platform: win-32
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;8.1;6.3.9600;x86;x86 Family 6 Model 58 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-06-08 21:19
Closing as duplicate of #1845

**Closed by goanpeca** 2017-06-08 21:19 UTC
Labels: pkg:navigator
