### ISSUE TITLE
conda install glib --> CondaError: OSError(36, 'File name too long') 

### ISSUE THREAD

**Issue by scivision** [ContinuumIO/anaconda-issues#7123] opened 2017-11-05 15:19 UTC
When trying to `conda install matplotlib` on a couple different computers, from a fresh install of Miniconda3 I get the "file name too long" error 3 times. 

```
platform: linux-64
conda version: 4.3.30
```

I tracked it down to this prereq

```
conda install glib -y
```
results in
```
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment $HOME/miniconda3:

The following NEW packages will be INSTALLED:

    glib:      2.53.6-h56f7bfe_1



CondaError: OSError(36, 'File name too long')
CondaError: OSError(36, 'File name too long')
CondaError: OSError(36, 'File name too long')
```

Is this related to https://github.com/conda-forge/glib-feedstock/issues/16

**Comment by leobiscassi** [comment] 2017-11-06 01:55
I've got the same issue here.

```
               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : /home/leobiscassi/.miniconda2  (writable)
    default environment : /home/leobiscassi/.miniconda2/envs/stark
       envs directories : /home/leobiscassi/.miniconda2/envs
                          /home/leobiscassi/.conda/envs
          package cache : /home/leobiscassi/.miniconda2/pkgs
                          /home/leobiscassi/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Linux/4.4.0-98-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1001:1001
```

**Comment by msarahan** [comment] 2017-11-06 02:51
I haven't been able to reproduce this in a linux docker container:

```
[root@9b75822ecfed build_scripts]# conda install glib
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    glib: 2.53.6-h56f7bfe_1 defaults
    pcre: 8.41-hc71a17e_0   defaults

Proceed ([y]/n)? y

pcre-8.41-hc71 100% |################################| Time: 0:00:00   1.56 MB/s
glib-2.53.6-h5 100% |################################| Time: 0:00:01   5.37 MB/s
[root@9b75822ecfed build_scripts]# conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.28
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.9.49-moby CentOS/6.9 glibc/2.12
                UID:GID : 0:0
```

I'll keep looking for something wrong there, but if anyone can figure out better reproduction steps, please post!

**Comment by yanirs** [comment] 2017-11-06 04:32
I'm experiencing the same issue when running `conda install glib`. This was working a few days ago. Running `conda install glib==2.50.2` works fine.

The main differences between my `conda info` and @msarahan's is that I don't have `conda-build` installed and that my `user-agent` is `conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-98-generic debian/stretch/sid glibc/2.23` (I'm on Ubuntu 16.04). Maybe the different glibc version is the root cause?

I also tried running `conda install glib` in a Docker container based on `debian:stable`, and it worked fine. The `user-agent` is `conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-98-generic debian/9.2 glibc/2.24`.

**Comment by brandimarte** [comment] 2017-11-06 09:26
I'm facing the same problem. I'm able to update to glib 2.53.6 build hc861d11_1, but beyond that I get 'CondaError: OSError(36, 'File name too long')'.

**Comment by waterswims** [comment] 2017-11-06 10:03
+1

**Comment by matthewfeickert** [comment] 2017-11-06 10:17
Same thing with me on Ubuntu 16.04:

```
$ uname -srvmpio
Linux 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linuxx86_64 x86_64 x86_64 GNU/Linux
$ conda --version
conda 4.3.30
$ python --version
Python 3.5.4 :: Anaconda custom (64-bit)
$ conda update glib
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/mcf/anaconda3:

The following packages will be UPDATED:

    glib: 2.53.6-hc861d11_1 --> 2.53.6-h56f7bfe_1

Proceed ([y]/n)? y


CondaError: OSError(36, 'File name too long')
CondaError: OSError(36, 'File name too long')
CondaError: OSError(36, 'File name too long')



```

**Comment by j9ac9k** [comment] 2017-11-06 18:03
ran into this issue over the weekend

```
$ uname -srvmpio
Linux 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ conda --version
conda 4.3.30
$ python --version
Python 3.6.3 :: Anaconda, Inc.
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/ogi/miniconda3  (writable)
    default environment : /home/ogi/miniconda3/envs/main
       envs directories : /home/ogi/miniconda3/envs
                          /home/ogi/.conda/envs
          package cache : /home/ogi/miniconda3/pkgs
                          /home/ogi/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.13.0-16-generic debian/stretch/sid glibc/2.26    
                UID:GID : 1000:1000

```

in my case, I noticed it failing on matplotlib, can duplicate with glib. 

Let me know what other information I can provide to be of assistance.

**Comment by msarahan** [comment] 2017-11-06 18:51
I believe this is related to our effort to restore debugging content with glib: https://github.com/AnacondaRecipes/glib-feedstock/commit/a4040baa60da1448d7f0b17b76483d654e0ccb11#diff-44a73bcc045c193c3bd45da87994b03bL34

That leads to folders and filenames like:

```./share/gdb/auto-load/tmp/build/80754af9/glib_1509734987129/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/__pycache__/libglib-2.0.so.0.5306.0-gdb.cpython-36.pyc```

which I suspect are the issue here.  I'm not sure why I'm having trouble reproducing the errors, but I don't think that's terribly important to understand.  I'm going to remove the gdb stuff and build new packages.

**Comment by leobiscassi** [comment] 2017-11-06 18:59
@msarahan thanks for the return! Let me know when you release the new package. :smile:

**Comment by msarahan** [comment] 2017-11-06 19:02
If anyone affected by this can please confirm that

``conda install -c c3i_test2 glib``

resolves the issue, I'd be most grateful.  The package is glib-2.53.6-h5d9569c_2.tar.bz2

**Comment by leobiscassi** [comment] 2017-11-06 19:06
successfully installation!

**Comment by msarahan** [comment] 2017-11-06 19:08
thanks.  I'll upload this to defaults now.  Closing this issue.

**Closed by msarahan** 2017-11-06 19:08 UTC

**Comment by scivision** [comment] 2017-11-06 20:33
yes, it works for me now too on multiple PCs.
installing `glib 2.53.6-h5d9569c_2`

**Comment by j9ac9k** [comment] 2017-11-06 20:35
things are fully functional now thanks @msarahan !

**Comment by matthewfeickert** [comment] 2017-11-06 21:50
Yup, this works great now. Thanks! :+1:
