### ISSUE TITLE
Launcher hangs on "Loading apps list..." (OS X El Capitan)

### ISSUE THREAD

**Issue by BKJackson** [ContinuumIO/anaconda-issues#508] opened 2015-11-02 19:36 UTC
I tried uninstalling and reinstalling the launcher; tried installing a dev 2.0 version mentioned in another thread--they all hang after the launcher window opens. 

It was working last time I used it (last Friday), and I'm not sure what might have changed since then.

Is there a log file or some way to see what the installer is trying to do that's causing it to hang? 

I can open iPython notebook (Jupyter) and Spyder from the command line, so the problem seems to be limited to the Anaconda launcher app.

**Comment by srt19170** [comment] 2015-11-05 15:33
I have this same problem on Windows.  I downgraded to 0.1.5 and that still works.

I noticed that 0.1.5 asks me for proxy information when it starts (I'm behind a firewall) and I didn't see that when starting 1.0.0.

**Comment by BKJackson** [comment] 2015-11-06 01:57
Update: 
My Anaconda Launcher version is 1.0.0 (node-webkit 0.10.1)
Conda Version: 3.18.3
Python Version: 3.4.3.final.0
Platform: osx-64

**Comment by g24swint** [comment] 2015-12-11 16:42
I downloaded a fresh installation of Anaconda2-2.4.1, 64-bit for my work laptop running Windows 7 and am seeing this problem. I had previously installed a conda environment and Spyder separately.

**Comment by josefk123** [comment] 2015-12-12 23:36
I have the same problem, on a Python 2.7 environment.  My 3.5 environment is working perfectly...if this points to a solution?

**Comment by pl-ki** [comment] 2016-01-27 15:25
Same problem with Anaconda2-2.4.1 64bit on Python 2.7 in Windows7 environment.

**Comment by jhdedrick** [comment] 2016-04-13 06:38
I had this issue on Windows 64 bit.  Works find if I "run as Administrator" - looks like there are some permissions issues with the environment directories.

**Comment by goanpeca** [comment] 2016-04-13 15:04
@jhdedrick, launcher is now deprecated and was replaced by Anaconda Navigator. For information on how to get it running, please visit the [docs](https://docs.continuum.io/anaconda/navigator)

**Comment by stephenakearns** [comment] 2016-06-06 15:22
closing per comment above.

**Closed by stephenakearns** 2016-06-06 15:22 UTC
Labels: Navigator

**Comment by silvamayflower** [comment] 2017-04-19 12:13
Shame this has closed without a solution.  I'm trying to complete a course that specifies this particular installation (Anaconda3-2.3.0), and I'm completely stuck.

**Comment by mingwandroid** [comment] 2017-04-19 14:17
You can probably use any more recent release of `Anaconda3`.

**Comment by silvamayflower** [comment] 2017-04-19 17:08
The problem is that the course specifies it because it is designed around it.  We are told not to click upgrade.  It is a fairly recent FutureLearn course from the Open University, so I trust it.  Sadly, I am following it a few months after its presentation.  However, if I can't find a solution, I may try that rather than give up.
