### ISSUE TITLE
An unexpected error occurred on Navigator start-up psutil.AccessDenied (pid=607)

### ISSUE THREAD

**Issue by nitingang9981** [ContinuumIO/anaconda-issues#7391] opened 2017-11-19 19:44 UTC
Traceback (most recent call last):
File "/Users/admin/anaconda3/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/admin/anaconda3/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/admin/anaconda3/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/admin/anaconda3/lib/python2.7/site-packages/psutil/__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "/Users/admin/anaconda3/lib/python2.7/site-packages/psutil/_psosx.py", line 295, in wrapper
return fun(self, *args, **kwargs)
File "/Users/admin/anaconda3/lib/python2.7/site-packages/psutil/_psosx.py", line 377, in cmdline
return cext.proc_cmdline(self.pid)
File "/Users/admin/anaconda3/lib/python2.7/contextlib.py", line 35, in __exit__
self.gen.throw(type, value, traceback)
File "/Users/admin/anaconda3/lib/python2.7/site-packages/psutil/_psosx.py", line 326, in catch_zombie
raise AccessDenied(proc.pid, proc._name)
AccessDenied: psutil.AccessDenied (pid=725)

**Comment by goanpeca** [comment] 2017-11-20 20:51
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-20 20:51 UTC
