### ISSUE TITLE
Anaconda Navigator start-up error

### ISSUE THREAD

**Issue by almota** [ContinuumIO/anaconda-issues#6753] opened 2017-10-19 00:05 UTC
# Error

An unexpected error ocurred on Navigator star-up
psutil.AccessDenied (pid=600)

# Traceback
```

Traceback (most recent call last):
File "C:\Users\Muquifo\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 536, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\Muquifo\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 589, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Acceso denegado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Muquifo\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\Muquifo\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\Muquifo\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\Muquifo\Anaconda3\lib\site-packages\psutil\__init__.py", line 622, in cmdline
return self._proc.cmdline()
File "C:\Users\Muquifo\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 539, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=600)

```

# System info

Microsoft Windows 10 Home (x64)
conda version 4.3.30
conda build version 2.0.2
python version 3.5.2.final.0

**Comment by goanpeca** [comment] 2017-10-19 14:05
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-19 14:05 UTC
