### ISSUE TITLE
navigation error

### ISSUE THREAD

**Issue by shuja1497** [ContinuumIO/anaconda-issues#3900] opened 2017-08-04 07:41 UTC
Main Error:
string indices must be integers, not str

**Comment by goanpeca** [comment] 2017-08-04 20:59
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-04 20:59 UTC
