### ISSUE TITLE
anaconda navigator shows error on startup

### ISSUE THREAD

**Issue by jhashailesh3108** [ContinuumIO/anaconda-issues#5555] opened 2017-09-15 17:28 UTC
Traceback (most recent call last):
File "C:\Users\103\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\103\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\103\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\103\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\103\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\103\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "C:\Users\103\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2112)

**Comment by goanpeca** [comment] 2017-09-15 17:33
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-15 17:33 UTC

**Comment by jhashailesh3108** [comment] 2017-09-15 18:03
Didn't work. it's showing same error. and amazed with your super fast reply. :)

**Comment by goanpeca** [comment] 2017-09-15 22:29
@jhashailesh3108 what did not work :-) ?

**Comment by jhashailesh3108** [comment] 2017-09-16 01:10
It shows the same error after updating the anaconda. Only navigator is
showing error otherwise everything is running fine. Should I uninstall and
reinstall that again?


On 16 Sep 2017 3:59 am, "Gonzalo Peña-Castellanos" <notifications@github.com>
wrote:

@jhashailesh3108 <https://github.com/jhashailesh3108> what did not work :-)
?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ContinuumIO/anaconda-issues/issues/5555#issuecomment-329918607>,
or mute the thread

**Comment by goanpeca** [comment] 2017-09-16 03:24
Did you `See issue #1984 for more information on how to fix this.` ?
