### ISSUE TITLE
pytorch doesn't install with defaults on windows + python 3.7

### ISSUE THREAD

**Issue by hmaarrfk** [ContinuumIO/anaconda-issues#10640] opened 2019-02-17 00:05 UTC
### Actual Behavior
I know this isn't a anaconda only issue, but talking to @mingwandroid they mentionned that this might be a good place to put the issue.

### Expected Behavior
Installing pytorch + python 3.7 should work

### Steps to Reproduce
Follow the workaround outline here
https://github.com/conda/conda/issues/8296

then
```
python -c "import torch"
```

```
(test) C:\Users\mark>python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mark\Miniconda3\envs\test\lib\site-packages\torch\__init__.py", line 84, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.

```
##### Anaconda or Miniconda version:

Fresh install from the latest on Feb 16 2019.

##### Operating System:

Windows 64 bit

##### `conda info`

```
(base) C:\Users\mark>conda info

     active environment : base
    active env location : C:\Users\mark\Miniconda3
            shell level : 1
       user config file : C:\Users\mark\.condarc
 populated config files :
          conda version : 4.6.4
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : C:\Users\mark\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\mark\Miniconda3\pkgs
                          C:\Users\mark\.conda\pkgs
                          C:\Users\mark\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\mark\Miniconda3\envs
                          C:\Users\mark\.conda\envs
                          C:\Users\mark\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
(base) C:\Users\mark>conda list --show-channel-urls
# packages in environment at C:\Users\mark\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.4                    py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.5              py37h7a1dbc1_0    defaults
idna                      2.8                      py37_0    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
openssl                   1.1.1a               he774522_0    defaults
pip                       19.0.1                   py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.2                h8c8aaf0_2    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                40.7.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.3                   py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
```

#### Test environment info

```
(test) C:\Users\mark>conda info

     active environment : test
    active env location : C:\Users\mark\Miniconda3\envs\test
            shell level : 2
       user config file : C:\Users\mark\.condarc
 populated config files :
          conda version : 4.6.4
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : C:\Users\mark\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\mark\Miniconda3\pkgs
                          C:\Users\mark\.conda\pkgs
                          C:\Users\mark\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\mark\Miniconda3\envs
                          C:\Users\mark\.conda\envs
                          C:\Users\mark\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

```
(test) C:\Users\mark>conda list --show-channel-urls
# packages in environment at C:\Users\mark\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
freetype                  2.9.1                ha9979f8_1    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
intel-openmp              2019.1                      144    defaults
jpeg                      9b                   hb83a4c4_2    defaults
libpng                    1.6.36               h2a8f88b_0    defaults
libtiff                   4.0.10               hb898794_2    defaults
mkl                       2019.1                      144    defaults
mkl_fft                   1.0.10           py37h14836fe_0    defaults
mkl_random                1.0.2            py37h343c172_0    defaults
ninja                     1.8.2            py37he980bc4_1    defaults
numpy                     1.15.4           py37h19fb1c0_0    defaults
numpy-base                1.15.4           py37hc3f5095_0    defaults
olefile                   0.46                     py37_0    defaults
openssl                   1.1.1a               he774522_0    defaults
pillow                    5.4.1            py37hdc69c19_0    defaults
pip                       19.0.1                   py37_0    defaults
pycparser                 2.19                     py37_0    defaults
python                    3.7.2                h8c8aaf0_2    defaults
pytorch-cpu               1.0.1             py3.7.1_cpu_1    pytorch
setuptools                40.7.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
torchvision-cpu           0.2.1                      py_2    pytorch
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.3                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    defaults
```

## Workaround

Remove anaconda/miniconda from your system. Reinstall it, then:

Something like:
```
conda config --add channels conda-forge
conda create --name test2 --yes
conda activate test2
conda install conda-forge::python=3.7 qt=5 --yes
conda install pytorch-cpu torchvision-cpu -c pytorch
python -c "import torch; print(torch.__version__)"
```

Honestly, I was getting errors like

```
(test2) C:\Users\mark>conda install pytorch-cpu torchvision-cpu -c pytorch
Collecting package metadata: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/r/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))
```
before uninstalling and reinstalling miniconda.

**Comment by hmaarrfk** [comment] 2019-02-17 15:19
@mingwandroid I think with your latest build as of 5 hours ago, torch now segfaults

```
(torch) C:\Users\mark>python -c "import torch; print(torch.__version__)"

(torch) C:\Users\mark>python -c "import torch; print(torch.__version__)"

(torch) C:\Users\mark>python
Python 3.7.2 (default, Feb 17 2019, 03:28:24) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch

(torch) C:\Users\mark>conda list
# packages in environment at C:\Users\mark\Miniconda3_2\envs\torch:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2019.1.23                     0
certifi                   2018.11.29               py37_0
cffi                      1.11.5           py37h74b6da3_1
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.1                      144
jpeg                      9b                   hb83a4c4_2
libpng                    1.6.36               h2a8f88b_0
libtiff                   4.0.10               hb898794_2
mkl                       2019.1                      144
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
ninja                     1.8.2            py37he980bc4_1
numpy                     1.15.4           py37h19fb1c0_0
numpy-base                1.15.4           py37hc3f5095_0
olefile                   0.46                     py37_0
openssl                   1.1.1a               he774522_0
pillow                    5.4.1            py37hdc69c19_0
pip                       19.0.1                   py37_0
pycparser                 2.19                     py37_0
python                    3.7.2                h8c8aaf0_3    rdonnelly
pytorch-cpu               1.0.1             py3.7.1_cpu_1    pytorch
setuptools                40.7.3                   py37_0
six                       1.12.0                   py37_0
sqlite                    3.26.0               he774522_0
tk                        8.6.8                hfa6e2cd_0
torchvision-cpu           0.2.1                      py_2    pytorch
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.32.3                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```

**Comment by FalkTannhaeuser** [comment] 2019-02-18 18:43
The same error (DLL load failure when trying `python -c "import torch"` occurs with Python 2.6.8 and the latest build h9f7ef89_1. As a workaround, I'm able to use PyTorch correctly after downgrading to the previous Python 2.6.8 build by executing `conda install python=2.6.8=h9f7ef89_0` from the Anaconda Prompt. It seems that in the last build something got broken in the management of the DLL load path and hence the PyTorch DLL `%CONDA_PREFIX%\Lib\site-packages\torch\_C.cp36-win_amd64.pyd`, which depends on some other DLLs found under `%CONDA_PREFIX%\Lib\site-packages\torch\lib`, cannot be loaded.

**Comment by mingwandroid** [comment] 2019-02-18 18:55
Can you try the latest builds which are on `c3i_test`? I'm testing now. I'll report back soon.

conda install -c c3i_test::python=3.7.2 (or 3.6.8)

**Comment by FalkTannhaeuser** [comment] 2019-02-18 21:07
Works fine - `python -c "import torch; print(torch.__version__)"` prints `0.4.1` with Python 3.7.2 both with build h8c8aaf0_0 from default channel and with build h8c8aaf0_3 from channel c3i_test. OTOH, with the current build h8c8aaf0_2, I get the DLL load failure too.
As I have only Python 3.7.2 on this machine, I won't be able to do the same tests with Python 3.6.8 before tomorrow morning (CET).

**Comment by fourier79** [comment] 2019-02-21 09:20
@FalkTannhaeuser do you use also gpu from pytorch? 
I followed your suggestion of downgrading conda by executing  `conda install python=3.6.8=h9f7ef89_0`; however, it has the same issue in accessing the gpu as reported in https://github.com/ContinuumIO/anaconda-issues/issues/10651.

**Comment by FalkTannhaeuser** [comment] 2019-02-21 09:56
With Python 3.6.8 build h9f7ef89_2 from channel c3i_test:
```
python -c "import torch; print(f'PyTorch {torch.__version__} with CUDA {torch.version.cuda} (available:{torch.cuda.is_available()}), Debug={torch.version.debug}')"
```
prints `PyTorch 0.4.1 with CUDA 9.2 (available:True), Debug=False`
I have not yet tested PyTorch 1.0.

**Comment by fourier79** [comment] 2019-02-21 15:17
Thank you @FalkTannhaeuser. I am not sure of the reason; but, I couldn't reproduce your result (maybe downgrading didn't remove some files for me). As a result, I uninstalled anaconda (Anaconda3-2018.12) and installed an earlier version from the file Anaconda3-5.2.0-Windows-x86_64.exe (chose this one, maybe 3.5.1 would work too ). This solved the issue. Now, I can access gpu from Pytorch 1.0 and could run a small training sample.

**Comment by mingwandroid** [comment] 2019-02-22 22:32
This should be fixed now, `conda update python`, sorry for the trouble.

**Closed by mingwandroid** 2019-02-22 22:32 UTC
