### ISSUE TITLE
Navigation Error

### ISSUE THREAD

**Issue by mohanmuthukumaran** [ContinuumIO/anaconda-issues#12880] opened 2022-03-30 04:12 UTC
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\mohan\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 224, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 72, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\mohan\.continuum\anaconda-client\config.yaml", position 0

**Comment by mohanmuthukumaran** [comment] 2022-03-30 04:18
- no file exists -looks like C:\Users\a.continuum\anaconda-client\config.yaml has gotten corrupted. If you rename it from config.yaml to config.old 

-deleted .condarc file, no file exist
-updated-
conda update anaconda-navigator
conda update navigator-update
-restarted computer 

-can't fix navigator error 
same error continues

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 09:39
Duplicate of #12762

**Closed by vshevchenko-anaconda** 2023-07-07 09:39 UTC
Labels: pkg-navigator
