### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by arinnem** [ContinuumIO/anaconda-issues#4580] opened 2017-08-24 04:11 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/free/win-32/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

```
## System information
```
platform: win-32
version: 1.6.2
conda: 4.3.24
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;7;6.1.7601;x86;x86 Family 6 Model 94 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-08-24 04:11
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-24 04:11 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by arinnem** [comment] 2017-08-24 05:03
Thank you so much.

**Comment by goanpeca** [comment] 2017-08-24 11:50
>HTTP errors are often intermittent, and a simple retry will get you on your way.

These errors are intermittent the server/or your connection might have been down for a while.

**Comment by arinnem** [comment] 2017-08-25 04:13
It remains the same from yesterday til now. I have to temporarily turn off verifying ssl to make things go through.

If you have solved it, please let me know. Thanks a lot.
