### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by pyparam** [ContinuumIO/anaconda-issues#8429] opened 2018-02-04 12:27 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 17:52:29.932 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 17:52:29.936 NotebookApp] Writing notebook server cookie secret to /run/user/1001/jupyter/notebook_cookie_secret
[I 17:52:30.123 NotebookApp] [nb_anacondacloud] enabled
[I 17:52:30.128 NotebookApp] [nb_conda] enabled
[I 17:52:30.217 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 17:52:30.217 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 17:52:30.230 NotebookApp] Serving notebooks from local directory: /home/paramveer
[I 17:52:30.230 NotebookApp] 0 active kernels 
[I 17:52:30.230 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=f2e6f19df87586a309b2624e5369308b0e25aad41a5ef524
[I 17:52:30.230 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:52:30.232 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f2e6f19df87586a309b2624e5369308b0e25aad41a5ef524
[I 17:52:31.381 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[12386:12424:0204/175231.400370:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
[E 17:52:37.073 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/paramveer/anaconda3/lib/python3.5/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/paramveer/anaconda3/lib/python3.5/site-packages/nb_conda/handlers.py", line 62, in get
        self.finish(json.dumps(self.env_manager.env_packages(env)))
      File "/home/paramveer/anaconda3/lib/python3.5/site-packages/nb_conda/envmanager.py", line 124, in env_packages
        "packages": [pkg_info(package) for package in data]
      File "/home/paramveer/anaconda3/lib/python3.5/site-packages/nb_conda/envmanager.py", line 124, in <listcomp>
        "packages": [pkg_info(package) for package in data]
      File "/home/paramveer/anaconda3/lib/python3.5/site-packages/nb_conda/envmanager.py", line 16, in pkg_info
        name, version, build = s.rsplit('-', 2)
    AttributeError: 'dict' object has no attribute 'rsplit'
[E 17:52:37.243 NotebookApp] {
      "Referer": "http://localhost:8888/tree",
      "X-Requested-With": "XMLHttpRequest",
      "Host": "localhost:8888",
      "Accept-Language": "en-US,en;q=0.9",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36",
      "Cookie": "_xsrf=2|0b2e3323|bfdc29e8f8168fae405d843108fc33fe|1517746951; username-localhost-8888=\"2|1:0|10:1517746951|23:username-localhost-8888|44:Y2ExNmIzNGRjYTE2NDc0Nzg2ZDYyZjA2Mjg1ZGY2ZGE=|c4f483833e7e7493b785bcdbe683557d6016d6b8a93e44507d783adf3151bb6e\"",
      "Connection": "keep-alive",
      "Accept-Encoding": "gzip, deflate, br"
    }
[E 17:52:37.243 NotebookApp] 500 GET /conda/environments/root?_=1517746951697 (127.0.0.1) 538.19ms referer=http://localhost:8888/tree

```
## System information
```
version: 1.6.2
qt: 5.6.2
platform: linux-64
language: en_IN
pyqt: 5.6.0
python: 3.5.3
os: Linux;3.19.0-80-generic;#88~14.04.1-Ubuntu SMP Fri Jan 13 14:54:07 UTC 2017;x86_64;x86_64
conda: 4.3.30
```

**Comment by goanpeca** [comment] 2018-02-05 03:44
Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #2098 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-02-05 03:44 UTC
Labels: pkg:navigator, reso:duplicate
