### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by andreas-h** [ContinuumIO/anaconda-issues#707] opened 2016-03-16 13:29 UTC
Each invokation of the `conda` command leads to an SSL error on my Debian/Stretch system:

    $ conda search numpy
    Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
    SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
    .SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
    SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
    .....
    numpy                        1.5.1                 py27_pro0  defaults        [mkl]

**Comment by msarahan** [comment] 2016-03-16 13:40
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/670.  Closing this issue, but reopening that issue.  We're not sure exactly how to fix or work around this, but it appears to be upstream in origin.

**Closed by msarahan** 2016-03-16 13:40 UTC
