### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by garry5563** [ContinuumIO/anaconda-issues#2693] opened 2017-06-28 20:35 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/garry/anaconda2/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/garry/anaconda2/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/garry/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/garry/anaconda2/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Linux;4.11.7-1-MANJARO;#1 SMP PREEMPT Sat Jun 24 07:27:27 UTC 2017;x86_64;
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-06-28 20:45
@ccordoba12

**Comment by goanpeca** [comment] 2017-11-14 20:46
## See issue #3374 for more information on how to fix this issue.**

---

Closing as duplicate of #3374

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-14 20:46 UTC
Labels: pkg:navigator, pkg:spyder
