### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by saiabhishekgv** [ContinuumIO/anaconda-issues#4765] opened 2017-08-30 00:50 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 20:49:56.243 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 20:49:58.169 NotebookApp] Serving notebooks from local directory: /home/ihp
[I 20:49:58.169 NotebookApp] 0 active kernels 
[I 20:49:58.169 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=41fbdedffff5c5934070a227e931b76c7b09136b9344e28c
[I 20:49:58.169 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:49:58.172 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=41fbdedffff5c5934070a227e931b76c7b09136b9344e28c
[I 20:50:02.177 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[30509:30548:0829/205002.327586:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

```
## System information
```
platform: linux-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Linux;4.4.0-92-generic;#115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017;x86_64;x86_64
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-08-30 13:48
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-30 13:48 UTC
Labels: pkg:navigator, reso:duplicate
