### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by emilyS2015** [ContinuumIO/anaconda-issues#2523] opened 2017-06-23 04:00 UTC
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

byte indices must be integers or slices, not str
Traceback

Traceback (most recent call last):
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Applications/anaconda/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-06-23 04:05
Closing as duplicate of #1837

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-23 04:05 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by emilyS2015** [comment] 2017-06-23 04:08
I tried that though and it still gives me the same error message.

**Comment by emilyS2015** [comment] 2017-06-23 04:11
Thanks that works! But I got this from the terminal:

 /Users/wsswemily/anaconda/bin/jupyter_mac.command ; exit;
[W 21:09:55.552 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[W 21:09:56.624 NotebookApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "/Users/wsswemily/anaconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/wsswemily/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'ipyparallel'
[I 21:09:56.640 NotebookApp] Serving notebooks from local directory: /Users/wsswemily
[I 21:09:56.640 NotebookApp] 0 active kernels 
[I 21:09:56.640 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=1aa1cb9499f47bd9b9f35cacbacaa6dd2f10ac3cdd54e7b3
[I 21:09:56.640 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:09:56.642 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=1aa1cb9499f47bd9b9f35cacbacaa6dd2f10ac3cdd54e7b3
0:97: execution error: "http://localhost:8888/tree?token=2e86ed379590b05ea1da02c8d05cb99d8b9c19ff4efda614" doesn’t understand the “open location” message. (-1708)
