### ISSUE TITLE
CondaHTTPError when trying to install packages

### ISSUE THREAD

**Issue by jlw4192** [ContinuumIO/anaconda-issues#3180] opened 2017-07-14 15:22 UTC
On both the anaconda terminal and navigator, I can't install any packages. Here is the error I get when I try to install plotly:
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')",),),)

I believe this may be some kind network firewall issue and, after searching various github issues, I set ssl_verify: false in my .condarc file. But this did not work. Any help would be greatly appreciated.

**Comment by goanpeca** [comment] 2017-07-14 15:22
Closing as duplicate of #1932

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-14 15:22 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by jlw4192** [comment] 2017-07-14 15:30
@goanpeca I still get a similar error when I try to do this on the anaconda prompt in windows

>conda update anaconda-navigator
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-
64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

SSLError(SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')"
,),),)

**Comment by noahwalugembe** [comment] 2019-03-31 09:53
> Closing as duplicate of #1932
> 
> Please update to the latest version of Navigator.
> 
> Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
> and type
> 
> ```
> $ conda update anaconda-navigator
> ```

I am getting the same problem
