### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by baeyeba** [ContinuumIO/anaconda-issues#5048] opened 2017-09-05 08:33 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

```
## System information
```
python: 3.6.1
language: nl_BE
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.25
```

**Comment by goanpeca** [comment] 2017-09-05 08:35
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-05 08:35 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by baeyeba** [comment] 2017-09-05 08:55
The conda update commands give the same error! 
Also, I think i have the latest version of navigator (1.6.2)

**Comment by goanpeca** [comment] 2017-09-05 16:09
>Also, I think i have the latest version of navigator (1.6.2)

No you do not. The latest is 1.6.5
