### ISSUE TITLE
Conda  cannot be updated through command line

### ISSUE THREAD

**Issue by kevin-coder** [ContinuumIO/anaconda-issues#8774] opened 2018-03-05 19:18 UTC
### Actual Behavior

Conda should be updated successfully through the command line.

### Expected Behavior

Actually, the updating procedure will be rolled back. Details show following.
Preparing transaction: done                                                     
Verifying transaction: done                                                     
Executing transaction: failed                                                   
ERROR conda.core.link:_execute(481): An error occurred while installing package 
'defaults::ipykernel-4.8.2-py36_0'.                                             
LinkError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0 
running your command again with `-v` will provide additional information        
location of failed script: C:\Software\SoftwareDev\Python36\Scripts\.ipykernel-p
ost-link.bat                                                                    
==> script messages <==                                                         
<None>                                                                          
                                                                                
Attempting to roll back.                                                        
                                                                                
Rolling back transaction: done                                                  
                                                                                
LinkError: post-link script failed for package defaults::ipykernel-4.8.2-py36_0 
running your command again with `-v` will provide additional information        
location of failed script: C:\Software\SoftwareDev\Python36\Scripts\.ipykernel-p
ost-link.bat                                                                    
==> script messages <==                                                         
<None>                                                                          

### Steps to Reproduce

1. Open the command prompt on Windows 10.
2. Type: conda update conda
3. Type: conda update --all

##### Anaconda or Miniconda version:
4.4.11

##### Operating System:
Windows 10
##### `conda info`

    active environment : None                                                 
      user config file : C:\Users\huzq8\.condarc                              
populated config files : C:\Users\huzq8\.condarc                              
         conda version : 4.4.11                                               
   conda-build version : not installed                                        
        python version : 3.6.4.final.0                                        
      base environment : C:\Software\SoftwareDev\Python36  (writable)         
          channel URLs : https://repo.continuum.io/pkgs/main/win-64           
                         https://repo.continuum.io/pkgs/main/noarch           
                         https://repo.continuum.io/pkgs/free/win-64           
                         https://repo.continuum.io/pkgs/free/noarch           
                         https://repo.continuum.io/pkgs/r/win-64              
                         https://repo.continuum.io/pkgs/r/noarch              
                         https://repo.continuum.io/pkgs/pro/win-64            
                         https://repo.continuum.io/pkgs/pro/noarch            
                         https://repo.continuum.io/pkgs/msys2/win-64          
                         https://repo.continuum.io/pkgs/msys2/noarch          
         package cache : C:\Software\SoftwareDev\Python36\pkgs                
                         C:\Users\huzq8\AppData\Local\conda\conda\pkgs        
      envs directories : C:\Software\SoftwareDev\Python36\envs                
                         C:\Users\huzq8\AppData\Local\conda\conda\envs        
                         C:\Users\huzq8\.conda\envs                           
              platform : win-64                                               
            user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Windows/10
indows/10.0.17604                                                             
         administrator : False                                                
            netrc file : None                                                 
          offline mode : False                                                

##### `conda list --show-channel-urls`
                                                                      
Name                    Version                   Build  Channel       
alabaster                 0.7.10           py36hcd07829_0    defaults    
anaconda-client           1.6.5                     <pip>                
anaconda-client           1.6.11                   py36_0    defaults    
anaconda-navigator        1.6.8                     <pip>                
anaconda-navigator        1.7.0                    py36_0    defaults    
anaconda-project          0.8.0                     <pip>                
anaconda-project          0.8.2            py36hfad2e28_0    defaults    
anyqt                     0.0.8                    py36_0    defaults    
appdirs                   1.4.3                    py36_0    defaults    
asn1crypto                0.24.0                   py36_0    defaults    
astroid                   1.5.3                     <pip>                
astroid                   1.6.1                    py36_0    defaults    
astropy                   2.0.2                     <pip>                
attrs                     17.4.0                   py36_0    defaults    
automat                   0.6.0            py36hc6d8c19_0    defaults    
Babel                     2.5.0                     <pip>                
babel                     2.5.3                    py36_0    defaults    
backports.shutil-get-terminal-size 1.0.0                     <pip>       
beautifulsoup4            4.6.0            py36hd4cc5e8_1    defaults    
bitarray                  0.8.1                     <pip>                
bkcharts                  0.2                       <pip>                
blaze                     0.11.3                    <pip>                
bleach                    2.1.2                    py36_0    defaults    
bleach                    2.0.0                     <pip>                
bokeh                     0.12.7                    <pip>                
boto                      2.48.0                    <pip>                
bottleneck                1.2.1            py36hd119dfa_0    defaults    
ca-certificates           2017.08.26           h94faf87_0    defaults    
certifi                   2018.1.18                py36_0    defaults    
cffi                      1.11.4           py36hfa6e2cd_0    defaults    
chardet                   3.0.4            py36h420ce6e_1    defaults    
click                     6.7                       <pip>                
cloudpickle               0.4.0                     <pip>                
cloudpickle               0.5.2                    py36_1    defaults    
clyent                    1.2.2            py36hb10d595_1    defaults    
colorama                  0.3.9            py36h029ae33_0    defaults    
comtypes                  1.1.2                     <pip>                
conda                     4.4.11                   py36_0    defaults    
conda-env                 2.6.0                h36134e3_1    defaults    
constantly                15.1.0                   py36_0    defaults    
contextlib2               0.5.5                     <pip>                
coverage                  4.4.2            py36hd32d05b_0    defaults    
cryptography              2.1.4            py36he1d7878_0    defaults    
cssselect                 1.0.3                    py36_0    defaults    
cycler                    0.10.0           py36h009560c_0    defaults    
Cython                    0.26.1                    <pip>                
cytoolz                   0.8.2                     <pip>                
dask                      0.15.2                    <pip>                
datashape                 0.5.4                     <pip>                
decorator                 4.2.1                    py36_0    defaults    
dill                      0.2.7.1          py36hf552773_0    defaults    
distributed               1.18.3                    <pip>                
docutils                  0.14             py36h6012d8f_0    defaults    
entrypoints               0.2.3            py36hfd66bb0_2    defaults    
et-xmlfile                1.0.1                     <pip>                
fastcache                 1.0.2                     <pip>                
filelock                  2.0.12                    <pip>                
Flask                     0.12.2                    <pip>                
Flask-Cors                3.0.3                     <pip>                
freetype                  2.8                  h51f8f2c_1    defaults    
gevent                    1.2.2                     <pip>                
glob2                     0.5                       <pip>                
greenlet                  0.4.12                    <pip>                
h5py                      2.7.0                     <pip>                
heapdict                  1.0.0                     <pip>                
html5lib                  1.0.1            py36h047fa9f_0    defaults    
hyperlink                 17.1.1                   py36_0    defaults    
hypothesis                3.38.5           py36h987501d_0    defaults    
icc_rt                    2017.0.4             h97af966_0    defaults    
icu                       58.2                 ha66f8fd_1    defaults    
idna                      2.6              py36h148d497_1    defaults    
imageio                   2.2.0                     <pip>                
imagesize                 0.7.1            py36he29f638_0    defaults    
incremental               17.5.0           py36he5b1da3_0    defaults    
intel-openmp              2018.0.0             hd92c6cd_8    defaults    
ipykernel                 4.6.1                     <pip>                
ipykernel                 4.8.0                    py36_0    defaults    
ipython                   6.1.0                     <pip>                
ipython                   6.2.1            py36h9cf0123_1    defaults    
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults    
ipywidgets                7.0.0                     <pip>                
isort                     4.2.15           py36h6198cc5_0    defaults    
itsdangerous              0.24                      <pip>                
jdcal                     1.3                       <pip>                
jedi                      0.11.1                   py36_0    defaults    
jedi                      0.10.2                    <pip>                
jinja2                    2.10             py36h292fed1_0    defaults    
Jinja2                    2.9.6                     <pip>                
joblib                    0.11                     py36_0    defaults    
jpeg                      9b                   hb83a4c4_2    defaults    
jsonschema                2.6.0            py36h7636477_0    defaults    
jupyter-client            5.1.0                     <pip>                
jupyter-console           5.2.0                     <pip>                
jupyter-core              4.3.0                     <pip>                
jupyter_client            5.2.2                    py36_0    defaults    
jupyter_core              4.4.0            py36h56e9d50_0    defaults    
jupyterlab                0.27.0                    <pip>                
jupyterlab-launcher       0.4.0                     <pip>                
keyring                   10.5.0           py36h410770b_0    defaults    
lazy-object-proxy         1.3.1            py36hd1c21d2_0    defaults    
libiconv                  1.15                 h1df5818_7    defaults    
libpng                    1.6.34               h79bbb47_0    defaults    
libtiff                   4.0.9                h0f13578_0    defaults    
libxml2                   2.9.7                h79bbb47_0    defaults    
libxslt                   1.1.32               hf6f1972_0    defaults    
llvmlite                  0.20.0                    <pip>                
locket                    0.2.0                     <pip>                
lxml                      3.8.0                     <pip>                
lxml                      4.1.1            py36hef2cd61_1    defaults    
markupsafe                1.0              py36h0e26971_1    defaults    
matplotlib                2.1.2            py36h016c42a_0    defaults    
matplotlib                2.0.2                     <pip>                
mccabe                    0.6.1            py36hb41005a_1    defaults    
menuinst                  1.4.11           py36hfa6e2cd_0    defaults    
mistune                   0.8.3                    py36_0    defaults    
mistune                   0.7.4                     <pip>                
mkl                       2018.0.1             h2108138_4    defaults    
mpmath                    0.19                      <pip>                
multipledispatch          0.4.9                     <pip>                
navigator-updater         0.1.0                     <pip>                
nbconvert                 5.3.1            py36h8dc0fde_0    defaults    
nbformat                  4.4.0            py36h3a5bc1b_0    defaults    
networkx                  1.11                      <pip>                
nltk                      3.2.4                     <pip>                
nose                      1.3.7                     <pip>                
notebook                  5.0.0                     <pip>                
notebook                  5.4.0                    py36_0    defaults    
numba                     0.35.0+10.g143f70e           <pip>             
numexpr                   2.6.2                     <pip>                
numpy                     1.13.1                    <pip>                
numpy                     1.14.0           py36h4a99626_1    defaults    
numpydoc                  0.7.0            py36ha25429e_0    defaults    
odo                       0.5.1                     <pip>                
olefile                   0.45.1                   py36_0    defaults    
opencv                    3.3.1            py36h20b85fd_1    defaults    
openpyxl                  2.4.8                     <pip>                
openssl                   1.0.2n               h74b6da3_0    defaults    
orange3                   3.4.1                    py36_0    defaults    
pandas                    0.20.3                    <pip>                
pandoc                    1.19.2.1             hb2460c7_1    defaults    
pandocfilters             1.4.2            py36h3ef6317_1    defaults    
parsel                    1.2.0                    py36_0    defaults    
parso                     0.1.1            py36hae3edee_0    defaults    
partd                     0.3.8                     <pip>                
path.py                   10.3.1                    <pip>                
pathlib2                  2.3.0                     <pip>                
patsy                     0.4.1                     <pip>                
pep8                      1.7.0                     <pip>                
pickleshare               0.7.4            py36h9de030f_0    defaults    
pillow                    5.0.0            py36h0738816_0    defaults    
Pillow                    4.2.1                     <pip>                
pip                       9.0.1            py36h226ae91_4    defaults    
pkginfo                   1.4.1                     <pip>                
ply                       3.10                      <pip>                
prompt_toolkit            1.0.15           py36h60b8f86_0    defaults    
psutil                    5.4.3            py36hfa6e2cd_0    defaults    
psutil                    5.2.2                     <pip>                
py                        1.4.34                    <pip>                
pyasn1                    0.4.2            py36h22e697c_0    defaults    
pyasn1-modules            0.2.1            py36hd1453cb_0    defaults    
pycodestyle               2.3.1            py36h7cc55cd_0    defaults    
pycosat                   0.6.3            py36h413d8a4_0    defaults    
pycparser                 2.18             py36hd053e01_1    defaults    
pycrypto                  2.6.1                     <pip>                
pycurl                    7.43.0                    <pip>                
pydispatcher              2.0.5                    py36_0    defaults    
pyflakes                  1.6.0            py36h0b975d6_0    defaults    
pyflakes                  1.5.0                     <pip>                
pygments                  2.2.0            py36hb010967_0    defaults    
pylint                    1.8.2                    py36_0    defaults    
pylint                    1.7.2                     <pip>                
pympler                   0.5              py36h863af32_0    defaults    
pyodbc                    4.0.17                    <pip>                
pyopenssl                 17.5.0           py36h5b7d817_0    defaults    
pyparsing                 2.2.0            py36h785a196_1    defaults    
pyqt                      5.6.0            py36hb5ed885_5    defaults    
pyqtgraph                 0.10.0                   py36_0    defaults    
pyreadline                2.1              py36h094d952_1    defaults    
pysocks                   1.6.7            py36h698d350_1    defaults    
pytest                    3.2.1                     <pip>                
python                    3.6.4                h6538335_1    defaults    
python-dateutil           2.6.1            py36h509ddcb_1    defaults    
pytz                      2017.2                    <pip>                
pytz                      2018.3                   py36_0    defaults    
PyWavelets                0.5.2                     <pip>                
pywin32                   222              py36hfa6e2cd_0    defaults    
pywinpty                  0.5              py36h6538335_1    defaults    
pyyaml                    3.12             py36h1d1928f_1    defaults    
pyzmq                     16.0.3           py36he714bf5_0    defaults    
pyzmq                     16.0.2                    <pip>                
qt                        5.6.2           vc14h6f8c307_12    defaults    
qtawesome                 0.4.4            py36h5aa48f6_0    defaults    
qtconsole                 4.3.1            py36h99a29a9_0    defaults    
qtpy                      1.3.1            py36hb8717c5_0    defaults    
queuelib                  1.4.2                    py36_0    defaults    
requests                  2.18.4           py36h4371aae_1    defaults    
rope                      0.10.5                    <pip>                
rope                      0.10.7           py36had63a69_0    defaults    
ruamel_yaml               0.15.35          py36hfa6e2cd_1    defaults    
scikit-image              0.13.0                    <pip>                
scikit-learn              0.20.dev0                 <pip>                
scikit-learn              0.19.0                    <pip>                
scikit-learn              0.19.1           py36h53aea1b_0    defaults    
scipy                     1.0.0            py36h1260518_0    defaults    
scipy                     0.19.1                    <pip>                
scrapy                    1.4.0            py36h764da0a_1    defaults    
seaborn                   0.8                       <pip>                
send2trash                1.4.2                    py36_0    defaults    
service_identity          17.0.0                   py36_0    defaults    
setuptools                38.4.0                   py36_0    defaults    
simplegeneric             0.8.1                    py36_2    defaults    
singledispatch            3.4.0.3                   <pip>                
sip                       4.18.1           py36h9c25514_2    defaults    
six                       1.11.0           py36h4db2310_1    defaults    
snowballstemmer           1.2.1            py36h763602f_0    defaults    
sortedcollections         0.5.3                     <pip>                
sortedcontainers          1.5.7                     <pip>                
sphinx                    1.6.6                    py36_0    defaults    
Sphinx                    1.6.3                     <pip>                
sphinxcontrib             1.0              py36hbbac3d2_1    defaults    
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1    defaults    
spyder                    3.2.6                    py36_0    defaults    
spyder                    3.2.3                     <pip>                
SQLAlchemy                1.1.13                    <pip>                
sqlite                    3.22.0               h9d3ae62_0    defaults    
statsmodels               0.8.0                     <pip>                
sympy                     1.1.1                     <pip>                
tables                    3.4.2                     <pip>                
tblib                     1.3.2                     <pip>                
terminado                 0.8.1                    py36_1    defaults    
testpath                  0.3.1            py36h2698cfe_0    defaults    
threadpool                1.3.2                     <pip>                
tk                        8.6.7                hcb92d03_3    defaults    
toolz                     0.8.2                     <pip>                
tornado                   4.5.2                     <pip>                
tornado                   4.5.3                    py36_0    defaults    
traitlets                 4.3.2            py36h096827d_0    defaults    
twisted                   17.9.0           py36hfad864c_0    defaults    
typing                    3.6.2            py36hb035bda_0    defaults    
unicodecsv                0.14.1                    <pip>                
urllib3                   1.22             py36h276f60a_0    defaults    
vc                        14                   h0510ff6_3    defaults    
vs2015_runtime            14.0.25420                    0    defaults    
w3lib                     1.18.0           py36h47df3ce_0    defaults    
wcwidth                   0.1.7            py36h3d5aa90_0    defaults    
webencodings              0.5.1            py36h67c50ae_1    defaults    
Werkzeug                  0.12.2                    <pip>                
wheel                     0.30.0           py36h6c3ec14_1    defaults    
widgetsnbextension        3.0.2                     <pip>                
win-unicode-console       0.5                       <pip>                
win_inet_pton             1.0.1            py36he67d7fd_1    defaults    
wincertstore              0.2              py36h7fe50ca_0    defaults    
winpty                    0.4.3                         4    defaults    
wrapt                     1.10.11          py36he5f5981_0    defaults    
xlrd                      1.1.0            py36h1cb58dc_1    defaults    
XlsxWriter                0.9.8                     <pip>                
xlwings                   0.11.4                    <pip>                
xlwt                      1.3.0                     <pip>                
yaml                      0.1.7                hc54c509_2    defaults    
zict                      0.1.2                     <pip>                
zlib                      1.2.11               h8395fce_2    defaults    
zope                      1.0                      py36_0    defaults    
zope.interface            4.4.3            py36h56cab3c_0    defaults

**Comment by sanketpatel91** [comment] 2018-03-19 15:28
I have also observed the same : 

ERROR conda.core.link:_execute(481): An error occurred while installing package
'defaults::ipykernel-4.8.0-py36_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: C:\Anaconda\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

**Comment by kalefranz** [comment] 2018-03-19 17:14
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/8087

**Closed by kalefranz** 2018-03-19 17:14 UTC
