### ISSUE TITLE
"Make starting directory for Jupyter Notebook configurable from Navigator"

### ISSUE THREAD

**Issue by PrinterMark** [ContinuumIO/anaconda-issues#7812] opened 2017-12-17 05:14 UTC
Need to have a way to set the directory that Jupyter  starts from at Launch in Windows 10.

**Comment by goanpeca** [comment] 2017-12-18 14:31
@PrinterMark thanks for the request. We are working on this feature and should be available in a newer release

**Comment by goanpeca** [comment] 2018-05-30 20:56
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/983

**Closed by goanpeca** 2018-05-30 20:56 UTC
Labels: pkg:navigator
