### ISSUE TITLE
Proxy authentication no prompt for a username and password.

### ISSUE THREAD

**Issue by nthomas92** [ContinuumIO/anaconda-issues#4054] opened 2017-08-09 14:13 UTC
## Main error
I found following in the docu: If you do not include the username and password, of if authentication fails, conda will prompt for a username and password.

This is not true. No promp occurs. It works only if i insert my username and Password in plaintext. Of course this is not what iIwant.

The following errors occurred:

## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 authenticationrequired',)))",),)

```
## System information
```
python: 3.6.1
language: de_DE
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-08-09 14:13
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-09 14:13 UTC
Labels: pkg:navigator, reso:duplicate
