### ISSUE TITLE
Still getting an error when starting anaconda-navigator after update

### ISSUE THREAD

**Issue by mbunse** [ContinuumIO/anaconda-issues#3504] opened 2017-07-24 11:14 UTC
Unfortunately, the update of anaconda-navigator did not resolve my [issue](https://github.com/ContinuumIO/anaconda-issues/issues/3500):
```
(my_root) C:\Users\301512>conda update anaconda-navigator
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\301512\AppData\Local\conda
\conda\envs\my_root:

The following packages will be UPDATED:

    anaconda-navigator: 1.6.2-py36_0 --> 1.6.3-py36_0

Proceed ([y]/n)?

anaconda-navig 100% |###############################| Time: 0:00:00  54.58 MB/s
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\Users\301512\AppData\Local\conda\conda\envs\my_root', env_name: 'my_
root', mode: 'user', used_mode: 'user'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\Users\301512\AppData\Local\conda\conda\envs\my_root', env_name: 'my_
root', mode: 'user', used_mode: 'user'

(my_root) C:\Users\301512>anaconda-navigator
An unexpected error occurred on Navigator start-up<br>byte indices must be integ
ers or slices, not str
Traceback (most recent call last):
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\301512\AppData\Local\conda\conda\envs\my_root\lib\site-packages
\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```

**Comment by goanpeca** [comment] 2017-07-24 11:15
Closing as duplicate of #1837

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-24 11:15 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by mbunse** [comment] 2017-07-24 11:19
That did not help as I wrote in the subject line of this issue.

**Comment by goanpeca** [comment] 2017-07-24 16:16
Updating is a suggestion. To solve the issue see the duplicate #1837

**Comment by mbunse** [comment] 2017-07-25 07:54
I reinstalled Anaconda without admin privileges and "jus for me" and now it works.
