### ISSUE TITLE
_imagingtk module missing in pillow 2.5.1 build(py27_1)

### ISSUE THREAD

**Issue by asmeurer** [ContinuumIO/anaconda-issues#150] opened 2014-08-01 15:17 UTC
_Issue by **[yasar11732](https://github.com/yasar11732)** from Sunday Jul 20, 2014 at 16:15 GMT_
_Originally opened as https://github.com/conda/conda/issues/818_

---

Here is the error I get (tail of it);

```
self.photo_image = ImageTk.PhotoImage(self.pil_image)
File "C:\Users\gorki\Miniconda3\envs\py27pillow\lib\site-packages\PIL\ImageTk.py", line 116, in `__init__`
self.paste(image)
File "C:\Users\gorki\Miniconda3\envs\py27pillow\lib\site-packages\PIL\ImageTk.py", line 181, in paste
import _imagingtk
ImportError: No module named _imagingtk
```

Here is my environment;

```
# packages in environment at C:\Users\gorki\Miniconda3\envs\py27pillow:
#
imaging                   1.1.7                    py27_2
pillow                    2.5.1                    py27_1
python                    2.7.8                         0
```

**Comment by sonofeft** [comment] 2016-02-18 00:06
Can you tell my why this issue was closed?

Is there a solution?

**Comment by sereneg** [comment] 2016-04-05 06:52
do:
1 conda remove pillow
2 pip install image
got this problem fixed by these 2 steps

**Comment by nehaljwani** [comment] 2017-05-20 19:44
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/6

**Closed by nehaljwani** 2017-05-20 19:44 UTC

**Comment by buzz2vatsal** [comment] 2018-04-18 17:13
Just install image in your anaconda env by typing "pip install image"

**Comment by gameon67** [comment] 2019-02-25 07:09
> do:
> 1 conda remove pillow
> 2 pip install image
> got this problem fixed by these 2 steps

Thanks, it works
