### ISSUE TITLE
Anaconda startup Error

### ISSUE THREAD

**Issue by dumonde84** [ContinuumIO/anaconda-issues#12753] opened 2021-12-08 21:37 UTC
Thanks for opening an issue! Please fill out the following template in full.

A few things to keep in mind:

- This issue tracker is for issues with installing Anaconda or Miniconda or with packages built by Anaconda, Inc. like Anaconda Navigator. It is also a place to request packages or other enhancements of the Anaconda Distribution.

- Anaconda Community Code of Conduct: https://www.anaconda.com/community-code-of-conduct/

- For conda issues, you should open an issue at https://github.com/conda/conda/issues

- For conda-build issues, you should open an issue at https://github.com/conda/conda-build

- For an issue with a particular conda-forge package, you should open an issue on the corresponding feedstock: https://github.com/conda-forge

### Actual Behavior

Starting Anaconda fails

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

'NoneType' object has no attribute 'split'

Traceback

Traceback (most recent call last):
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 79, in __init__
    self._conda_api = CondaAPI()
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1813, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\OpenSource\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 662, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'

### Steps to Reproduce

Starting Anaconda

##### Anaconda or Miniconda version:

2021.11

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 10:13
Duplicate of #11780

**Closed by vshevchenko-anaconda** 2023-07-07 10:13 UTC
