### ISSUE TITLE
Error Launching Navigator

### ISSUE THREAD

**Issue by mjmarz** [ContinuumIO/anaconda-issues#7100] opened 2017-11-03 19:52 UTC
I'm getting the following trying to launch Navigator:

Traceback (most recent call last):

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler return_value = func(*args, **kwargs)

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app window = run_app(splash)

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app window = MainWindow(splash=splash)

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 161, in init self.api = AnacondaAPI()

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1258, in AnacondaAPI ANACONDA_API = _AnacondaAPI()

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 70, in init self._conda_api = CondaAPI()

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI CONDA_API = _CondaAPI()

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in init self.set_conda_prefix()

File "C:\Users\Matthew\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix self.ROOT_PREFIX = info['root_prefix'] TypeError: byte indices must be integers or slices, not str

Just installed 5.0.1 for Windows 64bit.
Prompt and Spyder appear to be working fine.

**Comment by goanpeca** [comment] 2017-11-03 21:15
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-03 21:15 UTC

**Comment by mjmarz** [comment] 2017-11-04 04:01
@goanpeca I have been trying some of the fixes mentioned in the thread including the updates, but to no avail. I get the following additional message when trying to launch from command prompt:

![capture](https://user-images.githubusercontent.com/33358945/32402109-2b398fe6-c0f3-11e7-8093-a15abb9ba504.PNG)

**Comment by mjmarz** [comment] 2017-11-04 04:14
If this is a path issue I am not sure how to properly set the path

**Comment by goanpeca** [comment] 2017-11-04 15:46
@mjmarz not sure what is going on, 

What happens when you type

```
$ conda info --json
```
?

**Comment by mjmarz** [comment] 2017-11-04 17:23
@goanpeca Thank you for the response. This is what I get:

(C:\Users\Matthew\Anaconda3) C:\Users\Matthew>conda info --json
{
  "channels": [
    "https://repo.continuum.io/pkgs/main/win-64",
    "https://repo.continuum.io/pkgs/main/noarch",
    "https://repo.continuum.io/pkgs/free/win-64",
    "https://repo.continuum.io/pkgs/free/noarch",
    "https://repo.continuum.io/pkgs/r/win-64",
    "https://repo.continuum.io/pkgs/r/noarch",
    "https://repo.continuum.io/pkgs/pro/win-64",
    "https://repo.continuum.io/pkgs/pro/noarch",
    "https://repo.continuum.io/pkgs/msys2/win-64",
    "https://repo.continuum.io/pkgs/msys2/noarch"
  ],
  "conda_build_version": "3.0.28",
  "conda_env_version": "4.3.30",
  "conda_location": "C:\\Users\\Matthew\\Anaconda3\\lib\\site-packages\\conda",
  "conda_prefix": "C:\\Users\\Matthew\\Anaconda3",
  "conda_private": false,
  "conda_version": "4.3.30",
  "default_prefix": "C:\\Users\\Matthew\\Anaconda3",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "C:\\Users\\Matthew\\Anaconda3",
    "CONDA_ENVS_PATH": "<not set>",
    "CONDA_PREFIX": "C:\\Users\\Matthew\\Anaconda3",
    "CONDA_PS1_BACKUP": "$P$G",
    "CONDA_ROOT": "C:\\Users\\Matthew\\Anaconda3",
    "DYLD_LIBRARY_PATH": "<not set>",
    "FTP_PROXY": "<not set>",
    "HTTPS_PROXY": "<not set>",
    "HTTP_PROXY": "<not set>",
    "LD_LIBRARY_PATH": "<not set>",
    "PATH": "C:\\Users\\Matthew\\Anaconda3;C:\\Users\\Matthew\\Anaconda3\\Librar
y\\mingw-w64\\bin;C:\\Users\\Matthew\\Anaconda3\\Library\\usr\\bin;C:\\Users\\Ma
tthew\\Anaconda3\\Library\\bin;C:\\Users\\Matthew\\Anaconda3\\Scripts;C:\\Progra
m Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\
windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\
\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine
Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\
\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;
C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\P
rogram Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x86;C:\\Program Files (x86)\\In
tel\\OpenCL SDK\\2.0\\bin\\x64;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\Sy
stem32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files
(x86)\\MiKTeX 2.9\\miktex\\bin\\;C:\\Users\\Matthew\\Anaconda3;C:\\Users\\Matthe
w\\Anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\Matthew\\Anaconda3\\Library\\us
r\\bin;C:\\Users\\Matthew\\Anaconda3\\Library\\bin;C:\\Users\\Matthew\\Anaconda3
\\Scripts;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel
\\iCLS Client\\;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:
\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R
) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Managemen
t Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Eng
ine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine C
omponents\\IPT;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x86;C:\\Pro
gram Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x64;C:\\WINDOWS\\system32;C:\\WIN
DOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\
\;C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\;C:\\Users\\Matthew\\AppData
\\Roaming\\MiKTeX\\2.9\\miktex\\bin\\;C:\\Users\\Matthew\\Anaconda3\\Scripts;C:\
\Users\\Matthew\\Anaconda3",
    "PYTHONHOME": "<not set>",
    "PYTHONPATH": "<not set>",
    "REQUESTS_CA_BUNDLE": "<not set>",
    "SSL_CERT_FILE": "<not set>"
  },
  "envs": [],
  "envs_dirs": [
    "C:\\Users\\Matthew\\Anaconda3\\envs",
    "C:\\Users\\Matthew\\AppData\\Local\\conda\\conda\\envs",
    "C:\\Users\\Matthew\\.conda\\envs"
  ],
  "is_windows_admin": false,
  "netrc_file": null,
  "offline": false,
  "pkgs_dirs": [
    "C:\\Users\\Matthew\\Anaconda3\\pkgs",
    "C:\\Users\\Matthew\\AppData\\Local\\conda\\conda\\pkgs"
  ],
  "platform": "win-64",
  "python_version": "3.6.3.final.0",
  "rc_path": "C:\\Users\\Matthew\\.condarc",
  "requests_version": "2.18.4",
  "root_prefix": "C:\\Users\\Matthew\\Anaconda3",
  "root_writable": true,
  "site_dirs": [],
  "sys.executable": "C:\\Users\\Matthew\\Anaconda3\\python.exe",
  "sys.prefix": "C:\\Users\\Matthew\\Anaconda3",
  "sys.version": "3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v
.1900 64 bit (AMD64)]",
  "sys_rc_path": "C:\\Users\\Matthew\\Anaconda3\\.condarc",
  "user_agent": "conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/8.1 Windows/
6.3.9600",
  "user_rc_path": "C:\\Users\\Matthew\\.condarc"
}

(C:\Users\Matthew\Anaconda3) C:\Users\Matthew>

**Comment by goanpeca** [comment] 2017-11-04 17:52
@mingwandroid do you see anything unusual with the path?

**Comment by mjmarz** [comment] 2017-11-04 18:02
If it helps the empty quotations eg "PYTHONHOME":"" show up as "PYTHONHOME":"<not set>" in the command prompt. I just noticed the <not set> did not copy over.

**Comment by mjmarz** [comment] 2017-11-04 18:04
sorry it say "not set" with the <> symbols ie "PYTHONHOME":"not set" but with the not set inside the <> symbols

**Comment by mjmarz** [comment] 2017-11-06 22:54
@goanpeca FYI the issue appears to have been resolved. Not entirely sure what happened but I am no longer encountering the error and Navigator launches satisfactorily. Thanks for the support anyhow...

**Comment by goanpeca** [comment] 2017-11-07 00:42
@mjmarz thanks for the feedback. Not sure what was the cause. Glad to know its working now.
