### ISSUE TITLE
anaconda navigator and spyder not working

### ISSUE THREAD

**Issue by junejashubh** [ContinuumIO/anaconda-issues#9596] opened 2018-06-13 18:34 UTC
![untitled](https://user-images.githubusercontent.com/34593420/41370891-779c2d0e-6f66-11e8-9ec4-fbddeb82eab3.png)

even after reseting spyder it is not working

**Comment by ccordoba12** [comment] 2018-06-13 20:36
Duplicate of #9593. Please close.

**Closed** 2018-06-13 20:40 UTC
