### ISSUE TITLE
sqlite3 arrow keys issues

### ISSUE THREAD

**Issue by saiwing-yeung** [ContinuumIO/anaconda-issues#882] opened 2016-07-04 21:08 UTC
I have anaconda (osx-64, ver 4.0.5), which comes with SQLite version 3.9.2.

None of the arrow keys work. For example, pressing the left arrow produces `^[[D`.

A related issue is that once this happens you can't recover from it (at least I haven't figured out how to). The only ways I have found to be able to break out of this is to press Ctrl-C 3 times or Ctrl-D, both ends the current SQLite session.

The SQLite that comes with OS X (/usr/bin/sqlite3; SQLite version 3.8.10.2) doesn't have this issue.

**Comment by nehaljwani** [comment] 2017-05-19 04:50
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/307

**Closed by nehaljwani** 2017-05-19 04:50 UTC
Labels: reso:duplicate
