### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by paintingpeter** [ContinuumIO/anaconda-issues#1021] opened 2016-08-29 17:49 UTC
Anaconda Navigator Update error:

Extra data: line 2 column 1 (char 81)

{'platform': 'osx-64', 'qt': '4.8.7', 'version': '1.2.2', 'language': 'en', 'pyqt': '4.11.4', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'python': '3.5.1', 'conda': '4.1.11'}

**Comment by goanpeca** [comment] 2016-08-29 19:20
Hi @paintingpeter  thanks for reporting, the new version of Navigator has fixed this error.

Will close as this is a duplicate of #969

**Closed by goanpeca** 2016-08-29 19:20 UTC
