### ISSUE TITLE
`grammar3.6.txt` is missing

### ISSUE THREAD

**Issue by ciupicri** [ContinuumIO/anaconda-issues#1724] opened 2017-05-13 23:54 UTC
The file `Anaconda3\lib\site-packages\jedi\parser\python\grammar3.6.txt` seems to be missing. If I type `import j` in IPython or Jupyter QT, and then press <kbd>Tab</kbd>, I get this:

```
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\jedi\parser\python\__init__.py", line 42, in load_grammar
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\jedi\\parser\\python\\grammar3.6.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\jedi\parser\python\__init__.py", line 39, in load_grammar
    return _loaded_grammars[path]
KeyError: 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\jedi\\parser\\python\\grammar3.6.txt'

During handling of the above exception, another exception occurred:
```

I'm using an up to date Anaconda3-4.3.1-Windows-x86_64 install with **jedi 0.10.2 py36_0**.

**Comment by vc5** [comment] 2017-05-14 09:38
+1

**Comment by mingwandroid** [comment] 2017-05-14 21:02
Fixing this now.

**Comment by ccordoba12** [comment] 2017-05-14 22:08
@mingwandroid, this means Jedi 0.10.2 is failing badly?

**Comment by mingwandroid** [comment] 2017-05-14 22:19
Yeah. The new ones are very nearly ready.

**Comment by ccordoba12** [comment] 2017-05-14 22:20
Thanks!! We're receiving several complaints about code completion being broken in Spyder, so this should be the cause.

**Comment by mingwandroid** [comment] 2017-05-14 22:23
The recipe was missing a setuptools build dependency. I also added a test (on Unix anyway) that the grammar files got built. Just waiting for the Windows builds.

**Comment by mingwandroid** [comment] 2017-05-14 22:49
Done.

**Comment by ccordoba12** [comment] 2017-05-16 23:46
Closing since this seems solved. @ciupicri, please reopen if that's not the case.

**Closed by ccordoba12** 2017-05-16 23:46 UTC
