### ISSUE TITLE
after update pandas to latest 0.15.2 import fails on "cannot import name hashtable"

### ISSUE THREAD

**Issue by chanansh** [ContinuumIO/anaconda-issues#256] opened 2015-02-02 08:43 UTC
A clean anaconda installation + update spyder + update pandas
reverting to pandas 0.14.1 solves but I need new pandas functionality 

```
import pandas
cannot import name 'hashtable'
Traceback (most recent call last):

  File "<ipython-input-1-d6ac987968b6>", line 1, in <module>
    import pandas

  File "C:\Anaconda3\lib\site-packages\pandas\__init__.py", line 7, in <module>
    from . import hashtable, tslib, lib

ImportError: cannot import name 'hashtable'

```

```
Current conda install:

             platform : win-64
        conda version : 3.8.3
  conda-build version : 1.8.2
       python version : 3.4.1.final.0
     requests version : 2.5.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False
```

```
# packages in environment at C:\Anaconda3:
#
anaconda                  2.1.0                np19py34_0
argcomplete               0.8.1                    py34_0
astropy                   0.4.2                np19py34_0
beautiful-soup            4.3.2                    py34_0
beautifulsoup4            4.3.2                     <pip>
binstar                   0.7.1                    py34_0
bitarray                  0.8.1                    py34_1
blaze                     0.6.3                np19py34_0
blz                       0.6.2                np19py34_0
bokeh                     0.6.1                np19py34_0
boto                      2.32.1                   py34_0
cffi                      0.8.6                    py34_0
colorama                  0.3.1                    py34_0
conda                     3.8.3                    py34_0
conda-build               1.8.2                    py34_0
conda-env                 2.0.1                    py34_0
configobj                 5.0.6                    py34_0
cryptography              0.5.4                    py34_0
cython                    0.21                     py34_0
cytoolz                   0.7.0                    py34_0
datashape                 0.3.0                np19py34_1
dateutil                  2.1                      py34_2
decorator                 3.4.0                    py34_0
docutils                  0.12                     py34_0
dynd-python               0.6.5                np19py34_0
flask                     0.10.1                   py34_1
future                    0.13.1                   py34_0
greenlet                  0.4.4                    py34_0
h5py                      2.3.1                np19py34_0
ipython                   2.3.1                    py34_0
ipython-notebook          2.2.0                    py34_0
ipython-qtconsole         2.2.0                    py34_0
itsdangerous              0.24                     py34_0
jdcal                     1.0                      py34_0
jinja2                    2.7.3                    py34_1
launcher                  1.0.0                         1
libpython                 1.0                      py34_1
llvmpy                    0.12.7                   py34_0
lxml                      3.4.0                    py34_0
markupsafe                0.23                     py34_0
matplotlib                1.4.0                np19py34_0
menuinst                  1.0.4                    py34_0
mingw                     4.7                           1
mock                      1.0.1                    py34_0
multipledispatch          0.4.7                    py34_0
networkx                  1.9.1                    py34_0
nltk                      3.0.0                np19py34_0
node-webkit               0.10.1                        0
nose                      1.3.4                    py34_0
numba                     0.14.0               np19py34_0
numexpr                   2.3.1                np19py34_0
numpy                     1.9.1                    py34_0
openpyxl                  1.8.5                    py34_0
pandas                    0.15.2               np19py34_0
patsy                     0.3.0                np19py34_0
pip                       1.5.6                    py34_0
ply                       3.4                      py34_0
psutil                    2.1.1                    py34_0
py                        1.4.25                   py34_0
pycosat                   0.6.1                    py34_0
pycparser                 2.10                     py34_0
pycrypto                  2.6.1                    py34_2
pyflakes                  0.8.1                    py34_0
pygments                  2.0.1                    py34_0
pyopenssl                 0.14                     py34_0
pyparsing                 2.0.1                    py34_0
pyqt                      4.10.4                   py34_0
pyreadline                2.0                      py34_0
pytables                  3.1.1                np19py34_1
pytest                    2.6.3                    py34_0
python                    3.4.1                         2
python-dateutil           2.1                       <pip>
pytz                      2014.9                   py34_0
pywin32                   219                      py34_0
pyyaml                    3.11                     py34_0
pyzmq                     14.5.0                   py34_0
requests                  2.5.1                    py34_0
rope                      0.9.4                    py34_1
rope-py3k-0.9.4           1                         <pip>
runipy                    0.1.1                    py34_0
scikit-image              0.10.1               np19py34_0
scikit-learn              0.15.2               np19py34_0
scipy                     0.15.1               np19py34_0
setuptools                12.0.5                   py34_0
six                       1.9.0                    py34_0
sockjs-tornado            1.0.1                    py34_0
sphinx                    1.2.3                    py34_0
spyder                    2.3.2                    py34_0
spyder-app                2.3.1                    py34_0
sqlalchemy                0.9.7                    py34_0
statsmodels               0.5.0                np19py34_2
sympy                     0.7.5                    py34_0
tables                    3.1.1                     <pip>
toolz                     0.7.0                    py34_0
tornado                   4.0.2                    py34_0
ujson                     1.33                     py34_0
werkzeug                  0.9.6                    py34_1
xlrd                      0.9.3                    py34_0
xlsxwriter                0.5.7                    py34_0
```

**Comment by asmeurer** [comment] 2015-02-02 20:22
Try `conda install -f pandas`

**Comment by ccordoba12** [comment] 2015-02-02 20:43
Yes, and please close Spyder and all Python processes you have open before doing that.

**Comment by oliveirarodolfo** [comment] 2015-03-03 16:42
I had the same problem here, as suggested by @asmeurer ``conda install -f pandas`` solved my problem.

**Comment by ccordoba12** [comment] 2015-04-10 19:43
Closing because @oliveirarodolfo confirmed that the suggested solution works for him.

**Comment by tswicegood** [comment] 2015-04-13 05:30
Re-opening.  About to open a PR that will help with the root cause of this

**Closed** 2017-05-17 03:52 UTC
Labels: os:windows, type:bug
