### ISSUE TITLE
Navigator Error - occured on start-up

### ISSUE THREAD

**Issue by mroman09** [ContinuumIO/anaconda-issues#2805] opened 2017-07-03 13:07 UTC
# Navigator Error

An unexpected error occurred on Navigator start-up

# Report

Please report this issue in the anaconda issue tracker

# Main Error

string indices must be integers, not str
Traceback

Traceback (most recent call last):
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/Users/mikeroman/anaconda/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

# System Information

python: 2.7.11
language: en
os: Mac OS Sierra 10.12.5
conda: 4.0.8

**Comment by goanpeca** [comment] 2017-07-04 14:39
Closing as duplicate of #1837

Please update to the latest version of Navigator.

Open a terminal and type:

```
$ conda update anaconda-navigator

**Closed by goanpeca** 2017-07-04 14:39 UTC
