### ISSUE TITLE
reinstall anaconda and get " ImportError: No module named 'PyQt4' "

### ISSUE THREAD

**Issue by funnybomb** [ContinuumIO/anaconda-issues#1158] opened 2016-10-14 13:56 UTC
I reinstall anaconda3 recently and download new Anaconda3-4.2.0-Linux-x86_64.sh from
and got this error: 

In [1]: import matplotlib.pyplot as plt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-eff513f636fd> in <module>()
----> 1 import matplotlib.pyplot as plt

/home/fcaiyi/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py in <module>()
    112 
    113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    115 
    116 _IP_REGISTERED = None

/home/fcaiyi/anaconda3/lib/python3.5/site-packages/matplotlib/backends/__init__.py in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/home/fcaiyi/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py in <module>()
     14 
     15 from .backend_agg import FigureCanvasAgg
---> 16 from .backend_qt5 import QtCore
     17 from .backend_qt5 import QtGui
     18 from .backend_qt5 import FigureManagerQT

/home/fcaiyi/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py in <module>()
     29     figureoptions = None
     30 
---> 31 from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
     32 from matplotlib.backends.qt_editor.formsubplottool import UiSubplotTool
     33 

/home/fcaiyi/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py in <module>()
    135     # have been changed in the above if block
    136     if QT_API in [QT_API_PYQT, QT_API_PYQTv2]:  # PyQt4 API
--> 137         from PyQt4 import QtCore, QtGui
    138 
    139         try:

ImportError: No module named 'PyQt4'

conda info:
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.6
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/fcaiyi/anaconda3  (writable)
    default environment : /home/fcaiyi/anaconda3
       envs directories : /home/fcaiyi/anaconda3/envs
          package cache : /home/fcaiyi/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

conda list:
# packages in environment at /home/fcaiyi/anaconda3:
#
_license                  1.1                      py35_1  
_nb_ext_conf              0.3.0                    py35_0  
alabaster                 0.7.9                    py35_0  
anaconda                  4.2.0               np111py35_0  
anaconda-clean            1.0.0                    py35_0  
anaconda-client           1.5.1                    py35_0  
anaconda-navigator        1.3.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astroid                   1.4.7                    py35_0  
astropy                   1.2.1               np111py35_0  
babel                     2.3.4                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.5.1                    py35_0  
bitarray                  0.8.1                    py35_0  
blaze                     0.10.1                   py35_0  
bokeh                     0.12.2                   py35_0  
boto                      2.42.0                   py35_0  
bottleneck                1.1.0               np111py35_0  
cairo                     1.12.18                       6  
cffi                      1.7.0                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.6                      py35_0  
cloudpickle               0.2.1                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.7                    py35_0  
conda                     4.2.9                    py35_0  
conda-build               2.0.6                    py35_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py35_0  
contextlib2               0.5.3                    py35_0  
cryptography              1.5                      py35_0  
curl                      7.49.0                        1  
cycler                    0.10.0                   py35_0  
cython                    0.24.1                   py35_0  
cytoolz                   0.8.0                    py35_0  
dask                      0.11.0                   py35_0  
datashape                 0.5.2                    py35_0  
dbus                      1.10.10                       0  
decorator                 4.0.10                   py35_0  
dill                      0.2.5                    py35_0  
docutils                  0.12                     py35_2  
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2                    py35_0  
et_xmlfile                1.0.1                    py35_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py35_1  
filelock                  2.0.6                    py35_0  
flask                     0.11.1                   py35_0  
flask-cors                2.1.2                    py35_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
get_terminal_size         1.0.0                    py35_0  
gevent                    1.1.2                    py35_0  
glib                      2.43.0                        1  
greenlet                  0.4.10                   py35_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np111py35_2  
harfbuzz                  0.9.39                        1  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py35_1  
icu                       54.1                          0  
idna                      2.1                      py35_0  
imagesize                 0.7.1                    py35_0  
ipykernel                 4.5.0                    py35_0  
ipython                   5.1.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                5.2.2                    py35_0  
itsdangerous              0.24                     py35_0  
jbig                      2.1                           0  
jdcal                     1.2                      py35_1  
jedi                      0.9.0                    py35_1  
jinja2                    2.8                      py35_1  
jpeg                      8d                            2  
jsonschema                2.5.1                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            4.4.0                    py35_0  
jupyter_console           5.0.0                    py35_0  
jupyter_core              4.2.0                    py35_0  
lazy-object-proxy         1.2.1                    py35_0  
libdynd                   0.7.2                         0  
libffi                    3.2.1                         0  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxcb                    1.12                          0  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.13.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.6.4                    py35_0  
markupsafe                0.23                     py35_2  
matplotlib                1.5.3               np111py35_0  
mistune                   0.7.3                    py35_0  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py35_2  
mpmath                    0.19                     py35_1  
multipledispatch          0.4.8                    py35_0  
nb_anacondacloud          1.2.0                    py35_0  
nb_conda                  2.0.0                    py35_0  
nb_conda_kernels          2.0.0                    py35_0  
nbconvert                 4.2.0                    py35_0  
nbformat                  4.1.0                    py35_0  
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.1                    py35_0  
nose                      1.3.7                    py35_1  
notebook                  4.2.3                    py35_0  
numba                     0.28.1              np111py35_0  
numexpr                   2.6.1               np111py35_0  
numpy                     1.11.1                   py35_0  
odo                       0.5.0                    py35_1  
openpyxl                  2.3.2                    py35_0  
openssl                   1.0.2j                        0  
pandas                    0.18.1              np111py35_0  
partd                     0.3.6                    py35_0  
patchelf                  0.9                           0  
path.py                   8.2.1                    py35_0  
pathlib2                  2.1.0                    py35_0  
patsy                     0.4.1                    py35_0  
pep8                      1.7.0                    py35_0  
pexpect                   4.0.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    3.3.1                    py35_0  
pip                       8.1.2                    py35_0  
pixman                    0.32.6                        0  
pkginfo                   1.3.2                    py35_0  
ply                       3.9                      py35_0  
prompt_toolkit            1.0.3                    py35_0  
psutil                    4.3.1                    py35_0  
ptyprocess                0.5.1                    py35_0  
py                        1.4.31                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_1  
pycparser                 2.14                     py35_1  
pycrypto                  2.6.1                    py35_4  
pycurl                    7.43.0                   py35_0  
pyflakes                  1.3.0                    py35_0  
pygments                  2.1.3                    py35_0  
pylint                    1.5.4                    py35_1  
pyopenssl                 16.0.0                   py35_0  
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_0  
pytables                  3.2.3.1             np111py35_0  
pytest                    2.9.2                    py35_0  
python                    3.5.2                         0  
python-dateutil           2.5.3                    py35_0  
pytz                      2016.6.1                 py35_0  
pyyaml                    3.12                     py35_0  
pyzmq                     15.4.0                   py35_0  
qt                        5.6.0                         0  
qtawesome                 0.3.3                    py35_0  
qtconsole                 4.2.1                    py35_1  
qtpy                      1.1.2                    py35_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py35_0  
requests                  2.11.1                   py35_0  
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.14                  py35_0  
scikit-image              0.12.3              np111py35_1  
scikit-learn              0.17.1              np111py35_2  
scipy                     0.18.1              np111py35_0  
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.4.6                    py35_0  
spyder                    3.0.0                    py35_0  
sqlalchemy                1.0.13                   py35_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py35_1  
sympy                     1.0                      py35_0  
terminado                 0.6                      py35_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py35_0  
tornado                   4.4.1                    py35_0  
traitlets                 4.3.0                    py35_0  
unicodecsv                0.14.1                   py35_0  
wcwidth                   0.1.7                    py35_0  
werkzeug                  0.11.11                  py35_0  
wheel                     0.29.0                   py35_0  
widgetsnbextension        1.2.6                    py35_0  
wrapt                     1.10.6                   py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.3                    py35_0  
xlwt                      1.1.2                    py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3

**Comment by jjhelmus** [comment] 2016-10-14 15:28
I'm seeing the same issue in some of my CI builds but only with Python 2.7.  Specifying qt=4 when creating the environment is a work-around.

 A minimal example to reproduce:

```
[root@ff5143f95831 /]# conda create -n test python=2.7 matplotlib
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /opt/conda/envs/test:

The following NEW packages will be INSTALLED:

    cairo:            1.12.18-6         defaults
    cycler:           0.10.0-py27_0     defaults
    dbus:             1.10.10-0         defaults
    expat:            2.1.0-0           defaults
    fontconfig:       2.11.1-6          defaults
    freetype:         2.5.5-1           defaults
    glib:             2.43.0-1          defaults
    gst-plugins-base: 1.8.0-0           defaults
    gstreamer:        1.8.0-0           defaults
    icu:              54.1-0            defaults
    jpeg:             8d-2              defaults
    libffi:           3.2.1-0           defaults
    libgcc:           5.2.0-0           defaults
    libpng:           1.6.22-0          defaults
    libxcb:           1.12-0            defaults
    libxml2:          2.9.2-0           defaults
    matplotlib:       1.5.3-np111py27_0 defaults
    mkl:              11.3.3-0          defaults
    numpy:            1.11.2-py27_0     defaults
    openssl:          1.0.2j-0          defaults
    pip:              8.1.2-py27_0      defaults
    pixman:           0.32.6-0          defaults
    pycairo:          1.10.0-py27_0     defaults
    pyparsing:        2.1.4-py27_0      defaults
    pyqt:             5.6.0-py27_0      defaults
    python:           2.7.12-1          defaults
    python-dateutil:  2.5.3-py27_0      defaults
    pytz:             2016.7-py27_0     defaults
    qt:               5.6.0-1           defaults
    readline:         6.2-2             defaults
    setuptools:       27.2.0-py27_0     defaults
    sip:              4.18-py27_0       defaults
    six:              1.10.0-py27_0     defaults
    sqlite:           3.13.0-0          defaults
    tk:               8.5.18-0          defaults
    wheel:            0.29.0-py27_0     defaults
    zlib:             1.2.8-3           defaults

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#############################################################| 100%
dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id
#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#
[root@ff5143f95831 /]# source activate test
discarding /opt/conda/bin from PATH
prepending /opt/conda/envs/test/bin to PATH
(test)[root@ff5143f95831 /]# python -c "import matplotlib.pyplot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/test/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/conda/envs/test/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/opt/conda/envs/test/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/opt/conda/envs/test/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/opt/conda/envs/test/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
```

**Comment by jjhelmus** [comment] 2016-10-14 15:58
Looks like the root cause of this is that the linux-64 pyqt 5.6.0-py27_0 package links against libXdmcp which may not exist on the host machine.  

```
(test)[root@ff5143f95831 /]# python -c "from PyQt5 import QtGui"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libXdmcp.so.6: cannot open shared object file: No such file or directory
(test)[root@ff5143f95831 /]# ldd /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/QtGui.so
ldd: warning: you do not have execution permission for `/opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/QtGui.so'
	linux-vdso.so.1 =>  (0x00007ffd5059e000)
	libQt5Gui.so.5 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5 (0x00007f9665921000)
	libQt5Core.so.5 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../../libQt5Core.so.5 (0x00007f96651b8000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f9664f29000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9664d0c000)
	libstdc++.so.6 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../../libstdc++.so.6 (0x00007f966494f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f96646cb000)
	libgcc_s.so.1 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../../libgcc_s.so.1 (0x00007f96644b4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f966411f000)
	libpng16.so.16 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../.././libpng16.so.16 (0x00007f9663ede000)
	libz.so.1 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../.././libz.so.1 (0x00007f9663cc7000)
	libicui18n.so.54 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../.././libicui18n.so.54 (0x00007f9663863000)
	libicuuc.so.54 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../.././libicuuc.so.54 (0x00007f96634c4000)
	libicudata.so.54 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../.././libicudata.so.54 (0x00007f9661a9a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9661896000)
	libgthread-2.0.so.0 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../.././libgthread-2.0.so.0 (0x00007f9661694000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f966148c000)
	libglib-2.0.so.0 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../.././libglib-2.0.so.0 (0x00007f966114e000)
	/lib64/ld-linux-x86-64.so.2 (0x000056174acec000)
	libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007f9660f1f000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f9660d00000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f9660aee000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007f96608eb000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f96606e6000)
	libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007f96604e5000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f96601a7000)
	libxcb-glx.so.0 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../../libxcb-glx.so.0 (0x00007f965ff8f000)
	libxcb-dri2.so.0 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../../libxcb-dri2.so.0 (0x00007f965fd8b000)
	libxcb.so.1 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../../libxcb.so.1 (0x00007f965fb65000)
	libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007f965f960000)
	libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007f965f753000)
	libexpat.so.1 => /opt/conda/envs/test/lib/python2.7/site-packages/PyQt5/../../../libexpat.so.1 (0x00007f965f52a000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f965f326000)
	libXdmcp.so.6 => not found
(test)[root@ff5143f95831 /]# yum install libXdmcp
...
(test)[root@ff5143f95831 /]# python -c "from PyQt5 import QtGui"
(test)[root@ff5143f95831 /]#
```

Is it possible to build PyQt5 without linking against libXdmcp?

**Comment by jjhelmus** [comment] 2016-10-14 16:11
This issue seems to be a repeat of #1068, moving discussion there.

**Comment by ccordoba12** [comment] 2016-10-14 23:16
Yep, closing in favor of #1068.

**Closed by ccordoba12** 2016-10-14 23:16 UTC
