### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Dipugee** [ContinuumIO/anaconda-issues#1032] opened 2016-09-01 00:11 UTC
Anaconda Navigator Update error:

Extra data: line 2 column 1 (char 81)

{'language': 'en', 'os': 'Darwin;15.6.0;Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64;x86_64;i386', 'version': '1.2.2', 'pyqt': '4.11.4', 'conda': '4.1.11', 'platform': 'osx-64', 'qt': '4.8.7', 'python': '3.5.2'}

**Comment by Dipugee** [comment] 2016-09-01 00:13
I had another question...Is there a new version of Spyder, with Jupyter integrated, coming soon? If so, when?

Thanks.

Dipu

**Comment by goanpeca** [comment] 2016-09-01 00:44
@ccordoba12

**Comment by ccordoba12** [comment] 2016-09-01 01:04
> Is there a new version of Spyder, with Jupyter integrated, coming soon? If so, when?

There is a new version of Spyder coming soon, but unfortunately it won't have Jupyter integration :-(

**Comment by Dipugee** [comment] 2016-09-01 01:07
What will the new version have as improvements?

**Comment by ccordoba12** [comment] 2016-09-01 01:11
Short version:

https://github.com/spyder-ide/spyder/releases/tag/v3.0.0b6

Long version:

https://github.com/spyder-ide/spyder/wiki/Beta-version-changelog

**Comment by goanpeca** [comment] 2016-09-07 16:38
Hi @Dipugee thanks for reporting, this has been fixed in the new version of navigator coming soon.

Closing as it is a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/969

**Closed** 2016-09-07 16:37 UTC
