### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by tina9299** [ContinuumIO/anaconda-issues#3501] opened 2017-07-24 09:18 UTC
Traceback (most recent call last):
File "E:\Anaconda\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "E:\Anaconda\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "E:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "E:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "E:\Anaconda\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "E:\Anaconda\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "E:\Anaconda\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=12272)

**Comment by goanpeca** [comment] 2017-07-24 09:22
Closing as duplicate of #1984

Please update to the latest version of Navigator.

on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-24 09:22 UTC
