### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by g-gollin** [ContinuumIO/anaconda-issues#11327] opened 2019-09-29 00:32 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
conda: 4.3.30
version: 1.6.2
platform: osx-64
os: Darwin;18.7.0;Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64;x86_64;i386
python: 3.5.3
qt: 5.6.2
language: en
pyqt: 5.6.0
```

**Comment by csoja** [comment] 2019-11-05 20:33
Duplicate of #1778
Please see that issue for the solution.

**Closed by csoja** 2019-11-05 20:33 UTC
