### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by kz997** [ContinuumIO/anaconda-issues#12376] opened 2021-04-25 11:57 UTC
### Actual Behavior
'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 77, in __init__
    self._conda_api = CondaAPI()
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 371, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "/opt/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 540, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'

##### `conda info`

<details>

```
PASTE OUTPUT HERE:

```

</details>

##### `conda list --show-channel-urls`

<details>

```
PASTE OUTPUT HERE:

```

</details>

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 10:11
Duplicate of #11780

**Closed by vshevchenko-anaconda** 2023-07-07 10:11 UTC
