### ISSUE TITLE
PyQt5: undefined symbol: g_source_destroy

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#9270] opened 2018-04-29 18:59 UTC
When trying to run conda build for a package requiring Qt5 I tried using the recent Qt 5.9 builds but I am getting the following error during the test phase on Linux in CircleCI:

```
Traceback (most recent call last):
  File "/opt/conda/conda-bld/glue-core_1524960383918/test_tmp/run_test.py", line 8, in <module>
    import glue.app.qt
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/glue/app/qt/__init__.py", line 3, in <module>
    from .application import GlueApplication  # noqa
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/glue/app/qt/application.py", line 30, in <module>
    from glue.viewers.scatter.qt import ScatterViewer
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/glue/viewers/scatter/qt/__init__.py", line 1, in <module>
    from .data_viewer import ScatterViewer  # noqa
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/glue/viewers/scatter/qt/data_viewer.py", line 6, in <module>
    from glue.viewers.matplotlib.qt.data_viewer import MatplotlibDataViewer
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/glue/viewers/matplotlib/qt/data_viewer.py", line 6, in <module>
    from glue.viewers.matplotlib.qt.widget import MplWidget
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/glue/viewers/matplotlib/qt/widget.py", line 7, in <module>
    from matplotlib.figure import Figure
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/matplotlib/figure.py", line 51, in <module>
    from matplotlib.backend_bases import NonGuiException
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 61, in <module>
    from PIL import Image
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/PIL/Image.py", line 136, in <module>
    from pathlib2 import Path
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/pathlib2/__init__.py", line 46, in <module>
    from scandir import scandir as os_scandir
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/scandir.py", line 439, in <module>
    libc = ctypes.CDLL(ctypes.util.find_library('c'), use_errno=True)
  File "/opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/conda-bld/glue-core_1524960383918/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/PyQt5/../../.././libgobject-2.0.so.0: undefined symbol: g_source_destroy
```

The relevant package versions that got installed are:

```
    glib:             2.56.1-h000015b_0    
    pyqt:             5.9.2-py27h751905a_0 
    qt:               5.9.5-h7e424d6_0     
```

whereas things work fine with:

```
    glib:                               2.53.6-h5d9569c_2                    
    pyqt:                               5.6.0-py27h4b1e83c_5            
    qt:                                 5.6.2-hd25b39d_14    
```

If you are not sure how to reproduce the issue I can come up with a minimal example on CircleCI.

Full log of conda-build job: https://circleci.com/gh/glue-viz/conda-dev/102

**Comment by mingwandroid** [comment] 2018-04-30 14:56
Please provide a minimal example if you can @astrofrog.

**Comment by nehaljwani** [comment] 2018-05-03 04:54
This can be reproduced without a docker container.

**Comment by nehaljwani** [comment] 2018-05-03 05:37
Steps to repro:
```
conda create -yn test10 python=2 pyqt matplotlib pathlib2 pillow
conda activate test10
python -c 'import PyQt5.Qt; import matplotlib.pyplot'
```

**Comment by mingwandroid** [comment] 2018-05-03 09:28
You need to install some more system libraries due to QtWebEngine which requires basically all the low-level libraries necessary for a desktop experience (since it's a full web browser engine).

`yum install libgl1-mesa-glx mesa-libGL libXcomposite libXcursor libXi libXtst libXScrnSaver libXrandr alsa-lib mesa-libEGL`

**Comment by mingwandroid** [comment] 2018-05-03 09:30
BTW (and I know this is only a test-case but we did find real world examples already) if any project is doing `import PyQt5.Qt` it should be changed not to since in most cases that will load a huge amount of software the project does not need.

**Comment by nehaljwani** [comment] 2018-05-03 13:05
@mingwandroid If I remove pathlib2 from my environment, then I don't face this issue. I already have all of the low-level libraries necessary as I was running this on a full fledged desktop.

**Comment by mingwandroid** [comment] 2018-05-03 20:32
So the natural question is which system dependency does `pathlib2` introduce? Maybe look at the `CDT` packages it brings in (if any?)

**Comment by nehaljwani** [comment] 2018-05-04 05:27
As Ray pointed out, if I do:
```
ldd <path/to/test-env>/lib/python3.6/site-packages/PyQt5/QtWebEngine.so | grep not
```
And install all the missing deps, the problem goes away.

**Comment by mingwandroid** [comment] 2018-05-04 08:04
We do need to document these extended dependencies for the most common linux distros and update any docker or other CI files we are in charge of too.

Pinging @csoja about that (and closing, again!)

**Closed by mingwandroid** 2018-05-04 08:04 UTC
