### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by SouravRaha-dev** [ContinuumIO/anaconda-issues#2328] opened 2017-06-16 18:03 UTC
Fresh Installation on Ubuntu 16.04 LTS (64 bit) Anaconda3-4.4.0-Linux-x86_64.sh

I locked the Navigator icon on launcher after starting anaconda navigator from terminal as:
$ anaconda-navigator
But later on clicking the navigator icon from launcher, the following message is displayed:

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

byte indices must be integers or slices, not str
Traceback

Traceback (most recent call last):
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 111, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/external/filelock.py", line 254, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock '/home/sourav/.anaconda/navigator/navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 124, in start_app
    "There is an instance of "
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/dialogs/__init__.py", line 450, in __init__
    type_=self.INFORMATION_BOX,
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/dialogs/__init__.py", line 265, in __init__
    self.tracker = GATracker()
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/analytics.py", line 284, in GATracker
    GA_TRACKER = _GATracker()
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/analytics.py", line 95, in __init__
    self.api = AnacondaAPI()
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/sourav/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

What am I doing wrong? or what is the solution ?

**Comment by goanpeca** [comment] 2017-06-16 18:03
Closing as duplicate of #1837

**Closed by goanpeca** 2017-06-16 18:03 UTC
