### ISSUE TITLE
Anaconda Navigator Access Denied...

### ISSUE THREAD

**Issue by mnsblondie** [ContinuumIO/anaconda-issues#8659] opened 2018-02-24 00:57 UTC
### Actual Behavior

I get this:

Traceback (most recent call last):
File "C:\Users\Marie\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\Marie\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\Marie\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\Marie\Anaconda2\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\Marie\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=3196)

When trying to open Anaconda Navigator. I've updated the navigator and it still gives this error. I'm really not sure where to look to fix it

##### `conda info`

```
>anaconda-navigator --version
1.7.0

 active environment : base
    active env location : C:\Users\Marie\Anaconda2
            shell level : 1
       user config file : C:\Users\Marie\.condarc
 populated config files : C:\Users\Marie\.condarc
          conda version : 4.4.10
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       base environment : C:\Users\Marie\Anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\Marie\Anaconda2\pkgs
                          C:\Users\Marie\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Marie\Anaconda2\envs
                          C:\Users\Marie\AppData\Local\conda\conda\envs
                          C:\Users\Marie\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at C:\Users\Marie\Anaconda2:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h9111531_0    defaults
anaconda                  custom           py27h689e5c3_0    defaults
anaconda-client           1.6.5            py27h9642776_0    defaults
anaconda-navigator        1.7.0                    py27_0    defaults
msgpack-python            0.4.8            py27he0366a1_0    defaults
multipledispatch          0.4.9            py27h8ebb51e_0    defaults
mysql-connector-python    2.0.4                    py27_0    anaconda
mysql-connector-python    2.1.7                     <pip>
navigator-updater         0.1.0            py27h5e42984_0    defaults

```

**Comment by goanpeca** [comment] 2018-02-24 19:24
Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #1984 for more information on how to fix this.**

Or you can run on the Terminal or Anaconda prompt:

```
anaconda-navigator --reset
```

**Closed by goanpeca** 2018-02-24 19:24 UTC
