### ISSUE TITLE
mpi4py is not available in python 3.7

### ISSUE THREAD

**Issue by rainwoodman** [ContinuumIO/anaconda-issues#11406] opened 2019-10-28 00:58 UTC
What is the longer term plan for mpi4py on the default anaconda channel?

mpi4py on anaconda channel is one major version behind the upstream (2.0.0 vs 3.0.2), and not built for python 3.7.

**Comment by rgommers** [comment] 2019-11-01 10:37
this is a duplicate of gh-10018

**Comment by jjhelmus** [comment] 2019-12-03 22:23
mpi4py 3.0.3 packages are now available for linux-64, linux-ppc64le, and osx-64.

**Closed by jjhelmus** 2019-12-03 22:23 UTC
Labels: tag-package_request, type-packaging
