### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by lalitkpal** [ContinuumIO/anaconda-issues#10868] opened 2019-04-25 18:28 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
/Users/Lalit/anaconda/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.5.11
qt: 5.6.2
language: en
python: 2.7.6
os: Darwin;18.2.0;Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by csoja** [comment] 2019-04-25 18:44
Duplicate of #1778
Please see that issue for the solution.

**Closed by csoja** 2019-04-25 18:44 UTC
