### ISSUE TITLE
Issue with Anaconda Launcher

### ISSUE THREAD

**Issue by kengilbert** [ContinuumIO/anaconda-issues#459] opened 2015-10-06 16:15 UTC
I tried to start anaconda launcher. Got message saying "We've encountered and problem in Anaconda Launcher that we can't recover from."

---

## Uncaught Exception

```
Error: spawn conda ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1115:20
    at process._tickCallback (node.js:375:11)
```

## Platform Information

* Operating System: darwin
* Conda Version: 3.18.1
* Conda Platform: osx-64

```json
{
  "channels": [
    "https://repo.continuum.io/pkgs/free/osx-64/",
    "https://repo.continuum.io/pkgs/free/noarch/",
    "https://repo.continuum.io/pkgs/pro/osx-64/",
    "https://repo.continuum.io/pkgs/pro/noarch/"
  ],
  "conda_build_version": "not installed",
  "conda_version": "3.18.1",
  "default_prefix": "/Users/kgilbert/anaconda",
  "envs": [],
  "envs_dirs": [
    "/Users/kgilbert/anaconda/envs"
  ],
  "is_foreign": false,
  "pkgs_dirs": [
    "/Users/kgilbert/anaconda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "2.7.10.final.0",
  "rc_path": null,
  "requests_version": "2.7.0",
  "root_prefix": "/Users/kgilbert/anaconda",
  "root_writable": true,
  "sys_rc_path": "/Users/kgilbert/anaconda/.condarc",
  "user_rc_path": "/Users/kgilbert/.condarc",
  "condaBuildVersion": "not installed",
  "condaVersion": "3.18.1",
  "defaultPrefix": "/Users/kgilbert/anaconda",
  "envsDirs": [
    "/Users/kgilbert/anaconda/envs"
  ],
  "isForeign": false,
  "pkgsDirs": [
    "/Users/kgilbert/anaconda/pkgs"
  ],
  "pythonVersion": "2.7.10.final.0",
  "rcPath": null,
  "requestsVersion": "2.7.0",
  "rootPrefix": "/Users/kgilbert/anaconda",
  "rootWritable": true,
  "sysRcPath": "/Users/kgilbert/anaconda/.condarc",
  "userRcPath": "/Users/kgilbert/.condarc"
}
```

**Comment by goanpeca** [comment] 2015-10-15 14:07
Duplicate of #460

**Closed by goanpeca** 2015-10-15 14:07 UTC
