### ISSUE TITLE
Spyder Application Launch Error

### ISSUE THREAD

**Issue by LudgerHentschel** [ContinuumIO/anaconda-issues#5833] opened 2017-09-20 20:49 UTC
When I launch Spyder 3.2.3 from Anaconda Navigator 1.6.2, I see the error messages below. 

Spyder starts despite these error messages. 

This happens every time I launch Spyder from Anaconda Navigator. Other applications seem to launch from Anaconda Navigator without errors. 

The only problem I notice is that font smoothing in Spyder is terrible and not all fonts are available in the preferences. This may not be related to these launch errors, since I have had this problem for a long time without noticing the error messages. But I also have not used Anaconda Navigator in a long time. 

When I  reset Spyder's preferences to "Enable auto high DPI scaling", it asks to restart. Upon restart all appears well. The error messages do not show during the restart. 

## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.25
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-09-20 20:52
**See Issue #1778 for more information on how to fix this.**

---

Closing as duplicate of #1778


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-20 20:52 UTC
Labels: pkg:navigator, reso:duplicate
