### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by MMohey** [ContinuumIO/anaconda-issues#4017] opened 2017-08-08 12:05 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.23
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.5.0;Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-08-08 12:05
**See Issue #1778 for more information on how to fix this.**

---

Closing as duplicate of #1778


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-08 12:05 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by MMohey** [comment] 2017-08-08 13:24
@goanpeca @ccordoba12 

This hasn't resolved my issue and still spyder not working.

I followed the advice on https://github.com/spyder-ide/spyder/issues/3730#issuecomment-262588607 and still not working.

I did 
```
conda update spyder 
conda update anaconda-navigator
anaconda-navigator --reset
spyder --reset
export EVENT_NOKQUEUE=1
```

and nothing has changed and when I launch spyder, the launch error is the following:

> Traceback (most recent call last):
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3011, in main
> mainwindow = run_spyder(app, options, args)
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2913, in run_spyder
> main.setup()
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 873, in setup
> from spyder.plugins.ipythonconsole import IPythonConsole
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 60, in 
> from spyder.widgets.ipythonconsole import ClientWidget
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/__init__.py", line 12, in 
> from .debugging import DebuggingWidget
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/debugging.py", line 16, in 
> from qtconsole.rich_jupyter_widget import RichJupyterWidget
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 14, in 
> from .jupyter_widget import JupyterWidget
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 19, in 
> from IPython.lib.lexers import IPythonLexer, IPython3Lexer
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in 
> from .core.application import Application
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in 
> from IPython.core import release, crashhandler
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in 
> from IPython.core import ultratb
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in 
> from IPython.utils.terminal import get_terminal_size
> File "/Users/MohAfifi/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in 
> from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
> ImportError: No module named shutil_get_terminal_size
>

**Comment by MMohey** [comment] 2017-08-09 15:13
I found the only way to resolve that issue is completely uninstalling Anaconda-Navigator and all its related files, then reinstalling it again. Thanks.
