### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by myjz** [ContinuumIO/anaconda-issues#7010] opened 2017-10-31 04:40 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(ReadTimeoutError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out.",),)

```
## System information
```
language: zh_CN
pyqt: 5.6.0
python: 3.5.3
platform: win-64
conda: 4.3.27
qt: 5.6.2
os: Windows;10;10.0.14393;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
```

**Comment by goanpeca** [comment] 2017-10-31 04:43
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-31 04:43 UTC
Labels: pkg:navigator, reso:duplicate
