### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by rodeosaint** [ContinuumIO/anaconda-issues#5020] opened 2017-09-04 21:06 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 16:05:51.280 NotebookApp] Serving notebooks from local directory: /home/luke
[I 16:05:51.280 NotebookApp] 0 active kernels 
[I 16:05:51.281 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=81821f2e9b759b334296e82416939eb7e6051478b6b33cf3
[I 16:05:51.281 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:05:51.281 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=81821f2e9b759b334296e82416939eb7e6051478b6b33cf3
[7559:7559:0904/160551.605197:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
[I 16:05:51.989 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[I 16:05:57.926 NotebookApp] Creating new notebook in 
[I 16:05:58.585 NotebookApp] Kernel started: 13d4abe5-86ef-4ee7-98a8-e06a4bdd00a9

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.10.0-33-generic;#37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.22
```

**Comment by goanpeca** [comment] 2017-09-04 21:10
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-04 21:10 UTC
