### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by LudmilaDeute** [ContinuumIO/anaconda-issues#2695] opened 2017-06-29 01:06 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x108a541d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)

```
## System information
```
pyqt: 5.6.0
version: 1.6.2
platform: osx-64
qt: 5.6.2
language: en
conda: 4.3.22
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
python: 3.5.3
```

**Comment by goanpeca** [comment] 2017-06-29 13:34
Closing as duplicate of #1932

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-29 13:34 UTC
Labels: pkg:navigator, reso:duplicate
