### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by d00d** [ContinuumIO/anaconda-issues#10952] opened 2019-05-27 22:34 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.30
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;17.7.0;Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by csoja** [comment] 2019-06-07 15:27
Duplicate of #1778
Please see that issue for the solution.

**Closed by csoja** 2019-06-07 15:27 UTC
