### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ckshitij** [ContinuumIO/anaconda-issues#2188] opened 2017-06-12 04:47 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=3284)
## Traceback
```
Traceback (most recent call last):
  File "D:\conda\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "D:\conda\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\conda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\conda\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "D:\conda\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "D:\conda\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "D:\conda\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=3284)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by ckshitij** [comment] 2017-06-12 04:49
I m not able to start anaconda Navigator due to above mentioned issue . Can anybody have any idea ?
Please Help me Out .

**Comment by goanpeca** [comment] 2017-06-12 04:53
Closing as duplicate of #1984

**Closed by goanpeca** 2017-06-12 04:53 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by mohitmonu23** [comment] 2018-01-16 07:41
when i run the anaconda navigator is shows me like this 
Traceback (most recent call last):
File "C:\Users\asus\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\asus\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\asus\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\asus\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\asus\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\asus\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\asus\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=7360)

**Comment by goanpeca** [comment] 2018-01-16 20:01
Terminal or Anaconda prompt:

```
ancaonda-navigator --reset
```

**Comment by medeng** [comment] 2018-07-23 08:57
thank you so much that did the trick for my startup error
