### ISSUE TITLE
R channel packages errors, libgcc_s_seh-1.dll is missing

### ISSUE THREAD

**Issue by Diego-MX** [ContinuumIO/anaconda-issues#777] opened 2016-05-04 13:43 UTC
Dear Anacondians, 
I have an issue when running R from the Anaconda environment.   I set it up to be used with Jupyter  and I also set RStudio to use that install.  This is in a Windows 7 machine. 

The error appears when running R with Jupyter, RStudio and even from the console.  The window title is _R term.exe System error_ and reads the following,  

```
The program can't start because libgcc_s_seh-1.dll is missing from your computer. 
Try reinstalling the program to fix this problem. 
```

I did reinstall R, r-essentials and r-irkernel with `conda install`, and now I'm looking at what else to do... Please let me know if you need further info. 

Regards,

**Comment by Diego-MX** [comment] 2016-05-04 14:22
I did some tweaking.   
The R session by itself doesn't show that message, but it does when loading some of Hadley's libraries from _Rprofile.site_, these are _dplyr_, _ggplot2_, _tidyr_ but not others like _stringr_, _lubridate_, _magrittr_.  

The Jupyter and RStudio session do show the message even when disabling those packages.  

This suggests that the issue is related to some specific packages.

**Comment by mingwandroid** [comment] 2016-05-04 14:34
Hi @Diego-MX, can you paste your Rprofile.site please?

**Comment by Diego-MX** [comment] 2016-05-04 14:39
```
options(help_type="html")

# set a CRAN mirror
local({r <- getOption("repos")
     r["CRAN"] <- "https://cran.revolutionanalytics.com/"
     options(repos=r)})

# Give a fortune cookie, but only to interactive sessions
if (interactive()) fortunes::fortune()

library(lubridate)
library(magrittr)
library(stringr)
library(stats)   # Force STATS to be imported before DPLYR. 

#library(dplyr,   warn.conflicts = FALSE)
#library(ggplot2, warn.conflicts = FALSE)
#library(tidyr,   warn.conflicts = FALSE)
```

**Comment by mingwandroid** [comment] 2016-05-04 14:48
OK, I know what the issue is and can give you a workaround for now.

*Issue*

Our R interpreter needs an entry adding to its PATH environment to function correctly and I do that in the shim R.exe executable for Conda that's in the `<env>\Scripts\` folder.

I will have to make this modification to the actual R interpreter itself I think.

*Workaround*

From cmd.exe (or you could set you global Windows PATH but that's kind of horrible):
```
set PATH=<env>\Library\mingw-w64\bin;%PATH%
"C:\Program Files\RStudio\bin\rstudio.exe"
```

A batch file could also be used to do this.

Let me know if this workaround is acceptable for you in the short term. I'll leave this issue open until the correct fix is implemented.

**Comment by Diego-MX** [comment] 2016-05-04 15:20
I see something changed, but it's still not fixed.   (｡◝‿◜｡)  
When starting an R Jupyter notebook, I don't get the message anymore.  
However, I still get it when starting RStudio or loading the libraries.

I should mention that I'm not familiar with Windows' cmd (this is a work computer), so I just copy-pasted the command you suggested, replacing `<env>` with the location of my Anaconda install.

**Comment by mingwandroid** [comment] 2016-05-04 15:38
Hi @Diego-MX, I'm having trouble reproducing these problems, would you mind pasting the output from:

`conda list --export` please. Are you still having trouble launching R from the console after doing my PATH= line? If so, what R.exe are you running? Have you activated your conda environment? I think the full steps from opening a cmd.exe Window would be be helpful.

**Comment by Diego-MX** [comment] 2016-05-04 15:56
Oh. I see.  Launching RStudio doesn't take into account the `PATH=...`-line. 

I copied the line you recommended removing the end of line and substituting `<env>` for my Anaconda location.  Then I started R both directly in the terminal and through Jupyter. 

Anaconda environment is activated, and R session corresponds to it.  I can verify that with `R.home()` from within R. 

R does open, but it shows an error when loading the corresponding libraries. 

I pasted the output of `conda list --export` in [this pastebin](http://pastebin.com/mCHZLU3t).

**Comment by Diego-MX** [comment] 2016-05-04 16:06
I apologise, the command was run incorrectly. 
After removing quotes, I get a different dll message
```
Rterm.exe - Entry Point Not Found
The procedure entry point Rf_installChar could not be located in the dynamic link library R.dll. 
```

**Comment by mingwandroid** [comment] 2016-05-04 18:09
Somehow, you have a mix of old and new R packages (3.1.3 and 3.2.4). I can reproduce this if I ask conda to install `r-assertthat`. Investigations continue.

**Comment by Diego-MX** [comment] 2016-05-04 18:33
True.  I've had issues with package versions and locations since early on.  They go back to understanding how RStudio and Jupyter can coexist together and set them up with Anaconda's R engine. 

The cost of this was more than one installation, and inconsistencies with the packages.  

Still I'm confused that I cannot reinstall the packages.   

For instance I do:  `conda install -c r r-dplyr` and I get a simplified output:
```
Warning: 8 possible package resolutions:
  -r-asserthat-0.1-0.tar.bz2, r-dbi-0.3.1-r3.2.4_0.tar.bz2, ...
...
Package plan for installation in environment C:\...\Anaconda3:
The following packages will be UPDATED:
  r-asserthat: 0.1-r3.2.4_0 --> 0.1-0 
  ...
```
After `proceed`, I'm still getting the same error, as if nothing has been updated. 
Running the command again shows the same plan for installation.

**Comment by Diego-MX** [comment] 2016-05-04 18:37
If you think this situation is more messy than it is enlightning, I'm okay doing a clean install of either the R component, or the whole Anaconda.   ¯\_ȌᴥȌ_/¯

**Comment by mingwandroid** [comment] 2016-05-04 21:09
There's definitely things for me to investigate and fix here. When I do, I might ask you to go from clean again, yeah, but for now we'll see.

**Comment by Diego-MX** [comment] 2016-05-04 22:24
Sure thing.  Thanks.

**Comment by Diego-MX** [comment] 2016-05-04 23:56
Sure thing.  Thanks.

**Comment by mingwandroid** [comment] 2016-05-05 15:54
Hi @Diego-MX, if you can clean your environment and try again I'd appreciate it.

Then take care that all r-packages that Conda installs have r3.2.4 in their name, and if not please report back here. The exception to this is r-essentials.

**Comment by Diego-MX** [comment] 2016-05-05 16:47
Are there flags like `conda uninstall r-*`?  That is basically what I did, except typing one by one.  

There are bad news.  This is the sequence of events:
+ Uninstall Anaconda R and libaries with conda command as above. 
+ Verify that local R works, and so does RStudio with it. 
+ `conda install -c r r r-irkernel r-essentials`
+ Link RStudio to Anaconda's R engine. 
+ Try Anaconda R on all of: command prompt, RStudio, Jupyter Notebook. 

Results:
+ Command prompt R runs fine and I can load libraries with it. 
+ RStudio and Jupyter break at startup with error:  `libbz2-1.dll is missing`
+ Jupyter shows the error when starting the kernel, it does so 5 times. 
+ Add `<anaconda ...>\mingw-w64\bin` to `PATH` as mentioned before, and be able to start Jupyter without errors; RStudio still broken.  

About error:
This is the error that I started with before posting this.  That is to say `libbz2-1.dll` was missing before `libgcc_s_seh-1.dll` did.  The former is more viperous because it won't allow R to start, while the latter does start past the errors.  
I had been able to pass by the first one with `conda install -c r r`, but that won't help now. 

I hope this helps.

**Comment by mingwandroid** [comment] 2016-05-05 17:25
> Add <anaconda ...>\mingw-w64\bin to PATH as mentioned before, and be able to start Jupyter without errors; RStudio still broken.

When you added this to PATH, how did you then launch RStudio? From the same `cmd.exe` shell? That is a necessary step.

**Comment by Diego-MX** [comment] 2016-05-05 18:40
Right, that was misleading information as I did run it from the icon... hence expecting it to fail.
If I type `"..\..\Program Files\RStudio\bin\rstudio.exe"` on the command I do get a functioning IDE!

**Comment by mingwandroid** [comment] 2016-05-05 19:35
Ok great. Are you OK with this workaround for now?

**Comment by Diego-MX** [comment] 2016-05-05 19:47
Yes, thank you.  
It was interesting too.

**Comment by synapticarbors** [comment] 2016-05-09 15:05
I just wanted to report that I've run into the same issue and the work-around posted seems to resolve things for me as well. Looking forward to a more permanent fix.

**Comment by mingwandroid** [comment] 2016-05-09 15:54
OK, thanks for the feedback @synapticarbors.

**Comment by switch527** [comment] 2016-07-01 04:29
Has there been a more perm solution to this? The way this conda installation is set up just doesn't make much sense to me and after several installations I am having the same problem. I need it to work with R Studio, Jupyter, and Beaker notebook, but the way the installation sets everything up there is no way to get Beaker to recognize it. In every other language and every other build of R i just have to point the config file to where the binaries and executable are and bam, it works. But with this build there are library folders in envs/r/Library, but theres another at env/r/R/library. and there are binary folders everywhere. I can;t make head or tails of how this functions or how to get an IDE to connect to it. I wanted to get my company to transition to conda R to go with our installations of Anaconda2 & 3 but I can;t even get it to work on my laptop because it keeps telling me that I'm missing this or that when I try and fire it up.

**Comment by rgalbo** [comment] 2016-07-01 23:54
Having the same issue issue with both Rstudio and when attempting to launch r using a `jupyter notebook`

files supposedly missing:
- "ibbz2-1.dll"
- "liblzma-5.dll"
- "libpcre-1.dll"

**Comment by mingwandroid** [comment] 2016-07-02 11:33
You are meant activate the `conda` environment first from the command line. If you do that, then launch `jupyter` or `RStudio` then your `PATH` will have the right values.

**Comment by PCdLf** [comment] 2016-08-01 15:18
Is there another option to start RStudio? This solution does not work for me. I have installed and reinstalled RStudio. I ran the conda/ Rstudio commands from the cmd.exe but RStudio keeps telling me that "ibbz2-1.dll" is missing. I really don't want to uninstall conda.

Thanks,

**Comment by mingwandroid** [comment] 2016-08-01 16:03
I've explained what you need to do:

1. Launch cmd.exe.
2. <conda-root>\Scripts\activate.bat
3. Run the RStudio executable (or `jupyter notebook`) from this command prompt.

**Comment by mingwandroid** [comment] 2016-08-01 16:17
@switch527 I can give specific details of why it needs to be the way it is if you are interested, but actually the procedure for running conda's R on Windows, OS X and Linux is *exactly* the same, you activate the conda environment to setup the system environment.

The reason we have some extra bin folders for `R` on `conda` on Windows is because the R programming language doesn't use MSVC compilers, it uses GCC instead. On Windows, MSVC shared libraries and GCC shared libraries are incompatible with each other. This necessitates `conda` keeping them separate, because if it were to overwrite MSVC shared libraries with GCC ones, then the MSVC compiled executables that needed them would then fail to run. The same is true the other way around.

**Comment by PCdLf** [comment] 2016-08-01 18:16
What do you mean with \Scripts\activate.bat ? That is unclear to me.

**Comment by mingwandroid** [comment] 2016-08-01 20:25
@PCdLf: Each installation of `Anaconda` and `Miniconda` has a `Scripts` folder and inside that folder is a batch file called `activate.bat`. To setup the correct environment from which to run programs supplied by conda you should run that batch file. An alternative is to use the `Anaconda Prompt` from the `Start Menu`, but be aware that all this does is to launch `cmd.exe` and run `activate.bat` for you.

You can read more about activate (and deactivate) here:

http://conda.pydata.org/docs/using/envs.html#change-environments-activate-deactivate

**Comment by lsorber** [comment] 2016-08-11 13:15
@mingwandroid Your solution works well and I understand why, but it's not very convenient. Isn't there a more structural way to solve this?

**Comment by mingwandroid** [comment] 2016-08-11 14:11
I guess you could create your own `Start Menu` shortcuts based on the `Anaconda Prompt` and add more to them to also launch whatever you want in that environment.

But that doesn't sit well with the idea of easy, reproducible enviornments (`conda create -n <env>`/`conda actiave <env>`) which is one of conda's strong points, and changes that break this would be problematic.

You can launch `Jupyter` from the `Anaconda Navigator`: https://docs.continuum.io/anaconda/navigator and you should be able to create R notebooks from that. I am working on adding `RStudio` packages to conda. I hope to integrate those with `Navigator` too. Would this provide the convenience you are after?

**Comment by PCdLf** [comment] 2016-08-12 10:26
@mingwandroid Your solution didn't work for me, but I think I know why. I had 2 versions of R installed, one in Conda, and one for Rstudio. I removed the Conda R, and now Rstudio starts again. I now use Rpy2 to communicate with R.

**Comment by RodneyT272** [comment] 2016-08-28 01:12
Thank you, @mingwandroid!

I was able to make it more convenient on Win10. I simply opened the activate.bat file in a real text editor (Notepad++ for me), added at the bottom the path to the RStudio.exe file (C:\Program Files\RStudio\bin\rstudio.exe on my machine), then saved this as a new batch file in the same location. Using Explorer's right-click, I made a shortcut to this new batch file on the desktop.  Then I opened the Windows program menu, scrolled to the link for the RStudio program (not the menu folder), did a right-click, hovered over "More", and finally selected "Open file location".  This opens the location "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\RStudio" on my computer. Then I moved the shortcut from the desktop to this folder. Now I can pin it to Start, and/or do a Windows-S, type in a few characters of the batch file name, and it pops right up like any other app.  All this should work in a similar fashion for WIn8 and 7.

Adding RStudio to the Anaconda Navigator would be great!

**Comment by covelloz** [comment] 2016-09-15 08:54
@RodneyT272 
You are amazing! Your hack worked for Windows 7 too. I followed your directions exactly.

One nuance was that the shortcut wasn't immediately pinnable in Window 7. I had to right-click the shortcut > properties, then append "cmd.exe /C" to the beginning of the target field, so that all-in-all the shortcut target was
"cmd.exe /C C:\%your-R-path%\rstudio.bat"
where rstudio.bat is the copy of the activate.bat file,

However, one annoying thing was that Rstudio would launch a cmd prompt and leave it open...
You can manually close it without Rstudio closing, but I wasn't happy with that.
**THE FIX:**
Instead of just adding:
"C:%your-R-path%\rstudio.exe"
to the bottom of the activate.bat copy (rstudio.bat), I added:
cd "C:%your-R-path-location"
start rstudio.exe
exit

That did the trick. Cmd prompt opens, boots Rstudio, closes itself. 
However, if you pin the shortcut to the task bar, it will not group with the pinned icon so you'll have two Rstudio icons in your task bar when Rstudio is open. I called it a night and just pinned it to my StartMenu... hahaha, good enough.

Thanks so much!!

**Comment by NervenCid** [comment] 2016-10-29 02:44
I don't understand:

I run activate.bat and didn't worked

shall i agregate R to path?

In command prompt r works, but R studio cannot work properly

**Comment by covelloz** [comment] 2016-10-29 03:01
@NervenCid
You need to open Rstudio.exe from the same command line prompt that the conda env with R installed was activated from. Please carefully read @mingwandroid's comments above.

**Comment by NervenCid** [comment] 2016-10-29 03:43
@covelloz  Hello again:

Sorry for the english: My technical knowledge is limitated, but by understood the procedure is:

1) Install Anaconda 
2) Install RStudio
3)Open Comand prompt
4) Add PATH=C:\Users\user\AppData\Local\Continuum\Anaconda3\Library\mingw-w64\bin;%PATH%
5) In the same comand prompt enter "C:\Program Files\RStudio\bin\rstudio.exe"
6) So enjoy?

**Comment by covelloz** [comment] 2016-10-29 04:07
@NervenCid 
I wouldn't recommend step 4), it is not necessary. I (personally) don't like adding extras PATH variables.
You simply need to activate your conda environment before executing rstudio.exe

1)Install Anaconda
2)Open Command prompt
**3)Activate the environment you want R installed**
-type "activate root" to activate your default env
-otherwise, type "active some_env" if you'd rather install R into some other env you created.
4)Install R via conda: conda install -c r r-essentials
5)Install RStudio and choose Anaconda\R\ folder as the R version you want RStudio to use.
6)(in the activated command prompt): C:\Program Files\RStudio\bin\rstudio.exe
7)Enjoy

Please note. Step 3) is the most important part.

**Comment by NervenCid** [comment] 2016-10-29 04:34
Thanks for your answer: The step 3 is not clear to me yet....

So i must tip:

 >C:/activate root 

??

Shall i locate in a specific folder?

Thank you and sorry, i'm quite new in terminals

**Comment by covelloz** [comment] 2016-10-29 06:05
@NervenCid 
No, just type "activate root" (without quotes) into the command line.
You should see <root> at the beginning of the command prompt after you type this into the command line. That is your cue that the root env is activated. When you install Anaconda, it installs the "activate" command into your PATH variable for you.

For more information, please read the documents about managing environments with conda:
http://conda.pydata.org/docs/using/envs.html

**Comment by mingwandroid** [comment] 2016-10-29 09:04
`activate root` will only work if you let Anaconda add itself to the `System PATH` when you installed it. Personally I don't recommend letting it do that so in that case you need to enter `<INSTALL_LOCATION>\Scripts\activate root`. Here you do not literally enter `<INSTALL_LOCATION>` but replace that with where you installed Anaconda. For me, I'd enter `C:\Users\ray\anaconda\Scripts\activate root`

You can also run `Anaconda Prompt` from the `Start Menu`. That is the easiest way.

**Comment by 1rdsk1** [comment] 2016-11-30 17:38
Hi
I get error:"Rterm.exe - System Error The program can't start because liblzma-5.dll is missing from your computer. Try reinstalling the program to fix this problem." Then for other dll same missing error.
I do not have RStudio but just the Annaconda install on Windows 10.
I am webscraping data and so installed HTTR and XML packages from CRAN.  On install I got:
"Warning message: "package 'httr' was built under R version 3.3.2" Attaching package: 'httr'
I wonder if that is what is causing me to get these errors.  Now I cant start my R Jupyter Notebook as I have to close the terminal down sto stop the errors as the R kernel dies before trying to retart repeatedly.
I tried launching Jupyter exe from Annaconda prompt as suggested but still get this problem.
Rupert

**Comment by mingwandroid** [comment] 2016-11-30 17:58
You cannot mic packages from CRAN with packages from conda. You can get R to build CRAN packages from source though.

This is also completely unrelated to this bug report. Please open new reports for new issues.

**Closed by mingwandroid** 2016-11-30 17:58 UTC

**Comment by mingwandroid** [comment] 2017-01-11 07:11
It is likely that your user account PATH has some entries in it leading to what's simply called DLL hell or perhaps you were not activating your environment correctly. 

Either way, if you can use process hacker to show the list of modules loaded and PATH env var by Rcmd.exe when this happens it would be very helpful.
