### ISSUE TITLE
error message when creating Navigator.app link on Mac OS/X

### ISSUE THREAD

**Issue by jevad** [ContinuumIO/anaconda-issues#1079] opened 2016-09-19 22:24 UTC
Using Anaconda3-4.1.1 (installed to the user directory, not the system directory) on Mac OS/X 10.11.6, installed with the GUI installer:

Every time I "create" with conda, I get the following error when it links the packages:

Linking packages ...
ln: /Applications//Navigator.app: Permission denied#################################################              |  85%

I checked, and there is no Navigator.app in Applications, so that explains the permissions problem.  

Any reason why conda is trying to link to a non-existent application?

May I safely ignore this message?

Thanks.

**Comment by jevad** [comment] 2016-09-19 22:34
I figured out part of what it is doing (and I'll update the subject line if I get the chance).  It is trying to create a link in /Applications, and it does not have permission to do that -- it does seem to eventually create the link it needs, so I'm going to ignore it.  Y'all might want to fix the error message, but I would consider this very low priority.

**Comment by goanpeca** [comment] 2016-09-20 14:26
Hi @jevad, thanks for the heads up

---

@ilanschnell what should we do here?

**Comment by tshtatland** [comment] 2016-10-11 02:19
The cmd line installer does not make the symlink "eventually" for me (Mac OS X 10.10.5, Anaconda2-4.2.0-MacOSX-x86_64.sh).
I tried this temp fix, and it appears to work fine:
sudo ln -s /Users/shtatland/anaconda2/Anaconda-Navigator.app /Applications/Anaconda-Navigator.app

That is, I can launch the app. Anything I am missing here? 
Thanks!

**Comment by jevad** [comment] 2016-10-11 07:52
@tshtatland : The link that eventually was created (for me), was in ~/Applications, not in /Applications.

**Comment by justbennet** [comment] 2016-11-06 13:23
@ilanschnell Printing the full command line that it is trying to execute will make visible what failed.  Printing a message that says, for example,

    Attempt to create a link in /Applications failed.  To manually create this run the
    following command ($ is the prompt).
    $ sudo ln -s /Users/just/anaconda3/Anaconda-Navigator.app /Applications

would go one step further and enable most users to 'recover'.  Printing a blank line before and after will also help it stand out from the progress indicators.

It looks like the symlink gets created in ~/Applications, so you could also simply say something like

    Unable to create /Applications/Anaconda-Navigator.
    Created instead in ~/Applications.

and not even tag it as an error but tag it as a warning or informational message only.

If you can save printing to the end and wish to provide a more verbose message, something like this might be helpful.

```
. . . .
Extracting packages ...
[      COMPLETE      ]|######################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|######################################################################| 100%
Linking packages ...
[      COMPLETE      ]|######################################################################| 100%

Note:  The user installing Anaconda does not have permission to create a link in
       /Applications.
       To manually create this run the following command ($ is the prompt):
           $ sudo ln -s /Users/just/anaconda3/Anaconda-Navigator.app /Applications
       This is not required.
       You can use /Users/just/Applications/Anaconda-Navigator

[mac@just ~]$
```

Just some suggestions off the top of my head, since you asked.

**Comment by ccordoba12** [comment] 2016-11-11 14:14
I can confirm this error but there's no need to show a message to our users.

This will be fixed in the next release of Navigator.

**Comment by goanpeca** [comment] 2016-12-26 17:48
@ccordoba12 did you manage to get this done?

**Comment by goanpeca** [comment] 2016-12-27 15:44
@ccordoba12 I cant recall if this was already fixed on master

**Comment by ccordoba12** [comment] 2016-12-27 16:16
Nop, it hasn't. I'll do it today :-)

**Closed** 2017-01-10 19:35 UTC
Labels: pending:feedback, tag:navigator
