### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by seaun163** [ContinuumIO/anaconda-issues#4132] opened 2017-08-11 15:38 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Traceback (most recent call last):
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 1110, in setup
    self.setup_layout(default=False)
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 1385, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 1564, in setup_default_layouts
    widget.toggle_view(True)
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 692, in toggle_view
    self.create_new_client(give_focus=False)
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 925, in create_new_client
    self.connect_client_to_kernel(client)
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 944, in connect_client_to_kernel
    stderr_file)
  File "/Users/SEAUN/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1345, in create_kernel_manager_and_kernel_client
    stderr = codecs.open(stderr_file, 'w', encoding='utf-8')
  File "/Users/SEAUN/anaconda/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/var/folders/xr/hb6dwkt947s98ss8xyvhk7980000gn/T/spyder-SEAUN/kernel-e190cd7dd16b.stderr'
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-08-11 15:38
**See Issue #1778 for more information on how to fix this.**

---

Closing as duplicate of #1778


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-11 15:38 UTC
Labels: pkg:navigator, reso:duplicate
