### ISSUE TITLE
psutil.AccessDenied (pid = 514) 

### ISSUE THREAD

**Issue by oren1k** [ContinuumIO/anaconda-issues#8746] opened 2018-03-04 08:42 UTC
File "/Users/opk/anaconda3/lib/python3.6/site-packages/stanfordcorenlp/corenlp.py", line 79, in __init__
    if port_candidate not in [conn.laddr[1] for conn in psutil.net_connections()]:
  File "/Users/orenkobo/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 2191, in net_connections
    return _psplatform.net_connections(kind)
  File "/Users/orenkobo/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 229, in net_connections
    cons = Process(pid).connections(kind)
  File "/Users/orenkobo/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 300, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2136)

I tried the fixes suggested in #3511(conda update anaconda-navigator) and #7772 (anaconda-navigator --reset) but it doesn't work.
I'm using Mac & Python3.
Any idea?

**Comment by goanpeca** [comment] 2018-03-04 13:28
Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #1984 for more information on how to fix this.**

Or you can run on the Terminal or Anaconda prompt:

```
anaconda-navigator --remove-lock
```

**Closed by goanpeca** 2018-03-04 13:28 UTC

**Comment by oren1k** [comment] 2018-03-04 13:41
@goanpeca Please read my issue - as I wrote, I tried to update to the latest version of Navigator to include the latest fixes. Remove lock of Anaconda failed:
`naconda-navigator --remove-lock

Removing Anaconda Navigator lock...


Anaconda Navigator lock removal failed!!!

[Errno 2] No such file or directory: '/Users/opk/.anaconda/navigator/navigator.lock'`

**Comment by goanpeca** [comment] 2018-03-04 15:16
@oren1k try

```
anaconda-navigator --reset
```

**Comment by goanpeca** [comment] 2018-03-04 15:17
@oren1k manually remove this folder and try again

`/Users/opk/.anaconda/navigator/`

**Comment by oren1k** [comment] 2018-03-04 15:19
@goanpeca Thanks, I removed it manually. After removing - Should I try again to re-run the code ? Or update to the latest version of Navigator ? Or run anaconda-navigator --remove-lock?

**Comment by goanpeca** [comment] 2018-03-04 16:33
Could you provide the ooutput of 

```
conda info
```

and 

```
conda list
``` 

?

**Comment by oren1k** [comment] 2018-03-07 08:21
@goanpeca Any thoughts?

**Comment by goanpeca** [comment] 2018-03-07 13:43
@oren1k, don't know what is causing the issue :-\
