### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Petracchi1** [ContinuumIO/anaconda-issues#2476] opened 2017-06-21 21:34 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/osx-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /anaconda-fusion/osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10806fdd8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-06-21 22:11
Closing as duplicate of #1932

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-21 22:11 UTC
Labels: pkg:navigator, reso:duplicate
