### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by statistinks** [ContinuumIO/anaconda-issues#3394] opened 2017-07-21 00:49 UTC
Hello everyone - I uninstalled/installed my Anaconda few minutes ago due to R kernel keeps on dying on me. Now, I wanted to install R via Anaconda Navigator, I got the error below. Running it via command line resulted to the same error.
```
conda install -c r r-essentials
```
Need some help.

## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /anaconda-fusion/win-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000055E2470>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))",),)

```
## System information
```
python: 3.6.1
language: en_AU
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-07-21 00:50
Closing as duplicate of #1932

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-21 00:50 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by statistinks** [comment] 2017-07-21 00:55
Hi @goanpeca - thanks for the quick response. That's probably the quickest response I've ever had in my life :) Anyway, I already have the latest Anaconda Navigator (1.6.2). Any other alternative?
