### ISSUE TITLE
Anaconda 2-5-10 

### ISSUE THREAD

**Issue by ahmedshaaban1** [ContinuumIO/anaconda-issues#9421] opened 2018-05-21 22:17 UTC
### Actual Behavior

Could not launch Anaconda.. 
Main Error

could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/ahmedlasheen/Library/Application Support/binstar/config.yaml", line 1, column 1
Traceback

Traceback (most recent call last):
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._client_api = ClientAPI()
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 612, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 96, in get_server_api
    config = get_config(remote_site=site)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 229, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 223, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 223, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 203, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/binstar_client/utils/config.py", line 187, in load_config
    data = yaml_load(fd)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/binstar_client/utils/yaml.py", line 9, in yaml_load
    return safe_load(stream)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/constructor.py", line 127, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/ahmedlasheen/Library/Application Support/binstar/config.yaml", line 1, column 1
### Expected Behavior

No idea
##### Anaconda or Miniconda version:
2-5-10 
##### Operating System:
Mac high Sierra
##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment] 2018-05-21 22:18
Closing as duplicate of #8420

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8420 for more information on how to fix this issue.**

Or run

```
conda install anaconda-client=1.6.14
```

**Closed by goanpeca** 2018-05-21 22:18 UTC

**Comment by ahmedshaaban1** [comment] 2018-05-21 22:21
I got the following erro when I tried `conda install anaconda-clinet=1.6.14`

Traceback (most recent call last):
  File "./conda", line 11, in <module>
    sys.exit(main())
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 125, in main
    from ..exceptions import conda_exception_handler
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 13, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 250, in <module>
    from .collection import AttrDict, frozendict, make_immutable
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 7, in <module>
    from .compat import isiterable, iteritems, odict, text_type
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 7, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 77, in <module>
    use_errno=True)
  File "/Users/ahmedlasheen/anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/System/Library/Frameworks/CoreServices.framework/CoreServices, 6): Symbol not found: __cg_png_create_info_struct
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /opt/x11/lib//libPng.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

Thanks
