### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by frimpongk** [ContinuumIO/anaconda-issues#6770] opened 2017-10-20 02:24 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /t/<TOKEN>/conda-forge/win-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))",),)

```
## System information
```
python: 3.6.2
language: en_US
os: Windows;10;10.0.15063;AMD64;AMD64 Family 22 Model 0 Stepping 1, AuthenticAMD
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.29
```

**Comment by goanpeca** [comment] 2017-10-20 02:28
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-20 02:28 UTC
Labels: pkg:navigator, reso:duplicate
