### ISSUE TITLE
Navigator Error: Crashes at Splash Screen

### ISSUE THREAD

**Issue by SajidSalim** [ContinuumIO/anaconda-issues#6419] opened 2017-10-05 11:49 UTC
## Main Error

byte indices must be integers or slices, not str

## Traceback

```
Traceback (most recent call last):
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Users\rpa\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```

## Environment

1. **Python**: 3.6 (64-bit)
2. **Anaconda**: 4.4.0 (64-bit)
3. **OS**: Windows 10

**Comment by goanpeca** [comment] 2017-10-05 11:54
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-05 11:54 UTC
Labels: pkg:navigator, reso:duplicate
