### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by abdelrahman-abied** [ContinuumIO/anaconda-issues#4468] opened 2017-08-21 00:46 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: /home/abdo/anaconda3
#
# You don't appear to have the necessary permissions to install packages
# into the install area '/home/abdo/anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="/home/abdo/anaconda3"

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;3.13.0-128-generic;#177-Ubuntu SMP Tue Aug 8 11:40:23 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-08-21 00:46
**See Issue #1845 for more information on how to fix this.**

---

Closing as duplicate of #1845


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-21 00:46 UTC
Labels: pkg:navigator

**Comment by abdelrahman-abied** [comment] 2017-08-25 22:55
not fixed it just working from terminal only
