### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by RMSnow** [ContinuumIO/anaconda-issues#3090] opened 2017-07-12 07:01 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-07-12 07:01
Closing as duplicate of #1932

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-12 07:01 UTC
Labels: pkg:navigator, reso:duplicate
