### ISSUE TITLE
Issue installing OPENCV with Conda

### ISSUE THREAD

**Issue by umbidel** [ContinuumIO/anaconda-issues#826] opened 2016-06-14 18:12 UTC
Hi,

I have been trying to install Opencv on OS X El Capitan 10.11.3 through Anaconda, with the following particulars:

platform : osx-64
conda version : 4.0.5
conda-build version : 0+unknown
python version : 3.5.1.final.0
requests version : 2.9.1

The only version of opencv which I found to be compatible with my Anaconda is 3.1.0, which I installed using:

conda install -c menpo opencv3=3.1.0

However, when I type import cv2 in Spyder, I get the following error message:

ImportError: dlopen(/Users/umbi/Documents/anaconda/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /Users/umbi/Documents/anaconda/lib/libopencv_hdf.3.1.0.dylib
  Reason: Incompatible library version: libopencv_hdf.3.1.dylib requires version 12.0.0 or later, but libhdf5.10.dylib provides version 11.0.0

When I install opencv, I get a message on the terminal saying:

The following packages will be UPDATED:

```
conda:   4.0.5-py35_0 --> 4.0.8-py35_0  
```

I believe this is were the problem occurs, but I am not 100%.

Thank you for your help.

**Comment by muupan** [comment] 2016-06-23 08:34
Hi, I had the same problem and reached this issue by googling. I don't know the cause of the problem but `conda update hdf5` worked for me.

**Comment by YichenGong** [comment] 2016-09-30 19:28
Thanks muupan, it works!

**Comment by litingsjj** [comment] 2016-11-29 09:05
ha ha!! it works! but someone can tell me why??

**Comment by nehaljwani** [comment] 2017-05-19 05:44
This could have been fixed when the package was released with https://github.com/menpo/conda-opencv3/commit/69d21e18767a5a8e64f20f192a1476ec4dcebbb2 as it now pulls down a newer version of `hdf5`

**Comment by nehaljwani** [comment] 2017-05-19 05:45
```bash
(root) ➜  Downloads conda create -n 826 -c menpo opencv3=3.1.0
(root) ➜  Downloads source activate 826
(826) ➜  Downloads python -c 'import cv2; print(cv2.__version__)'
3.1.0
```

**Closed by nehaljwani** 2017-05-19 05:45 UTC

**Comment by nehaljwani** [comment] 2017-05-19 05:49
One can verify the version requirements:
```bash
(826) ➜  Downloads otool -L ~/m3/envs/826/lib/libhdf5.10.dylib | head -2
/Users/nwani/m3/envs/826/lib/libhdf5.10.dylib:
	@rpath/libhdf5.10.dylib (compatibility version 13.0.0, current version 13.0.0)
```

**Comment by leexue** [comment] 2017-09-16 00:29
good answers never can be late.
