### ISSUE TITLE
ipython does not provide ipython3 alias

### ISSUE THREAD

**Issue by chrish42** [ContinuumIO/anaconda-issues#173] opened 2014-09-09 19:13 UTC
I have a both a Python 2.7 Anaconda install and a Python 3.4 Anaconda environment on my path (to get both versions of Python on a RHEL 6.5 server, as recommended in another bug I filed). This works mostly well, with people being able to select the Python they want by using `python2.7` or `python3.4`, etc. However, for IPython, it doesn't work. The stock IPython (in /opt/anaconda/bin) supplies `ipython` and `ipython2`, so that's good. But the one in the Python 3.4 environment only supplies `ipython`.

It's be nice if the IPython Anaconda package also supplied an `ipython3` executable, when installed as a Python 3.

**Comment by minrk** [comment] 2015-03-07 21:58
this is a duplicate of #93

**Comment by ccordoba12** [comment] 2015-03-08 18:19
Thanks @minrk

**Closed by ccordoba12** 2015-03-08 18:19 UTC
Labels: duplicate
