### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jv4321** [ContinuumIO/anaconda-issues#3853] opened 2017-08-03 04:27 UTC
**Navigator Error**

An unexpected error occurred on Navigator start-up

**Report**

Please report this issue in the anaconda issue tracker

**Main Error**

string indices must be integers, not str
**Traceback**

Traceback (most recent call last):
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\\<user>\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**System information**

python: 2.7.13
language: en_US
os: Windows 7 ;
version: 7
platform: Win-64
conda: 4.4.0

**Comment by goanpeca** [comment] 2017-08-03 14:47
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-03 14:47 UTC
