### ISSUE TITLE
Installing anaconda to Ubuntu 16.04.2 64-bit

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1576] opened 2017-04-01 15:21 UTC
_From @JediGex on March 31, 2017 22:34_

In the middle of the anaconda installation I receive the following error:

creating default environment...
/anaconda3/bin/.openssl-libcrypto-fix: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
Error: post-link failed for: openssl-1.0.2k-1

Any thoughts on this issue?

_Copied from original issue: conda/conda#4983_

**Comment by nehaljwani** [comment] 2017-05-17 18:41
Doesn't seem to be the case with `openssl=1.0.2k=1` package in the defaults channel. 

```bash
(root) [nwani@centos6x64 ~]$ conda create -yn issue1576 openssl=1.0.2k=1
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/nwani/m2/envs/issue1576:

The following NEW packages will be INSTALLED:

    openssl: 1.0.2k-1

openssl-1.0.2k 100% |##########################################################################################################################################################| Time: 0:00:00  15.01 MB/s
#
# To activate this environment, use:
# > source activate issue1576
#
# To deactivate this environment, use:
# > source deactivate issue1576
#
```

Closing as cannot reproduce. Feel free to re-open if you are able to.

**Closed by nehaljwani** 2017-05-17 18:41 UTC
Labels: os:linux, reso:invalid, type:question
