### ISSUE TITLE
Orange - missing widgets

### ISSUE THREAD

**Issue by joesoap99** [ContinuumIO/anaconda-issues#896] opened 2016-07-11 15:21 UTC
Python 2.7 32bit , Windows 8.1, Anaconda 4.1, Orange 2.78

Orange runs and basically works OK using Navigator.

There is though an error message in the shell window:
orange-canvas-exe
"invalid/unknown: intersphinx inventory format".

Many of the widgets are missing. 
I only have 4 showing for visualisations, for example, not even scatter plots.

I tried to go to the widget Add-ons in Orange but it gives the error message : 
"must access using HTTPS and not HTTP"

**Comment by goanpeca** [comment] 2016-12-27 14:49
@ccordoba12 any idea?

**Comment by ccordoba12** [comment] 2016-12-27 14:53
This should be fixed now that we moved to use Qt5.

**Comment by goanpeca** [comment] 2016-12-27 14:54
Is Orange 2.78 qt5 compatible?

**Comment by ccordoba12** [comment] 2016-12-27 15:17
Yeah, sorry. Then I don't know the cause of this.

**Comment by goanpeca** [comment] 2016-12-27 15:23
@joesoap99 are you still experiencing the issue?

**Comment by joesoap99** [comment] 2016-12-27 17:49
Anaconda later issued updated instructions on installing Orange 3.36 on Python 3 using a separate environment which runs an older Qt version from a terminal. Orange 3.36 has many more widgets available so I have moved on to that.
The widget add-ons that fail are problems for the widget developer and I have not had the HTTPS problem using Orange 3.3.6. 
For me the original problem has been circumvented, but I do not know how folks using Python 2.7 only will fare.
Orange has later versions which are not available from Anaconda.

**Comment by goanpeca** [comment] 2016-12-27 18:13
@joesoap99 thanks for the update

For Orange, we have the latest on the repositories, but for Orange3 we do need to make an update.

I will close this issue and create a new one for the orange update request.

Cheers.

**Closed by goanpeca** 2016-12-27 18:13 UTC
Labels: pending-feedback
