### ISSUE TITLE
Spyder crashes when started on windows 7 professional- "pythonw.exe has stopped working"

### ISSUE THREAD

**Issue by akkaul** [ContinuumIO/anaconda-issues#296] opened 2015-03-30 05:51 UTC
I am a first time user of Spyder. When I start the Sypder, I get an error "pythomw.exe has stopped working" and the Spyder does not start. I am using windows 7 professional and I launch Spyder by either typing Spyder on cmd or by clicking on the spyder icon from start menu.

I have attached the screenshot of conda info output and the error I got when I tried to start Spyder. 

![conda info](https://cloud.githubusercontent.com/assets/11714503/6890750/cecce924-d676-11e4-9a83-314f61d4b3f1.png)
![pythonw](https://cloud.githubusercontent.com/assets/11714503/6890751/cecd2970-d676-11e4-8f54-9b578fadc555.png)

**Comment by ccordoba12** [comment] 2015-03-31 16:45
Please start Spyder by running

    spyder --show-console

and paste the output here to understand what's happening in your case.

**Comment by akkaul** [comment] 2015-03-31 17:27
ccordoba12 - Thanks for your attention. I tried the command suggested by you and nothing new happened. Same old issue. I am sharing the screenshot with you. 
![spyder --show-console](https://cloud.githubusercontent.com/assets/11714503/6924875/448c60ec-d7a1-11e4-9b70-a47fd425e800.png)

**Comment by akkaul** [comment] 2015-03-31 17:31
One thing that I have noticed is that sometimes I get an error - "python.exe has stopped working" (as seen in the most recent screenshot) and sometimes I get  "pythonw.exe has stopped working" (as seen in the first screenshot in this thread).

**Comment by ccordoba12** [comment] 2015-03-31 17:34
What happens when you just run

    python

in a terminal? Does it run correctly?

**Comment by akkaul** [comment] 2015-03-31 17:49
Sorry, I am a newb. I don't know what does "run correctly" means. I am again attaching a screenshot. I guess python ran fine.

![python](https://cloud.githubusercontent.com/assets/11714503/6925323/45669a5c-d7a4-11e4-842b-3e8062113899.png)

**Comment by ccordoba12** [comment] 2015-03-31 18:01
Yes, Python seems to be working fine. What if you run this other command?

    ipython qtconsole

What do you get this time?

**Comment by akkaul** [comment] 2015-03-31 18:04
I guess ipython qtconsole also worked fine.
![ipython qtconsole](https://cloud.githubusercontent.com/assets/11714503/6925636/692c3198-d7a6-11e4-81dc-6b06b3e66b35.png)

**Comment by ccordoba12** [comment] 2015-04-03 16:27
Everything seems to be working correctly except Spyder. Unfortunately, without further information I don't know how to help you solve this problem.

**Comment by groutr** [comment] 2015-04-06 20:44
Does Spyder work if you use the Anaconda launcher?
Have you tried resetting the spyder settings by running either ```spyder --reset``` or ```spyder --defaults```?

**Comment by dprice1551** [comment] 2015-05-19 22:45
I have this EXACT same problem.
Python works by itself.
Ipython works by itself
Spyder Light works by itself.

I have installed and and uninstalled the Anaconda package about 20 times with no luck. All I get is this innocuous message "python.exe has stopped working" or "pythonw.exe has stopped working".

I am running this install at work, behind a firewall, with the exact same virus protection software ON TWO DIFFERENT MACHINES. The weird part is, the desktop install works and and the laptop install does not work. I will note that the desktop is 64bit and the laptop is 32 bit, both running Win7. Previously, I have the old Spyder 1.7 / python 2.7 package working for years on my laptop, without a single problem. When I uninstalled the old version and installed the new package is when my problems started.

I'm ready to pitch python and head back to MatLab.

**Comment by ccordoba12** [comment] 2015-05-20 01:57
@dprice1551, sorry for the inconvenience. Could you try this command in terminal?

    spyder --new-instance

Maybe what's failing is our attempt to create a single Spyder instance.

**Comment by awisse** [comment] 2015-05-26 21:54
@ccordoba12 :

`spyder --new-instance` 

worked for me when Spyder wouldn't launch at all without any message after a Windows freeze/hard shutdown. Unchecked Preferences->General  "Use a single instance". Launches each time now. 

It worked in single instance before however. What happened ? Which Windows runtime does Anaconda need ?

**Comment by ccordoba12** [comment] 2015-06-04 07:23
@awisse, good to know! I'm working on a fix for Spyder 2.3.5. I'm closing this issue because it's a problem with Spyder, not with Anaconda.

Just for reference, the issue on the Spyder side is spyder-ide/spyder#2363

**Closed by ccordoba12** 2015-06-04 07:23 UTC
Labels: Windows

**Comment by Drekko** [comment] 2016-02-09 06:05
I am having the exact same issue that these guys are having
so was the fix this:
Go into spyder - Prefrences > general > Uncheck single instance

**Comment by angy50** [comment] 2016-09-27 05:50
Hi I am getting same error that python.exe has stopped working and gives two options; 1. close program 2. debug program. 
When I choose close program, it continuously keep on printing following message in ipython console of spyder:
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console. 
There is no problem with spyder working since other codes are getting executed. The problem is occurs when I use the following code:
net = caffe.Net('basic.prototxt', caffe.TEST)

**Comment by ccordoba12** [comment] 2016-09-27 07:26
@angy50, this should be fixed in Spyder 3.0. Please update to it with

    conda update spyder

**Comment by angy50** [comment] 2016-09-27 10:06
I got the problem why it was so.... it was my code problem...thank u

**Comment by jeffrimko** [comment] 2017-01-10 02:43
Just ran into similar issue and it ended up being due to not having PyQt4 installed (although PySide was installed). Can check if it is installed by running `python -c "import PyQt4"` from a console. If it is missing, go to [this website](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4), download the appropriate wheel file, then run `pip install <PATH_TO_DOWNLOADED_WHEEL_FILE>`.

**Comment by priyansh079** [comment] 2017-03-02 10:47
Hi, I am getting same error as @akkaul for spyder 3 and python 2.7.  I also tried re-installing anaconda but spyder gives same error. I also tried the above things but not able to resolve the error. Please help.

**Comment by priyansh079** [comment] 2017-03-04 10:18
Hi, I tried the command 'ipython qtconsole' but am getting the error 'python.exe has stopped working'. 

![image](https://cloud.githubusercontent.com/assets/13349731/23577959/e7e8e924-00f1-11e7-8ce0-e83c4c4bc797.png)

**Comment by Boriyilla** [comment] 2018-10-19 04:45
exact same problem here, and i tried the same things
any solution yet??

**Comment by jrafolsr** [comment] 2018-10-30 17:01
Hi, I have just experienced the same exact problem, Spyder crashing and the python.exe stop working in my new computer at work. It has Windows 7 and I installed the latest conda distribution. Following the several threads and issues I have not been able to solve it. Any suggestions? Thanks!

**Comment by Boriyilla** [comment] 2018-10-31 00:12
I read the guy who is supposed to repair this bug doesn't want to do it
because there's no money.
I switched to Pycharm. Works perfectly

**Comment by jrafolsr** [comment] 2018-10-31 07:06
Oh, such a pity! Anyway, thanks! I'll try PyCharm, sure!


Joan


Missatge de borilla <notifications@github.com> del dia dc., 31 d’oct. 2018
a les 1:12:

> I read the guy who is supposed to repair this bug doesn't want to do it
> because there's no money.
> I switched to Pycharm. Works perfectly
>

**Comment by jrafolsr** [comment] 2018-10-31 10:35
Just for your info, I've manage to run spyder by just installing a previous
distro on conda. It my work also by installing only a previous version of
spyder itself from Conda.

Good luck!

Joan


Missatge de borilla <notifications@github.com> del dia dc., 31 d’oct. 2018
a les 1:12:

> I read the guy who is supposed to repair this bug doesn't want to do it
> because there's no money.
> I switched to Pycharm. Works perfectly
>

**Comment by ccordoba12** [comment] 2018-10-31 12:11
> I read the guy who is supposed to repair this bug doesn't want to do it because there's no money.

I'm that guy and that's not true: Spyder development is doing just fine:

https://github.com/spyder-ide/spyder/graphs/contributors

**Comment by jrafolsr** [comment] 2018-10-31 12:30
I manage to solve (well.... 'solve'), by simply installing a previous version of the Anaconda distro . I don't know if by installing a previous version of just Spyder would have worked. Anyway, I'm happy again.
