### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by MaxMcR** [ContinuumIO/anaconda-issues#3291] opened 2017-07-18 10:46 UTC
An unexpected error occurred on Navigator start-up

# Main Error

string indices must be integers, not str

## Traceback

Traceback (most recent call last):
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\ProgramData\App-V\20E5B7D9-4E18-4C8E-B9E6-70717430874F\A6B7F1EC-4D64-46E1-8F24-BDFBC52D2035\Root\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

**Comment by goanpeca** [comment] 2017-07-18 16:28
Closing as duplicate of #1837

Please update to the latest version of Navigator.

Open a terminal and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-18 16:28 UTC

**Comment by MaxMcR** [comment] 2017-07-19 08:22
I have Navigator version 1.6.2 (as referenced in issue #1837) but the Navigator won’t launch. Is there some other way to solve this issue?
