### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by aardvark82** [ContinuumIO/anaconda-issues#7550] opened 2017-11-29 10:20 UTC
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Dependencies missing in current osx-64 channels: 
  - rstudio ==1.1.383 -> fonts-anaconda
  - rstudio ==1.1.383 -> icu >=58.2,<59.0a0
  - rstudio ==1.1.383 -> libcxx >=4.0.1
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> krb5 1.14.*
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> libgfortran >=3.0.1
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> libpng >=1.6.32,<1.7.0a0
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> libtiff >=4.0.8,<5.0a0
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> ncurses 6.0.*
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> readline 7.*
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-base >=3.4.2 -> tk 8.6.*
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-ddalpha -> r-sfsmisc
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-dimred >=0.1.0 -> r-drr -> r-cvst -> r-kernlab
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-gower
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-ipred -> r-prodlim -> r-lava
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-rcpproll
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-recipes >=0.0.1 -> r-tidyselect >=0.1.1
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-caret >=6.0_77 -> r-withr >=2.0.0
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-dbi >=0.7
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-glmnet >=2.0_13
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-haven >=1.1.0
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-httr >=1.3.1
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-irkernel >=0.8.9
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-modelr >=0.1.1
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-quantmod >=0.4_11
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-recommended >=3.4.2
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-rmarkdown >=1.6
  - rstudio ==1.1.383 -> r-essentials >=1.7.0 -> r-shiny >=1.0.5 -> r-httpuv >=1.3.5
  - rstudio ==1.1.383 -> r-mongolite >=0.8 -> cyrus-sasl
  - rstudio ==1.1.383 -> r-odbc >=1.1.1 -> r-blob >=1.1.0
  - rstudio ==1.1.383 -> r-profvis >=0.3.2
  - rstudio ==1.1.383 -> r-rjdbc >=0.2_5
  - rstudio ==1.1.383 -> r-rsconnect >=0.8.5

Close matches found; did you mean one of these?

    fonts-anaconda: anaconda

(and similarly for the other packages)
```
## System information
```
python: 3.6.1
language: en
os: Darwin;17.2.0;Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-11-29 12:55
**See issue #6970 for more information on how to fix this issue.**

---

Closing as duplicate of #6970

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-29 12:55 UTC
