### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by massimo1** [ContinuumIO/anaconda-issues#7926] opened 2017-12-27 11:13 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/osx-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/main/osx-64/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, \'Unexpected EOF\')",),))',),)

```
## System information
```
python: 3.6.3
language: en
os: Darwin;17.3.0;Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.30
```

**Comment by goanpeca** [comment] 2017-12-27 13:36
**See issue #1932 for more information on how to fix this issue.**

---

Closing as duplicate of #1932

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-12-27 13:36 UTC
Labels: pkg:navigator, reso:duplicate
