### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by pieralbino** [ContinuumIO/anaconda-issues#3960] opened 2017-08-06 15:32 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=592)
## Traceback
```
Traceback (most recent call last):
  File "/Users/spock/anaconda/lib/python3.5/site-packages/psutil/_psosx.py", line 272, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/spock/anaconda/lib/python3.5/site-packages/psutil/_psosx.py", line 335, in cmdline
    return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/spock/anaconda/lib/python3.5/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/spock/anaconda/lib/python3.5/site-packages/anaconda_navigator/app/start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "/Users/spock/anaconda/lib/python3.5/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "/Users/spock/anaconda/lib/python3.5/site-packages/psutil/__init__.py", line 694, in cmdline
    return self._proc.cmdline()
  File "/Users/spock/anaconda/lib/python3.5/site-packages/psutil/_psosx.py", line 285, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=592)

```
## System information
```
platform: osx-64
language: en
version: 1.6.2
pyqt: 5.6.0
qt: 5.6.2
os: Darwin;15.6.0;Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64;x86_64;i386
python: 3.5.2
conda: 4.3.22
```

**Comment by goanpeca** [comment] 2017-08-06 15:32
**See Issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-06 15:32 UTC
Labels: pkg:navigator, reso:duplicate
