### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by zhjhj2007** [ContinuumIO/anaconda-issues#5152] opened 2017-09-07 08:01 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <http://pypi.hustunique.com/osx-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPConnectionPool(host='pypi.hustunique.com', port=80): Max retries exceeded with url: /osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x110a070d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-09-07 08:03
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-07 08:03 UTC
Labels: pkg:navigator, reso:duplicate
