### ISSUE TITLE
psutil.access denied (PID = 793)

### ISSUE THREAD

**Issue by Ardeep** [ContinuumIO/anaconda-issues#8380] opened 2018-02-01 00:02 UTC
### Actual Behavior

Anaconda fails to launch on Mackbook.
I tried uninstalling and then reinstalling it. But still same thing is happening.

### Expected Behavior

Should launch normally

### Steps to Reproduce

Double click on Anaconda icon to launch it.

##### `conda info`

```
psutil.access denied (PID = 793)

Traceback (most recent call last):
File "/Applications/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 313, in catch_zombie
yield
File "/Applications/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Applications/anaconda3/lib/python3.6/site-packages/psutil/__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "/Applications/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 295, in wrapper
return fun(self, *args, **kwargs)
File "/Applications/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 377, in cmdline
return cext.proc_cmdline(self.pid)
File "/Applications/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
self.gen.throw(type, value, traceback)
File "/Applications/anaconda3/lib/python3.6/site-packages/psutil/_psosx.py", line 326, in catch_zombie
raise AccessDenied(proc.pid, proc._name)
psutil.AccessDenied: psutil.AccessDenied (pid=793)

```

##### `conda list --show-channel-urls`

```

```

**Comment by goanpeca** [comment] 2018-02-01 12:24
Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #1984 for more information on how to fix this.**

Or you can run on the Terminal or Anaconda prompt:

```
anaconda-navigator --reset
```

**Closed by goanpeca** 2018-02-01 12:24 UTC
