### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by JasonVon** [ContinuumIO/anaconda-issues#5381] opened 2017-09-12 03:20 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2913, in run_spyder
    main.setup()
  File "/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 873, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "/anaconda/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 60, in <module>
    from spyder.widgets.ipythonconsole import ClientWidget
  File "/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/__init__.py", line 12, in <module>
    from .debugging import DebuggingWidget
  File "/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/debugging.py", line 16, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
  File "/anaconda/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 14, in <module>
    from .jupyter_widget import JupyterWidget
  File "/anaconda/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 19, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named backports.shutil_get_terminal_size

```
## System information
```
platform: osx-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en
python: 2.7.13
os: Darwin;16.7.0;Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64;x86_64;i386
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-09-12 03:22
**See Issue #1778 for more information on how to fix this.**

---

Closing as duplicate of #1778


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-12 03:22 UTC
Labels: pkg:navigator, reso:duplicate
