### ISSUE TITLE
Cannot import RSA from Crpyto module in Python 3.5

### ISSUE THREAD

**Issue by VeenitShah** [ContinuumIO/anaconda-issues#758] opened 2016-04-18 16:46 UTC
I am unable to execute the following line -

from Crypto.PublicKey import RSA
I get ImportError: No module named 'Crypto'

However, I can do import Crypto with no problem.

I am using Python 3.5 with pycrpyto 2.6.1 already setup.
Python 3.5.1 | Anaconda 4.0.0 (x86_64) on Mac

**Comment by nehaljwani** [comment] 2017-05-21 16:42
Closing, as unable to reproduce. Feel free to re-open if the problem persists.

```bash
(root) cypher:~ $ conda create -yn 758 python=3.5.1=0 pycrypto=2.6.1=py35_0 
(root) cypher:~ $ source activate 758
(758) cypher:~ $ python -c 'from Crypto.PublicKey import RSA; print(RSA.__file__)'
/Users/nwani/m3/envs/758/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py
```

**Closed by nehaljwani** 2017-05-21 16:42 UTC
Labels: os:mac
