### ISSUE TITLE
anaconda not opening

### ISSUE THREAD

**Issue by nikhil-sudan** [ContinuumIO/anaconda-issues#4281] opened 2017-08-15 14:14 UTC
<html>
    <head>
      <title>Navigator Error</title>
    </head>
    <body>
      <div>
        <h1>Navigator Error</h1>
        <p>An unexpected error occurred on Navigator start-up</p>
        <h2>Report</h2>
        <p>Please report this issue in the anaconda
          <a href="https://github.com/continuumio/anaconda-issues">
            issue tracker
          </a>
        </p>
      </div>
      <div>
        <h2>Main Error</h2>
        <p><pre>byte indices must be integers or slices, not str</pre></p>
        <h2>Traceback</h2>
        <p><pre>Traceback (most recent call last):
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 111, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 254, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\Nikhil Sudan\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 124, in start_app
    "There is an instance of "
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 450, in __init__
    type_=self.INFORMATION_BOX,
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
    self.tracker = GATracker()
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 284, in GATracker
    GA_TRACKER = _GATracker()
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 95, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\Nikhil Sudan\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
</pre></p>
      </div>
    </body>
    </html>

**Comment by goanpeca** [comment] 2017-08-15 14:14
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-15 14:14 UTC
Labels: pkg:navigator, reso:duplicate
