### ISSUE TITLE
Broken Microsoft R packages (MRO)

### ISSUE THREAD

**Issue by nicolaasuni** [ContinuumIO/anaconda-issues#8728] opened 2018-03-02 09:55 UTC
After the introduction of the new Microsoft R packages as announced at: https://www.anaconda.com/blog/company-blog/introducing-microsoft-r-open-as-default-r-for-anaconda-distribution/ I am unable to build several conda environments.

Apparently the new mro packages are forcing the downgrade of numerous packages, including r-base from 3.4.3 to 3.2.2. To me this is a regression as I have to modify my code in order to keep it working and exclude MRO in favor of R.

One particular issue is with the new bash scripts in .../etc/conda/activate.d/ directory.
These scripts are not "safe mode" compatible and they break if the "activate" command is issued inside a bash script with the -e and -u options.

An example error is:
/etc/conda/activate.d/activate-gfortran_linux-64.sh: line 86: CONDA_BUILD: unbound variable
These scripts should check if the variable is set before trying to use it.

**Comment by mingwandroid** [comment] 2018-03-02 17:13
> Apparently the new mro packages are forcing the downgrade of numerous packages, including r-base from 3.4.3 to 3.2.2. To me this is a regression as I have to modify my code in order to keep it working and exclude MRO in favor of R.

Please give the reproduction steps for this. You should note that R 3.4.3 was released at the same time as MRO 3.4.3 so the fact that you had R 3.4.3 indicates that it is possible to install it in the presence of released MRO 3.4.3 packages.

> One particular issue is with the new bash scripts in .../etc/conda/activate.d/ directory.
These scripts are not "safe mode" compatible and they break if the "activate" command is issued inside a bash script with the -e and -u options.

You need to disable these settings to run activate, we do not and have never required activate scripts to be "safe mode" compatible.

**Comment by nicolaasuni** [comment] 2018-03-05 08:59
For now I have forced the installation of R packages by setting:
`- _r-mutex * anacondar*`
in meta.yaml configuration file.

I believe this is a bug because the introduction of new packages shouldn't break current settings.
Non-backward compatible packages should have different name or major version.

> You need to disable these settings to run activate, we do not and have never required activate scripts to be "safe mode" compatible.

Without safe (or strict) mode is not possible to tell if undefined variables are like this by design or a bug.
Breaking bash under strict mode is a sign of poor code quality:
http://redsymbol.net/articles/unofficial-bash-strict-mode/

**Comment by mingwandroid** [comment] 2018-03-05 10:08
@nicolaasuni, I cannot reproduce your problem, from earlier:

> Please give the reproduction steps for this

> Breaking bash under strict mode is a sign of poor code quality:
> http://redsymbol.net/articles/unofficial-bash-strict-mode/

Ouch, that burns a little. I will try to adapt them to work with your preferred set of options. Do you think:

```
if [ -n "${CONDA_BUILD+set}" ]; then
```

.. will work on every bash version (and shell pretending to be bash) we're likely to encounter (this is a limiting factor here)?

Otherwise I'll I could query the -u flag and reset it at the end but I'm not sure how portable that is.

**Comment by mingwandroid** [comment] 2018-03-05 10:11
Also, was there any reason that you just deleted the issues template instead of providing the details asked for? Please give those.



### Actual Behavior



### Expected Behavior



### Steps to Reproduce




##### Anaconda or Miniconda version:

##### Operating System:

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

**Comment by nicolaasuni** [comment] 2018-03-12 09:58
**Actual Behavior**

While executing conda commands I get errors like:

`[...]/etc/conda/deactivate.d/deactivate-gfortran_linux-64.sh: line 86: CONDA_BUILD: unbound variable`
`[...]etc/conda/deactivate.d/deactivate-binutils_linux-64.sh: line 67: CONDA_BACKUP_HOST: unbound variable`

**Expected Behavior**

Shell scripts should not complain about unbound variables in strict mode checking.
The proposed approach will work but it should be repeated for each unbound variable.

`if [ -n "${CONDA_BUILD:+x}" ]; then`

**Steps to Reproduce**

Execute a conda build via bash script with `set -u` option to highlight unbound variables.
This shows when using the R packages in particular.

**Anaconda or Miniconda version:**

https://repo.continuum.io/miniconda/Miniconda3-4.4.10-Linux-x86_64.sh
conda 4.4.10-py36_0 upgraded to 4.4.11-py36_0 

**Operating System:**

* Distributor ID:	Ubuntu
* Description:	Ubuntu 16.04.4 LTS
* Release:	16.04
* Codename:	xenial
* Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**conda info**

`
     active environment : None
       user config file : /home/XXX/.condarc
 populated config files : 
          conda version : 4.4.11
    conda-build version : 3.7.1
         python version : 3.6.4.final.0
       base environment : /home/XXX/env-xxx  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/XXX/env-xxx/pkgs
                          /home/nicola/.conda/pkgs
       envs directories : /home/XXX/env-xxx/envs
                          /home/XXX/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-36-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
`

**conda list --show-channel-urls**
`
# packages in environment at /home/XXX/env-xxx:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1    http://repo.continuum.io/pkgs/r
asn1crypto                0.24.0                   py36_0    defaults
beautifulsoup4            4.6.0            py36h49b8c8c_1    http://repo.continuum.io/pkgs/main
binutils_impl_linux-64    2.28.1               had2808c_3    http://repo.continuum.io/pkgs/main
binutils_linux-64         7.2.0                        25    http://repo.continuum.io/pkgs/main
bleach                    2.1.3                    py36_0    http://repo.continuum.io/pkgs/main
bwidget                   1.9.11                        0    http://repo.continuum.io/pkgs/main
bzip2                     1.0.6                h9a117a8_4    http://repo.continuum.io/pkgs/main
ca-certificates           2017.08.26           h1d4fec5_0    http://repo.continuum.io/pkgs/main
cairo                     1.14.12              h77bcde2_0    http://repo.continuum.io/pkgs/main
certifi                   2018.1.18                py36_0    http://repo.continuum.io/pkgs/main
cffi                      1.11.4           py36h9745a5d_0    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
click                     6.7              py36h5253387_0    http://repo.continuum.io/pkgs/main
conda                     4.4.11                   py36_0    http://repo.continuum.io/pkgs/main
conda-build               3.7.1                    py36_0    http://repo.continuum.io/pkgs/main
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h98955d8_0    http://repo.continuum.io/pkgs/main
cookies                   2.2.1                    py36_0    http://repo.continuum.io/pkgs/free
cryptography              2.1.4            py36hd09be54_0    defaults
curl                      7.58.0               h84994c4_0    http://repo.continuum.io/pkgs/main
decorator                 4.2.1                    py36_0    http://repo.continuum.io/pkgs/main
elasticsearch             6.0.0            py36h03877a2_0    http://repo.continuum.io/pkgs/main
entrypoints               0.2.3            py36h1aec115_2    http://repo.continuum.io/pkgs/main
filelock                  3.0.4                    py36_0    http://repo.continuum.io/pkgs/main
flask                     0.12.2           py36hb24657c_0    http://repo.continuum.io/pkgs/main
fontconfig                2.12.6               h49f89f6_0    http://repo.continuum.io/pkgs/main
freetype                  2.8                  hab7d2ae_1    http://repo.continuum.io/pkgs/main
gcc_impl_linux-64         7.2.0                habb00fd_3    http://repo.continuum.io/pkgs/main
gcc_linux-64              7.2.0                        25    http://repo.continuum.io/pkgs/main
gfortran_impl_linux-64    7.2.0                hdf63c60_3    http://repo.continuum.io/pkgs/main
gfortran_linux-64         7.2.0                        25    http://repo.continuum.io/pkgs/main
glib                      2.53.6               h5d9569c_2    http://repo.continuum.io/pkgs/main
glob2                     0.6              py36he249c77_0    http://repo.continuum.io/pkgs/main
gmp                       6.1.2                h6c8ec71_1    http://repo.continuum.io/pkgs/main
graphite2                 1.3.10               hf63cedd_1    http://repo.continuum.io/pkgs/main
gsl                       2.2.1                h0c605f7_3    http://repo.continuum.io/pkgs/main
gxx_impl_linux-64         7.2.0                hdf63c60_3    http://repo.continuum.io/pkgs/main
gxx_linux-64              7.2.0                        25    http://repo.continuum.io/pkgs/main
harfbuzz                  1.7.4                hc5b324e_0    http://repo.continuum.io/pkgs/main
html5lib                  1.0.1            py36h2f9c1c0_0    http://repo.continuum.io/pkgs/main
icu                       58.2                 h9c2bf20_1    http://repo.continuum.io/pkgs/main
idna                      2.6              py36h82fb2a8_1    defaults
intel-openmp              2018.0.0             hc7b2577_8    http://repo.continuum.io/pkgs/main
ipykernel                 4.8.2                    py36_0    http://repo.continuum.io/pkgs/main
ipython                   6.2.1            py36h88c514a_1    http://repo.continuum.io/pkgs/main
ipython_genutils          0.2.0            py36hb52b0d5_0    http://repo.continuum.io/pkgs/main
itsdangerous              0.24             py36h93cc618_1    http://repo.continuum.io/pkgs/main
jedi                      0.11.1                   py36_0    http://repo.continuum.io/pkgs/main
jinja2                    2.10             py36ha16c418_0    http://repo.continuum.io/pkgs/main
jpeg                      9b                   h024ee3a_2    http://repo.continuum.io/pkgs/main
jsonschema                2.6.0            py36h006f8b5_0    http://repo.continuum.io/pkgs/main
jupyter_client            5.2.2                    py36_0    http://repo.continuum.io/pkgs/main
jupyter_core              4.4.0            py36h7c827e3_0    http://repo.continuum.io/pkgs/main
krb5                      1.14.2               hcdc1b81_6    http://repo.continuum.io/pkgs/main
libcurl                   7.58.0               h1ad7b7a_0    http://repo.continuum.io/pkgs/main
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc                    7.2.0                h69d50b8_2    http://repo.continuum.io/pkgs/main
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran-ng            7.2.0                hdf63c60_3    http://repo.continuum.io/pkgs/main
libopenblas               0.2.20               h9ac9557_4    http://repo.continuum.io/pkgs/main
libpng                    1.6.34               hb9fc6fc_0    http://repo.continuum.io/pkgs/main
libsodium                 1.0.15               hf101ebd_0    http://repo.continuum.io/pkgs/main
libssh2                   1.8.0                h9cfc8f7_4    http://repo.continuum.io/pkgs/main
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.9                h28f6b97_0    http://repo.continuum.io/pkgs/main
libxcb                    1.12                 hcd93eb1_4    http://repo.continuum.io/pkgs/main
libxml2                   2.9.7                h26e45fe_0    http://repo.continuum.io/pkgs/main
markupsafe                1.0              py36hd9260cd_1    http://repo.continuum.io/pkgs/main
mistune                   0.8.3                    py36_0    http://repo.continuum.io/pkgs/main
mkl                       2018.0.1             h19d6760_4    http://repo.continuum.io/pkgs/main
nbconvert                 5.3.1            py36hb41ffb7_0    http://repo.continuum.io/pkgs/main
nbformat                  4.4.0            py36h31c9010_0    http://repo.continuum.io/pkgs/main
ncurses                   6.0                  h9df7e31_2    defaults
notebook                  5.4.0                    py36_0    http://repo.continuum.io/pkgs/main
numpy                     1.14.1           py36ha266831_2    http://repo.continuum.io/pkgs/main
openssl                   1.0.2n               hb7f436b_0    http://repo.continuum.io/pkgs/main
pandas                    0.22.0           py36hf484d3e_0    http://repo.continuum.io/pkgs/main
pandoc                    1.19.2.1             hea2e7c5_1    http://repo.continuum.io/pkgs/main
pandocfilters             1.4.2            py36ha6701b7_1    http://repo.continuum.io/pkgs/main
pango                     1.41.0               hd475d92_0    http://repo.continuum.io/pkgs/main
parso                     0.1.1            py36h35f843b_0    http://repo.continuum.io/pkgs/main
patchelf                  0.9                  hf79760b_2    http://repo.continuum.io/pkgs/main
pcre                      8.41                 hc27e229_1    http://repo.continuum.io/pkgs/main
pexpect                   4.4.0                    py36_0    http://repo.continuum.io/pkgs/main
pickleshare               0.7.4            py36h63277f8_0    http://repo.continuum.io/pkgs/main
pip                       9.0.1            py36h6c6f9ce_4    defaults
pixman                    0.34.0               hceecf20_3    http://repo.continuum.io/pkgs/main
pkginfo                   1.4.1            py36h215d178_1    http://repo.continuum.io/pkgs/main
prompt_toolkit            1.0.15           py36h17d85b1_0    http://repo.continuum.io/pkgs/main
psutil                    5.4.3            py36h14c3975_0    http://repo.continuum.io/pkgs/main
ptyprocess                0.5.2            py36h69acd42_0    http://repo.continuum.io/pkgs/main
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pygments                  2.2.0            py36h0d3125c_0    http://repo.continuum.io/pkgs/main
pyopenssl                 17.5.0           py36h20ba746_0    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
python                    3.6.4                hc3d631a_1    defaults
python-dateutil           2.6.1            py36h88d3b88_1    http://repo.continuum.io/pkgs/main
python-rapidjson          0.4.3            py36h6bb024c_0    http://repo.continuum.io/pkgs/main
pytz                      2018.3                   py36_0    http://repo.continuum.io/pkgs/main
pyyaml                    3.12             py36hafb9ca4_1    http://repo.continuum.io/pkgs/main
pyzmq                     17.0.0           py36h14c3975_0    http://repo.continuum.io/pkgs/main
r                         3.4.3                    r343_0    http://repo.continuum.io/pkgs/r
r-assertthat              0.2.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-backports               1.1.2            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-base                    3.4.3                h290ecf8_0    http://repo.continuum.io/pkgs/r
r-base64enc               0.1_3            r343h086d26f_4    http://repo.continuum.io/pkgs/r
r-bh                      1.65.0_1         r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-bindr                   0.1              r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-bindrcpp                0.2              r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-bitops                  1.0_6            r343h086d26f_4    http://repo.continuum.io/pkgs/r
r-boot                    1.3_20           r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-broom                   0.4.3            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-callr                   1.0.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-caret                   6.0_78           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-cellranger              1.1.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-class                   7.3_14           r343h086d26f_4    http://repo.continuum.io/pkgs/r
r-cli                     1.0.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-clipr                   0.4.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-cluster                 2.0.6            r343h4829c52_0    http://repo.continuum.io/pkgs/r
r-codetools               0.2_15           r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-colorspace              1.3_2            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-crayon                  1.3.4            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-curl                    3.1              r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-cvst                    0.2_1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-data.table              1.10.4_3         r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-dbi                     0.7              r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-dbplyr                  1.1.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-ddalpha                 1.3.1            r343h44b0c2a_0    http://repo.continuum.io/pkgs/r
r-deoptimr                1.0_8            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-devtools                1.13.4           r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-dichromat               2.0_0            r343h889e2dd_4    http://repo.continuum.io/pkgs/r
r-digest                  0.6.13           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-dimred                  0.1.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-dplyr                   0.7.4            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-drr                     0.0.2            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-essentials              3.4.3                    r343_0    http://repo.continuum.io/pkgs/r
r-evaluate                0.10.1           r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-feather                 0.3.1            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-forcats                 0.2.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-foreach                 1.4.4            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-foreign                 0.8_69           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-formatr                 1.5              r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-ggplot2                 2.2.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-git2r                   0.20.0           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-glmnet                  2.0_13           r343h4829c52_0    http://repo.continuum.io/pkgs/r
r-glue                    1.2.0            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-gower                   0.1.2            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-gtable                  0.2.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-haven                   1.1.0            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-hexbin                  1.27.1           r343h4829c52_4    http://repo.continuum.io/pkgs/r
r-highr                   0.6              r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-hms                     0.4.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-htmltools               0.3.6            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-htmlwidgets             0.9              r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-httpuv                  1.3.5            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-httr                    1.3.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-igraph                  1.1.2            r343h44b0c2a_0    http://repo.continuum.io/pkgs/r
r-ipred                   0.9_6            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-irdisplay               0.4.4            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-irkernel                0.8.11                   r343_0    http://repo.continuum.io/pkgs/r
r-irlba                   2.3.1            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-iterators               1.0.9            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-jsonlite                1.5              r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-kernlab                 0.9_25           r343h44b0c2a_0    http://repo.continuum.io/pkgs/r
r-kernsmooth              2.23_15          r343h4829c52_4    http://repo.continuum.io/pkgs/r
r-knitr                   1.18             r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-labeling                0.3              r343h889e2dd_4    http://repo.continuum.io/pkgs/r
r-lattice                 0.20_35          r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-lava                    1.5.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-lazyeval                0.2.1            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-lintr                   1.0.2            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-lubridate               1.7.1            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-magrittr                1.5              r343h889e2dd_4    http://repo.continuum.io/pkgs/r
r-maps                    3.2.0            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-markdown                0.8              r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-mass                    7.3_48           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-matrix                  1.2_12           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-memoise                 1.1.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-mgcv                    1.8_22           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-mime                    0.5              r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-mnormt                  1.5_5            r343h4829c52_0    http://repo.continuum.io/pkgs/r
r-modelmetrics            1.1.0            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-modelr                  0.1.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-munsell                 0.4.3            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-nlme                    3.1_131          r343h4829c52_0    http://repo.continuum.io/pkgs/r
r-nnet                    7.3_12           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-numderiv                2016.8_1         r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-openssl                 0.9.9            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-pbdzmq                  0.3_0            r343hf484d3e_0    http://repo.continuum.io/pkgs/r
r-pillar                  1.0.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-pkgconfig               2.0.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-plogr                   0.1_1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-plyr                    1.8.4            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-praise                  1.0.0            r343h889e2dd_4    http://repo.continuum.io/pkgs/r
r-prodlim                 1.6.1            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-psych                   1.7.8            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-purrr                   0.2.4            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-quantmod                0.4_12           r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-r6                      2.2.2            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-randomforest            4.6_12           r343h4829c52_4    http://repo.continuum.io/pkgs/r
r-rbokeh                  0.6.3                    r343_0    http://repo.continuum.io/pkgs/r
r-rcolorbrewer            1.1_2            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-rcpp                    0.12.14          r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-rcpproll                0.2.2            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-rcurl                   1.95_4.9         r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-readr                   1.1.1            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-readxl                  1.0.0            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-recipes                 0.1.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-recommended             3.4.3                    r343_0    http://repo.continuum.io/pkgs/r
r-rematch                 1.0.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-repr                    0.12.0           r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-reprex                  0.1.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-reshape2                1.4.3            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-rex                     1.1.2            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-rjson                   0.2.15           r343h599a50d_4    http://repo.continuum.io/pkgs/r
r-rlang                   0.1.6            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-rmarkdown               1.8              r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-robustbase              0.92_8           r343h4829c52_0    http://repo.continuum.io/pkgs/r
r-rpart                   4.1_11           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-rprojroot               1.3_1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-rstudioapi              0.7              r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-rvest                   0.3.2            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-scales                  0.5.0            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-selectr                 0.3_1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-sfsmisc                 1.1_1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-shiny                   1.0.5            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-sourcetools             0.1.6            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-spatial                 7.3_11           r343h086d26f_4    http://repo.continuum.io/pkgs/r
r-stringdist              0.9.4.6          r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-stringi                 1.1.6            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-stringr                 1.2.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-survival                2.41_3           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-testthat                2.0.0            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-tibble                  1.4.1            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-tidyr                   0.7.2            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-tidyselect              0.2.3            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-tidyverse               1.2.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-timedate                3042.101         r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-ttr                     0.23_2           r343h4829c52_0    http://repo.continuum.io/pkgs/r
r-utf8                    1.1.2            r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-uuid                    0.1_2            r343h086d26f_4    http://repo.continuum.io/pkgs/r
r-viridislite             0.2.0            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-whisker                 0.3_2            r343h889e2dd_4    http://repo.continuum.io/pkgs/r
r-withr                   2.1.1            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-xml2                    1.1.1            r343h599a50d_0    http://repo.continuum.io/pkgs/r
r-xtable                  1.8_2            r343h889e2dd_0    http://repo.continuum.io/pkgs/r
r-xts                     0.10_1           r343h4829c52_0    http://repo.continuum.io/pkgs/r
r-yaml                    2.1.16           r343h086d26f_0    http://repo.continuum.io/pkgs/r
r-zoo                     1.8_0            r343h086d26f_0    http://repo.continuum.io/pkgs/r
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
responses                 0.8.1            py36hcf147cc_0    http://repo.continuum.io/pkgs/main
ruamel_yaml               0.15.35          py36h14c3975_1    defaults
send2trash                1.5.0                    py36_0    http://repo.continuum.io/pkgs/main
setuptools                38.4.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    http://repo.continuum.io/pkgs/main
six                       1.11.0           py36h372c433_1    defaults
sqlite                    3.22.0               h1bed415_0    defaults
terminado                 0.8.1                    py36_1    http://repo.continuum.io/pkgs/main
testpath                  0.3.1            py36h8cadb63_0    http://repo.continuum.io/pkgs/main
tk                        8.6.7                hc745277_3    defaults
tktable                   2.10                 h14c3975_0    http://repo.continuum.io/pkgs/main
tornado                   5.0                      py36_0    http://repo.continuum.io/pkgs/main
traitlets                 4.3.2            py36h674d592_0    http://repo.continuum.io/pkgs/main
urllib3                   1.22             py36hbe7ace6_0    defaults
wcwidth                   0.1.7            py36hdf4376a_0    http://repo.continuum.io/pkgs/main
webencodings              0.5.1            py36h800622e_1    http://repo.continuum.io/pkgs/main
werkzeug                  0.14.1                   py36_0    http://repo.continuum.io/pkgs/main
wheel                     0.30.0           py36hfd4bba0_1    defaults
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.3                h439df22_3    http://repo.continuum.io/pkgs/main
zlib                      1.2.11               ha838bed_2    defaults
`

**Comment by nicolaasuni** [comment] 2018-03-12 14:28
Today, after disabling the "-u" bash option the scripts are still failing.
I believe that it has something to do with binutils.
This package wasn't present in the last successful build.

`
+++ env
++++ _get_sourced_filename
++++ '[' -n /home/XXX/env-xxx/etc/conda/deactivate.d/deactivate-gfortran_linux-64.sh ']'
++++ basename /home/XXX/env-xxx/etc/conda/deactivate.d/deactivate-gfortran_linux-64.sh
+++ echo 'INFO: deactivate-gfortran_linux-64.sh made the following environmental changes:'
INFO: deactivate-gfortran_linux-64.sh made the following environmental changes:
+++ diff -U 0 -rN /tmp/old-env-22007.txt /tmp/new-env-22007.txt
+++ tail -n +4
+++ grep -v CONDA_BACKUP_
+++ sort
+++ grep '^-.*\|^+.*'
+HOST=x86_64-conda_cos6-linux-gnu

me@XXX:$ echo $?
1
`

**Comment by nicolaasuni** [comment] 2018-03-12 14:38
In any case, it looks that all these issues are related to poor bash coding.

**Comment by mingwandroid** [comment] 2018-03-12 14:46
> Breaking bash under strict mode is a sign of poor code quality:
> related to poor bash coding

I will fix these bugs but I am closing this issue.

If you wish to have productive discourse and assistance with other issues I would recommend you stop being rude. This applies on github and also in general.

**Closed by mingwandroid** 2018-03-12 14:46 UTC

**Comment by nicolaasuni** [comment] 2018-03-12 14:48
Apparently disabling the "e" bash option allows the script to complete.
So, conda now requires:
```
set +u +e
```
This should be fixed.

**Comment by nicolaasuni** [comment] 2018-03-12 17:42
The title is not reflecting anymore the issue discussed here.
I am opening another ticket to track the bash issue I am experiencing:
https://github.com/ContinuumIO/anaconda-issues/issues/8838
