### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sastry45** [ContinuumIO/anaconda-issues#9416] opened 2018-05-21 15:22 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 20:51:48.163 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 20:51:49.533 NotebookApp] Serving notebooks from local directory: /home/vinayp
[I 20:51:49.534 NotebookApp] 0 active kernels 
[I 20:51:49.534 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=2395f51158997f584fe02e5932a135d290add599a8c89045
[I 20:51:49.535 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:51:49.538 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=2395f51158997f584fe02e5932a135d290add599a8c89045
[I 20:51:49.893 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[5395:5414:0521/205149.945022:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.

```
## System information
```
python: 3.6.1
language: en_IN
os: Linux;4.4.0-124-generic;#148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.24
```

**Comment by goanpeca** [comment] 2018-05-21 17:31
Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #2098 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-05-21 17:31 UTC
Labels: pkg:navigator, reso:duplicate
