### ISSUE TITLE
Unable to import curses module on Linux

### ISSUE THREAD

**Issue by buzmakov** [ContinuumIO/anaconda-issues#359] opened 2015-06-19 09:54 UTC
Hi,
on Ubuntu 12.04 x64 I'm not able to use curses module due next error:

```
➜  ~  python -c 'import curses'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/makov/opt/anaconda/lib/python2.7/curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /home/makov/opt/anaconda/lib/python2.7/lib-dynload/../.././libtinfo.so.5)
```

My python version 2.7.10

```
➜  ~  conda list python  
# packages in environment at /home/makov/opt/anaconda:
#
biopython                 1.63                 np18py27_0  
dynd-python               0.6.5                np19py27_0  
ipython                   3.1.0                    py27_1  
ipython-notebook          3.1.0                    py27_1  
ipython-qtconsole         3.1.0                    py27_0  
python                    2.7.10                        0  
python-dateutil           2.4.2                    py27_0  
python-modargs            1.7                       <pip>
```

**Comment by nehaljwani** [comment] 2017-05-21 09:30
Closing, as unable to reproduce the error.
```bash
(359) root@e2eb78ec3d24:~$ uname -m
x86_64
(359) root@e2eb78ec3d24:~$ cat /etc/issue
Ubuntu 12.04.5 LTS \n \l

(359) root@e2eb78ec3d24:~$ python -c 'import curses'

(359) root@e2eb78ec3d24:~$ readelf --version-info /conda/envs/359/lib/python2.7/lib-dynload/_curses.so | grep -Po '(?<=GLIBC_)([\d.]*)' | sort -Vr | head -1
2.2.5

(359) root@e2eb78ec3d24:~$ readelf --version-info /lib/x86_64-linux-gnu/libc.so.6 | grep -Po '(?<=GLIBC_)([\d.]*)' | sort -Vr | head -1
2.15

(359) root@e2eb78ec3d24:~$ conda list python
# packages in environment at /conda/envs/359:
#
python                    2.7.10                        0
```

**Closed by nehaljwani** 2017-05-21 09:30 UTC
