### ISSUE TITLE
Anaconda startup error

### ISSUE THREAD

**Issue by TomNett** [ContinuumIO/anaconda-issues#6454] opened 2017-10-06 17:21 UTC
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

byte indices must be integers or slices, not str
Traceback

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-10-07 02:44
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-07 02:44 UTC

**Comment by TomNett** [comment] 2017-10-08 11:26
Hi, when i run the command prompt i get this error:
'"C:\Anaconda3\Scripts\\..\Scripts\conda.exe"' is not recognized as an internal or external command,
operable program or batch file.

any idea?

**Comment by goanpeca** [comment] 2017-10-08 16:32
@TomNett did you use an all users install or a current user install?

**Comment by TomNett** [comment] 2017-10-08 16:50
I used current user install. But nevermind, I uninstalled anaconda completely and installed again and it works now. I had just lost all my created environments :-( Dont know what was wrong...
