### ISSUE TITLE
Anaconda Navigator not showing items on Home page

### ISSUE THREAD

**Issue by memememeda** [ContinuumIO/anaconda-issues#11103] opened 2019-07-10 03:35 UTC
Anaconda Navigator shows only VSCode on Home page.
Anaconda Prompt disappeared in  Start Menu
**This issue happened after** `conda clean`

I also have tried the means in #9025 : 
conda update conda
conda update anaconda-navigator
conda update navigator-updater

`conda info `
    active environment : None
       user config file : C:\Users\clement\.condarc
 populated config files : C:\Users\clement\.condarc
          conda version : 4.7.5
    conda-build version : 3.18.5
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\learning\Anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/mai
n/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/mai
n/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\learning\Anaconda3\pkgs
                          C:\Users\clement\.conda\pkgs
                          C:\Users\clement\AppData\Local\conda\conda\pkgs
       envs directories : C:\learning\Anaconda3\envs
                          C:\Users\clement\.conda\envs
                          C:\Users\clement\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Windows/7 Wi
ndows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False

![20190710112744](https://user-images.githubusercontent.com/29892439/60938398-67e98800-a306-11e9-8e63-cb291c46a5c0.png)

![TIM图片20190710113247](https://user-images.githubusercontent.com/29892439/60938432-8b143780-a306-11e9-9d0b-ed2c9135022a.png)

**Comment by memememeda** [comment] 2019-07-10 05:43
i have fixed the prompt disappear problem by conda install console_shortcut , in #8794

**Comment by sushantMoon** [comment] 2019-07-10 07:28
I am suffering from the same along with one additional issue, I have updated all the conda packages, still no success.

This started after `conda clean -i`

`conda info`
```sh
     active environment : base
    active env location : C:\Users\DELL\Anaconda3
            shell level : 1
       user config file : C:\Users\DELL\.condarc
 populated config files : C:\Users\DELL\.condarc
          conda version : 4.7.5
    conda-build version : 3.18.5
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\DELL\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/anaconda/win-64
                          https://conda.anaconda.org/anaconda/noarch
          package cache : C:\Users\DELL\Anaconda3\pkgs
                          C:\Users\DELL\.conda\pkgs
                          C:\Users\DELL\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\DELL\Anaconda3\envs
                          C:\Users\DELL\.conda\envs
                          C:\Users\DELL\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

![image](https://user-images.githubusercontent.com/4204403/60949043-fc0d1c80-a311-11e9-83cb-77de56b12f07.png)


Another issue is, under the all available packages on the Environment Tab, I cannot see any package not already installed by me previously. Update index / Update Channel does nothing.

Previously it had all the available channels that I can install, update, etc

![image](https://user-images.githubusercontent.com/4204403/60949193-48f0f300-a312-11e9-9803-709d07e995a2.png)

**Comment by A-as-name** [comment] 2019-07-10 08:44
Same issue for me after `conda clean -a`.

I just wanted to clean **pkgs** folder who was 7.5 G.

**Comment by msarahan** [comment] 2019-07-11 00:57
This is a problem with the name of cached repodata.  The fix is in https://github.com/conda/conda/pull/8900, and we hope to release a new conda version with that fix into the conda-canary channel tomorrow.

**Closed** 2019-07-11 00:57 UTC

**Comment by paulorig** [comment] 2020-01-21 00:12
For me, the problem is because i've installed Anaconda with sudo, so the folders are rooted. I reinstalled without sudo and working fine now. Ubuntu 18.04
