### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by ankitAMD** [ContinuumIO/anaconda-issues#1956] opened 2017-06-05 11:13 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=4196)
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\Ankit Gupta\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Ankit Gupta\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ankit Gupta\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Ankit Gupta\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Ankit Gupta\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Ankit Gupta\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Ankit Gupta\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=4196)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;8.1;6.3.9600;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
p

**Comment by nehaljwani** [comment] 2017-06-05 16:33
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1867

**Closed by nehaljwani** 2017-06-05 16:33 UTC
