### ISSUE TITLE
Problem with clang_osx-64-4.0.1-9 and/or clangxx_osx-64-4.0.1-9 : ERROR: This cross-compiler package contains no program bin/aras

### ISSUE THREAD

**Issue by jrsmith3** [ContinuumIO/anaconda-issues#8992] opened 2018-03-23 22:52 UTC
### Actual Behavior
I have a package I am trying to build that depends on the C++ compiler. The `clang_osx-64-4.0.1-9` and/or the `clangxx_osx-64-4.0.1-9` compilers released [earlier today](https://anaconda.org/anaconda/clang_osx-64/files) seem to have broken my build for macOS. In the morning my build worked, but after those packages were released, my build started failing.

Here 's the (somewhat  anonymized) output when I run `conda build` now; I don't know what the `/Users/build/miniconda2/conda-bld/foo_bar_baz_1521835515408/_build_env/bin/aras` is.

```
$ conda build recipe
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 0 (delta 0)
Unpacking objects: 100% (4/4), done.
From /Users/build/Documents/work/foo_bar_baz_package
   bb3f95e..9aa9fab             -> _conda_cache_origin_head
Cloning into '/Users/build/miniconda2/conda-bld/foo_bar_baz_1521835515408/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit 9aa9fab5acf0952c62a124789ed9f64ef14e849c
Author: nobody <nobody@gmail.com>
Date:   Fri Mar 23 16:02:21 2018 -0400

    Remove test_some_function.py from conda build recipe

==> git describe --tags --dirty <==

3.3.0-19-g9aa9fab

==> git status <==

On branch _conda_cache_origin_head
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
nothing to commit, working tree clean

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /Users/build/Documents/work/foo_bar_baz_package/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /Users/build/Documents/work/foo_bar_baz_package/recipe/conda_build_config.yaml
Attempting to finalize metadata for foo_bar_baz
INFO:conda_build.metadata:Attempting to finalize metadata for foo_bar_baz
Solving environment: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done
BUILD START: [u'foo_bar_baz-3.3.0.dev19_g9aa9fab-py27h04f5b5a_0.tar.bz2']
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/build/miniconda2/conda-bld/foo_bar_baz_1521835515408/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-ha1e5d58_0                                                                   
    certifi:         2018.1.18-py27_0                                                                        
    cython:          0.27.3-py27h6429b90_0                                                                   
    intel-openmp:    2018.0.0-8                                                                              
    libcxx:          4.0.1-h579ed51_0                                                                        
    libcxxabi:       4.0.1-hebd6815_0                                                                        
    libedit:         3.1-hb4e282d_0                                                                          
    libffi:          3.2.1-h475c297_4                                                                        
    libgfortran:     3.0.1-h93005f0_2                                                                        
    mkl:             2018.0.2-1                                                                              
    ncurses:         6.0-hd04f020_2                                                                          
    numpy:           1.11.3-py27h8a80b8c_4                                                                   
    openssl:         1.0.2n-hdbc3d79_0                                                                       
    pip:             9.0.1-py27_5                                                                            
    python:          2.7.14-h138c1fe_30                                                                      
    readline:        7.0-hc1231fa_4                                                                          
    setuptools:      38.5.1-py27_0                                                                           
    sqlite:          3.22.0-h3efe00b_0                                                                       
    tk:              8.6.7-h35a86e2_3                                                                        
    wheel:           0.30.0-py27h677a027_1                                                                   
    zlib:            1.2.11-hf3cbc9b_2                                                                       

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/build/miniconda2/conda-bld/foo_bar_baz_1521835515408/_build_env


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-ha1e5d58_0
    cctools:         895-h7512d6f_0       
    certifi:         2018.1.18-py27_0     
    clang:           4.0.1-h662ec87_0     
    clang_osx-64:    4.0.1-9              
    clangxx:         4.0.1-hc9b4283_0     
    clangxx_osx-64:  4.0.1-9              
    compiler-rt:     4.0.1-h5487866_0     
    intel-openmp:    2018.0.0-8           
    ld64:            274.2-h7c2db76_0     
    libcxx:          4.0.1-h579ed51_0     
    libcxxabi:       4.0.1-hebd6815_0     
    libedit:         3.1-hb4e282d_0       
    libffi:          3.2.1-h475c297_4     
    libgfortran:     3.0.1-h93005f0_2     
    llvm:            4.0.1-hc748206_0     
    llvm-lto-tapi:   4.0.1-h6701bc3_0     
    mkl:             2018.0.2-1           
    ncurses:         6.0-hd04f020_2       
    numpy:           1.11.3-py27h8a80b8c_4
    openssl:         1.0.2n-hdbc3d79_0    
    pip:             9.0.1-py27_5         
    python:          2.7.14-h138c1fe_30   
    readline:        7.0-hc1231fa_4       
    setuptools:      38.5.1-py27_0        
    sqlite:          3.22.0-h3efe00b_0    
    tk:              8.6.7-h35a86e2_3     
    wheel:           0.30.0-py27h677a027_1
    zlib:            1.2.11-hf3cbc9b_2    

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
source tree in: /Users/build/miniconda2/conda-bld/foo_bar_baz_1521835515408/work
ERROR: This cross-compiler package contains no program /Users/build/miniconda2/conda-bld/foo_bar_baz_1521835515408/_build_env/bin/aras
Traceback (most recent call last):
  File "/Users/build/miniconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/build/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/build/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/build/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/build/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 2097, in build_tree
    notest=notest,
  File "/Users/build/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1370, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/build/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 294, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/build/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 273, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/build/miniconda2/conda-bld/foo_bar_baz_1521835515408/work/conda_build.sh']' returned non-zero exit status 1
```

Here is my anonymized `meta.yaml`:

```yaml
package:
    name: foo_bar_baz
    version: 0.0.1

about:
    home: https://github.com/random_string_of_characters/foo_bar_baz_package

source:
    git_url: ..

requirements:
    build:
        - {{ compiler('cxx') }}
        - numpy
        - python {{ python }}
    host:
        - cython >=0.25.2
        - numpy
        - python {{ python }}
    run:
        - python
        - numpy

build:
    script: $PYTHON setup.py install

test:
    source_files:
        - setup.py
        - test/__init__.py
        - test/conftest.py
        - test/data
        - test/test_all_functions.py
        - test/test_utils.py
        - test/utils.py

    requires:
        - {{ compiler('cxx') }}
        - pytest
        - cython >=0.25.2

    commands:
        - python setup.py build_tests --inplace
        - py.test
```

Here's my `conda_build_config.yaml` file.

```yaml
python:
    - 2.7
CONDA_BUILD_SYSROOT:
    - /opt/MacOSX10.9.sdk        # [osx]
```

### Expected Behavior
I expected the package to build. Here is some of the output from `conda-build` from earlier today when the build was working. Note the versions of `clang_osx-64` and `clangxx_osx-64`.

```
build-host:foo_bar_baz_package build$ conda build recipe/
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 6), reused 0 (delta 0)
Unpacking objects: 100% (8/8), done.
From /Users/build/Documents/work/foo_bar_baz_package
   6111b8a..bb3f95e             -> _conda_cache_origin_head
Cloning into '/Users/build/miniconda2/conda-bld/foo_bar_baz_1521832795244/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit 9aa9fab5acf0952c62a124789ed9f64ef14e849c
Author: nobody <nobody@gmail.com>
Date:   Fri Mar 23 16:02:21 2018 -0400

    Remove test_some_function.py from conda build recipe

==> git describe --tags --dirty <==

3.3.0-19-g9aa9fab

==> git status <==

On branch _conda_cache_origin_head
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
nothing to commit, working tree clean

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /Users/build/Documents/work/foo_bar_baz_package/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /Users/build/Documents/work/foo_bar_baz_package/recipe/conda_build_config.yaml
Attempting to finalize metadata for foo_bar_baz
INFO:conda_build.metadata:Attempting to finalize metadata for foo_bar_baz
Solving environment: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done
BUILD START: [u'foo_bar_baz-3.3.0.dev19_g9aa9fab-py27h04f5b5a_0.tar.bz2']
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/build/miniconda2/conda-bld/foo_bar_baz_1521832795244/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-ha1e5d58_0                                                                   
    certifi:         2018.1.18-py27_0                                                                        
    cython:          0.27.3-py27h6429b90_0                                                                   
    intel-openmp:    2018.0.0-8                                                                              
    libcxx:          4.0.1-h579ed51_0                                                                        
    libcxxabi:       4.0.1-hebd6815_0                                                                        
    libedit:         3.1-hb4e282d_0                                                                          
    libffi:          3.2.1-h475c297_4                                                                        
    libgfortran:     3.0.1-h93005f0_2                                                                        
    mkl:             2018.0.2-1                                                                              
    ncurses:         6.0-hd04f020_2                                                                          
    numpy:           1.11.3-py27h8a80b8c_4                                                                   
    openssl:         1.0.2n-hdbc3d79_0                                                                       
    pip:             9.0.1-py27_5                                                                            
    python:          2.7.14-h138c1fe_30                                                                      
    readline:        7.0-hc1231fa_4                                                                          
    setuptools:      38.5.1-py27_0                                                                           
    sqlite:          3.22.0-h3efe00b_0                                                                       
    tk:              8.6.7-h35a86e2_3                                                                        
    wheel:           0.30.0-py27h677a027_1                                                                   
    zlib:            1.2.11-hf3cbc9b_2                                                                       

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/build/miniconda2/conda-bld/foo_bar_baz_1521832795244/_build_env


The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-ha1e5d58_0
    cctools:         895-h7512d6f_0       
    certifi:         2018.1.18-py27_0     
    clang:           4.0.1-h662ec87_0     
    clang_osx-64:    4.0.1-h1ce6c1d_8     
    clangxx:         4.0.1-hc9b4283_0     
    clangxx_osx-64:  4.0.1-h22b1bf0_8     
    compiler-rt:     4.0.1-h5487866_0     
    intel-openmp:    2018.0.0-8           
    ld64:            274.2-h7c2db76_0     
    libcxx:          4.0.1-h579ed51_0     
    libcxxabi:       4.0.1-hebd6815_0     
    libedit:         3.1-hb4e282d_0       
    libffi:          3.2.1-h475c297_4     
    libgfortran:     3.0.1-h93005f0_2     
    llvm:            4.0.1-hc748206_0     
    llvm-lto-tapi:   4.0.1-h6701bc3_0     
    mkl:             2018.0.2-1           
    ncurses:         6.0-hd04f020_2       
    numpy:           1.11.3-py27h8a80b8c_4
    openssl:         1.0.2n-hdbc3d79_0    
    pip:             9.0.1-py27_5         
    python:          2.7.14-h138c1fe_30   
    readline:        7.0-hc1231fa_4       
    setuptools:      38.5.1-py27_0        
    sqlite:          3.22.0-h3efe00b_0    
    tk:              8.6.7-h35a86e2_3     
    wheel:           0.30.0-py27h677a027_1
    zlib:            1.2.11-hf3cbc9b_2    

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
source tree in: /Users/build/miniconda2/conda-bld/foo_bar_baz_1521832795244/work
```

### Steps to Reproduce
Unfortunately, I can't give you my code. Running `conda build` is where I saw the issue.

##### Anaconda or Miniconda version:
Miniconda 2.

##### Operating System:
macOS.

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.3 (17D47)
      Kernel Version: Darwin 17.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: build-host
      User Name: build (build)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 days 19:26
```

I am using the macOS 10.9 SDK installed via [`XcodeLegacy`](https://github.com/devernay/xcodelegacy).

##### `conda info`
```
     active environment : None
       user config file : /Users/build/.condarc
 populated config files : /Users/build/.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 2.7.14.final.0
       base environment : /Users/build/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/build/miniconda2/pkgs
                          /Users/build/.conda/pkgs
       envs directories : /Users/build/miniconda2/envs
                          /Users/build/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/2.7.14 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`
```
$ conda list --show-channel-urls
# packages in environment at /Users/build/miniconda2:
#
# Name                    Version                   Build  Channel
asn1crypto                0.23.0           py27h862e517_0    defaults
attrs                     17.4.0                    <pip>
autobahn                  18.3.1                    <pip>
Automat                   0.6.0                     <pip>
beautifulsoup4            4.6.0            py27h9416283_1    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
cctools                   895                  h7512d6f_0    defaults
certifi                   2018.1.18                py27_0    defaults
cffi                      1.11.2           py27h21b8a49_0    defaults
chardet                   3.0.4            py27h2842e91_1    defaults
clang                     4.0.1                h662ec87_0    defaults
clang_osx-64              4.0.1                h1ce6c1d_8    defaults
click                     6.7                       <pip>
compiler-rt               4.0.1                h5487866_0    defaults
conda                     4.5.0                    py27_0    defaults
conda-build               3.7.2                    py27_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py27hbebe81d_0    defaults
constantly                15.1.0                    <pip>
contextlib2               0.5.5            py27h9cb85f4_0    defaults
cryptography              2.1.4            py27hdbc5e8f_0    defaults
enum34                    1.1.6            py27hf475452_1    defaults
filelock                  3.0.4                    py27_0    defaults
futures                   3.2.0            py27h1b80678_0    defaults
glob2                     0.6              py27h55c9705_0    defaults
hkdf                      0.0.3                     <pip>
humanize                  0.5.1                     <pip>
hyperlink                 18.0.0                    <pip>
idna                      2.6              py27hedea723_1    defaults
incremental               17.5.0                    <pip>
ipaddress                 1.0.18           py27h5b9a5b9_0    defaults
jinja2                    2.10             py27h70b8dc5_0    defaults
ld64                      274.2                h7c2db76_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
llvm                      4.0.1                hc748206_0    defaults
llvm-lto-tapi             4.0.1                h6701bc3_0    defaults
magic-wormhole            0.10.5                    <pip>
markupsafe                1.0              py27hd3c86fa_1    defaults
ncurses                   6.0                  hd04f020_2    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
pip                       9.0.1            py27h1567d89_4    defaults
pkginfo                   1.4.1            py27ha9221e7_0    defaults
psutil                    5.4.3            py27h1de35cc_0    defaults
pyasn1                    0.4.2                     <pip>
pyasn1-modules            0.2.1                     <pip>
pycosat                   0.6.3            py27h6c51c7e_0    defaults
pycparser                 2.18             py27h0d28d88_1    defaults
PyNaCl                    1.2.1                     <pip>
pyopenssl                 17.5.0           py27hfda213f_0    defaults
pysocks                   1.6.7            py27h1cff6a6_1    defaults
python                    2.7.14              hde5916a_29    defaults
python.app                2                py27hf2d5e94_7    defaults
pyyaml                    3.12             py27ha7932d0_1    defaults
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py27h9b2b37c_1    defaults
ruamel_yaml               0.11.14          py27h31666c4_2    defaults
scandir                   1.7              py27h1de35cc_0    defaults
service-identity          17.0.0                    <pip>
setuptools                36.5.0           py27h2a45cec_0    defaults
six                       1.11.0           py27h7252ba3_1    defaults
spake2                    0.8                       <pip>
sqlite                    3.20.1               h7e4c145_2    defaults
tk                        8.6.7                h35a86e2_3    defaults
tqdm                      4.19.8                    <pip>
Twisted                   17.9.0                    <pip>
txaio                     2.9.0                     <pip>
txtorcon                  0.20.0                    <pip>
urllib3                   1.22             py27hc3787e9_0    defaults
wheel                     0.30.0           py27h677a027_1    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
zope.interface            4.4.3                     <pip>
```

**Comment by jrsmith3** [comment] 2018-03-23 23:04
In case it takes awhile to fix this problem, is there any way to modify `meta.yaml` so I get the correct compilers?

**Comment by mcflugen** [comment] 2018-03-23 23:04
I'm having the same issue (it seems to be the same as [#6600](https://github.com/conda/conda/issues/6600) but on Mac) and has only begun in the last couple days or so.

To reproduce the problem, I simply have to install clang in an environment. The following will generate the error message that @jrsmith3  describes,
```bash
$ conda create -n _clang
$ source activate _clang
$ conda install clang_osx-64
```
I then get the error message about no program `aras`.
```
ERROR: This cross-compiler package contains no program <prefix>/conda/envs/_testing/bin/aras
ERROR: deactivate_clang_osx-64.sh failed, see above for details
ERROR: This cross-compiler package contains no program <prefix>/conda/envs/_testing/bin/aras
ERROR: activate_clang_osx-64.sh failed, see above for details
```

**Comment by mingwandroid** [comment] 2018-03-23 23:26
Fixed packages are being uploaded now.

**Comment by jrsmith3** [comment] 2018-03-23 23:35
@mingwandroid Thanks! Do you know what went wrong with the packages that were uploaded a few hours ago? Also, just for my own benefit, can you tell me what `aras` is? I couldn’t find it when I searched.

**Comment by mingwandroid** [comment] 2018-03-23 23:42
Fixed in build #10.

I forgot to pass the build matrix into conda-build so a substitution (@CHOST@) that should've happened did not happen.

You can see the diff here:

```
@@ -101,13 +101,13 @@
 env > /tmp/old-env-$$.txt

 _tc_activation \
-  activate host  - \
+  activate host x86_64-apple-darwin13.4.0 x86_64-apple-darwin13.4.0- \
   ar as checksyms codesign_allocate indr install_name_tool libtool lipo nm nmedit otool \
   pagestuff ranlib redo_prebinding seg_addr_table seg_hack segedit size strings strip \
   ld \
   clang \
-  "CC,${CC:--clang}" \
-  "CPPFLAGS,${CPPFLAGS:--D_FORTIFY_SOURCE=2 -mmacosx-version-min=}" \
+  "CC,${CC:-x86_64-apple-darwin13.4.0-clang}" \
+  "CPPFLAGS,${CPPFLAGS:--D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9}" \
   "CFLAGS,${CFLAGS:-${CFLAGS_USED}}" \
   "LDFLAGS,${LDFLAGS:-${LDFLAGS_USED}}" \
   "LDFLAGS_LD,${LDFLAGS_LD:-${LDFLAGS_LD_USED}}" \
```

**Comment by mcflugen** [comment] 2018-03-24 02:35
Thanks @mingwandroid! That fixed it. All is good.

**Comment by jrsmith3** [comment] 2018-03-26 13:25
The package update looks like it fixed my issue, too. Should I close this bug?

**Comment by msarahan** [comment] 2018-03-26 13:26
Thanks, closing.

**Comment by mingwandroid** [comment] 2018-08-21 07:01
How so? If the dependencies do not change (which I'm fairly sure they didn't here) then a new build should be completely fine. Please explain what's wrong with that.

**Comment by mingwandroid** [comment] 2018-08-21 07:04
And I'm not really happy with 'as we should know' statement and we are loathe to change metadata without any reason to do so.

**Comment by mingwandroid** [comment] 2018-08-21 08:04
```
curl -o repodata.macos.json -SLO https://repo.anaconda.com/pkgs/main/osx-64/repodata.json
cat repodata.macos.json  | jq --raw-output ".packages[] | select(.name | contains(\"clangxx_osx-64\"))" |  jq -s 'sort_by(.timestamp)'
```

```
..
  {
    "build": "h22b1bf0_8",
    "build_number": 8,
    "depends": [
      "clang_osx-64 4.0.1 h1ce6c1d_8",
      "clangxx",
      "libcxx",
      "libcxx >=4.0.1"
    ],
    "md5": "e9201939f98486745ec792d8ba769895",
    "name": "clangxx_osx-64",
    "sha256": "5792864387128be8e90310e1cee4bac2ff68c978f7fd073fb30aad7277c23e38",
    "size": 5818,
    "subdir": "osx-64",
    "timestamp": 1516031659273,
    "version": "4.0.1"
  },
  {
    "build": "9",
    "build_number": 9,
    "depends": [
      "clang_osx-64 4.0.1 9",
      "clangxx",
      "libcxx",
      "libcxx >=4.0.1"
    ],
    "md5": "938135578aacd6cca5b018e6e8cf8ac2",
    "name": "clangxx_osx-64",
    "sha256": "82baa6229554c203e6981a7e20b2e7409f7ed1ccbd6c757e2509c088582a144c",
    "size": 6889,
    "subdir": "osx-64",
    "timestamp": 1521821638932,
    "version": "4.0.1"
  },
  {
    "build": "h22b1bf0_10",
    "build_number": 10,
    "depends": [
      "clang_osx-64 >=4.0.1,<4.0.2.0a0",
      "clangxx",
      "libcxx",
      "libcxx >=4.0.1"
    ],
    "md5": "550c40fbc14510779e553078af6ae23b",
    "name": "clangxx_osx-64",
    "sha256": "d3e317344852af4d01e6cd2676fba7d7a62af5bf896321205e90481bd96dd45e",
    "size": 7390,
    "subdir": "osx-64",
    "timestamp": 1521847364493,
    "version": "4.0.1"
  },
  {
    "build": "h22b1bf0_11",
    "build_number": 11,
    "depends": [
      "clang_osx-64 >=4.0.1,<4.0.2.0a0",
      "clangxx",
      "libcxx >=4.0.1"
    ],
    "md5": "04f864612773b7e1ae26aad877e50bdd",
    "name": "clangxx_osx-64",
    "sha256": "d32676378f525490ab443ed3d2220390694587d453a3f35ef8371b3c0e3f3604",
    "size": 7508,
    "subdir": "osx-64",
    "timestamp": 1526461900028,
    "version": "4.0.1"
  }
```

**Comment by mcg1969** [comment] 2018-08-21 11:30
The metadata _did_ change. The broken builds have no dependencies.

**Comment by mcg1969** [comment] 2018-08-21 11:31
Hmm, surely I saw something different on anaconda.org? I did for the Linux cae

**Closed** 2018-08-21 11:30 UTC

**Comment by mingwandroid** [comment] 2018-08-21 11:32
I showed the [metadata](https://github.com/ContinuumIO/anaconda-issues/issues/8992#issuecomment-414587307).

**Comment by mcg1969** [comment] 2018-08-21 11:32
I could have sworn I saw something wrong on anaconda.org, Ray, my apologies!

**Comment by mingwandroid** [comment] 2018-08-21 11:33
No problem.

**Comment by mcg1969** [comment] 2018-08-21 11:33
Ah! The metadata is wrong on the anaconda channel

**Comment by mingwandroid** [comment] 2018-08-21 11:35
Some sync issue?

**Comment by mingwandroid** [comment] 2018-08-21 11:37
But I used the anaconda channel to get my metadata:

`https://repo.anaconda.com/pkgs/main/osx-64/repodata.json`

**Comment by mcg1969** [comment] 2018-08-21 11:42
I mean the conda.anaconda.org/anaconda channel .... I was looking at metadata through the GUI instead of through a direct JSON search

**Comment by mcg1969** [comment] 2018-08-21 11:44
Can you think of another reason why the Linux case is breaking for me then?

**Comment by mcg1969** [comment] 2018-08-21 11:50
It does look like the metadata is wrong for Linux:
```
   "gcc_linux-64-7.2.0-24.tar.bz2": {
      "build": "24",
      "build_number": 24,
      "depends": [],
      "license": "GPL",
      "md5": "f9e7d53aace773415713f2f15255d9cc",
      "name": "gcc_linux-64",
      "sha256": "ad3ab401b893cd814f3237ac95f4c9769bd70f996f16f623c1ef27aaed68af3b",
      "size": 5922,
      "subdir": "linux-64",
      "timestamp": 1514474638847,
      "version": "7.2.0"
    },
    "gcc_linux-64-7.2.0-25.tar.bz2": {
      "build": "25",
      "build_number": 25,
      "depends": [
        "binutils_linux-64 7.2.0 25",
        "gcc_impl_linux-64 7.2.0.*"
      ],
      "license": "GPL",
      "md5": "a93a8600bf1883e43c6652107e883611",
      "name": "gcc_linux-64",
      "sha256": "750ce6dabc744e048db0765868652367d3935dcf96fd95159330bd40e53b97b8",
      "size": 5965,
      "subdir": "linux-64",
      "timestamp": 1514480906213,
      "version": "7.2.0"
    },
```

**Comment by mingwandroid** [comment] 2018-08-21 11:54
This issue was about clang compilers on macOS, it bears no relation to linux GCC compilers, or only as much as libedit issues apply to readline issues.

Please open a new issue rather than taking this one all tangential.

**Comment by mcg1969** [comment] 2018-08-21 11:56
That’s totally fair, Ray. I misread the Mac metadata in my own head last night, and that’s why I am incorrectly conflating the two issues in my mind.

**Comment by msarahan** [comment] 2018-08-21 13:42
I will revoke the incorrect linux compiler.
