### ISSUE TITLE
Anaconda Navigator and prompt error

### ISSUE THREAD

**Issue by CodeNinjaHM** [ContinuumIO/anaconda-issues#4922] opened 2017-09-02 11:17 UTC
Everytime I open the prompt it says 'Access Denied'.
I cannot open the Navigator either. 

Main Error : byte indices must be integers or slices, not str.

Traceback (most recent call last):
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\harin\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

Help fix the issue.

**Comment by goanpeca** [comment] 2017-09-02 11:17
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-09-02 11:17 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by CodeNinjaHM** [comment] 2017-09-02 11:26
Dear Gonzalo *Peña-Castellanos,*

*The Anaconda prompt does not seem to work. It says access denied. How Do I
fix that in the first place.*

*Thanks.*

**Comment by goanpeca** [comment] 2017-09-02 13:51
@CodeNinjaHM hmmm access denied? what do you mean, if you open the Anaconda Prompt wht do you get? (paste it here please :-) )

**Comment by CodeNinjaHM** [comment] 2017-09-03 16:49
I uninstalled Anaconda and re-installed it again. Works fine now. Thanks.
