### ISSUE TITLE
Anaconda navigator will not launch

### ISSUE THREAD

**Issue by 1976dave** [ContinuumIO/anaconda-issues#7400] opened 2017-11-20 16:27 UTC
I am on macOs High Sierra.

Upon launching anaconda navigator I get this message:

Traceback (most recent call last):
File "/Users/me/anaconda/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/me/anaconda/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/me/anaconda/lib/python2.7/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/me/anaconda/lib/python2.7/site-packages/psutil/__init__.py", line 694, in cmdline
return self._proc.cmdline()
File "/Users/me/anaconda/lib/python2.7/site-packages/psutil/_psosx.py", line 285, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=1189)

I tried updating anaconda navigator and still get the same message.  I suspect this may have something to do with me just having installed the spacepy library, which required me to first get a fortran compiler (which I did through macports) but I do not know enough computer science to sort out my issue.

I downloaded the spacepy tar.gz and moved that into my python2.7 library, cd'd to the spacepy folder and built it in place using python setup.py install.

**Comment by goanpeca** [comment] 2017-11-20 21:01
@1976dave have you tried typing on the Terminal

**See issue #6970 for more information on how to fix this issue.**

---

Closing as duplicate of #6970

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ anaconda-navigator --reset
```

?

**Closed** 2018-05-30 21:10 UTC
Labels: pending:feedback, pkg:navigator
