### ISSUE TITLE
Anaconda version number

### ISSUE THREAD

**Issue by sho-87** [ContinuumIO/anaconda-issues#1088] opened 2016-09-22 10:25 UTC
I'm pretty confused by the version numbers used by anaconda. I installed anaconda by doing the following:

1. Install Anaconda 4.1.1 (Python 2.7 64 bit) using the installer from the website
2. `conda update conda`
3. `conda update anaconda`

So I'm expecting to see my version number as **4.1.1**, but, my start menu contains a folder for Anaconda **2** and when I run python from the command line I see Anaconda **2.3.0**

I see that some people are using version **4.2** (#1076). I would have thought that running either steps 2 or 3 above would update me to the latest, which presumably is 4.2? But as mentioned, starting python still shows **2.3.0**

Side note: the latest python 2 release is 2.7.12, but I'm guessing this isnt included in the latest anaconda release which why, despite steps 2 and 3 above, my python version is still 2.7.10?

**Comment by ilanschnell** [comment] 2016-09-23 14:22
Anaconda 4.2 is not released yet.  We are planning to release it next week.

**Comment by sho-87** [comment] 2016-09-23 16:30
and how about the difference between 2.3.0 and 4.1.1?

**Comment by csoja** [comment] 2016-09-23 17:03
The latest version right now is v4.1.1.
What happens when you _conda install anaconda=4.1.1_?
Can you copy the results here?  
Also, can you copy in the results of what shows on the screen when you ran _conda update anaconda_ and got anaconda v2.3?

**Comment by sho-87** [comment] 2016-09-23 17:46
ok so I did a fresh install from the website and here are the steps I took and the output I get:

- Install Anaconda 4.1.1 (Python 2.7 64 bit) using the installer from the website

When I use command prompt to start Python I correctly see Python 2.7.12 and Anaconda 4.1.1. All of the start menu links work (e.g. Jupyter notebook). Navigator also seems to start correctly (#1086)

- `conda update conda`

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    ruamel_yaml-0.11.14        |           py27_0         212 KB
    conda-4.2.7                |           py27_0         421 KB

```
The following packages will be UPDATED:

    conda:       4.1.6-py27_0  --> 4.2.7-py27_0
    conda-env:   2.5.1-py27_0  --> 2.6.0-0
    ruamel_yaml: 0.11.7-py27_0 --> 0.11.14-py27_0
```

After this step everything is working fine again, nothing has changed

- `conda update anaconda`

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    node-webkit-0.10.1         |                0        23.5 MB
    python-2.7.10              |                0        19.5 MB
    zlib-1.2.8                 |                0         116 KB
    _license-1.1               |           py27_0          50 KB
    alabaster-0.7.3            |           py27_0          13 KB
    beautiful-soup-4.3.2       |           py27_1         109 KB
    boto-2.38.0                |           py27_0         1.5 MB
    cdecimal-2.3               |           py27_1         117 KB
    certifi-14.05.14           |           py27_0         154 KB
    clyent-0.3.4               |           py27_0          13 KB
    colorama-0.3.3             |           py27_0          17 KB
    cython-0.22.1              |           py27_0         1.8 MB
    cytoolz-0.7.3              |           py27_0         188 KB
    decorator-3.4.2            |           py27_0           8 KB
    docutils-0.12              |           py27_1         637 KB
    enum34-1.0.4               |           py27_0          48 KB
    fastcache-1.0.2            |           py27_0          23 KB
    funcsigs-0.4               |           py27_0          19 KB
    greenlet-0.4.7             |           py27_0          13 KB
    grin-1.2.1                 |           py27_2          23 KB
    hdf5-1.8.15.1              |                2         1.4 MB
    idna-2.0                   |           py27_0         122 KB
    ipaddress-1.0.7            |           py27_0          25 KB
    jdcal-1.0                  |           py27_0           9 KB
    jedi-0.8.1                 |           py27_0         171 KB
    jsonschema-2.4.0           |           py27_0          92 KB
    launcher-1.0.0             |                1         1.6 MB
    lxml-3.4.4                 |           py27_0         1.5 MB
    markupsafe-0.23            |           py27_0          23 KB
    menuinst-1.0.4             |           py27_0          52 KB
    mistune-0.5.1              |           py27_1         116 KB
    mock-1.0.1                 |           py27_0          36 KB
    multipledispatch-0.4.7     |           py27_0          11 KB
    nose-1.3.7                 |           py27_0         236 KB
    numpy-1.9.2                |           py27_0        23.2 MB
    pep8-1.6.2                 |           py27_0          87 KB
    pillow-2.8.2               |           py27_0         920 KB
    ply-3.6                    |           py27_0          70 KB
    psutil-2.2.1               |           py27_0          99 KB
    py-1.4.27                  |           py27_0         122 KB
    pyasn1-0.1.7               |           py27_0          48 KB
    pycosat-0.6.1              |           py27_0          47 KB
    pycparser-2.14             |           py27_0         148 KB
    pycrypto-2.6.1             |           py27_3         454 KB
    pyflakes-0.9.2             |           py27_0          94 KB
    pygments-2.0.2             |           py27_0         1.1 MB
    pyparsing-2.0.3            |           py27_0          63 KB
    pyqt-4.10.4                |           py27_1        31.2 MB
    pyreadline-2.0             |           py27_0         127 KB
    pytz-2015.4                |           py27_0         168 KB
    pywin32-219                |           py27_0        10.4 MB
    pyyaml-3.11                |           py27_1         167 KB
    pyzmq-14.7.0               |           py27_0         597 KB
    requests-2.7.0             |           py27_0         590 KB
    setuptools-17.1.1          |           py27_0         646 KB
    six-1.9.0                  |           py27_0          16 KB
    snowballstemmer-1.2.0      |           py27_0          72 KB
    sphinx_rtd_theme-0.1.7     |           py27_0         209 KB
    sqlalchemy-1.0.5           |           py27_0         1.2 MB
    ssl_match_hostname-3.4.0.2 |           py27_0           6 KB
    sympy-0.7.6                |           py27_0         6.2 MB
    toolz-0.7.2                |           py27_0          48 KB
    ujson-1.33                 |           py27_0          17 KB
    unicodecsv-0.9.4           |           py27_0          17 KB
    werkzeug-0.10.4            |           py27_0         375 KB
    xlrd-0.9.3                 |           py27_0         160 KB
    xlsxwriter-0.7.3           |           py27_0         182 KB
    xlwt-1.0.0                 |           py27_0         151 KB
    argcomplete-0.8.9          |           py27_0          83 KB
    astropy-1.0.3              |       np19py27_0         5.1 MB
    babel-1.3                  |           py27_0         2.3 MB
    bcolz-0.9.0                |       np19py27_0         316 KB
    bottleneck-1.0.0           |       np19py27_0         142 KB
    cffi-1.1.0                 |           py27_0         164 KB
    dynd-python-0.6.5          |       np19py27_0         890 KB
    gevent-1.0.1               |           py27_0         293 KB
    h5py-2.5.0                 |       np19py27_1         552 KB
    ipython-3.2.0              |           py27_0         3.4 MB
    jinja2-2.7.3               |           py27_2         307 KB
    llvmlite-0.5.0             |           py27_0         4.7 MB
    networkx-1.9.1             |           py27_0         928 KB
    nltk-3.0.3                 |       np19py27_0         1.5 MB
    numexpr-2.4.3              |       np19py27_0         120 KB
    openpyxl-1.8.5             |           py27_0         127 KB
    patsy-0.3.0                |       np19py27_0         308 KB
    pip-7.0.3                  |           py27_0         1.4 MB
    pytest-2.7.1               |           py27_0         225 KB
    python-dateutil-2.4.2      |           py27_0         219 KB
    scipy-0.15.1               |       np19py27_0        71.3 MB
    tornado-4.2                |           py27_0         510 KB
    xlwings-0.3.5              |           py27_0         234 KB
    binstar-0.11.0             |           py27_0         137 KB
    blz-0.6.2                  |       np19py27_1         296 KB
    cryptography-0.9.1         |           py27_0         1.1 MB
    datashape-0.4.5            |       np19py27_0          95 KB
    flask-0.10.1               |           py27_1         128 KB
    gevent-websocket-0.9.3     |           py27_0          24 KB
    ipython-notebook-3.2.0     |           py27_0           5 KB
    ipython-qtconsole-3.2.0    |           py27_0           4 KB
    matplotlib-1.4.3           |       np19py27_1        41.9 MB
    numba-0.19.1               |       np19py27_0         1.1 MB
    pandas-0.16.2              |       np19py27_0         4.6 MB
    pytables-3.2.0             |       np19py27_0         1.4 MB
    scikit-learn-0.16.1        |       np19py27_0         3.5 MB
    sockjs-tornado-1.0.1       |           py27_0          31 KB
    sphinx-1.3.1               |           py27_0         1.2 MB
    bokeh-0.9.0                |       np19py27_0        12.6 MB
    odo-0.3.2                  |       np19py27_0         187 KB
    pyopenssl-0.15.1           |           py27_1         1.2 MB
    runipy-0.1.3               |           py27_0          48 KB
    scikit-image-0.11.3        |       np19py27_0        15.8 MB
    spyder-2.3.5.2             |           py27_0         2.6 MB
    statsmodels-0.6.1          |       np19py27_0         4.6 MB
    blaze-core-0.8.0           |       np19py27_0         319 KB
    ipykernel-4.0.3            |           py27_0         111 KB
    spyder-app-2.3.5.2         |           py27_0           7 KB
    anaconda-2.3.0             |       np19py27_0          30 KB
    blaze-0.9.1                |           py27_0         577 KB
    qtconsole-4.0.1            |           py27_0         166 KB

The following NEW packages will be INSTALLED:

    _license:           1.1-py27_0
    bcolz:              0.9.0-np19py27_0
    beautiful-soup:     4.3.2-py27_1
    binstar:            0.11.0-py27_0
    blaze-core:         0.8.0-np19py27_0
    blz:                0.6.2-np19py27_1
    certifi:            14.05.14-py27_0
    dynd-python:        0.6.5-np19py27_0
    gevent-websocket:   0.9.3-py27_0
    ipython-notebook:   3.2.0-py27_0
    ipython-qtconsole:  3.2.0-py27_0
    launcher:           1.0.0-1
    mock:               1.0.1-py27_0
    node-webkit:        0.10.1-0
    runipy:             0.1.3-py27_0
    spyder-app:         2.3.5.2-py27_0
    ujson:              1.33-py27_0

The following packages will be DOWNGRADED due to dependency conflicts:

    alabaster:          0.7.8-py27_0       --> 0.7.3-py27_0
    anaconda:           4.1.1-np111py27_0  --> 2.3.0-np19py27_0
    argcomplete:        1.0.0-py27_1       --> 0.8.9-py27_0
    astropy:            1.2.1-np111py27_0  --> 1.0.3-np19py27_0
    babel:              2.3.3-py27_0       --> 1.3-py27_0
    blaze:              0.10.1-py27_0      --> 0.9.1-py27_0
    bokeh:              0.12.0-py27_0      --> 0.9.0-np19py27_0
    boto:               2.40.0-py27_0      --> 2.38.0-py27_0
    bottleneck:         1.1.0-np111py27_0  --> 1.0.0-np19py27_0
    cdecimal:           2.3-py27_2         --> 2.3-py27_1
    cffi:               1.6.0-py27_0       --> 1.1.0-py27_0
    clyent:             1.2.2-py27_0       --> 0.3.4-py27_0
    colorama:           0.3.7-py27_0       --> 0.3.3-py27_0
    cryptography:       1.4-py27_0         --> 0.9.1-py27_0
    cython:             0.24-py27_0        --> 0.22.1-py27_0
    cytoolz:            0.8.0-py27_0       --> 0.7.3-py27_0
    datashape:          0.5.2-py27_0       --> 0.4.5-np19py27_0
    decorator:          4.0.10-py27_0      --> 3.4.2-py27_0
    docutils:           0.12-py27_2        --> 0.12-py27_1
    enum34:             1.1.6-py27_0       --> 1.0.4-py27_0
    fastcache:          1.0.2-py27_1       --> 1.0.2-py27_0
    flask:              0.11.1-py27_0      --> 0.10.1-py27_1
    funcsigs:           1.0.2-py27_0       --> 0.4-py27_0
    gevent:             1.1.1-py27_0       --> 1.0.1-py27_0
    greenlet:           0.4.10-py27_0      --> 0.4.7-py27_0
    grin:               1.2.1-py27_3       --> 1.2.1-py27_2
    h5py:               2.6.0-np111py27_0  --> 2.5.0-np19py27_1
    hdf5:               1.8.15.1-vc9_4     [vc9] --> 1.8.15.1-2
    idna:               2.1-py27_0         --> 2.0-py27_0
    ipaddress:          1.0.16-py27_0      --> 1.0.7-py27_0
    ipykernel:          4.3.1-py27_0       --> 4.0.3-py27_0
    ipython:            4.2.0-py27_0       --> 3.2.0-py27_0
    jdcal:              1.2-py27_1         --> 1.0-py27_0
    jedi:               0.9.0-py27_1       --> 0.8.1-py27_0
    jinja2:             2.8-py27_1         --> 2.7.3-py27_2
    jsonschema:         2.5.1-py27_0       --> 2.4.0-py27_0
    llvmlite:           0.11.0-py27_0      --> 0.5.0-py27_0
    lxml:               3.6.0-py27_0       --> 3.4.4-py27_0
    markupsafe:         0.23-py27_2        --> 0.23-py27_0
    matplotlib:         1.5.1-np111py27_0  --> 1.4.3-np19py27_1
    menuinst:           1.4.1-py27_0       --> 1.0.4-py27_0
    mistune:            0.7.2-py27_0       --> 0.5.1-py27_1
    multipledispatch:   0.4.8-py27_0       --> 0.4.7-py27_0
    networkx:           1.11-py27_0        --> 1.9.1-py27_0
    nltk:               3.2.1-py27_0       --> 3.0.3-np19py27_0
    nose:               1.3.7-py27_1       --> 1.3.7-py27_0
    numba:              0.26.0-np111py27_0 --> 0.19.1-np19py27_0
    numexpr:            2.6.0-np111py27_0  --> 2.4.3-np19py27_0
    numpy:              1.11.1-py27_0      --> 1.9.2-py27_0
    odo:                0.5.0-py27_1       --> 0.3.2-np19py27_0
    openpyxl:           2.3.2-py27_0       --> 1.8.5-py27_0
    pandas:             0.18.1-np111py27_0 --> 0.16.2-np19py27_0
    patsy:              0.4.1-py27_0       --> 0.3.0-np19py27_0
    pep8:               1.7.0-py27_0       --> 1.6.2-py27_0
    pillow:             3.2.0-py27_1       --> 2.8.2-py27_0
    pip:                8.1.2-py27_0       --> 7.0.3-py27_0
    ply:                3.8-py27_0         --> 3.6-py27_0
    psutil:             4.3.0-py27_0       --> 2.2.1-py27_0
    py:                 1.4.31-py27_0      --> 1.4.27-py27_0
    pyasn1:             0.1.9-py27_0       --> 0.1.7-py27_0
    pycosat:            0.6.1-py27_1       --> 0.6.1-py27_0
    pycparser:          2.14-py27_1        --> 2.14-py27_0
    pycrypto:           2.6.1-py27_4       --> 2.6.1-py27_3
    pyflakes:           1.2.3-py27_0       --> 0.9.2-py27_0
    pygments:           2.1.3-py27_0       --> 2.0.2-py27_0
    pyopenssl:          0.16.0-py27_0      --> 0.15.1-py27_1
    pyparsing:          2.1.4-py27_0       --> 2.0.3-py27_0
    pyqt:               4.11.4-py27_6      --> 4.10.4-py27_1
    pyreadline:         2.1-py27_0         --> 2.0-py27_0
    pytables:           3.2.2-np111py27_4  --> 3.2.0-np19py27_0
    pytest:             2.9.2-py27_0       --> 2.7.1-py27_0
    python:             2.7.12-0           --> 2.7.10-0
    python-dateutil:    2.5.3-py27_0       --> 2.4.2-py27_0
    pytz:               2016.4-py27_0      --> 2015.4-py27_0
    pywin32:            220-py27_1         --> 219-py27_0
    pyyaml:             3.11-py27_4        --> 3.11-py27_1
    pyzmq:              15.2.0-py27_0      --> 14.7.0-py27_0
    qtconsole:          4.2.1-py27_0       --> 4.0.1-py27_0
    requests:           2.10.0-py27_0      --> 2.7.0-py27_0
    scikit-image:       0.12.3-np111py27_1 --> 0.11.3-np19py27_0
    scikit-learn:       0.17.1-np111py27_1 --> 0.16.1-np19py27_0
    scipy:              0.17.1-np111py27_1 --> 0.15.1-np19py27_0
    setuptools:         23.0.0-py27_0      --> 17.1.1-py27_0
    six:                1.10.0-py27_0      --> 1.9.0-py27_0
    snowballstemmer:    1.2.1-py27_0       --> 1.2.0-py27_0
    sockjs-tornado:     1.0.3-py27_0       --> 1.0.1-py27_0
    sphinx:             1.4.1-py27_0       --> 1.3.1-py27_0
    sphinx_rtd_theme:   0.1.9-py27_0       --> 0.1.7-py27_0
    spyder:             2.3.9-py27_0       --> 2.3.5.2-py27_0
    sqlalchemy:         1.0.13-py27_0      --> 1.0.5-py27_0
    ssl_match_hostname: 3.4.0.2-py27_1     --> 3.4.0.2-py27_0
    statsmodels:        0.6.1-np111py27_1  --> 0.6.1-np19py27_0
    sympy:              1.0-py27_0         --> 0.7.6-py27_0
    toolz:              0.8.0-py27_0       --> 0.7.2-py27_0
    tornado:            4.3-py27_1         --> 4.2-py27_0
    unicodecsv:         0.14.1-py27_0      --> 0.9.4-py27_0
    werkzeug:           0.11.10-py27_0     --> 0.10.4-py27_0
    xlrd:               1.0.0-py27_0       --> 0.9.3-py27_0
    xlsxwriter:         0.9.2-py27_0       --> 0.7.3-py27_0
    xlwings:            0.7.2-py27_0       --> 0.3.5-py27_0
    xlwt:               1.1.2-py27_0       --> 1.0.0-py27_0
    zlib:               1.2.8-vc9_3        [vc9] --> 1.2.8-0

This actually seems to downgrade a lot of packages (and downgrades python to 2.7.10). So it is this step, where I upgrade anaconda, that causes the problems described in the initial post

The installation process is mostly ok, but navigator no longer starts (#1086) and an additional start menu folder with broken links is also created (#1087). A warning also comes up after linking packages:

`WARNING conda.common.disk:delete_trash(237): Unable to clean trash directory C:\Users\Simon\Anaconda2\pkgs\.trash`

- At this stage if I try `conda install anaconda=4.1.1` I get the following error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda 4.1.1*
  - gevent-websocket -> gevent 0.13.7|0.13.8|1.0|1.0.1|1.0.2|1.1.0
  - gevent-websocket -> python 2.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by mcg1969** [comment] 2016-09-23 18:24
I am almost certain I've seen the gevent-websocket problem before, and identified the correction. In fact I'm surprised it is coming up again. I will try and track down the documentation for the issue. The problem here is almost certainly a tight dependency pinning problem.

**Comment by csoja** [comment] 2016-09-23 18:34
Thank you for the additional details.  We have been able to reproduce the problem with a clean machine (Windows 8 64-bit Anaconda2 v4.1.1 installation) - and it is something we need to fix.  Our apologies you've run into this.

**Comment by sho-87** [comment] 2016-09-23 18:54
Can confirm the same thing is happening on my laptop (OSX El Capitan). One difference I noticed there is that after doing `conda update conda`, launching `python` from terminal shows an anaconda version of `Anaconda custom (x86_64)` instead of `4.1.1`

**Comment by mcg1969** [comment] 2016-09-23 18:57
Can we verify that this is limited to 4.2.x? If it's possible, @sho-87, can you repeat the steps you've taken, except: instead of `conda update conda`, do `conda install conda=4.1` instead, to make sure that the very latest version of conda 4.1 is installed, but not 4.2, before you do `conda update anaconda`.

**Comment by sho-87** [comment] 2016-09-23 19:09
ok so after fresh install I ran `conda install conda=4.1`:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.1.12               |           py27_0         245 KB

The following packages will be UPDATED:

    conda: 4.1.6-py27_0 --> 4.1.12-py27_0
```

Then running `conda update anaconda` shows no new packages to install so it seems like this is an issue with conda 4.2

**Comment by mcg1969** [comment] 2016-09-23 19:10
That's very helpful. Thank you very much for the help.

**Comment by mcg1969** [comment] 2016-09-24 16:42
@ilanschnell @csoja @kalefranz I haven't found the problem with 4.2.x yet; I'm still studying 4.1.x's behavior. But I have something that I think is somewhat important.

Notice above that sho-87 remarked that updating `conda` to 4.2.x required switching the Anaconda package to `anaconda-custom`. This should not be happening---we should be able to upgrade and downgrade `conda` without affecting `anaconda`.  

The reason this is happening is that `ruamel_yaml 0.11.7` was included in Anaconda starting in version 4.1.  But `ruamel_yaml` is a `conda` dependency, and indeed the only reason we've built this package is because of its use in `conda`. And `conda 4.2` depends on a _later_ version of this package, specifically `>=0.11.14`. Therefore, updating `conda` _forces_ Anaconda to be updated to its "custom" version.

I strongly suggest that this coupling of Anaconda and conda is a bad thing and needs to be corrected ASAP. The simplest way to do this is to remove `ruamel_yaml` from all `anaconda` metapackages. The installers themselves do not need to be changed, because `conda` itself will pick up that package as a dependency anyway. A metadata hotfix should be sufficient.

**Comment by mcg1969** [comment] 2016-09-24 16:47
@csoja @ilanschnell @kalefranz Actually, this may be _exactly_ what the problem is: _conda 4.2 is incompatible with anaconda 4.1_. After all, `anaconda 4.1' requires `ruamel_yaml 0.11.7`, while `conda 4.2` requires `ruamel_yaml 0.11.14` or later. They cannot be installed in the same environment.

**Comment by mcg1969** [comment] 2016-09-24 16:51
This investigation has highlighted the urgency of my solver/hint fix. The `gevent-websocket` hint is completely useless. Basically, it should have said that `conda 4.2` and `anaconda 4.1` conflict; and ideally, it would have pointed to their common `ruamel_yaml` dependency as the cause.

**Comment by ilanschnell** [comment] 2016-09-25 21:19
Fantastic!  Thanks for figuring this out @mcg1969!  I will make a hotfix to remove `yuamel_yaml` as an Anaconda dependency for all packages on repo.continuum.io`, and also ensure that the new Anaconda 4.2 installers that we are working on will reflect this change.

**Comment by ilanschnell** [comment] 2016-09-26 01:43
I have just removed the `ruamel_yaml` dependency from all Anaconda meta-packages on `repo.continuum.io`.

**Comment by csoja** [comment] 2016-09-26 14:32
I confirmed that I can now do
1) install anaconda 4.1.1
2) conda update conda
3) conda update anaconda 

And I remain on the latest version of Anaconda v4.1.1.  

Thanks @sho-87 for your help in reporting and debugging this issue! 

Closing this issue.

**Closed by csoja** 2016-09-26 14:32 UTC
Labels: bug

**Comment by ecseymour** [comment] 2016-10-12 16:08
I too have this problem of being unable to upgrade from version 2.3, and I coming here as per the request at [this Google Group conversation](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/WPhdE00TkqU).

Here is the output of `conda info a`:

    Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.4
         python version : 2.7.10.final.0
       requests version : 2.7.0
       root environment : /home/eric/anaconda  (writable)
    default environment : /home/eric/anaconda
       envs directories : /home/eric/anaconda/envs
          package cache : /home/eric/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False 

    conda environments:
   
    csvkit                   /home/eric/anaconda/envs/csvkit
    econ                     /home/eric/anaconda/envs/econ
    fignos                   /home/eric/anaconda/envs/fignos
    geo                      /home/eric/anaconda/envs/geo
    ll-env                   /home/eric/anaconda/envs/ll-env
    my-r-env                 /home/eric/anaconda/envs/my-r-env
    pelican                  /home/eric/anaconda/envs/pelican
    pysqlite                 /home/eric/anaconda/envs/pysqlite
    robobrowser              /home/eric/anaconda/envs/robobrowser
    shapefile                /home/eric/anaconda/envs/shapefile
    usaddress                /home/eric/anaconda/envs/usaddress
    root                  *  /home/eric/anaconda
   
    sys.version: 2.7.10 |Anaconda 2.3.0 (64-bit)| (defaul...
    sys.prefix: /home/eric/anaconda
    sys.executable: /home/eric/anaconda/bin/python
    conda location: /home/eric/anaconda/lib/python2.7/site-packages/conda
    conda-build: /home/eric/anaconda/bin/conda-build
    conda-convert: /home/eric/anaconda/bin/conda-convert
    conda-develop: /home/eric/anaconda/bin/conda-develop
    conda-env: /home/eric/anaconda/bin/conda-env
    conda-index: /home/eric/anaconda/bin/conda-index
    conda-inspect: /home/eric/anaconda/bin/conda-inspect
    conda-metapackage: /home/eric/anaconda/bin/conda-metapackage
    conda-render: /home/eric/anaconda/bin/conda-render
    conda-server: /home/eric/anaconda/bin/conda-server
    conda-sign: /home/eric/anaconda/bin/conda-sign
    conda-skeleton: /home/eric/anaconda/bin/conda-skeleton
    user site dirs:
   
    CIO_TEST: <not set>
    CONDA_DEFAULT_ENV: <not set>
    CONDA_ENVS_PATH: <not set>
    LD_LIBRARY_PATH: <not set>
    PATH: /home/eric/anaconda/bin:/opt/texbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    PYTHONHOME: <not set>
    PYTHONPATH: <not set>
   
    License directories:
        /home/eric/.continuum
        /home/eric/anaconda/licenses
    License files (license*.txt):
    Package/feature end date
