### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by yuyuhu21** [ContinuumIO/anaconda-issues#12789] opened 2022-01-04 14:30 UTC
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'NoneType' object has no attribute 'split'
Traceback
Traceback (most recent call last):
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 79, in __init__
    self._conda_api = CondaAPI()
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1813, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\ruanjianxiazai\huancun\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 662, in set_conda_prefix
    for part in info.get('conda_version').split('.'):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by mccurcio** [comment] 2022-01-05 14:20
**Same**,
but on a Windows 11 machine laptop.
I have even deleted and reinstalled the entire Ind. edition package.

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 10:13
Duplicate of #11780

**Closed by vshevchenko-anaconda** 2023-07-07 10:13 UTC
