### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by shahabraji** [ContinuumIO/anaconda-issues#8617] opened 2018-02-21 02:40 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
python: 3.6.2
language: en
os: Darwin;17.4.0;Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.7
```

**Comment by goanpeca** [comment] 2018-02-21 02:42
Closing as duplicate of #1778

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1778 for more information on how to fix this.**

**Closed by goanpeca** 2018-02-21 02:42 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by shahabraji** [comment] 2018-02-22 20:16
update solves the problem last time. But again I get the same warning. 

     [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
     [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
     [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
     [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
     [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
    ...

Update results in

    $ conda update conda && conda update anaconda-navigator && conda update navigator-updater
    Solving environment: done

    # All requested packages already installed.

    Solving environment: done

    # All requested packages already installed.

    Solving environment: done

    # All requested packages already installed.

**Comment by goanpeca** [comment] 2018-02-22 20:21
@shahabraji please run

```
conda install conda=4.4.10
conda install anaconda-navigator=1.7.0
```

**Comment by shahabraji** [comment] 2018-02-22 21:31
`conda` and `anaconda-navigator` versions were 4.4.10 and 1.7.0 already.

    # packages in environment at /Users///:
    anaconda                  custom                   py36_0  
    anaconda-client           1.6.3                    py36_0  
    anaconda-navigator        1.7.0                    py36_0  
    anaconda-project          0.6.0                    py36_0  
    conda                     4.4.10                   py36_0  
    conda-env                 2.6.0                h36134e3_0  

And it did not solve the issue.
So I updated `anaconda-client` and `anaconda-project`.

And now, I don't get the warning anymore.

**Comment by goanpeca** [comment] 2018-02-22 21:32
You should probably  update anaconda-client to 1.6.11

`conda install anaconda-client=1.6.11`
