### ISSUE TITLE
CondaHTTPError over Ubuntu 14.04 (windows subsystem for linux)

### ISSUE THREAD

**Issue by jbhateja** [ContinuumIO/anaconda-issues#4362] opened 2017-08-18 03:41 UTC
Hi,

I'm getting following error while searching a package. 

PROMPT>conda search urllib
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Read timed out. (read timeout=9.15)",))',),)

Following is output of conda info 

PROMPT>conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/jbhateja/miniconda3  (writable)
    default environment : /home/jbhateja/miniconda3
       envs directories : /home/jbhateja/miniconda3/envs
                          /home/jbhateja/.conda/envs
          package cache : /home/jbhateja/miniconda3/pkgs
                          /home/jbhateja/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-43-Microsoft debian/jessie/sid glibc/2.19
                UID:GID : 1000:1000

I'm working over ubuntu 14.04 (Windows Subsytem for Linux)

PROMPT>lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

Kindly let me know what could be the issue and a resolution for the same.

Thanks,
Jatin Bhateja

**Comment by goanpeca** [comment] 2017-08-18 03:42
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-18 03:42 UTC
Labels: pkg:navigator, reso:duplicate
