### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jayanthkumarak** [ContinuumIO/anaconda-issues#2109] opened 2017-06-09 07:15 UTC
## Main error
Application <b>orange3</b> launch may have produced errors.
## Traceback
```
libpng warning: iCCP: known incorrect sRGB profile
/anaconda/lib/python3.6/site-packages/orangecontrib/spark/widgets/data/spark_to_orange.py:3: RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  from PyQt4.QtGui import QSizePolicy
/anaconda/lib/python3.6/site-packages/orangecontrib/spark/widgets/data/spark_to_orange.py:3: RuntimeWarning: Loaded module AnyQt._backport.QtGui as a substitute for PyQt4.QtGui
  from PyQt4.QtGui import QSizePolicy
/anaconda/lib/python3.6/site-packages/orangecontrib/spark/widgets/ml/spark_ml_dataset.py:9: RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for PyQt4.QtCore
  from PyQt4.QtCore import Qt
/anaconda/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('http://example.com/my-widget/docs/')'
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
python: 3.6.0
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.2.13
```

**Comment by goanpeca** [comment] 2017-06-09 15:26
Closing as duplicate of #1778

**Closed by goanpeca** 2017-06-09 15:26 UTC
Labels: pkg:navigator, reso:duplicate
