### ISSUE TITLE
Output to stdout from first call to sysconfig.get_config_var() with python 3.7.4

### ISSUE THREAD

**Issue by greglandrum** [ContinuumIO/anaconda-issues#11197] opened 2019-08-12 09:30 UTC
### Actual Behavior

```
(blah2) glandrum@otter:~$ python
Python 3.7.4 (default, Aug  9 2019, 18:51:30) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils import sysconfig
>>> sysconfig.get_config_var('Py_ENABLE_SHARED')
7.4.0
0
>>> sysconfig.get_config_var('blah blah')
>>> sysconfig.get_config_var('Py_ENABLE_SHARED')
0
```

This is not a problem with the conda-supplied python v3.7.3 build.

### Expected Behavior

The first call to `sysconfig.get_config_var()` should not output anything to stdout

### Steps to Reproduce

Install python 3.7.4 in conda, run `python -c "from distutils import sysconfig; sysconfig.get_config_var('Py_ENABLE_SHARED')"`

##### Anaconda or Miniconda version:

Not sure any more

##### Operating System:

Ubuntu 18.04

##### `conda info`

<details>

```
conda info

     active environment : blah2
    active env location : /other_linux/home/glandrum/anaconda3/envs/blah2
            shell level : 2
       user config file : /other_linux/home/glandrum/.condarc
 populated config files : /other_linux/home/glandrum/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.5
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : /other_linux/home/glandrum/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/rdkit/linux-64
                          https://conda.anaconda.org/rdkit/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /other_linux/home/glandrum/anaconda3/pkgs
                          /other_linux/home/glandrum/.conda/pkgs
       envs directories : /other_linux/home/glandrum/anaconda3/envs
                          /other_linux/home/glandrum/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-55-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
(blah2) glandrum@otter:~$ conda list --show-channel-urls
# packages in environment at /other_linux/home/glandrum/anaconda3/envs/blah2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
asn1crypto                0.24.0                   py37_0    defaults
attrs                     19.1.0                   py37_1    defaults
backcall                  0.1.0                    py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2019.5.15                     1    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2019.6.16                py37_1    defaults
cffi                      1.12.3           py37h2e261b9_0    defaults
chardet                   3.0.4                 py37_1003    defaults
cryptography              2.7              py37h1ba5d50_0    defaults
cycler                    0.10.0                   py37_0    defaults
dbus                      1.13.6               h746ee38_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py37_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
glib                      2.56.2               hd408876_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.8                      py37_0    defaults
intel-openmp              2019.4                      243    defaults
ipykernel                 5.1.1            py37h39e3cac_0    defaults
ipython                   7.7.0            py37h39e3cac_0    defaults
ipython-sql               0.3.9                 py37_1000    conda-forge
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.1                      py_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10.1                   py37_0    defaults
joblib                    0.13.2                   py37_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.3.1                      py_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.5.0                      py_0    defaults
kiwisolver                1.1.0            py37he6710b0_0    defaults
libboost                  1.67.0               h46d08c1_4    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.0.10               h2733197_2    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
markupsafe                1.1.1            py37h7b6447c_0    defaults
matplotlib                3.1.0            py37h5429711_0    defaults
mistune                   0.8.4            py37h7b6447c_0    defaults
mkl                       2019.4                      243    defaults
mkl-service               2.0.2            py37h7b6447c_0    defaults
mkl_fft                   1.0.12           py37ha843d7b_0    defaults
mkl_random                1.0.2            py37hd81dba3_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
notebook                  6.0.0                    py37_0    defaults
numpy                     1.16.4           py37h7e9f1db_0    defaults
numpy-base                1.16.4           py37hde5b4d6_0    defaults
olefile                   0.46                     py37_0    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
pandas                    0.25.0           py37he6710b0_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.5.0                      py_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    6.1.0            py37h34e0f95_0    defaults
pip                       19.1.1                   py37_0    defaults
pixman                    0.38.0               h7b6447c_0    defaults
prettytable               0.7.2                      py_3    conda-forge
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py-boost                  1.67.0           py37h04863e7_4    defaults
py3dmol                   0.8.0                      py_0    conda-forge
pycparser                 2.19                     py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyrsistent                0.14.11          py37h7b6447c_0    defaults
pysocks                   1.7.0                    py37_0    defaults
python                    3.7.4                h265db76_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
pytz                      2019.1                     py_0    defaults
pyzmq                     18.0.0           py37he6710b0_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 4.5.2                      py_0    defaults
rdkit                     2019.03.3.0      py37hc20afe1_1    rdkit
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py37_0    defaults
scikit-learn              0.21.2           py37hd81dba3_0    defaults
scipy                     1.3.0            py37h7c811a0_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                41.0.1                   py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.12.0                   py37_0    defaults
sqlalchemy                1.3.5            py37h7b6447c_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
sqlparse                  0.3.0                      py_0    defaults
terminado                 0.8.2                    py37_0    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tornado                   6.0.3            py37h7b6447c_0    defaults
traitlets                 4.3.2                    py37_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.33.4                   py37_0    defaults
widgetsnbextension        3.5.0                    py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zeromq                    4.3.1                he6710b0_3    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults
```

</details>

**Comment by junluan** [comment] 2019-08-12 10:46
This is caused by printing gcc version directly in _sysconfigdata_m_linux_x86_64-linux-gnu.py.
This file is in lib/python3.7 directory

**Comment by jjhelmus** [comment] 2019-08-12 14:56
There are some issues with our build of Python 3.7.4.  We will be fixing the issue and releasing updated packages shortly.  Sorry for any inconveniences this has caused.

**Comment by jjhelmus** [comment] 2019-08-12 15:14
Thanks for the report.  The root of this issue was also reported in ContinuumIO/anaconda-issues#11195.  I'm closing this issue so that there is a single issue tracking the problem.  Updates on the fix will be posted to that issue.

**Closed by jjhelmus** 2019-08-12 15:14 UTC
