### ISSUE TITLE
Unable to contact repo to update anaconda/miniconda: SSLError 'unknown protocol'

### ISSUE THREAD

**Issue by DeepGeek** [ContinuumIO/anaconda-issues#5740] opened 2017-09-19 17:17 UTC
Hi,

I had this problem on a Anaconda via a virtual windows instance, replicated it with a fresh miniconda (4.3.2.1) install and I get the same problem.

```
conda update conda

Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'unknown protocol')],)",),),)
```
I have seen similar issues with slightly different errors ('certificate verify failed') but the suggested fix does not seem to work
i.e. `conda config --set ssl_verify False` does not solve the problem.

I can reach the URL https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2 in Chrome or IE.

Running conda update command as administrator gets the same error.

The odd thing is I can update conda and install packages on another 'real'/physical machine from the same network.

This is a clean miniconda install but the conda list output is below.

Any help or workarounds very gratefully accepted!

```
>conda list
# packages in environment at C:\Miniconda3:
#
asn1crypto                0.22.0                   py36_0
cffi                      1.10.0                   py36_0
conda                     4.3.21                   py36_0
conda-env                 2.6.0                         0
console_shortcut          0.1.1                    py36_1
cryptography              1.8.1                    py36_0
idna                      2.5                      py36_0
menuinst                  1.4.7                    py36_0
openssl                   1.0.2l                   vc14_0  [vc14]
packaging                 16.8                     py36_0
pip                       9.0.1                    py36_1
pycosat                   0.6.2                    py36_0
pycparser                 2.17                     py36_0
pyopenssl                 17.0.0                   py36_0
pyparsing                 2.1.4                    py36_0
python                    3.6.1                         2
pywin32                   220                      py36_2
requests                  2.14.2                   py36_0
ruamel_yaml               0.11.14                  py36_1
setuptools                27.2.0                   py36_1
six                       1.10.0                   py36_0
vs2015_runtime            14.0.25123                    0
wheel                     0.29.0                   py36_0
```

**Comment by goanpeca** [comment] 2017-09-19 17:21
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-19 17:21 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by DeepGeek** [comment] 2017-09-19 17:39
Thanks for your reply. I'm not sure this is a duplicate of 1932. I do not believe that I have installed Navigator. I am looking to leverage miniconda to minimise the installed footprint. Is that still achievable?

Here are the errors to the suggested lines from Anaconda Command Prompt:

```
>conda update anaconda-navigator

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Miniconda3
  package name: anaconda-navigator
>conda update navigator-updater

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Miniconda3
  package name: navigator-updater
```

**Comment by fonnesbeck** [comment] 2017-09-20 15:02
conda update conda                    
The same thing happens when I try to update conda:

```
PackageNotInstalledError: Package is not installed in prefix.
  prefix: /Users/fonnescj/anaconda3/envs/dev
  package name: conda
```

**Comment by DeepGeek** [comment] 2017-09-20 16:08
Figured it out - there was Websense endpoint protection blocking the SSL connection on that server. Once that site was permitted, good to go.

**Comment by fonnesbeck** [comment] 2017-09-20 16:09
@DeepGeek where is this located? condarc?

**Comment by DeepGeek** [comment] 2017-09-20 19:45
It was a program installed to protect the server by only allowing permitted programs access to the network in certain ways. It didn't know about anaconda and so blocked python/openssl as a threat: I needed to get the settings changed on this blocking agent to let the requests through.

So no changes were needed to any anaconda settings.

I should have thought about this sooner, since in the past anaconda has also been blocked from the local disk  by the ransomware detection software because it rapidly reads, writes and deletes lots files whenever you do a core package update.

**Comment by khalsa13** [comment] 2017-10-10 13:42
conda update conda                    

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /Users/fonnescj/anaconda3/envs/dev
  package name: conda
I am getting this error .Please help to remove it.
