### ISSUE TITLE
[Navigator Error] Spyder. I read that in write in terminal export EVENT_NOKQUEUE=1 will solve the problem, but it didn't

### ISSUE THREAD

**Issue by NguyenTri91** [ContinuumIO/anaconda-issues#3309] opened 2017-07-18 21:52 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

```
## System information
```
python: 3.6.1
language: en
os: Darwin;16.6.0;Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```
Are there any one tell me: 'How to write in terminal `export EVENT_NOKQUEUE=1`'?
<img width="1680" alt="error1" src="https://user-images.githubusercontent.com/30273900/28341454-c2126694-6c4e-11e7-9486-1eeab7249dc0.png">

It's seem stupid with someone but this is my first time using Mac. Please help me.

**Comment by goanpeca** [comment] 2017-07-18 21:52
Closing as duplicate of #1778

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-18 21:52 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by goanpeca** [comment] 2017-07-19 00:06
@NguyenTri91 this is not an error that in anyway affects the programs, so you can ignore it.
