### ISSUE TITLE
Unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by duncankmckinnon** [ContinuumIO/anaconda-issues#8825] opened 2018-03-10 18:02 UTC
When this happened I had just downloaded r-tensorflow in a new environment

### Actual Behavior
![capture](https://user-images.githubusercontent.com/13010582/37245183-4db66b2a-2449-11e8-9126-5290bff14fc7.PNG)

### Expected Behavior
Anaconda Navigator opens

### Steps to Reproduce
Running Anaconda Navigator

##### Anaconda or Miniconda version: 
Anaconda 3 5.1

##### Operating System: 
Windows 10

##### `conda info`
![capture1](https://user-images.githubusercontent.com/13010582/37245309-fc4f6bc2-244a-11e8-9171-c6b7a6e9fdcf.PNG)

##### `conda list --show-channel-urls`
```
Not accessible, won't run (see above screenshot)
```

**Comment by goanpeca** [comment] 2018-03-11 18:03
@kalefranz ?

**Comment by goanpeca** [comment] 2018-03-11 18:03
@duncankmckinnon seems like a problem with conda, perhaps you could provide the conda info error on a new issue over conda

https://github.com/conda/conda/issues

**Comment by davidcamachotrujillo** [comment] 2018-03-14 09:08
I am having exactly the same behavior.
Anaconda give me the following message:
(Additionally, the same "conda" problem, it does not start.)
But from the windows menu, I can run the Jupiter Notebook I was working with.

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2018-03-14 13:57
@davidcamachotrujillo this is a conda issues. Navigator depends on conda. Once the problem is fixed for conda, it will be fixed for Navigator.

Please see https://github.com/conda/conda/issues for a similar issue with conda, or open a new issue and fill in the requested information on that new issue.

**Comment by kalefranz** [comment] 2018-03-19 17:27
I doubt this issue with with Anaconda Navigator.  Although I'm not sure there's an issue with conda either.  Feel free to file a new issue at https://github.com/conda/conda/issues, and include detailed, step-by-step instructions on how the problem you're encountering can be independently reproduced.

**Closed by kalefranz** 2018-03-19 17:27 UTC
Labels: pending:feedback, pkg: conda
