### ISSUE TITLE
Navigator Error : An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by RaviBodkai** [ContinuumIO/anaconda-issues#6514] opened 2017-10-09 13:05 UTC
Main Error

psutil.AccessDenied (pid=4100)
Traceback

Traceback (most recent call last):
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=4100)

**Comment by goanpeca** [comment] 2017-10-09 17:46
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-09 17:46 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by RaviBodkai** [comment] 2017-10-23 23:47
Hi,
Have got the issue. Issue not resolved. Please help. 

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error


byte indices must be integers or slices, not str


Traceback


Traceback (most recent call last):
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
Thanks & RegardsRavi Bodkai(C):+1-416-428-3430


Regards Ravi 

    On ‎Monday‎, ‎October‎ ‎09‎, ‎2017‎ ‎01‎:‎46‎:‎59‎ ‎PM‎ ‎EDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
See issue #1984 for more information on how to fix this.

Closing as duplicate of #1984

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:
$ conda update anaconda-navigator
$ conda update navigator-updater

**Comment by RaviBodkai** [comment] 2018-01-20 06:38
Hi,
This is my first install of Anaconda on a new PC. I get the following errors when I open the Anaconda Navigator.
Please advise. 

Traceback (most recent call last):
File "C:\Users\Ravi\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\Ravi\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Ravi\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\Ravi\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\Ravi\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\Ravi\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "C:\Users\Ravi\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=10828)


Regards Ravi 

    On Monday, October 23, 2017, 7:43:25 PM EDT, ravi <ravi_bodkai@yahoo.com> wrote:  
 
 Hi,
Have got the issue. Issue not resolved. Please help. 

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error


byte indices must be integers or slices, not str


Traceback


Traceback (most recent call last):
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "C:\Users\Ravi\Anaconda3\envs\tensorflow\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
Thanks & RegardsRavi Bodkai(C):+1-416-428-3430


Regards Ravi 

    On ‎Monday‎, ‎October‎ ‎09‎, ‎2017‎ ‎01‎:‎46‎:‎59‎ ‎PM‎ ‎EDT, Gonzalo Peña-Castellanos <notifications@github.com> wrote:  
 
 
See issue #1984 for more information on how to fix this.

Closing as duplicate of #1984

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:
$ conda update anaconda-navigator
$ conda update navigator-updater
