### ISSUE TITLE
Navigator Start Error - pid=2380

### ISSUE THREAD

**Issue by chia1cdef** [ContinuumIO/anaconda-issues#8094] opened 2018-01-11 09:12 UTC
Hello!

My Anaconda was installed on January 2 this year and had performed flawlessly. I tried to launch the navigator today and encounter the following error message.

Traceback (most recent call last):
File "d:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 636, in wrapper
return fun(self, *args, **kwargs)
File "d:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 706, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "d:\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "d:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "d:\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "d:\Anaconda3\lib\site-packages\psutil\__init__.py", line 721, in cmdline
return self._proc.cmdline()
File "d:\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=2380)

I thought something was corrupted. Uninstalled the software, then downloaded a new copy to install. But it gives the same error message. Following one solution published in summer last year by typing the following command in a prompt window on my windows 7 system. 

conda update anaconda-navigator

I still have no luck. Appreciate any help. Thanks in advance for your attention.

**Comment by goanpeca** [comment] 2018-01-11 14:30
Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #1984 for more information on how to fix this.**

Or you can run on the Terminal or Anaconda prompt:

```
ancaonda-navigator --reset
```

**Closed by goanpeca** 2018-01-11 14:30 UTC

**Comment by chia1cdef** [comment] 2018-01-11 16:48
Thank you so much. Yes, followed your suggestions and the issue resolved.
