### ISSUE TITLE
Error with Anaconda Navigator

### ISSUE THREAD

**Issue by trannamishere** [ContinuumIO/anaconda-issues#3137] opened 2017-07-13 08:13 UTC
![image](https://user-images.githubusercontent.com/30142651/28156512-4812c82c-67dd-11e7-9813-459ed65bfff8.png)
This is what I get:
Traceback (most recent call last):
File "C:\Users\Dell\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
return fun(self, *args, **kwargs)
File "C:\Users\Dell\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Dell\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\Dell\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Users\Dell\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Users\Dell\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "C:\Users\Dell\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=3464)

I don't know how to fix it. I've reinstalled Anaconda and it has still has this error.( sorry for my bad English)

**Comment by trannamishere** [comment] 2017-07-13 08:16
Can someone help me please? Thanks you.

**Comment by goanpeca** [comment] 2017-07-13 16:43
Closing as duplicate of #1984. Go to #1984 for a solution!

---

Please update to the latest version of Navigator.

on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-13 16:43 UTC
