### ISSUE TITLE
Anaconda should include PySide-tools

### ISSUE THREAD

**Issue by lyonj** [ContinuumIO/anaconda-issues#35] opened 2013-11-04 04:08 UTC
As described at the link below, PySide-tools package is required to develop UIs for PySide when using Qt Creator.

http://qt-project.org/wiki/QtCreator_and_PySide

It would be nice to have these tools included in Anaconda to avoid having to install them separately.

**Comment by ccordoba12** [comment] 2015-04-11 17:37
This is a duplicate of #170, already fixed.

**Closed by ccordoba12** 2015-04-11 17:37 UTC
Labels: duplicate
