### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by 217aniruddhapal** [ContinuumIO/anaconda-issues#5445] opened 2017-09-13 11:30 UTC
Navigator Error

An unexpected error occurred on Navigator start-up
Main Error

byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-09-13 14:43
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-13 14:43 UTC
