### ISSUE TITLE
sqlite3 in Python 3 should have enable_load_extension

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1212] opened 2016-11-02 15:50 UTC
_From @tiagofassoni on October 16, 2016 17:12_

It is disabled in Conda distribution, but it is essential for using geodjango. If the default option shouldn't be changed, at least there should be a package I could swap. 

_Copied from original issue: conda/conda#3644_

**Comment by nehaljwani** [comment] 2017-05-18 20:18
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1287

**Closed by nehaljwani** 2017-05-18 20:18 UTC
Labels: reso:duplicate, tag:package-request
