### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Aramatis** [ContinuumIO/anaconda-issues#7378] opened 2017-11-18 19:16 UTC
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Package missing in current win-64 channels: 
  - rstudio ==1.0.153
```
## System information
```
python: 3.6.1
language: es_CL
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-11-19 04:25
**See issue #6970 for more information on how to fix this issue.**

---

Closing as duplicate of #6970

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-19 04:25 UTC
