### ISSUE TITLE
Anaconda start-up fails "TypeError: byte indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by juhhha** [ContinuumIO/anaconda-issues#5022] opened 2017-09-04 21:41 UTC
Hi,

I am running Windows 10 and installed Anaconda 4.4.0 with Python 3.6

Starting Anaconda Navigator fails, How to fix this? I tried to run already in Anaconda Prompt
conda update anaconda-navigator

Error message here:
Traceback (most recent call last):
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
window = run_app(splash)
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
window = MainWindow(splash=splash)
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
self.api = AnacondaAPI()
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1214, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
self._conda_api = CondaAPI()
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1654, in CondaAPI
CONDA_API = _CondaAPI()
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 345, in __init__
self.set_conda_prefix()
File "C:\Users\cc\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 494, in set_conda_prefix
self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2017-09-04 21:44
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-04 21:44 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by juhhha** [comment] 2017-09-04 21:55
Updates had no impact


(C:\Users\cc\Anaconda3) C:\Users\cc>conda update anaconda-navigator
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\cc\Anaconda3:
#
anaconda-navigator        1.6.4                    py36_0

(C:\Users\cc\Anaconda3) C:\Users\cc>conda update navigator-updater
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\cc\Anaconda3:
#
navigator-updater         0.1.0                    py36_0
