### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by prashantsinha201** [ContinuumIO/anaconda-issues#9089] opened 2018-04-04 08:24 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 13:54:01.320 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 13:54:02.619 NotebookApp] Serving notebooks from local directory: /home/ussr
[I 13:54:02.619 NotebookApp] 0 active kernels 
[I 13:54:02.619 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=4b58eac1c86caf43c7fffb6da92349b00956c0f69b119dda
[I 13:54:02.619 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:54:02.623 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=4b58eac1c86caf43c7fffb6da92349b00956c0f69b119dda
[I 13:54:03.101 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[8642:8679:0404/135403.152438:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.13.0-37-generic;#42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.0
```

**Comment by goanpeca** [comment] 2018-04-04 14:37
Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #2098 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-04-04 14:37 UTC
Labels: pkg:navigator, reso:duplicate
