### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by belieftry** [ContinuumIO/anaconda-issues#1899] opened 2017-06-03 04:20 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-canary/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

```
## System information
```
python: 3.6.1
language: zh_TW
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-06-03 17:18
@kalefranz, any thoughts?

**Comment by goanpeca** [comment] 2017-06-21 16:01
Closing as duplicate of #1932

Please update to the latest version of Navigator.

On Navigator click on the update button on the top right of the interface or
on the terminal type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-06-21 16:01 UTC
Labels: pkg:navigator, reso:duplicate
