### ISSUE TITLE
Anaconda Navigator not opening "An unexpected error occurred on Navigator start-up"

### ISSUE THREAD

**Issue by creatlyre** [ContinuumIO/anaconda-issues#13183] opened 2023-04-26 13:25 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/anaconda/navigator/) and didn't see anything to help

### What happened?

When the Anaconda Navigator is opening I've got the message below. I tried to re-install anaconda. 

```
Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

'list' object has no attribute 'get'

Traceback

Traceback (most recent call last):
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 59, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 219, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1085, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 69, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 1735, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 429, in __init__
    self.set_conda_prefix(info=get_conda_info(allow_fixes=True))
  File "C:\Users\Wojciech\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api\__init__.py", line 578, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')  # str
AttributeError: 'list' object has no attribute 'get'

```

When running anaconda prompt:
`'"C:\Users\Wojciech\AppData\Local\Temp\tmpc4jcc0v7.bat[0x7FFB2FCF4A80]"' is not recognized as an internal or external command,
operable program or batch file.
Could Not Find C:\Users\Wojciech\AppData\Local\Temp\tmpc4jcc0v7.bat[0x7FFB2FCF4A80]`

### Conda info

```shell
conda not working after reinstalling anaconda navigator

'conda' is not recognized as an internal or external command,
operable program or batch file.
```

### Conda config

```shell
'conda' is not recognized as an internal or external command,
operable program or batch file.
```

### Conda list

```shell
'conda' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Ruparani777** [comment] 2023-05-17 11:19
I would like to work on it.
Please assign to me 
Thanks

**Comment by vshevchenko-anaconda** [comment] 2023-07-07 10:40
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/11780

**Closed by vshevchenko-anaconda** 2023-07-07 10:40 UTC
Labels: type-bug, pkg-navigator
