### ISSUE TITLE
mkl ordinal 242

### ISSUE THREAD

**Issue by shoks** [ContinuumIO/anaconda-issues#10322] opened 2018-11-12 11:54 UTC
hi i'm having an issue with anaconda matplotlib and sometime numpy due to mkl the error ouput is missing 242 ordinal in the library

**Comment by msarahan** [comment] 2018-11-12 16:22
duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/10182

**Closed by msarahan** 2018-11-12 16:22 UTC
