### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mrsagitt** [ContinuumIO/anaconda-issues#6742] opened 2017-10-18 18:26 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>psutil.AccessDenied (pid=1580)
## Traceback
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\ProgramData\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\ProgramData\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=1580)

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: en_US
python: 2.7.13
os: Windows;10;10.0.15063;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-10-18 18:31
**See Issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-18 18:31 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by mrsagitt** [comment] 2017-10-18 19:28
i have uninstalled anaconda2 4.4.0 version and installed anaconda2 5.0.0 just now. Still getting the same error of denied access:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\ProgramData\Anaconda2\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "C:\ProgramData\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=1580)

**Comment by goanpeca** [comment] 2017-10-19 14:01
@mrsagitt you should use `Only for current user` install also. See Issue #1984 for more information on how to fix this.

**Comment by mrsagitt** [comment] 2017-10-21 06:52
Guys,

The issue was Windows update, not Anaconda. It only surfaced through Anaconda at first but then I had also problem with installing packages in R / RStudio - I was getting access denied error.
Originally I had Anaconda 4.4.0 installed and it ran without any problems only to last Wednesday. Prior to this Windows 10 had installed security update (unfortunately I cannot remember KB number as it is gone now) and then problems started. After uninstalling this Win10 update all is back to normal - Anaconda Navigator launches without any problems, so does R.
thanks for your help.
