### ISSUE TITLE
spyder crashes "You should import from qtconsole instead."

### ISSUE THREAD

**Issue by lyndb** [ContinuumIO/anaconda-issues#420] opened 2015-08-24 16:25 UTC
Spyder under anaconda and anaconda3 are now not launching for me on Ubuntu 14.04 LTS 64 bit or on OS X 10.10.5.  Trying to launch it from the command prompt on Linux gives me:

xxx@xdog:~$ spyder
/home/lynd/anaconda3/lib/python3.4/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)

I get a crashed pop up message that indicates I should try python spyder --reset, but I get a "file not found" error for spyder.  spyder is in my PATH.  Moving the ini files from the .spyder2 or from .spyder2-py directories makes no difference.

Spyder won't launch from the launcher. ipython and python both launch from the command prompt.

**Comment by ccordoba12** [comment] 2015-08-24 16:34
This is a duplicate of issue spyder-ide/spyder#2608. It'll be fixed once Spyder 2.3.6 is released (in a couple of days)

**Closed by ccordoba12** 2015-08-24 16:34 UTC
Labels: duplicate

**Comment by lyndb** [comment] 2015-08-24 16:37
Thanks!
