### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by aayushjn2** [ContinuumIO/anaconda-issues#4071] opened 2017-08-09 19:50 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000218354F2EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))",),)

```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;10;10.0.10586;AMD64;AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.23
```

**Comment by goanpeca** [comment] 2017-08-09 19:50
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-09 19:50 UTC
Labels: pkg:navigator, reso:duplicate
