### ISSUE TITLE
conda activate tensorflow-1.5 ERROR: This cross-compiler package contains no program /nfs/mercury-09/u15/pkgmgr/aida/miniconda3/envs/tensorflow-1.5/bin/x86_64-conda_cos6-linux-gnu-c++/envs/tensorflow-1.5/bin/x86_64-conda_cos6-linux-gnu-c++

### ISSUE THREAD

**Issue by adalisan** [ContinuumIO/anaconda-issues#11208] opened 2019-08-16 15:30 UTC
<!--

### Actual Behavior

conda install packages breaks the conda environment. conda environment activation fails. command return error code

### Expected Behavior

conda environment should be activated
### Steps to Reproduce
- Have a working environment 
- `conda env create -n tensorflow-gpu-1.5 -f gpu.yaml`

where gpu.yaml includes
```
name: tensorflow-1.5-gpu
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - keras-gpu=2.0.2
  - mccabe=0.6.1
  - pygpu=0.7.6
```
others dependencies not included
These packages are installed
```

Downloading and Extracting Packages
gxx_linux-64-7.2.0   | 5 KB      | ######################################################### | 100%
mccabe-0.6.1         | 14 KB     | ######################################################### | 100%
keras-gpu-2.0.2      | 341 KB    | ######################################################### | 100%
theano-1.0.2         | 3.7 MB    | ######################################################### | 100%
Preparing transaction: done
Executing transaction: done
#
```

```
conda activate tensorflow-gpu-1.5
ERROR: This cross-compiler package contains no program <ROOT>/miniconda3/envs/tensorflow-1.5-gpu/bin/x86_64-conda_cos6-linux-gnu-c++
$ conda deactivate
ERROR: This cross-compiler package contains no program /nfs/mercury-12/u15/sadali/anaconda3/envs/tensorflow-1.5-gpu/bin/x86_64-conda_cos6-linux-gnu-c++
ERROR: activate-gxx_linux-64.sh failed, see above for details
$ conda activate tensorflow-1.5
ERROR: This cross-compiler package contains no program <ROOT>/miniconda3/envs/tensorflow-1.5/bin/x86_64-conda_cos6-linux-gnu-c++
```

##### Operating System:
Scientific Linux 6.10 or Centos7
##### `conda info`

```

     active environment : tensorflow-1.5-gpu
    active env location : <ROOT>/envs/tensorflow-1.5-gpu
            shell level : 1
       user config file : /home/sadali/.condarc
 populated config files : /home/sadali/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.7
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : <ROOT>  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /nfs/mercury-12/u15/sadali/anaconda3/pkgs
       envs directories : /nfs/mercury-12/u15/sadali/anaconda3/envs
                          /home/sadali/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Linux/3.10.0-862.2.3.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 8513:34
             netrc file : None

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at <ROOT>/envs/tensorflow-1.5-gpu:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    anaconda
absl-py                   0.6.1                    py36_0    anaconda
asn1crypto                0.24.0                   py36_0    anaconda
astroid                   2.2.5                    py36_0    anaconda
blas                      1.0                    openblas    anaconda
bleach                    1.5.0                    py36_0    anaconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2019.6.16                py36_1    anaconda
cffi                      1.12.3           py36h2e261b9_0    anaconda
chardet                   3.0.4                 py36_1003    anaconda
cryptography              2.3.1            py36h1ba5d50_2    defaults
cudatoolkit               9.0                  h13b8566_0    anaconda
cudnn                     7.6.0                 cuda9.0_0    anaconda
cupti                     9.0.176                       0    anaconda
cymem                     2.0.2            py36hfd86e86_0    anaconda
cytoolz                   0.9.0.1          py36h14c3975_1    anaconda
dill                      0.2.8.2                  py36_0    anaconda
expat                     2.2.6                he6710b0_0    anaconda
ffmpeg                    4.0                  hcdf2ecd_0    anaconda
fftw                      3.3.8                h7b6447c_3    anaconda
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.9.1                h8a8886c_1    anaconda
future                    0.17.1                   py36_0    anaconda
gdk-pixbuf                2.36.12           h7a26e22_1003    conda-forge
gettext                   0.19.8.1             h9b4dc7a_1    anaconda
ghostscript               9.22              hf484d3e_1001    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gobject-introspection     1.58.2          py36h5503ade_1002    conda-forge
graphite2                 1.3.13               h23475e2_0    anaconda
graphviz                  2.40.1               h0dab3d1_0    conda-forge
gxx_linux-64              7.2.0                        24    anaconda
h5py                      2.8.0            py36h989c5e5_3    anaconda
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf5                      1.10.2               hba1933b_1    anaconda
html5lib                  0.9999999                py36_0    anaconda
icu                       58.2                 h211956c_0    anaconda
idna                      2.7                      py36_0    anaconda
imagemagick               7.0.8_53        pl526h39023e4_0    conda-forge
intel-openmp              2019.4                      243    anaconda
isodate                   0.6.0                      py_1    anaconda
isort                     4.3.21                   py36_0    anaconda
jbig                      2.1                  hdba287a_0    anaconda
jpeg                      9c                h14c3975_1001    conda-forge
keepalive                 0.5                        py_1    conda-forge
keras-gpu                 2.0.2                    py36_0    anaconda
lame                      3.100             h14c3975_1001    conda-forge
lazy-object-proxy         1.4.1            py36h7b6447c_0    anaconda
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libcroco                  0.6.13               h8d621e5_0    conda-forge
libedit                   3.1.20170329         h6b74fdf_2    anaconda
libffi                    3.2.1                h4deb6c0_3    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libgpuarray               0.7.6                h14c3975_0    anaconda
libiconv                  1.15                 h63c8f33_5    anaconda
liblapack                 3.8.0               11_openblas    conda-forge
libopenblas               0.3.6                h5a2b251_1    anaconda
libopus                   1.3                  h7b6447c_0    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libprotobuf               3.8.0                hd408876_0    anaconda
librsvg                   2.44.14              h11c8777_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.0.10               h2733197_2    anaconda
libtool                   2.4.6                h7b6447c_5    anaconda
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvpx                    1.7.0                h439df22_0    anaconda
libwebp                   1.0.1                h8e7db2f_0    anaconda
libxcb                    1.13                 h1bed415_1    anaconda
libxml2                   2.9.9                hea5a465_1    anaconda
mad                       0.15.1b              he1b5a44_0    conda-forge
mako                      1.0.10                     py_0    anaconda
markdown                  3.0.1                    py36_0    anaconda
markupsafe                1.0              py36h14c3975_1    anaconda
mccabe                    0.6.1                    py36_1    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.0.2            py36h7b6447c_0    anaconda
msgpack-numpy             0.4.3.2                  py36_0    anaconda
msgpack-python            0.6.1            py36hfd86e86_1    anaconda
murmurhash                1.0.1            py36he6710b0_0    anaconda
ncurses                   6.1                  he6710b0_1    anaconda
nomkl                     3.0                           0    anaconda
numpy                     1.15.4           py36h99e49ec_0    anaconda
numpy-base                1.15.4           py36h2f8d375_0    anaconda
openblas                  0.3.6                         1    anaconda
openblas-devel            0.3.6                         1    anaconda
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1b               h7b6447c_1    anaconda
pandas                    0.24.2           py36he6710b0_0    anaconda
pango                     1.40.14           he7ab937_1005    conda-forge
pcre                      8.43                 he6710b0_0    anaconda
pep8                      1.7.1                    py36_0    anaconda
perl                      5.26.2               h14c3975_0    anaconda
perl-carp-assert          0.21                    pl526_0    conda-forge
pip                       19.1.1                   py36_0    anaconda
pixman                    0.38.0               h7b6447c_0    anaconda
pkg-config                0.29.2               h1bed415_8    anaconda
plac                      0.9.6                    py36_0    anaconda
preshed                   2.0.1            py36he6710b0_0    anaconda
protobuf                  3.8.0            py36he6710b0_0    anaconda
pycparser                 2.19                     py36_0    anaconda
pygpu                     0.7.6            py36h035aef0_0    anaconda
pylint                    2.3.1                    py36_0    anaconda
pyopenssl                 19.0.0                   py36_0    anaconda
pyparsing                 2.4.0                      py_0    anaconda
pysocks                   1.6.8                    py36_0    anaconda
python                    3.6.8                h0371630_0    anaconda
python-crfsuite           0.9.6            py36hf484d3e_0    anaconda
python-dateutil           2.8.0                    py36_0    anaconda
pytz                      2019.1                     py_0    anaconda
pyyaml                    3.13             py36h14c3975_0    anaconda
rdflib                    4.2.2                 py36_1000    conda-forge
readline                  7.0                  h7b6447c_5    anaconda
regex                     2019.06.05       py36h7b6447c_0    anaconda
requests                  2.20.1                   py36_0    anaconda
scipy                     1.1.0            py36he2b7bc3_2    anaconda
setuptools                41.0.1                   py36_0    anaconda
six                       1.12.0                   py36_0    anaconda
sox                       14.4.2            h27f72bc_1013    conda-forge
spacy                     2.0.16           py36h962f231_0    anaconda
sparqlwrapper             1.8.2                 py36_1000    conda-forge
sqlite                    3.26.0               h7b6447c_0    anaconda
tensorflow-gpu            1.5.0                         0    anaconda
tensorflow-gpu-base       1.5.0            py36h8a131e3_0    anaconda
tensorflow-tensorboard    1.5.1            py36hf484d3e_1    anaconda
termcolor                 1.1.0                    py36_1    anaconda
theano                    1.0.2            py36h6bb024c_0    anaconda
thinc                     6.12.1           py36h22eb022_0    anaconda
tk                        8.6.9             hed695b0_1002    conda-forge
toolz                     0.10.0                     py_0    anaconda
tqdm                      4.32.1                     py_0    anaconda
typed-ast                 1.3.4            py36h7b6447c_0    anaconda
ujson                     1.35             py36h14c3975_0    anaconda
urllib3                   1.23                     py36_0    anaconda
webencodings              0.5.1                    py36_1    anaconda
werkzeug                  0.14.1                   py36_0    anaconda
wheel                     0.33.4                   py36_0    anaconda
wrapt                     1.10.11          py36h14c3975_2    anaconda
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.8                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.12            h14c3975_1002    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4    anaconda
yaml                      0.1.7                h96e3832_1    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.3.7                h0b5b093_0    anaconda

```

</details>

**Comment by jjhelmus** [comment] 2019-08-21 15:00
Duplicate of #11209

**Closed by jjhelmus** 2019-08-21 15:00 UTC
