### ISSUE TITLE
MySQLdb and mysql.connector are incompatible with openssl 1.1.1a

### ISSUE THREAD

**Issue by nehaljwani** [ContinuumIO/anaconda-issues#10646] opened 2019-02-18 06:46 UTC
_From @GoldstHa on February 17, 2019 22:15_

Packages:
    1. mysql.connector (mysql-connector-python) 8.0.13
    2. openssl 1.1.1a
When attempting to connect to an SSL enabled MySQL server I get:
`InterfaceError: 2026 (HY000): SSL connection error: SSL_CTX_set_tmp_dh failed`

Packages:
    1. MySQLdb (mysqlclient) 1.3.14
    2. openssl 1.1.1a
When attempting to connect to an SSL enabled MySQL server I get:
`OperationalError: (2006, 'SSL connection error: SSL_CTX_set_tmp_dh failed')`

When I downgrade to openssl 1.0.2p both packages are able to connect and I'm able to verify that my connection is encrypted. The conda package manager should be aware of this incompatibility when installing those packages.

_Copied from original issue: conda/conda#8299_

**Comment by nehaljwani** [comment] 2019-02-18 06:47
@GoldstHa Could you please share the output for: `conda list --show-channel-urls` when you have openssl 1.1.1a installed? I am interested in the version/build of certain packages, including mysql-connector-c

**Comment by GoldstHa** [comment] 2019-02-18 06:57
```
(base) <username>@<hostname>:~$ conda list --show-channel-urls
# packages in environment at /Users/<username>/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  5.3.0                    py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.6                    py37_0    defaults
anaconda-project          0.8.2                    py37_0    defaults
appdirs                   1.4.3            py37h28b3542_0    defaults
appnope                   0.1.0                    py37_0    defaults
appscript                 1.0.1            py37h1de35cc_1    defaults
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.1.0                    py37_0    defaults
astropy                   3.0.4            py37h1de35cc_0    defaults
atomicwrites              1.2.1                    py37_0    defaults
attrs                     18.2.0           py37h28b3542_0    defaults
automat                   0.7.0                    py37_0    defaults
autopep8                  1.4.3                    py37_0    defaults
babel                     2.6.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                      py37_1    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
beautifulsoup4            4.6.3                    py37_0    defaults
bitarray                  0.8.3            py37h1de35cc_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py37_0    defaults
bleach                    3.0.2                    py37_0    defaults
blosc                     1.14.4               hd9629dc_0    defaults
bokeh                     0.13.0                   py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h6174b99_1    defaults
chardet                   3.0.4                    py37_1    defaults
click                     7.0                      py37_0    defaults
cloudpickle               0.6.1                    py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
conda                     4.6.4                    py37_0    defaults
conda-build               3.17.6                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
constantly                15.1.0           py37h28b3542_0    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.5              py37ha12b0ac_0    defaults
curl                      7.63.0            ha441bb4_1000    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.2           py37h0a44026_0    defaults
cytoolz                   0.9.0.1          py37h1de35cc_1    defaults
dask                      0.19.1                   py37_0    defaults
dask-core                 1.0.0                    py37_0    defaults
datashape                 0.5.4                    py37_1    defaults
dbus                      1.13.2               h760590f_1    defaults
decorator                 4.3.0                    py37_0    defaults
defusedxml                0.5.0                    py37_1    defaults
distributed               1.25.1                   py37_0    defaults
django                    2.1.4                    py37_0    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.2.3                    py37_2    defaults
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py37h1de35cc_2    defaults
filelock                  3.0.10                   py37_0    defaults
flask                     1.0.2                    py37_1    defaults
flask-cors                3.0.7                    py37_0    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.3.7            py37h1de35cc_1    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py37_1    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py37h6ef4df4_2    defaults
greenlet                  0.4.15           py37h1de35cc_0    defaults
h5py                      2.8.0            py37h878fce3_3    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
hyperlink                 18.0.0                   py37_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.4.1                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.6                      py37_0    defaults
incremental               17.5.0                   py37_0    defaults
intel-openmp              2019.1                      144    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.2.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.2                    py37_0    defaults
isort                     4.3.4                    py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py37_0    defaults
jedi                      0.13.2                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab                0.35.3                   py37_0    defaults
jupyterlab_launcher       0.13.1                   py37_0    defaults
jupyterlab_server         0.2.0                    py37_0    defaults
keyring                   17.0.0                   py37_0    defaults
kiwisolver                1.0.1            py37h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.3.1            py37h1de35cc_2    defaults
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.63.0            h051b688_1000    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_0    defaults
libpng                    1.6.35               ha441bb4_0    defaults
libprotobuf               3.6.0                hd9629dc_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.9                hcb84e12_2    defaults
libxml2                   2.9.8                hab757c2_1    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvmlite                  0.26.0           py37h8c7ce04_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.2.5            py37hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.1.0            py37h1de35cc_0    defaults
matplotlib                2.2.3            py37h54f8f79_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h1de35cc_0    defaults
mkl                       2019.1                      144    defaults
mkl-service               1.1.2            py37h6b9c3cc_5    defaults
mkl_fft                   1.0.4            py37h5d10147_1    defaults
mkl_random                1.0.1            py37h5d10147_1    defaults
more-itertools            4.3.0                    py37_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.5.6            py37h04f5b5a_1    defaults
multipledispatch          0.6.0                    py37_0    defaults
mysql-connector-c         6.1.11               hccea1a4_0    defaults
mysql-connector-python    8.0.13           py37h3febbb0_0    defaults
mysqlclient               1.3.14           py37h1de35cc_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.3.1                    py37_0    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
networkx                  2.2                      py37_1    defaults
nltk                      3.4                      py37_1    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  5.7.4                    py37_0    defaults
numba                     0.39.0           py37h6440ff4_0    defaults
numexpr                   2.6.8            py37h1dc9127_0    defaults
numpy                     1.15.1           py37h6a91979_0    defaults
numpy-base                1.15.1           py37h8a80b8c_0    defaults
numpydoc                  0.8.0                    py37_0    defaults
odo                       0.5.1                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  2.5.12                   py37_0    defaults
openssl                   1.1.1a               h1de35cc_0    defaults
packaging                 18.0                     py37_0    defaults
pandas                    0.23.4           py37h6440ff4_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.1                    py37_0    defaults
partd                     0.3.9                    py37_0    defaults
path.py                   11.5.0                   py37_0    defaults
pathlib2                  2.3.3                    py37_0    defaults
patsy                     0.5.0                    py37_0    defaults
pcre                      8.42                 h378b8a2_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.6.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    5.3.0            py37hb68e598_0    defaults
pip                       18.1                     pypi_0    pypi
pkginfo                   1.4.2                    py37_1    defaults
pluggy                    0.8.0                    py37_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.5.0                    py37_0    defaults
prompt_toolkit            2.0.7                    py37_0    defaults
protobuf                  3.6.0            py37h0a44026_0    defaults
psutil                    5.4.8            py37h1de35cc_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py                        1.7.0                    py37_0    defaults
py-lief                   0.9.0            py37hd4eaf27_0    defaults
pyasn1                    0.4.4            py37h28b3542_0    defaults
pyasn1-modules            0.2.2                    py37_0    defaults
pycodestyle               2.4.0                    py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37h1de35cc_9    defaults
pycurl                    7.43.0.2         py37ha12b0ac_0    defaults
pyflakes                  2.0.0                    py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pyhamcrest                1.9.0                    py37_2    defaults
pylint                    2.2.2                    py37_0    defaults
pylint-django             2.0.2                    pypi_0    pypi
pylint-plugin-utils       0.4                      pypi_0    pypi
pymongo                   3.7.2            py37h0a44026_0    defaults
pymysql                   0.9.2                    py37_0    defaults
pyodbc                    4.0.25           py37h0a44026_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pyparsing                 2.3.0                    py37_0    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pysocks                   1.6.8                    py37_0    defaults
pytables                  3.4.4            py37h13cba08_0    defaults
pytest                    4.0.2                    py37_0    defaults
pytest-arraydiff          0.2              py37h39e3cac_0    defaults
pytest-astropy            0.4.0                    py37_0    defaults
pytest-doctestplus        0.1.3                    py37_0    defaults
pytest-openfiles          0.3.1                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
python                    3.7.2                haf84260_0    defaults
python-dateutil           2.7.5                    py37_0    defaults
python-libarchive-c       2.8                      py37_6    defaults
python.app                2                        py37_9    defaults
pytz                      2018.7                   py37_0    defaults
pywavelets                1.0.0            py37h1d22016_0    defaults
pyyaml                    3.13             py37h1de35cc_0    defaults
pyzmq                     17.1.2           py37h1de35cc_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.3                    py37_0    defaults
qtconsole                 4.4.3                    py37_0    defaults
qtpy                      1.5.2                    py37_0    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.21.0                   py37_0    defaults
rope                      0.11.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
scikit-image              0.14.0           py37h0a44026_1    defaults
scikit-learn              0.19.2           py37h4f467ca_0    defaults
scipy                     1.1.0            py37h28f7352_1    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
service_identity          18.1.0           py37h28b3542_0    defaults
setuptools                40.6.3                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1                    py37_0    defaults
sortedcollections         1.0.1                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
sphinx                    1.8.2                    py37_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-websupport  1.1.0                    py37_1    defaults
spyder                    3.3.2                    py37_0    defaults
spyder-kernels            0.3.0                    py37_0    defaults
sqlalchemy                1.2.15           py37h1de35cc_0    defaults
sqlite                    3.26.0               ha441bb4_0    defaults
statsmodels               0.9.0            py37h1d22016_0    defaults
sympy                     1.3                      py37_0    defaults
tblib                     1.3.2                    py37_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py37_0    defaults
tornado                   5.1.1            py37h1de35cc_0    defaults
tqdm                      4.28.1           py37h28b3542_0    defaults
traitlets                 4.3.2                    py37_0    defaults
twisted                   18.9.0           py37h1de35cc_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
wheel                     0.32.3                   py37_0    defaults
whitenoise                4.1                      pypi_0    pypi
widgetsnbextension        3.4.2                    py37_0    defaults
wrapt                     1.10.11          py37h1de35cc_2    defaults
wurlitzer                 1.0.2                    py37_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.2                    py37_0    defaults
xlwings                   0.15.1                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.5                h0a44026_1    defaults
zict                      0.1.3                    py37_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zope                      1.0                      py37_1    defaults
zope.interface            4.6.0            py37h1de35cc_0    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```

**Comment by jhartley218** [comment] 2019-02-23 20:28
Downgrading OpenSSL solved the issue for me as well.

**Comment by Daletxt** [comment] 2019-03-01 04:41
> Downgrading OpenSSL solved the issue for me as well.

What's your OpenSSL version? Mine is OpenSSL 1.1.1b  26 Feb 2019, my environment are:
1. conda 4.6.7(use conda --version)
2. Python 3.6.7(from anaconda)
3. mysql  Ver 8.0.13 for macos10.14 on x86_64 (MySQL Community Server - GPL)
4. OpenSSL 1.1.1b  26 Feb 2019(but I use "brew upgrade OpenSSL", it shows "Error: openssl 1.0.2q already installed")
5.MacOS Mojave 10.14.3
Python Packages:
1. MySQLdb (mysqlclient) 1.4.2.post1
2. DBUtils 1.3
When attempting to connect to an remote SSL enabled MySQL server I get:
"MySQLdb._exceptions.OperationalError: (2026, 'SSL connection error: SSL_CTX_set_tmp_dh failed')"

But in Windows 10 and Linux, I don't have this 2026 bug.
In Mac, I can use "localhost" connect my mysql, but use "127.0.0.1" can't.
And use other python(not anaconda's), I can also connect remote MySQL server and localhost mysql.
Who can explain this?
I think it's anaconda's issue.

**Comment by lixufeng1990** [comment] 2019-05-20 09:49
run conda comond: conda install openssl=1.0.2r
downgrade openssl to 1.0.2r can process the problem +1

**Comment by julilien** [comment] 2019-06-13 13:56
Unfortunately, this problem still exists for openssl 1.1.1b and c. Downgrading to an older version is often not possible due to requirement satisfaction problems (e. g. python 3.6.7 requires openssl >= 1.1.1a).

**Comment by hashamMunir** [comment] 2019-07-01 12:02
I am having the same issue with 1.1.1c as well. Any solution?

**Comment by aaymeloglu** [comment] 2019-07-01 17:26
Me too. This is blocking migrating to python 3.7.

**Comment by mehmedean** [comment] 2019-07-28 02:24
Is there any updates on this issue?

**Comment by mehmedean** [comment] 2019-07-28 05:25
I have solve this problem by providing `use_pure=True` as follows:

```
mysql.connector.connect(host=..., user=..., passwd=..., use_pure=True)
```

**Comment by rizzoli** [comment] 2019-09-17 16:15
Same problem here. I solved it by downgrading to openssl 1.0.2p by running 
`conda install openssl=1.0.2p`
But it's not nice

**Comment by brauliobarahona** [comment] 2019-10-16 12:17
I get the `2026 (HY000): SSL connection error: SSL_CTX_set_tmp_dh failed` as reported in #8299 however I have the full mysql installation [MySQL Community Server 8.0.18](https://dev.mysql.com/downloads/mysql/) running and tested. 

I was able to install the python connector provided by [Oracle](https://dev.mysql.com/doc/connector-python/en/) and it runs. I tested it starting a local database and from the python interpreter querying to it. However, this was directly installed in my system distribution of `Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin` - when install it directly with conda in anaconda `conda install -c anaconda mysql-connector-python` I get ``2026 (HY000): SSL connection error: SSL_CTX_set_tmp_dh failed`

I am trying to downgrade as posted above but this seems to take forever. Any other option?

**Comment by brauliobarahona** [comment] 2019-10-18 11:28
@rizzoli can you share what version of `pyopenssl` you have?

I could not downgrade to `openssl 1.0.2.p`. I made as far as `1.1.1c`

**Comment by atodniAr** [comment] 2019-10-21 02:52
Same thing here. I use `sqlalchemy` for `pandas` connection to mysql, downgrading to `openssl=1.0.2p` solved my issue. It's very bad for conda env management though, since you'll have to downgrade python as well.

**Comment by imanoj997** [comment] 2019-11-26 05:10
@hashamMunir where do you define this connection?

**Comment by hashamMunir** [comment] 2019-11-26 11:45
@imanoj997  sorry i did nt get your question. 
to resolve the openssl issue, use `use_pure=True` inside you mysql connector. It will resolve the issue. it is working fine for me.

**Comment by cjrzs** [comment] 2019-11-27 08:07
If I downgrade SSL in conda, will it affect the global environment？

**Comment by hashamMunir** [comment] 2019-11-27 08:55
> If I downgrade SSL in conda, will it affect the global environment？

it might , it depends version to version, some libraries support older versions

**Comment by cjrzs** [comment] 2019-11-27 09:04
> > 如果我在conda中降级SSL，会影响全球环境吗？
> 
> 可能取决于版本，某些库支持较旧的版本

I found that the SSL version in conda is different from that in the server, which means that the SSL version in conda is independent, so I should be able to change the SSL version in conda independently without affecting the SSL in the server

**Comment by cjrzs** [comment] 2019-11-27 09:04
> > If I downgrade SSL in conda, will it affect the global environment？
> 
> it might , it depends version to version, some libraries support older versions

I found that the SSL version in conda is different from that in the server, which means that the SSL version in conda is independent, so I should be able to change the SSL version in conda independently without affecting the SSL in the server

**Comment by cjrzs** [comment] 2019-11-27 11:31
Why is it still a problem that I downgraded to 1.0.2p
![image](https://user-images.githubusercontent.com/42176286/69719943-84b71880-114c-11ea-8e59-f51655722e79.png)

**Comment by cm008** [comment] 2019-12-03 17:28
i use lastest anaconda with sqlalchemy on ubuntu 16.04 . I did not found a way to configure use_pure=true for sqlalchemy.connect string. As i just work on my localhost i switched off ssl on the mysql-server in my.cnf by adding a line ssl=0. That solved the problem for me for the moment.

**Comment by AnkitR8** [comment] 2019-12-24 20:05
We can pass connection arguments parameter in create_engine method.
create_engine(<connection_string>, **connect_args={'use_pure': True}**)

Thanks

**Comment by synapticarbors** [comment] 2020-01-08 20:32
Any update on this issue? I can see the same problem with openssl 1.1.1d. While the `use_pure` solution works in theory, that forces the connector to use a pure python implementation, which has much poorer performance characteristics than the C-library or mysqlclient.

**Comment by cm008** [comment] 2020-01-08 21:56
for me the solution provided by AnkitR8 worked with sql-alchemy in python.
Thanks for that!

**Comment by jjhelmus** [comment] 2020-01-15 20:46
The patch used to build the mysql-connector-c package for OpenSSL 1.1.1 was incomplete.  This patch has been updated and new packages (build _1) has been released. Environments which have this new package do not require the `use_pure` work-around.

Existing environment can be updated using `conda update mysql-connector-c`, new environments will automatically include the corrected package.  

For more details see https://github.com/conda-forge/mysql-connector-c-feedstock/pull/10 and https://github.com/AnacondaRecipes/mysql-connector-c-feedstock/commit/c147a14cd0a8679d9687985295a4ffca073b6520

Any someone can check the new package, confirm the fix and close this issue it would be appreciated.

**Comment by synapticarbors** [comment] 2020-01-16 03:03
@jjhelmus I can confirm that the fix works for me using the `defaults` channel on MacOS with openssl 1.1.1d and using both `mysqlclient` and `mysql-connector-python`. That you for working through the issue with me and patching it. It's nice to solve a bug that seems to have been an issue for a lot of people for a while.

**Comment by jjhelmus** [comment] 2020-01-16 14:35
Thanks for checking this fix @synapticarbors.

**Closed by jjhelmus** 2020-01-16 14:35 UTC
Labels: type-bug

**Comment by GoldstHa** [comment] 2020-01-16 18:41
mysql-connector-python now uses the latest ssl without use_pure=True on macOS and Linux. Thank you so much for fixing this!!!

**Comment by Tburm** [comment] 2020-02-12 22:26
Which specific version of `mysql-connector-python` fixes this issue?

**Comment by jjhelmus** [comment] 2020-02-12 22:31
6.1.11 build `1` in `defaults`, build `1004` in `conda-forge`

**Comment by lordozb** [comment] 2020-02-14 10:34
conda install mysql-connector-c==6.1.11=h597af5e_1`
`CondaValueError: Value error: invalid package specification: mysql-connector-c==6.1.11=h597af5e_1`

Unable to install latest build for linux.

**Comment by sandykr01** [comment] 2023-02-13 15:46
Can anyone help me to solve this error: 

mysql.connector.errors.InterfaceError: 2055: Lost connection to MySQL server at '127.0.0.1:3306', system error: 1 [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:852)
