### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Arktius** [ContinuumIO/anaconda-issues#4996] opened 2017-09-04 08:12 UTC
Hey Guys, as I wrote in the title, Anaconda doesn't start any longer. I have no idea why, it used to work and I guess some Windows updates changed something. When I start Anaconda, I can see the Overview for a little moment. The below info may help you.

Thanks in advance.

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

**C:\Users\Admin>conda info**

Current conda install:

               platform : win-64
          conda version : 4.3.23
       conda is private : False
      conda-env version : 4.3.23
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.14.2
       root environment : C:\Users\Admin\Anaconda3  (writable)
    default environment : C:\Users\Admin\Anaconda3
       envs directories : C:\Users\Admin\Anaconda3\envs
                          C:\Users\Admin\AppData\Local\conda\conda\envs
                          C:\Users\Admin\.conda\envs
          package cache : C:\Users\Admin\Anaconda3\pkgs
                          C:\Users\Admin\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Admin\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.23 requests/2.14.2 CPython/3.5.2 Windows/10 Windows/10.0.15063
          administrator : False

**C:\Users\Admin>conda list --show-channel-urls**

# packages in environment at C:\Users\Admin\Anaconda3:
#
_license                  1.1                      py35_1    defaults
_nb_ext_conf              0.3.0                    py35_0    defaults
alabaster                 0.7.9                    py35_0    defaults
anaconda                  custom                   py35_0    defaults
anaconda-clean            1.0.0                    py35_0    defaults
anaconda-client           1.5.1                    py35_0    defaults
anaconda-navigator        1.3.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astroid                   1.4.7                    py35_0    defaults
astropy                   2.0.1               np112py35_0    defaults
babel                     2.3.4                    py35_0    defaults
backports                 1.0                      py35_0    defaults
beautifulsoup4            4.5.1                    py35_0    defaults
bitarray                  0.8.1                    py35_1    defaults
blaze                     0.10.1                   py35_0    defaults
bleach                    1.5.0                     <pip>
bokeh                     0.12.2                   py35_0    defaults
boto                      2.42.0                   py35_0    defaults
bottleneck                1.2.1               np112py35_0    defaults
bzip2                     1.0.6                    vc14_3  [vc14]  defaults
cffi                      1.7.0                    py35_0    defaults
chardet                   3.0.4                    py35_0    defaults
chest                     0.2.3                    py35_0    defaults
click                     6.6                      py35_0    defaults
cloudpickle               0.2.1                    py35_0    defaults
clyent                    1.2.2                    py35_0    defaults
colorama                  0.3.7                    py35_0    defaults
comtypes                  1.1.2                    py35_0    defaults
conda                     4.3.23                   py35_0    defaults
conda-build               2.0.2                    py35_0    defaults
conda-env                 2.6.0                         0    defaults
configobj                 5.0.6                    py35_0    defaults
console_shortcut          0.1.1                    py35_1    defaults
contextlib2               0.5.3                    py35_0    defaults
cryptography              1.5                      py35_0    defaults
cudatoolkit               8.0                           1    defaults
cudnn                     6.0                           0    defaults
curl                      7.49.0                   vc14_0  [vc14]  defaults
cycler                    0.10.0                   py35_0    defaults
cython                    0.24.1                   py35_0    defaults
cytoolz                   0.8.0                    py35_0    defaults
dask                      0.15.0                   py35_0    defaults
datashape                 0.5.2                    py35_0    defaults
decorator                 4.0.10                   py35_0    defaults
dill                      0.2.5                    py35_0    defaults
docutils                  0.12                     py35_2    defaults
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.2                    py35_0    defaults
et_xmlfile                1.0.1                    py35_0    defaults
fastcache                 1.0.2                    py35_1    defaults
filelock                  2.0.6                    py35_0    defaults
flask                     0.11.1                   py35_0    defaults
flask-cors                2.1.2                    py35_0    defaults
freetype                  2.5.5                    vc14_1  [vc14]  defaults
get_terminal_size         1.0.0                    py35_0    defaults
gevent                    1.1.2                    py35_0    defaults
greenlet                  0.4.10                   py35_0    defaults
h5py                      2.7.0               np112py35_0    defaults
hdf5                      1.8.15.1                 vc14_4  [vc14]  defaults
heapdict                  1.0.0                    py35_1    defaults
html5lib                  0.9999999                 <pip>
icu                       57.1                     vc14_0  [vc14]  defaults
idna                      2.1                      py35_0    defaults
imagesize                 0.7.1                    py35_0    defaults
ipykernel                 4.5.0                    py35_0    defaults
ipython                   5.1.0                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                5.2.2                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jdcal                     1.2                      py35_1    defaults
jedi                      0.9.0                    py35_1    defaults
jinja2                    2.8                      py35_1    defaults
jpeg                      8d                       vc14_2  [vc14]  defaults
jsonschema                2.5.1                    py35_0    defaults
jupyter                   1.0.0                    py35_3    defaults
jupyter_client            4.4.0                    py35_0    defaults
jupyter_console           5.0.0                    py35_0    defaults
jupyter_core              4.2.0                    py35_0    defaults
Keras                     2.0.6                     <pip>
lazy-object-proxy         1.2.1                    py35_0    defaults
libdynd                   0.7.2                         0    defaults
libgpuarray               0.6.8                    vc14_0  [vc14]  defaults
libpng                    1.6.27                   vc14_0  [vc14]  defaults
libprotobuf               3.2.0                    vc14_0  [vc14]  defaults
libpython                 2.0                      py35_0    defaults
libtiff                   4.0.6                    vc14_2  [vc14]  defaults
llvmlite                  0.19.0                   py35_0    defaults
locket                    0.2.0                    py35_1    defaults
lxml                      3.6.4                    py35_0    defaults
m2w64-binutils            2.25.1                        5    defaults
m2w64-bzip2               1.0.6                         6    defaults
m2w64-crt-git             5.0.0.4636.2595836               2    defaults
m2w64-gcc                 5.3.0                         6    defaults
m2w64-gcc-ada             5.3.0                         6    defaults
m2w64-gcc-fortran         5.3.0                         6    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gcc-objc            5.3.0                         6    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-headers-git         5.0.0.4636.c0ad18a               2    defaults
m2w64-isl                 0.16.1                        2    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-make                4.1.2351.a80a8b8               2    defaults
m2w64-mpc                 1.0.3                         3    defaults
m2w64-mpfr                3.1.4                         4    defaults
m2w64-pkg-config          0.29.1                        2    defaults
m2w64-toolchain           5.3.0                         7    defaults
m2w64-tools-git           5.0.0.4592.90b8472               2    defaults
m2w64-windows-default-manifest 6.4                           3    defaults
m2w64-winpthreads-git     5.0.0.4634.697f757               2    defaults
m2w64-zlib                1.2.8                        10    defaults
mako                      1.0.6                    py35_0    defaults
Markdown                  2.6.8                     <pip>
markupsafe                0.23                     py35_2    defaults
matplotlib                2.0.2               np112py35_0    defaults
menuinst                  1.4.1                    py35_0    defaults
mistune                   0.7.3                    py35_0    defaults
mkl                       2017.0.3                      0    defaults
mkl-service               1.1.2                    py35_2    defaults
mpmath                    0.19                     py35_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.4.8                    py35_0    defaults
nb_anacondacloud          1.2.0                    py35_0    defaults
nb_conda                  2.0.0                    py35_0    defaults
nb_conda_kernels          2.0.0                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbformat                  4.1.0                    py35_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
networkx                  1.11                     py35_0    defaults
nltk                      3.2.1                    py35_0    defaults
nose                      1.3.7                    py35_1    defaults
notebook                  4.2.3                    py35_0    defaults
numba                     0.34.0              np112py35_0    defaults
numexpr                   2.6.2               np112py35_0    defaults
numpy                     1.13.1                    <pip>
numpy                     1.12.1                   py35_0    defaults
numpydoc                  0.6.0                    py35_0    defaults
odo                       0.5.0                    py35_1    defaults
openpyxl                  2.3.2                    py35_0    defaults
openssl                   1.0.2j                   vc14_0  [vc14]  defaults
pandas                    0.20.3                   py35_0    defaults
partd                     0.3.8                    py35_0    defaults
path.py                   8.2.1                    py35_0    defaults
pathlib2                  2.1.0                    py35_0    defaults
patsy                     0.4.1                    py35_0    defaults
pep8                      1.7.0                    py35_0    defaults
pickleshare               0.7.4                    py35_0    defaults
pillow                    3.3.1                    py35_0    defaults
pip                       8.1.2                    py35_0    defaults
pkginfo                   1.3.2                    py35_0    defaults
ply                       3.9                      py35_0    defaults
prompt_toolkit            1.0.3                    py35_0    defaults
protobuf                  3.2.0                    py35_0    defaults
psutil                    4.3.1                    py35_0    defaults
py                        1.4.31                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycodestyle               2.3.1                    py35_0    defaults
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.14                     py35_1    defaults
pycrypto                  2.6.1                    py35_4    defaults
pycurl                    7.43.0                   py35_0    defaults
pyflakes                  1.3.0                    py35_0    defaults
pygments                  2.1.3                    py35_0    defaults
pygpu                     0.6.8                    py35_0    defaults
pylint                    1.5.4                    py35_1    defaults
pyopenssl                 16.2.0                   py35_0    defaults
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      5.6.0                    py35_0    defaults
pytables                  3.2.2               np112py35_4    defaults
pytest                    2.9.2                    py35_0    defaults
python                    3.5.2                         0    defaults
python-dateutil           2.5.3                    py35_0    defaults
pytz                      2016.6.1                 py35_0    defaults
pywavelets                0.5.2               np112py35_0    defaults
pywin32                   220                      py35_1    defaults
pyyaml                    3.12                     py35_0    defaults
pyzmq                     15.4.0                   py35_0    defaults
qt                        5.6.0                    vc14_0  [vc14]  defaults
qtawesome                 0.4.4                    py35_0    defaults
qtconsole                 4.2.1                    py35_2    defaults
qtpy                      1.1.2                    py35_0    defaults
requests                  2.14.2                   py35_0    defaults
rope                      0.9.4                    py35_1    defaults
ruamel_yaml               0.11.14                  py35_0    defaults
scikit-image              0.13.0              np112py35_0    defaults
scikit-learn              0.18.2              np112py35_0    defaults
scipy                     0.19.1              np112py35_0    defaults
setuptools                27.2.0                   py35_1    defaults
simplegeneric             0.8.1                    py35_1    defaults
singledispatch            3.4.0.3                  py35_0    defaults
sip                       4.18                     py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.4.6                    py35_0    defaults
spyder                    3.2.0                    py35_0    defaults
sqlalchemy                1.0.13                   py35_0    defaults
statsmodels               0.8.0               np112py35_0    defaults
sympy                     1.0                      py35_0    defaults
tensorflow                1.1.0               np112py35_0    defaults
tensorflow-gpu            1.1.0               np112py35_0    defaults
Theano                    0.9.0                     <pip>
tk                        8.5.18                   vc14_0  [vc14]  defaults
toolz                     0.8.0                    py35_0    defaults
tornado                   4.4.1                    py35_0    defaults
traitlets                 4.3.0                    py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
vs2015_runtime            14.0.25420                    0    defaults
wcwidth                   0.1.7                    py35_0    defaults
werkzeug                  0.11.11                  py35_0    defaults
Werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        1.2.6                    py35_0    defaults
win_unicode_console       0.5                      py35_0    defaults
wrapt                     1.10.6                   py35_0    defaults
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.3                    py35_0    defaults
xlwings                   0.10.0                   py35_0    defaults
xlwt                      1.1.2                    py35_0    defaults
zlib                      1.2.8                    vc14_3  [vc14]  defaults

**C:\Users\Admin>anaconda-navigator**

Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'

C:\Users\Admin>

**Comment by whysorfrans** [comment] 2017-09-04 12:22
I am experiencing a similar (the same?) problem, anaconda navigator appears to start, then shuts down after a few seconds. From cmd the message is the same:
`
C:\... >anaconda-navigator
Traceback (most recent call last):
  File "C:\...\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\community.py", line 372, in set_content_list
    uri=item['uri'], date=item.get('date', '') or "",
KeyError: 'uri'
`

**Comment by goanpeca** [comment] 2017-09-04 14:42
**See issue #4747 for more information on how to fix this issue.**

---

Closing as duplicate of #4747

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-04 14:42 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by Arktius** [comment] 2017-09-04 14:46
conda update anaconda-navigator was enough to fix it =)

Thanks so much!

**Comment by goanpeca** [comment] 2017-09-04 14:49
@Arktius please also install the `navigator-updater` as this will allow you to update navigator from within navigator and get information on new versions.
