### ISSUE TITLE
Error in anaconda-navigator after spyder update

### ISSUE THREAD

**Issue by daviregeloa** [ContinuumIO/anaconda-issues#5415] opened 2017-09-12 19:55 UTC
Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1214, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "/home/diego/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

I have updated anaconda navigator updater without any improvement  in performance

**Comment by goanpeca** [comment] 2017-09-12 21:21
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-12 21:21 UTC
