### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hmd23401** [ContinuumIO/anaconda-issues#8243] opened 2018-01-22 20:20 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "C:\Users\aolasisi\AppData\Local\Continuum\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\aolasisi\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\aolasisi\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.7
```

**Comment by goanpeca** [comment] 2018-01-25 16:22
Closing as duplicate of #8216

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8216 for more information on how to fix this issue.**

Or try running

```
conda upgrade jupyter_core
```

**Closed by goanpeca** 2018-01-25 16:22 UTC
Labels: pkg:navigator, reso:duplicate
