### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sanghaisubham** [ContinuumIO/anaconda-issues#9589] opened 2018-06-13 13:48 UTC
An unexpected error occurred on Navigator start-up

Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 138, in start_app
    window = run_app(splash)
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2122, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1699, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\Subham\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 506, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2018-06-13 13:49
Closing as duplicate of #1837

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1837 for more information on how to fix this.**

**Closed by goanpeca** 2018-06-13 13:49 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by sanghaisubham** [comment] 2018-06-13 13:53
Getting Error:

'conda' is not recognized as an internal or external command,
operable program or batch file.

**Comment by goanpeca** [comment] 2018-06-13 14:59
@sandhujasmine are you using the `anaconda prompt`?

**Comment by Almund** [comment] 2018-10-22 15:50
Getting the same error as @sanghaisubham. And yes, I'm using anaconda prompt @goanpeca
