### ISSUE TITLE
Navigator Error: string indices must be integers, not str

### ISSUE THREAD

**Issue by yogene** [ContinuumIO/anaconda-issues#7305] opened 2017-11-14 07:38 UTC
Whenever I launch anaconda, I get an error window with this information and anaconda also opens an html file with the same info.

# Navigator Error
An unexpected error occurred on Navigator start-up

## Report
Please report this issue in the anaconda issue tracker

## Main Error
```
string indices must be integers, not str
```

## Traceback
```
Traceback (most recent call last):
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 120, in start_app
    window = run_app(splash)
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 161, in __init__
    self.api = AnacondaAPI()
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1258, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 70, in __init__
    self._conda_api = CondaAPI()
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1654, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 345, in __init__
    self.set_conda_prefix()
  File "/Users/eugene/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 494, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str
```

**Comment by goanpeca** [comment] 2017-11-14 12:22
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-14 12:22 UTC

**Comment by yogene** [comment] 2017-11-14 18:45
Didn't help Navigator was aready up to date.
```
Eugenes-Air:~ eugene$ conda update anaconda-navigator

Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/eugene/anaconda2:
#
anaconda-navigator        1.6.9            py27h103b016_0  
Eugenes-Air:~ eugene$ 
Eugenes-Air:~ eugene$ conda update navigator-updater
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/eugene/anaconda2:
#
navigator-updater         0.1.0            py27ha63e0b4_0  
```

**Comment by goanpeca** [comment] 2017-11-14 18:55
See issue #1837 for more information on how to fix this issue.

**Comment by yogene** [comment] 2017-11-15 05:58
Turning off my antivirus did the trick. (Avast on Mac OS X El Capitan)
Is anyone doing something so that I would not have to disable my antivirus to use Anaconda?

**Comment by goanpeca** [comment] 2017-11-15 14:27
@yogene, yes unfortunately this happens still with some antivirus. We have already reported these issues, but it takes some time for them to reflect on the virus whitelist DB (I guess?)
