### ISSUE TITLE
Anaconda Installer not associating .py files with python

### ISSUE THREAD

**Issue by tpowellcio** [ContinuumIO/anaconda-issues#119] opened 2014-05-21 18:07 UTC
All windows platforms:
Anaconda Installer not associating .py files with python during the install process even if you check the use as system python box.

**Comment by nehaljwani** [comment] 2017-05-21 13:07
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/1375

**Closed by nehaljwani** 2017-05-21 13:07 UTC
Labels: os:windows, type:bug
