### ISSUE TITLE
conda failure after High Sierra upgrade

### ISSUE THREAD

**Issue by fonnesbeck** [ContinuumIO/anaconda-issues#5812] opened 2017-09-20 14:30 UTC
Following updating macOS to High Sierra (10.13), any network operations with conda fail with `CondaHTTPError` messages. For example, a package install attempt:

```
Fetching package metadata .....
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10f786b00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))",),)
```

running anaconda-navigator yields a series of these:

```
2017-09-20 09:26:53,990 - ERROR download_api._is_valid_url:259
HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/r/noarch/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1156fb828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

**Comment by goanpeca** [comment] 2017-09-20 14:32
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-09-20 14:32 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by fonnesbeck** [comment] 2017-09-20 14:54
OK, the fixes above do not work (both result in errors). Have reported this on #1932

**Comment by fonnesbeck** [comment] 2017-09-20 15:15
I notice #1932 is closed, but this is clearly not solved. Is there an open issue that this is related to?
