### ISSUE TITLE
qtpy seems broken: probably a repeat of issues #1182, #1183, and probably anaconda-recipes issue #52

### ISSUE THREAD

**Issue by kmtac** [ContinuumIO/anaconda-issues#1225] opened 2016-11-10 18:29 UTC
qtpy seems broken for a user install on MacOSx.  Removed anaconda completely, then reinstalled it from the website (both command-line and graphical versions tried).  Nothing worked.

It seems broken for both python2 and python3

This affects many packages: glue, ipython qtconsole, matplotlib backends, anaconda navigator, ...

In ipython, import PyQt5 works beautifully.  However, import qtpy doesn't work at all.

The issue may only apply to *nix users without root privileges.

Seems related to issue   #1182, issue #1183, and anaconda-recipes issue #52.  It also seems like the reporter of anaconda-recipes issue #52 suggested a fix. 

From the response to anaconda-recipes issue #52, it looks like Continuum has no intention of fixing the issue.  Instead, continuum closed the issues and said that the very frustrated person who posted both the issue and a potential solution was a troll.  

I'd much prefer that Continuum fix issues rather than accuse frustrated users of being trolls.   I'd also like to continue to use anaconda and to recommend it to my friends and colleagues.  However, the response to anaconda-recipes issue #52 is making me reconsider this long-standing recommendation.  

**System info**

```
mac1% conda info
Current conda install:

               platform : osx-64
               conda version : 4.2.9
               conda is private : False
               conda-env version : 4.2.9
               conda-build version : 2.0.2
               python version : 3.5.2.final.0
               requests version : 2.11.1
               root environment : /Users/k/anaconda  (writable)
               default environment : /Users/k/anaconda
               envs directories : /Users/k/anaconda/envs
               package cache : /Users/k/anaconda/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                       https://repo.continuum.io/pkgs/free/noarch/
                       https://repo.continuum.io/pkgs/pro/osx-64/
                       https://repo.continuum.io/pkgs/pro/noarch/
               config file : None
               offline mode : False
```

**Info on qtpy**

```
mac1% conda info qtpy
Fetching package metadata .......

qtpy 1.0 py27_0
---------------
file name   : qtpy-1.0-py27_0.tar.bz2
name        : qtpy
version     : 1.0
build number: 0
build string: py27_0
channel     : defaults
size        : 16 KB
date        : 2016-03-23
fn          : qtpy-1.0-py27_0.tar.bz2
license     : MIT
md5         : 3fc93b6983c4fe979682d67f5066c2db
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0-py27_0.tar.bz2
dependencies:
    python 2.7*

qtpy 1.0 py34_0
---------------
file name   : qtpy-1.0-py34_0.tar.bz2
name        : qtpy
version     : 1.0
build number: 0
build string: py34_0
channel     : defaults
size        : 17 KB
date        : 2016-03-23
fn          : qtpy-1.0-py34_0.tar.bz2
license     : MIT
md5         : 7d1acdcea9db3d888c22b8271a7a0b38
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0-py34_0.tar.bz2
dependencies:
    python 3.4*

qtpy 1.0 py35_0
---------------
file name   : qtpy-1.0-py35_0.tar.bz2
name        : qtpy
version     : 1.0
build number: 0
build string: py35_0
channel     : defaults
size        : 17 KB
date        : 2016-03-23
fn          : qtpy-1.0-py35_0.tar.bz2
license     : MIT
md5         : 94f6af7fb20465715a0127e87c022084
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0-py35_0.tar.bz2
dependencies:
    python 3.5*

qtpy 1.0.1 py27_0
-----------------
file name   : qtpy-1.0.1-py27_0.tar.bz2
name        : qtpy
version     : 1.0.1
build number: 0
build string: py27_0
channel     : defaults
size        : 16 KB
date        : 2016-04-11
fn          : qtpy-1.0.1-py27_0.tar.bz2
license     : MIT
md5         : fe8b78c084cb0baeaaea5186af6777df
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0.1-py27_0.tar.bz2
dependencies:
    python 2.7*

qtpy 1.0.1 py34_0
-----------------
file name   : qtpy-1.0.1-py34_0.tar.bz2
name        : qtpy
version     : 1.0.1
build number: 0
build string: py34_0
channel     : defaults
size        : 17 KB
date        : 2016-04-11
fn          : qtpy-1.0.1-py34_0.tar.bz2
license     : MIT
md5         : 10ddc315ad0a6ffe6d5007562c046e24
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0.1-py34_0.tar.bz2
dependencies:
    python 3.4*

qtpy 1.0.1 py35_0
-----------------
file name   : qtpy-1.0.1-py35_0.tar.bz2
name        : qtpy
version     : 1.0.1
build number: 0
build string: py35_0
channel     : defaults
size        : 17 KB
date        : 2016-04-11
fn          : qtpy-1.0.1-py35_0.tar.bz2
license     : MIT
md5         : 08c103ece744484b0bcac0bcd122d793
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0.1-py35_0.tar.bz2
dependencies:
    python 3.5*

qtpy 1.0.2 py27_0
-----------------
file name   : qtpy-1.0.2-py27_0.tar.bz2
name        : qtpy
version     : 1.0.2
build number: 0
build string: py27_0
channel     : defaults
size        : 16 KB
date        : 2016-06-07
fn          : qtpy-1.0.2-py27_0.tar.bz2
license     : MIT
md5         : 8230a741cbeb6adbe1c03649ca9e5b82
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0.2-py27_0.tar.bz2
dependencies:
    python 2.7*

qtpy 1.0.2 py34_0
-----------------
file name   : qtpy-1.0.2-py34_0.tar.bz2
name        : qtpy
version     : 1.0.2
build number: 0
build string: py34_0
channel     : defaults
size        : 17 KB
date        : 2016-06-07
fn          : qtpy-1.0.2-py34_0.tar.bz2
license     : MIT
md5         : f3a102d5fa8b8435dbb7a9679edb3ec9
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0.2-py34_0.tar.bz2
dependencies:
    python 3.4*

qtpy 1.0.2 py35_0
-----------------
file name   : qtpy-1.0.2-py35_0.tar.bz2
name        : qtpy
version     : 1.0.2
build number: 0
build string: py35_0
channel     : defaults
size        : 17 KB
date        : 2016-06-07
fn          : qtpy-1.0.2-py35_0.tar.bz2
license     : MIT
md5         : 43e57e0f1bc7c703d705c220d5a5eb20
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.0.2-py35_0.tar.bz2
dependencies:
    python 3.5*

qtpy 1.1.2 py27_0
-----------------
file name   : qtpy-1.1.2-py27_0.tar.bz2
name        : qtpy
version     : 1.1.2
build number: 0
build string: py27_0
channel     : defaults
size        : 22 KB
date        : 2016-09-20
fn          : qtpy-1.1.2-py27_0.tar.bz2
license     : MIT
md5         : d4eaf7fd2af8eefe030e655fe8fdcf78
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.1.2-py27_0.tar.bz2
dependencies:
    python 2.7*

qtpy 1.1.2 py34_0
-----------------
file name   : qtpy-1.1.2-py34_0.tar.bz2
name        : qtpy
version     : 1.1.2
build number: 0
build string: py34_0
channel     : defaults
size        : 22 KB
date        : 2016-09-20
fn          : qtpy-1.1.2-py34_0.tar.bz2
license     : MIT
md5         : ed4c1b59aa30f29057a482792cc90eff
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.1.2-py34_0.tar.bz2
dependencies:
    python 3.4*

qtpy 1.1.2 py35_0
-----------------
file name   : qtpy-1.1.2-py35_0.tar.bz2
name        : qtpy
version     : 1.1.2
build number: 0
build string: py35_0
channel     : defaults
size        : 22 KB
date        : 2016-09-20
fn          : qtpy-1.1.2-py35_0.tar.bz2
license     : MIT
md5         : 64281ee9e25245706b01481f46ae9de1
priority    : 0
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/qtpy-1.1.2-py35_0.tar.bz2
dependencies:
    python 3.5*
```

**Attempt to run navigator**

```
mac1% Anaconda-Navigator
Traceback (most recent call last):
  File "/Users/k/anaconda/lib/python3.5/site-packages/qtpy/__init__.py", line   119, in <module>
      from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
      ImportError: No module named 'PySide'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/k/anaconda/bin/Anaconda-Navigator", line 4, in <module>
            import anaconda_navigator.app.main
              File "/Users/k/anaconda/lib/python3.5/site-packages/              anaconda_navigator/app/main.py", line 16, in <module>
                  from qtpy.QtCore import QCoreApplication, QEvent, QObject, Qt
                    File "/Users/k/anaconda/lib/python3.5/site-packages/qtpy/   __init__.py", line 125, in <module>
                        raise PythonQtError('No Qt bindings could be found')
                        qtpy.PythonQtError: No Qt bindings could be found
```

**Attempt to import qtpy into ipython**

```
mac1% ipython
Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import qtpy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/k/anaconda/lib/python3.5/site-packages/qtpy/__init__.py in <module>()
    118     try:
    --> 119         from PySide import __version__ as PYSIDE_VERSION  #         analysis:ignore
        120         from PySide.QtCore import __version__ as QT_VERSION  #      analysis:ignore

        ImportError: No module named 'PySide'

        During handling of the above exception, another exception occurred:

        PythonQtError                             Traceback (most recent call   last)
        <ipython-input-1-9ff2cb73a064> in <module>()

        PythonQtError                             Traceback (most recent call   last)
        <ipython-input-1-9ff2cb73a064> in <module>()
        ----> 1 import qtpy

        /Users/k/anaconda/lib/python3.5/site-packages/qtpy/__init__.py in       <module>()
            123         PYSIDE = True
                124     except ImportError:
                --> 125         raise PythonQtError('No Qt bindings could be    found')
                    126
                        127 API_NAME = {'pyqt5': 'PyQt5', 'pyqt': 'PyQt4',      'pyqt4': 'PyQt4',

                        PythonQtError: No Qt bindings could be found
```

**Comment by ccordoba12** [comment] 2016-11-10 18:59
> This affects many packages: glue, ipython qtconsole, matplotlib backends, anaconda navigator,

qtpy is a library used in Navigator, Spyder and Glue, not in Matplotlib and qtconsole.

> In ipython, import PyQt5 works beautifully. However, import qtpy doesn't work at all.

qtpy is just a wrapper around PyQt and PySide, so I don't understand where your error is coming from. In any case, since qtconsole doesn't use qtpy, it should work for you. But you said it isn't, so please post the error you get when you run in a terminal

    jupyter qtconsole

> From the response to anaconda-recipes issue #52, it looks like Continuum has no intention of fixing the issue. Instead, continuum closed the issues and said that the very frustrated person who posted both the issue and a potential solution was a troll.

Please read very carefully that issue. First, the error reported by that user was fixed within a day by @mingwandroid, and it was an error in conda-build. Second, he didn't offer any solution to the problem. He just pointed out that permissions for the `qt.conf` file were set incorrectly, which is precisely what @mingwandroid fixed. Third, the guy just abused Continuum developers by venting his frustrations with comments like

    Maybe **you should learn** UNIX permissions / rights. This is extremely unprofessional for a
    company! This is why I will not recommend **your twisted snake env**. Another new reason why
    I **hate** this kind of "packager manager", where the maintainers are unable to correctly
    maintain packages.

If you really think this guy is not a throll, then I don't know what you think a throll is (emphasis is mine).

> I'd much prefer that Continuum fix issues rather than accuse frustrated users of being trolls.

Again, the error reported by that guy was fixed quite promptly. The error you have seems completely unrelated.

----

Note: I'm going to format your initial report to make it clearer to read. For now, please report the error you get when you run

    jupyter qtconsole

**Comment by kmtac** [comment] 2016-11-10 23:37
Error message from jupyter qtconsole:
Traceback (most recent call last):
  File "/Users/k/anaconda/bin/jupyter-qtconsole", line 2, in <module>
    from qtconsole.qtconsoleapp import main
  File "/Users/k/anaconda/lib/python3.5/site-packages/qtconsole/qtconsoleapp.py", line 60, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "/Users/k/anaconda/lib/python3.5/site-packages/qtconsole/qt.py", line 23, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "/Users/k/anaconda/lib/python3.5/site-packages/qtconsole/qt_loaders.py", line 309, in load_qt
    api_options))
ImportError: 
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5 or PySide >= 1.0.3 is available,
    and only one is imported per session.

    Currently-imported Qt library:   None
    PyQt4 installed:                 False
    PyQt5 installed:                 True
    PySide >= 1.0.3 installed:       False
    Tried to load:                   ['pyside']

**Comment by kmtac** [comment] 2016-11-10 23:44
This error is also affecting matplotlib:
     %pylab qt
does not work -- similar error message to that reported by ipython above when just importing qtpy.

import PyQt5 works, so the error seems to be in qtpy.  If matplotlib does not use qtpy, maybe there's another problem that affects both of them:

Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
>>> import qtpy
Traceback (most recent call last):
  File "/Users/k/anaconda/lib/python3.5/site-packages/qtpy/__init__.py", line 119, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/k/anaconda/lib/python3.5/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by ccordoba12** [comment] 2016-11-11 00:00
Mmmh, your error for qtconsole is basically the same error reported by `qtpy`. But since qtconsole doesn't use qtpy (as you can see in your error log) then the cause must be something else. The problem is PyQt5 is detected but (for some strange reason) it can't be loaded.

As an additional test, please save and run this code in a terminal, and report any errors.

```python
import sys
from PyQt5 import QtWidgets

def main():

    app = QtWidgets.QApplication(sys.argv)

    w = QtWidgets.QWidget()
    w.resize(250, 150)
    w.move(300, 300)
    w.setWindowTitle('Simple Test')
    w.show()

    sys.exit(app.exec_())

if __name__ == '__main__':
    sys.excepthook = sys.__excepthook__
    main()
```

It should show an empty window.

**Comment by kmtac** [comment] 2016-11-11 00:16
It does indeed show an empty window -- no errors.

**Comment by ccordoba12** [comment] 2016-11-11 00:19
Just to double check: do you have homebrew installed?

**Comment by kmtac** [comment] 2016-11-11 00:48
No.

But this gave me another idea, since I just changed computers.  I tried 
     %pylab qt 
on the old computer, and it worked.  Then, I did 
     conda install glueviz
and again tried
    %pylab qt 
This time, it didn't work -- very similar error messages to those reported above.

I had only recently installed (or updated?) glue.   

However, since I noticed the problems with qt, I've:
1. Removed the anaconda directory
2. Removed the .anaconda* directories
3. Completely reinstalled anaconda
4. Repeated a couple times with various anaconda versions (python2, python3, command-line, gui)
5. Posted an issue

**Comment by kmtac** [comment] 2016-11-11 00:51
I'll be on another computer for a few days, so won't be commenting again until I'm back to this computer.

**Comment by ccordoba12** [comment] 2016-11-11 00:52
Things probably worked before because you were using an older version of Qt (4.8.7, to be exact).

**Comment by goanpeca** [comment] 2016-12-26 23:40
@kmtac any updates here?

@ccordoba12 any thoughts?

**Comment by ccordoba12** [comment] 2016-12-27 05:36
The error isn't in qtpy, that's for sure. Other than that, I have no idea about where this error is coming from.

There's still very little info to know for sure.

**Closed** 2017-02-21 20:34 UTC
Labels: pending:feedback

**Comment by Dschoni** [comment] 2017-08-29 13:17
I have the exact same error as also mentioned here: 

https://github.com/spyder-ide/spyder/issues/5059

only, that the above posted code by @ccordoba12  for me leads to a segmentation fault.
