### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by chas-mellish** [ContinuumIO/anaconda-issues#2033] opened 2017-06-07 12:11 UTC
## Main error
An unexpected error occurred on Navigator start-up<br>byte indices must be integers or slices, not str
## Traceback
```
Traceback (most recent call last):
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/charles/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

```
## System information
```
python: 3.6.1
language: en_AU
os: Linux;4.8.0-52-generic;#55-Ubuntu SMP Fri Apr 28 13:28:01 UTC 2017;i686;i686
version: 1.6.2
platform: linux-32
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by chas-mellish** [comment] 2017-06-07 12:15
Segmentation fault (core dumped) 
[core_dumped.txt](https://github.com/ContinuumIO/anaconda-issues/files/1057890/core_dumped.txt)

**Comment by goanpeca** [comment] 2017-06-08 21:06
Closing as duplicate of #1837

**Closed by goanpeca** 2017-06-08 21:06 UTC
Labels: pkg:navigator, reso:duplicate
