### ISSUE TITLE
Main Error

### ISSUE THREAD

**Issue by shintkb** [ContinuumIO/anaconda-issues#3644] opened 2017-07-28 07:36 UTC
I saw issue #1932 , and tried it. But error has occurred...

%conda update anaconda-navigator

Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-32/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-32/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 405 Method Not Allowed',)))",),)

**Comment by goanpeca** [comment] 2017-07-28 07:36
**See Issue #1932 for more information on how to fix this.**

---

Closing as duplicate of #1932


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-28 07:36 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by shintkb** [comment] 2017-07-28 07:39
The problem is not solved
