### ISSUE TITLE
SSL verification error on Windows

### ISSUE THREAD

**Issue by petebachant** [ContinuumIO/anaconda-issues#494] opened 2015-10-26 13:50 UTC
I am using Anaconda 3 x64 on Windows and I am getting SSL certificate verify failures. Output and root env are shown below.

``` bash
conda update --all
Fetching package metadata: SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
...
Solving package specifications: ................................................................................................................................................................................................................................................................................
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: 'zlib' has unsatisfiable dependencies (see 'conda info zlib')

Note that the following features are enabled:
  - vc9
  - vc14
  - vc10
```

``` yaml
name: root
dependencies:
- _license=1.1=py34_0
- alabaster=0.7.3=py34_0
- anaconda=2.3.0=np19py34_0
- anaconda-client=1.0.2=py34_0
- argcomplete=1.0.0=py34_0
- astropy=1.0.4=np19py34_0
- babel=2.1.1=py34_0
- bcolz=0.11.3=py34_0
- beautiful-soup=4.3.2=py34_1
- beautifulsoup4=4.4.1=py34_0
- bitarray=0.8.1=py34_1
- blaze-core=0.8.3=py34_0
- blz=0.6.2=np19py34_1
- bokeh=0.10.0=py34_0
- boto=2.38.0=py34_0
- bottleneck=1.0.0=np19py34_0
- certifi=2015.9.6.2=py34_0
- cffi=1.2.1=py34_0
- clyent=0.4.0=py34_0
- colorama=0.3.3=py34_0
- comtypes=1.1.2=py34_0
- conda=3.18.3=py34_0
- conda-build=1.18.0=py34_0
- conda-env=2.4.2=py34_0
- configobj=5.0.6=py34_0
- cryptography=0.9.3=py34_0
- cython=0.23.4=py34_0
- cytoolz=0.7.3=py34_0
- datashape=0.4.7=py34_0
- decorator=4.0.4=py34_0
- docutils=0.12=py34_1
- dynd-python=0.6.5=np19py34_0
- fastcache=1.0.2=py34_0
- flask=0.10.1=py34_1
- funcsigs=0.4=py34_0
- greenlet=0.4.9=py34_0
- h5py=2.5.0=np110py34_2
- idna=2.0=py34_0
- ipykernel=4.1.0=py34_0
- ipython=4.0.0=py34_0
- ipython-notebook=4.0.4=py34_0
- ipython-qtconsole=4.0.1=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=4.0.3=py34_0
- itsdangerous=0.24=py34_0
- jdcal=1.0=py34_0
- jedi=0.9.0=py34_0
- jinja2=2.8=py34_0
- jsonschema=2.4.0=py34_0
- jupyter=1.0.0=py34_0
- jupyter_client=4.1.1=py34_0
- jupyter_console=4.0.3=py34_0
- jupyter_core=4.0.6=py34_0
- launcher=1.0.0=1
- llvmlite=0.7.0=py34_5
- lxml=3.4.4=py34_0
- markdown=2.6.2=py34_0
- markupsafe=0.23=py34_0
- matplotlib=1.4.3=np19py34_1
- menuinst=1.0.4=py34_0
- mingw=4.7=1
- mistune=0.7.1=py34_0
- mock=1.3.0=py34_0
- multipledispatch=0.4.8=py34_0
- nbconvert=4.0.0=py34_0
- nbformat=4.0.1=py34_0
- networkx=1.10=py34_0
- nltk=3.0.5=py34_0
- node-webkit=0.10.1=0
- nose=1.3.7=py34_0
- notebook=4.0.6=py34_0
- numba=0.21.0=np19py34_0
- numexpr=2.4.4=np19py34_0
- numpy=1.10.1=py34_0
- odo=0.3.4=py34_0
- openpyxl=2.0.2=py34_0
- pandas=0.16.2=np19py34_0
- patch=2.5=0
- path.py=8.1.2=py34_0
- patsy=0.4.0=np19py34_0
- pbr=1.3.0=py34_0
- pep8=1.6.2=py34_0
- pickleshare=0.5=py34_0
- pillow=3.0.0=py34_0
- pip=7.1.2=py34_0
- ply=3.8=py34_0
- psutil=3.2.2=py34_0
- py=1.4.30=py34_0
- pyasn1=0.1.7=py34_0
- pycosat=0.6.1=py34_0
- pycparser=2.14=py34_0
- pycrypto=2.6.1=py34_3
- pyflakes=1.0.0=py34_0
- pygments=2.0.2=py34_0
- pyopenssl=0.15.1=py34_1
- pyparsing=2.0.3=py34_0
- pyqt=4.10.4=py34_1
- pyreadline=2.1=py34_0
- pytables=3.2.2=np19py34_0
- pytest=2.8.1=py34_0
- python=3.4.3=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.6=py34_0
- pywin32=219=py34_0
- pyyaml=3.11=py34_2
- pyzmq=14.7.0=py34_0
- qtconsole=4.1.0=py34_0
- requests=2.8.1=py34_0
- rope=0.9.4=py34_1
- runipy=0.1.3=py34_0
- scikit-image=0.11.3=np19py34_0
- scikit-learn=0.16.1=np19py34_0
- scipy=0.16.0=np19py34_0
- seaborn=0.6.0=np19py34_0
- setuptools=18.4=py34_0
- simplegeneric=0.8.1=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sockjs-tornado=1.0.1=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- spyder=2.3.7=py34_1
- spyder-app=2.3.7=py34_0
- sqlalchemy=1.0.8=py34_0
- statsmodels=0.6.1=np19py34_0
- sympy=0.7.6.1=py34_0
- toolz=0.7.4=py34_0
- tornado=4.2.1=py34_0
- traitlets=4.0.0=py34_0
- ujson=1.33=py34_0
- virtualenv=13.0.1=py34_0
- werkzeug=0.10.4=py34_0
- wheel=0.26.0=py34_1
- xlrd=0.9.4=py34_0
- xlsxwriter=0.7.5=py34_0
- xlwings=0.4.1=py34_0
- xlwt=1.0.0=py34_0
- zlib=1.2.8=vc10_2
- pip:
  - acspy (c:\users\pete\google drive\python\acspy)==0.0.3
  - airfoilprep.py==0.1.0
  - blaze==0.8.3
  - blinker==1.4
  - commonmark==0.5.4
  - daqmx==0.0.2
  - django==1.8.4
  - feedgenerator==1.7
  - foampy==0.0.3
  - guidata==1.6.2
  - guiqwt==2.3.2
  - image==1.4.1
  - imageio==1.3
  - ipython-genutils==0.1.0
  - jsanimation==0.1
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - micronopt==0.0.2
  - moviepy==0.2.2.11
  - nortek==0.0.1
  - pelican==3.6.3
  - progressbar33==2.4
  - pxl==0.0.6
  - pydaqmx==1.3.1
  - pyqtgraph==0.9.10
  - pyqwt==5.2.1
  - pytdms==0.0.2
  - python-qwt==6.1.2a6
  - rope-py3k-0.9.4==1
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.2
  - tow==0.2.0
  - tqdm==1.0
  - unidecode==0.4.18
  - wand==0.4.1
```

**Comment by almarklein** [comment] 2015-10-27 15:43
I can reproduce this on Windows with a command as simple as `conda install networkx`

**Comment by groutr** [comment] 2015-10-28 16:01
From my experience, the latest updates of certifi require updated versions of openssl (1.0.2d) and cryptography (1.0.2)

**Comment by almarklein** [comment] 2015-10-28 21:14
:P

    Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certific
    ate verify failed (_ssl.c:600): https://repo.continuum.io/pkgs/fre
    e/win-64/openssl-1.0.2d-vc10_0.tar.bz2

**Comment by groutr** [comment] 2015-10-29 16:31
Try removing certifi, updating openssl, then if you want reinstall certifi.

**Comment by petebachant** [comment] 2015-10-29 16:47
Removing `certifi` got rid of the error message, but as a default Anaconda package, I'm not sure that's really a fix. The error message came back after installing `openssl` and then `certifi`.

**Comment by GitH00t** [comment] 2015-10-29 17:03
Same problem for me.

**Comment by groutr** [comment] 2015-10-29 21:17
I forgot to mention that cryptography needs to be updated as well.

**Comment by almarklein** [comment] 2015-10-29 23:39
Confirmed that `conda remove certifi` fixes it.

**Comment by finarb** [comment] 2015-11-01 09:46
Doesnt solve ....this issue even after removing certifi

**Comment by ivan-usov** [comment] 2015-11-01 14:37
Had the same problem on Windows 10 after installing jupyter, `conda remove certifi` fixed it

**Comment by groutr** [comment] 2015-11-02 18:10
Here is an issue detailing the changes and reasons why these errors are surfacing.
https://github.com/certifi/python-certifi/issues/26

**Comment by msarahan** [comment] 2015-11-02 18:18
Thanks, @groutr .  Can you please post detailed workaround steps here, to save people having to trawl through comment history?

**Comment by gm6** [comment] 2015-11-02 21:55
Same issue here. Thanks for the solution of removing the bad guy "certifi".

**Comment by groutr** [comment] 2015-11-09 15:34
SSL verification errors after updating certifi in Anaconda:

Recently, an update to the certifi package broke SSL verification.  This upgrade was necessary to ensure security for users of the Anaconda platform.  Unfortunately, we were not able to devise an upgrade path that does not require some manual user intervention.  To fix your system, please follow these steps:
Update openssl and cryptography packages to 1.0.2d and 1.0.2, respectively:

`conda update openssl cryptography`
next, update certifi:
`conda update certifi`

Problems arise when certifi is updated prior to updating openssl and cryptography.  If you are seeing SSL errors, the best way to restore your system is to:
Set ssl_verify to False in .condarc

  1. In .condarc, set the following
    * ssl_verify: False
    Note that this DISABLES verification of SSL certificiates.
  2. Upgrade openssl and cryptography:
    `conda update openssl cryptography`
  3. Update certifi:
    `conda update certifi`
  4. Re-enable SSL verification by removing the ssl_verify line from .condarc


Why did SSL Verification Break?
---------------------------------------------
This is explained very well in this blog post:
https://lukasa.co.uk/2015/04/Certifi_State_Of_Union/

The short story is, the updated certifi removed old, insecure certificates.  The new certificates in certifi can only be used by OpenSSL >=1.0.2  Along with OpenSSL, cryptography needs to be updated (compiled against the new openssl package).

There was a lengthy discussion in this issue that touches a number of good points:
https://github.com/certifi/python-certifi/issues/26

Here are two comments from the author/maintainer of certifi that justify why the updates to certifi were the Right Thing to do.
1. "However, a user who is using certifi presumably is hoping for somewhat regular updates for security purposes. It defeats those security purposes to keep old, weak certificates in the bundle. The 1024-bit roots were removed for a reason. Given that I have to provide both, it seems to me to be totally defensible to go secure-by-default: I would much rather say that I handed you an unloaded gun and a bullet and you loaded it, pointed it at your foot, and shot yourself, than say that I handed you a loaded gun pointed at your foot and said "don't forget to take the bullet out!"."

2. "I'd like to address something else that I think is coming across in these comments, which is that there is a sense that projects concerned with security should just make you more secure without ever stopping your software from working. That's simply not how security works. If anyone deployed certifi on the assumption that, if your web request worked on day X it would therefore work on day X+1, I am sorry but we failed to communicate how security software works.

Security software works by breaking your application any time it does something that fails to meet a certain security threshold. Whenever you change your application or your dependencies, what previously worked may not work. In this sense, certifi is exactly like AppArmor/SELinux: each change to either those or your codebase risk breaking your application.

In this case, certifi broke your application because the security of your web request was based on whether or not someone was able to crack one of the 1024-bit keys used by certain CAs. Those keys are weak, and at a certain point we do need to stop trusting them. Mozilla, Chrome, IE, and Safari have all stopped trusting them: why are you?

Cracking those 1024-bit keys is within the computational reach of nation-state attackers at this stage, and is not far from the reach of large organisations (e.g. Amazon). A certificate chain is only as strong as its weakest link, and a 1024-bit key is judged to be unacceptably weak by all reputable authorities in this area. The fact that we didn't by default protect users from them for a whole year is arguably a dereliction of duty on our part. Our most recent change was to step up our default protection and force you to consciously weaken it, or take steps to mitigate."

What if I just remove certifi?
--------------------------------------------
Here is why that is potentially a bad idea.  From the Requests Documentation:
"By default Requests bundles a set of root CAs that it trusts, sourced from the Mozilla trust store. However, these are only updated once for each Requests version. This means that if you pin a Requests version your certificates can become extremely out of date.

From Requests version 2.4.0 onwards, Requests will attempt to use certificates from certifi if it is present on the system. This allows for users to update their trusted certificates without having to change the code that runs on their system.

For the sake of security we recommend upgrading certifi frequently!"

Since requests has been updated recently in the Anaconda repositories, the certificates that ship with requests are almost identical to certifi.  The reason why certifi was separated out of requests by the developers was to permit users to update the certificates independently of updating requests.  Requests will attempt to use certifi's certificate bundle and fall back onto its own built-in bundle.  It is possible, especially on systems where requests is pinned to a certain version, for the certificates to become out of date.  The certifi packages fixes this problem by always providing a secure, updated bundle of certificates.

**Comment by Sanojkumar** [comment] 2015-11-09 21:42
When I am trying to update openss1 package: conda update openss1
1) It says that does not exists in C:/Anaconda3 directory.
Then I am trying to install that and I am getting this error: conda install openss1
Fetching package metadata: ....
Error: No packages found in current win-64 channels matching: openss1

Any idea?

**Comment by Sanojkumar** [comment] 2015-11-09 22:05
I have Windows7 X64 bit machine. I was not able to find .condarc file. Therefore I can not disable it. But I was able to remove certifi and update openssl and cryptography. When I re-installed certifi, my other updates were still giving SSL certification error. Therefore I removed certifi again and it is working. Therefore a work around will be better for future updates.

**Comment by groutr** [comment] 2015-11-12 17:35
The `.condarc`, if it exists, should be in your home folder (on windows that would be your folder in C:\Users).  If `.condarc` does not exists, you can create the file.

**Comment by Flaviolib** [comment] 2015-11-17 14:16
Groutr, Man thanks a lot. I was having this issue for I long time. I tried to solve it 2 mths ago and I gust give up. So literally I stopped to use python.

So I did the step where disable SSL verification a than I installed "openssl" (I hadn't it previously) and reinstalled "certifi" ( I removed it trying fixing). Both installations was smooth and fine.

But.. After it I tried to run  "conda update --all" I received the following msg: 


C:\Users\Flavio\Documents\python\python\PVaR>conda update --all
Fetching package metadata: ....
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: 'openssl' has unsatisfiable dependencies (see 'conda info openssl')

Note that the following features are enabled:
  - vc9
  - vc14
  - vc10

**Comment by msarahan** [comment] 2015-11-17 14:25
That is due to a bug in conda. Please run

conda update conda

Then try again.

**Comment by Flaviolib** [comment] 2015-11-18 11:23
Hi mate, same thing.

It says that conda is already updated see below. And I still just able to install or update anything if I keep set ssl_verify False

 C:\Users\Flavio\Documents\python\python\PVaR>conda update conda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at C:\Users\Flavio\Anaconda3:
#
conda                     3.18.5                   py34_0

**Comment by pmkelly00** [comment] 2015-11-23 15:49
I've been wrestling with this issue for over a week.  Although I have a workaround that seems to take, I am extremely confused at this point.  Given this is a security feature, I don't want to simply disable it.  I was able to make things work by downgrading my certifi package to a previous version through the following commands:

          conda config --set ssl_verify False
          conda install certifi=14.05.14
          conda config --set ssl_verify True

Was this smart?  I have no idea.  But then I noticed the person above solved everything by reinstalling Anaconda.  Looking at the changelog, it looks like certifi has been removed altogether from the Anaconda distribution:

          http://docs.continuum.io/anaconda/changelog

Does this mean they have removed the security features altogether?  Or is it now handled by another package?  Should I simply delete the package from my version of the distribution?

Thanks.  These issues are making my head spin.

**Comment by marcinwolak** [comment] 2015-12-22 16:07
Hey pmkelly00, your last comment was from almost a month ago. Have you resolved this issue?

**Comment by pmkelly00** [comment] 2015-12-23 14:33
Thanks for getting back to me.  To be honest, I am still confused but am not receiving any error messages at this time.

I am seeing what appears to be conflicting guidance about the certifi package.  One of the posts above suggests you should not delete it, and yet the latest anaconda package does not include it by default.  

Should I keep it in my local distribution(s) or get rid of it?  Does conda/anaconda make use of it at all?

Thanks.

**Comment by remram44** [comment] 2016-02-21 17:47
I'm getting this also. It is likely not a client error...

<img width="300" alt="screen shot 2016-02-21 at 12 46 30" src="https://cloud.githubusercontent.com/assets/426784/13204256/4df1ae72-d899-11e5-8c1b-eb09b12aae53.png">

```
$ curl -LO https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: unable to get local issuer certificate
```

**Comment by H0R5E** [comment] 2016-04-12 08:21
Well the problem for me was caused by a channel address using the old binstar web address, where the certificate appears to have expired. Fixed by switching the channel to anaconda.org address.

**Comment by statchaitya** [comment] 2016-05-23 13:03
Hi guys, I am facing the same problem at work. Its been like a week now.

In my system, the 'conda install' command also throws out a SSL Verification Error. Its saying 'could not connect to http://repo.continuum....'. So basically, I am not able to install/remove any package from the cmd. Is this problem because of my network settings I am wondering? The fact that I am doing all these things from my work system? I am working on win64bit. I am not able to download MinGW through either of the sources, cmd using conda OR setup.exe (that is also throwing an error while installing mingw-get')

Until now, I've tried troubleshooting using the steps provided by groutr. I was surprised that my conda env. did not have certifi package. So I downloaded it from the source (can't get it through cmd). Now interestingly, I can call certifi from the repl, but when I try to remove/update it using 'conda install/update'.. Conda tells me that there is no package named 'certifi' in the path C:\Anaconda2 environment. How is that even possible?

Sorry if my comment is very noobish but I am desperately trying to find a solution here. My background is not from CS but from Statistics. Any help/suggestions is appreciated. Basically what I trying to do is get g++ (minGW) which will get theano (and hence keras) up and running. Thanks.

**Comment by remram44** [comment] 2016-05-23 13:21
Installing with pip or from source will not add the package to conda's list and will probably break stuff. Bad plan there.

Try to follow the steps above, changing your channels to anaconda.org, and upgrading conda.

**Comment by kschluns** [comment] 2016-08-09 17:42
I am having the same problem as pmkelly00 and statchaitya. I originally installed anaconda back in early 2016 and first came across this problem a few months ago. I found this post and tried following groutr's instructions. However, I never had certifi installed in the first place. So I followed all instructions but instead of updating certifi, I installed it. When I set the ssl verify back to true, I still am getting the same error:

Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

Note that my error code is 645, which is different than the original post, 600. Not sure if that's relevant.

After this I just tried uninstalling and re-installing Anaconda. Again, I notice that it comes with the most updated openssl and cryptography, but is missing certifi. I am having the same exact error mentioned previously. I also tried the recommended solution from groutr and still have the errors.


conda info -a
```
Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Users\I53224\AppData\Local\Continuum\Anaconda3  (writable)
  default environment : C:\Users\I53224\AppData\Local\Continuum\Anaconda3
     envs directories : C:\Users\I53224\AppData\Local\Continuum\Anaconda3\envs
        package cache : C:\Users\I53224\AppData\Local\Continuum\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\I53224\.condarc
         offline mode : False
    is foreign system : False

# conda environments:
#
root                  *  C:\Users\I53224\AppData\Local\Continuum\Anaconda3

sys.version: 3.5.2 |Anaconda 4.1.1 (64-bit)| (default...
sys.prefix: C:\Users\I53224\AppData\Local\Continuum\Anaconda3
sys.executable: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\python.exe
conda location: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda
conda-build: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-build.exe
conda-convert: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-convert.exe
conda-develop: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-metapackage.exe
conda-pipbuild: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-pipbuild.exe
conda-render: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-render.exe
conda-server: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-server.exe
conda-sign: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-sign.exe
conda-skeleton: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts\conda-skeleton.exe
user site dirs: C:\Users\I53224\AppData\Roaming\Python\Python35

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
PATH: C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Library\bin;C:\ProgramData\Oracle\Java\javapath;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files (x86)\Silk\SilkTest;C:\Program Files (x86)\Silk\SilkTest\ng\gui;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Users\I53224\AppData\Local\Continuum\Anaconda3;C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Scripts;C:\Users\I53224\AppData\Local\Continuum\Anaconda3\Library\bin;C:\Program Files (x86)\IDM Computer Solutions\UltraCompare\;C:\Users\I53224\AppData\Local\Pandoc\
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

after trying solution from groutr:
conda list 
```
_nb_ext_conf              0.2.0                    py35_0
alabaster                 0.7.8                    py35_0
anaconda                  4.1.1               np111py35_0
anaconda-client           1.4.0                    py35_0
anaconda-navigator        1.2.1                    py35_0
argcomplete               1.0.0                    py35_1
astropy                   1.2.1               np111py35_0
babel                     2.3.3                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.4.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.0                   py35_0
boto                      2.40.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
certifi                   2016.2.28                py35_0
cffi                      1.6.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.1.11                   py35_0
conda-build               1.21.3                   py35_0
conda-env                 2.5.2                    py35_0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.4                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24                     py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.10.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.1                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.3.1                    py35_0
ipython                   4.2.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                4.1.1                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.3.0                    py35_0
jupyter_console           4.1.1                    py35_0
jupyter_core              4.1.0                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.11.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.0                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.1               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.2                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.1.0                    py35_0
nb_conda                  1.1.0                    py35_0
nb_conda_kernels          1.0.3                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.0.1                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.1                    py35_0
numba                     0.26.0              np111py35_0
numexpr                   2.6.0               np111py35_0
numpy                     1.11.1                   py35_0
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2h                   vc14_0  [vc14]
pandas                    0.18.1              np111py35_0
partd                     0.3.4                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.2                    py35_0
pillow                    3.2.0                    py35_1
pip                       8.1.2                    py35_0
ply                       3.8                      py35_0
psutil                    4.3.0                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.2.3                    py35_0
pygments                  2.1.3                    py35_0
pyopenssl                 0.16.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      4.11.4                   py35_6
pyreadline                2.1                      py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.4                   py35_0
pywin32                   220                      py35_1
pyyaml                    3.11                     py35_4
pyzmq                     15.2.0                   py35_0
qt                        4.8.7                    vc14_8  [vc14]
qtconsole                 4.2.1                    py35_0
qtpy                      1.0.2                    py35_0
requests                  2.10.0                   py35_0
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.7                   py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.17.1              np111py35_1
setuptools                23.0.0                   py35_0
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.16.9                   py35_2
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.1                    py35_0
sphinx_rtd_theme          0.1.9                    py35_0
spyder                    2.3.9                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.3                      py35_1
traitlets                 4.2.1                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
werkzeug                  0.11.10                  py35_0
wheel                     0.29.0                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.2                    py35_0
xlwings                   0.7.2                    py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]
```

**Comment by NeilBryant** [comment] 2016-08-29 16:22
I was having issues like statchaitya; Miniconda install, `conda list` only shows 14 packages, and openssl, cryptography, and certifi aren't among them. Conda choking out on this error, and can't download anything.

My issue seems to be because I had HTTP_PROXY set, but not HTTPS_PROXY. I set that, and the error went away. See:
[Configure Conda for use behind a proxy server](http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers)

**Closed** 2016-12-26 23:42 UTC
