### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by NagarajYe** [ContinuumIO/anaconda-issues#4596] opened 2017-08-24 13:27 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda2
#
# You don't appear to have the necessary permissions to install packages
# into the install area 'C:\ProgramData\Anaconda2'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda2"

```
## System information
```
platform: win-64
version: 1.6.2
conda: 4.3.21
qt: 5.6.2
language: nl_NL
python: 2.7.13
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
pyqt: 5.6.0
```

**Comment by goanpeca** [comment] 2017-08-24 13:27
**See Issue #1845 for more information on how to fix this.**

---

Closing as duplicate of #1845


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-24 13:27 UTC
Labels: pkg:navigator

**Comment by Enphass** [comment] 2018-03-11 18:17
Traceback (most recent call last):
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\ProgramData\Anaconda2\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\ProgramData\Anaconda2\lib\site-packages\psutil\__init__.py", line 666, in cmdline
return self._proc.cmdline()
File "C:\ProgramData\Anaconda2\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=4596)

**Comment by goanpeca** [comment] 2018-03-11 19:24
@Enphass please open the Anaconda Prompt and run

```
anaconda-navigator --reset
```

**Comment by Enphass** [comment] 2018-03-11 19:25
thank you!!!!
