### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by yixd** [ContinuumIO/anaconda-issues#4575] opened 2017-08-24 02:44 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 22:43:46.648 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 22:43:46.709 NotebookApp] Serving notebooks from local directory: /home/yixd
[I 22:43:46.709 NotebookApp] 0 active kernels 
[I 22:43:46.709 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=5b5cca6860420a42f2fcef96f9ce3e8dc181f7524169957b
[I 22:43:46.709 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:43:46.711 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=5b5cca6860420a42f2fcef96f9ce3e8dc181f7524169957b
[I 22:43:47.341 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[8672:8709:0823/224347.346023:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

```
## System information
```
python: 3.6.1
language: en_US
os: Linux;4.4.0-92-generic;#115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-08-24 03:13
Try using a different browse

**Comment by goanpeca** [comment] 2017-08-30 13:48
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-08-30 13:48 UTC
Labels: pkg:navigator, reso:duplicate
