### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by AhmedRebai** [ContinuumIO/anaconda-issues#9232] opened 2018-04-24 12:25 UTC
## Main error
Application <b>spyder</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/ahmed/anaconda3/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/home/ahmed/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 14, in <module>
    import zmq
  File "/home/ahmed/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/ahmed/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/ahmed/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/ahmed/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/ahmed/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/ahmed/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

```
## System information
```
python: 3.6.3
language: en_US
os: Linux;4.4.0-116-generic;#140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.7
```

**Comment by goanpeca** [comment] 2018-04-24 12:28
Closing as duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/9180

**Closed by goanpeca** 2018-04-24 12:28 UTC
Labels: pkg:navigator, pkg:spyder
