### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by DanteLuo** [ContinuumIO/anaconda-issues#3796] opened 2017-08-01 17:12 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 13:12:18.075 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 13:12:18.091 NotebookApp] Serving notebooks from local directory: /home/ztluo
[I 13:12:18.091 NotebookApp] 0 active kernels 
[I 13:12:18.091 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=46725df71e35e84cf866bd83e6420cf238e95ceb25e17110
[I 13:12:18.091 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:12:18.092 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=46725df71e35e84cf866bd83e6420cf238e95ceb25e17110
[12755:12791:0801/131218.334944:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[I 13:12:18.340 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1

```
## System information
```
python: 3.6.1
language: en_CA
os: Linux;4.10.0-28-generic;#32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-11-14 22:59
**See issue #2098 for more information on how to fix this issue.**

---

Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-11-14 22:59 UTC
