### ISSUE TITLE
Graphviz seem to miss PNG support. 

### ISSUE THREAD

**Issue by Carreau** [ContinuumIO/anaconda-issues#485] opened 2015-10-20 18:28 UTC
See first report blaze/dask#788

When using `dask.visualize()` the visualization fails if graphviz (actually `dot`executable) is installed via conda.

```
Format: "png" not recognized. Use one of: canon cmap cmapx cmapx_np dot eps fig gv imap imap_np ismap pic plain plain-ext pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4
```

On OS X  a simple workaround is to brew-install graphiz which then works great. 

Thanks, 

---

OS X 10.10.3, conda 3.18.3 in python 3.4 root environment.

**Comment by bryevdv** [comment] 2015-10-20 19:19
I can confirm that I have run into this issue before as well.

**Comment by mrocklin** [comment] 2015-11-16 16:29
This has come up several times from dask users.  Example here https://github.com/blaze/dask/issues/835

I'm telling people that this packages is broken and that they should uninstall it.  Is this incorrect?  Given how prevalent this library is within system installers (brew, apt-get) it seems that this package might cause more pain than its worth.

**Comment by ccordoba12** [comment] 2015-11-16 16:35
I think there's a fix in conda-recipes for this, right @ahmadia?

**Comment by fonnesbeck** [comment] 2015-11-16 16:36
Removing conda's graphviz and using Homebrew's cask binary has resolved these issues for me. I was getting output files with zero size and no error messages (other than an dyld warning) under the conda distribution.

**Comment by joejacobs** [comment] 2015-11-16 19:02
Having the same issue on a Debian. Solved by uninstalling graphviz from anaconda and then re-installing graphviz with apt-get.

**Comment by groutr** [comment] 2015-11-19 17:47
Looks like our graphviz is missing libgd.  I'll update that as soon as I can.

**Comment by caseyclements** [comment] 2015-11-19 17:50
Thanks Ryan!

**Comment by michaelaye** [comment] 2015-12-17 02:04
same problem here.

**Comment by WangZhwei** [comment] 2016-01-01 13:17
thank you ,@joejacobs, same problem solved as you did

**Comment by WangZhwei** [comment] 2016-01-01 13:18
thank you!  @joejacobs, same problem solved on Ubuntu.

**Comment by kalefranz** [comment] 2016-01-16 23:35
@groutr Did we get this graphviz issue fixed?

**Comment by ozancaglayan** [comment] 2016-02-04 16:28
I just encountered this issue.

**Comment by bscipio** [comment] 2016-02-10 03:00
Same problem here.

**Comment by bryevdv** [comment] 2016-02-16 00:20
ping @groutr

**Comment by groutr** [comment] 2016-02-17 17:53
Graphviz on linux now has png support.

**Comment by eriknw** [comment] 2016-02-26 17:39
@groutr, Graphviz on linux does not work if libtool (libltdl) is not installed on the system.

**Comment by ijstokes** [comment] 2016-05-06 02:05
@groutr Any love on the OS X front? Just ran into this myself.  Thank you @mrocklin for the nice error message that pointed me here!  Yes, homebrew to the rescue.  That solved it for me.

**Comment by mrocklin** [comment] 2016-05-06 04:46
I'm going to again recommend that we just remove this package entirely until we have a proper fix for it. A broken package feels far worse than a missing package.

**Comment by bryevdv** [comment] 2016-05-06 06:04
Agreed.

**Comment by ccordoba12** [comment] 2016-05-07 20:51
All people interested in seeing this one solved, please follow conda-forge/staged-recipes#568 :-)

**Comment by mcg1969** [comment] 2016-09-09 16:46
Ping. @csoja this is still busted. Ryan was assigned to it, so now it's not assigned to anyone. Note that `conda install -c conda-forge graphviz` solves the problem for me, which involves updating `jpeg` and `libtiff` from conda-forge as well.

**Comment by jni** [comment] 2016-09-16 02:33
@mcg1969 your suggestion still seems to be pulling graphviz from defaults for me... Anyone have any idea how to force conda to download the conda-forge version?

```
 ~ $ conda search -c conda-forge graphviz
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
graphviz                     2.38.0                        0  conda-forge
                             2.38.0                        1  conda-forge
                          *  2.38.0                        2  http://repo.continuum.io/pkgs/free/osx-64/
```

**Comment by ccordoba12** [comment] 2016-09-16 02:58
@mcg1969, I was the one who built graphviz for conda-forge. Unfortunately I haven't had time to move it to defaults, and also to add `python-graphviz` to it.

**Comment by mrocklin** [comment] 2017-02-02 23:59
This issue continues to affect Dask users.  It would be great if we could remove this faulty package. 

http://stackoverflow.com/questions/42014458/dask-not-isntalling-graphviz-dependency

**Comment by abalter** [comment] 2017-02-03 01:15
@mrocklin I'm just confused because the `dask.dot` graph creating capability seems like a major component of `dask`. Seems like if you aren't going to support being able to `conda install dask` and have `dask.dot` import properly, you should remove the `dask.dot` feature. Better yet, fix it :)

**Comment by mrocklin** [comment] 2017-02-03 01:24
We tell people to install graphviz with their system installer and to avoid conda.  Then things work fine.  This would be a user's default behavior if this errant conda package was removed.

**Comment by Carreau** [comment] 2017-02-03 03:19
Just out of precision for @abalter , it is not because @mrocklin worked/is working  for/with continuum that he have the authority or the influence to have the libpng package fixed or removed. Dasked dot is a feature of Dask, on which @mrocklin have most control, and it is a useful feature for many of the non-conda user, as well as conda user that manually set it to use the system libpng.

So unfortunately that's where we can't do much except maybe loby higher in the food chain.

Would tweeting at continuum/pwang/toliphant help to push this forward ?

**Comment by abalter** [comment] 2017-02-03 07:24
Oh golly. Sorry if I stepped on toes. Thanks for pointing this out @Carreau. @mrocklin -- if you say it's not working right now, I'm guessing there is a very good reason for it. I've asked our sysadmin to install graphviz natively.

**Comment by bryevdv** [comment] 2017-02-03 17:31
I also asked recently @csoja offline about removing this broken package, but I will second the request again here. It has never fully worked in four years, AFAIK.

**Comment by mcg1969** [comment] 2017-02-03 18:02
My understanding is that, technically, it _does_ work. It just doesn't do what people logically expect it should: install the base graphviz package _and its python bindings_. Nevertheless I agree with the conclusion that it would reduce confusion to remove it.

**Comment by mrocklin** [comment] 2017-02-03 18:10
It's not that it's missing the python bindings, it's that it won't emit png
files.

**Comment by mrocklin** [comment] 2017-02-03 18:11
Even if you pip install graphviz afterwards the issues still persist.

**Comment by mcg1969** [comment] 2017-02-03 18:30
Ah, thanks for the education!

**Comment by bryevdv** [comment] 2017-02-03 19:00
yes, it's definitely just plain broken. I've never even wanted it for the python bindings, I wanted it for a sphinx integration (which uses `dot` directly, not the python bindings). Graphviz has an unusual and baroque build system and I gather this has been part of the problem. But if we can't prioritize fixing it, it should just be removed at this point.

**Comment by Carreau** [comment] 2017-02-03 20:35
> Oh golly. Sorry if I stepped on toes.

No I don't think you did, don't worry. The distinction Conda/Anaconda/Continuum and various packages/packager can be hard to grasp often. So I was just offering clarifications as to why things are as they are now.

**Comment by DavidMertz** [comment] 2017-02-10 20:04
Just to chime in, this bit me again today; having done a `rm -rf anaconda3` and fresh install recently.  I keep forgetting this broken corner of the Anaconda ecosystem.  A working graphviz is a very important tool for lots of purposes, and what `conda install graphviz` gets you is definitely **not** a working graphviz.

I have to teach this in a week, and have a special new dread of getting things working for students.

On *my* system, I have graphviz itself installed with `brew`, then use `pip` to install the Python bindings.  The "attractive nuisance" of using `conda` for what it obviously should do (and **appears** to do) is a problem.

**Comment by ccordoba12** [comment] 2017-02-10 20:31
> Graphviz has an unusual and baroque build system and I gather this has been part of the problem

Not now, i.e. after I created a good recipe for conda-forge.

The real problem is that the Anaconda team is always understaffed for the amount of packages we manage.

> I have to teach this in a week, and have a special new dread of getting things working for students.

Ok, I'll create packages for `graphviz` and `python-graphviz` during the weekend.

I can't promise when they'll be uploaded though because that doesn't depend on me.

**Comment by Carreau** [comment] 2017-02-10 21:14
Thanks @ccordoba12 for taking some time to do it.

**Comment by DavidMertz** [comment] 2017-02-11 20:44
I think the `pip install pygraphviz` was really just irrelevant.  But I was distracted by the fact I knew I had the `brew install` working system wide, yet the message said “You need both graphviz and the Python bindings.”  If I understand correctly `pygraphviz` and `graphviz` are two separate Python packages (on PyPI) that serve mostly the same purpose, but with slightly different APIs.  That is, either one provides Python functions/classes to create graphs, then passes rending to the actual graphviz library (or maybe to the executables—dot, neato, etc).

In particular, Dask chose to use the Python module called `graphviz` rather than the one called `pygraphviz`.  There are also packages `graphviz-python` and `pydot` that also “compete” with those two.  I have no opinion on the choice of Python library, I trust Matt’s judgement (or whoever made the choice).

Whatever it is that `conda install graphviz` installs is **not** a Python binding, but is *intended to be* the system library/utilities.  However, it is a completely non-functional version of that library/utilities.  As Matt noted in the GH issue, it would be FAR better for that not to exist at all than to install something non-functional.

Actually, I guess the breakage is slightly more subtle.  Maybe in `libgvplugin_dot_layout.dylib` or somewhere similar.  I can do this:

```bash
% conda create -n graphviz python graphviz
% which dot
/usr/local/bin/dot
activate graphviz
(graphviz) % which dot
//anaconda/envs/graphviz/bin/dot
(graphviz) % dot atoms.dot -Tpng -oatoms.png
(graphviz) % deactivate
% dot atoms.dot -Tpng -oatoms.png
```
Both my conda graphviz and my system graphviz create a PNG from the command line.

**Comment by ccordoba12** [comment] 2017-02-13 05:15
There are new `graphviz` packages in our default channels that have PNG support since the beginning of 2017. I didn't know that, please try them!

----

@DavidMertz, our `graphviz` package contains only C libraries and binaries (e.g. the `dot` executable). We decided to call `python-graphviz` to the Python bindings that on PyPi are called simply `graphviz`.

That's an unfortunate clash of names, but after a very [long discussion](https://github.com/conda-forge/staged-recipes/pull/568) in conda-forge, both Continuum and conda-forge decided that the best way to solve this conflict was to use the `graphviz` name for the original (i.e. `C`) project, and `python-graphviz` for its bindings (I know there are several other Python bindings, but none of them is just called `graphviz`).

This is just another proof that conda is a general package manager and not just a `pip` replacement of sorts. So

    conda install graphviz

and

    pip install graphviz

will always give different results, and we have to learn to live with that (and make users aware of that too).

**Closed** 2017-02-13 16:28 UTC

**Comment by DavidMertz** [comment] 2017-02-13 19:12
My training customer has a firewall, and a private repo.  They frequently mirror the main channel, but I'm pretty sure they will not mirror `conda-forge`.  Is it possible to get `python-graphviz` into the main channel?

**Comment by ccordoba12** [comment] 2017-02-13 23:42
> Is it possible to get python-graphviz into the main channel?

Yep, I added a recipe for it to our internal repo. It should be available shortly.

**Comment by Carreau** [comment] 2017-02-13 23:48
Thank you Carlos, much appreciated !

On Feb 13, 2017 15:42, "Carlos Cordoba" <notifications@github.com> wrote:

Is it possible to get python-graphviz into the main channel?

Yep, I added a recipe for it to our internal repo. It should be available
shortly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ContinuumIO/anaconda-issues/issues/485#issuecomment-279560366>,
or mute the thread

**Comment by mrocklin** [comment] 2017-05-15 16:14
Windows error reported here: http://stackoverflow.com/questions/43983089/dask-dot-runtimeerror-visualizing

They seem to have updated graphviz already.

**Comment by Joshuaalbert** [comment] 2017-05-15 16:24
To clarify, the setup for the SO issue that @mrocklin just refered to is:
`pip install graphviz` for the python bindings which installs `0.7`
`conda install graphviz` for the system executables which installs `2.38.0`

and I just now got it to work by installing graphviz from http://www.graphviz.org/ and then putting this before the conda graphviz path (I should really just remove the conda graphviz). So it seems the conda graphviz is the issue.

**Comment by ccordoba12** [comment] 2017-05-15 20:27
> Windows error reported here: http://stackoverflow.com/questions/43983089/dask-dot-runtimeerror-visualizing

I solved this problem already and asked the Anaconda team to create packages for `python-graphviz` (which is the name for the package you get when you run `pip install graphviz`).

This package was created for Mac and Linux, but (I don't know why) not for Windows. I'll ask the team again.

@Joshuaalbert, sorry for the inconvenience this caused you.

@mrocklin, please remember that `conda install graphviz` gives you the C libraries and executables. The Python bindings that dask use are obtained with `conda install python-graphviz`.

**Comment by ccordoba12** [comment] 2017-05-15 22:55
Packages for `python-graphviz` on Windows are now available in our channels.

Thanks for your patience.

**Comment by poleguy** [comment] 2017-06-22 20:37
I can't get this to work on windows. Depending on which of the various pip/conda/path commands listed here I run and in what order, I get various error messages or no output with no error message. Can someone check that this should work on windows?

**Comment by ccordoba12** [comment] 2017-06-22 22:34
It is working on Windows. You need to run

    conda install graphviz python-graphviz

and remove the pip graphviz package to make it work.

**Comment by poleguy** [comment] 2017-06-24 04:30
I just tried again using that command on a different Windows 7 box than the one I tried the first time. It doesn't work... but now I see that the problem seems to be the handling of a space in the path to dot.py

I guess that's not really a problem with graphviz... I'm not sure where to report this as a separate bug, but it manifests itself as a link to this thread, so it's probably not bad to leave a clue here for the next guy. I'll reinstall anaconda in a path with no spaces and try again.

> 'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> Traceback (most recent call last):
>   File "G:/data/Dropbox/SVN/ppprsGui/dask_test.py", line 26, in <module>
>     dot_graph(b2_min.dask)
>  File "C:\Program Files\Anaconda3\lib\site-packages\dask\dot.py", line 227, in dot_graph
>     raise RuntimeError("Graphviz failed to properly produce an image. "
> RuntimeError: Graphviz failed to properly produce an image. This probably means your installation of graphviz is missing png support. See: https://github.com/ContinuumIO/anaconda-issues/issues/485 for more information.

**Comment by poleguy** [comment] 2017-06-24 12:17
No dice. I reinstalled the latest anaconda3 on windows 7 in a path with no space.
It now gives no error, but does not produce any image.

It returns only:
dask.array<amin-aggregate, shape=(), dtype=float64, chunksize=()>

`import numpy as np`
`from dask.dot import dot_graph`
`import dask.array as da`
`a = np.random.randn(1000)`
`a2 = da.from_array(a, chunks=200)`
`b2 = a2 * 4`
`b2_min = b2.min()`
`dot_graph(b2_min.dask)`
`print(b2_min)`
