### ISSUE TITLE
Cannot Create New Environment

### ISSUE THREAD

**Issue by jlw4192** [ContinuumIO/anaconda-issues#3183] opened 2017-07-14 16:01 UTC
I can't do anything from the conda terminal or the navigator: update, install, etc. I've been told to update the navigator but that does not even work. 

## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://repo.continuum.io/pkgs/free/win-64/repodata.json.bz2>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),),)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2017-07-14 16:01
Closing as duplicate of #1932

---

Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-14 16:01 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by IntelligentFunction** [comment] 2019-08-30 12:10
This still does not appear to work, I have updated anaconda Navigator, updated Anaconda complete rebooted computer and still any new environments disappear if created using the gui. Can they either fix it, or remove it please.

**Comment by csoja** [comment] 2019-08-30 13:59
anaconda 4.x is no longer available in the defaults channel included in the latest conda - conda mostly pulls packages from the main channel now.  There are options to add these older packages back in so you can create environments with that version.  
https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/
If you are having an issue, please open a new github issue - not add a comment to a closed github issue.

**Comment by ParthikB** [comment] 2019-11-02 23:15
Inside the conda-navigator, when I click on the create button after assigning a name and python version, nothing happens! There is no loading bar in the bottom left, nothing is processing. No matter how many times I try. I tried restarting, and I even tried updating the navigator using "conda update anaconda-navigator", still no good.

Save me.

**Comment by nmorenol** [comment] 2019-11-12 14:38
I have the same problem. Any help?

**Comment by ParthikB** [comment] 2019-11-12 22:38
> I have the same problem. Any help?

I don't know man, I just used the following command and it WORKED.

`conda create -n <name> python=3.6`

You can refer here for more info:
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
