### ISSUE TITLE
Crash on Windows with Qt and Python 3.4

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-issues#654] opened 2016-02-08 15:44 UTC
In a Python 3.4 conda environment on Windows, I am trying to run:

```
from PyQt4 import QtGui
 
app = QtGui.QApplication([''])
 
class Test(QtGui.QMainWindow):
   
    def __init__(self):
        QtGui.QMainWindow.__init__(self)
        lw = QtGui.QTreeView(parent=self)
        self.setCentralWidget(lw)
 
t = Test()
t.show()
app.exec_()
```

However, this results in the Python process crashing. From browsing around existing Qt issues, it seems that this is fixed by using a more recent compiler. Indeed, switching to a Python 3.5 environment, the above example works. The build version for ``qt`` on Python 3.5 is ``vc14_5`` and on Python 3.4 is ``vc10_5``.

Of course, the easy solution is to then just use Python 3.5, but unfortunately some of the packages I need are not available there, in particular VisPy (only a 3.4 package is available).

In any case, would it be possible to re-build the conda package for qt and pyqt for Python 3.4 on Windows to avoid this issue?

**Comment by msarahan** [comment] 2016-02-08 17:24
Hi,

I'm not sure a rebuild will fix your issue.  Python 3.4 is built with VS
2010, and we keep all packages for Python 3.4 also built with VS 2010.  Bad
things can happen when MSVC runtimes are mixed.

Crashes often happen when an incorrect Qt dll gets picked up on PATH.  Are
you working in an environment other than root, or not?  Environments
prepend their PATH when activated, so they often avoid this issue.

Please let us know what you find.

Best,
Michael

**Comment by astrofrog** [comment] 2016-02-09 09:30
@msarahan - I think this is a real known issue: https://bugreports.qt.io/browse/QTBUG-22375 - I see the issue when in a Python 3.4 environment, but not a Python 3.5 environment, without changing anything else. I think the correct Qt is getting picked up.

In the Python 3.4 environment, I can also get rid of the problem by pinning the PyQt version to 4.10. It's just the 4.11 build that has an issue.

**Comment by msarahan** [comment] 2016-02-09 13:30
Thanks.  I followed your link one level deeper to https://bugreports.qt.io/browse/QTBUG-11445 - which indicates that we may not have VS 2010 SP1 installed.  I will ensure that this is installed on our build machines, and rebuild Qt if we did not have it installed.

**Comment by msarahan** [comment] 2016-02-09 13:32
By the way, the difference between the 4.10 build and the 4.11 build is that the 4.10 build was just a repackaging of Riverbank's PyQt package, which included Qt.  With 4.11, we now build both Qt and PyQt ourselves.  Sorry this has caused some growing pains.

**Comment by astrofrog** [comment] 2016-02-09 13:43
@msarahan - no problem! By the way, out of interest, can you reproduce the issue I described higher up?

**Comment by msarahan** [comment] 2016-02-09 13:47
Yes, I can reproduce your crash.  I will use your example to test the new build.

**Comment by astrofrog** [comment] 2016-02-09 13:54
@msarahan - thanks! By the way, do you have any plans to include builds for PyQt5 in the default conda channel in the future?

**Comment by msarahan** [comment] 2016-02-09 13:57
Yes, definitely.  It's just a matter of prioritizing it and getting it done.  I am the one to bother about it, by the way. @ccordoba12 has packages for Linux and Mac, but I need to do the Windows build scripts.

**Comment by astrofrog** [comment] 2016-02-09 16:15
@msarahan - perfect! I've been using some of the unofficial channels for MacOS X and Linux, but I will only be able to have users switch to PyQt5 for Glue (http://www.glueviz.org/en/stable/) by default once it's available in the main channel.

**Comment by msarahan** [comment] 2016-02-12 01:13
We have rebuilt Qt and PyQt with VS 2010 SP1.  These packages should be available soon.  The build number is 6 for Qt, and 5 for PyQt.  I'm closing this issue, but please reopen it if you have further issues.

**Closed by msarahan** 2016-02-12 01:13 UTC

**Comment by birgander2** [comment] 2016-09-23 06:54
This bug seems to be still present in the current Anaconda!?

**Comment by MSeifert04** [comment] 2016-09-23 12:49
@birgander2 I don't know but there is currently some build problem regarding pyqt so maybe it will be resolved in a few hours. Could you tell us which pyqt, astropy, sip version you're using?

**Comment by birgander2** [comment] 2016-09-26 11:05
pyqt = 4.10.4 py34_1 (this one works, I had problems with 4.11.4 py34_7). Astropy = 1.2.1, sip=4.18.

**Comment by ccordoba12** [comment] 2016-09-26 11:53
@birgander2, could you post some code that's giving you troubles?

**Comment by birgander2** [comment] 2016-09-26 11:57
Oh, exactly the above one for example!

**Comment by ccordoba12** [comment] 2016-09-26 12:00
From @astrofrog?

**Comment by birgander2** [comment] 2016-09-26 13:08
yes
