### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by Avin-Mathew** [ContinuumIO/anaconda-issues#8727] opened 2018-03-02 08:49 UTC
## Main error
Application <b>notebook</b> launch may have produced errors.
## Traceback
```
[I 14:18:06.009 NotebookApp] The port 8888 is already in use, trying another port.
[I 14:18:06.021 NotebookApp] Serving notebooks from local directory: /home/avin
[I 14:18:06.021 NotebookApp] 0 active kernels
[I 14:18:06.021 NotebookApp] The Jupyter Notebook is running at:
[I 14:18:06.021 NotebookApp] http://localhost:8889/?token=ce6afb39ed006cddbb878caf5b625ae7dba21c0d1bd6adc4
[I 14:18:06.021 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:18:06.030 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=ce6afb39ed006cddbb878caf5b625ae7dba21c0d1bd6adc4
[I 14:18:06.856 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[6413:6451:0302/141806.885076:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
[W 14:18:07.657 NotebookApp] 404 GET /static/components/moment/locale/en-gb.js?v=20180302141805 (127.0.0.1) 16.11ms referer=http://localhost:8889/tree

```
## System information
```
python: 3.6.1
language: en_GB
os: Linux;4.13.0-36-generic;#40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.4.3
```

**Comment by goanpeca** [comment] 2018-03-02 15:34
Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #2098 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-03-02 15:34 UTC
Labels: pkg:navigator, reso:duplicate
