### ISSUE TITLE
Navigator Launch Error

### ISSUE THREAD

**Issue by kkloos** [ContinuumIO/anaconda-issues#6581] opened 2017-10-11 15:38 UTC
I get the following Error when starting the Navigator. 
`Traceback (most recent call last):
File "C:\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "C:\Anaconda\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
cmds = process.cmdline()
File "C:\Anaconda\lib\site-packages\psutil\__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "C:\Anaconda\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
raise AccessDenied(self.pid, self._name)
AccessDenied: psutil.AccessDenied (pid=772)
`

I use Python 2.7.13 on Windows 7. Conda is on 4.3.29 and Navigator is up-to date. Any idea how to solve this? 

anaconda-navigator --reset yields:
`Traceback (most recent call last):
  File "C:\Anaconda\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\anaconda_navigator\app\main.py", line 101,
 in main
    from anaconda_navigator.config import CONF_PATH
  File "C:\Anaconda\lib\site-packages\anaconda_navigator\config\__init__.py", li
ne 22, in <module>
    from anaconda_navigator.config.base import (get_conf_path, get_home_dir,
  File "C:\Anaconda\lib\site-packages\anaconda_navigator\config\base.py", line 1
8, in <module>
    from anaconda_navigator.utils import encoding
  File "C:\Anaconda\lib\site-packages\anaconda_navigator\utils\__init__.py", lin
e 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Anaconda\lib\site-packages\qtpy\__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found`

**Comment by goanpeca** [comment] 2017-10-11 16:01
**See issue #1984 for more information on how to fix this.**

---

Closing as duplicate of #1984

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

**Closed by goanpeca** 2017-10-11 16:01 UTC
