### ISSUE TITLE
Spyder has generic dock icon on Mac

### ISSUE THREAD

**Issue by DanHickstein** [ContinuumIO/anaconda-issues#634] opened 2016-01-22 17:05 UTC
In https://github.com/ContinuumIO/anaconda-issues/issues/129, it was reported that Spyder previously had a generic icon on Windows and Ubuntu, but that this was then fixed. On the Mac dock, it still shows up as a generic application icon: 

![image](https://cloud.githubusercontent.com/assets/1107796/12517367/8c58539e-c0ef-11e5-8f18-3897c97aeb1f.png)

This is especially problematic, because if you open a matplotlib window from the terminal, it shows up with the same generic icon, making it impossible to locate Spyder in a sea of identical icons.

**Comment by ccordoba12** [comment] 2016-01-23 19:13
Icons are shown only for app bundles in Mac. Since Spyder is started from a terminal in Anaconda, it's not possible to show an icon for it.

----

@stuarteberg, is it possible to create a simple wrapper app bundle to fix this?

**Comment by stuarteberg** [comment] 2016-01-24 00:45
>is it possible to create a simple wrapper app bundle to fix this?

Yes.  On my machine, I can make some changes to `create_app.py` that optionally allow you to use py2app's "alias mode" feature.  I'll submit a PR with my changes tonight or tomorrow.

**Comment by ccordoba12** [comment] 2016-01-24 02:00
Thanks a lot @stuarteberg! I guess the next step would be to create a conda package for that app bundle and start distributing it in our channels, right?

**Comment by DanHickstein** [comment] 2016-01-24 02:21
Thanks! 

If you're using the py2app alias feature, does that also mean that you would be left with a double-clickable ".app" file? Having a clickable application file for Spyder would be more convenient than accessing it through the launcher.

**Comment by ccordoba12** [comment] 2016-01-24 02:49
> does that also mean that you would be left with a double-clickable ".app" file?

Yes, but it would installed inside `~/anacondaX`. However, you could start that app from Spotlight, and then you could pin it in your dock :-)

**Comment by stuarteberg** [comment] 2016-01-24 03:28
>I guess the next step would be to create a conda package for that app bundle and start distributing it in our channels, right?

I guess we have a few choices:

1. distribute `spyder.app` as a separate package, which depends on the `spyder` app
2. Add `spyder.app` to the existing `spyder` package, but don't change the the `bin/spyder` launch script
3. Add `spyder.app` to the existing `spyder` package, and change `bin/spyder` to open `spyder.app`instead of using `python.app`.

        #!/bin/sh
        open ${PREFIX}/bin/spyder.app

Which option would you like me to implement?

**Comment by stuarteberg** [comment] 2016-01-25 04:41
I submitted spyder-ide/spyder#2954 and conda/conda-recipes#560 as a possible fix for this.  You'll have to decide if you prefer option 1,2, or 3 from above.  (For now, these PRs implement option 1.)

**Comment by DanHickstein** [comment] 2016-01-25 16:22
Thanks for your work on this @stuarteberg!

> Which option would you like me to implement?

Are you asking me? I am basically an amateur at this :)

But here is what I think. One great thing about Anaconda is that it finally brings a working Spyder implementation to the Mac in an easy-to-install way. Spyder is great for everyone, but I think that it's especially nice for users that are new to Python, since it provides a single Matlab-like application where users can edit code, run code, read documentation, and see the values of the variables. So, I would suggest that it works in a way that new users would expect any other application to run. It should have an icon in /Applications/Spyder.app (or, an alias as is done for Launcher.app). Alternatively, it can just live in ~/Anaconda/. But there should be a clickable app.

As far as typing ``spyder`` from the terminal, the main difference between the existing behavior and option #3 (proposed above) would be whether or not Spyder closes when the terminal window that launched the program closes. Currently, Spyder closes when the terminal window closes, a behavior that is consistent with how most terminal-based programs operate, but is probably not desirable for a GUI-based application like Spyder. In general, I think that it's a little bit unusual to be able to launch a normal graphical application from the OSX command line without using the ``open`` command. (I.e., typing ``Safari`` does nothing, you must use ``open /Aplications/Safari.app``.

Anyway, the point is, it would be nice if there was a clickable Spyder app instead of using the command line. If forced to chose, I like the behavior where Spyder does not close if I accidentally close the terminal window that launched it (Option #3).

**Comment by stuarteberg** [comment] 2016-01-25 16:30
>Are you asking me? I am basically an amateur at this

I guess it was intended for anyone with an opinion :-)  But I think @ccordoba12 gets veto-power.

> I like the behavior where Spyder does not close if I accidentally close the terminal window that launched it (Option #3).

I agree, I think option #3 is best.  But I'm not a regular Spyder user, so I might be missing something.

**Comment by DanHickstein** [comment] 2016-11-30 23:36
Did a spyder.app ever get added to Anaconda? I've having another whirl at using Spyder, but the lack of an identifiable icon in the dock makes it difficult to work with...

**Comment by ccordoba12** [comment] 2016-11-30 23:50
Nop, we hope to do it next year.

**Comment by DanHickstein** [comment] 2016-12-01 15:46
Thanks for looking into it! 

...Next year is only 1 month away! :)

**Comment by rantanplan77** [comment] 2017-03-23 14:38
Sorry for bringing this up again. For me, spyder has this generic icon for the app and another "blank page" one for every kernel. So it distracts even more...

**Comment by rantanplan77** [comment] 2017-10-11 09:40
This seems to have been fixed in the meantime - Spyder 3.2.3 via miniconda 4.3.21. Thanks to the anonymous benefactor!

**Closed** 2017-10-11 14:09 UTC

**Comment by rantanplan77** [comment] 2017-11-14 11:05
The issue seems to be somehow connected to the matplotlib backend (In Spyder, `Preferences->IPython Console->Graphics`). If I use `macosx`, I only get one icon. With the `Qt5` backend, I get a "blank page" icon in the dock for every kernel. With `tkinter`, I get a "feather" icon in the dock for every kernel.

Unfortunately, the `macosx` backend has some other [bugs](https://stackoverflow.com/questions/29956681/unable-to-modify-file-name-when-saving-matplotlib-figures-in-mac-system)...
