### ISSUE TITLE
Anaconda navigator 1.1.0 lacks support for high-dpi screens in windows

### ISSUE THREAD

**Issue by efecege** [ContinuumIO/anaconda-issues#754] opened 2016-04-15 04:38 UTC
I'm working on a Dell XPS15 laptop with 4K screen and text/icons in Anaconda Navigator 1.1.0 are extremely small.

**Comment by goanpeca** [comment] 2016-04-15 13:21
Hi @efecege, thanks for reporting. 

We are actively working to fix this in a coming release. 

Remember to search for similar issues before reporting an issue.
Closing this one as it is a duplicate of #742

**Closed by goanpeca** 2016-04-15 13:21 UTC
