### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by avinash13715** [ContinuumIO/anaconda-issues#8892] opened 2018-03-15 10:40 UTC
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
Traceback (most recent call last):
  File "/home/mach/anaconda3/envs/universe/bin/jupyter-lab", line 7, in <module>
    from jupyterlab.labapp import main
  File "/home/mach/anaconda3/envs/universe/lib/python3.5/site-packages/jupyterlab/labapp.py", line 7, in <module>
    from notebook.notebookapp import NotebookApp, aliases, flags
  File "/home/mach/anaconda3/envs/universe/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/mach/anaconda3/envs/universe/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

```
## System information
```
python: 3.5.3
pyqt: 5.6.0
qt: 5.6.2
os: Linux;4.13.0-37-generic;#42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
language: en_IN
conda: 4.4.11
```

**Comment by goanpeca** [comment] 2018-03-15 13:10
Closing as duplicate of #8216

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #8216 for more information on how to fix this issue.**

Or try running

```
conda upgrade jupyter_core
```

**Closed by goanpeca** 2018-03-15 13:10 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by avinash13715** [comment] 2018-03-15 13:40
Thank u
