### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by duartemolha** [ContinuumIO/anaconda-issues#8631] opened 2018-02-21 23:07 UTC
## Main error
Application <b>jupyterlab</b> launch may have produced errors.
## Traceback
```
[I 23:06:40.907 LabApp] [nb_conda_kernels] enabled, 2 kernels found
[I 23:06:40.913 LabApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 23:06:41.609 LabApp] JupyterLab beta preview extension loaded from /home/duartem/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 23:06:41.610 LabApp] JupyterLab application directory is /home/duartem/anaconda3/share/jupyter/lab
No cio_test package found.
[I 23:06:41.891 LabApp] [nb_anacondacloud] enabled
[I 23:06:41.913 LabApp] [nb_conda] enabled
[I 23:06:42.020 LabApp] ✓ nbpresent HTML export ENABLED
[W 23:06:42.020 LabApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 23:06:42.043 LabApp] Serving notebooks from local directory: /home/duartem
[I 23:06:42.043 LabApp] 0 active kernels 
[I 23:06:42.043 LabApp] The Jupyter Notebook is running at: http://localhost:8888/?token=d8019f687b29aeec4c55af19633cb4dc495484cb8e8be721
[I 23:06:42.043 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:06:42.044 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=d8019f687b29aeec4c55af19633cb4dc495484cb8e8be721
[I 23:06:42.515 LabApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[27211:27249:0221/230642.544663:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.

```
## System information
```
python: 3.6.1
language: en_GB
os: Linux;4.13.0-32-generic;#35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018;x86_64;x86_64
version: 1.6.2
platform: linux-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.34
```

**Comment by goanpeca** [comment] 2018-02-21 23:16
Closing as duplicate of #2098

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #2098 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-02-21 23:16 UTC
Labels: pkg:navigator, reso:duplicate
