### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by heesoo25** [ContinuumIO/anaconda-issues#2887] opened 2017-07-06 01:04 UTC
My Python3 was not working on PyCharm (though Python2.7 works just fine on it) even though I have Python 3.5 installed. Since I wish to use Python3, I decided to install Python 3.6 using Anaconda, but I got the following error when I tried to start Navigator after installing it. Perhaps there is issue with multiple versions of Python being installed together?

Navigator Error

`An unexpected error occurred on Navigator start-up`

Main Error

`byte indices must be integers or slices, not str`

Traceback

```
Traceback (most recent call last):
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```

**Comment by goanpeca** [comment] 2017-07-06 01:30
Closing as duplicate of #1837

Please update to the latest version of Navigator.

Open a terminal and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-06 01:30 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by heesoo25** [comment] 2017-07-06 01:54
I did update the anaconda-navigator, and when I typed in 

`$ conda update anaconda-navigator`

I get

```
# All requested packages already installed.
# packages in environment at /home/heesoo/anaconda3:
#
anaconda-navigator        1.6.3                    py36_0 
```

When I launch the Navigator, I still get the error

Main Error

`byte indices must be integers or slices, not str`

Traceback

```
Traceback (most recent call last):
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/heesoo/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```
