### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mzeeqazi** [ContinuumIO/anaconda-issues#8783] opened 2018-03-06 15:31 UTC
#Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

byte indices must be integers or slices, not str

Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment] 2018-03-06 15:34
Closing as duplicate of #1837

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1837 for more information on how to fix this.**

**Closed by goanpeca** 2018-03-06 15:34 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by mzeeqazi** [comment] 2018-03-06 15:38
C:\WINDOWS\system32>conda update conda

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\mzeeqazi\.condarc", position 0

`$ C:\ProgramData\Anaconda3\Scripts\conda update conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                 HOMEPATH=\Users\mzeeqazi
          MOZ_PLUGIN_PATH=D:\PROGRAM FILES (X86)\FOXIT SOFTWARE\FOXIT READER\plugins\
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Oracle\Java\
                          javapath;C:\Program
                          Files\Java\jdk1.8.0_144\bin;C:\Android;C:\Windows\System32;C:\Program
                          Files\MySQL\MySQL Utilities 1.6\;C:\WINDOWS\system32;C:\WINDOWS;C:\WIN
                          DOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Prog
                          ram Files (x86)\GTK2-Runtime\lib;D:\MATLAB7\bin\win32;C:\Users\mzeeqaz
                          i\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS
                          Code\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=D:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\mzeeqazi\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\mzeeqazi\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\mzeeqazi\AppData\Local\conda\conda\envs
                          C:\Users\mzeeqazi\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 110, in main
        from ..activate import main as activator_main
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\mzeeqazi\.condarc", position 0

`$ C:\ProgramData\Anaconda3\Scripts\conda shell.cmd.exe reactivate`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\ProgramData\Anaconda3
                 HOMEPATH=\Users\mzeeqazi
          MOZ_PLUGIN_PATH=D:\PROGRAM FILES (X86)\FOXIT SOFTWARE\FOXIT READER\plugins\
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Oracle\Java\
                          javapath;C:\Program
                          Files\Java\jdk1.8.0_144\bin;C:\Android;C:\Windows\System32;C:\Program
                          Files\MySQL\MySQL Utilities 1.6\;C:\WINDOWS\system32;C:\WINDOWS;C:\WIN
                          DOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Prog
                          ram Files (x86)\GTK2-Runtime\lib;D:\MATLAB7\bin\win32;C:\Users\mzeeqaz
                          i\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS
                          Code\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=D:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\mzeeqazi\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\mzeeqazi\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\mzeeqazi\AppData\Local\conda\conda\envs
                          C:\Users\mzeeqazi\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true


C:\WINDOWS\system32>

**Comment by goanpeca** [comment] 2018-03-06 15:55
You condarc file seems to have an invalid character

Please remove this file

`C:\Users\mzeeqazi\.condarc`

**Comment by iyutpo** [comment] 2019-03-16 20:28
@goanpeca Thank you very much. However, it doesn't work on my laptop. I got:

conda update conda


Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\exceptions.py", line 724, in __call__
        return func(*args, **kwargs)
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\cli\main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\cli\install.py", line 236, in install
        force_reinstall=context.force,
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\core\solve.py", line 504, in solve_for_transaction
        force_remove, force_reinstall)
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\core\solve.py", line 437, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\core\solve.py", line 218, in solve_final_state
        _, inconsistent_dists = r.bad_installed(solution, ())
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\resolve.py", line 718, in bad_installed
        C = r2.gen_clauses()
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\resolve.py", line 505, in gen_clauses
        C.Require(C.Or, nkey, self.push_MatchSpec(C, ms))
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\resolve.py", line 477, in push_MatchSpec
        m = C.from_name(self.push_MatchSpec(C, ms2))
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\resolve.py", line 477, in push_MatchSpec
        m = C.from_name(self.push_MatchSpec(C, ms2))
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\resolve.py", line 477, in push_MatchSpec
        m = C.from_name(self.push_MatchSpec(C, ms2))
      [Previous line repeated 967 more times]
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\resolve.py", line 476, in push_MatchSpec
        ms2 = MatchSpec(track_features=tf) if tf else MatchSpec(nm)
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\models\match_spec.py", line 76, in __call__
        return super(MatchSpecType, cls).__call__(**kwargs)
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\models\match_spec.py", line 178, in __init__
        self._match_components = self._build_components(**kwargs)
      File "D:\LANGUAGE\Anaconda3.5\lib\site-packages\conda\models\match_spec.py", line 363, in _build_components
        return frozendict(_make(key, value) for key, value in iteritems(kwargs))
    RecursionError: maximum recursion depth exceeded

`$ D:\LANGUAGE\Anaconda3.5\Scripts\conda update conda`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=.;%Java_Home%\bin;%Java_Home%\lib\dt.jar;%Java_Home%\lib\tools.jar
        CONDA_DEFAULT_ENV=base
             CONDA_PREFIX=D:\LANGUAGE\Anaconda3.5
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:\LANGUAGE\Anaconda3.5\python.exe
               CONDA_ROOT=D:\LANGUAGE\Anaconda3.5
              CONDA_SHLVL=1
                 HOMEPATH=\Users\Yinghai Yu
MYSQLCONNECTOR_ASSEMBLIESPATH=C:\Program Files (x86)\MySQL\Connector NET 8.0\Assemblies\v4.5.2
                     PATH=D:\LANGUAGE\Anaconda3.5;D:\LANGUAGE\Anaconda3.5\Library\mingw-w64\bin;
                          D:\LANGUAGE\Anaconda3.5\Library\usr\bin;D:\LANGUAGE\Anaconda3.5\Librar
                          y\bin;D:\LANGUAGE\Anaconda3.5\Scripts;D:\LANGUAGE\Anaconda3.5\bin;C:\P
                          rogram Files (x86)\Common Files\Oracle\Java\javapath;D:\LANGUAGE\Oracl
                          e11g\bin;"\bin;\jre\bin;C:\ProgramData\Oracle\Java\javapath";C:\Progra
                          m Files\Microsoft MPI\Bin\;"C:\ProgramData\Oracle\Java\javapath;\bin";
                          "C:;\bin;\jre\bin;\ProgramData\Oracle\Java\javapath";C:\WINDOWS\system
                          32;C:\WINDOWS;"C:\WINDOWS\System32\Wbem;D:\LANGUAGE\Python3.6.4\Script
                          s";C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files\Microsoft SQL
                          Server\130\Tools\Binn\;D:\LANGUAGE\Mingw;D:\LANGUAGE\Python
                          3.6.3;D:\LANGUAGE\Python 3.6.3\Scripts;C:\Program Files\dotnet\;C:\WIN
                          DOWS\System32\Wbem;C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\Java\jre-10.0.1\bin;C:\Program
                          Files\Java\jdk-10.0.1\bin;C:\Program Files\Microsoft VS Code\bin;C:\Wi
                          ndows\System32\curl-7.61.0-win64-mingw\bin;D:\InternetTools\phantomjs-
                          2.1.1-windows\phantomjs-2.1.1-windows\bin;C:\Users\Yinghai
                          Yu\AppData\Local\GitHubDesktop\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : D:\LANGUAGE\Anaconda3.5
            shell level : 1
       user config file : C:\Users\Yinghai Yu\.condarc
 populated config files : C:\Users\Yinghai Yu\.condarc
          conda version : 4.4.6
    conda-build version : 3.2.1
         python version : 3.6.7.final.0
       base environment : D:\LANGUAGE\Anaconda3.5  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : D:\LANGUAGE\Anaconda3.5\pkgs
                          C:\Users\Yinghai Yu\AppData\Local\conda\conda\pkgs
       envs directories : D:\LANGUAGE\Anaconda3.5\envs
                          C:\Users\Yinghai Yu\AppData\Local\conda\conda\envs
                          C:\Users\Yinghai Yu\.conda\envs
               platform : win-64
             user-agent : conda/4.4.6 requests/2.14.2 CPython/3.6.7 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
