### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by Petrichor23** [ContinuumIO/anaconda-issues#12903] opened 2022-04-16 08:32 UTC
When I open the Anaconda Navigator I could launch it and use it. After restarting my computer though I receive this error every time I try to launch Navigator. I have uninstalled and re-installed the software, but receive this error even after re-installing.

Main Error
('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)
Traceback
Traceback (most recent call last):
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/widgets/main_window/__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 94, in __init__
    self.reload_client()
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 325, in reload_client
    client.user()
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/binstar_client/__init__.py", line 242, in user
    self._check_response(res)
  File "/Users/hongmoye/opt/anaconda3/lib/python3.9/site-packages/binstar_client/__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)

**Comment by csoja** [comment] 2022-04-18 15:57
I'm sorry to hear you've run into this.  It seems like it has gotten confused and for some reason is looking for https://api.anaconda.org/user - which doesn't exist. 
Do you know what version of Navigator you have?  
It sounds as if something in the configuration has gotten confused.   My first thought would be to check your .condarc configuration file, the navigator.ini configuration file and anaconda-client/config.yaml configuration file.  I believe the .condarc one would be in your home directory (it may be hidden though depending on your machine settings) - the navigator.ini file will be in the .anaconda directory of your home directory, and the anaconda-client/config.yaml file would be in the .continuum folder of your home directory.  You can often just rename the current version to .old - and then they will be recreated again when you start up Navigator.

**Comment by vshevchenko-anaconda** [comment] 2022-09-09 12:04
Duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/12415

**Closed by vshevchenko-anaconda** 2022-09-09 12:04 UTC
Labels: type-bug, reso-duplicate, pkg-navigator
