### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by arash2060** [ContinuumIO/anaconda-issues#10623] opened 2019-02-13 16:25 UTC
The same issue within on Conda install, requests within Python, pip install ... on my MacBook

## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda-fusion/osx-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),),)

```
## System information
```
python: 3.6.5
language: en
os: Darwin;18.2.0;Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64;x86_64;i386
version: 1.6.2
platform: osx-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.5.11
```

**Comment by goanpeca** [comment] 2019-02-13 16:28
Closing as duplicate of #1932

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1932 for more information on how to fix this.**

**Closed by goanpeca** 2019-02-13 16:28 UTC
Labels: pkg-navigator, reso-duplicate
