### ISSUE TITLE
Navigator Error: byte indices must be integers or slices, not str

### ISSUE THREAD

**Issue by shankarsiddharth** [ContinuumIO/anaconda-issues#3573] opened 2017-07-26 06:15 UTC
# Navigator Error

An unexpected error occurred on Navigator start-up

### Main Error

byte indices must be integers or slices, not str

### Traceback

```
Traceback (most recent call last):
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\<USERNAME>\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str
```

## System Information
*Windows 7 Enterprise Service Pack 1*
*64-bit*
*conda 4.3.21*

**Installer**: Anaconda3-4.4.0-Windows-x86.exe

**Comment by goanpeca** [comment] 2017-07-26 06:15
**See Issue #1837 for more information on how to fix this.**

---

Closing as duplicate of #1837


---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Closed by goanpeca** 2017-07-26 06:15 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by shankarsiddharth** [comment] 2017-07-26 06:31
Updating the `anaconda-navigator` resolves the issue.
