### ISSUE TITLE
Failed to install Jupyter with an error

### ISSUE THREAD

**Issue by masuday** [ContinuumIO/anaconda-issues#10082] opened 2018-09-18 18:35 UTC
### Actual Behavior

Jupyter cannot be installed with an error caused by `ipykernel`. This has been reported at https://github.com/JuliaLang/IJulia.jl/issues/739#issuecomment-422465615.

### Expected Behavior

I expect Jupyter is installed without errors.

### Steps to Reproduce

In Windows 7:

1. Download miniconda installer: https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
2. Run the installer `Miniconda3-latest-Windows-x86_64.exe /S /AddToPath=0 /RegisterPython=0 /D=C:\fresh_miniconda3`
3. Move to the directory: `cd C:\fresh_miniconda3\Scripts`
4. Run `conda config --add channels defaults --force` and `conda update -y conda`
5. Run `conda install -y jupyter` — this produces the error about `ipykernel`

The end of log:

```
m2w64-gmp-6.1.0      | 689 KB    | ######################################################## | 100%
markupsafe-1.0       | 27 KB     | ######################################################## | 100%
ipython-6.5.0        | 1.1 MB    | ######################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::ipykernel
-4.9.0-py37_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.9.0-py37_0
running your command again with `-v` will provide additional information
location of failed script: c:\fresh_miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package defaults::ipykernel-4.9.0-py37_0
running your command again with `-v` will provide additional information
location of failed script: c:\fresh_miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>
```

##### Anaconda or Miniconda version:

Miniconda3 4.5.11 (64-bit)

##### Operating System:

Windows 7

##### `conda info`

```
     active environment : None
       user config file : C:\Users\yutaka\local\.condarc
 populated config files : C:\Users\yutaka\local\.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : c:\fresh_miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : c:\fresh_miniconda3\pkgs
                          C:\Users\yutaka\AppData\Local\conda\conda\pkgs
       envs directories : c:\fresh_miniconda3\envs
                          C:\Users\yutaka\AppData\Local\conda\conda\envs
                          C:\Users\yutaka\local\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`

```
# packages in environment at c:\fresh_miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.8.24                py37_1    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.5.11                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.3.1            py37h74b6da3_0    defaults
idna                      2.7                      py37_0    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
openssl                   1.0.2p               hfa6e2cd_0    defaults
pip                       10.0.1                   py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.18                     py37_1    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.0                hea74fb7_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.19.1                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                40.2.0                   py37_0    defaults
six                       1.11.0                   py37_1    defaults
urllib3                   1.23                     py37_0    defaults
vc                        14                   h0510ff6_3    defaults
vs2015_runtime            14.0.25123                    3    defaults
wheel                     0.31.1                   py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
```

**Comment by tkelman** [comment] 2018-09-18 20:15
Can you open `c:\fresh_miniconda3\Scripts\.ipykernel-post-link.bat` (or c:\fresh_miniconda3\pkgs\*\Scripts\.ipykernel-post-link.bat`) and replace
```
"%PREFIX%\python.exe" -m ipykernel install --sys-prefix > NUL 2>&1 && if errorlevel 1 exit 1
```
with
```
"%PREFIX%\python.exe" -m ipykernel install --sys-prefix 2>&1 && if errorlevel 1 exit 1
```
then re-run `conda install -v -y jupyter` ?

**Comment by masuday** [comment] 2018-09-18 21:00
I change the file `C:\fresh_miniconda3\pkgs\ipykernel-4.9.0-py37_0\Scripts\.ipykernel-post-link.bat` according to your suggestion. I got the same error with the following message.

```
===> LINKING PACKAGE: defaults::ipykernel-4.9.0-py37_0 <===
  prefix=c:\fresh_miniconda3
  source=c:\fresh_miniconda3\pkgs\ipykernel-4.9.0-py37_0


$ C:\Windows\system32\cmd.exe /d /c c:\fresh_miniconda3\Scripts\.ipykernel-post-link.bat
==> cwd: c:\fresh_miniconda3\Scripts <==
==> exit code: 1 <==
==> stdout <==
b'_cffi_ext.c\r\nc:\\fresh_miniconda3\\lib\\site-packages\\zmq\\backend\\cffi\\__pycache__\\_cffi_ex
t.c(213): fatal error C1083: Cannot open include file: \'sys/un.h\': No such file or directory\r\nTr
aceback (most recent call last):\r\n  File "c:\\fresh_miniconda3\\lib\\runpy.py", line 183, in _run_
module_as_main\r\n    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\r\n  File "c:
\\fresh_miniconda3\\lib\\runpy.py", line 142, in _get_module_details\r\n    return _get_module_detai
ls(pkg_main_name, error)\r\n  File "c:\\fresh_miniconda3\\lib\\runpy.py", line 109, in _get_module_d
etails\r\n    __import__(pkg_name)\r\n  File "c:\\fresh_miniconda3\\lib\\site-packages\\ipykernel\\_
_init__.py", line 2, in <module>\r\n    from .connect import *\r\n  File "c:\\fresh_miniconda3\\lib\
\site-packages\\ipykernel\\connect.py", line 18, in <module>\r\n    import jupyter_client\r\n  File
"c:\\fresh_miniconda3\\lib\\site-packages\\jupyter_client\\__init__.py", line 4, in <module>\r\n
from .connect import *\r\n  File "c:\\fresh_miniconda3\\lib\\site-packages\\jupyter_client\\connect.
py", line 23, in <module>\r\n    import zmq\r\n  File "c:\\fresh_miniconda3\\lib\\site-packages\\zmq
\\__init__.py", line 47, in <module>\r\n    from zmq import backend\r\n  File "c:\\fresh_miniconda3\
\lib\\site-packages\\zmq\\backend\\__init__.py", line 40, in <module>\r\n    reraise(*exc_info)\r\n
 File "c:\\fresh_miniconda3\\lib\\site-packages\\zmq\\utils\\sixcerpt.py", line 34, in reraise\r\n
  raise value\r\n  File "c:\\fresh_miniconda3\\lib\\site-packages\\zmq\\backend\\__init__.py", line
27, in <module>\r\n    _ns = select_backend(first)\r\n  File "c:\\fresh_miniconda3\\lib\\site-packag
es\\zmq\\backend\\select.py", line 27, in select_backend\r\n    mod = __import__(name, fromlist=publ
ic_api)\r\n  File "c:\\fresh_miniconda3\\lib\\site-packages\\zmq\\backend\\cython\\__init__.py", lin
e 6, in <module>\r\n    from . import (constants, error, message, context,\r\nImportError: DLL load
failed: The specified module could not be found.\r\n'
==> stderr <==
b''


===> REVERSING PACKAGE LINK: defaults::ipykernel-4.9.0-py37_0 <===
  prefix=c:\fresh_miniconda3


failed
An error occurred while installing package 'defaults::ipykernel-4.9.0-py37_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.9.0-py37_0
running your command again with `-v` will provide additional information
location of failed script: c:\fresh_miniconda3\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.
```

**Comment by tkelman** [comment] 2018-09-18 21:27
Can you post the entire output prior to that? Either here or at gist.github.com and leave a link. There should be a set of pyd files under `C:\fresh_miniconda3\pkgs\pyzmq-*\Lib\site-packages\zmq\backend\cython` but they're failing to import, looks like due to a missing dependency.

**Comment by masuday** [comment] 2018-09-18 22:11
Please see the log: https://gist.github.com/masuday/8215a692014a1457b9b708a4ed3f369e.

**Comment by masuday** [comment] 2018-09-18 22:41
If my memory is correct, the installation of Conda/IJulia was successful just after the solution to make it work in Julia 0.7 on Windows modification https://github.com/JuliaLang/IJulia.jl/issues/693. The solution came 14 days ago (around Sep 4) and the current issue appeared 11 days ago (Sep 7). Anyway I will try an old installer.

**Comment by tkelman** [comment] 2018-09-18 22:46
A few things happened around then - a new version of miniconda3-latest at https://repo.continuum.io/miniconda/ (possibly switching from py36 to py37?), and a new conda package of ipykernel 4.9.0 at https://anaconda.org/anaconda/ipykernel/files

**Comment by mingwandroid** [comment] 2018-09-18 23:16
I believe this is a bug in zeromq, but I don't have any reproducer. I spent a while on it too.

I'm hoping the next zeromq release works better!

**Comment by tkelman** [comment] 2018-09-18 23:45
There hasn't been a new zmq release in a while though has there? What's different about py37 that's triggering it? Is there an env var you can set to make python and/or windows more verbose about module or shared library loading?

**Comment by masuday** [comment] 2018-09-19 03:58
I confirmed that the previous Miniconda3 (4.5.4 64-bit) has no problem in the installation of Jupyter and it perfectly works. The following table shows the difference in packages between 4.5.4 and 4.5.11. You will see two versions have exactly the same package-versions; only the difference is the Python version i.e. 3.6 vs 3.7.

|package name|4.5.4|4.5.11|
|-|-|-|
|Python|3.6|3.7|
|                      appdirs:  |1.4.3-py36h28b3542_0     |1.4.3-py37h28b3542_0     |
|                        attrs:  |18.2.0-py36h28b3542_0    |18.2.0-py37h28b3542_0    |
|                      automat:  |0.7.0-py36_0             |0.7.0-py37_0             |
|                     backcall:  |0.1.0-py36_0             |0.1.0-py37_0             |
|                       bleach:  |2.1.4-py36_0             |2.1.4-py37_0             |
|                     colorama:  |0.3.9-py36h029ae33_0     |0.3.9-py37_0             |
|                   constantly:  |15.1.0-py36h28b3542_0    |15.1.0-py37h28b3542_0    |
|                    decorator:  |4.3.0-py36_0             |4.3.0-py37_0             |
|                  entrypoints:  |0.2.3-py36_2             |0.2.3-py37_2             |
|                     html5lib:  |1.0.1-py36_0             |1.0.1-py37_0             |
|                    hyperlink:  |18.0.0-py36_0            |18.0.0-py37_0            |
|                          icu:  |58.2-ha66f8fd_1          |58.2-ha66f8fd_1          |
|                  incremental:  |17.5.0-py36_0            |17.5.0-py37_0            |
|                    ipykernel:  |4.9.0-py36_0             |4.9.0-py37_0             |
|                      ipython:  |6.5.0-py36_0             |6.5.0-py37_0             |
|             ipython_genutils:  |0.2.0-py36h3c5d0ee_0     |0.2.0-py37_0             |
|                   ipywidgets:  |7.4.1-py36_0             |7.4.1-py37_0             |
|                         jedi:  |0.12.1-py36_0            |0.12.1-py37_0            |
|                       jinja2:  |2.10-py36_0              |2.10-py37_0              |
|                         jpeg:  |9b-hb83a4c4_2            |9b-hb83a4c4_2            |
|                   jsonschema:  |2.6.0-py36h7636477_0     |2.6.0-py37_0             |
|                      jupyter:  |1.0.0-py36_6             |1.0.0-py37_6             |
|               jupyter_client:  |5.2.3-py36_0             |5.2.3-py37_0             |
|              jupyter_console:  |5.2.0-py36_1             |5.2.0-py37_1             |
|                 jupyter_core:  |4.4.0-py36_0             |4.4.0-py37_0             |
|                       libpng:  |1.6.34-h79bbb47_0        |1.6.34-h79bbb47_0        |
|                    libsodium:  |1.0.16-h9d3ae62_0        |1.0.16-h9d3ae62_0        |
|        m2w64-gcc-libgfortran:  |5.3.0-6                  |5.3.0-6                  |
|               m2w64-gcc-libs:  |5.3.0-7                  |5.3.0-7                  |
|          m2w64-gcc-libs-core:  |5.3.0-7                  |5.3.0-7                  |
|                    m2w64-gmp:  |6.1.0-2                  |6.1.0-2                  |
|      m2w64-libwinpthread-git:  |5.0.0.4634.697f757-2     |5.0.0.4634.697f757-2     |
|                   markupsafe:  |1.0-py36hfa6e2cd_1       |1.0-py37hfa6e2cd_1       |
|                      mistune:  |0.8.3-py36hfa6e2cd_1     |0.8.3-py37hfa6e2cd_1     |
|            msys2-conda-epoch:  |20160418-1               |20160418-1               |
|                    nbconvert:  |5.3.1-py36_0             |5.3.1-py37_0             |
|                     nbformat:  |4.4.0-py36h3a5bc1b_0     |4.4.0-py37_0             |
|                     notebook:  |5.6.0-py36_0             |5.6.0-py37_0             |
|                       pandoc:  |2.2.3.2-0                |2.2.3.2-0                |
|                pandocfilters:  |1.4.2-py36_1             |1.4.2-py37_1             |
|                        parso:  |0.3.1-py36_0             |0.3.1-py37_0             |
|                  pickleshare:  |0.7.4-py36h9de030f_0     |0.7.4-py37_0             |
|            prometheus_client:  |0.3.1-py36h28b3542_0     |0.3.1-py37h28b3542_0     |
|               prompt_toolkit:  |1.0.15-py36h60b8f86_0    |1.0.15-py37_0            |
|                       pyasn1:  |0.4.4-py36h28b3542_0     |0.4.4-py37h28b3542_0     |
|               pyasn1-modules:  |0.2.2-py36_0             |0.2.2-py37_0             |
|                     pygments:  |2.2.0-py36hb010967_0     |2.2.0-py37_0             |
|                         pyqt:  |5.9.2-py36ha878b3d_0     |5.9.2-py37ha878b3d_0     |
|              python-dateutil:  |2.7.3-py36_0             |2.7.3-py37_0             |
|                     pywinpty:  |0.5.4-py36_0             |0.5.4-py37_0             |
|                        pyzmq:  |17.1.2-py36hfa6e2cd_0    |17.1.2-py37hfa6e2cd_0    |
|                           qt:  |5.9.6-vc14h62aca36_0     |5.9.6-vc14h62aca36_0     |
|                    qtconsole:  |4.4.1-py36_0             |4.4.1-py37_0             |
|                   send2trash:  |1.5.0-py36_0             |1.5.0-py37_0             |
|             service_identity:  |17.0.0-py36h28b3542_0    |17.0.0-py37h28b3542_0    |
|                simplegeneric:  |0.8.1-py36_2             |0.8.1-py37_2             |
|                          sip:  |4.19.12-py36h6538335_0   |4.19.12-py37h6538335_0   |
|                       sqlite:  |3.24.0-h7602738_0        |3.24.0-h7602738_0        |
|                    terminado:  |0.8.1-py36_1             |0.8.1-py37_1             |
|                     testpath:  |0.3.1-py36h2698cfe_0     |0.3.1-py37_0             |
|                      tornado:  |5.1-py36hfa6e2cd_0       |5.1-py37hfa6e2cd_0       |
|                    traitlets:  |4.3.2-py36h096827d_0     |4.3.2-py37_0             |
|                      twisted:  |18.7.0-py36hfa6e2cd_1    |18.7.0-py37hfa6e2cd_1    |
|                      wcwidth:  |0.1.7-py36h3d5aa90_0     |0.1.7-py37_0             |
|                 webencodings:  |0.5.1-py36_1             |0.5.1-py37_1             |
|           widgetsnbextension:  |3.4.1-py36_0             |3.4.1-py37_0             |
|                       winpty:  |0.4.3-4                  |0.4.3-4                  |
|                       zeromq:  |4.2.5-he025d50_1         |4.2.5-he025d50_1         |
|                         zlib:  |1.2.11-h8395fce_2        |1.2.11-h8395fce_2        |
|                         zope:  |1.0-py36_1               |1.0-py37_1               |
|               zope.interface:  |4.5.0-py36hfa6e2cd_0     |4.5.0-py37hfa6e2cd_0     |

**Comment by mingwandroid** [comment] 2018-09-19 08:14
The previous release fails too sometimes. Seems like a race condition.

It also fails on py 3.6 (that's what's in the previous release).

**Comment by tkelman** [comment] 2018-09-19 12:38
@masuday wasn't this happening preditably for you 100% of the time with py37? "The specified module could not be found" doesn't sound like a race condition to me, it sounds like a mis-built binary that's depending on something that isn't available on the user's system.

**Comment by mingwandroid** [comment] 2018-09-19 12:45
zmq dll fails to initialize and this is the failure mode AFAIR.

**Comment by masuday** [comment] 2018-09-19 14:28
I reproduced this issue on 3 Windows 7/10 PCs whenever I used the latest installer and `conda`, Miniconda3 4.5.11 (64-bit). 

I find this error has been reported at the zeromq/pyzmq forum (https://github.com/zeromq/pyzmq/issues/852) in the previous versions and even in MacOS. In their cases, the problem happens when Jupyter is invoked, not when it is installed. They are using `pip` and show some workaround.

Then I tried `pip install jupyter` instead of `conda` and it works! All the packages are installed without errors. Jupyter runs well with the Python3 kernel. So, the issue seems to be in the packaging in conda.

**Comment by msarahan** [comment] 2018-09-19 14:52
Do you happen to have any zmq DLLs anywhere else on your system?  I don't really think this is the culprit, since the older python version worked for you, but it is worth checking.  The Windows DLL search path is at https://msdn.microsoft.com/en-us/library/7d83bc18.aspx?f=255&MSPPError=-2147217396

According to that, a wheel (where any zmq DLL will be included directly alongside the .pyd) will be less prone to interference from DLLs installed into the Windows system directories than conda (which relies on PATH).

**Comment by mingwandroid** [comment] 2018-09-19 15:06
@msauday, can you explain why you think it same bug! The stack traces are different.

Also why the effort? If the pip one works and ours doesn't that suggests it's an issue that pip doesn't suffer from?

**Comment by masuday** [comment] 2018-09-19 15:56
@mingwandroid There’s a misunderstanding here. I simply tried to show what I observed. But my comment has a casual guess without any deep thinking. The pip thing was just for an additional test; no more than that. I edit my comment just to report the fact I observed.

**Comment by mingwandroid** [comment] 2018-09-19 17:29
Well, hopefully a new zeromq will come along soon and hopefully it'll fix this issue. It's a real pain point.

**Comment by tkelman** [comment] 2018-09-19 17:37
What makes you think it's an initialization problem when it depends on version of python but not version of libzmq, and it happens with conda but not pip?

@masuday https://github.com/zeromq/pyzmq/issues/852 is only related via the `_cffi_ext.c(213): fatal error C1083: Cannot open include file: \'sys/un.h\': No such file or directory` part of the error. If you look at https://github.com/zeromq/pyzmq/blob/64c885e8e36790b45d19429b2695cdb82d658755/zmq/backend/__init__.py#L19, pyzmq has two backends that it tries. For cpython it first tries cython then tries cffi, but for pypy (the subject of that issue) it tries them in the other order. If both fail, it shows the entire backtrace only for the first backend it tries. The fatal error C1083 gets shown even for you using cpython because that's coming from msvc (during the cffi fallback) rather than part of the python backtrace.

I don't think the cffi backend is expected to work with a conda-packaged pyzmq at the moment, the package includes compiled pyd files for the cython backend but they're failing to import in py37.

**Comment by mingwandroid** [comment] 2018-09-19 17:49
> What makes you think it's an initialization problem when it depends on version of python but not version of libzmq, and it happens with conda but not pip?

About 4 mostly fruitless hours debugging it, could've been something else, just that's how it appears. We do build with both backends, but it tries the Cython one first, we could/should disable the other one but it's not actually related to the problem with the Cython one failing (it was just me experimenting).

**Comment by mingwandroid** [comment] 2018-09-19 17:52
As I say, this zeromq thing has been around for ages, mostly in the guise of ipykernel failing to install.

**Comment by tkelman** [comment] 2018-09-19 17:56
I've seen several of the ipykernel post link failures (was hitting the sphinx/jedi one myself), that script does have a way of triggering all sorts of issues which is why I think it should be deleted if at all possible, but I don't recall them having zmq as their root cause. Do you have past issues you can reference that were due to zmq?

**Comment by mingwandroid** [comment] 2018-09-19 18:05
I first saw this when debugging that issue and it did appear to be down to a failure to initialise the zeromq DLL. I saw this from monitoring the output from ProcMon initially.

**Comment by mingwandroid** [comment] 2018-09-19 18:05
Deleting scripts because of other bugs doesn't sound great, it's there for a reason, AFAIK to register it with jupyter?

**Comment by tkelman** [comment] 2018-09-19 18:12
Underlying issues should be fixed whenever possible yes (the underlying cause of that sphinx/jedi one is liable to come back any time something tries to conditionally import what conda might have left as an empty directory, that was also just worked around in jedi's codebase), but see https://github.com/conda-forge/ipykernel-feedstock/blob/c9f1317a4761bd3c456514dcdc2c273238c35c5b/recipe/post-link.bat#L3 - it was done as a post-link script originally to work around a limitation in conda that has since been fixed.

I can also reproduce this myself with a `conda create -v -p C:\code\envs\py37zmq python=3.7 ipykernel`, FWIW

**Comment by tkelman** [comment] 2018-09-19 18:47
Is the environment activated when post-link scripts run? I don't get what would be different about that between py36 and py37, but adding
```
from shutil import copy
copy("C:\\code\\envs\\py37zmq\\Library\\bin\\libzmq-mt-4_2_5.dll", "C:\\code\\envs\\py37zmq\\lib\\site-packages\\zmq\\backend\\cython")
copy("C:\\code\\envs\\py37zmq\\Library\\bin\\libsodium.dll", "C:\\code\\envs\\py37zmq\\lib\\site-packages\\zmq\\backend\\cython")
```
to the top of that https://github.com/zeromq/pyzmq/blob/master/zmq/backend/__init__.py file makes it go through successfully.

**Comment by msarahan** [comment] 2018-09-19 18:51
Very interesting.  That makes sense.  I haven't seen those in procmon - I had hoped to see some (failed) attempt to load them.

I don't think environments are activated for running post-link scripts, but arguably they definitely should be for things like this.  I'll take a look at a temporary workaround until we can get conda to do that.

**Comment by msarahan** [comment] 2018-09-19 19:36
yes, in testing this locally, adding this to the post-link script seems to have helped:

```set "PATH=%PATH%;%PREFIX%\Library\bin"```

We'll issue new packages in a bit.

**Comment by msarahan** [comment] 2018-09-19 20:02
ipykernel 4.9.0 build 1 is available now, and should address this problem.  Thanks @tkelman for your help figuring this out.

Closing this issue, but let me know if it still has problems and I'll reopen.

**Closed by msarahan** 2018-09-19 20:02 UTC

**Comment by tkelman** [comment] 2018-09-19 20:45
Yep, that looks very likely to be the difference. So you might see similar issues pop up elsewhere due to that change.

**Comment by mingwandroid** [comment] 2018-09-19 21:14
This change causes problems for `conda activate`, we could work around them under the knowledge it's running our Python but I feel we should be in a more activated state than we are at this point?

**Comment by mingwandroid** [comment] 2018-09-19 22:47
I believe that software as important as the Python interpreter should not mutate PATH. It rules out a whole range of use cases and introduces surprising results, thanks for getting the workaround applied. @kalefranz, can you comment on this (I agree with it):

> I don't think environments are activated for running post-link scripts, but arguably they definitely should be for things like this.

Should we file a bug report?

**Comment by tkelman** [comment] 2018-09-19 23:07
I agree with that, touching PATH is always bad news. As I added in an edit to my previous comment - it's kind of a messy patch and good to be rid of, but you will start finding places like this one that were depending on it.

**Comment by msarahan** [comment] 2018-09-20 13:30
Filed issue at https://github.com/conda/conda/issues/7789

**Comment by kalefranz** [comment] 2018-09-20 15:11
Using post-link scripts for configuration will always be brittle.  Using post-link scripts for *anything* will always be brittle.  They should be used as a last resort.  An escape hatch for capabilities that conda doesn't have, but are absolutely necessary.  As we see patterns emerge that post-link is being used for, that also don't have an implementation strategy we've already identified as a best practice, we should be coding those capabilities into conda.

For the configuration case, the best practice is using the unix standard of `.d` directories.  If a file is going to be managed by conda (or any other package manager for that matter), a post-link script shouldn't come by and change up the contents.

> I don't think environments are activated for running post-link scripts, but arguably they definitely should be for things like this.

I agree that, when post-links scripts *have* to be used as a last resort, the environment should be activated when they run.  That is, the environment variables should be correctly set for the subprocess.  But what happens if activation has some other side-effect other than just setting environment variables (like @mcg1969 has made the case for in the past)?  That could lead to pretty disastrous situations with poorly written, non-idempotent activate.d scripts.  It might require us pushing through https://github.com/conda/conda/issues/6820 before this is feasible.

**Comment by mcg1969** [comment] 2018-09-20 15:17
I totally agree about the brittleness of post-link scripting. It should be avoided whenever possible. But that said, ultimately I agree that the environment should be activated for a post-link script. If activation fails, then so should post-link scripting. That's just the risk of it.

**Comment by kalefranz** [comment] 2018-09-20 15:57
I guess at some point we should document and enumerate the down-sides of post-link. In addition to just being generally brittle, add

* changing hashes of conda-managed files to the list (so a future `conda doctor` command that checks that an environment is in order would report errors)
* environment clones can’t copy files straight across, but instead have to potentially re-download and then reinstall the package into the new environment

**Comment by tkelman** [comment] 2018-09-20 17:47
With respect to this particular post-link script, I'll reiterate that it's not necessary any more, and the issue with conda not replacing paths in json files was fixed long ago. You'll know better than I exactly how comprehensive to be in testing things out, but the only difference from https://github.com/conda-forge/ipykernel-feedstock/pull/25 that I can tell is getting a slightly different mix of forward vs backslashes in some of the kernel config paths.

**Comment by mingwandroid** [comment] 2018-09-20 21:07
Thanks @tkelman, we'll get round to removing it at some point!
