### ISSUE TITLE
ipykernel error when updating

### ISSUE THREAD

**Issue by ntopi** [ContinuumIO/anaconda-issues#8259] opened 2018-01-24 00:08 UTC
I observed this error while trying to update my packages. Thanks for assisting.
Traceback (most recent call last):
  File "D:\python\lib\site-packages\conda\exceptions.py", line 743, in __call__
    return func(*args, **kwargs)
  File "D:\python\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "D:\python\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "D:\python\lib\site-packages\conda\cli\main_update.py", line 14, in execute
    install(args, parser, 'update')
  File "D:\python\lib\site-packages\conda\cli\install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "D:\python\lib\site-packages\conda\cli\install.py", line 285, in handle_txn
    unlink_link_transaction.execute()
  File "D:\python\lib\site-packages\conda\core\link.py", line 225, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "D:\python\lib\site-packages\conda\core\link.py", line 500, in _execute
    rollback_excs,
CondaMultiError: post-link script failed for package defaults::ipykernel-4.8.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: D:\python\envs\py36\Scripts\.ipykernel-post-link.bat

Insufficient permissions to write menu folder.  Falling back to user location
WARNING menuinst_win32:__init__(194): Insufficient permissions to write menu folder.  Falling back to user location
DEBUG menuinst_win32:create(299): Shortcut cmd is D:\python\pythonw.exe, args are [u'D:\\python\\cwp.py', u'D:\\python\\envs\\py36', u'D:\\python\\envs\\py36\\pythonw.exe', u'D:\\python\\envs\\py36\\Scripts\\anaconda-navigator-script.py']
- DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\python\envs\py36', env_name: 'py36', mode: 'None', used_mode: 'system'
Insufficient permissions to write menu folder.  Falling back to user location
WARNING menuinst_win32:__init__(194): Insufficient permissions to write menu folder.  Falling back to user location
DEBUG menuinst_win32:create(299): Shortcut cmd is D:\python\pythonw.exe, args are [u'D:\\python\\cwp.py', u'D:\\python\\envs\\py36', u'D:\\python\\envs\\py36\\pythonw.exe', u'D:\\python\\envs\\py36\\Scripts\\anaconda-navigator-script.py']
failed

**Comment by mingwandroid** [comment] 2018-01-24 00:32
Closing as a duplicate of https://github.com/ContinuumIO/anaconda-issues/issues/8087

If you can provide the info I've asked for over there then please do so, otherwise one of the most recent comments suggests a workaround of first updating `conda` then `ipykernel`.

**Closed by mingwandroid** 2018-01-24 00:32 UTC
