### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by telferm57** [ContinuumIO/anaconda-issues#8490] opened 2018-02-09 09:12 UTC
## Main error
The following errors occurred:
## Traceback
```
PackageNotFoundError: Packages missing in current channels:
            
  - rstudio ==1.0.153

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
            
```
## System information
```
python: 3.6.1
language: en_GB
os: Windows;10;10.0.16299;AMD64;Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.33
```

**Comment by telferm57** [comment] 2018-02-09 09:15
attempting to install rstudio - created separate environment, upgraded conda .. which got downgraded 

conda: 4.4.7-py36_0 --> 4.3.33-py36_0 conda-forge

tried to install rstudio froom navigator with new env selected , got above msg

**Comment by goanpeca** [comment] 2018-02-09 11:18
@telferm57 you are mixing conda-fore and defaults channels which are not compatible.

Please remove conda-forge channel and run:

Closing as duplicate of #6970

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

---

**See issue #6970 for more information on how to fix this issue.**

**Closed by goanpeca** 2018-02-09 11:18 UTC
