### ISSUE TITLE
Navigator Error when I tried to install python 2.7 enviorment from anaconda - how do I get around my company's firewall ? 

### ISSUE THREAD

**Issue by seanliu333** [ContinuumIO/anaconda-issues#8477] opened 2018-02-08 19:01 UTC
## Main error
The following errors occurred:
## Traceback
```
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /anaconda-fusion/win-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))",),)

```
## System information
```
python: 3.6.1
language: en_US
os: Windows;7;6.1.7601;AMD64;Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
version: 1.6.2
platform: win-64
qt: 5.6.2
pyqt: 5.6.0
conda: 4.3.21
```

**Comment by goanpeca** [comment] 2018-02-08 19:06
Closing as duplicate of #1932

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update conda
$ conda update anaconda-navigator
$ conda update navigator-updater
```

---

**See Issue #1932 for more information on how to fix this.**

**Closed by goanpeca** 2018-02-08 19:06 UTC
Labels: pkg:navigator, reso:duplicate

**Comment by seanliu333** [comment] 2018-02-08 19:12
Tried to update but there is a proxy error (could be due to my company's fire wall)

(C:\Users\liuxia\AppData\Local\Continuum\Anaconda3) C:\Users\liuxia>conda update
 conda
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusi
on/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=44
3): Max retries exceeded with url: /anaconda-fusion/win-64/repodata.json (Caused
 by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 40
7 Proxy Authentication Required',)))",),)
