### ISSUE TITLE
Not able to install anything becouse of libarchive "ModuleNotFoundError".

### ISSUE THREAD

**Issue by vgthengane** [ContinuumIO/anaconda-issues#11104] opened 2019-07-10 04:12 UTC
Previously I was able to install packages using `conda install packege_name` command. But after updating the anaconda it started getting an error for every package. Even I can't able to get the `conda info` now. 

##### `conda info`

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/home/vishal/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
    ModuleNotFoundError: No module named 'libarchive'

`$ /home/vishal/anaconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

```

</details>

##### `conda list --show-channel-urls`

```
Traceback (most recent call last):
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1043, in __call__
    return func(*args, **kwargs)
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/home/vishal/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 14, in <module>
    from ..core.prefix_data import PrefixData
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 24, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 17, in <module>
    import conda_package_handling.api
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
ModuleNotFoundError: No module named 'libarchive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vishal/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/home/vishal/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
ModuleNotFoundError: No module named 'libarchive'

```
Please help me with this I don't wanna create all environment again. 

Thanks!

**Comment by msarahan** [comment] 2019-07-11 01:02
fundamentally, there's something wrong with libarchive.  As a hack, what you could do is:

1. install miniconda to a separate folder.  Tell it not to run `conda init`
2. activate that installation with `source /path/to/new/miniconda/bin/activate`
3. run `conda install -p /path/to/broken/anaconda --force python-libarchive-c conda-package-handling libarchive

now open up a new terminal, and hopefully your old installation will work again.

**Comment by earlev4** [comment] 2019-07-12 18:21
Hi Mike,

Good day! I greatly appreciate all you and Anaconda, Inc. do. As an individual user (and not part of an enterprise), I would certainly be interested in contributing through a service such as Patreon.  I was experiencing the same error issue as Vishal. The hack that you provided resolved the issue. However, when performing the `conda update --all`, I encounter a new issue:

```
> conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::anaconda==custom=py37_0
- 
Warning: >10 possible package resolutions (only showing differing packages):
  - r::r-base64enc-0.1_3-r351h96ca727_4, r::r-htmltools-0.3.6-r351h29659fb_0, r::r-magrittr-1.5-r351h6115d3f_4, r::r-stringr-1.3.1-r351h6115d3f_0
  - defaults::r-magrittr-1.5-r351h6115d3f_4, r::r-base64enc-0.1_3-r351h96ca727_4, r::r-htmltools-0.3.6-r351h29659fb_0, r::r-stringr-1.3.1-r351h6115d3f_0
  - defaults::r-base64enc-0.1_3-r351h96ca727_4, r::r-htmltools-0.3.6-r351h29659fb_0, r::r-magrittr-1.5-r351h6115d3f_4, r::r-stringr-1.3.1-r351h6115d3f_0
  - defaults::r-base64enc-0.1_3-r351h96ca727_4, defaults::r-magrittr-1.5-r351h6115d3f_4, r::r-htmltools-0.3.6-r351h29659fb_0, r::r-stringr-1.3.1-r351h6115d3f_0
  - defaults::r-base64enc-0.1_3-r351h96ca727_4, defaults::r-htmltools-0.3.6-r351h29659fb_0, r::r-magrittr-1.5-r351h6115d3f_4, r::r-stringr-1.3.1-r351h6115d3f_0
  - defaults::r-base64enc-0.1_3-r351h96ca727_4, defaults::r-htmltools-0.3.6-r351h29659fb_0, defaults::r-magrittr-1.5-r351h6115d3f_4, r::r-stringr-1.3.1-r351h6115d3f_0
  - defaults::r-htmltools-0.3.6-r351h29659fb_0, r::r-base64enc-0.1_3-r351h96ca727_4, r::r-magrittr-1.5-r351h6115d3f_4, r::r-stringr-1.3.1-r351h6115d3f_0
  - defaults::r-htmltools-0.3.6-r351h29659fb_0, defaults::r-magrittr-1.5-r351h6115d3f_4, r::r-base64enc-0.1_3-r351h96ca727_4, r::r-stringr-1.3.1-r351h6115d3f_0
  - defaults::r-htmltools-0.3.6-r351h29659fb_0, defaults::r-stringr-1.3.1-r351h6115d3f_0, r::r-base64enc-0.1_3-r351h96ca727_4, r::r-magrittr-1.5-r351h6115d3f_4
  - defaults::r-stringr-1.3.1-r351h6115d3f_0, r::r-base64enc-0.1_3-r351h96ca727_4, r::r-htmltools-0.3.6-r351h29659fb_0, r::r-magrittr-1.5-r351h6115d3f_4
  ... and othedone

## Package Plan ##

  environment location: /home/earle/anaconda3


The following NEW packages will be INSTALLED:

  _anaconda_depends  pkgs/main/linux-64::_anaconda_depends-2019.03-py37_0
  alabaster          pkgs/main/linux-64::alabaster-0.7.12-py37_0
  anaconda-project   pkgs/main/noarch::anaconda-project-0.8.3-py_0
  astroid            pkgs/main/linux-64::astroid-2.2.5-py37_0
  astropy            pkgs/main/linux-64::astropy-3.2.1-py37h7b6447c_0
  babel              pkgs/main/noarch::babel-2.7.0-py_0
  backports          pkgs/main/noarch::backports-1.0-py_2
  backports.os       pkgs/main/linux-64::backports.os-0.1.1-py37_0
  backports.shutil_~ pkgs/main/linux-64::backports.shutil_get_terminal_size-1.0.0-py37_2
  bitarray           pkgs/main/linux-64::bitarray-0.9.3-py37h7b6447c_0
  bkcharts           pkgs/main/linux-64::bkcharts-0.2-py37_0
  blosc              pkgs/main/linux-64::blosc-1.16.3-hd408876_0
  bokeh              pkgs/main/linux-64::bokeh-1.2.0-py37_0
  boto               pkgs/main/linux-64::boto-2.49.0-py37_0
  bottleneck         pkgs/main/linux-64::bottleneck-1.2.1-py37h035aef0_1
  click              pkgs/main/linux-64::click-7.0-py37_0
  cloudpickle        pkgs/main/noarch::cloudpickle-1.2.1-py_0
  colorama           pkgs/main/linux-64::colorama-0.4.1-py37_0
  contextlib2        pkgs/main/linux-64::contextlib2-0.5.5-py37_0
  cython             pkgs/main/linux-64::cython-0.29.11-py37he6710b0_0
  cytoolz            pkgs/main/linux-64::cytoolz-0.9.0.1-py37h14c3975_1
  dask               pkgs/main/noarch::dask-2.1.0-py_0
  dask-core          pkgs/main/noarch::dask-core-2.1.0-py_0
  distributed        pkgs/main/noarch::distributed-2.1.0-py_0
  docutils           pkgs/main/linux-64::docutils-0.14-py37_0
  et_xmlfile         pkgs/main/linux-64::et_xmlfile-1.0.1-py37_0
  fastcache          pkgs/main/linux-64::fastcache-1.1.0-py37h7b6447c_0
  flask              pkgs/main/linux-64::flask-1.0.3-py37_0
  get_terminal_size  pkgs/main/linux-64::get_terminal_size-1.0.0-haa9412d_0
  gevent             pkgs/main/linux-64::gevent-1.4.0-py37h7b6447c_0
  gmpy2              pkgs/main/linux-64::gmpy2-2.0.8-py37h10f8cd9_2
  greenlet           pkgs/main/linux-64::greenlet-0.4.15-py37h7b6447c_0
  h5py               pkgs/main/linux-64::h5py-2.9.0-py37h7918eee_0
  hdf5               pkgs/main/linux-64::hdf5-1.10.4-hb1b8bf9_0
  heapdict           pkgs/main/linux-64::heapdict-1.0.0-py37_2
  html5lib           pkgs/main/linux-64::html5lib-1.0.1-py37_0
  imageio            pkgs/main/linux-64::imageio-2.5.0-py37_0
  imagesize          pkgs/main/linux-64::imagesize-1.1.0-py37_0
  ipython            pkgs/main/linux-64::ipython-7.6.1-py37h39e3cac_0
  isort              pkgs/main/linux-64::isort-4.3.21-py37_0
  itsdangerous       pkgs/main/linux-64::itsdangerous-1.1.0-py37_0
  jbig               pkgs/main/linux-64::jbig-2.1-hdba287a_0
  jdcal              pkgs/main/noarch::jdcal-1.4.1-py_0
  jeepney            pkgs/main/linux-64::jeepney-0.4-py37_0
  joblib             pkgs/main/linux-64::joblib-0.13.2-py37_0
  jupyter            pkgs/main/linux-64::jupyter-1.0.0-py37_7
  jupyter_console    pkgs/main/linux-64::jupyter_console-6.0.0-py37_0
  keyring            pkgs/main/linux-64::keyring-18.0.0-py37_0
  lazy-object-proxy  pkgs/main/linux-64::lazy-object-proxy-1.4.1-py37h7b6447c_0
  libtool            pkgs/main/linux-64::libtool-2.4.6-h7b6447c_5
  libxslt            pkgs/main/linux-64::libxslt-1.1.33-h7d1a2b0_0
  llvmlite           pkgs/main/linux-64::llvmlite-0.29.0-py37hd408876_0
  locket             pkgs/main/linux-64::locket-0.2.0-py37_1
  lxml               pkgs/main/linux-64::lxml-4.3.4-py37hefd8a0e_0
  mccabe             pkgs/main/linux-64::mccabe-0.6.1-py37_1
  mkl-service        pkgs/main/linux-64::mkl-service-2.0.2-py37h7b6447c_0
  mock               pkgs/main/linux-64::mock-3.0.5-py37_0
  mpc                pkgs/main/linux-64::mpc-1.1.0-h10f8cd9_1
  mpfr               pkgs/main/linux-64::mpfr-4.0.1-hdf1c602_3
  mpmath             pkgs/main/linux-64::mpmath-1.1.0-py37_0
  msgpack-python     pkgs/main/linux-64::msgpack-python-0.6.1-py37hfd86e86_1
  multipledispatch   pkgs/main/linux-64::multipledispatch-0.6.0-py37_0
  networkx           pkgs/main/noarch::networkx-2.3-py_0
  nltk               pkgs/main/linux-64::nltk-3.4.3-py37_0
  nose               pkgs/main/linux-64::nose-1.3.7-py37_2
  numba              pkgs/main/linux-64::numba-0.44.1-py37h962f231_0
  numexpr            pkgs/main/linux-64::numexpr-2.6.9-py37h9e4a6bb_0
  numpydoc           pkgs/main/noarch::numpydoc-0.9.1-py_0
  openpyxl           pkgs/main/noarch::openpyxl-2.6.2-py_0
  partd              pkgs/main/noarch::partd-1.0.0-py_0
  path.py            pkgs/main/noarch::path.py-12.0.1-py_0
  pathlib2           pkgs/main/linux-64::pathlib2-2.3.4-py37_0
  patsy              pkgs/main/linux-64::patsy-0.5.1-py37_0
  pep8               pkgs/main/linux-64::pep8-1.7.1-py37_0
  ply                pkgs/main/linux-64::ply-3.11-py37_0
  pycodestyle        pkgs/main/linux-64::pycodestyle-2.5.0-py37_0
  pycrypto           pkgs/main/linux-64::pycrypto-2.6.1-py37h14c3975_9
  pycurl             pkgs/main/linux-64::pycurl-7.43.0.3-py37h1ba5d50_0
  pyflakes           pkgs/main/linux-64::pyflakes-2.1.1-py37_0
  pylint             pkgs/main/linux-64::pylint-2.3.1-py37_0
  pyodbc             pkgs/main/linux-64::pyodbc-4.0.26-py37he6710b0_0
  pytables           pkgs/main/linux-64::pytables-3.5.2-py37h71ec239_1
  pytest-arraydiff   pkgs/main/linux-64::pytest-arraydiff-0.3-py37h39e3cac_0
  pytest-astropy     pkgs/main/linux-64::pytest-astropy-0.5.0-py37_0
  pytest-doctestplus pkgs/main/linux-64::pytest-doctestplus-0.3.0-py37_0
  pytest-openfiles   pkgs/main/linux-64::pytest-openfiles-0.3.2-py37_0
  pytest-remotedata  pkgs/main/linux-64::pytest-remotedata-0.3.1-py37_0
  pywavelets         pkgs/main/linux-64::pywavelets-1.0.3-py37hdd07704_1
  qtawesome          pkgs/main/linux-64::qtawesome-0.5.7-py37_1
  qtconsole          pkgs/main/noarch::qtconsole-4.5.1-py_0
  rope               pkgs/main/noarch::rope-0.14.0-py_0
  scikit-image       pkgs/main/linux-64::scikit-image-0.15.0-py37he6710b0_0
  scikit-learn       pkgs/main/linux-64::scikit-learn-0.21.2-py37hd81dba3_0
  scipy              pkgs/main/linux-64::scipy-1.2.1-py37h7c811a0_0
  seaborn            pkgs/main/linux-64::seaborn-0.9.0-py37_0
  secretstorage      pkgs/main/linux-64::secretstorage-3.1.1-py37_0
  simplegeneric      pkgs/main/linux-64::simplegeneric-0.8.1-py37_2
  singledispatch     pkgs/main/linux-64::singledispatch-3.4.0.3-py37_0
  snappy             pkgs/main/linux-64::snappy-1.1.7-hbae5bb6_3
  snowballstemmer    pkgs/main/noarch::snowballstemmer-1.9.0-py_0
  sortedcollections  pkgs/main/linux-64::sortedcollections-1.1.2-py37_0
  sortedcontainers   pkgs/main/linux-64::sortedcontainers-2.1.0-py37_0
  sphinx             pkgs/main/noarch::sphinx-2.1.2-py_0
  sphinxcontrib      pkgs/main/linux-64::sphinxcontrib-1.0-py37_1
  sphinxcontrib-app~ pkgs/main/noarch::sphinxcontrib-applehelp-1.0.1-py_0
  sphinxcontrib-dev~ pkgs/main/noarch::sphinxcontrib-devhelp-1.0.1-py_0
  sphinxcontrib-htm~ pkgs/main/noarch::sphinxcontrib-htmlhelp-1.0.2-py_0
  sphinxcontrib-jsm~ pkgs/main/noarch::sphinxcontrib-jsmath-1.0.1-py_0
  sphinxcontrib-qth~ pkgs/main/noarch::sphinxcontrib-qthelp-1.0.2-py_0
  sphinxcontrib-ser~ pkgs/main/noarch::sphinxcontrib-serializinghtml-1.1.3-py_0
  sphinxcontrib-web~ pkgs/main/noarch::sphinxcontrib-websupport-1.1.2-py_0
  spyder             pkgs/main/linux-64::spyder-3.3.5-py37_0
  spyder-kernels     pkgs/main/linux-64::spyder-kernels-0.5.0-py37_0
  sqlalchemy         pkgs/main/linux-64::sqlalchemy-1.3.5-py37h7b6447c_0
  statsmodels        pkgs/main/linux-64::statsmodels-0.10.0-py37hdd07704_0
  sympy              pkgs/main/linux-64::sympy-1.4-py37_0
  tblib              pkgs/main/noarch::tblib-1.4.0-py_0
  toolz              pkgs/main/linux-64::toolz-0.9.0-py37_0
  unicodecsv         pkgs/main/linux-64::unicodecsv-0.14.1-py37_0
  unixodbc           pkgs/main/linux-64::unixodbc-2.3.7-h14c3975_0
  werkzeug           pkgs/main/noarch::werkzeug-0.15.4-py_0
  wrapt              pkgs/main/linux-64::wrapt-1.11.2-py37h7b6447c_0
  wurlitzer          pkgs/main/linux-64::wurlitzer-1.0.2-py37_0
  xlrd               pkgs/main/linux-64::xlrd-1.2.0-py37_0
  xlsxwriter         pkgs/main/noarch::xlsxwriter-1.1.8-py_0
  xlwt               pkgs/main/linux-64::xlwt-1.3.0-py37_0
  zict               pkgs/main/noarch::zict-1.0.0-py_0

The following packages will be UPDATED:

  conda-build                                 3.18.5-py37_0 --> 3.18.7-py37_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(637): An error occurred while installing package 'None'.
AssertionError()
Attempting to roll back.

Rolling back transaction: done

AssertionError()
()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
AssertionError()
```

Here is my system information:
```
> conda info

     active environment : None
       user config file : /home/earle/.condarc
 populated config files : /home/earle/.condarc
          conda version : 4.7.5
    conda-build version : 3.18.5
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/earle/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/earle/anaconda3/pkgs
                          /home/earle/.conda/pkgs
       envs directories : /home/earle/anaconda3/envs
                          /home/earle/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-54-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

I also tried `conda update conda` and experienced similar results. 

Any assistance would be greatly appreciated.

Thanks so much!

**Comment by earlev4** [comment] 2019-07-12 19:12
Good day! I tried using `conda install` _package with the inconsistency_ but decided to add the conda-forge repo. After adding the conda-forge repo, `conda update --all`, and updating the packages, my environment appears to be consistent.

```
> conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

Thanks so much!

**Comment by vishalthengane** [comment] 2019-07-16 03:37
Hi @msarahan, 

The hack is worked. Thank you so much!

**Comment by Julie420** [comment] 2019-07-23 16:41
@msarahan  Thanks for the hack.  I met the same issue and able to fix it with your hack.  Is there a final solution? The conda looks broken after upgrading from 4.6 to 4.7.  And after fixing the issue with the hack, whenever I try to update a package, it will show "The environment is inconsistent, please check the package plan carefully, The following packages are causing the inconsistency:...."  Thanks.

**Comment by muhlbach** [comment] 2019-07-25 20:42
> fundamentally, there's something wrong with libarchive. As a hack, what you could do is:
> 
> 1. install miniconda to a separate folder.  Tell it not to run `conda init`
> 2. activate that installation with `source /path/to/new/miniconda/bin/activate`
> 3. run `conda install -p /path/to/broken/anaconda --force python-libarchive-c conda-package-handling libarchive`
> 
> now open up a new terminal, and hopefully your old installation will work again.

Do you mind specifying step 1?

**Comment by wzj42** [comment] 2019-07-26 22:35
> > fundamentally, there's something wrong with libarchive. As a hack, what you could do is:
> > 
> > 1. install miniconda to a separate folder.  Tell it not to run `conda init`
> > 2. activate that installation with `source /path/to/new/miniconda/bin/activate`
> > 3. run `conda install -p /path/to/broken/anaconda --force python-libarchive-c conda-package-handling libarchive`
> > 
> > now open up a new terminal, and hopefully your old installation will work again.
> 
> Do you mind specifying step 1?

Just the same way as you installed miniconda/anaconda before. But during installation, make sure it will be installed in a **different directory**. (it might still share some config file such as "$HOME/.condarc" from your old conda) 
https://docs.conda.io/en/latest/miniconda.html

Since you only need it to effect once, so remember not to initialize it so it wouldn't modify your system file (such as ".bashrc"). Activate it manually as step2. 
Before step3, you could test things like "which conda", "conda info", "echo $PATH" to confirm miniconda working.

**Comment by muhlbach** [comment] 2019-07-26 22:38
> > > fundamentally, there's something wrong with libarchive. As a hack, what you could do is:
> > > 
> > > 1. install miniconda to a separate folder.  Tell it not to run `conda init`
> > > 2. activate that installation with `source /path/to/new/miniconda/bin/activate`
> > > 3. run `conda install -p /path/to/broken/anaconda --force python-libarchive-c conda-package-handling libarchive`
> > > 
> > > now open up a new terminal, and hopefully your old installation will work again.
> > 
> > 
> > Do you mind specifying step 1?
> 
> Just the same way as you installed miniconda/anaconda before. But during installation, make sure it will be installed in a **different directory**. (it might still share some config file such as "$HOME/.condarc" from your old conda)
> https://docs.conda.io/en/latest/miniconda.html
> 
> Since you only need it to effect once, so remember not to initialize it so it wouldn't modify your system file (such as ".bashrc"). Activate it manually as step2.
> Before step3, you could test things like "which conda", "conda info", "echo $PATH" to confirm miniconda working.

Thank you, I got it now! Are you guys working on updating conda such that this problem with libarchice disappears?

**Comment by msarahan** [comment] 2019-07-26 22:44
Anaconda 2019.07 is released and has a known good libarchive. Miniconda will be it Monday. We're not sure why updates continue to have issues, but we'll keep looking.

**Comment by muhlbach** [comment] 2019-07-26 22:50
Thank you @msarahan. Would you recommend me to uninstall my current version of Anaconda inorder to install Anaconda 2019.07? If not, should I do the "hack" in order to fix libarchive or can I install Anaconda 2019.07 otherwise?

**Comment by msarahan** [comment] 2019-07-26 23:05
It's totally up to you. If you have lots of extra stuff that will be
annoying to reinstall, try to fix it. If not, reinstall.

Note that you can back up your envs folder, and if you reinstall anaconda
to the same location and move your backup envs folder back, all the envs
will still work.

**Comment by ronanpaixao** [comment] 2019-08-01 03:56
It is strange that such an ugly bug has not been fixed nor reverted yet. I just ran `conda update conda` and it tried updating the whole environment, failed miserably and got me into this libarchive error. This sounds lousy as more and more people are hit by this bug as they try to upgrade. If it is hard to fix, maybe Anaconda should consider reverting it until then.

**Comment by Hadrien-lcrx** [comment] 2019-08-06 07:57
I needed to update Scipy from 1.1.0 to 1.3.0 to get rid of a warning with Seaborn. Updating with Conda gave the error highlighted in this issue. Any `conda` command would then give this error. I had to uninstall and re-install to solve the issue and update Scipy automatically.

**Comment by LuposX** [comment] 2019-08-18 18:00
the hack helped a lot thanks msarahan

**Comment by sanjeed5** [comment] 2019-09-14 20:09
> > > > fundamentally, there's something wrong with libarchive. As a hack, what you could do is:
> > > > 
> > > > 1. install miniconda to a separate folder.  Tell it not to run `conda init`
> > > > 2. activate that installation with `source /path/to/new/miniconda/bin/activate`
> > > > 3. run `conda install -p /path/to/broken/anaconda --force python-libarchive-c conda-package-handling libarchive`
> > > > 
> > > > now open up a new terminal, and hopefully your old installation will work again.
> > > 
> > > 
> > > Do you mind specifying step 1?
> > 
> > 
> > Just the same way as you installed miniconda/anaconda before. But during installation, make sure it will be installed in a **different directory**. (it might still share some config file such as "$HOME/.condarc" from your old conda)
> > https://docs.conda.io/en/latest/miniconda.html
> > Since you only need it to effect once, so remember not to initialize it so it wouldn't modify your system file (such as ".bashrc"). Activate it manually as step2.
> > Before step3, you could test things like "which conda", "conda info", "echo $PATH" to confirm miniconda working.
> 
> Thank you, I got it now! Are you guys working on updating conda such that this problem with libarchice disappears?



> fundamentally, there's something wrong with libarchive. As a hack, what you could do is:
> 
> 1. install miniconda to a separate folder.  Tell it not to run `conda init`
> 2. activate that installation with `source /path/to/new/miniconda/bin/activate`
> 3. run `conda install -p /path/to/broken/anaconda --force python-libarchive-c conda-package-handling libarchive`
> 
> now open up a new terminal, and hopefully your old installation will work again.

Thank you so much!
Life saver!!!

**Comment by clsx524** [comment] 2019-10-16 06:43
I figured out the issue is somehow I have both anaconda installed at ~/ananconda3 and ~/opt/ananconda3 and zshrc references the former which is an old installation. After I deleted the whole old directory, the issue is gone.

**Comment by StevenLi-DS** [comment] 2019-10-27 02:43
@wzj42 Sorry buddy. I still can't fix the issue. I don't understand how you not run `conda init` and activate it manually.

**Closed** 2022-01-10 12:20 UTC
