### ISSUE TITLE
Navigator Launch Error

### ISSUE THREAD

**Issue by nevadarain** [ContinuumIO/anaconda-issues#3925] opened 2017-08-04 23:04 UTC
I just installed Anaconda 4.4.0 and it seems to install, but when i double click to launch the Anaconda Navigator i get the following error message which pops up in my web browser:

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

string indices must be integers, not str

Traceback

Traceback (most recent call last):
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 115, in start_app
    window = run_app(splash)
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "C:\Users\Rashad Powell\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

Your help will be much appreciated.  Thank you

**Comment by goanpeca** [comment] 2017-08-05 01:03
**See issue #1837 for more information on how to fix this issue.**

---

Closing as duplicate of #1837.

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
$ conda update anaconda-navigator
```

**Comment by nevadarain** [comment] 2017-08-05 03:21
Im confused, nothing in issue #1837 talks about the solution

**Comment by solunter** [comment] 2017-08-05 13:23
I got the exact same issue!!!But, it works fine if I start from terminal with command
`$ anaconda-navigator`
even error messages followed:
`<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 111] Connection refused>
<urlopen error [Errno 111] Connection refused>
libpng warning: iCCP: known incorrect sRGB profile

<urlopen error [Errno 111] Connection refused>
`
so, is that ok or not?

**Comment by nevadarain** [comment] 2017-08-05 18:14
i guess Im not going to get any assistance on this issue.  Oh well. Im not gonna stress myself over it.   I just wont use anaconda by contiuum

**Comment by Satheesh-Rajkamal** [comment] 2017-08-09 04:28
I also having the same error...don't how to solve this issue

**Comment by goanpeca** [comment] 2017-08-10 17:02
@mingwandroid do you think that this issue appearing quite often now, is due to menuinst not doing something it should?

**Comment by themantalope** [comment] 2017-09-05 04:11
I am also experiencing the same error. I am running anaconda-navigator on Ubuntu 16.04. When launching navigator from the command line using the `anaconda-navigator`, it works fine. However when I launch by clicking on the app icon I get the following error:

```

Navigator Error

An unexpected error occurred on Navigator start-up
Report

Please report this issue in the anaconda issue tracker
Main Error

string indices must be integers, not str

Traceback

Traceback (most recent call last):
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 115, in start_app
    window = run_app(splash)
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/start.py", line 58, in run_app
    window = MainWindow(splash=splash)
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/widgets/main_window.py", line 160, in __init__
    self.api = AnacondaAPI()
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 65, in __init__
    self._conda_api = CondaAPI()
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 1622, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 340, in __init__
    self.set_conda_prefix()
  File "/home/matt/anaconda2/lib/python2.7/site-packages/anaconda_navigator/api/conda_api.py", line 489, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str

```

**Comment by goanpeca** [comment] 2017-09-05 16:09
@themantalope we do not provide (yet) icons for launching Navigator on linux systems, so I am not aware what you are using to launch it.

On linux the CLI should be used.

**Comment by genvir** [comment] 2017-09-24 23:10
You need to add anaconda path to PATH environment variable to root user

just edit environment file in /etc/environment

sudo cat "PATH=/home/your user/anaconda3/bin:$PATH" >>/etc/environment

then restart your computer and bingo it works

**Comment by themantalope** [comment] 2017-09-24 23:27
@genvir That worked perfectly! Thanks for letting me know. I'm curious though why `root` needs the path to anaconda and not just my user?

**Closed** 2017-11-14 21:00 UTC
Labels: pending:feedback

**Comment by Yiman-GO** [comment] 2017-12-12 08:07
@solunter If you still have the problem: '[Errno 111] Connection refused'. I suggest you try the following:
1: $ export | grep "proxy"
2: $ export | grep "PROXY"
3: if you get things like "declare -x http_proxy="http://127.0.0.1:43241/"",  $ unset http_proxy. Replace 'http_proxy' if you get others.

**Comment by gavinbai** [comment] 2018-11-09 09:20
> I got the exact same issue!!!But, it works fine if I start from terminal with command
> `$ anaconda-navigator`
> even error messages followed:
> `<urlopen error [Errno 111] Connection refused> <urlopen error [Errno 111] Connection refused> <urlopen error [Errno 111] Connection refused> <urlopen error [Errno 111] Connection refused> <urlopen error [Errno 111] Connection refused> <urlopen error [Errno 111] Connection refused> <urlopen error [Errno 111] Connection refused> libpng warning: iCCP: known incorrect sRGB profile <urlopen error [Errno 111] Connection refused> `
> so, is that ok or not?

i  have the same error,dou you solve it?
