### ISSUE TITLE
gfortran_linux-64 7.2.0 missing finclude files

### ISSUE THREAD

**Issue by bartnijssen** [ContinuumIO/anaconda-issues#8423] opened 2018-02-03 18:39 UTC
### Actual Behavior

After installing the `gfortran_linux-64` package from `defaults`, code that requires 

`USE,intrinsic :: ieee_arithmetic    ! IEEE arithmetic`

fails to build with `ieee_arithmetic.mod not found` message

### Expected Behavior

Successful compilation: which requires the `/opt/conda/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/finclude` directory, which is missing. This directory should contain (based on a listing using a non-conda gfortran distribution):

```finclude/
    ieee_arithmetic.mod 
    ieee_exceptions.mod
    ieee_features.mod   
    omp_lib.f90
    omp_lib.h
    omp_lib.mod
    omp_lib_kinds.mod
    openacc.f90
    openacc.mod
    openacc_lib.h
    openacc_kinds.mod                            
```
### Steps to Reproduce

Compile code that requires ieee_arithmetic.mod.
Checking for completeness simply requires

`ls /opt/conda/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/finclude`

##### Anaconda or Miniconda version:
conda 4.3.33

##### Operating System:
Linux ce4f19c13f84 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

condaforge/linux-anvil docker image

##### `conda info`

```
Current conda install:

               platform : linux-64
          conda version : 4.3.33
       conda is private : False
      conda-env version : 4.3.33
    conda-build version : 2.1.18
         python version : 3.6.4.final.0
       requests version : 2.18.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/conda/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.33 requests/2.18.4 CPython/3.6.4 Linux/4.9.60-linuxkit-aufs CentOS/6.9 glibc/2.12    
                UID:GID : 9001:9001

```

##### `conda list --show-channel-urls`

```
# packages in environment at /opt/conda:
#
anaconda-client           1.6.5                      py_0    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
binutils_impl_linux-64    2.28.1               h04c84fa_2    defaults
binutils_linux-64         7.2.0                        25    defaults
ca-certificates           2017.11.5                     0    conda-forge
certifi                   2017.11.5                py36_0    conda-forge
cffi                      1.11.2                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
conda                     4.3.33                   py36_0    conda-forge
conda-build               2.1.18                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
cryptography              2.1.4                    py36_0    conda-forge
curl                      7.55.1                        0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
expat                     2.2.5                         0    conda-forge
filelock                  2.0.6                    py36_0    conda-forge
gcc_impl_linux-64         7.2.0                hc5ce805_2    defaults
gcc_linux-64              7.2.0                        25    defaults
gfortran_impl_linux-64    7.2.0                hb3c8cce_2    defaults
gfortran_linux-64         7.2.0                        25    defaults
git                       2.14.2                        3    conda-forge
gosu                      1.10                          0    conda-forge
idna                      2.6                      py36_1    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.14.2                        0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libiconv                  1.15                          0    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
markupsafe                1.0                      py36_0    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
openssl                   1.0.2n                        0    conda-forge
packaging                 16.8                     py36_0    conda-forge
patchelf                  0.9                           2    conda-forge
pip                       9.0.1                    py36_1    conda-forge
pkginfo                   1.4.1                    py36_0    conda-forge
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pyopenssl                 17.4.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.4                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
setuptools                38.4.0                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tini                      0.16.1                        0    conda-forge
tk                        8.6.7                         0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
wheel                     0.30.0                   py36_2    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

```

**Comment by ericmjonas** [comment] 2018-04-23 04:47
I also ran into this today, is there any planned resolution? Currently this means that for a lot of applications this package is simply broken. In my case, I spent an entire afternoon trying to find ` omp_lib.mod`

**Comment by msarahan** [comment] 2018-08-10 21:48
Duplicate of https://github.com/AnacondaRecipes/aggregate/issues/66 - closing to consolidate discussion there.

Work is being done at https://github.com/AnacondaRecipes/aggregate/pull/76 to fix this.  Preview packages are up on the c3i_test2 channel (linux-64 only so far).

**Closed by msarahan** 2018-08-10 21:48 UTC
